:sourcesdir: ../../../../../source

[[managed_beans_creation]]
===== Creating a Bean

[TIP]
====
Learn https://www.cuba-platform.com/guides/create-business-logic-in-cuba#client_tier_beans[Create Business Logic in CUBA] guide, which shows how to put business logic as a Spring bean.
====

To create a Spring bean, add the `@org.springframework.stereotype.Component` annotation to the Java class. For example:
[source, java]
----
include::{sourcesdir}/common/managedbean_1.java[]
----

It is recommended to assign a unique name to the bean in the `++{project_name}_{class_name}++` form and to define it in the `NAME` constant.

[TIP]
====
The `@javax.annotation.ManagedBean` can also be used for the bean definition, but it can cause problems when deploying the application into some application servers. Therefore we recommend to use only `@Component` annotation from Spring Framework.
====

The bean class should be placed inside the package tree with the root specified in the `context:component-scan` element of the <<spring.xml,spring.xml>> file. For the bean in the example above, the `spring.xml` file should contain the element:

[source, xml]
----
include::{sourcesdir}/common/managedbean_2.xml[]
----

which means that the search for annotated beans for this application block will be performed starting with the `com.sample.sales` package.

Spring beans can be created on any application <<app_tiers,tier>>.

