:sourcesdir: ../../../../source

[[app_components_dev]]
==== Создание компонентов приложения

В этом разделе описаны рекомендации по созданию компонентов приложения с целью повторного использования.

[[app_components_dev_naming]]
Правила именования::
+
--
. Имя корневого пакета должно следовать нотации reverse-DNS, например, `com.jupiter.amazingsearch`.
+
Имя корневого пакета не должно начинаться с имени любого другого компонента или приложения. К примеру, если корневой пакет вашего приложения `com.jupiter.tickets`, вы НЕ можете использовать пакет `com.jupiter.tickets.amazingsearch` для компонента. Это обусловлено тем, что Spring сканирует classpath бинов, начиная с указанного корневого пакета, и это сканирование должно быть уникальным для всех компонентов.

. Пространство имён используется в качестве префикса таблиц в базе данных, поэтому для публичных компонентов оно должно быть составным, к примеру, `jptams`, а не просто `search`. Это минимизирует риск совпадения имён между компонентов и конечным приложением. В пространстве имён запрещено использовать нижние подчёркивания и дефисы, только буквы и цифры.

. Значение Module prefix должно повторять пространство имён, но может при этом содержать дефисы, например, `jpt-amsearch`.

. Используйте namespace в качестве префикса имён бинов и свойств приложения, например:
+
[source, java]
----
@Component("jptams_Finder")
@Property("jptams.ignoreCase")
----
--

[[app_components_dev_install_local]]
Установка в локальный Maven-репозиторий::
+
--
Чтобы сделать компонент доступным для использования в проектах, расположенных на том же компьютере, установите его в локальный репозиторий Maven, выполнив команду *CUBA > Advanced > Install app component* в меню Studio. Данная команда просто запускает задачу Gradle `install` после остановки демонов Gradle.
--

[[app_components_dev_upload]]
Загрузка в удалённый Maven-репозиторий::
+
--
. Создайте репозиторий, следуя инструкции в разделе <<private_repo>>.

. Укажите репозиторий и данные для входа в настройках вашего проекта вместо стандартного репозитория CUBA.

. Откройте файл `build.gradle` проекта компонента на редактирование и добавьте секцию `uploadRepository` в секцию `cuba`:
+
[source,groovy]
----
include::{sourcesdir}/development/app_comp_upload_1.groovy[]
----

. Откройте проект компонента в Studio.

. Выполните задачу Gradle `uploadArchives` из командной строки. Артефакты компонента будут загружены в ваш репозиторий.

. Удалите артефакты проекта из локального Maven-репозитория, чтобы убедиться, что они будут загружены из удалённого репозитория при следующей сборке проекта приложения. Для этого просто удалите папку `.m2/repository/com/company` из домашнего каталога пользователя.

. Теперь при сборке и запуске приложения, использующего этот компонент, он будет скачиваться из удалённого репозитория.
--

[[app_components_dev_upload_bintray]]
Загрузка в Bintray::
+
--
. Зарегистрируйтесь на https://bintray.com/signup/oss
+
[TIP]
====
Для входа на Bintray можно использовать social login (через GitHub, Gmail или Twitter), однако позже вам потребуется выполнить сброс пароля, так как для получения API-ключа (см.ниже) понадобится пароль от учетной записи.
====

. Запомните своё имя пользователя Bintray. Его можно взять из URL, который открывается после логина на Bintray. К примеру, в `\https://bintray.com/vividphoenix` именем пользователя будет `vividphoenix`.

. Получите свой API key. Его можно найти через интерфейс Bintray в настройках профиля. В разделе API-key вам потребуется ввести пароль от учетной записи, чтобы ключ высветился. Используйте ключ и имя пользователя для авторизации с помощью плагина:
+
** Вы можете создать для авторизации переменные окружения:
+
[source, plain]
----
BINTRAY_USER=your_bintray_user
BINTRAY_API_KEY=9696c1cb90752357ded8fdf20eb3fa921bf9dbbb
----
+
** Вместо переменных окружения можно использовать эти параметры в явном виде в файле `build.gradle`:
+
[source, plain]
----
bintray {
user = 'bintray_user'
key = 'bintray_api_key'
...
}
----
+
** Как вариант, можно передать параметры доступа Bintray в командной строке:
+
[source, plain]
----
./gradlew clean assemble bintrayUpload -Pcuba.artifact.version=1.0.0 -PbintrayUser=your_bintray_user -PbintrayApiKey=9696c1cb90752357ded8fdf20eb3fa921bf9dbbb
----

. Создайте публичный репозиторий с типом _Maven_. При создании open source (OSS) репозитория обязательно нужно указать тип лицензии.
+
Структура Bintray предполагает использование пакетов (packages) внутри репозиториев. На данном этапе создавать пакет необязательно, так как он будет создан автоматически в ходе задания `gradle bintrayUpload`.

. Добавьте зависимость для плагина загрузки Bintray в файл `build.gradle`:
+
[source, groovy]
----
include::{sourcesdir}/development/bintray_plugin.groovy[]
----

. В конце скрипта `build.gradle` укажите настройки для плагина Bintray:
+
[source, groovy]
----
include::{sourcesdir}/development/bintray_plugin_settings.groovy[]
----
+
** здесь, `pkg:repo` - ваш репозиторий (используйте `main`),
** `pkg:name` - имя пакета (используйте ваше уникальное имя, например, `amazingsearch`),
** `pkg:desc` - необязательное описание пакета, которое будет отображаться в интерфейсе Bintray,
** `pkg:userOrg` - имя организации, к которой должен относиться репозиторий (если не задано, по умолчанию будет использоваться значение `BINTRAY_USER`).

. Теперь вы можете собрать и загрузить проект, используя следующую команду:
+
[source, plain]
----
./gradlew clean assemble bintrayUpload -Pcuba.artifact.version=1.0.0
----

. Если вы публикуете аддон в маркетплейс CUBA, его репозиторий будет привязан к стандартным репозиториям CUBA, и пользователям не придётся дополнительно настраивать репозитории в своих проектах.
--

