:sourcesdir: ../../../../source

[[app_components_usage]]
==== Использование публичных аддонов

Аддоны, доступные на маркетплейсе CUBA, можно добавить к приложению одним из способов, описанных ниже. Первый и второй способы подразумевают, что в приложении настроен доступ к одному из <<access_to_repo,стандартных репозиториев CUBA>>. Третий подход применим к аддонам с открытым исходным кодом и не требует подключения к какому-либо удалённому репозиторию.

[[app_components_usage_by_studio]]
Подключение из Studio::
+
--
Если вы используете CUBA Studio 11+, управляйте аддонами в окне **CUBA Add-Ons**, как это описано в {studio_man_url}/#add_ons[документации по Studio].

Для предыдущих версий CUBA Studio выполните следующие действия:

. Откройте экран *Project properties* и на панели *App components* нажмите на кнопку со знаком плюс рядом с *Custom components*.

. Скопируйте координаты аддона из маркетплейса или документации к аддону и вставьте их в поле координат компонента, например:
+
[source, plain]
----
com.haulmont.addon.cubajm:cuba-jm-global:0.3.1
----

. Нажмите *OK* в диалоговом окне. Studio попытается найти бинарные артефакты аддона в репозитории, используемом в проекте в настоящий момент. Если они найдены, диалоговое окно закроется, и аддон появится в списке собственных компонентов.

. Сохраните изменения в свойствах проекта нажатием *OK*.
--

[[app_components_usage_manual_edit]]
Добавление вручную::
+
--
. Откройте файл `build.gradle` на редактирование и добавьте координаты аддона в секцию `dependencies`:
+
[source, groovy]
----
dependencies {
    appComponent("com.haulmont.cuba:cuba-global:$cubaVersion")
    // your add-ons go here
    appComponent("com.haulmont.addon.cubajm:cuba-jm-global:0.3.1")
}
----

. Выполните команду `gradlew idea` из командной строки, чтобы добавить аддон к окружению проекта.

. Добавьте в файлы `web.xml` модулей `core` и `web` идентификатор аддона (он совпадает с Maven groupId) в параметр контекста `appComponents` к списку компонентов приложения, разделённому пробелами:
+
[source, xml]
----
<context-param>
    <param-name>appComponents</param-name>
    <param-value>com.haulmont.cuba com.haulmont.addon.cubajm</param-value>
</context-param>
----
--

[[app_components_usage_from_sources]]
Сборка из исходников::
+
--
. Склонируйте репозиторий аддона в локальный каталог и откройте проект аддона в Studio.

. Выполните команду *CUBA > Advanced > Install app component* в главном меню Studio, чтобы установить аддон в локальный репозиторий Maven (по умолчанию это каталог `~/.m2`).

. Откройте основной проект в Studio и добавьте локальный репозиторий Maven к списку используемых репозиториев в экране настроек проекта *Project properties*.

. На панели *App components* нажмите на кнопку со знаком плюс рядом с *Custom components* и выберите установленный аддон в выпадающем списке внизу диалога. Координаты аддона появятся в верхнем поле.

. Нажмите *OK* в диалоге и сохраните изменения.
--

