:sourcesdir: ../../../../../source

[[transaction_listeners]]
===== Transaction Listeners

Transaction listeners предназначены для реакции на события жизненного цикла транзакций. В отличие от <<entity_listeners,entity listeners>>, они не привязаны к типу сущности и вызываются для каждой транзакции.

Слушатель должен быть <<managed_beans,управляемым бином>>, реализующим один или оба интерфейса `BeforeCommitTransactionListener` и `AfterCompleteTransactionListener`.

BeforeCommitTransactionListener::
+
--
Метод `beforeCommit()` вызывается перед коммитом транзакции после всех <<entity_listeners,entity listeners>> если транзакция не является read-only. Метод принимает текущий `EntityManager` и коллекцию сущностей текущего персистентного контекста.

Данный слушатель можно использовать для обеспечения сложных бизнес-правил, вовлекающих различные сущности. В примере ниже атрибут `amount` сущности `Order` должен рассчитываться на основе значения `discount`, находящегося в заказе, и атрибутов `price` и `quantity` экземпляров сущности `OrderLine`, составляющих заказ.

[source,java]
----
include::{sourcesdir}/middleware/tx_listener_1.java[]
----
--

AfterCompleteTransactionListener::
+
--
Метод `afterComplete()` вызывается после завершения транзакции. Метод принимает параметр, указывающий, была ли транзакция успешно закоммичена, и коллекцию detached сущностей, содержавшихся в персистентном контексте завершенной транзакции.

Пример использования:

[source,java]
----
include::{sourcesdir}/middleware/tx_listener_2.java[]
----
--

