:sourcesdir: ../../../../../source

[[transaction_params]]
===== Параметры транзакций

[[transaction_timeout]]
Таймаут транзакции::
+
--
Для создаваемой транзакции может быть указан таймаут в секундах, при превышении которого транзакция будет прервана и откачена. Таймаут транзакции ограничивает максимальную длительность запросов к базе данных.

При программном управлении транзакциями таймаут включается путем передачи объекта `TransactionParams` в метод `Persistence.createTransaction()`. Например:

[source, java]
----
include::{sourcesdir}/middleware/transactions_6.java[]
----

При декларативном управлении транзакциями используется параметр `timeout` аннотации `@Transactional`, например:

[source, java]
----
include::{sourcesdir}/middleware/transactions_7.java[]
----

Таймаут по умолчанию может быть задан в свойстве приложения <<cuba.defaultQueryTimeoutSec,cuba.defaultQueryTimeoutSec>>.
--

[[transaction_read_only]]
Read-only транзации::
+
--
Транзакцию можно пометить как read-only если она предназначена только для чтения данных из БД. Например, все методы `load` в <<dataManager,DataManager>> используют read-only транзакции по умолчанию. Read-only транзакции улучшают производительность системы, потому что платформа не выполняет код, обрабатывающий возможные изменения в сущностях. Кроме того, не вызываются `BeforeCommit` <<transaction_listeners,transaction listeners>>.

[WARNING]
====
Если персистентный контекст read-only транзакции содержит измененные сущности, то при попытке коммита транзакции будет выброшено исключение `IllegalStateException`. Это означает, что помечать транзакцию как read-only следует только если вы уверены, что она не модифицирует никакие сущности.
====

При программном управлении транзакциями признак read-only включается путем передачи объекта `TransactionParams` в метод `Persistence.createTransaction()`. Например:

[source, java]
----
include::{sourcesdir}/middleware/transactions_8.java[]
----

При декларативном управлении транзакциями используется параметр `readOnly` аннотации `@Transactional`, например:

[source, java]
----
include::{sourcesdir}/middleware/transactions_9.java[]
----
--

