:sourcesdir: ../../../../../source

[[jespa_conf]]
===== Setting Up Configuration

* Follow the steps described in *Installation* -> *Step 1: Create the Computer Account for NETLOGON Communication* of the *Jespa Operator's Manual*, which is available at link:$$http://www.ioplex.com/support.html$$[http://www.ioplex.com/support.html].

* Set domain parameters in the `activeDirectory.domains` property in the <<app_properties_files,local.app.properties>> file. Each domain descriptor should have the following format: `++domain_name|full_domain_name|service_account_name|service_account_password++`. Domain descriptors are separated by semicolons.
+
Example:
+
[source, properties]
----
activeDirectory.domains = MYCOMPANY|mycompany.com|JESPA$@MYCOMPANY.COM|password1;TEST|test.com|JESPA$@TEST.COM|password2
----

* Enable the Active Directory integration by setting the `activeDirectory.integrationEnabled` property in the `local.app.properties` file:
+
[source, properties]
----
activeDirectory.integrationEnabled = true
----

* Configure additional Jespa properties in the `local.app.properties` file (see *Jespa Operator's Manual*). For example:
+
[source, properties]
----
jespa.log.level=3
----
+
If the application is deployed to Tomcat, Jespa log file can be found in `tomcat/logs`.

* Add the server address to the local intranet in the browser settings:

** For *Internet Explorer* and *Chrome*: *Settings* > *Security* > *Local intranet* > *Sites* > *Advanced*

** For *Firefox*: `about:config` > `network.automatic-ntlm-auth.trusted-uris=http://myapp.mycompany.com`.

* Create a user with a domain account in the application.
