:sourcesdir: ../../../../../source

[[file_download]]
===== Downloading Files

Files can be downloaded from the file storage to the user's computer by using the `ExportDisplay` interface. It can be obtained by calling the `AppConfig.createExportDisplay()` static method or via <<screen_controller_injection,injection>> in the controller class. For example:

[source, java]
----
AppConfig.createExportDisplay(this).show(fileDescriptor);
----

The `show()` method accepts an optional `ExportFormat` type parameter, which defines the type of the content and the file extension. If the format has not been provided, the extension is retrieved from the `FileDescriptor`, and the content type is set to `application/octet-stream`.

The file extension defines whether the file is downloaded via the browser's standard open/save dialog (`Content-Disposition = attachment`), or if the browser will attempt to show the file in the browser window (`Content-Disposition = inline`). The list of extensions for files that should be shown in the browser window is defined by the <<cuba.web.viewFileExtensions,cuba.web.viewFileExtensions>> application property.

`ExportDisplay` also enables downloading of arbitrary data if `ByteArrayDataProvider` is used as a parameter of the `show()` method. For example:

[source, java]
----
include::{sourcesdir}/features/exportDisplay_1.java[]
----

