:sourcesdir: ../../../../source

[[roles_example]]
==== Настройка ролей

Рекомендованный способ настройки <<roles,ролей>> и <<permissions,разрешений>>:

. Создать роль `*Default*`, отбирающую все права в системе. Проще всего это сделать, установив тип роли *Denying*. Включить флажок *Default role*, чтобы эта роль автоматически назначалась всем новым пользователям.

. Создать набор ролей, дающих нужные права различным категориям пользователей. Можно предложить две стратегии создания таких ролей:

* Крупнозернистые (coarse-grained) роли - каждая роль содержит набор разрешений для всего круга обязанностей пользователя в системе. Например `*Sales Manager*`, `*Accountant*`. В этом случае пользователям в дополнение к запрещающей `*Default*` роли необходимо назначить как правило только одну разрешающую роль.

* Мелкозернистые (fine-grained) роли - каждая роль содержит небольшой набор разрешений для выполнения пользователем некоторой функции в системе. Например `*Task Creator*`, `*References Editor*`. В этом случае пользователям в дополнение к запрещающей `*Default*` роли необходимо назначить несколько разрешающих ролей в соответствии с кругом их обязанностей.
+
Разумеется, ничто не мешает совмещать обе стратегии.

. Администратору системы можно просто не назначать никаких ролей вообще, тогда у него будут все права на все объекты системы. Пользователя с запрещающими ролями можно сделать администратором, добавив ему роль типа *Super*.

