:sourcesdir: ../../../../../source

[[config_interfaces]]
===== Configuration Interfaces

The configuration interfaces mechanism enables working with application properties using Java interface methods, providing the following benefits:

* Typed access – application code works with actual data types (String, Boolean, Integer etc.).
* Instead of string property identifiers, the application code uses interface methods, which are checked by the compiler and you can use code completion when working in an IDE.

Example of reading the transaction timeout value in the Middleware block:

[source, java]
----
include::{sourcesdir}/common/configinterface_1.java[]
----

If injection is impossible, the configuration interface reference can be obtained via the <<configuration,Configuration>> infrastructure interface:

[source, java]
----
include::{sourcesdir}/common/configinterface_2.java[]
----

[WARNING]
====
Configuration interfaces are not regular Spring managed beans. They can only be obtained through explicit interface injection or via `Configuration.getConfig()` but not through `AppBeans.get()`.
====

include::config_interfaces/config_interface_usage.adoc[]

include::config_interfaces/config_interface_property_types.adoc[]

include::config_interfaces/config_interface_default_values.adoc[]

