:sourcesdir: ../../../../../source

[[deployment]]
==== Настройки развёртывания

Специальные экраны редакторов Studio помогут вам настроить задачи Gradle для сборки артефактов развёртывания. Эти редакторы можно открыть из главного меню *CUBA > Deployment* или по двойному клику на элементе дерева *Project > Deployment*.

Редактор *WAR Settings* позволяет настроить сборку WAR файлов. После завершения настройки в файле `build.gradle` будет автоматически создана задача {main_man_url}/build.gradle_buildWar.html[buildWar].

* *Build WAR* - установка этого флажка создаст задачу `buildWar` в файле `build.gradle`.

* *Include JDBC driver* - определяет, нужно ли включать в WAR-файл драйвер JDBC.

* *Include Tomcat's context.xml* - определяет, нужно ли включать в WAR-файл конфигурационный файл `context.xml` (дескриптор развёртывания Tomcat).

* *Custom context.xml path* - путь к дескриптору развёртывания Tomcat `context.xml` относительно корневого каталога приложения. Поле доступно, если установлен флажок *Include Tomcat's context.xml*. Нажмите *Generate*, чтобы создать этот файл автоматически.

* *Single WAR for Middleware and Web Client* - определяет, нужно ли объединять блоки приложения Middleware и Web Client в один единый WAR-файл.

* *Custom web.xml path* - файл, который будет использован в качестве собственного `web.xml` единого WAR-файла. Нажмите *Generate*, чтобы создать этот файл автоматически.

* *Logback configuration file* - путь к конфигурационному файлу `logback.xml` относительно корневого каталога приложения. Нажмите *Generate*, чтобы создать этот файл автоматически.

* *App properties* - набор свойств приложения, имеющих отношение к этому развёртыванию. Свойства будут добавлены в файл `/WEB-INF/local.app.properties` внутри WAR.

Редактор *UberJAR Settings* позволяет настроить сборку Uber JAR. После завершения настройки в файле `build.gradle` будет автоматически создана задача {main_man_url}/build.gradle_buildUberJar.html[buildUberJar].

* *Build Uber JAR* - установка этого флажка создаст задачу `buildUberJar` в файле `build.gradle`.

* *Single Uber JAR* - если флажок установлен, задача `buildUberJar` создаст единый Uber JAR для всех модулей проекта.

* *Logback configuration file* - путь к конфигурационному файлу `logback.xml` относительно корневого каталога приложения. Нажмите *Generate*, чтобы создать этот файл автоматически.

* *Custom Jetty environment file* - путь к конфигурационному файлу `jetty-env.xml` относительно корневого каталога приложения. Этот файл будет использоваться встроенным сервером Jetty. Поле обязательно к заполнению. Нажмите *Generate*, чтобы создать этот файл автоматически.

* *App properties* - набор свойств приложения, имеющих отношение к этому развёртыванию. Свойства будут добавлены в файл `/WEB-INF/local.app.properties` внутри Uber JARs.

* В полях *Core port, Web port, Portal port* можно настроить порты встроенных серверов для соответствующих блоков приложения. Поле недоступно, если выбрана опция  Single Uber JAR. Значения портов по умолчанию описаны в {main_man_url}/build.gradle_buildUberJar.html[основном руководстве]. Кроме того, порты можно указать в качестве аргументов при запуске JAR из командной строки с помощью команды `-port`.
