:sourcesdir: ../../../../../source

[[project_properties]]
==== Редактор свойств проекта

Окно *Project Properties* позволяет настроить конфигурацию конкретного проекта. Окно редактора свойств можно открыть из главного меню *CUBA* или двойным кликом по элементу дерева *Project > Properties*.

Вкладка Main::
+
--
На вкладке *Main* располагаются основные настройки проекта.

* Поле *Repositories* отображает список репозиториев, используемых в текущем проекте. Studio сканирует эти репозитории и выводит доступные в них версии платформы. Чтобы настроить доступ к репозиторию, используйте кнопки рядом с полем. Более подробно о настройках доступа смотрите в {main_man_url}/access_to_repo.html[документации]. Также вы можете вручную настроить доступ к любому количеству дополнительных репозиториев, содержащих компоненты приложения, зарегистрировав их в файле `build.gradle`.

* В поле *Platform version* можно выбрать желаемую версию платформы. При выборе более новой версии Studio при необходимости осуществит автоматическую миграцию проекта.

* В панели *App components* можно добавить как готовые дополнения, поставляемые с платформой, так и свои собственные компоненты приложения, чтобы использовать их в текущем проекте.

* Если необходимо изменить путь к серверу приложений, укажите новый путь в поле *Tomcat path*. При следующем вызове команды `gradlew deploy` или `gradlew start` сервер Tomcat будет установлен в указанный каталог.

* Группа полей *Tomcat ports* позволяет указать нестандартные порты для сервера приложений Tomcat, установленного в каталог `deploy/tomcat` в результате {main_man_url}/fast_deployment.html[быстрого развёртывания] приложения.

* В частности, поле *HTTP port* определяет порт, который сервер Tomcat слушает для установки HTTP-соединения, аналогично свойствам приложения `cuba.webPort`, `cuba.webAppUrl`, `cuba.restApiUrl` и `cuba.connectionUrlList`.

* В поле *AJP port* можно указать порт AJP-коннектора.

* Поле *Shutdown port* позволяет задать порт, на котором Tomcat будет отслеживать команду SHUTDOWN.

* Поле *Debug port* определяет порт, который сервер Tomcat слушает для подключения к отладчику (debugger) Java. После изменения этого порта необходимо также изменить его в настройках отладчика в IDE.

* В поле *Available locales* вы можете указать {main_man_url}/localization.html[локали], используемые в приложении. Откройте редактор локалей, нажав на кнопку рядом с полем. Флажок *Locale select visible* в окне редактора управляет свойством приложения {main_man_url}/app_properties_reference.html#cuba.localeSelectVisible[cuba.localeSelectVisible]. В редакторе также можно определить и переопределить формат строк для {main_man_url}/datatype.html[распознавания и форматирования дат].

* Флажок *Groovy support* позволяет использовать код Groovy в приложении: например, в классах контроллеров экранов.
--

Вкладка Data Stores::
+
--
На вкладке *Data Stores* отображается настройки подключения вашего проекта к одной или нескольким базам данных.

* В верхней части редактора расположены настройки основного хранилища данных проекта.

** Тип сервера базы данных можно выбрать в поле *Database type*. В полях ниже вы можете настроить URL подключения к базе данных, указать имя пользователя, пароль и дополнительные параметры подключения.

** Формат параметров подключения зависит от типа выбранной СУБД. Строка параметров должна содержать разделитель между именем базы данных и непосредственно параметрами. К примеру, чтобы указать имя экземпляра Microsoft SQL Server 2008+, нужно ввести в поле следующую строку:
+
[source]
----
;instanceName=myinstance
----

** Нестандартный URL подключения к БД можно указать в случае, если установлен флажок *Custom database URL*. В этом случае необходимо также указать значения *Host* и *Database*, так как в скрипте `build.gradle` эти значения используются по отдельности.

** Если выбрана HSQLDB, Studio сама обеспечит создание и подключение к БД. Созданные файлы БД будут сохранены в каталог `build/hsqldb`.

* Панель *Additional data stores* содержит список дополнительных хранилищ данных, к которым подключен проект. При создании и редактировании дополнительного хранилища открывается диалоговое окно *Data Store*, которое содержит следующие поля:

** *Data store name* - имя хранилища данных. Может содержать только буквенно-числовые символы и нижние подчеркивания, а также должно отличаться от имени проекта.

** *Data store type* - тип хранилища: `RdbmsStore` или `Custom`, более подробно см. в основном Руководстве. В случае, если выбран тип `RdbmsStore`, необходимо также заполнить следующие поля, описанные ниже.

** *DataSource JNDI name* - устанавливается автоматически в Studio на основе имени хранилища.

** *Database type*, *URL*, и т.д. - параметры подключения к БД.
--