[appendix]
[[app_properties]]
== Application Properties

This section describes the application properties related to the report generator in the alphabetical order.

[[cuba.reporting.displayDeviceUnavailable]]
cuba.reporting.displayDeviceUnavailable:: 

Allows running OpenOffice/LibreOffice in the server operating system without a window interface.
+
Default value: `false`
+
Used in the *Middleware* block.

[[cuba.reporting.fontsDir]]
cuba.reporting.fontsDir:: 

Path to the fonts directory for converting HTML to PDF.
+
For example: `cuba.reporting.fontsDir = C:/Windows/Fonts`.
+
Used in the *Middleware* block.

[[cuba.reporting.openoffice.docx.useOfficeForPdfConversion]]
cuba.reporting.openoffice.docx.useOfficeForPdfConversion:: 

Turns on using OpenOffice to convert the report having DOCX template to PDF, which significantly increases the conversion accuracy.
+
Default value: `false`
+
Used in the *Middleware* block.

[[cuba.reporting.openoffice.path]]
cuba.reporting.openoffice.path:: 

Sets the path to OpenOffice.
+
Default value: `/`
+
Used in the *Middleware* block.

[[cuba.reporting.putEmptyRowIfNoDataSelected]]
cuba.reporting.putEmptyRowIfNoDataSelected:: 

Sets the mode when the bands which datasets have returned no records are still displayed once.
+
Default value: `true`
+
Used in the *Middleware* block.
      
