:sourcesdir: ../../source

[appendix]
[[app_properties]]
== Application Properties

This section describes the application properties related to the report generator in the alphabetical order.

[[reporting.backgroundReportProcessingTimeoutMs]]
reporting.backgroundReportProcessingTimeoutMs::
+
--
Defines the processing timeout in milliseconds for the report execution if the <<reporting.useBackgroundReportProcessing,reporting.useBackgroundReportProcessing>> is set to `true`.

Default value: `10000`.

Stored in the database.

Used in the *Middleware* block.
--

[[reporting.displayDeviceUnavailable]]
reporting.displayDeviceUnavailable::
+
--
Allows running OpenOffice/LibreOffice in the server operating system without a window interface.

Default value: `false`

Used in the *Middleware* block.
--

[[reporting.enableTabSymbolInDataSetEditor]]
reporting.enableTabSymbolInDataSetEditor::
+
--
Defines whether TAB key should be handled as `\t` symbol instead of focus navigation in Script fields of the report editor.

Default value: `false`

Used in the client blocks.
--

[[reporting.fontsDir]]
reporting.fontsDir::
+
--
Path to the fonts directory for converting HTML to PDF.

For example: `reporting.fontsDir = C:/Windows/Fonts`.

Used in the *Middleware* block.
--

[[reporting.docFormatterTimeout]]
reporting.docFormatterTimeout::
+
--
Sets the LibreOffice timeout in seconds for converting DOCX/XLSX to HTML/PDF.

When the time is up, the user will receive an error message.

Default value: `20`

Used in the *Middleware* block.
--

[[reporting.openoffice.docx.useOfficeForDocumentConversion]]
reporting.openoffice.docx.useOfficeForDocumentConversion::
+
--
Turns on using OpenOffice to convert the report having DOCX template to HTML/PDF, which significantly increases the conversion accuracy.

Default value: `false`

Used in the *Middleware* block.
--

[[reporting.openoffice.path]]
reporting.openoffice.path::
+
--
Sets the path to OpenOffice.

Default value: `/`

Used in the *Middleware* block.
--

[[reporting.openoffice.ports]]
reporting.openoffice.ports::
+
--
Specifies the comma- or vertical bar-separated list of available ports for OpenOffice/LibreOffice.

For example: `reporting.openoffice.ports = 8100|8101|8102|8103|8104|8105`.

Default value: `8100, 8101, 8102, 8103`.

Used in the *Middleware* block.
--

[[reporting.putEmptyRowIfNoDataSelected]]
reporting.putEmptyRowIfNoDataSelected::
+
--
Sets the mode when the bands which datasets have returned no records are still displayed once.

Default value: `true`

Used in the *Middleware* block.
--

[[reporting.useBackgroundReportProcessing]]
reporting.useBackgroundReportProcessing::
+
--
Allows you to set the report execution as a background task. This property is used in order to add the <<run_cancel,cancel>> option.

Default value: `false`.

Stored in the database.

Used in the *Middleware* block.
--
