:sourcesdir: ../../source

[appendix]
[[app_properties]]
== Application Properties

This section describes the application properties related to the report generator in the alphabetical order.

[[reporting.backgroundReportProcessingTimeoutMs]]
reporting.backgroundReportProcessingTimeoutMs::
+
--
Defines the processing timeout in milliseconds for the report execution if the <<reporting.useBackgroundReportProcessing,reporting.useBackgroundReportProcessing>> is set to `true`.

Default value: `10000`.

Stored in the database.

Used in the *Middleware* block.
--

[[reporting.displayDeviceAvailable]]
reporting.displayDeviceAvailable::
+
--
`false` value allows running OpenOffice/LibreOffice in the server operating system without a window interface.

Default value: `false`

Used in the *Middleware* block.
--

[[reporting.enableTabSymbolInDataSetEditor]]
reporting.enableTabSymbolInDataSetEditor::
+
--
Defines whether TAB key should be handled as `\t` symbol instead of focus navigation in Script fields of the report editor.

Default value: `false`

Used in the client blocks.
--

[[reporting.executionHistory.cleanup.days]]
reporting.executionHistory.cleanup.days::
+
--
The scheduled task deletes all <<execution_history,execution history>> records older than the specified number of days. If the property value is 0, the scheduled task does not consider this property when deleting records. See <<execution_history_cleanup, Cleanup the History>> for details on setting up the scheduled task.

Default value: `730`

Stored in the database.

Used in the *Middleware* block.

--

[[reporting.executionHistory.cleanup.itemsPerReport]]
reporting.executionHistory.cleanup.itemsPerReport::
+
--
The scheduled task leaves no more than this number of <<execution_history,execution history>> entries for every report. It is not recommended to use a number greater than 1000 as the value of this property. If the property value is 0, the scheduled task does not consider this property when deleting records. It is useful for frequently run reports such as email templates, invoicing document templates, etc. See <<execution_history_cleanup, Cleanup the History>> for details on setting up the scheduled task.

Default value: `1000`.

Stored in the database.

Used in the *Middleware* block.
--

[[reporting.executionHistory.enabled]]
reporting.executionHistory.enabled::
+
--
Activates the <<execution_history, report execution history>> mechanism.

Default value: `false`.

Stored in the database.

Used in the *Middleware* block.

--

[[reporting.executionHistory.saveOutputDocument]]
reporting.executionHistory.saveOutputDocument::
+
--
If set to true, report results files are saved to the {main_man_url}/file_storage.html[file store], if the <<reporting.executionHistory.enabled,reporting.executionHistory.enabled>> property is on. See <<history_output_documents,Output documents>> for details.

Default value: `false`.

Stored in the database.

Used in the *Middleware* block.
--

[[reporting.fontsDir]]
reporting.fontsDir::
+
--
Path to the fonts directory for converting HTML to PDF.

For example: `reporting.fontsDir = C:/Windows/Fonts`.

Used in the *Middleware* block.
--

[[reporting.docFormatterTimeout]]
reporting.docFormatterTimeout::
+
--
Sets the LibreOffice timeout in seconds for converting DOCX/XLSX to HTML/PDF.

When the time is up, the user will receive an error message.

Default value: `20`

Used in the *Middleware* block.
--

[[reporting.office.docx.useOfficeForDocumentConversion]]
reporting.office.docx.useOfficeForDocumentConversion::
+
--
Turns on using OpenOffice to convert the report having DOCX template to HTML/PDF, which significantly increases the conversion accuracy.

Default value: `false`

Used in the *Middleware* block.
--

[[reporting.office.path]]
reporting.office.path::
+
--
Sets the path to OpenOffice.

Default value: `/`

Used in the *Middleware* block.
--

[[reporting.office.ports]]
reporting.office.ports::
+
--
Specifies the comma- or vertical bar-separated list of available ports for OpenOffice/LibreOffice.

For example: `reporting.office.ports = 8100|8101|8102|8103|8104|8105`.

Default value: `8100, 8101, 8102, 8103`.

Used in the *Middleware* block.
--

[[reporting.putEmptyRowIfNoDataSelected]]
reporting.putEmptyRowIfNoDataSelected::
+
--
Sets the mode when the bands which datasets have returned no records are still displayed once.

Default value: `true`

Used in the *Middleware* block.
--

[[reporting.useBackgroundReportProcessing]]
reporting.useBackgroundReportProcessing::
+
--
Allows you to set the report execution as a background task. This property is used in order to add the <<run_cancel,cancel>> option.

Default value: `false`.

Stored in the database.

Used in the *Middleware* block.
--
