:sourcesdir: ../../source

[appendix]
[[app_properties]]
== Application Properties

This section describes the application properties related to the report generator in the alphabetical order.

[[reporting.displayDeviceUnavailable]]
reporting.displayDeviceUnavailable::

Allows running OpenOffice/LibreOffice in the server operating system without a window interface.
+
Default value: `false`
+
Used in the *Middleware* block.

[[reporting.fontsDir]]
reporting.fontsDir::

Path to the fonts directory for converting HTML to PDF.
+
For example: `reporting.fontsDir = C:/Windows/Fonts`.
+
Used in the *Middleware* block.

[[reporting.openoffice.docx.useOfficeForDocumentConversion]]
reporting.openoffice.docx.useOfficeForDocumentConversion::

Turns on using OpenOffice to convert the report having DOCX template to HTML/PDF, which significantly increases the conversion accuracy.
+
Default value: `false`
+
Used in the *Middleware* block.

[[reporting.openoffice.path]]
reporting.openoffice.path::

Sets the path to OpenOffice.
+
Default value: `/`
+
Used in the *Middleware* block.

[[reporting.openoffice.ports]]
reporting.openoffice.ports::

Specifies the comma- or vertical bar-separated list of available ports for OpenOffice/LibreOffice.
+
For example: `reporting.openoffice.ports = 8100|8101|8102|8103|8104|8105`.
+
Default value: `8100, 8101, 8102, 8103`.
+
Used in the *Middleware* block.

[[reporting.putEmptyRowIfNoDataSelected]]
reporting.putEmptyRowIfNoDataSelected::

Sets the mode when the bands which datasets have returned no records are still displayed once.
+
Default value: `true`
+
Used in the *Middleware* block.
      
