[appendix]
== Installing and Configuring OpenOffice

The report generator uses the *OpenOffice / LibreOffice* package to output reports in PDF and DOC <<template_to_output, formats>>. The installation to the computer containing the application server and configuration of this package is described below.

=== Installing and Configuring OpenOffice for Microsoft Windows

* Download the application at http://openoffice.org.
* Install the application.
* In the <<app_properties.adoc#cuba.reporting.openoffice.path, cuba.reporting.openoffice.path>> application property, specify the path to *OpenOffice.org*, for example:

[source]
----
cuba.reporting.openoffice.path = C:/Program Files (x86)/OpenOffice.org 3/program
----

=== Installing and Configuring LibreOffice on Ubuntu Server

* Install the `libreoffice` package, for example, by running the following command:

  `$ sudo apt-get install libreoffice`
    
* In the <<app_properties.adoc#cuba.reporting.openoffice.path, cuba.reporting.openoffice.path>> application property, specify the path to LibreOffice:

[source]
----
cuba.reporting.openoffice.path = /usr/lib/libreoffice/program
----

* If the server does not have window interface installed, LibreOffice will start with the error, `Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it`, or will simply terminate without error messages. To resolve this, set the <<app_properties.adoc#cuba.reporting.displayDeviceUnavailable, cuba.reporting.displayDeviceUnavailable>> application property:

[source]
----
cuba.reporting.displayDeviceUnavailable = true
----

* You can run the following command to diagnose errors when starting LibreOffice:

`$ strace -e trace=signal /usr/lib/libreoffice/program/soffice.bin --headless --accept="socket,host=localhost,port=8100;urp" --nologo --nolockcheck`
    


