:sourcesdir: ../../source

[appendix]
[[open_office]]
== Installing and Configuring OpenOffice

The report generator uses the *OpenOffice / LibreOffice* package to output reports in PDF and DOC <<template_to_output,formats>>. The installation to the computer containing the application server and configuration of this package is described below.

*Installing and Configuring OpenOffice for Microsoft Windows*

* Download the application at http://openoffice.org.
* Install the application.
* In the <<app_properties.adoc#reporting.openoffice.path, reporting.openoffice.path>> application property in the `app.properties` file of the *core* module, specify the path to *OpenOffice.org*, for example:

[source, properties]
----
reporting.openoffice.path = C:/Program Files (x86)/OpenOffice.org 3/program
----

*Installing and Configuring LibreOffice for Microsoft Windows*

* Download the application at http://www.libreoffice.org/download/download/.
* Install the application.
* In the <<app_properties.adoc#reporting.openoffice.path,reporting.openoffice.path>> application property in the `app.properties` file of the *core* module, specify the path to *LibreOffice*, for example:

[source, properties]
----
reporting.openoffice.path = C:/Program Files (x86)/LibreOffice 5/program
----

*Installing and Configuring LibreOffice on Ubuntu Server*

* Install the `libreoffice` package, for example, by running the following command:
+
[source, properties]
----
$ sudo apt-get install libreoffice`
----
    
* In the <<app_properties.adoc#reporting.openoffice.path, reporting.openoffice.path>> application property in the `app.properties` file of the *core* module, specify the path to LibreOffice:
+
[source, properties]
----
reporting.openoffice.path = /usr/lib/libreoffice/program
----

* If the server does not have window interface installed, LibreOffice will start with the error, `Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it`, or will simply terminate without error messages. To resolve this, set the <<app_properties.adoc#reporting.displayDeviceUnavailable, reporting.displayDeviceUnavailable>> application property:
+
[source, properties]
----
reporting.displayDeviceUnavailable = true
----

* You can run the following command to diagnose errors when starting LibreOffice:
+
[source, properties]
----
$ strace -e trace=signal /usr/lib/libreoffice/program/soffice.bin --headless --accept="socket,host=localhost,port=8100;urp" --nologo --nolockcheck
----

[TIP]
====
For Ubuntu users who installed tomcat using `apt`, it is necessary to copy `~/.config/libreoffice` to `$CATALINA_HOME`. For tomcat8, it is `/usr/share/tomcat8`.

After that, you should change the owner of this folder:

[source, properties]
----
sudo mkdir /usr/share/tomcat8/.config
sudo cp -pr ~/.config/libreoffice /usr/share/tomcat8/.config/
sudo chown -R tomcat8.tomcat8 /usr/share/tomcat8/.config/
----
====

*Installing and Configuring LibreOffice for macOS*

* Download the application at https://www.libreoffice.org/get-help/install-howto/os-x/.
* Install the application.
* In the <<app_properties.adoc#reporting.openoffice.path, reporting.openoffice.path>> application property, specify the path to *LibreOffice.app*, for example:

[source, properties]
----
reporting.openoffice.path = /Applications/LibreOffice.app
----

