= CUBA Platform. Report Generator
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.10
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)
:rest_swagger_url: http://files.cuba-platform.com/swagger/{revnumber}

:!sectnums:

[[preface]]
[preface]
== Preface

This document provides guidance for creating reports in applications built on CUBA platform.

[[audience]]
=== Intended Audience

This manual is intended for developers and administrators of CUBA applications. In order to work successfully with the report generator, you should understand relational database principles and be able to write SQL queries. Familiarizing yourself with JPQL and Groovy is also useful, because in some cases it is easier to extract report data using these languages.

[[additional_info]]
=== Further Reading

This Manual and the accompanying documentation related to the CUBA platform can be found at https://www.cuba-platform.com/manual.

The core of the platform report generator is the *YARG* framework, which is distributed under the free Apache 2.0 license. The framework documentation is available at https://github.com/Haulmont/yarg/wiki.

[[feedback]]
=== Feedback

If you have any suggestions for improving this manual, feel free to report issues in the source repository on https://github.com/cuba-platform/documentation[GitHub]. If you see a spelling or wording mistake, a bug or inconsistency, don't hesitate to fork the repo and fix it. Thank you!

:sectnums:

include::creation.adoc[]

include::running.adoc[]

include::examples.adoc[]

include::wizard.adoc[]

include::rest_reports.adoc[]

include::open_office.adoc[]

include::app_properties.adoc[]