= CUBA Platform. Report Generator
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.8
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)

:!sectnums:

[[preface]]
[preface]
== Preface

This document provides guidance for creating reports in applications built on CUBA platform.

[[audience]]
=== Intended Audience

This manual is intended for developers and administrators of CUBA applications. In order to work successfully with the report generator, you should understand relational database principles and be able to write SQL queries. Familiarizing yourself with JPQL and Groovy is also useful, because in some cases it is easier to extract report data using these languages.

[[additional_info]]
=== Further Reading

This Manual and the accompanying documentation related to the CUBA platform can be found at https://www.cuba-platform.com/manual.

The core of the platform report generator is the *YARG* framework, which is distributed under the free Apache 2.0 license. The framework documentation is available at https://github.com/Haulmont/yarg/wiki.

[[feedback]]
=== Feedback

If you have any suggestions for improvement of this Manual, please contact us at https://www.cuba-platform.com/support/topics. 

If you find a mistake in the documentation, please specify the number of the chapter and attach a small abstract of surrounding text to help us locate the issue. 

:sectnums:

include::creation.adoc[]

include::running.adoc[]

include::examples.adoc[]

include::wizard.adoc[]

include::open_office.adoc[]

include::app_properties.adoc[]