:sourcesdir: ../../../../../source

[[dataManager]]
===== DataManager

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/core/global/DataManager.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`DataManager` interface provides CRUD functionality on both middle and client tiers. It is a universal tool for loading entity graphs from the database and saving changed detached entity instances.

[TIP]
====
Learn https://www.cuba-platform.com/guides/intro-working-with-data-in-cuba[Introduction to Working with Data] guide, which includes different use cases regarding programmatic data access with the DataManager API.
====

[TIP]
====
See <<dm_vs_em>> for information on differences between DataManager and <<entityManager,EntityManager>>.
====

`DataManager` in fact just delegates to a <<data_store,DataStore>> implementation and handles cross-database references if needed. The most implementation details described below are in effect when you work with entities stored in a relational database through the standard `RdbmsStore`. For another type of data store, everything except the interface method signatures can be different. For simplicity, when we write _DataManager_ without additional clarification, we mean _DataManager via RdbmsStore_.

`DataManager` methods are listed below:

* `load(Class)` - loads entities of the specified class. This method is an entry point to the fluent API:
+
[source, java]
----
include::{sourcesdir}/common/dataManager_4.java[]
----

* `loadValues(String query)` - loads key-value pairs by the query for scalar values. This method is an entry point to the fluent API:
+
[source, java]
----
include::{sourcesdir}/common/dataManager_5.java[]
----
+
<1> - specify data store where the entity is located. Omit this method if the entity is located in the main data store.
<2> - specify names of the resulting `KeyValueEntity` attributes. The order of the properties must correspond to the columns in the query result set.

* `loadValue(String query, Class valueType)` - loads a single value by the query for scalar values. This method is an entry point to the fluent API:
+
[source, java]
----
include::{sourcesdir}/common/dataManager_6.java[]
----
+
<1> - specify data store where the entity is located. Omit this method if the entity is located in the main data store.

* `load(LoadContext)`, `loadList(LoadContext)` – load entities according to the parameters of the `LoadContext` object passed to it. `LoadContext` must include either a JPQL query or an entity identifier. If both are defined, the query is used, and the identifier is ignored.
+
For example:
+
[source, java]
----
include::{sourcesdir}/common/dataManager_1.java[]
----

* `loadValues(ValueLoadContext)` - loads a list of key-value pairs. The method accepts `ValueLoadContext` which defines a query for scalar values and a list of keys. The returned list contains instances of `KeyValueEntity`. For example:
+
[source, java]
----
include::{sourcesdir}/common/dataManager_3.java[]
----

* `getCount(LoadContext)` - returns a number of records for a query passed to the method. When possible, the standard implementation in `RdbmsStore` executes `select count()` query with the same conditions as in the original query for maximum performance.

* `commit(CommitContext)` – saves a set of entities passed in `CommitContext` to the database. Collections of entities for updating and deletion must be specified separately.
+
The method returns the set of entity instances returned by <<entityManager,EntityManager>>.merge(); essentially these are fresh instances just updated in DB. Further work should be performed with these returned instances to prevent data loss or optimistic locking. You can ensure that required attributes are present in the returned entities by setting a view for each saved instance using `CommitContext.getViews()` map.
+
`DataManager` can perform <<bean_validation_in_DataManager,bean validation>> of saved entities.
+
Examples of saving a collection of entities:
+
[source, java]
----
include::{sourcesdir}/common/dataManager_2.java[]
----

* `reload(Entity, View)` - convenience method to reload a specified instance from the database with the required <<views,view>>. It delegates to the `load()` method.

* `remove(Entity)` - removes a specified instance from the database. Delegates to `commit()` method.

* `create(Class)` - creates an instance of the given entity in memory. This is a convenience method that just delegates to `Metadata.create()`.

* `getReference(Class, Object)` - returns an entity instance which can be used as a reference to an object which exists in the database.
+
--
For example, if you are creating a `User`, you have to set a `Group` the user belongs to. If you know the group id, you could load it from the database and set to the user. This method saves you from unneeded database round trip:

[source, java]
----
include::{sourcesdir}/common/dataManager_7.java[]
----

A reference can also be used to delete an existing object by id:

[source, java]
----
include::{sourcesdir}/common/dataManager_8.java[]
----
--

[[dm_query]]
Query::
+
--
When working with relational databases, use <<jpql,JPQL>> queries to load data. See the <<jpql_functions>>, <<query_case_insensitive>> and <<jpql_macro>> sections for information on how JPQL in CUBA differs from the JPA standard. Also note that `DataManager` can execute only "select" queries.

The `query()` method of the fluent interface accepts both full and abbreviated query string. The latter should be created in accordance with the following rules:

* You can always omit the `"select <alias>"` clause.
* If the `"from"` clause contains a single entity and you don't need a specific alias for it, you can omit the `"from <entity> <alias> where"` clause. In this case, the framework assumes that the alias is `e`.
* You can use positional parameters and pass their values right to the `query()` method as additional arguments.

For example:

[source, java]
----
include::{sourcesdir}/common/dataManager_9.java[]
----

Please note that positional parameters are supported only in the fluent interface. `LoadContext.Query` supports only named parameters.
--

[[dm_transactions]]
Transactions::
+
--
DataManager always starts a new <<transactions,transaction>> and commits it on operation completion, thus returning entities in the <<entity_states,detached state>>. On the middle tier, you can use <<transactionalDataManager,TransactionalDataManager>> if you need to implement complex transactional behavior.
--

[[dm_partial_entities]]
Partial entities::
+
--
_Partial_ entity is an entity instance that can have only a subset of local attributes loaded. By default, DataManager loads partial entities according to <<views,views>> (in fact, `RdbmsStore` just sets the <<view_loadPartialEntities,loadPartialEntities>> property of the view to true and passes it down to <<entityManager,EntityManager>>).

There are some conditions, when DataManager loads all local attributes and uses views only for fetching references:

* The loaded entity is <<entity_cache,cached>>.
* In-memory "read" <<constraints,constraints>> are defined for the entity.
* Dynamic <<entity_attribute_access,attribute access control>> is set up for the entity.
* The `loadPartialEntities` attribute of `LoadContext` is set to false.
--

include::dataManager/dm_vs_em.adoc[]

include::dataManager/transactionalDataManager.adoc[]

include::dataManager/dm_security.adoc[]

include::dataManager/query_with_distinct.adoc[]

include::dataManager/query_from_selected.adoc[]

