:sourcesdir: ../../../../../source

[[entityStates]]
===== EntityStates

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/global/EntityStates.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

An interface for obtaining the information on persistent entities managed by <<orm,ORM>>. Unlike the <<persistence,Persistence>> and <<persistenceTools,PersistenceTools>> beans, this interface is available on all <<app_tiers,tiers>>.

The `EntityStates` interface has the following methods:

* `isNew()` – determines if the passed instance is newly created, i.e., in the <<entity_states,New>> state. Also returns `true` if this instance is actually in <<entity_states,Managed>> state but newly-persisted in the current transaction, or if it is not a persistent entity.

* `isManaged()` - determines if the passed instance is Managed, i.e. attached to a persistence context.

* `isDetached()` – determines if the passed instance is in the <<entity_states,Detached>> state. Also returns `true`, if this instance is not a persistent entity.

*  `isLoaded()` - determines if an attribute is loaded from the database. The attribute is loaded if it is included into a <<views,view>>, or if it is a local attribute and a view was not provided to the loading mechanism (<<entityManager,EntityManager>> or <<dataManager,DataManager>>). Only immediate attributes of the entity can be checked by this method.

* `checkLoaded()` - the same as `isLoaded()` but throws `IllegalArgumentException` if at least one of the attributes passed to the method is not loaded.

* `isLoadedWithView()` - accepts an entity instance and a view and returns true if all attributes required by the view are actually loaded.

* `checkLoadedWithView()` - the same as `isLoadedWithView()` but throws `IllegalArgumentException` instead of returning false.

* `makeDetached()` - accepts a newly created entity instance and turns it into the detached state. The detached object can be passed to `DataManager.commit()` or `EntityManager.merge()` to save its state in the database. See details in the API docs.

* `makePatch()` - accepts a newly created entity instance and makes it a _patch object_. The patch object can be passed to `DataManager.commit()` or `EntityManager.merge()` to save its state in the database. Unlike for a detached object, only non-null attributes will be saved. See details in the API docs.

include::entityStates/persistenceHelper.adoc[]

