:sourcesdir: ../../../../../source

[[messages]]
===== Messages

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/global/Messages.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`Messages` interface provides methods to get <<localization,localized message strings>>.

Let's consider interface methods in detail.

* `getMessage()` – returns the localized message by key, pack name and required locale. There are several modifications of this method with different sets of parameters. If locale is not specified in the method parameter, the current user locale is used. 
+
Examples:
+
[source, java]
----
include::{sourcesdir}/common/messages_1.java[]
----

* `formatMessage()` – retrieves a localized message by key, pack name and required locale, then uses it to format the input parameters. The format is defined according to `String.format()` method rules. There are several modifications of this method with different sets of parameters. If locale is not specified in the method parameter, the current user locale is used.
+
Example:
+
[source, java]
----
include::{sourcesdir}/common/messages_2.java[]
----

* `getMainMessage()` – returns the localized message from the <<main_message_pack,main message pack>> of the application <<app_tiers,block>>.
+
Example:
+
[source, java]
----
include::{sourcesdir}/common/messages_3.java[]
----

* `getMainMessagePack()` – returns the name of the <<main_message_pack,main message pack>> of the application block. 
+
Example:
+
[source, java]
----
include::{sourcesdir}/common/messages_4.java[]
----

* `getTools()` – returns `MessageTools` interface instance (see below).

include::messages/messageTools.adoc[]

