:sourcesdir: ../../../../../source

[[metadata]]
===== Metadata

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/global/Metadata.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`Metadata` interface provides access to metadata session and <<views,view>> repository.

Interface methods:

* `getSession()` – returns the <<metadata_framework,metadata>> session instance.

* `getViewRepository()` – returns the <<views,view>> repository instance.

* `getExtendedEntities()` – returns `ExtendedEntities` instance, intended for working with the extended entities. See more in <<entity_extension>>.

* `create()` – creates an entity instance, taking into account potential <<entity_extension, extension>>.
+
For persistent `BaseLongIdEntity` and `BaseIntegerIdEntity` subclasses, assigns identifiers right after creation. The new identifiers are fetched from automatically created database sequences. By default, the sequences are created in the main <<data_store,data store>>. However, if the <<cuba.useEntityDataStoreForIdSequence,cuba.useEntityDataStoreForIdSequence>> application property is set to true, sequences are created in the data store the entity belongs to.

* `getTools()` – returns `MetadataTools` interface instance (see below).

include::metadata/metadataTools.adoc[]

