:sourcesdir: ../../../../../source

[[resources]]
===== Resources

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/global/Resources.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`Resources` interface maintains resources loading according to the following rules:

. If the provided location is a URL, the resource is downloaded from this URL;

. If the provided location begins with `classpath:` prefix, the resource is downloaded from classpath;

. If the location is not a URL and it does not begin with `classpath:`, then:

.. The file is searched in the <<conf_dir,configuration folder>> of application using the provided location as relative pathname. If the file is found, the resource is downloaded from it;

.. If the resource is not found at the previous steps, it is downloaded from classpath.

In practice, explicit identification of URL or `classpath:` prefix is rarely used, so resources are usually downloaded either from the <<conf_dir,configuration folder>> or from classpath. The resource in the configuration folder overrides the classpath resource with the same name.

`Resources` methods:

* `getResourceAsStream()` – returns `InputStream` for the provided resource, or `null`, if the resource is not found. The stream should be closed after it had been used, for example:
+
[source, java]
----
include::{sourcesdir}/common/resources_1.java[]
----
+
You can also use "try with resources":
+
[source, java]
----
include::{sourcesdir}/common/resources_2.java[]
----

* `getResourceAsString()` – returns the indicated resource content as string, or `null`, if the resource is not found. 

