:sourcesdir: ../../../../../source

[[securityContext]]
===== SecurityContext

Экземпляр класса `SecurityContext` хранит информацию о пользовательской сессии для текущего потока выполнения. Он создается и передается в метод `AppContext.setSecurityContext()` в следующие моменты:

* для блоков Web Client и Web Portal - в начале обработки каждого HTTP-запроса от пользовательского браузера.

* для блока Middleware - в начале обработки каждого запроса от клиентского уровня и от <<scheduled_tasks_cuba,назначенных заданий CUBA>>.

По окончании выполнения запроса в первых двух случаях `SecurityContext` удаляется из потока выполнения.

При создании прикладным кодом нового потока выполнения в него необходимо передать текущий экземпляр `SecurityContext`, например:

[source, java]
----
include::{sourcesdir}/common/securitycontext_1.java[]
----

То же самое можно сделать, используя обертки `SecurityContextAwareRunnable` или `SecurityContextAwareCallable`, например:

[source, java]
----
include::{sourcesdir}/common/securitycontext_2.java[]
----

[source, java]
----
include::{sourcesdir}/common/securitycontext_3.java[]
----

