:sourcesdir: ../../../../../source

[[userSession]]
===== UserSession

Основной элемент подсистемы контроля доступа в CUBA-приложении - пользовательская сессия. Это объект класса `UserSession`, который ассоциирован с аутентифицированным в данный момент в системе пользователем, и содержит информацию о правах доступа пользователя к данным. Объект текущей сессии может быть получен в любом <<app_tiers,блоке>> приложения через интерфейс инфраструктуры <<userSessionSource,UserSessionSource>>.

Пользовательская сессия создается на Middleware при выполнении метода `AuthenticationManager.login()` после аутентификации пользователя по переданному имени и паролю. Объект `UserSession` затем кэшируется в данном блоке Middleware, и возвращается на клиентский уровень. При работе в кластере объект сессии реплицируется на соседние узлы кластера Middleware. Клиентский блок, получив объект сессии, также сохраняет его у себя, так или иначе ассоциируя с активным пользователем (например, в HTTP сессии). Далее все вызовы Middleware для данного пользователя сопровождаются передачей идентификатора сессии (типа `UUID`), причем прикладному коду не нужно об этом заботиться - идентификатор сессии передается автоматически, независимо от сигнатуры вызываемых методов среднего слоя. Обработка вызовов клиентов на Middleware начинается с извлечения из кэша сессии по полученному идентификатору и установки ее в потоке выполнения. Объект сессии удаляется из кэша при вызове метода `LoginService.logout()`, либо при истечении времени бездействия, определяемого свойством приложения <<cuba.userSessionExpirationTimeoutSec,cuba.userSessionExpirationTimeoutSec>>.

Таким образом, идентификатор сессии, создаваемой при входе пользователя в систему, служит для аутентификации пользователя при каждом вызове среднего слоя.

Объект `UserSession` содержит также методы для _авторизации_ текущего пользователя, т.е. проверки его прав на объекты системы: `isScreenPermitted()`, `isEntityOpPermitted()`, `isEntityAttrPermitted()`, `isSpecificPermitted()`.

С объектом `UserSession` могут быть ассоциированы именованные атрибуты произвольного сериализуемого типа. Атрибуты устанавливаются методом `setAttribute()` и возвращаются методом `getAttribute()`. Последний может также возвращать следующие параметры сессии, как если бы они были атрибутами:

* `userId` - ID текущего зарегистрированного или замещенного пользователя;

* `userLogin` - логин текущего зарегистрированного или <<user_substitution,замещенного>> пользователя в нижнем регистре.

Атрибуты реплицируются в кластере Middleware так же, как и все остальные данные сессии.

