:sourcesdir: ../../../../../../source

[[datasource_query_filter]]
====== Фильтр запроса

Запрос источника данных может быть модифицирован во время работы приложения, в зависимости от вводимых пользователем условий, что позволяет эффективно фильтровать данные на уровне выборки из БД.

Простейший способ обеспечения такой возможности - подключение к источнику данных специального визуального компонента <<gui_Filter,Filter>>.

Если по какой-то причине применение универсального фильтра нежелательно, можно встроить в текст запроса специальную разметку на XML, позволяющую сформировать итоговый запрос в зависимости от значений, введенных пользователем в произвольные визуальные компоненты экрана.

В таком фильтре могут быть использованы следующие элементы:

* `filter` - корневой элемент фильтра. Может непосредственно содержать только одно условие.

** `and`, `or` - логические условия, могут содержать любое количество других условий и предложений. 

** `c` - предложение на JPQL, которое добавляется в секцию `where`. Содержит только текст и опционально атрибут `join`, значение которого будет добавлено в соответствующее место запроса, если добавляется данное предложение `where`. 

Условия и предложения добавляются в итоговый запрос, только если присутствующие внутри них параметры получили значения, т.е. не равны `null`. 

[WARNING]
====
В фильтрах запросов можно использовать только параметры <<datasource_query_params_custom,custom>>, <<datasource_query_params_param,param>>, <<datasource_query_params_component,component>> и <<datasource_query_params_session,session>>. Параметр <<datasource_query_params_ds,ds>> не будет работать.
====

Пример:

[source, xml]
----
include::{sourcesdir}/gui/datasources_13.xml[]
----

В данном случае если в метод `refresh()` источника данных переданы параметры `state` и `initiator`, а в визуальном компоненте `barCodeFilterField` установлено некоторое значение, то итоговый запрос примет вид:

[source, jpql]
----
select distinct d from app$GeneralDoc d, app$DocRole dr
where
(
  (dr.doc.id = d.id and d.processState = :custom$state)
  and
  (d.barCode like :component$barCodeFilterField)
)
or
(dr.doc.id = d.id and dr.user.id = :custom$initiator)
----

Если же, к примеру, компонент `barCodeFilterField` пуст, а в `refresh()` передан только параметр `initiator`, то запрос получится следующим:

[source, jpql]
----
select distinct d from app$GeneralDoc d, app$DocRole dr
where
(dr.doc.id = d.id and dr.user.id = :custom$initiator)
----

