:sourcesdir: ../../../../../source

[[record_set]]
===== Record Sets

In order to use record sets with a screen, follow the steps below.

. Link the <<gui_Filter,Filter>> component with the <<gui_Table,Table>> using the `applyTo` attribute.
. Add the `addToSet` predefined action to the table. After that, users will be able to add entities to sets using table's context menu.
. Add a button representing the action to the buttons panel.

For example:

[source, xml]
----
<layout>
  <filter id="customerFilter" dataLoader="customersDl"
          applyTo="customersTable"/>

  <groupTable id="customersTable" dataContainer="customersDc">
      <actions>
          <action id="addToSet" type="addToSet"/>
          ...
      </actions>
      <buttonsPanel>
          <button action="customersTable.addToSet"/>
          ...
      </buttonsPanel>
----

When the screen displays some set, i.e. it is opened by clicking on a set in the folders panel, the table automatically shows *Add to current set* / *Remove from current set* actions in the context menu. If the table includes `buttonsPanel` (as in the example above), the corresponding table buttons are also shown.

Record sets are the instances of the `SearchFolder` entity stored in the related *SYS_FOLDER* and *SEC_SEARCH_FOLDER* tables.
