:sourcesdir: ../../../../../source

[[build.gradle_buildInfo]]
===== buildInfo

Задача `buildInfo` автоматически добавляется в конфигурацию модуля `global` плагином CUBA для Gradle. Она записывает файл `build-info.properties` с информацией о приложении в артефакт `global` (например, `app-global-1.0.0.jar`). Во время работы приложения, эта информация читается бином `BuildInfo` и отображается на экране *Help > About*. Данный бин может также вызываться другими механизмами для получения информации о имени, версии и т.д. приложения.

В проекте можно явно указать следующие параметры задачи:

* `appName` - имя приложения. По умолчанию используется имя проекта, заданное в `settings.gradle`.

* `artifactGroup` - группа артефактов, которая по конвенции равна корневому пакету проекта.

* `version` - версия приложения. По умолчанию используется версия, заданная в свойстве `cuba.artifact.version`.

* `properties` - мэп произвольных свойств. По умолчанию пусто.

Пример указания параметров задачи:

[source, groovy]
----
include::{sourcesdir}/development/build_gradle_buildInfo_1.groovy[]
----

