:sourcesdir: ../../../../../source

[[build.gradle_deployWar]]
===== deployWar

`deployWar` - задача типа `CubaJelasticDeploy`, выполняющая развёртывание WAR-файла на сервер Jelastic.

[TIP]
====
Эту задачу можно настроить на странице *Deployment settings > Cloud* в Studio. См. контекстную помощь.
====

Пример использования:

[source, groovy]
----
task deployWar(type: CubaJelasticDeploy, dependsOn: buildWar) {
   email = '<your@email.address>'
   password = '<your password>'
   context = '<app contex>'
   environment = '<environment name or ID>'
   hostUrl = '<Host API url>'
}
----

Параметры задачи:

* `appName` - имя приложения. По умолчанию совпадает с *Modules prefix*, например, `app`.

* `email` - логин учётной записи сервера Jelastic.

* `password` - пароль учётной записи сервера Jelastic.

* `context` - контекст приложения. Значение по умолчанию: `ROOT`.

* `environment` - окружение, в которое будет развернут WAR. Можно указать как имя, так и ID окружения.

* `hostUrl` - URL-адрес API хостинга. Обычно это `app.jelastic.<host name>`.

* `srcDir` - директория, в которой находится WAR. По умолчанию это `"${project.buildDir}/distributions/war"`.

