:sourcesdir: ../../../../../source

[[securityContext]]
===== SecurityContext

`SecurityContext` class instance stores information about the user session for the current execution thread. It is created and passed to `AppContext.setSecurityContext()` method in the following moments:

* For the Web Client and Web Portal blocks – at the beginning of processing of each HTTP request from the user browser.
* For the Middleware block – at the beginning of processing of each request from the client tier and from <<scheduled_tasks_cuba>>.
* For the Desktop Client block – once after the user login, as the desktop application is running in single user mode.

In the first two cases, `SecurityContext` is removed from the execution thread when the request execution is finished.

If you create a new execution thread from the application code, pass the current `SecurityContext` instance to it as in the example below:

[source, java]
----
include::{sourcesdir}/common/securitycontext_1.java[]
----

The same can be done using `SecurityContextAwareRunnable` or `SecurityContextAwareCallable` wrappers, for example:

[source, java]
----
include::{sourcesdir}/common/securitycontext_2.java[]
----

[source, java]
----
include::{sourcesdir}/common/securitycontext_3.java[]
----

