:sourcesdir: ../../../../../../source

[[transactionalDataManager]]
====== TransactionalDataManager

`TransactionalDataManager` - это бин среднего слоя, который во многом повторяет интерфейс `DataManager`, но при этом может присоединяться к существующей транзакции. Он имеет следуюшие особенности:

* При наличии активной транзакции, выполняет действия в ее контексте, в противном случае стартует и коммитит новую транзакцию так же как `DataManager`.

* Принимает и возвращает сущности в состоянии detached. Разработчик должен загружать сущности с необходимыми <<views,представлениями>> и явно вызывать метод `save()` для сохранения измененных экземпляров в БД.

* Применяет ограничения row-level security, работает с динамическими атрибутами и ссылками между хранилищами так же как `DataManager`.

Ниже приведен простейший пример использования `TransactionalDataManager` в некотором методе сервиса:

[source,java]
----
include::{sourcesdir}/common/transactionalDataManager_1.java[]
----

Более сложный пример можно найти в тесте фреймворка: https://github.com/cuba-platform/cuba/blob/{git_branch}/modules/core/test/com/haulmont/cuba/core/DataManagerTransactionalUsageTest.java[DataManagerTransactionalUsageTest.java]

[TIP]
====
`TransactionalDataManager` особенно полезен при обработке события <<entityChangedEvent,EntityChangedEvent>> в текущей транзакции. Он позволяет получить текущее состояние измененной сущности из базы данных до коммита транзакции.
====