:sourcesdir: ../../../../../source

[[url_history]]
===== History

An application handles on the browser "Back"/"Forward" buttons clicking as URL changes. To distinguish regular and history changes [[url_state_mark]]_URL state marks_ are used. In the following example the "0" is the state mark:

[source, url]
----
http://localhost:8080/app/#main/0/users
----

So all URL's changes that have state mark are checked as history navigation. To distinguish history navigation and copy-pasted addresses an app stores a local copy of opened screens with resolved routes and state marks. It allows checking whether URL change is related to history navigation or not.

[[url_forward]]
Forward::
+
--
"Forward" history navigation is not supported due to the complexity of context-specific screens and actions.
--

[[url_back]]
Back::
+
--
"Back" history navigation is supported only for opened screens. It enables to navigate through history sequentially in order of screens opening. These transitions consider unsaved changes and backward navigation will be aborted if the `Cancel` action performed.
--