:sourcesdir: ../../../../source

[[polymer_manual__advanced__dom]]
==== Accessing DOM Elements

The simplest and the most straightforward method to access an HTML element from JS code is to use id-s. Consider an example below.

Click on the button to see what it's doing:
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/dom/colored-square-controller.html">

<div class="polymer-demo-container">
    <colored-square-controller></colored-square-controller>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/dom/colored-square-controller.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <colored-square-controller></colored-square-controller>
</body>
</html>
----

.src/polymer-advanced/dom/colored-square-controller.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square-controller.html[]
----

.src/polymer-advanced/dom/colored-square.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square.html[]
----

As you can see, Polymer has special shortcut — `this.$`, which can be used to retrieve an element by its id. In found element, you can change properties and call methods.

[TIP]
====
Please note that we used attribute `black$` instead of `black`. What's the difference?

If we used just `black`, then during the component initialization Polymer would or would not put `black` attribute in DOM on `div` based on if `black` property is true or false. And if the `black` property changed later Polymer wouldn't add/remove this attribute from the `div`. Therefore, it would be impossible to use this attribute in CSS (`.square[black]`). But when we use `black$`, Polymer automatically updates HTML attribute `black` based on changes in the `black` property.

That is if in our example we used `black` instead of `black$`, then the square would always be white, no matter how much we press the button.
====

However, the `this.$` syntax won't always work. Let's put the `colored-square` component inside an if-template.
In this case `this.$.square` won't work even if the condition is true. See more in the https://www.polymer-project.org/2.0/docs/devguide/dom-template#node-finding[official guide].

.src/polymer-advanced/dom/colored-square-controller-with-if.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square-controller-with-if.html[]
----

In such cases you can use native DOM API to find a required element: `this.shadowRoot.querySelector("selector")`. This method will search for the element dynamically.

.src/polymer-advanced/dom/colored-square-controller-with-if-fixed.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square-controller-with-if-fixed.html[]
----

What we have learned so far::
+
--
* `this.$.{id}` can be used to retrieve an element by id. However, it won't work if this element is
added/removed dynamically from DOM.

* Native DOM API `this.shadowRoot.querySelector("{selector}")` can be used to find an element by CSS selector.

* We can change properties on the found element and call its methods.

* Use special syntax ("black$=") if you want to change attribute (not property). Mostly, it's required
when we want to use these attributes in our CSS.
--

