:sourcesdir: ../../../../source

[[polymer_manual__advanced__lifecycle]]
==== Lifecycle Callbacks

Polymer components allow you to define code that would be called in response to certain lifecycle events.

To use this feature, implement methods with the following names:

- `constructor` - called when an element is created but before property values are set.

- `connectedCallback` - called when an element is created and properties are set.

- `disconnectedCallback` - called when an element is removed from a document.

For example, a user opens some profile page and we would like to load all required details from the server
before showing them to the user.

[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/lifecycle/profile-page.html">

<div class="polymer-demo-container">
    <profile-page></profile-page>
</div>

++++

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/lifecycle/profile-page.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <profile-page></profile-page>
</body>
</html>
----

.src/polymer-advanced/lifecycle/profile-page.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/lifecycle/profile-page.html[]
----

.src/polymer-advanced/lifecycle/personal-details-page.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/lifecycle/personal-details-page.html[]
----

.src/polymer-advanced/lifecycle/preferences-page.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/lifecycle/preferences-page.html[]
----

What we have learned so far::
+
--
* During their lifecycle, Polymer elements call a number of callback methods.
We can use these methods to invoke our initialization logic.
--

