:sourcesdir: ../../../../source

[[polymer_manual__advanced__observers]]
==== Observers

Sometimes, it is needed to listen to changes in some properties and react on them. For example, we may want
to send some notifications to a server when users enter some information.

The example below demonstrates it. Basically, users can choose a type of their company and we save this information somewhere in a database.

*Company type selector*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/observers/company-type-select.html">

<div class="polymer-demo-container">
    <company-type-select></company-type-select>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/observers/company-type-select.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <company-type-select></company-type-select>
</body>
</html>
----

.src/polymer-advanced/observers/company-type-select.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/observers/company-type-select.html[]
----

Observers can be much more complex. For example, you may want to monitor changes in several different properties.

Let's enhance our previous example by adding a contact name input.

.src/polymer-advanced/observers/company-type-select-enhanced.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/observers/company-type-select-enhanced.html[]
----

*Enhanced company type selector*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/observers/company-type-select-enhanced.html">

<div class="polymer-demo-container">
    <company-type-select-enhanced></company-type-select-enhanced>
</div>

++++

What we have learned so far::
+
--
* We can monitor changes in a single property by using an `observer` attribute. An observer function accepts 2 arguments:
an old value and a new one.

* We can monitor several properties at the same time by using observers array. But we lose information about old values in this case.
--

