= Платформа CUBA. Подсистема BPM
:toc: left
:toc-title: Содержание
:appendix-caption: Приложение
:toclevels: 6
:sectnumlevels: 6
:linkcss:
:stylesheet: cuba.css
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: ru
:revnumber: 6.9
:version-label: Версия
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)
:figure-caption: Рисунок

:!sectnums:

[[preface]]
== Предисловие

Данный документ является руководством по применению подсистемы исполнения бизнес-процессов (business process management, BPM) платформы CUBA.

Предполагается, что читатель ознакомлен с Руководством по разработке приложений, доступным по адресу https://www.cuba-platform.ru/manual.

Подсистема исполнения бизнес-процессов CUBA основана на фреймворке Activiti, поэтому знакомство с его устройством будет полезным. См. http://www.activiti.org. Исполняемый процесс описывается в нотации BPMN 2.0, поэтому разработчик должен быть знаком с данной нотацией. См. http://www.bpmn.org.

Если у Вас имеются предложения по улучшению данного руководства, мы будем рады принять ваши pull request'ы и issues в исходниках документации на https://github.com/cuba-platform/documentation[GitHub]. Если вы увидели ошибку или несоответствие в документе - пожалуйста, форкните репозиторий и исправьте проблему. Заранее спасибо!

:sectnums:

include::quickstart.adoc[]

include::datamodel.adoc[]

include::functionality.adoc[]

include::services.adoc[]

include::ui.adoc[]

include::examples.adoc[]

[[app_properties]]
[appendix]
== Свойства приложения

bpm.activiti.asyncExecutorEnabled:: Возможные значение: `true` или `false`. Определяет, включен ли Job executor для выполнения задач таймеров и асинхронных задач. По умолчанию значение равно `false`.
