[[examples]]
== Примеры

[[process_runtime_service_usage]]
=== Программный запуск процесса

`ProcActionsFrame` является удобным механизмом запуска процессов из редактора сущности, однако, иногда возникает необходимость запустить процесс программного. Для этого первым делом необходимо создать объект ProcInstance с заполненной коллекцией участников процесса (ProcActor). Можно создавать экземпляры сущностей с помощью бина Metadata, но модуль BPM имеет для этого специальный метод: `BpmEntitiesService.createProcInstance(ProcInstanceDetails procInstanceDetails)`. 

Предположим, мы задеплоили процесс с кодом `orderProcessing`. В процессе объявлены две роли: `manager` и `storekeeper`.

Для создания объекта `ProcInstance` с помощью `BpmEntitiesService` и запуска процесса используется следующий код:

[source, java]
----
include::{sourcesdir}/start_process.java[]
----

Этот код создаст новый экземпляр `ProcInstance`. В его свойство `procDefinition` будет проставлена ссылка на ProcDefinition с кодом `orderProcessing` (если процесс с данным кодом не найден, будет выброшено исключение). Коллекция участников процесса (procActors) будет содержать две записи: одна для роли с кодом `manager`, вторая для роли с кодом `storekeeper`. 

`ProcessRuntimeService.startProcess()` запускает процесс, сохраняя объекты ProcInstance и ProcActor в базу данных.