[[preface]]
== Предисловие

Данный документ является руководством по применению подсистемы исполнения бизнес-процессов (business process management, BPM) платформы CUBA.

=== Целевая аудитория

Данное руководство предназначено для разработчиков, создающих на платформе CUBA приложения с возможностью исполнения бизнес-процессов. Предполагается, что читатель ознакомлен с Руководством по разработке приложений, доступным по адресу http://www.cuba-platform.com/ru/manual.

=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу http://www.cuba-platform.com/ru/manual.

Подсистема исполнения бизнес-процессов CUBA основана на фреймворке Activiti, поэтому знакомство с его устройством будет полезным. См. http://www.activiti.org.

Исполняемый процесс должен быть описан в нотации BPMN 2.0. Разработчик должен быть знаком с данной нотацией. См. http://www.bpmn.org.

=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, обратитесь пожалуйста в службу поддержки по адресу http://ru.cuba-platform.com/support/topics.

При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска.