[[services]]
== Основные сервисы

[[process-repository-service]]
=== ProcessRepositoryService

Служит для работы с описаниями процесса (ProcDefinition).

Основные методы:

* deployProcessFromXml() - загружает XML BPMN процесса в Activiti engine, при этом создавая или изменяя существующий объект ProcDefinition.
* getProcessDefinitionXml() - возвращает XML представление процесса
* convertModelToProcessXml() - преобразует JSON модели в BPMN XML
* undeployProcess() - удаляет процесс из Activiti engine

Для доступу к функциональности сервиса в коде middleware используйте ProcessRepositoryManager.

[[process-runtime-service]]
=== ProcessRuntimeService

Служит для работы с экземпляром процесса (ProcInstance).

Основные методы:

* startProcess() - запуск процесса. В Activiti engine создаются соответствующие объекты. В ProcInstance заполняется дата процесса и стартовый комментарий. При запуске автоматически заполняются следующие процессные переменные:
** bpmProcInstanceId - ID сущности ProcInstance
** entityId - ID связанной сущности
** entityName - имя связанной сущности
* cancelProcess() - удаляет процесс из Activiti engine. Все незавершенные задачи ProcTask завершаются. Объекту ProcInstance проставляется дата завершения и признак отмены.
* completeProcTask() - завершение текущей задачи ProcTask. Производится сигнал Activiti engine и процесс переходит на следующий этап. В экземпляр ProcTask проставляется время завершения, результат и комментарий.
* claimProcTask() - назначение задачи, не имеющей владельца на конкретного пользователя.

Для доступу к функциональности сервиса в коде middleware используйте ProcessRuntimeManager.

[[process-form-service]]
=== ProcessFormService

Служит для получения информации о выходах из задачи, формах, которые должны быть показаны пользователю при выборе того или иного выхода, а также для получения информации о формах старта и отмены процесса.

[[process-messages-service]]
=== ProcessMessagesService

Служит для доступа к локализованным сообщениям, определенным в процессе. Для доступу к функциональности сервиса в коде middleware используйте ProcessMessagesManager.

[[model-service]]
=== ModelService

Используется для создания, обновления моделей во внутренних таблицах Activiti, а также для получения JSON модели.