[[services]]
== Основные сервисы

Раздел содержит общее описание сервисов. Описание методов сервисов находится в Javadoc в исходном коде классов.

[[process_repository_service]]
=== ProcessRepositoryService

Служит для работы с описаниями процесса (`ProcDefinition`). Сервис использутся для:

* загрузки описания процесса из XML;
* удаления процесса из Activiti engine;
* преобразования JSON модели в BPMN XML.

Для доступа к функциональности сервиса в коде middleware используйте `ProcessRepositoryManager`.

[[process_runtime_service]]
=== ProcessRuntimeService

Служит для работы с экземпляром процесса (`ProcInstance`). Методы сервиса позволяют:

* запускать процесс;
* отменять процесс;
* завершать задачу;
* назначать задачу на пользователя.

Для доступа к функциональности сервиса в коде middleware используйте `ProcessRuntimeManager`.

[[process_form_service]]
=== ProcessFormService

Служит для получения информации о выходах из задачи, формах, которые должны быть показаны пользователю при выборе того или иного выхода, а также для получения информации о формах старта и отмены процесса.

Для доступа к функциональности сервиса в коде middleware используйте `ProcessFormManager`.

[[process_messages_service]]
=== ProcessMessagesService

Служит для доступа к локализованным сообщениям, определенным в процессе. 

Для доступа к функциональности сервиса в коде middleware используйте `ProcessMessagesManager`.

[[model_service]]
=== ModelService

Используется для создания, обновления моделей во внутренних таблицах Activiti, а также для получения JSON-модели.