[[ui_components]]
== Компоненты UI

[[proc_actions_frame]]
=== ProcActionsFrame

`ProcActionsFrame` - фрейм для работы с процессными действиями. После инициализации во фрейме автоматически отобразятся:

* кнопка запуска процесса, если процесс не запущен;
* кнопки, соответствующие выходам из задачи, если процесс запущен и текущий пользователь имеет активную задачу;
* кнопка отмены процесса;
* информация о задаче (имя и дата создания).

Каждому из действий возможно задать предикат, вычисляемый перед выполнением этого действия, что позволяет сделать проверку возможности выполнения действия в настоящее время (например, выполнить коммит экрана и в случае неудачи не выполнять процессное действие). Также можно задать слушатель, который будет выполнен после завершения действия (например, закрыть экран редактирования сущности и отобразить сообщение пользователю).

`ProcActionsFrame` должен быть связан с экземпляром `ProcInstance`. Связывание происходит во время инициализации фрейма.

.Пример инициализации фрейма
[source,java]
----
include::{sourcesdir}/quickstart/ProcActionsFrameInitialization.java[]
----

* Метод `initializer()` возвращает объект, используемый для инициализации фрейма.

* Метод `setBeforeStartProcessPredicate` устанавливает предикат, который будет вычислен перед выполнением запуска процесса. Если предикат вернет `false`, запуск процесса будет прерван.

* Метод `setAfterStartProcessListener` задает слушатель, который будет вызыван после завершения действия запуска процесса.

* Самое главное - метод `init` принимает два параметра: код процесса и экземпляр сущности. При вызове этого метода происходит поиск объекта `ProcInstance`, связанного с указанным экземпляром сущности и ссылающимся на `ProcDefinition` с указанным кодом. Если `ProcInstance` существует, фрейм связывается с ним, если нет, то создается новый объект `ProcInstance`.

О прочих методах, выполняющих настройку фрейма, можно узнать из javadoc класса.

[[process_forms]]
=== Процессные формы

[[proc_form_interface]]
==== Интерфейс ProcForm

При определении выхода (outcome) для задачи и в узле начала процесса возможно указать форму, которая будет показана пользователю. Форма должна реализовывать интерфейс `ProcForm`.
Методы интерфейса `ProcForm`:

* `String getComment()` - значение, возвращаемое этим методом, будет записано в поле `comment` объекта ProcTask при завершении задачи или в поле `startComment` у ProcInstance если форма отображается на старте процесса;
* `Map<String, Object> getFormResult()` - возвращает список объектов, которые будут добавлены к переменным процесса после коммита формы.

[[bpm_forms]]
==== Задание списка форм для дизайнера моделей процесса

Список форм, доступный в дизайнере моделей процесса, формируется на основе конфигурационных файлов, определенных свойством приложения `bpm.formsConfig`. Для добавления новой процессной формы выполните следующие шаги:

. Создайте и зарегистрируйте экран для новой формы. Контроллер экрана должен реализовывать интерфейс `ProcForm`.

. Создайте файл с конфигурацией для новых процессных форм. Положите его в директорию `src` модуля *web* или *gui*.
+
.app-bpm-forms.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns="http://schemas.haulmont.com/cuba/bpm-forms.xsd">
    <form name="myCustomForm" defult="true">
        <param name="someParam" value="hello"/>
        <param name="otherParam"/>
    </form>
</forms>
----
+
`myCustomForm` - идентификатор экрана.
+
Помимо имени форм в файле определены имена возможных параметров формы и их значения по умолчанию.
+
Форма с атрибутом `default="true"` будет использоваться в дизайнере как форма по умолчанию.

. Переопределите свойство `bpm.formsConfig` в файле `web-app.properties`.
+
[source]
----
bpm.formsConfig = bpm-forms.xml app-bpm-forms.xml
----