:sourcesdir: ../../../source

[[pivotTable_extension]]
=== Экспорт данных из PivotTable

`PivotTableExtension` - это расширение компонента `PivotTable`, которое предоставляет API для скачивания таблицы с агрегированными данными в формате XLS-файла.

Для добавления этой функциональности необходимо создать экземпляр расширения в контроллере экрана с помощью конструктора класса расширения (т.е., не с помощью `ComponentsFactory`), например:

[source, java]
----
@Inject
private PivotTable pivotTable;

private PivotTableExtension extension;

@Override
public void init(Map<String, Object> params) {
    extension = new WebPivotTableExtension(pivotTable);
}
----

[TIP]
====
Расширение поддерживает только следующие типы <<chart_PivotTable_renderers,рендереров>>: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP`, `ROW_HEATMAP`, кроме того, оно не получает данных о цвете ячеек таблицы.
====

[[pivotTable_extension_xls]]
Чтобы скачать таблицу как файл XLS, нужно вызвать метод `exportTableToXls()`, например, по клику на кнопку:

[source, java]
----
extension.exportTableToXls();
----

По умолчанию, имя скачиваемого файла совпадает с локализованным именем сущности из источника данных `PivotTable`. Другое имя файла можно задать с помощью метода `setFileName()`:

[source, java]
----
extension.setFileName("Orders of " + new Date());
----

[TIP]
====
Формат XLS имеет ограничение в 65536 строк в одном файле. Если `PivotTable` содержит более 65536 строк, при экспорте содержимое будет обрезано, и пользователь увидит соответствующее предупреждение.
====

[[pivotTable_extension_data]]
Дополнительно, расширение `PivotTableExtension` предоставляет ещё два способа получения данных из `PivotTable`:

* данные в формате JSON:
+
[source, java]
----
extension.getPivotDataJSON();
----

* сериализованный объект `PivotData`:
+
[source, java]
----
extension.getPivotData();
----

[[chart_PivotTable_ShowPivotAction]]
==== Экспорт с помощью ShowPivotAction

`ShowPivotAction` - это особое действие, позволяющее экспортировать данные из компонентов - наследников `ListComponent`, таких как `Table`, `Tree` и `DataGrid`, и представлять их в виде сводной таблицы. По сути, это простой инструмент для BI-анализа, не требующий установки дополнительных компонентов приложения.

Действие `ShowPivotAction` можно создать программно в контроллере экрана и присвоить его некоторой кнопке, к примеру:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction.java[]
----

`ShowPivotAction` предоставляет два способа экспорта данных: только выделенные строки и все строки. Если в таблице не выделена ни одна строка, диалоговое окно выбора не будет показано, и по умолчанию будут экспортированы все строки.

После нажатия кнопки в новой вкладке появится редактируемая таблица `PivotTable`. По умолчанию, в этой таблице отображаются все атрибуты, включенные в источник данных компонента, кроме следующих:

* атрибуты-коллекции,
* байтовые массивы,
* атрибуты с типом UUID,
* аннотированные `@SystemLevel`.

Если вы хотите исключить некоторые атрибуты или, наоборот, включить выборочно только часть из них, используйте методы fluent API:

* `withIncludedProperties()` для включения атрибутов, например:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_2.java[]
----

* `withExcludedProperties()` для исключения атрибутов, например:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_3.java[]
----

Эти методы принимают список имен атрибутов. Некорректные имена будут проигнорированы.

Вы можете изменить конфигурацию сводной таблицы по умолчанию, использовав метод `withNativeJson()`, который принимает конфигурацию в формате JSON-строки. Обратите внимание, что в нём используются локализованные имена атрибутов:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_4.java[]
----

Ниже приведена структура JSON для нередактируемой сводной таблицы:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_5.java[]
----

А здесь - структура JSON для редактируемой сводной таблицы:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_6.java[]
----

Отображенные в сводной таблице данные можно легко скачать в формате Excel-файла, если выбран поддерживаемый рендерер. Кнопка экспорта по умолчанию будет отображена на открывшейся вкладке.
