:sourcesdir: ../../../source

[[pivotTable_ShowPivotAction]]
=== Использование ShowPivotAction

`ShowPivotAction` - это особое действие, позволяющее экспортировать данные из компонентов - наследников `ListComponent`, таких как `Table`, `Tree` и `DataGrid`, и представлять их в виде сводной таблицы. По сути, это простой инструмент для BI-анализа, не требующий установки дополнительных компонентов приложения.

Действие `ShowPivotAction` можно создать программно в контроллере экрана и присвоить его некоторой кнопке, к примеру:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction.java[]
----

`ShowPivotAction` предоставляет два способа экспорта данных: только выделенные строки и все строки. Если в таблице не выделена ни одна строка, диалоговое окно выбора не будет показано, и по умолчанию будут экспортированы все строки.

После нажатия кнопки в новой вкладке появится редактируемая таблица `PivotTable`. По умолчанию, в этой таблице отображаются все атрибуты, включенные в источник данных компонента, кроме следующих:

* атрибуты-коллекции,
* байтовые массивы,
* атрибуты с типом UUID,
* аннотированные `@SystemLevel`.

Если вы хотите исключить некоторые атрибуты или, наоборот, включить выборочно только часть из них, используйте методы fluent API:

* `withIncludedProperties()` для включения атрибутов, например:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_2.java[]
----

* `withExcludedProperties()` для исключения атрибутов, например:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_3.java[]
----

Эти методы принимают список имен атрибутов. Некорректные имена будут проигнорированы.

Вы можете изменить конфигурацию сводной таблицы по умолчанию, использовав метод `withNativeJson()`, который принимает конфигурацию в формате JSON-строки. Обратите внимание, что в нём используются локализованные имена атрибутов:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_4.java[]
----

Ниже приведена структура JSON для нередактируемой сводной таблицы:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_5.java[]
----

А здесь - структура JSON для редактируемой сводной таблицы:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_6.java[]
----

Отображенные в сводной таблице данные можно легко скачать в формате Excel-файла, если выбран поддерживаемый рендерер. Кнопка экспорта по умолчанию будет отображена на открывшейся вкладке.
