:sourcesdir: ../../../source

[[pivotTable_extension]]
=== Экспорт данных из PivotTable

`PivotTableExtension` - это расширение компонента `PivotTable`, которое предоставляет API для скачивания таблицы с агрегированными данными в формате XLS-файла.

Для добавления этой функциональности необходимо создать экземпляр расширения в контроллере экрана с помощью конструктора класса расширения (т.е., не с помощью `UiComponents`), например:

[source, java]
----
@Inject
private PivotTable pivotTable;

private PivotTableExtension extension;

@Override
public void init(Map<String, Object> params) {
    extension = new WebPivotTableExtension(pivotTable);
}
----

[TIP]
====
Расширение поддерживает только следующие типы <<chart_PivotTable_renderers,рендереров>>: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP`, `ROW_HEATMAP`, кроме того, оно не получает данных о цвете ячеек таблицы.
====

[[pivotTable_extension_xls]]
Чтобы скачать таблицу как файл XLS, нужно вызвать метод `exportTableToXls()`, например, по клику на кнопку:

[source, java]
----
extension.exportTableToXls();
----

По умолчанию, имя скачиваемого файла совпадает с локализованным именем сущности из источника данных `PivotTable`. Другое имя файла можно задать с помощью метода `setFileName()`:

[source, java]
----
extension.setFileName("Orders of " + new Date());
----

[TIP]
====
Формат XLS имеет ограничение в 65536 строк в одном файле. Если `PivotTable` содержит более 65536 строк, при экспорте содержимое будет обрезано, и пользователь увидит соответствующее предупреждение.
====

[[pivotTable_extension_data]]
Дополнительно, расширение `PivotTableExtension` предоставляет ещё два способа получения данных из `PivotTable`:

* данные в формате JSON:
+
[source, java]
----
extension.getPivotDataJSON();
----

* сериализованный объект `PivotData`:
+
[source, java]
----
extension.getPivotData();
----
