:sourcesdir: ../../../source

[[execution_history_cleanup]]
=== Cleanup the History

You can configure the execution history cleanup procedure to remove unnecessary data and prevent the infinite growing a table.

. Create and activate a {main_man_url}/scheduled_tasks_cuba.html[scheduled task]. Go to the *Administration > Scheduled Tasks* screen of your application. Create a new task and set the following parameters:
+
--
* *Bean Name* = `reporting_ExecutionHistoryRecorder`
* *Method Name* = `cleanupHistory()`
* *Cron* = nightly, e.g. `0 0 1 * * *`
* *Singleton* – yes (this is important only for a cluster of middleware servers)
--
+
Save the task and click *Activate* on it.
+
If you did not set up the execution of the scheduled tasks for this project before, nothing would happen on this stage – the task will not be executed until you start the whole scheduling mechanism with the {main_man_url}/app_properties_reference.html#cuba.schedulingActive[cuba.schedulingActive] application property.

. Set up the configuration properties:
+
--
* <<reporting.executionHistory.cleanup.days,reporting.executionHistory.cleanup.days>> – 730 days by default.
* <<reporting.executionHistory.cleanup.itemsPerReport,reporting.executionHistory.cleanup.itemsPerReport>> – 1000 by default.
--

When the report execution history is cleaned up, the associated output document is also deleted from the file storage.