:sourcesdir: ../../../../../../source

[[messageTools]]
====== MessageTools

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/core/global/MessageTools.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

<<managed_beans,ManagedBean>>, содержащий вспомогательные методы работы с <<localization,локализованными сообщениями>>. Интерфейс `MessageTools` можно получить либо методом `Messages.getTools()`, либо как любой другой бин - инжекцией или через класс `AppBeans`. 

Методы `MessageTools`:

[[messageTools.loadString]]
* `loadString()` - возвращает локализованное сообщение, заданное ссылкой вида `msg://{messagePack}/{key}`.
+
Составные части ссылки:

** `msg://` - обязательный префикс.

** `{messagePack}` - необязательное имя пакета сообщения. Если не указано, предполагается, что имя пакета передается в `loadString()` отдельным параметром.

** `{key}` - ключ сообщения в пакете.
+
Примеры ссылок на сообщения:
+
[source, plain]
----
msg://someMessage
msg://com.abc.sales.web.customer/someMessage
----

* `getEntityCaption()` - возвращает локализованное название сущности.

* `getPropertyCaption()` - возвращает локализованное название атрибута сущности.

* `hasPropertyCaption()` - определяет, задано ли для атрибута сущности локализованное название. 

* `getMessageRef()` - формирует для <<metaProperty,мета-свойства>> ссылку на сообщение, по которой можно получить локализованное название атрибута сущности.

* `getDefaultLocale()` - возвращает локаль приложения по умолчанию, то есть указанную первой в списке свойства <<cuba.availableLocales,cuba.availableLocales>>.

* `useLocaleLanguageOnly()` - возвращает `true`, если в списке поддерживаемых приложением локалей, заданном свойством <<cuba.availableLocales,cuba.availableLocales>>, для всех локалей определен только язык, а `country` и `variant` не указаны. Этим методом пользуются механизмы платформы, которым необходимо найти наиболее подходящую локаль из списка поддерживаемых на основе локали, полученной из внешних источников, таких как операционная система или HTTP запрос.

* `trimLocale()` - удаляет из переданной локали все кроме языка, если метод `useLocaleLanguageOnly()` возвращает `true`.

Для расширения набора вспомогательных методов в конкретном приложении бин `MessageTools` можно <<bean_extension,переопределить>>. Примеры работы с расширенным интерфейсом:

[source, java]
----
MyMessageTools tools = messages.getTools();
tools.foo();
----

[source, java]
----
((MyMessageTools) messages.getTools()).foo();
---- 

