:sourcesdir: ../../../../../source

[[gui_ScreenFacet]]
===== ScreenFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/ScreenFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`ScreenFacet` – это невизуальный компонент, который обеспечивает возможность предварительной настройки <<opening_screens,открытия экранов>> и <<screen_parameters,передачи параметров в экраны>>. Диалоговое описание экрана заменяет существующий метод `ScreenBuilders.screen()`. `ScreenFacet` определяется в элементе `facets` XML-дескриптора экрана.

XML-имя компонента: `screen`.

Пример использования:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_ScreenFacet_example.xml[]
----

Экран, настроенный с помощью `ScreenFacet`, может быть показан явно с помощью метода `show()`:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_ScreenFacet_show.java[]
----

Кроме того, фасет может быть подписан на действие (см. атрибут <<gui_NotificationFacet_onAction,onAction>>) или кнопку (см. атрибут <<gui_NotificationFacet_onButton,onButton>>) по идентификатору.

`screen` имеет следующие атрибуты:

[[gui_ScreenFacet_screenId]]
* `screenId` – задаёт идентификатор открываемого экрана.

[[gui_ScreenFacet_screenClass]]
* `screenClass` – задаёт Java-класс контроллера открываемого экрана.

[[gui_ScreenFacet_openMode]]
* `openMode` – режим открытия экрана, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, `NEW_WINDOW`, `ROOT`, `THIS_TAB`. Значением по умолчанию является `NEW_TAB`.

[[gui_ScreenFacet_properties]]
`ScreenFacet` может содержать элемент `properties`, представляющий собой список параметров, которые будут переданы в открываемый экран через публичные setter-методы контроллера. См. также <<screen_parameters,Передача параметров в экраны >>.

'''

Атрибуты screen ::
<<gui_attr_id,id>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_ScreenFacet_openMode,openMode>> -
<<gui_ScreenFacet_screenClass,screenClass>> -
<<gui_ScreenFacet_screenId,screenId>>

Элементы screen ::
<<gui_ScreenFacet_properties,properties>>

