:sourcesdir: ../../../../../source

[[gui_DataLoadCoordinator]]
===== DataLoadCoordinator

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.1/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/DataLoadCoordinator.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

<<gui_facets,Фасет>> `DataLoadCoordinator` предназначен для декларативного связывания загрузчиков данных с контейнерами данных, визуальными компонентами и событиями экрана. Он может работать в двух режимах:

* В автоматическом режиме компонент полагается на имена параметров, имеющие специальные префиксы. Префикс указывает, какой компонент является источником значения параметра и событий его изменения. Если у загрузчика нет параметров в тексте запроса (при этом параметры могут быть в <<gui_data_loader_query_conditions,условиях>>), то он срабатывает по событию <<screen_BeforeShowEvent,BeforeShowEvent>> в `Screen` или по событию <<screenFragment_AttachEvent,AttachEvent>> в `ScreenFragment`.
+
По умолчанию используется префикс `container_` для контейнеров данных и `component_` для визуальных компонентов.

* В ручном режиме связи указываются в XML-разметке компонента или через его API.

Возможен также полуавтоматический режим, при котором некоторые связи задаются явно, а остальные конфигурируются автоматически.

При использовании `DataLoadCoordinator` в экране, аннотация <<LoadDataBeforeShow_annotation,@LoadDataBeforeShow>> на контроллере экрана не оказывает эффекта: загрузка данных полностью управляется компонентом `DataLoadCoordinator` и кастомными обработчиками событий, если они определены.

Ниже приведены примеры использования компонента.

. Автоматическая конфигурация. Атрибут `auto` установлен в `true`.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/dataLoadCoordinator_1.xml[]
----
<1> - в запросе нет параметров, поэтому загрузчик `ownersDl` сработает на событие экрана `BeforeShowEvent`.
<2> - загрузчик `ownersDl` также сработает на изменение значения компонента `categoryFilterField`.
<3> - загрузчик `ownersDl` также сработает на изменение значения компонента `nameFilterField`. Так как условие использует оператор `like`, значение будет автоматически завернуто в '(?i)% %' для того, чтобы обеспечить <<datasource_query_case_insensitive,нечувствительный к регистру поиск>>.
<4> - загрузчик `petsDl` сработает при смене выбранной сущности в контейнере `ownersDc`.

. Ручная конфигурация. Атрибут `auto` отсутствует или установлен в `false`, вложенные элементы определяют, когда должны сработать загрузчики.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/dataLoadCoordinator_2.xml[]
----
<1> - загрузчик `ownersDl` сработает на событие экрана `InitEvent`.
<2> - загрузчик `ownersDl` также сработает на изменение значения компонента `categoryFilterField`.
<3> - загрузчик `ownersDl` также сработает на изменение значения компонента `nameFilterField`. Атрибут `likeClause` приводит к заворачиванию значения в '(?i)% %' для того, чтобы обеспечить <<datasource_query_case_insensitive,нечувствительный к регистру поиск>>.
<4> - загрузчик `petsDl` сработает при смене выбранной сущности в контейнере `ownersDc`.

. Полуавтоматическая конфигурация. Когда атрибут `auto` установлен в `true` и объявлены некоторые вручную сконфигурированные связи, компонент автоматически сконфигурирует все загрузчики, для которых не указано ни одной связи вручную.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/dataLoadCoordinator_3.xml[]
----
<1> - загрузчик `petsDl` сконфигурирован автоматически и сработает при смене выбранной сущности в контейнере `ownersDc`.
<2> - загрузчик `ownersDl` сконфигурирован вручную и сработает на событие экрана `InitEvent`.
