:sourcesdir: ../../../../../source

[[gui_EditorScreenFacet]]
===== EditorScreenFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/EditorScreenFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=screen-facet" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`EditorScreenFacet` – это невизуальный компонент, который обеспечивает возможность предварительной настройки <<opening_screens,экрана редактирования>>. Декларативное описание экрана редактирования заменяет существующий метод `ScreenBuilders.editor()`. `EditorScreenFacet` определяется в элементе `facets` XML-дескриптора экрана.

XML-имя компонента: `editorScreen`.

Пример использования:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_EditorScreenFacet_example.xml[]
----
Экран, настроенный с помощью `EditorScreenFacet`, может быть показан явно с помощью метода `show()`:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_EditorScreenFacet_show.java[]
----

Кроме того, фасет может быть подписан на действие (см. атрибут <<gui_NotificationFacet_onAction,onAction>>) или кнопку (см. атрибут <<gui_NotificationFacet_onButton,onButton>>) по идентификатору.

`editorScreen` имеет следующие атрибуты:

[[gui_EditorScreenFacet_addFirst]]
* `addFirst` – определяет, будет ли новый элемент добавлен в начало или в конец коллекции. Влияет только на самостоятельные контейнеры; для <<gui_property_containers,вложенных контейнеров>> новые элементы всегда добавляются в конец.

[[gui_EditorScreenFacet_container]]
* `container` – устанавливает <<gui_collection_container,CollectionContainer>>. Контейнер обновляется после коммита экрана. Если контейнер является <<gui_property_containers,вложенным>>, фреймворк автоматически инициализирует ссылку на родительскую сущность и настраивает контекст данных для редактирования композиций.

[[gui_EditorScreenFacet_editMode]]
* `editMode` – задает режим редактирования экрана, задаваемый значением перечисления `EditMode`: `CREATE` (для создания нового экземпляра сущности) или `EDIT` (для редактирования существующего).

[[gui_EditorScreenFacet_entityClass]]
* `entityClass` – полное имя класса сущности.

[[gui_EditorScreenFacet_field]]
* `field` – задает идентификатор компонента <<gui_PickerField,PickerField>>. Если это поле задано, фреймворк устанавливает закоммиченную сущность в качестве значения поля после успешного коммита экрана редактирования.

[[gui_EditorScreenFacet_listComponent]]
* `listComponent` – задает идентификатор компонента списка. Компонент используется для получения <<gui_EditorScreenFacet_container,контейнера>>, если он не установлен. Обычно компонент списка представляет собой <<gui_Table,таблицу>> или <<gui_DataGrid,DataGrid>>, отображающую список сущностей.

'''

Атрибуты editorScreen ::
<<gui_EditorScreenFacet_addFirst,addFirst>> -
<<gui_EditorScreenFacet_container,container>> -
<<gui_EditorScreenFacet_editMode,editMode>> -
<<gui_EditorScreenFacet_entityClass,entityClass>> -
<<gui_EditorScreenFacet_field,field>> -
<<gui_attr_id,id>> -
<<gui_EditorScreenFacet_listComponent,listComponent>>
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_ScreenFacet_openMode,openMode>> -
<<gui_ScreenFacet_screenClass,screenClass>> -
<<gui_ScreenFacet_screenId,screenId>>

Элементы editorScreen ::
<<gui_ScreenFacet_properties,properties>>
