:sourcesdir: ../../../../../source

[[gui_NotificationFacet]]
===== NotificationFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/NotificationFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`NotificationFacet` – это невизуальный компонент, который обеспечивает возможность предварительной настройки <<gui_notifications,уведомлений>>. Декларативное описание уведомления заменяет существующий метод `Notifications.create()`. `NotificationFacet` определяется в элементе `facets` XML-дескриптора экрана.

XML-имя компонента: `notification`.

Пример использования:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_example.xml[]
----

Экран, настроенный с помощью `NotificationFacet`, может быть показан явно с помощью метода `show()`:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_show.java[]
----

`notification` имеет следующие атрибуты:

[[gui_NotificationFacet_onAction]]
* атрибут `onAction` содержит идентификатор <<gui_Action,действия>>, после выполнения которого будет показано уведомление.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_onAction.xml[]
----

[[gui_NotificationFacet_onButton]]
* атрибут `onButton` содержит идентификатор <<gui_Button,кнопки>>, после нажатия на которую будет показано уведомление.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_onButton.xml[]
----

[[gui_NotificationFacet_htmlSanitizerEnabled]]
* Если атрибут <<gui_notifications_contentMode,contentMode>> установлен в `true`, вы можете сделать доступной HTML санитизацию для содержимого уведомления, используя атрибут `htmlSanitizerEnabled`.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_htmlSanitizer.xml[]
----
+
Значение атрибута `htmlSanitizerEnabled` имеет приоритет над значением глобального свойства <<cuba.web.htmlSanitizerEnabled,cuba.web.htmlSanitizerEnabled>>.

'''

Атрибуты notification::
<<gui_attr_caption,caption>> -
<<gui_notifications_contentMode,contentMode>> -
<<gui_notifications_delay,delay>> -
<<gui_notifications_description,description>> -
<<gui_NotificationFacet_htmlSanitizerEnabled,htmlSanitizerEnabled>> -
<<gui_attr_id,id>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_notifications_position,position>> -
<<gui_attr_stylename,stylename>> -
<<gui_notifications_type,type>>