:sourcesdir: ../../../../../source

[[gui_InputDialogFacet]]
===== InputDialogFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/InputDialogFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=dialog-facet" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`InputDialogFacet` – это невизуальный компонент, который обеспечивает возможность предварительной настройки <<gui_input_dialog,Input Dialog>>. Декларативное описание диалога ввода заменяет существующий метод `Dialogs.createInputDialog()`. `InputDialogFacet` определяется в элементе `facets` XML-дескриптора экрана.

XML-имя компонента: `inputDialog`.

Пример использования:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_InputDialogFacet_example.xml[]
----

Экран, настроенный с помощью `InputDialogFacet`, может быть показан явно с помощью метода `show()`:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_InputDialogFacet_show.java[]
----

Кроме того, фасет может быть подписан на действие (см. атрибут <<gui_NotificationFacet_onAction,onAction>>) или кнопку (см. атрибут <<gui_NotificationFacet_onButton,onButton>>) по идентификатору.

[[gui_InputDialogFacet_defaultActions]]
В дополнение к атрибутам, описанным для <<gui_OptionDialogFacet,OptionDialogFacet>>, диалог ввода имеет атрибут `defaultActions`, который определяет набор предопределенных действий для использования в диалоговом окне. Стандартные значения:

* `OK`
* `OK_CANCEL`
* `YES_NO`
* `YES_NO_CANCEL`

Значение по умолчанию – `OK_CANCEL`.

*элементы inputDialog:*

[[gui_InputDialogFacet_actions]]
* элемент `actions` представляет собой список <<gui_option_dialog_actions,диалоговых действий>>.

[[gui_InputDialogFacet_parameters]]
* элемент `parameters` может содержать следующие параметры:

** `stringParameter`
** `booleanParameter`
** `intParameter`
** `doubleParameter`
** `longParameter`
** `bigDecimalParameter`
** `dateParameter`
** `timeParameter`
** `dateTimeParameter`
** `entityParameter`
** `enumParameter`

Чтобы реализовать кастомную логику для диалогового действия, нужно создать соответствующий метод-обработчик в контроллере.

Для обработки результатов, полученных в диалоге ввода, нужно создать соответствующий делегат:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_InputDialogFacet_handleResult.java[]
----

Атрибуты inputDialog ::

<<gui_attr_caption,caption>> -
<<gui_message_dialog_contentMode,contentMode>> -
<<gui_InputDialogFacet_defaultActions,defaultActions>> -
<<gui_message_dialog_width_height,height>> -
<<gui_attr_id,id>> -
<<gui_message_dialog_withMaximized,maximized>> -
<<gui_message_dialog_message,message>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_attr_stylename,stylename>> -
<<gui_message_dialog_width_height,width>>

Элементы inputDialog ::
<<gui_OptionDialogFacet_actions,actions>> -
<<gui_InputDialogFacet_parameters,parameters>>