:sourcesdir: ../../../../../source

[[gui_Timer]]
===== Timer

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Timer.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=timer" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

Таймер − это <<gui_facets,фасет>>, позволяющий выполнять некоторый код контроллера экрана через определенные промежутки времени. Срабатывание таймера происходит в потоке обработки событий пользовательского интерфейса, что позволяет обновлять экран без каких-либо ограничений. Таймер прекращает работу при закрытии экрана, для которого он был создан.

Основной способ создания таймеров - декларативно в XML-дескрипторе экрана в элементе `facets`.

Для описания таймера используется элемент `timer`.

* Атрибут `delay` является обязательным атрибутом, в нем задается интервал срабатывания таймера в миллисекундах.

* `autostart` - необязательный атрибут, при установке которого в `true` таймер стартует сразу после открытия экрана. По умолчанию `false`, что означает что для старта таймера необходимо вызвать его метод `start()`.

* `repeating` − необязательный атрибут, включает многократное срабатывание таймера. Если значение атрибута равно `true`, то таймер выполняется циклически, через равные промежутки времени, заданные в атрибуте `delay`. В противном случае таймер выполняется один раз через `delay` миллисекунд после старта таймера.

Для выполнения некоторого кода по таймеру, создайте подписку на событие `TimerActionEvent` в контроллере экрана.

Пример объявления таймера и подписки на него в контроллере:

[source, xml]
----
include::{sourcesdir}/gui_facets/timer_1.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_facets/timer_2.java[]
----

Таймер можно инжектировать в поле контроллера, либо получить методом `Window.getFacet()`. Управлять активностью таймера можно с помощью его методов `start()` и `stop()`. Для уже активного таймера вызов `start()` игнорируется. После остановки таймера методом `stop()` его можно снова запустить методом `start()`.

Пример определения таймера в XML дескрипторе и использования листенеров в контроллере:

[source, xml]
----
include::{sourcesdir}/gui_facets/timer_3.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_facets/timer_4.java[]
----

<1> обработчик выполнения таймера

<2> остановка таймера

<3> запуск таймера при инициализации экрана

Таймер можно также создавать в коде контроллера, при этом необходимо явно добавить таймер к экрану с помощью метода `addFacet()`, к примеру:

[source, java]
----
include::{sourcesdir}/gui_facets/timer_5.java[]
----

<1> добавление таймера к экрану

<2> установка параметров таймера

<3> добавление обработчика выполнения

<4> добавление слушателя остановки таймера

<5> запуск таймера
