:sourcesdir: ../../../../../source

[[gui_OptionDialogFacet]]
===== OptionDialogFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/OptionDialogFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=dialog-facet" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

`OptionDialogFacet` – это невизуальный компонент, который обеспечивает возможность предварительной настройки <<gui_option_dialog,Option Dialog>>. Декларативное описание диалога выбора заменяет существующий метод `Dialogs.createOptionDialog()`. `OptionDialogFacet` определяется в элементе `facets` XML-дескриптора экрана.

XML-имя компонента: `optionDialog`.

Пример использования:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_OptionDialogFacet_example.xml[]
----

Экран, настроенный с помощью `OptionDialogFacet`, может быть показан явно с помощью метода `show()`:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_OptionDialogFacet_show.java[]
----

Кроме того, фасет может быть подписан на действие (см. атрибут <<gui_NotificationFacet_onAction,onAction>>) или кнопку (см. атрибут <<gui_NotificationFacet_onButton,onButton>>) по идентификатору.

[[gui_OptionDialogFacet_actions]]
Диалог выбора содержит элемент `actions`, который представляет собой список <<gui_option_dialog_actions,диалоговых действий>>.

Чтобы реализовать кастомную логику для диалогового действия, нужно создать соответствующий метод-обработчик в контроллере:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_OptionDialogFacet_installDelegate.java[]
----

<1> - обработчик, вызываемый при нажатии на кнопку *OK* в диалоге выбора.
<2> - обработчик, вызываемый при нажатии на кнопку *Cancel* в диалоге выбора.

'''

Атрибуты optionDialog ::

<<gui_attr_caption,caption>> -
<<gui_message_dialog_contentMode,contentMode>> -
<<gui_message_dialog_width_height,height>> -
<<gui_NotificationFacet_htmlSanitizerEnabled,htmlSanitizerEnabled>> -
<<gui_attr_id,id>> -
<<gui_message_dialog_withMaximized,maximized>> -
<<gui_message_dialog_message,message>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_attr_stylename,stylename>> -
<<gui_message_dialog_width_height,width>>

Элементы optionDialog ::
<<gui_OptionDialogFacet_actions,actions>>

