:sourcesdir: ../../../../../source

[[rest_api_v2_ex_get_entities_list]]
===== Получение списка экземпляров сущности

Предположим, в системе имеется сущность `sales$Order`, и необходимо получить список экземпляров этой сущности. При этом, необходимо получить не все записи, а 50 записей, начиная с сотой (для отображения третьей странице в каком-либо списке клиентского приложения). Кроме простых атрибутов сущности `sales$Order` результат должен содержать данные о клиенте (поле `customer`). Заказы должны быть отсортированы по дате.

Базовый URL для получения списка экземпляров сущности `sales$Order`:

`\http://localhost:8080/app/rest/v2/entities/sales$Order`

Для выполнения описанных выше условий необходимо задать параметры запроса:

* *view* - <<views, представление>>, с которым должны быть загружены сущности. В нашем примере представление `order-edit-view` содержит ссылку на `customer`.
* *limit* - количество возвращаемых экземпляров.
* *offset* - позиция первого извлеченного элемента.
* *sort* - имя атрибута сущности, по которому будет произведена сортировка.

OAuth-токен должен быть передан в заголовке запроса `Authorization` с типом *Bearer*:

  Authorization: Bearer 29bc6b45-83cd-4050-8c7a-2a8a60adf251

В итоге получаем следующий *GET* http-запрос:

`\http://localhost:8080/app/rest/v2/entities/sales$Order?view=order-edit-view&limit=50&offset=100&sort=date`

В https://curl.haxx.se/[cURL] запрос может выглядеть так:

[source, plain]
----
include::{sourcesdir}/rest/rest_api_v2_ex_get_entities_list.txt[]
----

Ответ будет выглядеть следующим образом:

[source, json]
----
include::{sourcesdir}/rest/rest-orders-list-response.json[]
----

Обратите внимание, что для каждой сущности загружаются атрибуты `_entityName` с именем сущности и `_instanceName`, содержащий результат вычисления <<namePattern_annotation, короткого имени>> для сущности.

