:sourcesdir: ../../../../../source

[[rest_api_v2_ex_query_get]]
===== Выполнение JPQL-запроса (GET)

Перед выполнением запроса с помощью REST API необходимо описать его в <<rest_api_v2_queries_config, конфигурационном файле>>. В корневом пакете модуля *web* (например, `com.company.sales`) необходимо создать файл `rest-queries.xml`. Затем этот файл объявляется в файле свойств приложения модуля *web* (web-app.properties):

[source, properties]
----
cuba.rest.queriesConfig = +com/company/sales/rest-queries.xml
----

Содержимое файла `rest-queries.xml`:

[source, xml]
----
include::{sourcesdir}/rest/sales-rest-queries.xml[]
----

Для выполнения JPQL запроса, необходимо выполнить *GET* http-запрос к REST API:

`\http://localhost:8080/app/rest/v2/queries/sales$Order/ordersAfterDate?startDate=2016-11-01&endDate=2017-11-01`

Части URL:

* `sales$Order` - имя извлекаемой сущности.
* `ordersAfterDate` - имя запроса из конфигурационного файла.
* `startDate` и `endDate` - параметры запроса со значениями.

OAuth-токен должен быть передан в заголовке запроса `Authorization` с типом *Bearer*.

Метод возвращает JSON-массив со списком извлеченных экземпляров сущности:

[source, json]
----
include::{sourcesdir}/rest/rest-ordersAfterDate-query-response.json[]
----

Список других возможных параметров для метода выполнения запросов можно посмотреть в {rest_swagger_url}[Swagger документации].

