:sourcesdir: ../../../source

[[create_project]]
=== Создание нового проекта

С помощью CUBA Studio легко создавать приложения на платформе с нуля. Запустите мастер *New Project* и выполняйте шаги, описанные ниже:

. В окне *Welcome to CUBA Studio* выберите *Create New Project*.

. Выберите *CUBA Project*.

. Вы можете принять настройки доступа к репозиториям платформы по умолчанию или {main_man_url}/access_to_repo.html[изменить] их для конкретного проекта. Затем нажмите *Next*.

. Введите имя нового проекта в поле *Project name*. Имя должно содержать только латинские буквы, цифры и знак подчеркивания. Тщательно продумайте имя проекта на данном этапе, так как в дальнейшем изменить его будет достаточно сложно.

. В полях ниже автоматически сгенерируются:
+
--
* *Project location* – путь к каталогу нового проекта. Путь можно изменить, введя адрес каталога вручную или нажав на кнопку *...* рядом с полем.

* *Project namespace* – пространство имен, которое будет использоваться как префикс имен сущностей и таблиц базы данных. Пространство имен может состоять только из латинских букв и должно быть как можно короче.

* *Root package* − корневой (или основной) пакет Java-классов проекта. Может быть скорректирован позже, однако сгенерированные на этапе создания классы перемещены не будут.

* *Platform version* – используемая в проекте версия платформы. Артефакты платформы будут автоматически загружены из репозитория при сборке проекта.
--

. Нажмите *Finish*. В указанном каталоге будет создан пустой проект, и в главном окне Studio начнётся сборка проекта по скриптам Gradle и индексирование файлов проекта.

. После окончания процессов синхронизации и индексации вы увидите представление проекта в виде CUBA-дерева в боковой панели *Project*. На этом этапе можно начинать работу с проектом.