:sourcesdir: ../../../source

[[open_project]]
=== Открытие существующего проекта

Открытие уже импортированного проекта::
+
--
Если проект ранее уже был открыт в CUBA Studio на данном компьютере, достаточно сделать следующее:

* Используйте список недавних проектов или нажмите *Open*, выберите _папку проекта_ в диалоговом окне файловой системы и нажмите на кнопку *Open*.

* Дождитесь завершения синхронизации Gradle и индексации файлов проекта. Когда откроется представление с CUBA-деревом в окне инструментов *Project*, можно начинать работу с проектом.
--

Первое открытие проекта::
+
--
Если проект ранее не был открыт в CUBA Studio на данном компьютере (например, вы только что импортировали его из VCS), необходимо сделать следующие шаги:

* Нажмите *Open* и выберите файл `build.gradle` проекта в диалоговом окне файловой системы, затем нажмите на кнопку *Open*.

* Выберите *Open as Project* в диалоговом окне *Open Project*.

* Далее в окне *Import Project from Gradle*:
** поставьте флажок *Use auto-import*;
** выберите `Use JAVA_HOME` в поле *Gradle JVM*. Если вы не видите этого варианта в выпадающем списке, убедитесь, что вы правильно настроили окружение согласно инструкции в разделе {main_man_url}/setup.html[Установка и настройка инструментария] основного руководства по разработке приложений;
** выберите `.idea (directory based)` в поле *Project format*;
** нажмите *OK*.

* Дождитесь завершения синхронизации Gradle и индексации файлов проекта. Когда откроется представление с CUBA-деревом в окне инструментов *Project*, можно начинать работу с проектом.
--

Первое открытие проекта на платформе CUBA версии 6.10::
+
--
CUBA Studio поддерживает работу с проектами, использующими версии платформы 6.10+ и 7.0. Вы можете открыть проект, созданный в предыдущей версии Studio, и импортировать его в новую Studio следующим образом:

. Удалите старые файлы IntelliJ с помощью задачи `gradlew cleanIdea` в командной строке.

. Если проект находится под контролем версий Git, добавьте строку `.idea` в файл `.gitignore`, расположенный в корневом каталоге проекта. Так вы избежите попадания ваших локальных настроек IDE в проекты других разработчиков.

. Откройте файл `build.gradle`, как описано выше в секции *Первое открытие проекта*.
--