:sourcesdir: ../../../source

[[open_project]]
=== Открытие существующего проекта

Открытие уже импортированного проекта::
+
--
Если проект ранее уже был открыт в CUBA Studio на данном компьютере, достаточно сделать следующее:

. Используйте список недавних проектов; или нажмите *Open*, выберите _папку проекта_ в диалоговом окне файловой системы и нажмите на кнопку *Open*.

. Дождитесь завершения синхронизации Gradle и индексации файлов проекта. Когда откроется дерево проекта CUBA в окне инструментов *Project*, можно начинать работу с проектом.
--

Первое открытие проекта::
+
--
Если проект ранее не был открыт в CUBA Studio на данном компьютере (например, вы только что импортировали его из VCS), необходимо сделать следующее:

. Нажмите *Open* и выберите файл `build.gradle` проекта в диалоговом окне файловой системы, затем нажмите на кнопку *Open*.

. Выберите *Open as Project* в диалоговом окне *Open Project*.

. Далее в окне *Import Project from Gradle*:
* поставьте флажок *Use auto-import*;
* выберите `Use JAVA_HOME` в поле *Gradle JVM*. Если вы не видите такого пункта в выпадающем списке, убедитесь, что вы правильно настроили окружение согласно инструкции в разделе {main_man_url}/setup.html[Установка и настройка] руководства по разработке приложений;
* нажмите *OK*.

. Дождитесь завершения синхронизации Gradle и индексации файлов проекта. В окне инструментов *Project* должно появиться дерево проекта CUBA.

. Выберите *File > Project Structure* в главном меню.
* Убедитесь, что поле *Project SDK* имеет значение, соответствующее переменной окружения `JAVA_HOME` установленной в вашей операционной системе. Если вы видите значение `<No SDK>`, то нажмите *New* и выберите каталог установки нужного JDK, например `/Users/me/lib/jdk8u202-b08`.
* Убедитесь, что поле *Project language level* имеет значение, соответствующее версии выбранного JDK. Например, если JDK версии `1.8`, то уровень языка должен быть `8 - Lambdas, type annotations, etc.`
--

Первое открытие проекта на платформе CUBA версии 6.10::
+
--
CUBA Studio поддерживает работу с проектами, использующими версии платформы 6.10+ и 7.0. Вы можете открыть проект, созданный в предыдущей версии Studio, и импортировать его в новую Studio.

Имейте в виду, что CUBA 6 поддерживает только Java 8, поэтому ваша переменная `JAVA_HOME` должна указывать на каталог установки JDK 8. Позже, после миграции на CUBA 7, вы сможете выбрать более новый JDK, если это необходимо.

Выполните следующие шаги для первого открытия проекта, использующего CUBA 6.10:

. Если ваш проект использует премиум-дополнения (Reports, BPM, etc.) и у вас есть подписка, необходимо прописать имя и пароль доступа к репозиторию в файле `~/.gradle/gradle.properties` как описано в {main_man_url}/access_to_repo.html#access_to_premium_repo[документации].

. Удалите старые файлы IntelliJ с помощью задачи `gradlew cleanIdea` в командной строке.

. Если проект находится под управлением Git, добавьте строку `.idea` в файл `.gitignore`, расположенный в корневом каталоге проекта. Так вы избежите попадания локальных настроек IDE в рабочую среду других разработчиков вашего проекта.

. Откройте файл `build.gradle`, как описано выше в секции *Первое открытие проекта*.
--