:sourcesdir: ../../../source

[[upgrade_project]]
=== Обновление проекта

В этом разделе описан процесс обновления проекта до более новой версии платформы.

[TIP]
====
Мы рекомендуем настроить контроль версий для проекта и всегда делать commit планируемых изменений до изменения версии платформы. Это даст вам возможность видеть изменения и откатить их на предыдущую версию в случае, если обновление по каким-либо причинам завершится неудачей.
====

* Откройте проект, следуя инструкции в <<open_project,предыдущем разделе>>.

* Выберите *CUBA > Project Properties* в основном меню либо дважды нажмите на *Project > Properties* в дереве проекта CUBA.

* В открывшемся окне *CUBA Project Properties* выберите желаемую версию платформы в поле *Platform version*.
+
[WARNING]
====
Если вы используете репозиторий `repo.cuba-platform.com`, вам будут доступны SNAPSHOT-версии платформы. Мы категорически не рекомендуем использовать эти версии в промышленной эксплуатации.
====

* Нажмите *OK*, затем подтвердите изменения.

* Если вы обновляетесь до нового feature release (к примеру, с 6.10.X до 7.0.X или с 7.0.Y до 7.1.Y), появится диалоговое окно *Migration Required*. В этом окне содержится информация об этапах миграции, которые Studio выполнит автоматически. Ознакомьтесь с этой информацией и нажмите *Migrate*.

* Studio выполнит автоматическую миграцию (при необходимости) и выполнит задачи Gradle `clean` и `undeploy`.

* Если вы обнрвляетесь до нового feature release, просмотрите раздел _Breaking Changes_ в {rel_notes_url}[Release Notes] и при необходимости внесите соответствующие изменения в ваш проект.

* Попробуйте собрать проект, выполнив команду *CUBA > Build Tasks > Assemble*. Просмотрите журнал вывода и поправьте код, если в логах есть сообщения об ошибках компиляции.

* Выполните команду *CUBA > Update Database*, чтобы применить возможные изменения в системных таблицах платформы к базе данных вашего проекта.