:sourcesdir: ../../../../../../source

[[cdb_xml_descriptor]]
====== XML-дескриптор экрана

Откройте в CUBA Studio вкладку *GENERIC UI* и создайте экран в модуле *web*. Введите значение `column3d-chart.xml` в поле *Descriptor*. В полях *Id*, *Controller Name* и *Messages Pack* будут сгенерированы подходящие значения. Сохраните изменения. Далее перейдите на вкладку *XML* и замените ее содержимое на следующий код:

[source, xml]
----
include::{sourcesdir}/chart/column3d-chart.xml[]
----

В корневой элемент дескриптора экрана добавлен атрибут `xmlns:chart`:

[source, xml]
----
<window xmlns:chart="http://schemas.haulmont.com/charts/charts.xsd"
    ...
    >
----

Диаграмма получает данные из источника `countryGrowthDs`, указанного в атрибуте `datasource`. Для отображения названий и значений используются атрибуты `country`, `year2014` и `year2015` сущности `CountryGrowth`, список экземпляров которой находится в источнике данных.

Компонент `chart:serialChart` содержит следующие атрибуты:

* `angle` - определяет угол наклона диаграммы. Может принимать значения от `0` до `90`.

* `balloonText` - определяет текст всплывающей подсказки при наведении на колонку диаграммы. Доступны для использования тэги `\[[value]]`, `\[[title]]`, `\[[persents]]`, `\[[description]]`, а также ключи из `DataItem`, список которых хранится в экземпляре `DataProvider`, либо имена атрибутов сущности в источнике данных. Для использования `html` тегов, их нужно экранировать.

* `depth3D` - толщина диаграммы. При использовании совместно с атрибутом `angle` позволяет создать эффект объема.

* `plotAreaFillAlphas` - степень непрозрачности области графика.

* `startDuration` - длительность анимации в секундах.

* `categoryField` - ключ из набора пар, содержащихся в объектах `DataItem`, список которых хранится в экземпляре `DataProvider`, по которому будут взяты значения для подписи оси категорий.

Компонент `chart:serialChart` содержит следующие элементы:

* `chart:categoryAxis` - элемент, описывающий ось категорий.
** Атрибут `gridPosition` определяет будет ли линия сетки расположена по центру ячейки или от ее начала.

* `chart:valueAxes` - элемент, описывающий вертикальные оси значений. В данном случае используется только одна ось, описываемая элементом `chart:axis`
** Атрибут `position` задает положение оси значений относительно диаграммы.
** Установка атрибуту `stackType` значения `BOX_3D` говорит о том, что колонки гистограммы будут расположены одна позади другой.

* `chart:graphs` - элемент, описывающий графы диаграммы. Граф описывается элементом `chart:graph`.
** Атрибут `type` задает тип графа и может быть: line, column, step line, smoothed line, ohlc и candlestick.
** Атрибут `valueField`определяет ключ из набора пар, содержащихся в объектах DataItem, список которых хранится в экземпляре DataProvider, по которому будет взято значение.
** Атрибут `fillAlphas` задает степень непрозрачности заполнения.
** Атрибут `lineAlpha` задает степень непрозрачности линии (или рамки колонки).

* `chart:export` – добавляет возможность сохранить полученный график.

