:sourcesdir: ../../../../source

[[polymer_in_studio]]
==== Polymer UI in Studio

In order to add the Polymer client module to your project, open it in CUBA Studio and click *Create module > Create polymer client module* on the *Project Properties* navigator tab.
Studio will create the *polymer-client* module in the project and configure it in `build.gradle`. The module will contain an application stub that is able to connect to the REST API and login/logout user to the middleware.

After creating the module, start the application server and open `++http://localhost:8080/app-front++` in a web browser. You will be presented with a login form. After logging in, the main window with a vertical menu and responsive layout will be shown.

In order to create a UI screen working with an entity, select an entity in Studio navigator and click *New > Polymer UI component*. Select a template (e.g. *Entity cards list with editor*), fill in required properties and click *Create*. The web component will be created and added to the menu. Studio provides hot-deploy of Polymer components, so you just need to refresh the page in the browser and you will see the newly created screen in the menu.

