:sourcesdir: ../../../../source

[[structure_jpql]]
==== JPQL Dataset

*JPQL* dataset is produced as result of JPQL query execution. The resulted query fields must have aliases provided using the `as` operator. You can use report input parameters and parent bands fields in the JPQL query, similar to SQL query.

Below is an example of a JPQL query with a `groupId` parameter, obtained from the `group` parent band and an external `active` parameter:

[source, jpql]
----
select u.name as userName, u.login as userLogin
from sec$User u
where u.group.id = ${group.groupId}
    and u.active = ${active}
----

JPQL queries automatically support soft deletion and return only records which are not deleted.

You can also activate <<query_preprocessing,query preprocessing>> by checking the *Preprocess query as Groovy template* checkbox below the band editor.

By default, JPQL queries use entities mapped to the the main database. If you want to query entities from an additional data store (see Developer's Manual), set its name in the *Data store* field.

