:sourcesdir: ../../../../source

[[structure_json]]
==== JSON Dataset

*JSON* dataset is generated from JSON data. This data can be received from the following sources:

. *Groovy script*
+
--
The script provided by the user is supposed to return JSON data as a string.

For example:

[source, json]
----
include::{sourcesdir}/json.groovy[]
----
--

. *URL*
+
--
The report engine will perform a GET HTTP query against the URL.

For example:

[source, plain]
----
https://jsonplaceholder.typicode.com/users
----
--

. *Parameter of a String type*
+
--
The report external parameter of String type which contains the JSON data must be described in the *Parameters and Formats* tab.
--

The received JSON tree is queried using the JsonPath query. For example, you can use the `$.store.book[*]` JsonPath to return all books from the following JSON tree:

[source, json]
----
include::{sourcesdir}/json.json[]
----

For more details on JsonPath expressions see http://goessner.net/articles/JsonPath/.

[WARNING]
====
Fields outputted by the report that have `Date`, `DateTime`, or `Time` data types do not support the format defined by `java.text.SimpleDateFormat`. To set the correct format, you should write a Groovy script.

To do this, switch to the **Parameters and Formats** tab of the report editor and open the <<formatters,formatter>> editor. For example, for the field `bookPublication.dateTime` Groovy-script will look like this:

[source, groovy]
----
include::{sourcesdir}/formatter_for_dates.groovy[]
----
====

