:sourcesdir: ../../../../source

[[log_dir]]
==== Каталог журналов

Состав и настройка файлов журналов определяются конфигурацией фреймворка *Logback*. По умолчанию в приложении используется файл конфигурации `logback.xml`, предоставляемый платформой в корне classpath. В соответствии с его настройками, вывод лога осуществляется в  standard output.

Для того чтобы указать собственную конфигурацию, необходимо передать системное свойство Java <<logback.configurationFile,logback.configurationFile>> с путем к файлу конфигурации. В разделе <<logging_setup_tomcat>> приведена информации по настройке в случае <<fast_deployment,быстрого развертывания>>.

Содержимое `logback.xml` определяет, где будут расположены файлы логов. Это может быть подкаталог внутри некоторого каталога Tomcat (`tomcat/logs` в случае быстрого развертывания), или подкаталог <<app_home,домашнего каталога>> приложения. Управлять расположением можно, если взять `logback.xml` из каталога `deploy/tomcat/conf` проекта и изменить свойство `logDir`, например:

[source,xml]
----
include::{sourcesdir}/deployment/log_dir_1.xml[]
----

Приложение должно знать, где расположены файлы логов, для того, чтобы позволить администраторам просматривать и загружать их в экране *Administration > Server Log*. Поэтому установите свойство приложения <<cuba.logDir,cuba.logDir>> в тот же каталог, который задается в `logback.xml`.

См. также <<logging, Логирование>>.

