:sourcesdir: ../../../../../source

[[deployment]]
==== Deployment Settings

Studio contains editors for setting up Gradle tasks that build deployment artifacts. These editors can be opened through the *CUBA > Deployment* main menu or by double-clicking the items in *Project > Deployment* project tree section.

*WAR Settings* editor allows you to set up building of WAR files. After completing the setup, the {main_man_url}/build.gradle_buildWar.html[buildWar] task will be created in your `build.gradle`.

* *Build WAR* - if checked, the `buildWar` task is configured in `build.gradle`.

* *Include JDBC driver* - whether JDBC driver should be included in WAR file.

* *Include Tomcat's context.xml* - whether `context.xml` (Tomcat deployment descriptor) should be included in WAR file.

* *Custom context.xml path* - a path relative to the project root to the `context.xml` Tomcat deployment descriptor. Enabled if *Include Tomcat's context.xml* is checked. Click *Generate* to create this file automatically.

* *Single WAR for Middleware and Web Client* - whether to build a single WAR comprising the Middleware and Web Client application blocks.

* *Custom web.xml path* is the file to be used as a special `web.xml` of the single WAR. Click *Generate* to create this file automatically.

* *Logback configuration file* - a path relative to the project root to the `logback.xml` configuration file. Click *Generate* to create this file automatically.

* *App properties* - a set of application properties to define for this deployment. The properties will be added to the `/WEB-INF/local.app.properties` file inside the WAR.

*UberJAR Settings* editor allows you to set up building of an Uber JAR. After completing the setup, the {main_man_url}/build.gradle_buildUberJar.html[buildUberJar] task will be created in your `build.gradle`.

* *Build Uber JAR* - if checked, the `buildUberJar` task is configured in `build.gradle`.

* *Single Uber JAR* - if checked, the `buildUberJar` task creates a single Uber JAR from all application modules.

* *Logback configuration file* - a path relative to the project root to the `logback.xml` configuration file. Click *Generate* to create this file automatically.

* *Custom Jetty environment file* - a path relative to the project root to the `jetty-env.xml` configuration file to be used by the embedded Jetty server. Required field. Click *Generate* to create this file automatically.

* *App properties* - a set of application properties to define for this deployment. The properties will be added to the `/WEB-INF/local.app.properties` file inside the Uber JARs.

* *Core port, Web port, Portal port* fields allow you to set ports for the embedded servers of the corresponding application blocks. Not available if Single Uber JAR checked. Default port values are described in the {main_man_url}/build.gradle_buildUberJar.html[documentation]. You can also set ports when running the JARs using the `-port` command line argument.
