:sourcesdir: ../../../../../source

[[project_properties]]
==== Project Properties Editor

The *Project Properties* editor allows you to configure your project. You can open it from the *CUBA* main menu or by double-clicking the *Project > Properties* item of the project tree.

Main tab::
+
--
The *Main* tab displays the basic settings.

* The *Repositories* field display the repositories currently used in the project. Studio scans these repositories to discover what platform versions are available. Use the buttons next to the field to configure the access to repository. For more details see {main_man_url}/access_to_repo.html[documentation]. You can also manually register in `build.gradle` any number of additional repositories containing application components.

* The *Platform version* field allows you to select a version of the platform. If you choose a newer version, an automatic migration will be performed if required.

* In the *App components* panel, you can add the platform or custom application components that will be used in your project.

* If you need to change the path to the application server, specify the new path in the *Tomcat path* field. The next execution of `gradlew deploy` or `gradlew start` will install Tomcat into that location.

* The *Tomcat ports* group allows you to assign non-standard ports for the Tomcat application server installed in the `deploy/tomcat` folder as a result of {main_man_url}/fast_deployment.html[fast deployment].

* In particular, the *HTTP port* field affects the port Tomcat is listening on for HTTP connection, as well as `cuba.webPort`, `cuba.webAppUrl`, `cuba.restApiUrl` and `cuba.connectionUrlList` application properties.

* In the *AJP port* field, you can set the port for AJP Connector.

* In the *Shutdown port* field, you can set the port Tomcat is listening on for SHUTDOWN command.

* In the *Debug port* field, you can set the port Tomcat is listening on for Java debugger connection. If you change this port, you should also change it in the debug configuration of your IDE.

* *Available locales* field allows you to set {main_man_url}/localization.html[locales] used in your application. Open the locales editor by clicking the button next to the field. The *Locale select visible* checkbox located in the editor window controls the value of the {main_man_url}/app_properties_reference.html#cuba.localeSelectVisible[cuba.localeSelectVisible] application property. The editor also enables defining or overriding format strings for {main_man_url}/datatype.html[parsing and formatting data].

* *Groovy support* checkbox enables Groovy code within the application: for example, in screen controller classes.
--

Data Stores tab::
+
--
The *Data Stores* tab displays database connections of your project.

* The upper part of the editor contains settings of the main data store.

** You can select the type of your database server in the *Database type* field. The fields below allow you to change the database URL, and specify the username, password and optional connection parameters.

** Format of connection parameters depends on the selected DBMS. The string should include a separator between the database name and parameters. For example, to specify a Microsoft SQL Server 2008+ instance name, use the following string in the field:
+
[source]
----
;instanceName=myinstance
----

** A custom database connection URL can be specified if *Custom database URL* checkbox is enabled. *Host* and *Database* name should be provided in this case, as they are used in `build.gradle` separately.

** In case of HSQLDB the Studio itself serves the database and stores its files in the `build/hsqldb` directory.

* The *Additional data stores* panel contains the list of additional data stores registered in the project. The *Data Store* dialog appears when you create or edit an additional data store. It has the following fields:

** *Data store name* - the name of the data store. It may contain only alphanumeric characters and underscores and should be different from the project name.

** *Data store type* - the type of the data store: either `RdbmsStore` or `Custom`, see the documentation for details. The fields explained below should be set in case of `RdbmsStore`.

** *DataSource JNDI name* - automatically set by Studio on the basis of the data store name.

** *Database type*, *URL*, etc. - database connection parameters.
--