:sourcesdir: ../../../../../../source

[[gui_property_containers]]
====== Property Containers

`InstancePropertyContainer` and `CollectionPropertyContainer` are designed to work with entity instances and collections that are attributes of other entities. For example, if the `Order` entity that has the `orderLines` attribute which is a collection of the `OrderLine` entity, you can use `CollectionPropertyContainer` to bind `orderLines` to a table component.

Property containers implement the `Nested` interface which defines methods to get the master container and the name of its attribute to bind the property container to. In the example with `Order` and `OrderLine` entities, the master container is the one storing the `Order` instance.

`InstancePropertyContainer` works directly with the attribute of the master entity. It means that if you invoke its `setItem()` method, the value will be set to the corresponding master entity attribute and its `ItemPropertyChangeEvent` listener will be invoked.

`CollectionPropertyContainer` contains a copy of the master collection and its methods behave as follows:

* `getMutableItems()` returns the mutable list of entities and changes in the list are reflected in the underlying property. That is if you remove an item from this list, the master attribute will be changed and `ItemPropertyChangeEvent` listener will be invoked on the master container.

* `getDisconnectedItems()` returns the mutable list of entities, but changes in the list are not reflected in the underlying property. That is if you remove an item from this list, the master attribute will stay the same.

* `setItems()` sets a collection of entities to the container and to the underlying property. `ItemPropertyChangeEvent` listener is invoked on the master container.

* `setDisconnectedItems()` sets a collection of entities to the container, but the underlying master attribute will stay the same.

The `getDisconnectedItems()` and `setDisconnectedItems()` methods can be used to temporarily change the representation of the collection in UI, for example to filter a table:

[source, java]
----
include::{sourcesdir}/gui/data_containers/property_1.java[]
----
