:sourcesdir: ../../../../source

[[gauge_chart]]
==== AngularGaugeChart

The `AngularGaugeChart` component allows you to create gauge charts.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=gauge-chart" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

.GaugeChart
image::chart/gauge-chart.svg[align="center", width="800"]

XML name of the component: `chart:gaugeChart`.

Elements of `chart:gaugeChart`::
+
--
* `arrows` - includes the nested `arrow` elements for the chart arrow axes.
+
[source, xml]
----
<chart:arrows>
    <chart:arrow value="60"/>
</chart:arrows>
----

* `axes` - includes the nested `axis` elements for the chart axes.
+
[source, xml]
----
include::{sourcesdir}/chart/chart_axes.xml[]
----
+
The `band` element enables you to split an axis into several bands, as on the picture above:
+
[source, xml]
----
include::{sourcesdir}/chart/chart_axes_band.xml[]
----
+
The `endValue` and `startValue` attributes are used to set the range of values on the chart, the `valueInterval` attribute defines the gauge scale marks.
--

`AngularGaugeChart` event listeners: ::
+
--
* `ChartClickListener` - click on the canvas.
* `ChartRightClickListener` - right click on the canvas.
--

For more details, see http://docs.amcharts.com/3/javascriptcharts/AmAngularGauge[AmCharts documentation].

