:sourcesdir: ../../../../../source

[[rest_api_v2_social_login]]
===== Social Login in REST API

The mechanism of social login can be used in REST API too. The complete sample application is available on https://github.com/cuba-platform/sample-social-login/[GitHub] and described in the <<social_login>> section, below are the key points of getting an access token with a Facebook account.

. Create the `restapi` package under the root package of *web* module and implement the custom Spring MVC controller in it. This controller should contain two main methods: `get()` to get a `ResponseEntity` instance and `login()` to obtain an OAuth token.
+
--
[source,java]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/src/com/company/demo/restapi/FacebookAuthenticationController.java[FacebookAuthenticationController.java]
----
include::{sourcesdir}/rest/social_login_rest_1.java[]
----

Here we check the Facebook code, obtain an access code and issue the access token using `OAuthTokenIssuer`:

[source,java]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/src/com/company/demo/restapi/FacebookAuthenticationController.java[FacebookAuthenticationController.java]
----
include::{sourcesdir}/rest/social_login_rest_2.java[]
----
--

. Exclude the `restapi` package from scanning in *web/core* modules: the `OAuthTokenIssuer` bean is available only in REST API context, and scanning for it in the application context will cause an error.
+
[source, xml]
----
include::{sourcesdir}/rest/social_login_rest_5.xml[]
----

. Create the `facebook-login-demo.html` file in the `modules/web/web/VAADIN` folder of your project. It will contain the JavaScript code running on HTML page:
+
--
[source, html]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/web/VAADIN/facebook-login-demo.html[facebook-login-demo.html]
----
include::{sourcesdir}/rest/social_login_rest_3.html[]
----

The following script will try to login with Facebook. Firstly, it will remove code parameters from URL, then it will pass the code to REST API to get an OAuth access token, and in case of successful authentication we will be able to load and save data as usual.

[source, js]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/web/VAADIN/facebook-login-demo.html[facebook-login-demo.html]
----
include::{sourcesdir}/rest/social_login_rest_4.js[]
----

Another example or running a JavaScript code from CUBA applications you can find in the <<rest_api_v2_ex_javascript_usage>> section.
--

