:sourcesdir: ../../../../source

[[logging_setup_desktop]]
==== Setting up Logging in The Desktop Client

For the desktop client, the logback.xml file should be located in the source files directory of the project's *desktop* module. When an application is built, it is packed into the corresponding JAR file and is accessible in CLASSPATH.

Make the following steps to set up logging for your project:

* Create a new file, for example `sample-logback.xml`, in the `src` directory of the *desktop* module, and copy the contents of `cuba-logback.xml` to this new file. `cuba-logback.xml` file is located in one of the platform's JAR files and can be easily found using search in the IDE.

* Define path to a log file in the `file` parameter of the `FILE` appender.

* Add settings for loggers of your project.

* In the <<gui_desktop,inheritor class>> of `com.haulmont.cuba.desktop.App` of your project, for example `SampleApp`, override the `getDefaultLogConfig()` method and use it to return the path to your log file relative to the CLASSPATH root. For example:
+
[source, java]
----
include::{sourcesdir}/development/logging_2.java[]
----

* If necessary, you can override the location of the configuration file at the application start using <<logback.configurationFile,logback.configurationFile>> system property.

