:sourcesdir: ../../../../../source

[[own_component_samples]]
===== Создание собственных визуальных компонентов

В разделе <<own_components>> был приведен обзор методов расширения набора стандартных визуальных компонентов в проекте. У вас есть следующие варианты:

. Подключение аддона Vaadin. Много сторонних компонентов Vaadin распространяются в виде дополнений (add-on). Библиотека аддонов находится по адресу https://vaadin.com/directory.

. Подключение компонента, написанного на JavaScript. Vaadin дает возможность создавать серверные компоненты, использующие JavaScript-библиотеку.

. Создание собственного компонента Vaadin с клиентской частью, написанной на GWT.

Далее вы можете интегрировать получившийся компонент Vaadin в универсальный пользовательский интерфейс CUBA, чтобы иметь возможность использовать его декларативно в XML-дескрипторах экранов и привязывать к источникам данных.

Финальным шагом интеграции является поддержка нового компонента в WYSIWYG редакторе экранов Studio.

Далее в этом разделе приводятся примеры создания новых визуальных компонентов каждым из описанных выше способов. Интеграция в Generic UI одинакова для всех трех способов, поэтому она описана только для примера с подключением аддона Vaadin.

include::own_component_samples/vaadin_addon_sample.adoc[]

include::own_component_samples/vaadin_addon_sample_gui.adoc[]

include::own_component_samples/js_library_sample.adoc[]

include::own_component_samples/gwt_component_sample.adoc[]

include::own_component_samples/own_component_in_studio.adoc[]

