:sourcesdir: ../../../../source

[[gui_data]]
==== Компоненты данных

Компоненты данных представляют собой невизуальные элементы экрана, которые обеспечивают загрузку данных со среднего слоя, связь данных с визуальными компонентами и отправку измененных экземпляров обратно на Middleware. В платформе имеются следующие типы компонентов данных:

* <<gui_data_containers,Контейнеры>> - тонкий слой между сущностями и визуальными компонентами, связанными с данными (data-aware). Разные типы контейнеров могут хранить один экземпляр или коллекцию экземпляров сущностей.

* <<gui_data_loaders,Загрузчики>> загружают данные из Middleware в контейнеры.

* <<gui_DataContext,DataContext>> отслеживает изменения сущностей и сохраняет измененные экземпляры на Middleware по запросу.

Обычно компоненты данных задаются в XML-дескрипторе экрана внутри элемента `<data>`. Их можно инжектировать в контроллер экрана так же, как и визуальные компоненты:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_4.java[]
----

Компоненты данных конкретного экрана регистрируются в объекте `ScreenData`, который связан с контроллером экрана и доступен с помощью метода `getScreenData()` экрана. Этот объект полезен в прикладном коде, когда необходимо загрузить все данные экрана, к примеру:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_5.java[]
----

[TIP]
====
Обратите внимание, что экраны загружают данные автоматически, если контроллер экрана снабжен аннотацией `@LoadDataBeforeShow`. Поэтому программно вызывать загрузку нужно только если такой аннотации на контроллере нет или ее значение - `false`. Обычно это требуется, когда необходимо установить некоторые параметры загрузки данных, как в примере выше.
====

include::gui_data/gui_data_containers.adoc[]

include::gui_data/gui_data_loaders.adoc[]

include::gui_data/gui_DataContext.adoc[]

include::gui_data/gui_using_data_comp.adoc[]
