:sourcesdir: ../../../../source

[[gui_data]]
==== Компоненты данных

Компоненты данных представляют собой невизуальные элементы экрана, которые обеспечивают загрузку данных со среднего слоя, связь данных с визуальными компонентами и отправку измененных экземпляров обратно на Middleware. В платформе имеются следующие типы компонентов данных:

* <<gui_data_containers,Контейнеры>> - тонкий слой между сущностями и визуальными компонентами, связанными с данными (data-aware). Разные типы контейнеров могут хранить один экземпляр или коллекцию экземпляров сущностей.

* <<gui_data_loaders,Загрузчики>> загружают данные из Middleware в контейнеры.

* <<gui_DataContext,DataContext>> отслеживает изменения сущностей и сохраняет измененные экземпляры на Middleware по запросу.

Обычно компоненты данных задаются в XML-дескрипторе экрана внутри элемента `<data>`. Их можно инжектировать в контроллер экрана так же, как и визуальные компоненты.

Компоненты данных конкретного экрана регистрируются объектом `ScreenData`, который связан с контроллером экрана и доступен с помощью метода `getScreenData()` экрана. Этот объект позволяет загрузить все данные для этого экрана, к примеру:

[source, java]
----
@Subscribe
protected void onBeforeShow(BeforeShowEvent event) {
    getScreenData().loadAll();
}
----

[TIP]
====
Обратите внимание, что базовые классы экранов `StandardEditor`, `StandardLookup` и `MasterDetailScreen` загружают данные автоматически, если контроллер экрана снабжен аннотацией `@LoadDataBeforeShow`. Таким образом, если ваш экран унаследован напрямую от `Screen`, методы загрузки данных необходимо вызывать вручную.
====

include::gui_data/gui_data_containers.adoc[]

include::gui_data/gui_data_loaders.adoc[]

include::gui_data/gui_DataContext.adoc[]

include::gui_data/gui_using_data_comp.adoc[]
