:sourcesdir: ../../../../source

[[gui_notifications]]
==== Уведомления

Уведомления представляют собой небольшие окна, всплывающие в центре или в углу главного окна приложения. Они могут исчезать автоматически или когда пользователь щелкает по экрану или нажимает Esc.

Для того чтобы показать уведомление, необходимо инжектировать в контроллер экрана бин `Notifications` и воспользоваться его fluent-интерфейсом. В примере ниже уведомление показывается, когда пользователь щелкает по кнопке:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_1.java[]
----

Уведомление может иметь дополнительное описание, которое показывается под заголовком более мелким шрифтом:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_2.java[]
----

Уведомления могут быть следующих типов:

** `TRAY` - уведомление показывается в правом нижнем углу приложения и исчезает автоматически.

** `HUMANIZED` - стандартное уведомление в центре экрана, исчезает автоматически.

** `WARNING` - предупреждение. Исчезает при щелчке по экрану.

** `ERROR` - уведомление об ошибке. Исчезает при щелчке по экрану.

Тип по умолчанию - `HUMANIZED`. Другой тип можно указать в параметре метода `create()`:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_3.java[]
----

В тексте можно использовать символы `\n` для перевода строк. Для отображения HTML необходимо указать соответствующий параметр в методе `withContentMode()`:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_4.java[]
----

При использовании HTML обязательно экранируйте данные, полученные из БД, во избежание инжекции вредоносного кода.

Остальные методы, такие как `withHideDelayMs()`, `withPosition()` и `withStyleName()`, позволяют изменить параметры отображения и поведения уведомления.