:sourcesdir: ../../../../source

[[gui_notifications]]
==== Уведомления

Уведомления представляют собой небольшие окна, всплывающие в центре или в углу главного окна приложения. Они могут исчезать автоматически или когда пользователь щелкает по экрану или нажимает Esc.

Для того чтобы показать уведомление, необходимо инжектировать в контроллер экрана бин `Notifications` и воспользоваться его fluent-интерфейсом. В примере ниже уведомление показывается, когда пользователь щелкает по кнопке:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_1.java[]
----

[[gui_notifications_description]]
Уведомление может иметь дополнительное описание, которое показывается под заголовком более мелким шрифтом:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_2.java[]
----

[[gui_notifications_type]]
Уведомления могут быть следующих типов:

** `TRAY` – уведомление показывается в правом нижнем углу приложения и исчезает автоматически.

** `HUMANIZED` – стандартное уведомление в центре экрана, исчезает автоматически.

** `WARNING` – предупреждение. Исчезает при щелчке по экрану.

** `ERROR` – уведомление об ошибке. Исчезает при щелчке по экрану.

Тип по умолчанию – `HUMANIZED`. Другой тип можно указать в параметре метода `create()`:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_3.java[]
----

[[gui_notifications_contentMode]]
В тексте можно использовать символы `\n` для перевода строк. Для отображения HTML необходимо указать соответствующий параметр в методе `withContentMode()`:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_4.java[]
----

При использовании HTML обязательно экранируйте данные, полученные из БД, во избежание инжекции вредоносного кода.

Вы можете передать значение `true` в метод `withHtmlSanitizer()`, чтобы сделать доступной HTML санитизацию для текстового содержимого уведомления. Также в этом случае параметр `ContentMode.HTML` должен быть передан в метод `withContentMode()`.

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_5.java[]
----

Значение, переданное в метод `withHtmlSanitizer()`, имеет приоритет над значением глобального свойства <<cuba.web.htmlSanitizerEnabled,cuba.web.htmlSanitizerEnabled>>.

[[gui_notifications_position]]
Вы можете установить положение окна уведомления, используя метод `withPosition()`. Стандартные значения:

* `TOP_RIGHT`
* `TOP_LEFT`
* `TOP_CENTER`
* `MIDDLE_RIGHT`
* `MIDDLE_LEFT`
* `MIDDLE_CENTER`
* `BOTTOM_RIGHT`
* `BOTTOM_LEFT`
* `BOTTOM_CENTER`

[[gui_notifications_delay]]
Также вы можете установить задержку в миллисекундах до исчезновения уведомления, используя метод `withHideDelayMs()`. Значение `-1` используется для того, чтобы потребовать от пользователя щелкнуть сообщение.