:sourcesdir: ../../../../source

[[gui_screens]]
==== Экраны

Экран - основной элемент пользовательского интерфейса. Экран состоит из визуальных компонентов, контейнеров данных и других невизуальных компонентов. Экраны отображаются внутри главного окна приложения, в отдельной его вкладке либо в виде модального окна.

Основу экрана составляет Java-  или Groovy-класс, который называется <<screen_controllers,контроллером>>. Компоновка экрана обычно определяется в XML-файле, именуемом <<screen_descriptors,дескриптором>> экрана.

Чтобы отобразить экран, платформа создаёт новый экземпляр визуального компонента `Window`, подключает его к контроллеру экрана и загружает компоненты, входящие в компоновку экрана, в качестве дочерних компонентов окна. Затем окно этого экрана добавляется к главному экрану приложения.

Фрагмент - это еще один структурный элемент UI, который можно использовать в качестве компонента экранов или других фрагментов. Внутреннее устройство фрагмента аналогично экрану, но фрагмент имеет специфический жизненный цикл, а в корне иерархии визуальных компонентов находится `Fragment` вместо `Window`. Фрагменты, также как экраны, состоят из контроллеров и XML-дескрипторов.

include::gui_screens/screen_controllers.adoc[]

include::gui_screens/screen_descriptors.adoc[]

include::gui_screens/opening_screens.adoc[]

include::gui_screens/using_screen_fragments.adoc[]

include::gui_screens/screen_mixins.adoc[]

include::gui_screens/gui_root_screens.adoc[]

include::gui_screens/screen_validation.adoc[]