:sourcesdir: ../../../../source

[[gui_dialogs]]
==== Диалоговые окна

Интерфейс `Dialogs` предназначен для отображения стандартных диалоговых окон. Его методы `createMessageDialog()`, `createOptionDialog()` и `createInputDialog()` являются точками входа в fluent API, позволяющий конструировать и отображать диалоги.

Внешний вид диалоговых окон можно настроить с помощью переменных SCSS с префиксом `$cuba-window-modal-*`. Эти переменные можно изменить в визуальном редакторе после <<web_theme_extension,расширения темы>> или создания <<web_theme_creation,новой темы>>.

[[gui_message_dialog]]
Message Dialog::
+
--
В примере ниже диалог отображает сообщение при нажатии кнопки:

[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_dialogs_1.java[]
----

В тексте можно использовать символы `\n` для перевода строк. Для отображения HTML необходимо передать `ContentMode.HTML` в метод `withContentMode()`. При использовании HTML обязательно экранируйте данные, полученные из БД, во избежание инжекции вредоносного кода.

Следующие методы позволяют изменить параметры отображения и поведения диалога:

* `withModal()` - если передано `false`, диалог отображается как немодальный, что позволяет пользователю взаимодействовать с другими частями приложения.

* `withCloseOnClickOutside()` - если передано `true` и диалог модальный, то пользователь может закрыть диалог щелкнув на любой части окна приложения вне диалога.

* `withWidth()`, `withHeight()` позволяют указать желаемую геометрию диалога.

Например:

[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_dialogs_2.java[]
----
--

[[gui_option_dialog]]
Option Dialog::
+
--
Диалог выбора отображает некоторое сообщение и набор кнопок для выбора пользователем. При конструировании данного диалога необходимо передать в метод `withActions()` массив <<gui_Action,действий>>, для каждого из которых в диалоге создается кнопка. Например:

[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_dialogs_3.java[]
----

При нажатии на кнопку диалог закрывается и вызывается метод `actionPerform()` соответствующего действия.

В качестве кнопок со стандартными названиями и значками удобно использовать анонимные классы, унаследованные от `DialogAction`. Поддерживаются пять видов действий, определяемых перечислением `DialogAction.Type`: `OK`, `CANCEL`, `YES`, `NO`, `CLOSE`. Названия соответствующих кнопок извлекаются из <<main_message_pack,главного пакета>> локализованных сообщений.

Второй параметр конструктора `DialogAction` используется для задания визуального стиля кнопки, к которой привязано данное действие. Статус `Status.PRIMARY` подсвечивает кнопку и задаёт ей выделение по умолчанию, что обеспечивается стилем `c-primary-action`. Если для диалога задано несколько действий с `Status.PRIMARY`, то фокус и стиль получает только кнопка первого такого действия в списке.
--

[[gui_input_dialog]]
Input Dialog::
+
--
Диалог ввода - это мощный инструмент, позволяющий конструировать формы ввода с помощью API, который часто может избавить от необходимости создавать <<gui_screens,экраны>> для тривиального ввода данных. Он позволяет вводить значения разнообразных типов, валидировать их и предоставлять различные действия для выбора пользователем.

Рассмотрим несколько примеров.

. Диалог ввода с параметрами стандартных типов и стандартными действиями OK/Cancel:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_1.java[]
----
<1> - задает строковый обязательный параметр.
<2> - задает числовой параметр со значением по умолчанию.
<3> - задает параметр типа сущность.
<4> - задает параметр типа перечисление.
<5> - задает набор действий, представляемых кнопками внизу диалога.
<6> - в слушателе на закрытие можно определить, какое действие было выбрано пользователем.
<7> - событие закрытия содержит введенные значения, которые можно получить по идентификаторам параметров.

. Диалог ввода с нестандартным параметром:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_2.java[]
----
<1> - задает нестандартный параметр.
<2> - заголовок нестандартного параметра задается в создаваемом компоненте.
<3> - value of the custom parameter is obtained in the same way as for standard parameters.

. Диалог ввода с нестандартными действиями:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_3.java[]
----
<1> - метод `withActions()` может принимать массив кастомных действий.
<2> - в обработчике действия можно получить значение параметра из объекта диалога.
<3> - кастомное действие не закрывает диалог само, поэтому это надо сделать в какой-то момент явно.

. Диалог ввода с валидатором:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_4.java[]
----
<1> - кастомный валидатор в данном примере необходим для того, чтобы обеспечить ввод как минимум одного параметра из двух.
<2> - значения параметров в валидаторе можно получить через объект контекста.
--