:sourcesdir: ../../../../source

[[gui_Action]]
==== Действия. Интерфейс Action

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Action.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`Action` − интерфейс, абстрагирующий действие (другими словами, некоторую функцию) от визуального компонента. Он особенно полезен в случаях, когда одно и то же действие может быть вызвано из разных визуальных компонентов. Данный интерфейс задает некоторые общие свойства действий, такие как заголовок, горячая клавиша, признаки доступности и видимости, и другими.

Действия могут быть объявлены <<declarative_actions,декларативно>>, либо программно путем наследования от класса <<baseAction,BaseAction>>. Кроме того, существует набор предоставляемых фреймворком <<standard_actions,стандартных действий>>, применимых для работы с таблицами и компонентами выбора.

Визуальные компоненты, связанные с действием, могут быть двух типов:

* Визуальный компонент, содержащий одно действие, реализует интерфейс `Component.ActionOwner`. Это <<gui_Button,Button>> и <<gui_LinkButton,LinkButton>>.
+
Связь компонента с действием осуществляется путем вызова метода `ActionOwner.setAction()` компонента. В этот момент компонент заменяет свои свойства на соответствующие свойства действия (подробнее см. описание компонентов). 

* Визуальный компонент, содержащий несколько действий, реализует интерфейс `Component.ActionsHolder`. Это `Window`, `Frame`, <<gui_Table,Table>> и ее наследники, <<gui_Tree,Tree>>, <<gui_PopupButton,PopupButton>>, <<gui_PickerField,PickerField>>, <<gui_LookupPickerField,LookupPickerField>>.
+
Действия добавляются компоненту вызовом метода `ActionsHolder.addAction()`. Реализация этого метода в компоненте проверяет, нет ли уже в нем действия с таким же идентификатором. Если есть, то имеющееся действие будет заменено на новое переданное. Поэтому можно, например, декларировать стандартное действие в дескрипторе экрана, а затем в контроллере создать новое с переопределенными методами и добавить компоненту.

include::gui_Action/declarative_actions.adoc[]

include::gui_Action/standard_actions.adoc[]

include::gui_Action/custom_action_types.adoc[]

include::gui_Action/baseAction.adoc[]

