:sourcesdir: ../../../../source

[[gui_facets]]
==== Невизуальные компоненты

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

Экран может содержать невизуальные компоненты в элементе `facets` XML-дескриптора. Фреймворк предоставляет следующие невизуальные компоненты:

* <<gui_Timer,Timer>>
* <<gui_ClipboardTrigger,ClipboardTrigger>>
* <<gui_DataLoadCoordinator,DataLoadCoordinator>>

В приложении или аддоне можно создать собственные невизуальные компоненты. Для этого необходимо выполнить следующие шаги:

. Создайте интерфейс, расширяющий `com.haulmont.cuba.gui.components.Facet`.

. Создайте класс реализации на основе `com.haulmont.cuba.web.gui.WebAbstractFacet`.

. Создайте Spring бин реализующий интерфейс `com.haulmont.cuba.gui.xml.FacetProvider`, параметризованный типом компонента.

. Создайте XSD для использования компонента в XML-дескрипторах экранов.

Классы `ClipboardTrigger`, `WebClipboardTrigger` и `ClipboardTriggerFacetProvider` фреймворка могут служить хорошим примером создания невизуального компонента.

include::gui_facets/gui_Timer.adoc[]

include::gui_facets/gui_ClipboardTrigger.adoc[]

include::gui_facets/gui_DataLoadCoordinator.adoc[]
