:sourcesdir: ../../../../source

[[gui_facets]]
==== Фасеты

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.1/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

Фасеты - это элементы экрана, которые не добавляются в компоновку экрана, в отличие от визуальных компонентов. Вместо этого они добавляют дополнительное поведение к экрану или одному из его компонентов.

Экран может содержать фасеты в элементе `facets` XML-дескриптора. Фреймворк предоставляет следующие фасеты:

* <<gui_Timer,Timer>>
* <<gui_ClipboardTrigger,ClipboardTrigger>>
* <<gui_DataLoadCoordinator,DataLoadCoordinator>>
* <<gui_NotificationFacet,NotificationFacet>>
* <<gui_MessageDialogFacet,MessageDialogFacet>>
* <<gui_OptionDialogFacet,OptionDialogFacet>>
* <<gui_InputDialogFacet,InputDialogFacet>>
* <<gui_ScreenFacet,ScreenFacet>>
* <<gui_EditorScreenFacet,EditorScreenFacet>>
* <<gui_LookupScreenFacet,LookupScreenFacet>>

В приложении или аддоне можно создать собственные фасеты. Для этого необходимо выполнить следующие шаги:

. Создайте интерфейс, расширяющий `com.haulmont.cuba.gui.components.Facet`.

. Создайте класс реализации на основе `com.haulmont.cuba.web.gui.WebAbstractFacet`.

. Создайте Spring бин реализующий интерфейс `com.haulmont.cuba.gui.xml.FacetProvider`, параметризованный типом компонента.

. Создайте XSD для использования компонента в XML-дескрипторах экранов.

. Опционально, пометьте интерфейс фасета и его методы <<own_component_in_studio,специальными аннотациями>>, чтобы добавить поддержку вашего фасета в CUBA Studio.

Классы `ClipboardTrigger`, `WebClipboardTrigger` и `ClipboardTriggerFacetProvider` фреймворка могут служить хорошим примером создания фасета.

include::gui_facets/gui_Timer.adoc[]

include::gui_facets/gui_ClipboardTrigger.adoc[]

include::gui_facets/gui_DataLoadCoordinator.adoc[]

include::gui_facets/gui_NotificationFacet.adoc[]

include::gui_facets/gui_MessageDialogFacet.adoc[]

include::gui_facets/gui_OptionDialogFacet.adoc[]

include::gui_facets/gui_InputDialogFacet.adoc[]

include::gui_facets/gui_ScreenFacet.adoc[]

include::gui_facets/gui_EditorScreenFacet.adoc[]

include::gui_facets/gui_LookupScreenFacet.adoc[]