:sourcesdir: ../../../../source

[[gui_facets]]
==== Невизуальные компоненты

Экран может содержать невизуальные компоненты в элементе `facets` XML-дескриптора. Фреймворк предоставляет следующие невизуальные компоненты:

* <<gui_Timer,Timer>>
* <<gui_ClipboardTrigger,ClipboardTrigger>>

В приложении или аддоне можно создать собственные невизуальные компоненты. Для этого необходимо выполнить следующие шаги:

. Создайте интерфейс, расширяющий `com.haulmont.cuba.gui.components.Facet`.

. Создайте класс реализации на основе `com.haulmont.cuba.web.gui.WebAbstractFacet`.

. Создайте Spring бин реализующий интерфейс `com.haulmont.cuba.gui.xml.FacetProvider`, параметризованный типом компонента.

. Создайте XSD для использования компонента в XML-дескрипторах экранов.

Классы `ClipboardTrigger`, `WebClipboardTrigger` и `ClipboardTriggerFacetProvider` фреймворка могут служить хорошим примером создания невизуального компонента.

include::gui_facets/gui_Timer.adoc[]

include::gui_facets/gui_ClipboardTrigger.adoc[]
