:sourcesdir: ../../../../source

[[gui_web]]
==== Инфраструктура Web Client

Реализация универсального пользовательского интерфейса в <<app_tiers,блоке>> Web Client основана на фреймворке Vaadin. Рассмотрим основные классы, входящие в состав инфраструктуры веб-клиента.

.Классы инфраструктуры Web Client
image::WebClientInfrastructure.svg[align="center"]

* `App` - центральный класс инфраструктуры приложения. Позволяет получить ссылки на `Connection` и другие объекты инфраструктуры. Экземпляр `App` существует в единственном экземпляре для данной HTTP-сессии пользователя. Ссылку на `App` можно получить вызовом статического метода `App.getInstance()`. Если необходимо кастомизировать функциональность `App` в проекте, создайте класс, расширяющий `DefaultApp` в корневом пакете модуля *web* и зарегистрируйте его в <<spring.xml, web-spring.xml>> в качестве бина `cuba_App`, например:
+
[source, xml]
----
<bean name="cuba_App" class="com.company.sample.web.MyApp" scope="vaadin"/>
----

* `Connection` - интерфейс, обеспечивающий функциональность подключения к среднему слою и хранящий пользовательскую сессию <<userSession,UserSession>>. Стандартной реализацией этого интерфейса является класс `ConnectionImpl`.

* `ExceptionHandlers` - содержит коллекцию <<exceptionHandlers,обработчиков исключений клиентского уровня>>.

* `AppUI` - класс платформы, унаследованный от класса `com.vaadin.ui.UI`. Экземпляр данного класса соответствует одной открытой вкладке веб браузера. Содержит ссылку на реализацию интерфейса `TopLevelWindow` - это может быть либо окно логина, либо главное окно приложения, в зависимости от состояния подключения. Ссылку на `AppUI` можно получить вызовом статического метода `AppUI.getCurrent()`.

* `AppLoginWindow` - окно, отображаемое до логина пользователя. В конкретном приложении окно можно кастомизировать или создать новое с нуля, унаследовав класс от <<abstractWindow,AbstractWindow>>. В Studio это можно сделать, нажав *New > Screen* в секции *Generic UI > Screens* дерева проекта и выбрав шаблон *Login window* на вкладке *Legacy Screen Templates*. Если вы переопределяете метод `init()`, обязательно вызовите `super.init(params)`.

* `AppMainWindow` - главное окно приложения, отображаемое после логина пользователя. В конкретном приложении окно можно кастомизировать или создать новое с нуля, унаследовав класс от `AbstractMainWindow` и определив нужную компоновку в XML-дескрипторе. В Studio это можно сделать, нажав *New > Screen* в секции *Generic UI > Screens* дерева проекта и выбрав шаблон *Main window*  на вкладке *Legacy Screen Templates*. Если вы переопределяете метод `init()`, обязательно вызовите `super.init(params)`.
+
Без переопределения главного окна можно управлять некоторыми параметрами с помощью следующих свойств приложения:
+
--
** <<cuba.web.foldersPaneEnabled,cuba.web.foldersPaneEnabled>> - включает формирование <<folders_pane,панели папок>>.

** <<cuba.web.appWindowMode,cuba.web.appWindowMode>> - задает начальный режим главного окна: с вкладками или одноэкранный (`TABBED` или `SINGLE`). Пользователь впоследствии может задать желаемый режим через экран *Help* → *Settings*.

** <<cuba.web.maxTabCount,cuba.web.maxTabCount>> - в режиме представления главного окна с вкладками задает максимальное количество вкладок, которое может открыть пользователь. По умолчанию 7.
--

Для того, чтобы обрабатывать нажатия на кнопку *Back* браузера, реализуйте интерфейс `CubaHistoryControl.HistoryBackHandler` в ваших `TopLevelWindow` (окно логина и главное окно). Метод `onHistoryBackPerformed()` этого интерфейса вызывается вместо стандартного поведения браузера, если свойство приложения <<cuba.web.allowHandleBrowserHistoryBack,cuba.web.allowHandleBrowserHistoryBack>> установлено в true.

