:sourcesdir: ../../../../source

[[html_attributes]]
==== Атрибуты DOM и CSS

Платформа CUBA предоставляет специальный API для HTML-атрибутов, позволяющий устанавливать DOM и CSS атрибуты для визуальных компонентов.

DOM/CSS атрибуты можно установить программно с помощью бина `HtmlAttributes` и следующих его методов:

* `setDomAttribute()` - устанавливает DOM-атрибут для самого верхнего элемента UI-компонента. Он принимает идентификатор компонента, имя DOM-атрибута (например, `title`) и его значение.

* `setCssProperty()` - устанавливает CSS-свойство для самого верхнего элемента UI-компонента. Он принимает идентификатор компонента, имя CSS-свойства (например, `border-color`) и его значение.

Имена наиболее часто используемых DOM-атрибутов и CSS-свойств доступны как константы класса `HtmlAttributes`, однако вы можете использовать и свои собственные имена атрибутов.

[WARNING]
====
Будет ли атрибут работать с конкретным компонентом, зависит от этого компонента. Некоторые визуальные компоненты могут скрыто использовать те же атрибуты для своих собственных нужд, поэтому приведённые выше методы в определенных случаях могут не работать.
====

Чтобы использовать бин `HtmlAttributes`, его нужно инжектировать в контроллер экрана, например:

.XML descriptor
[source, xml]
----
include::{sourcesdir}/gui/html_attributes.xml[]
----

.Screen controller
[source, java]
----
include::{sourcesdir}/gui/HtmlAttributes.java[]
----

