:sourcesdir: ../../../../source

[[shortcuts]]
==== Горячие клавиши

В данном разделе приведена информация обо всех горячих клавишах (shortcuts), которые используются по умолчанию в универсальном пользовательском интерфейсе приложения. Все перечисленные ниже <<app_properties,свойства приложения>> принадлежат интерфейсу `ClientConfig` и используются в блоке Web Client.

* Главное окно приложения.

** *CTRL-SHIFT-PAGE_DOWN* - переход на следующую вкладку. Настраивается свойством приложения `cuba.gui.nextTabShortcut`.

** *CTRL-SHIFT-PAGE_UP* - переход на предыдущую вкладку. Настраивается свойством приложения `cuba.gui.previousTabShortcut`.

* Панель папок.

** *ENTER* – открыть выделенную <<folders_pane,папку>>.

** *SPACE* - выделить/снять выделение с папки, находящейся в фокусе.

** *ARROW UP*, *ARROW DOWN* - выбрать папку.

** *ARROW LEFT*, *ARROW RIGHT* - свернуть/развернуть папку, содержащую вложенные папки, или переместить фокус на уровень выше.

* Экраны.

** *ESCAPE* - закрыть текущий <<abstractWindow,экран>>. Настраивается свойством приложения `cuba.gui.closeShortcut`.

** *CTRL-ENTER* - закрыть текущий <<abstractEditor,экран редактирования>> с сохранением изменений. Настраивается свойством приложения `cuba.gui.commitShortcut`.

* Стандартные действия компонента-списка (<<gui_Table,Table>>, <<gui_GroupTable,GroupTable>>, <<gui_TreeTable,TreeTable>>, <<gui_Tree,Tree>>). Кроме указанных свойств приложения горячая клавиша для конкретного экземпляра действия может быть установлена его методом `setShortcut()`.

** *CTRL-\* - вызов действия <<createAction,CreateAction>>. Настраивается свойством приложения `cuba.gui.tableShortcut.insert`.

** *CTRL-ALT-\* - вызов действия <<addAction,AddAction>>. Настраивается свойством приложения `cuba.gui.tableShortcut.add`.

** *ENTER* - вызов действия <<editAction,EditAction>>. Настраивается свойством приложения `cuba.gui.tableShortcut.edit`.

** *CTRL-DELETE* - вызов действий <<removeAction,RemoveAction>> и <<excludeAction,ExcludeAction>>. Настраивается свойством приложения `cuba.gui.tableShortcut.remove`.

* Выпадающие списки (<<gui_LookupField,LookupField>>, <<gui_LookupPickerField,LookupPickerField>>).

** *SHIFT-DELETE* – очистить значение.

* Стандартные действия поля выбора (<<gui_PickerField,PickerField>>, <<gui_LookupPickerField,LookupPickerField>>, <<gui_SearchPickerField,SearchPickerField>>). Кроме указанных свойств приложения горячая клавиша для конкретного экземпляра действия может быть установлена его методом `setShortcut()`.
** *CTRL-ALT-L* - вызов действия <<lookupAction,LookupAction>>. Настраивается свойством приложения `cuba.gui.pickerShortcut.lookup`.

** *CTRL-ALT-O* - вызов действия <<openAction,OpenAction>>. Настраивается свойством приложения `cuba.gui.pickerShortcut.open`.

** *CTRL-ALT-C* - вызов действия <<clearAction,ClearAction>>. Настраивается свойством приложения `cuba.gui.pickerShortcut.clear`.
+
В полях выбора кроме вышеперечисленных горячих клавиш поддерживается вызов действий сочетанием *CTRL-ALT-1*, *CTRL-ALT-2* и так далее по количеству действий. То есть при нажатии сочетания клавиш *CTRL-ALT-1* произойдет вызов действия, которое описано первым в списке действий, при нажатии сочетания клавиш *CTRL-ALT-2* − вызов второго действия и так далее. Сочетание *CTRL-ALT* можно заменить другим, указав его в свойстве приложения `cuba.gui.pickerShortcut.modifiers`.

* Компонент <<gui_Filter,Filter>>.

** *SHIFT-BACKSPACE* – открыть список выбора фильтров. Настраивается свойством приложения `cuba.gui.filterSelectShortcut`.

** *SHIFT-ENTER* - применить выбранный фильтр. Настраивается свойством приложения `cuba.gui.filterApplyShortcut`.


