= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.0
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/release_6_10/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

=== All Resolved Issues

* {githubissueslog}/release_7.0.0.md[Platform 7.0.0 Resolved Issues]


[[platform_breaking_changes]]
=== Breaking Changes

. CUBA and add-ons (BPM, Charts, FTS, Reports) configuration files have been moved from the classpath root to the root packages of the appropriate application components. For example, `/cuba-persistence.xml` became `/com/haulmont/cuba/persistence.xml`. These changes do not affect properly configured application projects, except in one case: in the test containers, there is a reference to the `test-app.properties` file which is now at `com/haulmont/cuba/testsupport/test-app.properties`. So if you are using middleware integration tests, edit your test container class and replace the reference:
+
[source, java]
----
public class MyProjectTestContainer extends TestContainer {

    public MyProjectTestContainer() {
        super();
        // ...
        appPropertiesFiles = Arrays.asList(
                // List the files defined in your web.xml
                // in appPropertiesConfig context parameter of the core module
                "com/company/myproject/app.properties",
                // Add this file which is located in CUBA and defines some properties
                // specifically for test environment. You can replace it with your own
                // or add another one in the end.
                "com/haulmont/cuba/testsupport/test-app.properties");
        // ...
    }
----

[[gui]]
=== Generic UI

[[rest]]
=== REST API

[[charts]]
=== Charts Addon

[[fts]]
=== Full-Text Search Addon

[[bpm]]
=== BPM Addon

[[misc]]
=== Miscellaneous

[[upd_dep]]
=== Updated Dependencies

----
com.haulmont.thirdparty/eclipselink = 2.6.2.cuba24
com.vaadin = 7.7.13.cuba.11
org.apache.tika/tika-parsers = 1.18
----

[[studio]]
== Studio

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%206.10%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.10.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 6.10.0 Resolved Issues]

[[studio_known_issues]]
=== Known Issues

If you use the in-place update in Studio SE on macOS, it will completely replace your application folder. If you previously added some JDBC drivers to `/Applications/Cuba Studio SE.app/Contents/Resources/app/studio/lib`, they will be lost and you will have to add them again.
