= CUBA Platform Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.2
:version-label: Version
:revremark: Copyright (c) 2020 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:restapi: https://doc.cuba-platform.com/restapi-{revnumber}
:studio: https://doc.cuba-platform.com/studio
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/master/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform version {revnumber}.

[WARNING]
====
Please note that in order to work with CUBA 7.2, you need to install Studio 13 BETA2 or newer. Older versions of Studio don't have correct support for project creation, migration and hot deployment.

Follow the steps below to install Studio 13 BETA or see details in the https://www.cuba-platform.com/discuss/t/studio-13-beta-published/11219[announcement].

* Open the IDE _Settings/Preferences -> Plugins_ dialog.
* Click the gear icon and select _Manage Plugin Repositories_.
* Click “+” (add) and enter the following in the _Repository URL_ field: https://plugins.jetbrains.com/plugins/beta/list
* Switch to the _Marketplace_ tab. You should immediately see that CUBA plugin requests for update to 13.0.BETA version.
* Click _Update_.
====

== All Resolved Issues

* {githubissueslog}/release_7.2.0.md[Platform 7.2.0 Resolved Issues]

[[breaking_changes]]
== Breaking Changes

. Due to changes in the "remember me" login mechanism (see <<gui,below>>) all application users will have to enter their credentials when logging in, as if their browser cookies were removed.

. The `LoginScreen` class has been refactored to simplify creation of https://github.com/cuba-platform/cuba/issues/2455[alternative login screen] implementations. The `AuthInfo` inner class has been moved into `LoginScreenAuthDelegate`, so if you have extended login screen in your project and overridden methods with this class in the signature, make the proper import to fix compilation, for example:
+
[source,java]
----
public class ExtLoginScreen extends LoginScreen {
    @Override
    protected void setAuthInfo(LoginScreenAuthDelegate.AuthInfo authInfo) {
    // ...
----

. Due to changes in {manual}/gui_SideMenu.html[SideMenu] component, the main screen using such menu should have `cssLayout` as a root container. If you have the main screen with non-responsive side menu in your project, Studio will replace the root `hbox` with `cssLayout` upon automatic migration. If something is wrong with your main screen layout, make sure the root container is correct, for example:
+
[source,xml]
----
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        extends="/com/haulmont/cuba/web/app/main/main-screen.xml">
    <layout>
        <cssLayout id="horizontalWrap">
            <workArea id="workArea">
            <!-- -->
----

. Due to introducing {manual}/roles.html#security_scope[security scopes], the `cuba.anonymousSessionId` application property has been removed. Now anonymous sessions for all scopes are created with random identifiers.

. When using {manual}/folders_pane.html[Folders Panel], the _Add to set_ action and button do not appear automatically in the tables linked to the generic filter. If you need this action, add it explicitly as described in the {manual}/record_set.html[Record Sets] section.

. Amazon S3 {manual}/file_storage.html[file storage] implementation has been moved to a separate add-on. See the add-on https://github.com/cuba-platform/cuba-aws[README] for details.

. JGroups has been updated to version 4.1.8.Final. If you use {manual}/cluster_mw.html[middleware cluster], make the following changes in your JGroups configuration files:
** For UDP configuration, replace:
*** `MERGE2` with `MERGE3`
*** `pbcast.NAKACK` with `pbcast.NAKACK2` and remove `retransmit_timeout` property
*** `UNICAST` with `UNICAST3`
*** `FC` with `MFC`
** For TCP configuration, remove properties `timer_type, timer.min_threads, timer.max_threads, timer.keep_alive_time, timer.queue_max_size, thread_pool.queue_enabled, thread_pool.queue_max_size, thread_pool.rejection_policy, oob_thread_pool.min_threads, oob_thread_pool.max_threads, oob_thread_pool.keep_alive_time, oob_thread_pool.queue_enabled, oob_thread_pool.queue_max_size, oob_thread_pool.rejection_policy` and add property `thread_pool.enabled="true"`. See details in http://belaban.blogspot.com/2016/09/removing-thread-pools-in-jgroups-40.html[this article].

. The `DataContext.evictAll()` has been renamed to `evictModified()`, which is a more appropriate name for the method evicting only modified and removed instances. Use the new `clear()` method to evict all instances including modified ones.

. The `Icons.Icon.name()` method has been renamed to `iconName()`.

[[security]]
== Security Subsystem

. The security subsystem {manual}/permissions.html[permissions] and {manual}/roles.html[roles] have been reworked to provide "denied by default" model instead of the previous "allowed by default". Newly created with CUBA 7.2 projects will use the new model by default. If you migrate a project from the previous CUBA version, Studio will add the application properties explained in {manual}/legacy_roles.html[Legacy Roles and Permissions] to keep your existing security configuration intact.

. Role types ("Super", "Denying", etc.) have been replaced with default permissions for different categories, see the _Default permissions_ group box in the role edit screen and `@DefaultScreenAccess`, `@DefaultEntityAccess`, `@DefaultEntityAttributeAccess`, `@DefaultSpecificAccess` annotations. When upgrading to CUBA 7.2 from a previous version, your set of roles will be automatically updated by the database migration scripts to convert role types to default permissions.

. Now security {manual}/roles.html[roles] and {manual}/groups.html[access groups] together with permissions and constraints can be defined at design time using annotated Java classes. It makes the access control more robust and eliminates difficulties with transferring the configuration between application instances (e.g. from the development environment to production).

. {manual}/roles.html#security_scope[Security scopes] have been introduced to allow you to define different sets of roles for users logging in through different clients. The motivation behind this feature is that REST API clients should normally have more restrictions than Generic UI, because Generic UI is more safe by its nature.

[[deployment]]
== Deployment

. Usage of {manual}/app_home.html[Application Home] has been standardized for development and deployment environment. When you start the application in Studio, the application home is created in `deploy/app_home` directory. It contains `conf`, `temp` and `work` directories for all application blocks, as well as the common `logs` directory. The application home also contains the empty `local.app.properties` file and the default logging configuration in `logback.xml`.
+
[WARNING]
====
In order to correctly work with the application home, development Tomcat must define `app.home` Java system property in its `setenv.*` scripts. So remove the old `deploy/tomcat` folder after upgrading to CUBA 7.2 and before running the application. The new Tomcat will be installed automatically.
====
+
Setting `app.home` Java system property is recommended for all deployment variants, however sensible fallback is provided by the framework: it is either the working directory for UberJAR, or `${catalina.base}/work/app_home` when running WAR on Tomcat, or just `~/.app_home` otherwise.

. You can easily provide your own {manual}/logging.html[logging configuration] for the development environment: just create `etc/logback.xml` file in the project, and when you start the application, the file will be copied to `deploy/app_home` and recognized by the logging initialization procedure.

. Now you can configure connections to databases using application properties, see {manual}/db_connection.html[Connecting to Databases]. This method simplifies the overall configuration, because `app.properties` files define all settings including the data source parameters. Also, it makes your WAR file completely independent of the application server environment.
+
Getting data sources from JNDI is supported as before, so no migration is required for existing projects.

. {manual}/spring_profiles.html[Spring profiles] can be used to customize application in different environments.

. OS environment variables can be used as a source of {manual}/app_properties.html#setting_app_properties[application properties] values.

. Redeployment of web applications without restarting the application server works more reliably as a result of using the
https://github.com/mjiderhamn/classloader-leak-prevention[Classloader Leak Prevention] library.

[[gui]]
== Generic UI

. {manual}/gui_SideMenu.html[SideMenu] is now collapsible, which saves horizontal space. Also, the branding image and other components of the menu have been rearranged. See also the <<breaking_changes>> section for possible issues on migration.

. The "remember me" login mechanism has been completely reworked:

** The new application property {manual_app_props}cuba.rememberMeExpirationTimeoutSec[cuba.rememberMeExpirationTimeoutSec] defines expiration timeout for "remember me" cookies and `RememberMeToken` entity instances. It is set to 30 days by default.

** If the user selects the _Remember Me_ checkbox in the login screen, next time they log in automatically without showing the login screen.

** If the user logs out explicitly, or the cookie is expired, next time the login screen is shown again.

. {manual}/views_creation.html[Views] used for loading data in screens can be defined right in the screen descriptors, see an example {manual}/gui_data_comp_decl.html[here]. This feature reduces the need for creating shared views in the `views.xml` file.

. {manual}/standard_actions.html[Standard actions] now have parameters that can be configured in XML and Java. So you don't have to rewrite the whole action behavior just to open an editor screen as a dialog, or to specify a different screen class. Use *Component Inspector* in Studio to find and assign action properties and handlers, or copy code snippets from the documentation.

. {manual}/ViewAction.html[ViewAction] allows you to open entity edit screen in read-only mode. The optional `enableEditing` can be used to switch to the edit mode without reopening the screen.

. Introduced {manual}/opening_screens.html#screen_return_values[StandardOutcome] and {manual}/gui_dialogs.html#gui_input_dialog[DialogOutcome] enumerations that can be used instead of `CloseAction` constants when closing screens and testing how the screen or dialog was closed.

. {manual}/gui_Form.html[Form] now supports flexible positioning of fields, see the `colspan` and `rowspan` XML attributes and corresponding parameters of the `add()` method.

. In addition to the global layout template for the generic filter, a layout can be specified for each filter instance, see {manual}/gui_Filter.html#gui_Filter_controlsLayoutTemplate[controlsLayoutTemplate] property.

. {manual}/gui_BulkEditor.html[BulkEditor] has the responsive layout, which you can control using the `columnsMode` attribute.

. In {manual}/gui_DateField.html[DateField], if the new `autofill` attribute is set to true, the current month and year is set automatically after entering a day.

. {manual}/gui_TimeField.html[TimeField] can work in 12h AM/PM format if you set its `timeMode` attribute to `H_12`.

. In {manual}/gui_Table.html[Table] and {manual}/gui_DataGrid.html[DataGrid], you can set initial sorting order declaratively using the `sort` attribute of the `column` element.

. For {manual}/gui_DataGrid.html[DataGrid] and {manual}/gui_TreeDataGrid.html[TreeDataGrid], you can use the following predefined styles: `borderless`, `no-horizontal-lines`, `no-vertical-lines`, `no-stripes`.

. {manual}/gui_PopupView.html[PopupView] supports setting its position using `popupPosition`, `popupTop`, `popupLeft` attributes.

. All tables and data grids now have _Select all_ / _Deselect all_ commands in the columns popup, which simplifies managing long lists of columns.

. {manual}/gui_LookupField.html#gui_LookupField_setOptionImageProvider[setOptionImageProvider] method have been added to `LookupField` and `LookupPickerField`. It allows you to display images for the field options (previously only icons could be used). Go to _Handlers_ tab in Studio component inspector and double-click _optionImageProvider_ field to generate handler code.

. {manual}/gui_Button.html[Button] has its own `shortcut` attribute, which allows you to assign keyboard shortcuts to buttons not linked to actions.

. The new {manual}/gui_components.html[Slider] component has been implemented.

. If you set the `autoLoad` attribute of {manual}/gui_Table.html#gui_Table_rowsCount[RowsCount] to true, the component will load the number of rows in background and show it automatically.

. {manual}/gui_Filter.html[Filter] component can now work with {manual}/gui_keyvalue_containers.html[KeyValueCollectionContainer] loaders.

[[misc]]
== Miscellaneous

. Kotlin is fully {manual}/support_for_kotlin.html[supported], which means that you can use it in all parts of the project: entities, beans, screen controllers, etc. Hot-deploy of screen controllers written in Kotlin also works.

. Now you can provide database migration scripts for additional data stores in `/db/init_<datastore_name>` and `/db/update_<datastore_name>` directories of the `core` module. The scripts will be executed by the {manual}/build.gradle_createDb.html[createDb] and {manual}/build.gradle_updateDb.html[updateDb] Gradle tasks having the `storeName` parameter, as well as by the application server if the {manual_app_props}cuba.automaticDatabaseUpdate[cuba.automaticDatabaseUpdate] property is configured accordingly.

. Gradle 5.6.4 is used for migrated and new projects. Studio automatically sets the proper version in the `gradle/wrapper/gradle-wrapper.properties` file. Check it in case of any troubles with project building.

. JUnit 5 is used in new projects for tests. The {manual}/testing.html[documentation] has been updated accordingly.

. {manual}/views_creation.html[ViewBuilder] simplifies creation of views in the business logic and tests.

. {manual}/dataManager.html#dm_query[DataManager]'s fluent interface allows you to specify JPQL queries in abbreviated format omitting parts of the query that can be inferred from the context.

. Listeners of {manual}/entity_attr_annotations.html#metaProperty_annotation[read-only transient properties] are now notified when related properties change. It helps to update UI components displaying read-only attributes that depend on some other mutable attributes.

. {manual}/entity_class_annotations.html#postConstruct_entity_annotation[@PostConstruct] methods can accept Spring beans available in the `global` module as parameters.

[[upd_dep]]
== Updated Dependencies

Core framework:
----
com.fasterxml.jackson = 2.10.1
com.fasterxml.jackson-databind = 2.10.1
com.google.code.gson/gson = 2.8.6
com.google.guava/guava = 28.1-jre
com.microsoft.sqlserver/mssql-jdbc = 7.2.2.jre8
com.sun.mail/javax.mail = 1.6.2
com.vaadin = 8.9.2-0-cuba
commons-codec/commons-codec = 1.13
de.javakaffee/kryo-serializers = 0.45
mysql/mysql-connector-java = 8.0.17
org.apache.commons/commons-collections4 = 4.4
org.apache.commons/commons-compress = 1.19
org.apache.commons/commons-dbcp2 = 2.7.0
org.apache.commons/commons-pool2 = 2.7.0
org.apache.commons/commons-text = 1.8
org.apache.httpcomponents/httpclient = 4.5.10
org.apache.poi/poi = 4.1.1
org.aspectj/aspectjrt = 1.9.4
org.aspectj/aspectjweaver = 1.9.4
org.codehaus.groovy = 2.5.8
org.freemarker/freemarker = 2.3.29
org.hibernate.validator/hibernate-validator = 6.1.1.Fin`al
org.hsqldb/hsqldb = 2.5.0
org.jgroups/jgroups = 4.1.8.Final
org.jmockit/jmockit = 1.48
org.jsoup/jsoup = 1.12.1
org.postgresql/postgresql = 42.2.8
org.slf4j/log4j-over-slf4j = 1.7.29
org.slf4j/slf4j-api = 1.7.29
org.springframework = 5.2.1.RELEASE
org.springframework.security = 5.2.1.RELEASE
tomcat = 9.0.27
----

FTS add-on:
----
org.apache.lucene = 8.2.0
org.apache.tika/tika-parsers = 1.22
----

Reports add-on:
----
com.haulmont.yarg = 2.2.4
org.apache.poi/ooxml-schemas = 1.4
org.apache.xmlbeans/xmlbeans = 3.1.0
----
