= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.5
:version-label: Version
:revremark: Copyright (c) 2017 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-6.5

:!sectnums:

WARNING: This document is now work in progress!

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}. The full list of resolved issues is available in YouTrack:

* https://youtrack.cuba-platform.com/issues/PL?q=Milestone%3A+%7BRelease+6.5%7D+State%3A+Fixed%2C+Verified+Affected+versions%3A+-SNAPSHOT+sort+by%3A+created+asc[Platform Resolved Issues]

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone%3A+%7BRelease+6.5%7D+State%3A+Fixed%2C+Verified+Affected+versions%3A+-SNAPSHOT+sort+by%3A+created+asc[Studio Resolved Issues]

[[platform]]
== Platform

[[platform_breaking_changes]]
=== Breaking Changes

. The structure of storing references to entities in Entity Log, Entity Snapshots and Dynamic Attributes has been changed. If you have accessed internals of these mechanisms from your application code, you may need to change it accordingly. {youtrack}/issue/PL-8461[PL-8461].

. Now we use default behavior of Vaadin's Valo theme ({youtrack}/issue/PL-8267[PL-8267]) :

* `HBox` and `VBox` use `overflow: auto` CSS mode. If a `HBox` or `VBox` has a child with 0 height then the layout will have non-zero height.
* Font size is inherited using normal CSS rules instead of explicit setting for components.

. The `fileExists()` method of `FileStorageAPI` now declares `FileStorageException`. If you invoke this method, add a `catch` block. {youtrack}/issue/PL-8866[PL-8866].

. Validation for input parameters of `UniqueNumbersAPI` methods has been added. A sequence name can contain only alphanumeric characters and underscores, otherwise `IllegalArgumentException` is thrown. {youtrack}/issue/PL-8724[PL-8724].

. Due to cluster improvements explained <<cluster,below>>, pay attention to the following:

* If you don't use Studio migration procedure, edit `spring.xml` files of all client modules used in your project, find the `xyz_proxyCreator` bean definitions and replace:
+
--
[source, xml]
----
<property name="clusterInvocationSupport" ref="cuba_clusterInvocationSupport"/>
----

with

[source, xml]
----
<property name="serverSelector" ref="cuba_ServerSelector"/>
----
--

* `jgroups.xml` has been split into two files: `jgroups.xml` (UDP stack) and `jgroups_tcp.xml` (TCP stack). Use `cuba.cluster.jgroupsConfig` application property to select the stack.

. Option dialogs opened with `showOptionDialog()` method of screen controllers are always closed after selecting an option, even if an exception occurs in `actionPerform()`. {youtrack}/issue/PL-8610[PL-8610].

. Microsoft's JDBC driver is now used instead of jTDS if the project uses Microsoft SQLServer database. Studio performs automatic migration when upgrading the project to platform 6.5. {youtrack}/issue/PL-8826[PL-8826].

. *Reporting*. If no screens are specified for a report, it is not shown on pop-up window of screen reporting actions. {youtrack}/issue/PL-8618[PL-8618].

. *Charts and Maps*. Chart API has been reworked, see <<chart_api,below>>. {youtrack}/issue/PL-7754[PL-7754].

. *Charts and Maps*. The `GoogleMapViewer` interface has been deprecated, use the `MapViewer` component directly. {youtrack}/issue/PL-8787[PL-8787].

[[uber_jar]]
=== Uber JAR

CUBA applications can now be deployed as executable JAR files containing the application code, all dependencies and embedded HTTP server. See
{manual}/uberjar_deployment.html[UberJAR Deployment] for details.

[[cluster]]
=== Cluster Improvements

[[cluster_load_balancing]]
Middleware Load Balancing::
+
--
Previously, the web client blocks did not perform balancing when worked with multiple middleware blocks. They chose a middleware server from the list specified in the `cuba.connectionUrlList` at startup and didn't change it until it became unavailable. So the load balancing was possible only between multiple web blocks (and if `cuba.randomServerPriority` was set to true): first web block works with first middleware, second web with another middleware and so on. If `cuba.randomServerPriority` was set to false, each client block selected a middleware block that was first in its `cuba.connectionUrlList`.

Now the balancing is much more granular - on the user session level. A middleware server is randomly determined on the first remote connection for a user session, and it is fixed for the whole session life time ("sticky session"). Requests from anonymous session and without session do not stick to a server and go to random servers.

The algorithm of selecting a middleware server is provided by the `cuba_ServerSorter` bean which is by default implemented by the `RandomServerSorter` class. You can provide your own implementation in the project or use `NoopServerSorter` to revert to the old behavior when client always selects the first available server from its `cuba.connectionUrlList`.
--

[[cluster_zookeeper]]
Coordination Using ZooKeeper::
+
--
Application blocks interact in a cluster in two ways: middleware blocks interact with each other, web blocks send requests to middleware. These channels of communication are based on different mechanisms (JGroups for inter-middleware interaction, Spring HTTPInvoker for requesting middleware from clients), however they both require discovering of current cluster topology - what middleware servers are up now and how to connect to them. By default, the following approaches are used:

* For communication between middleware blocks you set up UDP or TCP stack with some discovery methods. In case of UDP stack the discovery can be automatic as it is based on broadcasting UDP messages. However, broadcasting is often disabled in production environments, so the only reliable method of discovery is to specify the list of server addresses for TCPPING protocol in `jgroups.xml`. It means that the topology is static - you have to know it in advance when starting a middleware server.

* For requesting middleware from client blocks, you have to specify addresses of the middleware blocks in the `cuba.connectionUrlList` application property. It also makes the configuration static - you have to know addresses of the middleware servers when starting a client block.

Now we provide an application component that enables dynamic discovery of middleware servers for both communication channels. It is based on integration with https://zookeeper.apache.org[Apache ZooKeeper] - a centralized service for maintaining configuration information. When this component is included in your project, you need to specify only one static address when running your application blocks - the address of ZooKeeper. Middleware servers will advertise themselves by publishing their addresses on the ZooKeeper directory and discovery mechanisms will request ZooKeeper for addresses of available servers. If a middleware server goes down, it will be automatically removed from the directory immediately or after a timeout.

The source code of application component is available on https://github.com/cuba-platform/cuba-zk[GitHub], the binary artifacts are published in the standard CUBA repositories. See https://github.com/cuba-platform/cuba-zk[README] for information about including and configuring the component.
--

[[rest_api]]
=== REST API Improvements

[[rest_api_model_versioning]]
Model Versioning::
+
--
REST API v2 now contains a mechanism that allows you to change your data model but keep compatibility with existing REST clients. If a request from a client contains the `modelVersion` parameter, REST will apply a set of JSON transformations defined in a special XML configuration file. There are predefined transformations like removing or replacing an attribute, and you can provide custom classes for arbitrary transformations of schema and values. See {manual}/rest_api_v2_data_model_versioning.html[documentation] for details.
--

[[rest_api_persistent_token_store]]
Persistent Token Store::
+
--
By default, REST API v2 OAuth tokens are stored in memory only, which means clients need to re-login if the middleware server is restarted. Now you can turn on persistent storage for authentication tokens: see {manual}/rest_api_v2_persistent_token_store.html[documentation] for details. You may also want to increase token expiration timeout using the `cuba.rest.client.tokenExpirationTimeSec` application property, which is 12 hours by default.
--

[[file_Loader]]
=== FileLoader Interface

The new `FileLoader` interface allows you to work with files contained in {manual}/file_storage.html[File Storage] uniformly from the client and middle tier using input/output streams. It's a managed bean that can be injected or obtained via `AppBeans` class and it provides `openStream()` and `saveStream()` methods to load and save files. Both client and middleware implementations of the interface do not keep the whole file in memory, so you can pass files of any size without the risk of reaching memory limits.

[[field_group]]
=== FieldGroup API


[[data_grid]]
=== DataGrid Component

[[data_grid_inline_edit]]
Inline Edit::

[[charts]]
=== Charts

[[chart_api]]
Simplified Chart API::

[[polymer]]
=== Polymer UI

[[polymer_routing]]
Routing::

[[polymer_lookup]]
Lookup Approach::

[[polymer_file_upload]]
File Upload Field::

[[platform_other]]
=== Other Notable Changes

TabSheet Not Unloading Content::

[[studio]]
== Studio

[[studio_breaking_changes]]
=== Breaking Changes

[[polymer_templates]]
==== Polymer templates

Templates which are used for Polymer UI scaffolding were changed to support routing improvements.
In order to adopt those changes and use new templates you have to perform manual upgrade on your
Polymer client source code. The changes are listed below.

. Add `cuba-ui` dependency to the `bower.json`:
+
--
[source, json]
----
{
  ...
  "dependencies": {
    ...
    "cuba-ui": "cuba-elements/cuba-ui#^0.1.0",
    ...
  }
  ...
}
----
--
. Add `cuba-ui` import to the `{namespace}-shell.html`:
+
--
[source, xml]
----
<link rel="import" href="../bower_components/cuba-ui/cuba-ui.html">
----
--
. Make the following changes in `{namespace}-shell.html`:
.. add `tail` property binding in the `app-route` component:
+
--
[source, xml]
----
<app-route route="{{route}}" pattern="/:page" data="{{routeData}}" tail="{{routeTail}}">
----
--
.. set `selected-attribute="active"` in the `iron-lazy-pages` component:
+
--
[source, xml]
----
<iron-lazy-pages selected="[[_computeSelectedPage(routeData.page)]]" attr-for-selected="data-route" selected-attribute="active" class="content fit">
----
--
.. add the following listener and handler:
+
--
[source, javascript]
----
Polymer({
  is: 'namespace-shell',
  ...
  listeners: {
    'navigate': '_onNavigate'
  },
  ...
  _onNavigate: function(event, detail) {
    this.set("route.path", detail);
  }
});
----
--

=== Bintray Repository

=== Support for Bean Validation

=== Groovy-based Entity Listeners

=== Scaffolding of Custom Datasources

=== Localized Messages in UI Designer
