= CUBA Platform Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.1
:version-label: Version
:revremark: Copyright (c) 2019 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:studio: https://doc.cuba-platform.com/studio
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/master/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform version {revnumber}.

== All Resolved Issues

//* {githubissueslog}/release_7.0.1.md[Platform 7.0.1 Resolved Issues]

[[breaking_changes]]
== Breaking Changes


[[gui]]
== Generic UI

* Now you can create new visual components by combining existing ones, see {manual}/composite_components.html[Composite Components].

* The concept of non-visual components has been generalized and made extendable, see {manual}/gui_facets.html[Non-Visual Components]. Along with {manual}/gui_Timer.html[Timer], the framework now provides a new useful non-visual component: {manual}/gui_ClipboardTrigger.html[ClipboardTrigger].

* Introduced {manual}/gui_dialogs.html#gui_input_dialog[input dialog] which allows you to construct input forms using API. It can be used instead of creating screens for trivial data input.

* Now you can make some screens of your application available to non-authenticated users, see {manual}/gui_anonymous_access.html[Anonymous Access to Screens].

* Standard login and main screens have been reworked using the new screens API, see details in {manual}/gui_root_screens.html[Root Screens]. The main screen has the layout with side menu, so it is used by default for new projects. For projects, migrated from previous versions of the framework, the Studio migration procedure adds the following application properties to `web-app.properties`:
+
----
cuba.web.loginScreenId = loginWindow
cuba.web.mainScreenId = mainWindow
----
+
It ensures the migrated project uses the legacy login and main screens. If you want to switch to the new screens, remove these properties.

* Logout button shown on the standard main screen has been replaced with the `UserActionsButton` component. If the user is not authenticated, the component allows the user to go to login screen; when authenticated, the component provides actions to show the *Settings* screen or to log out.

* If a screen controller has public setters to accept parameters, they can be passed from the main menu, see {manual}/menu.xml.html#menu.xml_screen_properties[menu.xml].

* If a screen fragment controller has public setters to accept parameters, they can be specified in the host screen XML, see {manual}/using_screen_fragments.html#using_screen_fragment_params[Passing parameters to fragments].

* Screen fragments now send attach/detach lifecycle event when a fragment is added/removed to the host screen, see {manual}/screen_fragment_events.html[ScreenFragment Events]. Also, when a fragment is created programmatically, you don't need to invoke its `init()` method anymore, because all fragment's lifecycle events will be sent automatically when the fragment is added to a screen.

* In order to simplify migration from version 6 of the framework, we have restored the undocumented ability to use legacy API screens as frames. It is now supported for subclasses of `AbstractWindow`, `AbstractLookup` and `EntityCombinedScreen` (`AbstractEditor` is not supported). The `init()` method of the screen is invoked, `ready()` is not, as before.

* The framework now provides infrastructure for writing integration tests on the web tier for testing UI in full-functioning Spring container, see {manual}/integration_tests_client.html[Web Integration Tests].

[[misc]]
== Miscellaneous

[[upd_dep]]
== Updated Dependencies

Core framework:
----
----

Full-Text Search add-on:
----
----

Reports add-on:
----
----
