= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.0
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:studio: https://doc.cuba-platform.com/studio-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/release_6_10/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

//=== All Resolved Issues

//* {githubissueslog}/release_7.0.0.md[Platform 7.0.0 Resolved Issues]

[[known_issues]]
=== Known Issues And Limitations

. CUBA 7.0 does not support the desktop client. You should not migrate your project to this release if you depend on Desktop module.

. Hot-deploy mechanism for UI screens is limited to changes in the existing screens only. If you create a new screen while your application is running this screen will not be hot-deployed. See https://github.com/cuba-platform/cuba/issues/1509[GitHub issue] for details.

. `Tree` UI component has been reworked using `TreeDataGrid`. For now it does not have borders and padding and looks different than old `Tree`.

. Beta does not support `RuntimePropertiesFrame` component. It will be restored before the final release 7.0.

[[platform_breaking_changes]]
=== Breaking Changes

. IntelliJ IDEA / Eclipse project files generation (`idea` and `eclipse` Gradle tasks) is not required anymore.
+
The framework does not use `idea` / `eclipse` Gradle plugins and you must import the project using the standard IDE mechanisms. In the simplest case you just open `build.gradle` file as a project. See {studio}/open_project.html[Studio User Guide] for detailed instructions.

. CUBA and add-ons (BPM, Charts, FTS, Reports) configuration files have been moved from the classpath root to the root packages of the appropriate application components. For example, `/cuba-persistence.xml` became `/com/haulmont/cuba/persistence.xml`. These changes do not affect properly configured application projects, except in one case: in the test containers, there is a reference to the `test-app.properties` file which is now at `com/haulmont/cuba/testsupport/test-app.properties`. So if you are using middleware integration tests, edit your test container class and replace the reference:
+
[source, java]
----
public class MyProjectTestContainer extends TestContainer {

    public MyProjectTestContainer() {
        super();
        // ...
        appPropertiesFiles = Arrays.asList(
                "com/company/myproject/app.properties",
                "com/haulmont/cuba/testsupport/test-app.properties");
----

. Old `commons-lang` dependency has been removed, the platform depends on new `commons-lang3` library. You can either migrate usages to `commons-lang3` (simply change imports to use `org.apache.commons.lang3` package) or add explicit dependency `compile('commons-lang:commons-lang:2.6')` to your global module in `build.gradle`.

. Dependency on `groovy-all` package removed. Now the platform depends only on `groovy`, `groovy-templates` and `groovy-sql` modules. Add required Groovy modules to your project dependencies if needed.

. Dependency on MyBatis and `com.haulmont.cuba.core.sys.mybatis.UUIDTypeHandler` class have been removed. If you need MyBatis in your project, see the {manual}/myBatis.html[Integration with MyBatis] section for instructions.

. Interfaces `Component.Container`, `Component.HasValue`, `Component.HasFormatter` and others have been extracted from `Component` and moved to `com.haulmont.cuba.gui.components` package. See https://github.com/cuba-platform/cuba/issues/925[GitHub issue] for details. Imports of those interfaces must be changed, e.g. instead of `com.haulmont.cuba.gui.components.Component.HasValue` import `com.haulmont.cuba.gui.components.HasValue` directly.

. Deprecated methods `addListener` and `removeListener` of `Instance` have been removed. Use `addPropertyChangeListener` and `removePropertyChangeListener` instead.

. All `addSomeListener` and `removeSomeListener` methods in UI components now receive `Consumer<E>` where `E` is a type of event object. If you use those methods with a lambda parameter then your code will not require migration. If you implement one of the old listener interfaces (e.g. ValueChangeListener) with a standalone class you will need to implement `Consumer<E>` (e.g. ValueChangeEvent) instead. See https://github.com/cuba-platform/cuba/issues/1108[GitHub issue] for details.

. `WebWindowManager` class has been replaced with `WebScreens`. If you have extended `WebWindowManager` in your code you will need to migrate your improvements manually.

. Behavior of `Component` methods `isVisible` and `isEnabled` has been changed. Now methods return only value of the component visibility / enabled without taking parent value into consideration. New `isVisibleRecursive` and `isEnabledRecursive` methods are introduced.

. Interface `HasValue` now has type parameter `V` - type of the corresponding value of UI component. Old code that uses untyped UI components, for instance `TextField` or `LookupField` might be broken. You can find default type of the UI component in its interface in `TYPE_DEFAULT` constant. For example (here `TextField` has default type `String`):
+
[source, java]
----
TypeToken<TextField<String>> TYPE_DEFAULT = new TypeToken<TextField<String>>(){};
----
+
It is highly recommended to set type parameter for UI components explicitly, even default type parameter should be set. For example:
+
[source, java]
----
@Inject
protected LookupField<User> userField;
@Inject
protected TextField<Long> countField;
@Inject
protected Label<String> defaultTypedLabel;
----

. Method `HasValue.getValue()` does not support auto cast of the return value anymore. You should either cast value manually or use typed UI Component, e.g. `TextField<String>`.

. Widget set file location has been changed. If you have `web-toolkit` module in your project you will need to change references to widget sets in `AppWidgetSet.gwt.xml` file:
+
cuba: `com.haulmont.cuba.web.toolkit.ui.WidgetSet` changed to `com.haulmont.cuba.web.widgets.WidgetSet`.
+
charts: `com.haulmont.charts.web.toolkit.ui.ChartsWidgetSet` changed to `com.haulmont.charts.web.widgets.ChartsWidgetSet`.

. FreeMarker templates are not supported in `caption` and `description` attributes of a window. Now values loaded from XML are treated as simple String values. If you want to use templates in those attributes you can call `com.haulmont.cuba.core.global.TemplateHelper` methods manually from a screen controller.

. Screens declared in `screens.xml` file with `class` attribute do not support `Runnable` interface anymore. You can register only UI controllers that extend `Screen` class. The old behaviour is considered dangerous because a caller that opens such a screen receives `null` from `openWindow` call. Those screens must be changed: you can convert them into Spring beans or if you need to call them only from the menu - use `class` attribute of a menu item.

. ScreenAgent support has been removed without replacement. You can either open fragments in a screen depending on `DeviceInfo` or create separate screen for each device type.

. Old Havana UI theme completely reimplemented on the basis of Halo theme. If you have extended Havana you will need to migrate your SCSS styles accordingly. See https://github.com/cuba-platform/cuba/issues/1067[GitHub issue] for details.

. Property `wordwrap` of `TextArea` has been renamed to `wordWrap`. XML definitions still work, but `wordwrap` is removed from XSD and should not be used anymore.

. `ComponentPalette` has been removed. Use the standard mechanism with `cuba.web.componentsConfig` application property if your application component provides UI components.

. Deprecated `ObjectsCache` classes have been removed as a legacy and undocumented feature.

. Deprecated classes from charts `com.haulmont.charts.gui.amcharts.model.data` package have been removed. Use data items classes from `com.haulmont.charts.gui.data` package instead.

. Charts UI palette - the `ChartComponentPalette` class have been removed. Use the standard application component mechanism or include `charts-web-components.xml` into `cuba.web.componentsConfig` application property explicitly. If you did not use `ChartComponentPalette` then migration actions are not required.

. Class `com.haulmont.cuba.core.app.DataServiceQueryBuilder` has been renamed to `RdbmsQueryBuilder`.

. `com.haulmont.cuba.gui.components.RowsCount.BeforeRefreshEvent` does not have reference to a datasource anymore.

[[gui]]
=== Generic UI

* Generic UI now uses Vaadin 8.

* New {manual}/gui_screens.html[screen API].

* New {manual}/standard_actions.html[standard actions].

* New {manual}/gui_data.html[data components] to replace datasources.

Old screen API, standard actions and datasources are kept for backward compatibility.

//[[rest]]
//=== REST API
//
//[[charts]]
//=== Charts Addon
//
//[[fts]]
//=== Full-Text Search Addon
//
//[[bpm]]
//=== BPM Addon

[[misc]]
=== Miscellaneous

. Java 8, 9 and 10 can be used to build and run applications. If you are going to run the application on Java 10, add the following dependencies to the `global` module in `build.gradle`:
+
[source, groovy]
----
configure(globalModule) {
    dependencies {
        runtime('javax.xml.bind:jaxb-api:2.3.1')
        runtime('org.glassfish.jaxb:jaxb-runtime:2.3.1')
    }
    // ...
----

. It is recommended to use underscore instead of "$" to separate namespace and class in entity names, for example `sales_Customer`.

[[upd_dep]]
=== Updated Dependencies

----
org.springframework = 5.0.10.RELEASE
org.eclipse.persistence/eclipselink = 2.7.2-2-cuba
com.vaadin = 8.5.2-1-cuba
org.codehaus.groovy = 2.5.2
com.google.guava = 26.0-jre
org.dom4j/dom4j = 2.1.0
----

[[studio]]
== Studio

All Studio functionality has been moved to the plugin for IntelliJ IDEA. It supports projects based on CUBA 6.10 and 7.0, so you can open an existing project in the new Studio and migrate it to the new framework version. See {studio}[CUBA Studio User Guide] for details.

If you need premium add-ons (Reports, BPM, etc.) and have a subscription, you should set the premium repository access credentials in `~/.gradle/gradle.properties` as described in the {manual}/access_to_repo.html#access_to_premium_repo[documentation]. At the moment, Studio 7.0 Beta does not pass the credentials to Gradle.