= CUBA Platform Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.1
:version-label: Version
:revremark: Copyright (c) 2019 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:restapi: https://doc.cuba-platform.com/restapi-{revnumber}
:studio: https://doc.cuba-platform.com/studio
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/master/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform version {revnumber}.

== All Resolved Issues

//* {githubissueslog}/release_7.0.1.md[Platform 7.0.1 Resolved Issues]

[[breaking_changes]]
== Breaking Changes

. Removed previously deprecated `LoginService` and `LoginWorker` classes. Use corresponding methods of `AuthenticationService` and `TrustedClientService`:
** `LoginService.login()` -> `AuthenticationService.login()` with `LoginPasswordCredentials`
** `LoginService.loginTrusted()` -> `AuthenticationService.login()` with `TrustedClientCredentials`
** `LoginService.loginByRememberMe()` -> `AuthenticationService.login()` with `RememberMeCredentials`
** `LoginService.loginByRememberMe()` -> `AuthenticationService.login()` with `RememberMeCredentials`
** `LoginService.substituteUser()` -> `AuthenticationService.substituteUser()`
** `LoginService.getSession()` -> `TrustedClientService.findSession()`
** `LoginService.getSystemSession()` -> `TrustedClientService.getSystemSession()`

. Removed previously deprecated `CubaAuthProvider` interface, its implementations and `cuba.web.externalAuthentication` and `cuba.web.externalAuthenticationProviderClass` application properties. Use events, `LoginProvider` and `HttpRequestFilter` as explained in the {manual}/web_login.html[documentation].

. In `Table` and `GroupTable` interfaces, removed previously deprecated methods that manipulate with columns:
+
[source, java]
----
// removed from Table
void setColumnCaption(String columnId, String caption);
void setColumnCaption(Table.Column column, String caption);
void setColumnDescription(String columnId, String description);
void setColumnDescription(Table.Column column, String description);
void setColumnCollapsed(String columnId, boolean collapsed);
void setColumnCollapsed(Table.Column column, boolean collapsed);
void setColumnWidth(String columnId, int width);
void setColumnWidth(Table.Column column, int width);
void setColumnAlignment(String columnId, ColumnAlignment alignment);
void setColumnAlignment(Column column, ColumnAlignment alignment);
void addAggregationProperty(String columnId, AggregationInfo.Type type);
void addAggregationProperty(Column columnId, AggregationInfo.Type type);
void removeAggregationProperty(String columnId);
void setColumnSortable(String columnId, boolean sortable);
boolean getColumnSortable(String columnId);
void setColumnSortable(Column column, boolean sortable);
boolean getColumnSortable(Column column);
void setColumnCaptionAsHtml(String columnId, boolean captionAsHtml);
void setColumnCaptionAsHtml(Table.Column column, boolean captionAsHtml);
boolean getColumnCaptionAsHtml(String columnId);
boolean getColumnCaptionAsHtml(Table.Column column);

// removed from GroupTable
boolean getColumnGroupAllowed(String columnId);
void setColumnGroupAllowed(String columnId, boolean allowed);
boolean getColumnGroupAllowed(Table.Column column);
void setColumnGroupAllowed(Table.Column column, boolean allowed);
----
+
Instead of the removed methods, use the following approach:
+
[source, java]
----
Table.Column<Foo> numberColumn = fooTable.getColumn("number"); // get Column object by column id
numberColumn.setCaption("Num"); // invoke Column's methods
----

. The REST API functionality has been moved to the https://github.com/cuba-platform/restapi[REST API] add-on, see its {restapi}[documentation]. The Studio migration procedure includes the add-on in the project if the project contains some REST configuration files or Frontend UI module. Otherwise, the REST servlet and filter are removed from `web.xml` of the `web` module.

. The legacy REST API v1 functionality has been moved to the https://github.com/cuba-platform/jpawebapi[JPA Web API] add-on. Studio does not provide any automatic migration, so use the installation instructions in README if you need this functionality in the project.

[[gui]]
== Generic UI

* Now you can create new visual components by combining existing ones, see {manual}/composite_components.html[Composite Components].

* The concept of non-visual components has been generalized and made extendable, see {manual}/gui_facets.html[Non-Visual Components]. Along with {manual}/gui_Timer.html[Timer], the framework now provides new useful non-visual components: {manual}/gui_ClipboardTrigger.html[ClipboardTrigger] and `DataLoadCoordinator`.

* The {manual}/gui_DataLoadCoordinator.html[DataLoadCoordinator] component is designed for declarative linking of data loaders to data containers, visual components and screen events. You can use this component instead of writing event handlers in Java.

* The {manual}/gui_Form.html[Form] component can now contain generic fields defined with the `field` element. The framework will choose an appropriate visual component on the basis of the corresponding entity attribute and existing component generation strategies.

* Introduced {manual}/gui_dialogs.html#gui_input_dialog[input dialog] which allows you to construct input forms using API. It can be used instead of creating screens for trivial data input.

* Now you can make some screens of your application available to non-authenticated users, see {manual}/gui_anonymous_access.html[Anonymous Access to Screens].

* Standard login and main screens have been reworked using the new screens API, see details in {manual}/gui_root_screens.html[Root Screens]. The main screen has the layout with side menu, so it is used by default for new projects. For projects, migrated from previous versions of the framework, the Studio migration procedure adds the following application properties to `web-app.properties`:
+
----
cuba.web.loginScreenId = loginWindow
cuba.web.mainScreenId = mainWindow
----
+
It ensures the migrated project uses the legacy login and main screens. If you want to switch to the new screens, remove these properties.

* Logout button shown on the standard main screen has been replaced with the `UserActionsButton` component. If the user is not authenticated, the component allows the user to go to login screen; when authenticated, the component provides actions to show the *Settings* screen or to log out.

* If a screen controller has public setters to accept parameters, they can be passed from the main menu, see {manual}/menu.xml.html#menu.xml_screen_properties[menu.xml].

* If a screen fragment controller has public setters to accept parameters, they can be specified in the host screen XML, see {manual}/using_screen_fragments.html#using_screen_fragment_params[Passing parameters to fragments].

* Screen fragments now send attach/detach lifecycle event when a fragment is added/removed to the host screen, see {manual}/screen_fragment_events.html[ScreenFragment Events]. Also, when a fragment is created programmatically, you don't need to invoke its `init()` method anymore, because all fragment's lifecycle events will be sent automatically when the fragment is added to a screen.

* Sorting of UI tables by entity attributes can now be {manual}/gui_data_comp_sort.html[customized].

* In order to simplify migration from version 6 of the framework, we have restored the undocumented ability to use legacy API screens as frames. It is now supported for subclasses of `AbstractWindow`, `AbstractLookup` and `EntityCombinedScreen` (`AbstractEditor` is not supported). The `init()` method of the screen is invoked, `ready()` is not, as before.

* The framework now provides infrastructure for writing integration tests on the web tier for testing UI in full-functioning Spring container, see {manual}/integration_tests_client.html[Web Integration Tests].

[[misc]]
== Miscellaneous

* `DataManager` can now perform {manual}/bean_validation_running.html#bean_validation_in_DataManager[bean validation] of saved entity instances. Use {manual}/app_properties_reference.html#cuba.dataManagerBeanValidation[cuba.dataManagerBeanValidation] property to control whether the validation is performed by default.
+
When you upgrade an existing project to CUBA 7.1, the Studio migration procedure sets this property to `false` to switch off the validation.

* `DataManager` now uses `_base` view by default (previously it was `_local`). So when you execute a request without specifying a view, like
`dataManager.load(Person.class).id(someId).one()`, you will get the result entity with fetched local attributes and attributes specified in `@NamePattern`. If `@NamePattern` contains reference attributes, more data will be fetched than before.

* Introduced `LoadContext.setIds()` method which accepts a collection of entity identifiers. It is used by `DataManager.loadList()` method in higher priority than passed query or single id. The fluent interface also has methods accepting multiple ids:
+
[source,java]
----
dataManager.load(Customer.class).ids(customer1Id, customer2Id).list();

List<UUID> idList = Arrays.asList(customer1Id, customer2Id);
dataManager.load(Customer.class).ids(idList).list();
----


[[upd_dep]]
== Updated Dependencies

Core framework:
----
----

Full-Text Search add-on:
----
----

Reports add-on:
----
----
