= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.10
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/release_6_10/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

=== All Resolved Issues

* {githubissueslog}/release_6.10.0.md[Platform 6.10.0 Resolved Issues]


[[platform_breaking_changes]]
=== Breaking Changes

. Due to the enhancement https://github.com/cuba-platform/cuba-gradle-plugin/issues/48[#48], `build.gradle` of an existing project must be changed in the part where the entities enhancing is declared. Instead of using `CubaEnhancing` task like this:
+
----
task enhance(type: CubaEnhancing) {
    persistenceConfig = 'custom-persistence.xml' // optional
}

task testEnhance(type: CubaTestEnhancing) {
    persistenceConfig = 'test-persistence.xml'
}
----
+
use the following DSL:
+
----
entitiesEnhancing {
    main {
        enabled = true
        persistenceConfig = 'custom-persistence.xml' // optional
    }
    test {
        enabled = true
        persistenceConfig = 'test-persistence.xml'
    }
}
----
+
If you are using Studio, the migration will be done automatically.

. While implementing the <<gui_hover_theme,new theme>>, we had to refactor the standard login window. If you have extended the login window in your project, you should adapt your code to be compatible with the new base implementation. See https://github.com/cuba-platform/cuba/issues/932#loginformchanges[changes] and https://github.com/cuba-platform/cuba/issues/932#samplemigration[example migration] for details.

. Due to https://github.com/cuba-platform/cuba/issues/469[this enhancement] your code may not compile if you have created a custom `DataSupplier` and implemented the `commit()` method. In order to fix the code, change the method return type to `EntitySet`.

. REST v1 is now disabled by default (see https://github.com/cuba-platform/cuba/issues/1027[#1027]). To enable it in your project, add the following line to the `web-dispatcher-spring.xml` or `portal-dispatcher-spring.xml`:
+
[source, xml]
----
<context:component-scan base-package="com.haulmont.cuba.restapi"/>
----

. If `anonymous` session cannot be loaded due to a database connection problem or other error, server does not start at all. See https://github.com/cuba-platform/cuba/issues/1080[#1080].

[[gui]]
=== Generic UI

[[gui_hover_theme]]
* Created a new visual theme: Hover. See details in the https://github.com/cuba-platform/cuba/issues/932[issue].

* Now it is possible to exclude properties from the Filter component recursively down to the object graph. See the {manual}/gui_Filter.html#gui_Filter_properties_excludeRecursively[excludeRecursively] property.

[[rest]]
=== REST API

. A certain service method can be marked as available without authentication even when the anonymous access to the whole REST API is disabled. See the `anonymousAllowed` attribute of a {manual}/rest_api_v2_services_config.html[service configuration].

[[charts]]
=== Charts Addon

. Pivot Table data can now be exported and downloaded in XLS and JSON formats using {charts}/pivotTable_extension.html[PivotTableExtension].

. The new {charts}/pivotTable_ShowPivotAction.html[ShowPivotAction] allows users to quickly export data from Table, Tree, or DataGrid to a pivot table.

[[fts]]
=== Full-Text Search Addon

. Search process and visualization of results have been changed considerably for better performance and accuracy. Now the results are checked for row-level security in batches. The search results screen has pages, which guarantees sequential loading of all available results. See https://github.com/cuba-platform/fts/issues/26[#26] for details.

[[reporting]]
=== Reporting Addon

. Reports can be generated and downloaded via {reporting}/rest_reports.html[REST API].

. The new _Copy_ button allows users to copy report templates. See https://github.com/cuba-platform/reports/issues/70[#70] for details.

. Ports available for OpenOffice can be set in the {reporting}/app_properties.html#reporting.openoffice.ports[reporting.openoffice.ports] application property.

[[misc]]
=== Miscellaneous

. A new experimental API has been introduced in this release: `EntityChangedEvent` and `TransactionalDataManager`.
+
--
`EntityChangedEvent` is a Spring's ApplicationEvent of the middle tier which is sent when an entity instance is saved to the database. The event can be handled both inside the transaction and after its completion (using `@TransactionalEventListener`). The event is sent only for entities annotated with `@PublishEntityChangedEvents`.

`EntityChangedEvent` does not contain the changed object but only its id. Also, the `getOldValue(attributeName)` method returns ids of references instead of objects. This is done intentionally to make the developer reload objects with required view, dynamic attributes and other parameters. This also allows us to keep the security and other logic just in one place - in the loading mechanism, and saves from potential bugs and inconsistencies.

`TransactionalDataManager` mimics the `DataManager` interface but can join to an existing transaction. It has the following properties:

** If there is an active transaction, `TransactionalDataManager` joins it, otherwise it creates and commits a transaction same as `DataManager`.
** It returns entities in detached state, so no automatic saving of changes on transaction commit is performed. Lazy loading also doesn't work, so a developer has to load entities with appropriate views.
** No persistence context, no implicit flushes.
** It applies row-level security, works with dynamic attributes and cross-datastore references as expected.

Please be informed that these features are not stable yet and we can change the API and implementation in the near future. See some additional information https://github.com/cuba-platform/cuba/pull/1033[here].
--

. Standard JPA lifecycle callbacks (`@PrePersist`, `@PreUpdate`, `@PostLoad`, etc.) can be used for simple changes of entity attributes before saving and after loading.

. The `create()` and `getReference()` methods have been added to the {manual}/dataManager.html[DataManager] interface.

// TODO

https://github.com/cuba-platform/cuba-gradle-plugin/issues/48

https://github.com/cuba-platform/cuba/issues/687

https://github.com/cuba-platform/cuba/issues/1148


[[upd_dep]]
=== Updated Dependencies

----
com.google.code.gson/gson = 2.8.5
com.haulmont.thirdparty/eclipselink = 2.6.2.cuba24
com.vaadin = 7.7.13.cuba.12
commons-codec/commons-codec = 1.11
commons-io/commons-io = 2.6
io.swagger/swagger-models = 1.5.21
org.apache.commons/commons-collections4 = 4.2
org.apache.commons/commons-compress = 1.18
org.apache.commons/commons-dbcp2 = 2.5.0
org.apache.commons/commons-lang3 = 3.7
org.apache.commons/commons-pool2 = 2.6.0
org.apache.httpcomponents/fluent-hc = 4.5.6
org.apache.httpcomponents/httpclient = 4.5.6
org.apache.httpcomponents/httpcore = 4.4.10
org.apache.httpcomponents/httpmime = 4.5.6
org.apache.tika/tika-parsers = 1.18
org.apache.tomcat/tomcat = 8.5.33
org.aspectj/aspectjrt = 1.9.1
org.aspectj/aspectjweaver = 1.9.1
org.codehaus.groovy/groovy-all = 2.4.15
org.freemarker/freemarker = 2.3.28
org.javassist/javassist = 3.23.1-GA
org.jgroups/jgroups = 3.6.16.Final
org.json/json = 20180130
org.jsoup/jsoup = 1.11.3
org.mybatis/mybatis = 3.2.8
org.mybatis/mybatis-spring = 1.2.5
org.spockframework/spock-core = 1.1-groovy-2.4
org.springframework = 4.3.18.RELEASE
org.springframework.security = 4.2.7.RELEASE
org.springframework.security.oauth/spring-security-oauth2 = 2.1.2.RELEASE
----

[[studio]]
== Studio

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%206.10%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.10.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 6.10.0 Resolved Issues]

[[studio_known_issues]]
=== Known Issues

If you use the in-place update in Studio SE on macOS, it will completely replace your application folder. If you previously added some JDBC drivers to `/Applications/Cuba Studio SE.app/Contents/Resources/app/studio/lib`, they will be lost and you will have to add them again.
