= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.9
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/PL?q=Milestone:%20%7BRelease%206.9%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.9.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Platform 6.9.0 Resolved Issues]


[[platform_breaking_changes]]
=== Breaking Changes

. Columns called `VALUE` in CUBA tables `SEC_USER_SETTING`, `SYS_CONFIG` and `SEC_PERMISSION` have been renamed to `VALUE_`. `VALUE` is a SQL reserved word and is not allowed as a column name in some databases. See {youtrack}/issue/PL-10334[PL-10334].

. In newly created databases, a denying role is assigned to the `anonymous` user by default. It means that this user cannot see or update any data through clients including REST API, and you have to explicitly grant permissions to the anonymous user. This change does not affect existing databases.

. Cleanup of the `SYS_QUERY_RESULT` table used by the {manual}/query_from_selected.html[sequential queries] mechanism is now performed by default once in 10 minutes. Database update scripts truncate the table during migration, so you database size may decrease.

. Access to not loaded attributes in {manual}/entity_listeners.html[BeforeDetachEntityListener] has been restricted: if the entity is loaded with a view, and you are trying to access a _local_ attribute not included in the view, `IllegalStateException` is thrown. It protects from possible data loss, because otherwise ORM would completely reloaded the instance.
+
Accessing reference attributes is possible regardless of the specified view. If the entity is loaded without a view (e.g. if you load it in a custom service), all local and reference attributes are available. See {youtrack}/issue/PL-10340[PL-10340].

. The JPQL `delete from` statement now throws exception if launched for soft-deleted entity and the soft delete mode is on. Such statement is actually transformed to SQL which deletes all instances not marked for deletion. This is counter-intuitive and disabled by default, but can be enabled by the {manual}/app_properties_reference.html#cuba.enableDeleteStatementInSoftDeleteMode[cuba.enableDeleteStatementInSoftDeleteMode] application property. See {youtrack}/issue/PL-10354[PL-10354].

. The `PersistenceTools.getOldValue()` method now returns old value for not changed attributes too (previously it returned `null` if the attribute wasn't changed). See {youtrack}/issue/PL-10361[PL-10361].

. The old (pre-6.8.1) mechanism of defining entity attribute access has been removed completely. If you still have setup rules based on Spring application events, you have to rewrite them as beans implementing the `SetupAttributeAccessHandler` interface. See {manual}/entity_attribute_access.html[documentation] for details.

. All SLF4J loggers in platform classes has been made `private static final`. If you have overridden a platform class and used its logger, you need to define a separate logger in your own class. See {youtrack}/issue/PL-10404[PL-10404].

. The `EntityManager.createNativeQuery(query, class)` method's target class is now parameterized as `<T extends Entity>`. It clearly states that the query result can be mapped only to an entity and not to an arbitrary POJO. See {youtrack}/issue/PL-10467[PL-10467].

. The `authenticate()` and `login()` methods of `AuthenticationManager` now always work in own transactions. Previously, they could join to an existing transaction if there was an active one. See {youtrack}/issue/PL-10548[PL-10548].

. The {manual}/app_properties_reference.html#cuba.performanceTestMode[cuba.performanceTestMode] application property has been introduced to indicate that the application is running performance tests. The old {manual}/app_properties_reference.html#cuba.testMode[cuba.testMode] property is now used only for automatic UI tests. See {youtrack}/issue/PL-10562[PL-10562].

[[gui]]
=== Generic UI

* Methods for programmatic grouping have been added to the {manual}/gui_GroupTable.html[GroupTable] component: `groupByColumns()`, `ungroupByColumns()` and `ungroup()`.

* The {manual}/gui_SplitPanel.html[SplitPanel] component now has a public API for dock button. See `setDockable/isDockable`, `setDockMode/getDockMode` methods and `dockable`, `dockMode` XML attributes.

* The `inputPrompt` XML attribute can be used in {manual}/gui_FieldGroup.html[FieldGroup] fields.

* The _Clear values_ action has been added to the {manual}/gui_Filter.html[Filter] component. By default, it is available in the filter settings drop-down menu. If you want to display it as a separate button, use the {manual}/app_properties_reference.html#cuba.gui.genericFilterControlsLayout[cuba.gui.genericFilterControlsLayout] application property.

* Now all beans implementing Vaadin's `BootstrapListener` interface will be subscribed to HTML bootstraping. So there is no need to extend `CubaBootsrtapListener` to add static content, and application components may add their BootstrapListener's  independently.

* The {manual}/link_to_screen.html[screen links] mechanism has been reworked to provide better extensibility. The `LinkHandler` bean now just delegates to the chain of processors, and you can provide your own processors without redefining platform code. If you have overridden `LinkHandler` in your project, your code will continue to work, but we recommend refactoring it to conform to the new structure described in the documentation.

[[rest]]
=== REST API

* REST API {manual}/rest_api_v2_queries_config.html[queries] can contain parameters that take values of the current user id and login: `session$userId` and `session$userLogin`.

* The `query` element can have the `cacheable` attribute that enables caching of the query.

* The {manual}/rest_api_v2_security_constraints.html[security token] is not sent by default even if there are security constraints defined for the entity. Use {manual}/app_properties_reference.html#cuba.rest.requiresSecurityToken[cuba.rest.requiresSecurityToken] application property to control this behavior.

[[charts]]
=== Charts Addon

* PivotTable has been updated and got new renderers, properties and {charts}/pivotTable.html#chart_PivotTable_CellClickListener[CellClickListener]. See details in {youtrack}/issue/PL-9689[PL-9689] and in the {charts}/pivotTable.html[documentation].

* `bezierX` and `bezierY` properties have been removed from the `com.haulmont.charts.gui.amcharts.model.Settings` class and added to `SerialChart` model and component classes. These properties can also be used in XML descriptors.

* `accessibleDescription` property has been added for all charts and can be used both in XML and Java.

[[misc]]
=== Miscellaneous

* {manual}/entity_log.html[Entity Log] now supports embedded attributes. On the _Entity Log > Setup_ tab, attributes of embedded entities are displayed after the dot. For example, if `Employee` entity contains `Address` embeddable entity, you will be able to set up logging of `Address` attributes like `address.zip`, `address.line1`, etc.

* The `@Secret` annotation can be used on a property of a {manual}/config_interface_usage.html[configuration interface] in order to mask its value on the _Administration > Application Properties_ screen.

* The `NEW` operator is now supported in JPQL select queries, for example:
+
----
select new com.company.example.CustomerDetails(c.id, c.status) from app$Customer c
----

* In the {manual}/background_tasks.html[background tasks] mechanism, `isCancelled()` method has been added to the `TaskLifeCycle` interface. It returns true if the task was interrupted by calling its `cancel()` method.

* Default methods can be used in {manual}/config_interfaces.html[configuration interfaces]. See an example in the {youtrack}/issue/PL-10565[issue].

[[upd_dep]]
=== Updated Dependencies

Java:

----
com.fasterxml.jackson = 2.9.4
com.google.code.gson/gson = 2.8.2
com.google.gwt = 2.8.2
com.vaadin = 7.7.13.cuba.8
javax.servlet/javax.servlet-api = 3.1.0
org.apache.commons/commons-pool2 = 2.4.3
org.apache.httpcomponents/fluent-hc = 4.5.5
org.apache.httpcomponents/httpclient = 4.5.5
org.apache.httpcomponents/httpcore = 4.4.9
org.apache.httpcomponents/httpmime = 4.5.4
org.apache.lucene = 7.2.1
org.apache.tika/tika-parsers = 1.17
org.codehaus.groovy/groovy-all = 2.4.13
org.springframework = 4.3.14.RELEASE
org.springframework.ldap/spring-ldap-core = 2.3.2.RELEASE
org.springframework.security = 4.2.4.RELEASE
org.thymeleaf = 3.0.9.RELEASE
----

JavaScript:

----
org.webjars.bower/pivottable = 2.20.0.cuba.0
org.webjars/amcharts = 3.21.12.cuba.1
----

[[studio]]
== Studio

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%206.9%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.9.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 6.9.0 Resolved Issues]
