= CUBA Platform and Studio Release Notes - WORK IN PROGRESS
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.7
:version-label: Version
:revremark: Copyright (c) 2017 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/PL?q=Milestone:%20%7BRelease%206.7%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.7.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Platform 6.7.0 Resolved Issues]


[[platform_breaking_changes]]
=== Breaking Changes

. Due to improvements in <<datatype,datatypes>>, a migration of custom datatypes is needed. Studio does it automatically when you switch to the new platform version. If you don't use Studio and your project has custom datatypes registered in `metadata.xml`, add `id` attribute to the `datatype` element and set it to the value of the `NAME` constant of your datatype class. For example:
+
[source, xml]
----
<datatype id="year" class="com.company.sample.YearDatatype"/>
----

[[data_model]]
=== Data Model

[[entity_base_classes]]
==== Base Classes

Non-persistent entities should be inherited form the same {manual}/base_entity_classes.html[base classes] as persistent ones: `BaseUuidEntity`, `BaseLongIdEntity`, and so on. It allows you to have identifiers of any type, which is important when non-persistent entities represent data from some data store. The framework determines if the entity is persistent or not by the file where it is registered: `persistence.xml` or `metadata.xml`.

`AbstractNotPersistentEntity` has been deprecated, but can still be used for backward compatibility.

[[number_format]]
==== Number Format

Using the new {manual}/entity_attr_annotations.html#numberFormat_annotation[@NumberFormat] annotation, you can define a display format for numeric attributes right in the entity class. So if you need just a specific formatting of an attribute, and don't need some custom conversion algorithm, then you don't have to create a {manual}/datatype.html[Datatype] for the attribute. For example, here is an integer number without grouping separators:

[source, java]
----
@Column(name = "SIMPLE_NUMBER")
@NumberFormat(pattern = "#")
protected Integer simpleNumber;
----

[[datatype]]
==== Datatypes

The {manual}/datatype.html[datatypes] mechanism has been improved for better extensibility.

The `getName()` method of the `Datatype` interface is deprecated, and implementation classes do not need the `NAME` constant. Instead, the `id` XML attribute is used when the implementation class is registered.

The `getJavaClass()` method of the `Datatype` interface now has a default implementation that returns a value of the `@JavaClass` annotation if it is present on the class.

All datatypes are registered in `metadata.xml` files, but if old `datatypes.xml` exists, it is loaded for backward compatibility.

There is no hard-coded list of "standard datatypes" anymore. The `default` XML attribute in `metadata.xml` indicates that the datatype should be used by default for a Java class handled by this datatype, i.e. this datatype will be resolved automatically for entity attributes of appropriate type. Standard datatypes are defined in the `cuba-metadata.xml` of the `cuba` application component. Subsequent `metadata.xml` files can add and override any datatype including default ones.

The `Datatypes` class became a thin wrapper delegating to the `DatatypeRegistry` and `FormatStringsRegistry` beans. It is recommended to use `DatatypeRegistry` directly. Its `getId*()` methods are designed to get an id the datatype is registered with.

[[gui]]
=== Generic UI

[[lookup_screen_customization]]
==== Lookup Screen Customization

When a browse screen is opened as a lookup, it contains an automatically added panel with buttons and a special lookup action. Now you can customize all these parts: replace the frame with buttons for all lookup screens in your project, create your own selection buttons for a certain screen, or customize the lookup action. See details in the {manual}/screen_lookup.html#screen_lookup_customization[documentation].

[[misc]]
=== Miscellaneous

[[attr_access_control]]
==== Entity Attribute Access Control

The security subsystem allows you to set up access to entity attributes according to user permissions. But sometimes you may want to change the access to attributes dynamically depending also on the current state of the entity or its linked entities. The new mechanism allows you to create rules of what attributes should be hidden, read-only or required for a particular entity instance, and apply these rules automatically to Generic UI components and REST API. See details in the {manual}/entity_attribute_access.html[documentation].

[[reporting]]
=== Reporting

[[upd_dep]]
=== Updated Dependencies

Java libraries:
----
com.esotericsoftware/kryo-shaded = 4.0.1
com.fasterxml.jackson = 2.9.0
com.google.code.gson/gson = 2.8.1
com.haulmont.thirdparty/eclipselink = 2.6.2.cuba18
com.haulmont.yarg = 2.0.7
com.microsoft.sqlserver/mssql-jdbc = 6.2.1.jre8
com.vaadin = 7.7.10.cuba.9
com.vaadin.addon/vaadin-context-menu = 0.7.5
commons-cli/commons-cli = 1.4
commons-fileupload/commons-fileupload = 1.3.3
commons-io/commons-io = 2.5
org.apache.commons/commons-collections4 = 4.1
org.apache.commons/commons-compress = 1.14
org.codehaus.groovy/groovy-all = 2.4.12
org.javassist/javassist = 3.21.0-GA
org.springframework = 4.3.10.RELEASE
org.springframework.security = 4.2.3.RELEASE
org.springframework.security.oauth/spring-security-oauth2 = 2.1.1.RELEASE
org.thymeleaf = 3.0.7.RELEASE
org.vaadin.addons/popupbutton = 2.6.0-3
org.webjars/amcharts = 3.20.20
org.webjars/pivottable = 2.3.0
----

[[studio]]
== Studio

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%206.7%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.7.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 6.7.0 Resolved Issues]

[[studio_breaking_changes]]
=== Breaking Changes


[[studio_repositories]]
=== Repository Configuration

