= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.9
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/PL?q=Milestone:%20%7BRelease%206.9%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.9.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Platform 6.9.0 Resolved Issues]


[[platform_breaking_changes]]
=== Breaking Changes

. Columns called `VALUE` in CUBA tables `SEC_USER_SETTING`, `SYS_CONFIG` and `SEC_PERMISSION` have been renamed to `VALUE_`. `VALUE` is a SQL reserved word and is not allowed as a column name in some databases. See {youtrack}/issue/PL-10334[PL-10334].

. Access to not loaded attributes in {manual}/entity_listeners.html[BeforeDetachEntityListener] has been restricted: if the entity is loaded with a view, and you are trying to access a _local_ attribute not included in the view, `IllegalStateException` is thrown. It protects from possible data loss, because otherwise ORM would completely reloaded the instance.
+
Accessing reference attributes is possible regardless of the specified view. If the entity is loaded without a view (e.g. if you load it in a custom service), all local and reference attributes are available. See {youtrack}/issue/PL-10340[PL-10340].

. The JPQL `delete from` statement now throws exception if launched for soft-deleted entity and the soft delete mode is on. Such statement is actually transformed to SQL which deletes all instances not marked for deletion. This is counter-intuitive and disabled by default, but can be enabled by the {manual}/app_properties_reference.html#cuba.enableDeleteStatementInSoftDeleteMode[cuba.enableDeleteStatementInSoftDeleteMode] application property. See {youtrack}/issue/PL-10354[PL-10354].

[[upd_dep]]
=== Updated Dependencies

Java:

----
com.fasterxml.jackson = 2.9.4
com.google.code.gson/gson = 2.8.2
com.google.gwt = 2.8.2
com.vaadin = 7.7.13.cuba.8
javax.servlet/javax.servlet-api = 3.1.0
org.apache.commons/commons-pool2 = 2.4.3
org.apache.httpcomponents/fluent-hc = 4.5.5
org.apache.httpcomponents/httpclient = 4.5.5
org.apache.httpcomponents/httpcore = 4.4.9
org.apache.httpcomponents/httpmime = 4.5.4
org.apache.lucene = 7.2.1
org.apache.tika/tika-parsers = 1.17
org.codehaus.groovy/groovy-all = 2.4.13
org.springframework = 4.3.14.RELEASE
org.springframework.ldap/spring-ldap-core = 2.3.2.RELEASE
org.springframework.security = 4.2.4.RELEASE
org.thymeleaf = 3.0.9.RELEASE
----

JavaScript:

----
org.webjars.bower/pivottable = 2.20.0.cuba.0
org.webjars/amcharts = 3.21.12.cuba.1
----

[[studio]]
== Studio

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%206.9%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.9.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 6.9.0 Resolved Issues]
