= CUBA Platform Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.2
:version-label: Version
:revremark: Copyright (c) 2019 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:restapi: https://doc.cuba-platform.com/restapi-{revnumber}
:studio: https://doc.cuba-platform.com/studio
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}
:charts: https://doc.cuba-platform.com/charts-{revnumber}
:bpm: https://doc.cuba-platform.com/bpm-{revnumber}
:githubissueslog: https://github.com/cuba-platform/documentation/blob/master/content/release_notes/issues

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform version {revnumber}.

== All Resolved Issues

* {githubissueslog}/release_7.2.0.md[Platform 7.2.0 Resolved Issues]

[[breaking_changes]]
== Breaking Changes

[[gui]]
== Generic UI

[[deployment]]
== Deployment

. Usage of {manual}/app_home.html[Application Home] has been standardized for development and deployment environment. When you start the application in Studio, the application home is created in `deploy/app_home` directory. It contains `conf`, `temp` and `work` directories for all application blocks, as well as the common `logs` directory. The application home also contains the empty `local.app.properties` file and the default logging configuration in `logback.xml`.
+
[WARNING]
====
In order to correctly work with the application home, development Tomcat must define `app.home` Java system property in its `setenv.*` scripts. So remove the old `deploy/tomcat` folder after upgrading to CUBA 7.2 and before running the application. The new Tomcat will be installed automatically.
====
+
Setting `app.home` Java system property is recommended for all deployment variants, however sensible fallback is provided by the framework: it is either the working directory for UberJAR, or `${catalina.base}/work/app_home` when running WAR on Tomcat, or just `~/.app_home` otherwise.

. You can easily provide your own {manual}/logging.html[logging configuration] for the development environment: just create `etc/logback.xml` file in the project, and when you start the application, the file will be copied to `deploy/app_home` and recognized by the logging initialization procedure.

. Now you can configure connections to databases using application properties, see {manual}/db_connection.html[Connecting to Databases]. This method simplifies the overall configuration, because `app.properties` files define all settings including the data source parameters. Also, it makes your WAR file completely independent of the application server environment.
+
Getting data sources from JNDI is supported as before, so no migration is required for existing projects.

. {manual}/spring_profiles.html[Spring profiles] can be used to customize application in different environments.

. OS environment variables can be used as a source of {manual}/app_properties.html#setting_app_properties[application properties] values.

[[misc]]
== Miscellaneous

[[upd_dep]]
== Updated Dependencies

Core framework:
----
----

Reports add-on:
----
----
