= CUBA Platform and Studio Release Notes
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.7
:version-label: Version
:revremark: Copyright (c) 2017 Haulmont
:youtrack: https://youtrack.cuba-platform.com
:manual: https://doc.cuba-platform.com/manual-{revnumber}
:manual_app_props: https://doc.cuba-platform.com/manual-{revnumber}/app_properties_reference.html#
:reporting: https://doc.cuba-platform.com/reporting-{revnumber}

:!sectnums:

[[overview]]
== Overview

This document highlights major changes in CUBA Platform and Studio version {revnumber}.

[[platform]]
== Platform

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/PL?q=Milestone:%20%7BRelease%206.7%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.7.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Platform 6.7.0 Resolved Issues]


[[platform_breaking_changes]]
=== Breaking Changes


[[data_model]]
=== Data Model

[[entity_base_classes]]
==== Base Classes

Non-persistent entities should be inherited form the same base classes as persistent ones: `BaseUuidEntity`, `BaseLongIdEntity`, and so on. It allows you to have identifiers of any type, which is important when non-persistent entities represent data from some data store. The framework determines if the entity is persistent or not by the file where it is registered: `persistence.xml` or `metadata.xml`.

`AbstractNotPersistentEntity` has been deprecated, but can still be used for backward compatibility.

[[deployment]]
=== Deployment

[[gui]]
=== Generic UI

[[lookup_screen_customization]]
==== Lookup Screen Customization

When a browse screen is opened as a lookup, it contains an automatically added panel with buttons and a special lookup action. Now you can customize all these parts: replace the frame with buttons for all lookup screens in your project, create your own selection buttons for a certain screen, or customize the lookup action. See details in the {manual}/screen_lookup.html#screen_lookup_customization[documentation].

[[misc]]
=== Miscellaneous

[[reporting]]
=== Reporting

[[upd_dep]]
=== Updated Dependencies

Java libraries:
----
ch.qos.logback/logback-classic = 1.2.3
com.fasterxml.jackson = 2.8.8.1
com.fasterxml.jackson.dataformat/jackson-dataformat-yaml = 2.8.8
com.google.code.findbugs/jsr305 = 3.0.2
com.vaadin = 7.7.10.cuba.0
commons-collections/commons-collections = 3.2.2
mysql/mysql-connector-java = 5.1.41
org.apache.commons/commons-compress = 1.13
org.apache.tomcat/tomcat-servlet-api = 8.0.43
org.codehaus.groovy/groovy-all = 2.4.10
org.hibernate/hibernate-validator = 5.4.1.Final
org.slf4j/log4j-over-slf4j = 1.7.25
org.springframework = 4.3.8.RELEASE
org.springframework.ldap/spring-ldap-core = 2.3.1.RELEASE
org.springframework.security = 4.2.2.RELEASE
org.springframework.security.oauth/spring-security-oauth2 = 2.1.0.RELEASE
org.thymeleaf = 3.0.5.RELEASE
org.thymeleaf.extras/thymeleaf-extras-springsecurity4 = 3.0.2.RELEASE
tomcat = 8.5.14
----

JavaScript libraries:
----
node.js = 8.1.2
npm = 5.0.3
----

[[studio]]
== Studio

=== All Resolved Issues

* https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%206.7%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%206.7.0%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 6.7.0 Resolved Issues]

[[studio_breaking_changes]]
=== Breaking Changes


[[studio_repositories]]
=== Repository Configuration

