:sourcesdir: ../../../../../../source

[[gui_formatter]]
====== Formatter

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Formatter.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Formatter предназначен для преобразования некоторого значения в строку.

[WARNING]
====
Formatter предназначен для использования с read-only компонентами, такими как <<gui_Label,Label>>, колонка <<gui_Table,Table>> и тому подобными. Для форматирования значения в редактируемых компонентах, например <<gui_TextField,TextField>>, используйте механизм <<datatype,Datatype>>.
====

В XML-дескрипторе экрана formatter для компонента может быть задан во вложенном элементе `formatter`. Элемент имеет единственный атрибут:

* `class` − имя класса, реализующего интерфейс `com.haulmont.cuba.gui.components.Formatter`

Если конструктор класса formatter принимает параметр типа `org.dom4j.Element`, то ему будет передан элемент XML, описывающий данный `formatter`. Это можно использовать для параметризации экземпляра formatter'а, например, строкой форматирования. В частности, имеющиеся в платформе классы `DateFormatter` и `NumberFormatter` могут брать строку форматирования из атрибута `format`. Пример использования:

[source, xml]
----
include::{sourcesdir}/gui_vcl/formatter_1.xml[]
----

Кроме того, класс `DateFormatter` распознает также атрибут `type`, который может принимать значения `DATE` или `DATETIME`. В этом случае форматирование производится с помощью механизма <<datatype,Datatype>> по строке формата `dateFormat` или `dateTimeFormat` соответственно. Например:

[source, xml]
----
include::{sourcesdir}/gui_vcl/formatter_2.xml[]
----

По умолчанию, `DateFormatter` отображает дату и время в часовом поясе сервера. Чтобы учитывать часовой пояс текущего пользователя, установите значение `true` для атрибута `useUserTimezone` элемента formatter.

[TIP]
====
Если formatter реализован внутренним классом, то он должен быть объявлен с модификатором `static`, а его имя для загрузки отделяется символом "$", например:

`<formatter class="com.sample.sales.gui.OrderBrowse$CurrencyFormatter"/>`
====

Formatter можно назначить компоненту не только в XML-дескрипторе экрана, но и программно, передавая экземпляр formatter'а в метод `setFormatter()` компонента.

Пример объявления собственного formatter'а и использования его для форматирования значения колонки таблицы:

[source, java]
----
include::{sourcesdir}/gui_vcl/formatter_3.java[]
----

[source, java]
----
include::{sourcesdir}/gui_vcl/formatter_4.java[]
----

