:sourcesdir: ../../../../source

[[app_components_dev]]
==== Creating Application Components

This section contains some recommendations useful if you are developing a reusable application component.

[[app_components_dev_naming]]
Naming rules::
+
--
. Choose the root package using the standard reverse-DNS notation, e.g. `com.jupiter.amazingsearch`.
+
Root package should not begin with a root package of any other component or application. For example, if you have an application with `com.jupiter.tickets` root package, you cannot use `com.jupiter.tickets.amazingsearch` package for a component. The reason is that Spring scans the classpath for the beans starting from the specified root package, and this scanning space must be unique for each component.

. Namespace is used as a prefix for the database tables, so for a public component it should be composite, like `jptams`, not just `search`. It will minimize the risk of name collisions in the target application. You cannot use underscores and dashes in namespace, only letters and digits.

. Module prefix should repeat namespace, but can contain dashes, like `jpt-amsearch`.

. Use namespace as a prefix for bean names and application properties, for example:
+
[source, java]
----
@Component("jptams_Finder")
@Property("jptams.ignoreCase")
----
--

[[app_components_dev_install_local]]
Installing into the local Maven repository::
+
--
In order to make the component available to the projects located on your computer, install it into the local Maven repository by executing the *CUBA > Advanced > Install app component* menu command. This command just runs the `install` Gradle task after stopping Gradle daemons.
--

[[app_components_dev_upload]]
Uploading to a remote Maven repository::
+
--
. Set up a repository as explained in <<private_repo>>.

. Specify your repository and credentials for the project instead of the standard CUBA repository.

. Open `build.gradle` of the component project in a text editor and add `uploadRepository` to the `cuba` section:
+
[source,groovy]
----
include::{sourcesdir}/development/app_comp_upload_1.groovy[]
----

. Open the component project in Studio.

. Run the `uploadArchives` Gradle task from the command line. The component's artifacts will be uploaded to your repository.

. Remove the component artifacts from your local Maven repository to ensure that they will be downloaded from the remote repository during the next assembling of the application project: just delete the `.m2/repository/com/company` folder located in your user home directory.

. Now, when you assemble and run the application that uses this component, it will be downloaded from the remote repository.
--
