:sourcesdir: ../../../source

[[ldap]]
=== Интеграция с LDAP

Интеграция CUBA-приложения c LDAP позволяет решить две задачи:

. Хранить пароли пользователей и управлять ими централизованно в базе данных LDAP.

. Для пользователей компьютеров, входящих в домен Windows, выполнять логин в приложение без ввода имени и пароля (то есть организовывать Single Sign-On).

В режиме интеграции с LDAP пользователи по-прежнему должны иметь учетную запись в приложении. Все разрешения и параметры пользователя (кроме пароля) хранятся в БД приложения, LDAP используется только для аутентификации, т.е. проверки имени и пароля. Пароль в приложении для большинства пользователей, за исключением тех, кому требуется стандартная аутентификация (см. ниже), рекомендуется не задавать вообще. Поле пароля в экране редактирования пользователя не является обязательным к заполнению, если свойство <<cuba.web.requirePasswordForNewUsers,cuba.web.requirePasswordForNewUsers>> установлено в `false`.

Если логин пользователя перечислен в свойстве приложения <<cuba.web.standardAuthenticationUsers,cuba.web.standardAuthenticationUsers>>, то он всегда аутентифицируется обычным способом через хранимый в базе данных приложения хэш пароля. Поэтому если для некоторого пользователя из данного списка пароль в приложении задан, он сможет войти в систему с этим паролем, если в LDAP такого пользователя нет.

Взаимодействие CUBA-приложения с LDAP осуществляется через бин `LdapLoginProvider`.

Для расширенной интеграции с Active Directory и обеспечения Single Sign-On для пользователей домена Windows можно использовать библиотеку *Jespa* и соответствующую имплементацию `CubaAuthProvider`, которая описана в <<jespa,>>.

Вы можете реализовать свой механизм входа при помощи интерфейсов `LoginProvider`, `HttpRequestFilter` и обработчиков событий, как это описано в разделе <<web_login, Специфика процесса входа в Web Client>>.

Также вы можете включить LDAP аутентификацию для клиентов REST API: <<rest_api_v2_ldap,LDAP аутентификация для REST API>>.

include::ldap/ldap_basic.adoc[]

include::ldap/jespa.adoc[]

