:sourcesdir: ../../../source

[[security_web]]
=== Безопасность веб-приложения

*Защищены ли CUBA приложения?*

Фреймворк CUBA Platform следует лучшим практикам безопасности и предоставляет автоматическую защиту от большинства самых распространённых уязвимостей веб-приложений. Архитектура платформы реализует безопасную модель программирования, позволяя вам сконцентрироваться на бизнес задачах и логике приложений.

1. *Состояние и валидация данных UI*
+
<<gui_web,Web Client>> - серверное приложение, в котором всё состояние вашего приложения, бизнес- и UI-логика расположены на сервере. В отличие от фронтенд-фреймворков, исполняющих код UI в веб-браузере, веб-клиент никогда не открывает серверные структуры данных для клиентской части, где уязвимости могут быть использованы злонамеренным кодом. Валидация данных всегда выполняется на сервере, гарантируя, что злонамеренные пользователи не смогут её обойти, то же самое применимо и к валидации данных в универсальном <<rest_api_v2,REST API>>.

2. *Межсайтовый скриптинг (Cross-Site Scripting / XSS)*
+
Веб-клиент имеет встроенную защиту от атак межсайтового скриптинга (XSS). Все выводимые данные автоматически преобразуются в HTML формат перед тем как они будут показаны в веб-браузере.

3. *Межсайтовая подделка запроса (Cross-Site Request Forgery / CSRF)*
+
Все запросы между сервером и клиентом включают CSRF токен, специфичный для пользовательской сессии. Фреймворк https://vaadin.com/framework/[Vaadin] обеспечивает всё взаимодействие между сервером и клиентом, поэтому вам не потребуется добавлять CSRF токен к каждому запросу вручную.

4. *Веб-сервисы*
+
Все сетевые вызовы в веб-клиенте проходят через один веб-сервис, используемый для вызова удалённых процедур (RPC) из клиентской части UI компонентов. Приложения не открывают доступ к своей бизнес-логике в виде веб-сервисов, поэтому пользователям доступно меньшее количество точек входа для возможных атак.
+
Универсальный REST API автоматически применяет разрешения ролей и все ограничения (constraints) как для пользователей системы, выполнивших вход, так и при анонимном доступе.

5. *SQL Инъекции*
+
Платформа использует слой <<orm,ORM>> на базе EclipseLink, реализующую защиту от SQL инъекций. Параметры SQL запросов всегда передаются в JDBC в виде массива параметров и не подставляются в SQL запросы в виде строк.

