:sourcesdir: ../../../source

[[sso]]
=== Single-Sign-On для приложений CUBA

Single-Sign-On (единый вход, SSO) для приложений CUBA позволяет пользователям входить в несколько запущенных приложений, введя единые имя и пароль один раз в течение сессии веб-браузера.

При использовании SSO существуют два типа приложений:

* Identity Provider (IDP) - приложение, обеспечивающее аутентификацию пользователей. Оно содержит форму для ввода логина/пароля и выполняет их проверку в соответствии со списком зарегистрированных пользователей. Identity Provider в некоторой SSO-системе может быть только один.

* Service Provider (SP) - обычное приложение, которое перенаправляет к IDP для аутентификации пользователей. SP должен содержать тот же список пользователей, что и IDP (пароли при этом не важны, так как они проверяются на IDP). SP обеспечивает проверку прав пользователей в соответствии с их ролями и группами доступа. Количество SP в SSO-системе не ограничено.

Приложение может одновременно выполнять функции IDP и SP, то есть установка отдельного IDP не требуется. Функциональность SSO предоставляется модулем *cuba-idp*, входящим в состав <<app_tiers,блока>> Web Client. Приложение можно разрабатывать как обычно, а SSO настроить уже на этапе деплоймента, если требуется.

[WARNING]
====
CUBA SSO использует собственный протокол, основанный на HTTP, и на данный момент не поддерживает интеграции с системами, использующими стандартные протоколы аутентификации, такие как SAML или OIDC.
====

При использовании SSO, когда пользователь заходит на адрес SP, он перенаправляется на страницу IDP для ввода имени и пароля. После успешной аутентификации, IDP перенаправляет пользователя обратно в приложение SP, где пользователь входит автоматически.

Для настройки SSO необходимо выполнить следующее:

* На Identity Provider:

** Добавьте следующую конфигурацию в файл `web.xml` модуля *web* (если вы выполняете настройку на этапе деплоймента, данный файл находится здесь: `tomcat/webapps/app/WEB-INF/web.xml`):
+
[source, xml]
----
include::{sourcesdir}/security/sso_1.xml[]
----

** Установите свойства приложения:

*** <<cuba.idp.serviceProviderUrls,cuba.idp.serviceProviderUrls>> - разделенный запятыми список URL приложений SP (символ `/` в конце URL обязателен). Например:
+
[source]
----
cuba.idp.serviceProviderUrls = http://fish:8081/app/,http://chips:8082/app/
----

*** <<cuba.idp.serviceProviderUrlMasks,cuba.idp.serviceProviderUrlMasks>> - разделенный запятыми список масок разрешенных URL в формате Java Regex (символ `/` в конце URL обязателен). Например:
+
[source]
----
cuba.idp.serviceProviderUrlMasks = http://your-fish.com/.*,http://your-chips.com/.*
----

*** <<cuba.idp.serviceProviderLogoutUrls,cuba.idp.serviceProviderLogoutUrls>> - разделенный запятой список URL, которые используются для уведомления SP о логауте или истечении сессии пользователей. Стандартные приложения CUBA принимают такие запросы на адресе `/dispatch/idpc/logout`. Например:
+
[source]
----
cuba.idp.serviceProviderLogoutUrls = http://fish:8081/app/dispatch/idpc/logout,http://chips:8082/app/dispatch/idpc/logout
----

*** <<cuba.idp.trustedServicePassword,cuba.idp.trustedServicePassword>> - пароль, используемый в коммуникации server-to-server между SP и IDP.

*** Опциональные свойства: <<cuba.idp.sessionExpirationTimeoutSec,cuba.idp.sessionExpirationTimeoutSec>>, <<cuba.idp.ticketExpirationTimeoutSec,cuba.idp.ticketExpirationTimeoutSec>>, <<cuba.idp.sessionExpirationCheckIntervalMs,cuba.idp.sessionExpirationCheckIntervalMs>>, <<cuba.idp.cookieMaxAgeSec,cuba.idp.cookieMaxAgeSec>>, <<cuba.idp.cookieHttpOnly,cuba.idp.cookieHttpOnly>>.

* На Service Providers:

** Установите свойства приложения:

*** <<cuba.webAppUrl,cuba.webAppUrl>> - URL приложения (символ `/` в конце обязателен). Данный URL должен быть в списке URL, определенном свойством IDP <<cuba.idp.serviceProviderUrls,cuba.idp.serviceProviderUrls>>. Например:
+
[source]
----
cuba.webAppUrl = http://fish:8081/app/
----

*** <<cuba.web.idp.enabled,cuba.web.idp.enabled>> должно быть установлено в `true`.

*** <<cuba.web.idp.baseUrl,cuba.web.idp.baseUrl>> - на данном URL IDP принимает запросы на аутентификацию. Стандартный CUBA IDP использует адрес `idp/` (символ `/` в конце обязателен). Например:
+
[source]
----
cuba.web.idp.baseUrl = http://main:8080/app/idp/
----

*** <<cuba.web.idp.trustedServicePassword,cuba.web.idp.trustedServicePassword>> - должен быть таким же как заданный для IDP в свойстве <<cuba.idp.trustedServicePassword,cuba.idp.trustedServicePassword>>.

include::sso/sso_customization.adoc[]

include::sso/sso_example.adoc[]

