:sourcesdir: ../../../../../../source

[[messageTools]]
====== MessageTools

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/global/MessageTools.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`MessageTools` interface is a <<managed_beans,managed bean>> containing additional methods for working with <<localization,localized messages>>. You can access `MessageTools` interface either using `Messages.getTools()` method, or as any other bean – by means of injection or through `AppBeans` class.

`MessageTools` methods:

[[messageTools.loadString]]
* `loadString()` – returns a localized message, specified by reference in `msg://{messagePack}/{key}` format
+
Reference components:
+
--
** `msg://` – mandatory prefix.

** `{messagePack}` – optional name of the message pack. If it is not specified, it is assumed that the pack name is passed to `loadString()` as a separate parameter.

** `{key}` – message key in the pack.
--
+
Examples of the message references:
+
[source, properties]
----
msg://someMessage
msg://com.abc.sales.web.customer/someMessage
----

* `getEntityCaption()` – returns the localized entity name.

* `getPropertyCaption()` – returns the localized name of an entity attribute.

* `hasPropertyCaption()` – checks whether the entity attribute was given a localized name.

* `getLocValue()` – returns the localized value of the entity attribute based on <<localizedValue_annotation,@LocalizedValue>> annotation.

* `getMessageRef()` – forms a <<messageTools.loadString,message reference>> for <<metaProperty,meta-property>> which can be used to retrieve the localized name of the entity attribute.

* `getDefaultLocale()` – returns default application locale, which is the first one listed in <<cuba.availableLocales,cuba.availableLocales>> application property.

* `useLocaleLanguageOnly()` – returns `true`, if for all locales supported by the application (defined in `cuba.availableLocales` property) only the language parameter is specified, without country and variant. This method is used by platform mechanisms which need to find the most appropriate supported locale when locale info is received from the external sources such as operation system or HTTP request.

* `trimLocale()` – deletes from the passed locale everything except language, if `useLocaleLanguageOnly()` method returns `true`.

You can <<bean_extension,override>> `MessageTools` to extend the set of its methods in your application. Below are the examples of working with the extended interface:

[source, java]
----
include::{sourcesdir}/common/messagetools_1.java[]
----

[source, java]
----
include::{sourcesdir}/common/messagetools_2.java[]
----

