[[preface]]
== Preface

This manual provides the reference information for the CUBA platform and covers the most important topics of developing business applications with it.

Knowledge of the following technologies is required to use the platform:

* Java Standard Edition

* Relational databases (SQL, DDL)

Additionally, knowledge of the following technologies and frameworks will be helpful to get a deeper understanding of the platform:

* link:https://docs.gradle.org/{gradleVersion}/userguide/userguide.html[Gradle] build system

* link:$$http://projects.spring.io/spring-framework$$[Spring Framework]

* link:$$https://en.wikipedia.org/wiki/Java_Persistence_API$$[Java Persistence API]

* link:$$https://vaadin.com/book$$[Vaadin] web applications framework

* HTML / CSS / JavaScript

* Java Servlets

This manual and other documentation related to the CUBA platform can be found at link:https://www.cuba-platform.com/manual[www.cuba-platform.com/manual]. Video materials and presentations that can help you to understand the platform are available at link:https://www.cuba-platform.com/tutorials[www.cuba-platform.com/tutorials]. You can also check out online demo applications at link:https://www.cuba-platform.com/online-demo[www.cuba-platform.com/online-demo].

If you have any suggestions for improving this manual, feel free to report issues in the source repository on https://github.com/cuba-platform/documentation[GitHub]. If you see a spelling or wording mistake, a bug or inconsistency, don't hesitate to fork the repo and fix it. Thank you!

:sectnums:

