:sourcesdir: ../../../../../../source

[[gui_data_comp_sort]]
====== Custom Sorting

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

Sorting of UI tables by entity attributes is performed by `CollectionContainerSorter` which is set for a <<gui_collection_container,CollectionContainer>>. The standard implementation sorts data in memory if it fits in one page of loaded data, otherwise it sends a new request to the database with the appropriate "order by" clause. The "order by" clause is created by the `JpqlSortExpressionProvider` bean on the middle tier.

Some entity attributes may require a special implementation of sorting. Below we explain how to customize sorting on a simple example: suppose there is a `Foo` entity with a `number` attribute of type `String`, but we know that the attribute actually stores only numeric values. So we want the sort order to be `1, 2, 3, 10, 11`. With the default behavior, the order would be `1, 10, 11, 2, 3`.

First, create a subclass of the `CollectionContainerSorter` class in the `web` module for sorting in memory:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_1.java[]
----

If you need the customized sorting just in a few screens, you can instantiate `CustomCollectionContainerSorter` right in the screen:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_2.java[]
----

If your sorter defines some global behavior, create your own factory which instantiates sorters system-wide:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_3.java[]
----

Register the factory in `web-spring.xml` to override the default factory:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_4.xml[]
----

Now create own implementation of `JpqlSortExpressionProvider` in the `core` module for sorting at the database level:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_5.java[]
----

Register the expression provider in `spring.xml` to override the default one:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_6.xml[]
----
