:sourcesdir: ../../../../../../source

[[gui_data_comp_prog]]
====== Programmatic Creation of Data Components

Data components can be created and used in visual components programmatically.

In the example below, we create an editor screen with the same data and visual components as defined in the <<gui_data_comp_decl,previous section>> using only Java code without any XML descriptor.

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_3.java[]
----

<1> `DataComponents` is a factory to create data components.
<2> `DataContext` instance is registered in the screen for standard commit action to work properly.
<3> `orderDl` loader will load data to `orderDc` container.
<4> `orderDl` loader will merge loaded entities into data context for change tracking.
<5> `linesDc` is created as a property container.
<6> A query is specified for the `customersDl` loader.
<7> `ContainerValueSource` is used to bind single fields to containers.
<8> `ContainerOptions` is used to provide options to lookup fields.
<9> `ContainerTableItems` is used to bind tables to containers.
<10> `getEditedEntityContainer()` is overridden to specify the container instead of `@EditedEntityContainer` annotation.
<11> Load data before showing the screen. The edited entity id will be set to `orderDl` by the framework automatically.
