:sourcesdir: ../../../../../../source

[[gui_data_comp_decl]]
====== Declarative Creation of Data Components

The simplest way to create data components for a screen is to define them in the screen XML descriptor in the `<data>` element.

Let's consider the data model consisting of `Customer`, `Order` and `OrderLine` entities. The edit screen for the `Order` entity can have the following XML definition:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_1.xml[]
----

In this case, the following data components are created:

<1> - `DataContext` instance.
<2> - `InstanceContainer` the `Order` entity.
<3> - Inline <<views,view>> of the entity instance located in the container. Inline views can extend shared (defined in `views.xml`) ones.
<4> - `InstanceLoader` which loads the `Order` instance.
<5> - `CollectionPropertyContainer` for the nested `OrderLines` entity. It is bound to the `Order.lines` collection attribute.
<6> - `CollectionContainer` for the `Customer` entity. The `view` attribute can point to a shared view.
<7> - `CollectionLoader` which loads `Customer` entity instances using the specified query.

The data containers can be used in visual components as follows:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_2.xml[]
----

<1> Standalone fields have `dataContainer` and `property` attributes.
<2> `form` propagates `dataContainer` to its fields so they need only `property` attribute.
<3> Lookup fields have `optionsContainer` attribute.
<4> Tables have only `dataContainer` attribute.
