:sourcesdir: ../../../../../../source

[[gui_data_comp_param]]
====== Using Screen Parameters in Loaders

It is often required to load data in a screen depending on parameters passed to that screen. Below is an example of a browse screen which accepts a parameter and uses it to filter the loaded data.

Suppose we have two entities: `Country` and `City`. The `City` entity has `country` attribute which is a reference to `Country`. The cities browser accepts a country instance and shows cities only of this country.

First, consider the cities screen XML descriptor. It's loader contains a query with a parameter:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_param_1.xml[]
----

The cities screen controller contains a public setter for the parameter and uses the parameter in <<screen_BeforeShowEvent,BeforeShowEvent>> handler. Notice that the screen has no `@LoadDataBeforeShow` annotation, because loading is triggered explicitly:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_param_1.java[]
----

The cities screen can be opened from another screen passing a country as follows:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_param_2.java[]
----
