:sourcesdir: ../../../source

[[health_check_url]]
=== Health check URL

Каждый блок приложения, развернутый как веб-приложение, предоставляет URL для проверки своего состояния. HTTP GET запрос на этот URL возвращает `ok` если блок готов к работе.

Пути URL для различных блоков перечислены ниже:

* Middleware: `/remoting/health`
* Web Client: `/dispatch/health`
* Web Portal: `/rest/health` (требует подключения {rest_man_url}[аддона REST API])

То есть для приложения с именем `app`, развернутого на `++localhost:8080++`, адреса будут следующими:

* `\http://localhost:8080/app-core/remoting/health`
* `\http://localhost:8080/app/dispatch/health`
* `\http://localhost:8080/app-portal/rest/health`

Ответ `ok` можно заменить на произвольный текст с помощью свойства приложения <<cuba.healthCheckResponse,cuba.healthCheckResponse>>.

Контроллеры проверки посылают <<events,события>> типа `HealthCheckEvent`. Следовательно, вы можете добавить собственную логику проверки работоспособности приложения. В https://github.com/cuba-platform/sample-base/blob/master/modules/web/src/com/haulmont/addon/samplebase/web/HealthCheckListener.java[примере на GitHub], бин web-уровня реагирует на события проверки и вызывает сервис среднего слоя, который в свою очередь выполняет операцию на базе данных.

