:sourcesdir: ../../../../source

[[rest_api_v2_ex_get_entities_list]]
==== Getting an Entity Instances List

Let's suppose that the system has a `sales$Order` entity and we need to get a list of this entity instances. Besides, we need to get not all the records, but only 50 records, starting with the 100th one. A response must contain not only simple properties of the `sales$Order` entity but also an information about the order customer (a reference field named `customer`). Orders must be sorted by date.

A base URL for getting all instances of the `sales$Order` entity is as follows:

`\http://localhost:8080/app/rest/v2/entities/sales$Order`

To implement all the conditions described above the following request parameters must be specified:

* *view* - a <<views, view>>, that will be used for loading entities. In our case the `order-edit-view` contains a `customer` reference.
* *limit* - a number of instances to be returned.
* *offset* - a position of the first extracted record.
* *sort* - an entity attribute name that will be used for sorting.

An OAuth token must be put in the `Authorization` header with the `Bearer` type:

  Authorization: Bearer 29bc6b45-83cd-4050-8c7a-2a8a60adf251

As a result, we get the following *GET* request URL:

`\http://localhost:8080/app/rest/v2/entities/sales$Order?view=order-edit-view&limit=50&offset=100&sort=date`

The response will be like this:

[source, json]
----
include::{sourcesdir}/rest/rest-orders-list-response.json[]
----

Please note, that every entity in the response has a `_entityName` attribute with the entity name and an `_instanceName` attribute with the entity <<namePattern_annotation, instance name>>.

