:sourcesdir: ../../../../../../source

[[url_routes_registration]]
====== Routes registration

There are two ways to register a route:

* use the `@Route` annotation – used for <<gui_screens,new screens>>;
* register it in the <<screens.xml,screens.xml>> file for <<screens,legacy screens>>.

`@Route` annotation is used to register routes for <<gui_screens,new screen>> controllers (inheritors of the `Screen` class). It has two parameters:

* `path` (`value`) – route itself;
* `parentPrefix` is used for <<url_routes_squashing,routes squashing>>.

[[source_new_screen_registration]]
.New Screen Route Registration
[source, java]
----
include::{sourcesdir}/gui/url_new_screen_registration.java[]
----

Routes for <<screens,legacy screens>> should be registered in the <<screens.xml,screens.xml>>. Attributes `route` and `routeParentPrefix` are intended for this purpose.

[[source_legacy_screen_registration]]
.Legacy Screen Route Registration
[source, xml]
----
include::{sourcesdir}/gui/url_legacy_screen_registration.xml[]
----
[[url_routes_squashing]]
Routes squashing::
+
--
Let’s assume that there are browser and editor screens for the `Order` entity:

[[source_browse_entity_squashing1]]
.Browser & Editor Routes (URL Squashing)
[source, java]
----
include::{sourcesdir}/gui/url_routes_squashing1.java[]
----
To avoid `"orders"` subroute repeating when these screens are opened right after each other URL squashing can be used. This subroute should be defined in the `parentPrefix` parameter (or in the `routeParentPrefix` attribute for legacy screens) for the order editor screen:

[[source_browse_entity_squashing2]]
.Browser & Editor Routes (URL Squashing)
[source, java]
----
include::{sourcesdir}/gui/url_routes_squashing2.java[]
----
Now when the editor is opened in the same tab as the browser, a resulting address will be like: `app/#main/0/orders/edit?id=...`

It allows to specify clear routes for each screen and avoid repeats in URL.
--