:sourcesdir: ../../../../../../source

[[url_navigation_filter]]
====== NavigationFilter

There is a mechanism that enables to prevent history or general navigation due to custom logic – `NavigationFilter`.

Any navigation filter is a <<managed_beans,managed bean>> that implements `NavigationFilter` interface. `@Order` annotation can be used to configure an order of all navigation filters invocation. The `NavigationFilter.HIGHEST_PLATFORM_PRECEDENCE` and `NavigationFilter.LOWEST_PLATFORM_PRECEDENCE` constants define the range which is used by access filters defined in the platform.

`NavigationFilter` interface has the only one method `allowed()` that accepts two arguments: current navigation state `fromState` and requested navigation state `toState`. The method returns `AccessCheckResult` instance and checks whether the transition from the current navigation state to the requested navigation state is allowed or not.

`CubaLoginScreenFilter` is an example of such filters. It is intended for checking whether the current session is authenticated to prevent navigation to the login screen when the user is logged in:

[[source_url_navigation]]
.CubaLoginScreenFilter (NavigationFilter Example)
[source, java]
----
include::{sourcesdir}/gui/url_navigation_filter.java[]
----