:sourcesdir: ../../../source

[[create_project]]
=== Creating a New Project

CUBA Studio provides an easy way to create new CUBA projects from scratch. Just use the *New Project* wizard and follow the steps below:

. In the *Welcome to CUBA Studio* window, click *Create New Project*.

. Select *CUBA Project*.

. In the *Project SDK* field, select a JDK corresponding to `JAVA_HOME` which is set in your environment. If you see the `<No SDK>` value, click *New* and select the folder where the JDK is installed, for example `++C:\Java\jdk8u202-b08++` on Windows or `/Library/Java/JavaVirtualMachines/jdk8u202-b08/Contents/Home` on macOS.

. Accept the default repositories configuration, or {main_man_url}/access_to_repo.html[customize] it for the project, and click *Next*.

. Specify the name of the new project in the *Project name* field. The name should contain only Latin letters, numbers and underscores. Think carefully on the project name at this stage, as changing it later on will require complex manual intervention.

. The following fields below will be automatically populated:
+
--
* *Project location* – the path to the new project directory. You can select another directory by typing it in the field or clicking the ellipsis button next to the field.

* *Project namespace* – the namespace which will be used as a prefix for entity names and database tables. The namespace can consist of Latin letters only and should be as short as possible.

* *Root package* − the root (or base) package of Java classes. It can be adjusted later, but the classes generated at project creation will not be moved.

* *Platform version* – the platform version used in the project. If you don't have any specific requirements, use the latest released version, i.e. without `BETA` or `SNAPSHOT` suffixes. The platform artifacts will be automatically downloaded from the repository on project import.
--

. Click *Finish*. The empty project will be created in the specified directory, and Studio will start building the project information from Gradle files and indexing the project.

. When the project synchronization and indexing process is completed, you will see the CUBA project tree in the *Project* tool window.

. Open the *Gradle* tool window which is docked on the right side by default. Click the "wrench" icon (*Gradle Settings*) and select `Use JAVA_HOME` in the *Gradle JVM* field. If you don't see such item in the drop-down list, make sure you have set up your development environment correctly as described in the {main_man_url}/setup.html[Setup] section of the CUBA Developer's Manual. Click *OK*.

. Now you can start working with the project.