:sourcesdir: ../../../source

[[create_project]]
=== Creating a New Project

CUBA Studio provides an easy way to create new CUBA projects from scratch. Just use the *New Project* wizard and follow the steps below:

. In the *Welcome to CUBA Studio* window, click *Create New Project*.

. Select *CUBA Project*.

. Accept the default repositories configuration, or https://doc.cuba-platform.com/manual-latest/access_to_repo.html[customize] it for the project, and click *Next*.

. Specify the name of the new project in the *Project name* field. The name should contain only Latin letters, numbers and underscores. Think carefully on the project name at this stage, as changing it later on will require complex manual intervention.

. The following fields below will be automatically populated:
+
--
* *Project location* – the path to the new project directory. You can select another directory by typing it in the field or clicking the *...* button next to the field.

* *Project namespace* – the namespace which will be used as a prefix for entity names and database tables. The namespace can consist of Latin letters only and should be as short as possible.

* *Root package* − the root (or base) package of Java classes. It can be adjusted later, but the classes generated at project creation will not be moved.

* *Platform version* – the platform version used in the project. The platform artifacts will be automatically downloaded from the repository on project build.
--

. Click *Finish*. The empty project will be created in the specified directory, and Studio will start building the project information from Gradle files and indexing the project.

. When the project synchronization and indexing process is completed, you will see the CUBA perspective in the *Project* tool window. Now you can start working with the project.