:sourcesdir: ../../../source

[[open_project]]
=== Opening an Existing Project

Opening an imported project::
+
--
If the project has already been opened by CUBA Studio on this computer, do the following:

* Use recent projects list or click *Open*, select the _project's folder_ in the file system dialog and click *Open* button.

* Wait for Gradle synchronization and project indexing process to complete. As soon as the CUBA perspective appears in the *Project* tool window, you can start working with the project.
--

Opening a project for the first time::
+
--
If the project has not been opened by CUBA Studio on this computer, for example, just checked out from VCS, do the following:

* Click *Open* and select the project's `build.gradle` file in the file system dialog, then click *Open* button.

* Select *Open as Project* in the *Open Project* dialog.

* In the *Import Project from Gradle* dialog:
** Select *Use auto-import* checkbox.
** Select `Use JAVA_HOME` in *Gradle JVM* field. If you don't see such item in the drop-down list, make sure you have set up your development environment correctly as described in the {main_man_url}/setup.html[Setup] section of the CUBA Developer's Manual.
** Select `.idea (directory based)` in the *Project format* field.
** Click *OK*.

* Wait for Gradle synchronization and project indexing process to complete. As soon as the CUBA perspective appears in the *Project* tool window, you can start working with the project.
--

Opening a project based on CUBA 6.10 for the first time::
+
--
CUBA Studio supports projects based on CUBA 6.10+ and 7.0. You can open your existing projects created in a previous version of Studio and import them into the new Studio as follows:

. Remove old IntelliJ project files using the `gradlew cleanIdea` task in the command line.

. If the project is under Git version control, add `.idea` line to the `.gitignore` file located in the project root. It will ensure your local IDE settings will not be shared between all developers of the project.

. Open `build.gradle` file as described in the *Opening a project for the first time* section above.
--