:sourcesdir: ../../../source

[[open_project]]
=== Opening an Existing Project

Opening an imported project::
+
--
If the project has already been opened by CUBA Studio on this computer, do the following:

. Use recent projects list; or click *Open*, select the _project's folder_ in the file system dialog and click *Open* button.

. Wait for Gradle synchronization and project indexing process to complete. As soon as the CUBA project tree appears in the *Project* tool window, you can start working with the project.
--

Opening a project for the first time::
+
--
If the project has not been opened by CUBA Studio on this computer, for example, just checked out from VCS, do the following:

. In the welcome window, click *Import Project*. If another project is already opened, click *File > New > Project from Existing Sources* in the main menu.

. In the file system dialog, select the project's root folder containing the `build.gradle` file, then click *Open* button.

. In the *Import Project* window, select *Import project from external model* radio-button and choose *CUBA* in the list below. Then click *Next*.

. Click *Finish* on the next page of the import wizard.

. Wait for Gradle synchronization and project indexing process to complete. The CUBA project tree should appear in the *Project* tool window.

. Click *File > Project Structure* in the main menu.
* Make sure that the *Project SDK* field has a value corresponding to `JAVA_HOME` which is set in your environment. If you see the `<No SDK>` value, click *New* and select the folder where the JDK is installed, for example `++C:\Java\jdk8u202-b08++` on Windows or `/Library/Java/JavaVirtualMachines/jdk8u202-b08/Contents/Home` on macOS.
* Make sure that the *Project language level* field has a value corresponding to the JDK version. For example, if the JDK is `1.8`, the language level must be `8 - Lambdas, type annotations, etc.`
--

Opening a project based on CUBA 6.10 for the first time::
+
--
CUBA Studio supports projects based on CUBA 6.10+ and 7.0. You can open your existing projects created in a previous version of Studio and import them into the new Studio.

Keep in mind that CUBA 6.10 supports only Java 8, so your `JAVA_HOME` environment variable must point to the JDK 8 installation. Later after migrating to CUBA 7, you will be able to use a newer JDK if needed.

Follow the steps below to open an existing project based on CUBA 6.10 for the first time:

. If your project uses premium add-ons (Reports, BPM, etc.) and you have a subscription, you should set the premium repository access credentials in `~/.gradle/gradle.properties` as described in the {main_man_url}/access_to_repo.html#access_to_premium_repo[documentation].

. Remove old IntelliJ project files using the `gradlew cleanIdea` task in the command line.

. If the project is under Git version control, add `.idea` line to the `.gitignore` file located in the project root. It will ensure your local IDE settings will not be shared between all developers of the project.

. Import the project as described in the *Opening a project for the first time* section above.
--