:sourcesdir: ../../../source

[[upgrade_project]]
=== Upgrading a Project

This section covers the process of upgrading a project to a newer CUBA version.

[TIP]
====
It is recommended to put the project under version control and commit all pending changes before upgrade. It will allow you to see what changes are performed and quickly roll back to a previous version if the upgrade fails for some reason.
====

* Open the project as described in the <<open_project,previous section>>.

* Click *CUBA > Project Properties* in the main menu or double-click *Project > Properties* in the CUBA project tree.

* In the *CUBA Project Properties* dialog, select the desired CUBA version in the *Platform version* field.
+
[WARNING]
====
SNAPSHOT versions are available if you use the `repo.cuba-platform.com` repository. They are strongly not recommended for use in production.
====

* Click *OK*, then confirm.

* If you are upgrading to a newer feature release (for example, from 6.10.X to 7.0.X or from 7.0.Y to 7.1.Y), the *Migration Required* dialog appears. This dialog contains information about migration steps which will be performed automatically by Studio. Review the information and click *Migrate*.

* Studio performs automatic migration (if needed) and runs Gradle `clean` and `undeploy` tasks.

* If you are upgrading to a feature release, review _Breaking Changes_ section in {rel_notes_url}[Release Notes] and make changes in your project accordingly.

* Try to assemble your project by executing *CUBA > Build Tasks > Assemble*. Watch the output and fix your code if it doesn't compile.

* Execute *CUBA > Update Database* to incorporate possible framework schema changes into your project's database.