:sourcesdir: ../../../source

[[search]]
=== Searching

Search is performed according to the following rules: 

* If the search term is included in quotation marks, the system searches for the corresponding *phrase* – the same set of words in the same order ignoring the punctuation.
* If the search term begins with "++*++", the system searches for the term as a substring *in any part of a word* in indexed data.
* Otherwise search is performed by matching the search term with the *beginnings of the words* in indexed data.

For Russian and English languages search accounts for word forms.

Search algorithm contains two stages:

* First, the search term is looked for in the `all` field of Lucene documents. All found entities are added to the results list.
* If the first stage produces results, the identifiers of found entities are then searched in the `links` field of Lucene documents. All entities found at the second stage are also added to the list of search results.

[WARNING]
====
If the search string contains several words (not enclosed in quotation marks) the system will search each word separately using OR condition. I.e. search results will include the entities containing at least one of the entered words.
====

