:sourcesdir: ../../../source

[[ide_integration]]
=== IDE Integration

Take the following steps to integrate Studio with *IntelliJ IDEA* or *Eclipse*:

. Open or <<qs_create_project,create a new>> project in Studio.

. Switch to *Project properties* section and click *Edit*. Select the required *Java IDE* by checking *IntelliJ IDEA* or *Eclipse*.

. Select *Build* > *Create or update <IDE> project files* in the Studio menu. The corresponding files will be created in the project directory.

. For IntelliJ IDEA integration:

.. Run IntelliJ IDEA 13+ and install *CUBA Framework Integration* plugin, from the plugin repository: *File > Settings > Plugins > Browse Repositories*.

. For Eclipse integration:

.. Run Eclipse 4.3+, open *Help > Install New Software*, add `++http://files.cuba-platform.com/eclipse-update-site++` repository and install the *CUBA Plugin*.

.. In the *CUBA* section of the *Window > Preferences* menu, check *Studio Integration Enabled*, and click *OK*.

Please note that *IDE: on port 48561* label has appeared in the bottom left corner of Studio. Now the corresponding source code files will be opened in IDE when you click *IDE* buttons in the Studio.

[TIP]
====
If you are using https://www.cuba-platform.com/marketplace/cuba-cli[CUBA CLI], switch to the project folder in a terminal and run the command `gradlew idea` to create the project files for IntelliJ IDEA integration.
====