:sourcesdir: ../../../source

[[project_creation]]
=== Creating a Project

The recommended way to create a new project is to use CUBA Studio. An example can be found in the <<qs_create_project,Quick Start>> chapter of this manual.

Another option is to use https://www.cuba-platform.com/marketplace/cuba-cli[CUBA CLI]:

. Open a terminal and start CUBA CLI.

. Input the command `create-app`. You can use tab auto-completion.

. CLI will ask you for the project configuration. Click ENTER to accept the defaults or select another options:
+
--
* *Project name* – the project name. For sample projects CLI generates random names that can be selected by default.
* *Project namespace* – the namespace which will be used as a prefix for entity names and database tables. The namespace can consist of Latin letters only and should be as short as possible.
* *Platform version* – the platform version used in the project. The platform artifacts will be automatically downloaded from the repository on project build.
* *Root package* – the root package of Java classes.
* *Database* – the SQL database to use.
--

After that, the empty project will be created in a new folder in the current directory. You can keep developing it in Studio or using CLI and any IDE.