:sourcesdir: ../../../source

[[spring_profiles]]
=== Using Spring Profiles

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

Spring profiles allow you to customize the application for working in different environments. Depending on an active profile, you can instantiate different implementations of the same bean and assign different values of application properties.

If a Spring bean has `@Profile` annotation, it will be instantiated only when the annotation value matches some active profile. In the following example, `SomeDevServiceBean` will be used when `dev` profile is active, and `SomeProdServiceBean` will be used when the `prod` profile is active:

[source,java]
----
include::{sourcesdir}/development/spring_profile_1.java[]
----

In order to define some profile-specific application properties, create a `<profile>-app.properties` file in the same package as the base `app.properties` file, for example:

[source]
----
com/company/demo/app.properties
com/company/demo/prod-app.properties
----

The profile-specific file will be loaded right after the base file, so the profile-specific properties will override the properties defined in the base file. In the following example, we define connection to a specific database for the `prod` profile:

.prod-app.properties
[source,properties]
----
include::{sourcesdir}/development/spring_profile_2.properties[]
----

The list of active profiles can be set for the application in either of two ways:

* In `spring.profiles.active` servlet context parameter in the `web.xml` file, for example:
+
[source,xml]
----
include::{sourcesdir}/development/spring_profile_3.xml[]
----

* In `spring.profiles.active` Java system property. For example, when running <<uberjar_deployment,Uber JAR>>:
+
[source]
----
java -Dspring.profiles.active=prod -jar app.jar
----