:sourcesdir: ../../../source

[[testing]]
=== Testing

CUBA applications can be tested using well-known approaches: unit, integration and UI testing.

Unit tests are well suited for testing business logic encapsulated in specific classes and loosely coupled with the application infrastructure. You can just create the `test` directory in the `global`, `core` or `web` module of your project and start writing JUnit tests. If you need mocks, add a dependency on your favorite mocking framework or link:http://jmockit.github.io/[JMockit] which is already used by CUBA. The mocking framework dependency must be added to the `build.gradle` file before JUnit:

[source, groovy]
----
include::{sourcesdir}/development/testing_jmockit_dep.groovy[]
----

Integration tests run in the Spring container, so they are able to test most aspects of your application, including interaction with the database and UI screens. This section describes how to create integration tests on the middleware and web tiers.

For UI tests, we recommend using the https://github.com/cuba-platform/masquerade[Masquerade] library which provides a set of useful abstractions for testing CUBA applications. See README and Wiki sections on GitHub.

include::testing/integration_tests_mw.adoc[]

include::testing/integration_tests_client.adoc[]
