:sourcesdir: ../../../../source

[[integration_tests_mw]]
==== Middleware Integration Tests

Middleware integration tests run in a fully functional Spring container connected to the database. In such tests, you can run code on all layers of the middleware, from services down to ORM.

Right after creating a new project in Studio, you can find two classes in the base package of the `core` module: a test container class and a sample test. The test container class launches the middleware Spring container which is set up for tests. The sample test makes use of it and demonstrates how to test some operations with an entity.

Let's consider the generated test container class and how it should be adapted to your needs.

The class must extend `TestContainer` provided by CUBA. In the constructor, you should add <<app_components_recipes,application components>> (add-ons) used in your project to the `appComponents` list. Also, you can specify additional application properties files in the `appPropertiesFiles` list.

The `initDbProperties()` method performs initialization of the database connection properties. In the generated test container, it tries to find the <<db_connection,connection properties>> regardless of whether they are defined in application properties or in <<context.xml,context.xml>>. If you keep the method implementation as is, your tests will work against your main data store even if you change its type or how the JDBC DataSource is defined.

There is a disadvantage of using the same database for tests and for the application: the data entered manually may interfere with test data and break test execution. To avoid this, you can set up a separate database and use it only for tests. We recommend using a test database of the same type as your main database in order to use the same set of <<db_scripts,database migration scripts>>. Below is an example of setting up a test database on local PostgreSQL.

First, implement the `initDbProperties()` method as follows:

[source, java]
----
public class DemoTestContainer extends TestContainer {
    // ...
    private void initDbProperties() {
        dbDriver = "org.postgresql.Driver";
        dbUrl = "jdbc:postgresql://localhost/demo_test";
        dbUser = "cuba";
        dbPassword = "cuba";
    }
----

Then add the <<build.gradle_createDb, test database creation task>> to `build.gradle`:

[source, groovy]
----
include::{sourcesdir}/development/testing_4.groovy[]
----

Before running tests, create the test database by executing the task:

[source]
----
./gradlew createTestDb
----

The test container should be used in test classes as a JUnit 5 extension specified by the `@RegisterExtension` annotation:

[source, java]
----
include::{sourcesdir}/development/testing_5.java[]
----

Useful container methods::
+
--
The `TestContainer` class has the following methods that can be used in the test code (see the `CustomerTest` example above):

* `persistence()` – returns the reference to the <<persistence,Persistence>> interface.

* `metadata()` – returns the reference to the <<metadata,Metadata>> interface.

* `deleteRecord()` – this set of overloaded methods is aimed to be used in `@After` methods to clean up the database after tests.
--

Logging::
+
--
The test container sets up logging according to the `test-logback.xml` file provided by the platform.

If you want to configure logging levels for your tests, do the following:

* Create `my-test-logback.xml` file in the `test` folder of your project's `core` module.

* Configure appenders and loggers in `my-test-logback.xml`. You can take the default content from the `test-logback.xml` file located inside the `cuba-core-tests` artifact.

* Add a static initializer to your test container to specify the location of your logback configuration file in the `logback.configurationFile` system property:
+
[source, java]
----
include::{sourcesdir}/development/testing_9.java[]
----
--

[[integration_tests_mw_data_store]]
Additional Data Stores::
+
--
If your project uses <<data_store,additional data stores>>, you should create corresponding JDBC data sources in your test container. For example, if you have `mydb` datastore which is a PostgreSQL database, add the following method to the test container class:

[source, java]
----
include::{sourcesdir}/development/testing_10.java[]
----

Also, if the additional database type is different from the main one, you should add its driver as the `testRuntime` dependency to the `core` module in `build.gradle`, for example:

[source, java]
----
include::{sourcesdir}/development/testing_12.groovy[]
----
--

