:sourcesdir: ../../../../../source

[[db_scripts_groovy]]
===== Структура Groovy-скриптов

Groovy-скрипты обновления имеют следующую структуру:

* _Основная_ часть, содержащая код, выполняемый до старта <<appContext,контекста приложения>>. В этой части можно использовать любые классы Java, Groovy и блока Middleware приложения, но при этом необходимо иметь в виду, что никакие бины, интерфейсы инфраструктуры и прочие объекты приложения еще не инстанциированы, и с ними работать нельзя.
+
Основная часть предназначена в первую очередь, как и обычные SQL-скрипты, для обновления схемы данных.

* _PostUpdate_ часть - набор замыканий, которые будут выполнены после завершения процесса обновления и после старта контекста приложения. Внутри этих замыканий можно оперировать любыми объектами *Middleware* приложения.
+
В этой части скрипта удобно, например, выполнять импорт данных, так как в ней можно использовать интерфейс <<persistence,Persistence>> и объекты модели данных.

На вход Groovy-скриптов механизм выполнения передает следующие переменные:

* `ds` - экземпляр `javax.sql.DataSource` для базы данных приложения.

* `log` - экземпляр `org.apache.commons.logging.Log` для вывода сообщений в журнал сервера

* `postUpdate` - объект, содержащий метод `add(Closure closure)` для добавления замыканий, выполняющихся после старта контекста сервера.

[WARNING]
====
Groovy-скрипты выполняются только <<db_update_server,механизмом запуска скриптов БД сервером>>.
====

Пример Groovy-скрипта обновления:

[source, java]
----
include::{sourcesdir}/dbms/groovyupdate_1.groovy[]
----

