:sourcesdir: ../../../../../source

[[gui_api]]
===== API компонентов

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/Component.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Доступно для всех визуальных компонентов::
+
--
[[gui_api_unwrap]]
* `unwrap()` - возвращает экземпляр компонента для текущего типа клиента (компонент Vaadin или Swing). Можно использовать в клиентском модуле для доступа к API базового компонента, см. раздел <<webComponentsHelper>>.
+
[source, java]
----
com.vaadin.ui.TextField vTextField = textField.unwrap(com.vaadin.ui.TextField.class);
----

* `unwrapComposition()` - возвращает экземпляр самого внешнего контейнера для текущего типа клиента. Можно использовать в клиентском модуле для доступа к API базового компонента.
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/Buffered.html[Buffered]::
+
--
[[gui_api_commit]]
* `commit()` - обновляет источник данных, сохраняя все изменения, внесённые после последнего коммита.

[[gui_api_discard]]
* `discard()` - отменяет все изменения, внесённые после последнего коммита. Значение компонента обновляется из источника данных.

[[gui_api_isModified]]
* `isModified()` - возвращает `true`, если значение компонента изменилось с момента последнего обновления из источника данных.

[source, java]
----
if (textArea.isModified()) {
    textArea.commit();
}
----

Доступно для компонентов:

<<gui_CheckBox,CheckBox>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/Collapsable.html[Collapsable]::
+
--
[[gui_api_expanded]]
* `addExpandedStateChangeListener()` - добавляет слушатель, реализующий интерфейс `ExpandedStateChangeListener`, для отслеживания событий сворачивания/разворачивания компонента.
+
[source, java]
----
@Subscribe("groupBox")
protected void onGroupBoxExpandedStateChange(Collapsable.ExpandedStateChangeEvent event) {
    notifications.create()
            .withCaption("Expanded: " + groupBox.isExpanded())
            .show();
}
----

Доступно для компонентов:

<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/ComponentContainer.html[ComponentContainer]::
+
--
[[gui_api_add]]
* `add()` - добавляет дочерний компонент в контейнер.

[[gui_api_remove]]
* `remove()` - удаляет дочерний компонент из контейнера.

[[gui_api_removeAll]]
* `removeAll()` - удаляет все дочерние компоненты из контейнера.

[[gui_api_getOwnComponent]]
* `getOwnComponent()` - возвращает компонент, вложенный непосредственно в этот контейнер.

[[gui_api_getComponent]]
* `getComponent()` - возвращает компонент, находящийся где-либо внутри дерева компонентов в этом контейнере.

[[gui_api_getComponentNN]]
* `getComponentNN()` - возвращает компонент, находящийся где-либо внутри дерева компонентов в этом контейнере, и выбрасывает исключение, если компонент не найден.

[[gui_api_getOwnComponents]]
* `getOwnComponents()` - возвращает список всех компонентов, вложенных непосредственно в этот контейнер.

[[gui_api_getComponents]]
* `getComponents()` - возвращает список всех компонентов, находящихся где-либо внутри дерева компонентов в этом контейнере.

Доступно для компонентов:

<<gui_Accordion,Accordion>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_FieldGroup,FieldGroup>> -
<<gui_Form,Form>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_HtmlBoxLayout,HtmlBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_TabSheet,TabSheet>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/OrderedContainer.html[OrderedContainer]::
+
--
[[gui_api_indexOf]]
* `indexOf()` - возвращает индекс компонента внутри упорядоченного контейнера.

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_Frame,Frame>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasContextHelp.html[HasContextHelp]::
+
--
[[gui_api_contextHelp]]
* `setContextHelpText()` - задаёт текст контекстной подсказки для компонента, см. атрибут <<gui_attr_contextHelpText,contextHelpText>>.

* `setContextHelpTextHtmlEnabled()` - указывает, может ли текст контекстной подсказки быть обработан как HTML, см.атрибут <<gui_attr_contextHelpTextHtmlEnabled,contextHelpTextHtmlEnabled>>.

* `setContextHelpIconClickHandler()` - добавляет слушатель кликов по значку контекстной подсказки. Слушатель имеет приоритет над <<gui_attr_contextHelpText,текстом подсказки>>, таким образом, контекстная подсказка с текстом не будет отображаться, если также установлен слушатель кликов по значку подсказки.

[source, java]
----
textArea.setContextHelpIconClickHandler(contextHelpIconClickEvent ->
        dialogs.createMessageDialog()
                .withCaption("Title")
                .withMessage("Message body")
                .withType(Dialogs.MessageType.CONFIRMATION)
                .show()
);
----

Доступно для большинства компонентов:

<<gui_Accordion,Accordion>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_BrowserFrame,BrowserFrame>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_Calendar,Calendar>> -
<<gui_CheckBox,CheckBox>> -
<<gui_CheckBoxGroup,CheckBoxGroup>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CssLayout,CssLayout>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DataGrid,DataGrid>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_Embedded,Embedded>> -
<<gui_FieldGroup,FieldGroup>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_Filter,Filter>> -
<<gui_Form,Form>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_GroupTable,GroupTable>> -
<<gui_HtmlBoxLayout,HtmlBoxLayout>> -
<<gui_Image,Image>> -
<<jsComponent,JavaScriptComponent>> -
<<gui_Label,Label>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_PopupView,PopupView>> -
<<gui_ProgressBar,ProgressBar>> -
<<gui_RadioButtonGroup,RadioButtonGroup>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_SuggestionField,SuggestionField>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_Table,Table>> -
<<gui_TabSheet,TabSheet>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_Tree,Tree>> -
<<gui_TreeDataGrid,TreeDataGrid>> -
<<gui_TreeTable,TreeTable>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasSettings.html[HasSettings]::
+
--
[[gui_api_settings]]
* `applySettings()` - восстанавливает последние пользовательские настройки для этого компонента.

* `saveSettings()` - сохраняет текущие пользовательские настройки для этого компонента.

Доступно для компонентов:

<<gui_DataGrid,DataGrid>> -
<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_Table,Table>> -
<<gui_TextArea,TextArea>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasUserOriginated.html[HasUserOriginated]::
+
--
[[gui_api_UserOriginated]]
* `isUserOriginated()` - предоставляет информацию о происхождении события. Возвращает `true`, если событие было вызвано пользователем на стороне клиента, или `false`, если событие было вызвано программно на стороне сервера.
+
Пример использования:
+
[source, java]
----
@Subscribe("customersTable")
protected void onCustomersTableSelection(Table.SelectionEvent<Customer> event) {
    if (event.isUserOriginated())
        notifications.create()
                .withCaption("You selected " + event.getSelected().size() + " customers")
                .show();
}
----

Метод `isUserOriginated()` доступен для следующих событий:

* `CollapseEvent` компонента <<gui_TreeDataGrid,TreeDataGrid>>,
* `ColumnCollapsingChangeEvent` компонента <<gui_DataGrid,DataGrid>>,
* `ColumnReorderEvent` компонента <<gui_DataGrid,DataGrid>>,
* `ColumnResizeEvent` компонента <<gui_DataGrid,DataGrid>>,
* `ExpandedStateChangeEvent` компонентов <<gui_Filter,Filter>> и <<gui_GroupBoxLayout,GroupBoxLayout>> (см. <<gui_api_expanded,Collapsable>>),
* `ExpandEvent` компонента <<gui_TreeDataGrid,TreeDataGrid>>,
* `SelectedTabChangeEvent` компонента <<gui_TabSheet,TabSheet>>,
* `SelectionEvent` компонента <<gui_DataGrid,DataGrid>>,
* `SelectionEvent` компонента <<gui_Table,Table>>,
* `SortEvent` компонента <<gui_DataGrid,DataGrid>>,
* `SplitPositionChangeEvent` компонента <<gui_SplitPanel,SplitPanel>>,
* `ValueChangeEvent` компонентов, реализующих интерфейс `HasValue` (см. <<gui_api_addValueChangeListener,ValueChangeListener>>).
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasValue.html[HasValue]::
+
--
[[gui_api_addValueChangeListener]]
* `addValueChangeListener()` - добавляет слушатель, реализующий интерфейс `ValueChangeListener`, для отслеживания изменения значения компонента.
+
[source, java]
----
@Inject
private TextField<String> textField;
@Inject
private Notifications notifications;

@Subscribe
protected void onInit(InitEvent event) {
    textField.addValueChangeListener(stringValueChangeEvent ->
            notifications.create()
                    .withCaption("Before: " + stringValueChangeEvent.getPrevValue() + ". After: " + stringValueChangeEvent.getValue())
                    .show());
}
----
+
С той же целью вы можете подписаться на событие изменения значения конкретного компонента в контроллере экрана, к примеру:
+
[source, java]
----
@Subscribe("textField")
protected void onTextFieldValueChange(HasValue.ValueChangeEvent<String> event) {
    notifications.create()
            .withCaption("Before: " + event.getPrevValue() + ". After: " + event.getValue())
            .show();
}
----

См. также <<gui_api_UserOriginated,UserOriginated>>.

Доступно для компонентов:

<<gui_CheckBox,CheckBox>> -
<<gui_CheckBoxGroup,CheckBoxGroup>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_Label,Label>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_ProgressBar,ProgressBar>> -
<<gui_RadioButtonGroup,RadioButtonGroup>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SuggestionField,SuggestionField>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_TwinColumn,TwinColumn>> -
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/LayoutClickNotifier.html[LayoutClickNotifier]::
+
--
[[gui_api_addLayoutClickListener]]
* `addLayoutClickListener()` - добавляет слушатель, реализующий интерфейс `LayoutClickListener`, для отслеживания кликов по области компонента.
+
[source, java]
----
vbox.addLayoutClickListener(layoutClickEvent ->
    notifications.create()
            .withCaption("Clicked")
            .show());
----
+
С той же целью вы можете подписаться на событие клика по конкретному компоненту, к примеру:
+
[source, java]
----
@Subscribe("vbox")
protected void onVboxLayoutClick(LayoutClickNotifier.LayoutClickEvent event) {
    notifications.create()
            .withCaption("Clicked")
            .show();
}
----

Доступно для компонентов:

<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasMargin.html[HasMargin]::
+
--
[[gui_api_margin]]
* `setMargin()` - устанавливает компоненту внешние поля.
+
** Добавление внешних полей со всех сторон компонента:
+
[source, java]
----
vbox.setMargin(true);
----
+
** Добавление внешних полей только в верхней и нижней части компонента:
+
[source, java]
----
vbox.setMargin(true, false, true, false);
----
+
** Создание объекта конфигурации `MarginInfo`:
+
[source, java]
----
vbox.setMargin(new MarginInfo(true, false, false, true));
----

* `getMargin()` - возвращает конфигурацию внешних полей в виде экземпляра `MarginInfo`.

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_Filter,Filter>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasOuterMargin.html[HasOuterMargin]::
+
--
[[gui_api_outerMargin]]
* `setOuterMargin()` - устанавливает внешние поля вокруг границы компонента.
+
** Добавление внешних полей со всех сторон компонента:
+
[source, java]
----
groupBox.setOuterMargin(true);
----
+
** Добавление внешних полей только в верхней и нижней части компонента:
+
[source, java]
----
groupBox.setOuterMargin(true, false, true, false);
----
+
** Создание объекта конфигурации `MarginInfo`:
+
[source, java]
----
groupBox.setOuterMargin(new MarginInfo(true, false, false, true));
----

* `getOuterMargin()` - возвращает конфигурацию внешних полей в виде экземпляра `MarginInfo`.

Доступно для компонентов:

<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/HasSpacing.html[HasSpacing]::
+
--
[[gui_api_spacing]]
* `setSpacing()` - добавляет внутренние поля между компонентом и вложенными в него компонентами.
+
[source, java]
----
vbox.setSpacing(true);
----

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>>
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/components/ShortcutNotifier.html[ShortcutNotifier]::
+
--
[[gui_api_shortcut]]
* `addShortcutAction()` - добавляет действие, вызываемое при нажатии определённого сочетания клавиш.
+
[source, java]
----
include::{sourcesdir}/gui_vcl/cssLayout.java[]
----

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--