:sourcesdir: ../../../../../source

[[gui_api]]
===== API компонентов

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Доступно для всех визуальных компонентов::
+
--
[[gui_api_unwrap]]
* `unwrap()` - возвращает экземпляр компонента для текущего типа клиента (компонент Vaadin или Swing). Можно использовать в клиентском модуле для доступа к API базового компонента, см. раздел <<webComponentsHelper>>.
+
[source, java]
----
com.vaadin.ui.TextField vTextField = textField.unwrap(com.vaadin.ui.TextField.class);
----

* `unwrapComposition()` - возвращает экземпляр самого внешнего контейнера для текущего типа клиента. Можно использовать в клиентском модуле для доступа к API базового компонента.
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.Buffered.html[Component.Buffered]::
+
--
[[gui_api_commit]]
* `commit()` - обновляет источник данных, сохраняя все изменения, внесённые после последнего коммита.

[[gui_api_discard]]
* `discard()` - отменяет все изменения, внесённые после последнего коммита. Значение компонента обновляется из источника данных.

[[gui_api_isModified]]
* `isModified()` - возвращает `true`, если значение компонента изменилось с момента последнего обновления из источника данных.

[source, java]
----
if (textArea.isModified()) {
    textArea.commit();
}
----

Доступно для компонентов:

<<gui_CheckBox,CheckBox>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_PickerField,PickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.Collapsable.html[Component.Collapsable]::
+
--
[[gui_api_expanded]]
* `addExpandedStateChangeListener()` - добавляет слушатель, реализующий интерфейс `ExpandedStateChangeListener`, для отслеживания событий сворачивания/разворачивания компонента.
+
[source, java]
----
groupBox.addExpandedStateChangeListener(e ->
        showNotification("Expanded: " + groupBox.isExpanded()));
----

Доступно для компонентов:

<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.Container.html[Component.Container]::
+
--
[[gui_api_add]]
* `add()` - добавляет дочерний компонент в контейнер.

[[gui_api_remove]]
* `remove()` - удаляет дочерний компонент из контейнера.

[[gui_api_removeAll]]
* `removeAll()` - удаляет все дочерние компоненты из контейнера.

[[gui_api_getOwnComponent]]
* `getOwnComponent()` - возвращает компонент, вложенный непосредственно в этот контейнер.

[[gui_api_getComponent]]
* `getComponent()` - возвращает компонент, находящийся где-либо внутри дерева компонентов в этом контейнере.

[[gui_api_getComponentNN]]
* `getComponentNN()` - возвращает компонент, находящийся где-либо внутри дерева компонентов в этом контейнере, и выбрасывает исключение, если компонент не найден.

[[gui_api_getOwnComponents]]
* `getOwnComponents()` - возвращает список всех компонентов, вложенных непосредственно в этот контейнер.

[[gui_api_getComponents]]
* `getComponents()` - возвращает список всех компонентов, находящихся где-либо внутри дерева компонентов в этом контейнере.

Доступно для компонентов:

<<gui_Accordion,Accordion>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_HtmlBoxLayout,HtmlBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_TabSheet,TabSheet>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.OrderedContainer.html[Component.OrderedContainer]::
+
--
[[gui_api_indexOf]]
* `indexOf()` - возвращает индекс компонента внутри упорядоченного контейнера.

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_Frame,Frame>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.HasContextHelp.html[Component.HasContextHelp]::
+
--
[[gui_api_contextHelp]]
* `setContextHelpIconClickHandler()` - добавляет слушатель кликов по значку контекстной подсказки. Слушатель имеет приоритет над <<gui_attr_contextHelpText,текстом подсказки>>, таким образом, контекстная подсказка с текстом не будет отображаться, если также установлен слушатель кликов по значку подсказки.

[source, java]
----
textArea.setContextHelpIconClickHandler(event ->
        showMessageDialog("Title", "Body message",
                MessageType.CONFIRMATION_HTML
                        .modal(false)));
----

Доступно для компонентов:

<<gui_CheckBox,CheckBox>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.HasSettings.html[Component.HasSettings]::
+
--
[[gui_api_settings]]
* `applySettings()` - восстанавливает последние пользовательские настройки для этого компонента.

* `saveSettings()` - сохраняет текущие пользовательские настройки для этого компонента.

Доступно для компонентов:

<<gui_DataGrid,DataGrid>> -
<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_Table,Table>> -
<<gui_TextArea,TextArea>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.HasValue.html[Component.HasValue]::
+
--
[[gui_api_addValueChangeListener]]
* `addValueChangeListener()` - добавляет слушатель, реализующий интерфейс `ValueChangeListener`, для отслеживания изменения значения компонента. Если компонент привязан к некоему источнику данных, то с точки зрения жизненного цикла экрана зачастую удобнее использовать <<datasource_listeners,слушатели источников данных>>.
+
[source, java]
----
textField.addValueChangeListener(e ->
        showNotification("Before: " + e.getPrevValue() + ". After: " + e.getValue()));
----

Доступно для компонентов:

<<gui_CheckBox,CheckBox>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_Label,Label>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_ProgressBar,ProgressBar>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.LayoutClickNotifier.html[Component.LayoutClickNotifier]::
+
--
[[gui_api_addLayoutClickListener]]
* `addLayoutClickListener()` - добавляет слушатель, реализующий интерфейс `LayoutClickListener`, для отслеживания кликов по области компонента.
+
[source, java]
----
vbox.addLayoutClickListener(event ->
                showNotification("Clicked"));
----

Доступно для компонентов:

<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.Margin.html[Component.Margin]::
+
--
[[gui_api_margin]]
* `setMargin()` - устанавливает компоненту внешние поля.
+
** Добавление внешних полей со всех сторон компонента:
+
[source, java]
----
vbox.setMargin(true);
----
+
** Добавление внешних полей только в верхней и нижней части компонента:
+
[source, java]
----
vbox.setMargin(true, false, true, false);
----
+
** Создание объекта конфигурации `MarginInfo`:
+
[source, java]
----
vbox.setMargin(new MarginInfo(true, false, false, true));
----

* `getMargin()` - возвращает конфигурацию внешних полей в виде экземпляра `MarginInfo`.

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_Filter,Filter>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.OuterMargin.html[Component.OuterMargin]::
+
--
[[gui_api_outerMargin]]
* `setOuterMargin()` - устанавливает внешние поля вокруг границы компонента.
+
** Добавление внешних полей со всех сторон компонента:
+
[source, java]
----
groupBox.setOuterMargin(true);
----
+
** Добавление внешних полей только в верхней и нижней части компонента:
+
[source, java]
----
groupBox.setOuterMargin(true, false, true, false);
----
+
** Создание объекта конфигурации `MarginInfo`:
+
[source, java]
----
groupBox.setOuterMargin(new MarginInfo(true, false, false, true));
----

* `getOuterMargin()` - возвращает конфигурацию внешних полей в виде экземпляра `MarginInfo`.

Доступно для компонентов:

<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.ShortcutNotifier.html[Component.ShortcutNotifier]::
+
--
[[gui_api_shortcut]]
* `addShortcutAction()` - добавляет действие, вызываемое при нажатии определённого сочетания клавиш.
+
[source, java]
----
include::{sourcesdir}/gui_vcl/cssLayout.java[]
----

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.9/com/haulmont/cuba/gui/components/Component.Spacing.html[Component.Spacing]::
+
--
[[gui_api_spacing]]
* `setSpacing()` - добавляет внутренние поля между компонентом и вложенными в него компонентами.
+
[source, java]
----
vbox.setSpacing(true);
----

Доступно для компонентов:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>>
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

