:sourcesdir: ../../../../source

[[rest_api_v2_ex_get_token]]
==== Getting an OAuth Token

An OAuth token is required for any REST API method (except when you are using an <<rest_api_v2_anonymous, anonymous access>>). A token can be obtained by the POST request on the address:

`\http://localhost:8080/app/rest/v2/oauth/token`

An access to this endpoint is protected with a basic authentication. REST API client identifier and password is used for basic authentication. Please note that these are not an application user login and password. REST API client id and password are defined in the application properties <<cuba.rest.client.id, cuba.rest.client.id>> and <<cuba.rest.client.secret, cuba.rest.client.secret>> (the default values are `client` and `secret`). You must pass the client id and secret, separated by a single colon (":") character, within a base64 encoded string in the `Authorization` header.

The request type must be `application/x-www-form-urlencoded`, the encoding is `UTF-8`.

The request must contain the following parameters:

* `grant_type` - `password`.
* `username` - application user login.
* `password` - application user password.

[source, httprequest]
----
include::{sourcesdir}/rest/rest-access-token-request.txt[]
----

Method returns a JSON object:

[source, json]
----
include::{sourcesdir}/rest/rest-access-token-response.json[]
----

An access token value is in the `access_token` property.

In order to use the access token, put it in the `Authorization` header with the `Bearer` type, for example:

[source, plain]
----
Authorization: Bearer 29bc6b45-83cd-4050-8c7a-2a8a60adf251
----

The `refresh_token` property contains a refresh token value. A refresh token cannot be used for accessing the protected resources, but it has a longer lifetime than an access token and it can be used to obtain new access token when the current one is expired. 

The request for getting new access token using the refresh token must contain the following parameters:

* `grant_type` - `refresh_token`.
* `refresh_token` - a refresh token value.

[source, httprequest]
----
include::{sourcesdir}/rest/rest-access-token-using-refresh-request.txt[]
----

See also the following application properties related to tokens:

* <<cuba.rest.client.tokenExpirationTimeSec,cuba.rest.client.tokenExpirationTimeSec>>

* <<cuba.rest.client.refreshTokenExpirationTimeSec,cuba.rest.client.refreshTokenExpirationTimeSec>>

* <<cuba.rest.client.authorizedGrantTypes,cuba.rest.client.authorizedGrantTypes>>

