:sourcesdir: ../../../../source

[[rest_api_v2_ex_query_get]]
==== Executing a JPQL Query (GET)

Before the execution with the REST API a query must be described in the <<rest_api_v2_queries_config, configuration file>>. The `rest-queries.xml` file must be created in the main package of the *web* module (e.g. `com.company.sales`). Then the file must be defined in the application properties file of the *web* module (web-app.properties).

[source, properties]
----
cuba.rest.queriesConfig = +com/company/sales/rest-queries.xml
----

`rest-queries.xml` contents:

[source, xml]
----
include::{sourcesdir}/rest/sales-rest-queries.xml[]
----

To execute a JPQL query the following *GET* request must be executed:

`\http://localhost:8080/app/rest/v2/queries/sales$Order/ordersAfterDate?startDate=2016-11-01&endDate=2017-11-01`

The request URL parts:

* `sales$Order` - extracted entity name.
* `ordersAfterDate` - a query name from the configuration file.
* `startDate` and `endDate` - request parameters with the values.

An OAuth token must be put in the `Authorization` header with the `Bearer` type.

The method returns a JSON array of extracted entity instances:

[source, json]
----
include::{sourcesdir}/rest/rest-ordersAfterDate-query-response.json[]
----

A full list of possible request parameters is available in the {rest_swagger_url}[Swagger documentation].

