:sourcesdir: ../../../../../source

[[views_creation]]
===== Создание представлений

Представление может быть создано двумя путями:

* *программно* - созданием экземпляра `View`, например:
+
[source, java]
----
include::{sourcesdir}/common/views_1.java[]
----
+
Как правило, таким способом создаются представления, используемые только в каком-то одном месте бизнес-логики.

* *декларативно* - путем создания описателя на XML и его развертывания в репозитории представлений `ViewRepository`. При развертывании на основе XML-описателя создаются и кэшируются экземпляры `View`. В дальнейшем в любом месте кода приложения требуемое представление можно получить вызовом репозитория с указанием класса сущности и имени представления.

Рассмотрим подробнее декларативный способ создания и работы с представлениями.

`ViewRepository` является бином *Spring*, доступным для всех блоков приложения. Ссылка на `ViewRepository` может быть также получена через интерфейс инфраструктуры <<metadata,Metadata>>. Для получения экземпляра `View`, содержащегося в репозитории, используются методы `getView()`. Для развертывания XML-описателей представлений в репозитории используются методы `deployViews()` базовой реализации `AbstractViewRepository`.

В репозитории для каждой сущности по умолчанию доступны три представления с именами `_local`, `_minimal` и `_base`:

* `_local` включает в себя все <<local_attribute,локальные>> атрибуты сущности

* `_minimal` включает в себя атрибуты, входящие в имя экземпляра сущности, и задаваемые аннотацией <<namePattern_annotation,@NamePattern>>. Если аннотация `@NamePattern` для сущности не указана, данное представление не включает никаких атрибутов.

* `_base` включает в себя все локальные несистемные атрибуты и атрибуты, заданные в аннотации `@NamePattern` (т.е. фактически `_minimal` + `_local`).

Подробная структура XML-описателей изложена <<views.xml,здесь>>.

Пример описателя представления для сущности Заказ, которое должно обеспечить загрузку всех локальных атрибутов, ассоциированного Покупателя и коллекции Пунктов заказа:

[source, xml]
----
include::{sourcesdir}/common/views_2.xml[]
----

Рекомендуемый способ группировки и развертывания описателей представлений:

* В <<app_modules,модуле>> *global* в корне `src` создать файл `views.xml` и поместить в него все описатели представлений, которые должны быть доступны глобально, т.е. на всех <<app_tiers,уровнях приложения>>.

* Зарегистрировать данный файл в свойстве <<cuba.viewsConfig,cuba.viewsConfig>> блока Middleware и используемых клиентских блоков, т.е. в файле `app.properties` модуля *core*, в файле `web-app.properties` модуля *web* и так далее. Это обеспечит автоматическое развертывание представлений на старте приложения в репозитории Middleware и клиентских блоков (см. метод `AbstractViewRepository.init()`).

* Если существуют представления, которые необходимы только какому-то одному клиентскому блоку приложения, то можно определить их в аналогичном файле данного блока, например, `web-views.xml`, и добавить этот файл в свойство `cuba.viewsConfig` этого блока, т.е. в данном случае в файл `web-app.properties`. 

Если на момент развертывания некоторого представления в репозитории уже есть представление для этого же класса сущности и с таким же именем, то новое будет проигнорировано. Для того чтобы представление заменило имеющееся в репозитории и гарантированно было развернуто, в XML-описателе должен быть явно указан атрибут `overwrite = "true"`.

[TIP]
====
Рекомендуется давать представлениям "описательные" имена. Например, не "browse", а "customerBrowse". Это упрощает поиск XML-описателей представлений по имени в процессе разработки приложения.
====

