:sourcesdir: ../../../../../source

[[views_creation]]
===== Создание представлений

Представление может быть создано следующими способами:

* *Программно* - созданием экземпляра `View`. Как правило, таким способом создаются представления, используемые в бизнес-логике.
+
Экземпляры представлений, включая вложенные, можно создавать с помощью конструктора:
+
[source, java]
----
include::{sourcesdir}/common/views_1.java[]
----
+
То же самое можно сделать с помощью `ViewBuilder`:
+
[source, java]
----
include::{sourcesdir}/common/views_3.java[]
----
+
`ViewBuilder` можно также использовать в <<dataManager,DataManager>> через его fluent interface:
+
[source, java]
----
include::{sourcesdir}/common/views_4.java[]
----

* *Декларативно в экранах* - путем объявления внутри XML-дескриптора экрана, см. пример в разделе <<gui_data_comp_decl>>. Это рекомендуемый способ при загрузке данных в экранах Generic UI для проектов, использующих CUBA 7.2+.

* *Декларативно в общем репозитории* - путем объявления в файле <<views.xml>> проекта. Файл `views.xml` обрабабывается на старте приложения, созданные экземпляры `View` кэшируются в репозитории представлений `ViewRepository`. В дальнейшем в любом месте кода приложения требуемое представление можно получить вызовом репозитория с указанием класса сущности и имени представления.

Пример XML-описателя представления, которое должно обеспечить загрузку всех локальных атрибутов сущности Заказ, ассоциированного Покупателя и коллекции Пунктов заказа:

[source, xml]
----
include::{sourcesdir}/common/views_2.xml[]
----

Работа с репозиторием представлений::
+
--
`ViewRepository` является бином Spring, доступным для всех блоков приложения. Ссылка на `ViewRepository` может быть также получена инжекцией или через статические методы класса `AppBeans`. Для получения экземпляра `View`, содержащегося в репозитории, используются методы `getView()`.

В репозитории для каждой сущности по умолчанию доступны три представления с именами `_local`, `_minimal` и `_base`:

* `_local` включает в себя все <<local_attribute,локальные>> атрибуты сущности

* `_minimal` включает в себя атрибуты, входящие в имя экземпляра сущности, и задаваемые аннотацией <<namePattern_annotation,@NamePattern>>. Если аннотация `@NamePattern` для сущности не указана, данное представление не включает никаких атрибутов.

* `_base` включает в себя все локальные несистемные атрибуты и атрибуты, заданные в аннотации `@NamePattern` (т.е. фактически `_minimal` + `_local`).

CUBA Studio автоматически создает и поддерживает в проекте один файл <<views.xml>>. Однако при необходимости можно использовать и несколько таких файлов следующим образом:

* В модуле `global` должен находиться файл `views.xml` со всеми описателями представлений, которые должны быть доступны глобально, т.е. на всех уровнях приложения. Данный файл должен быть зарегистрирован в свойстве приложения <<cuba.viewsConfig,cuba.viewsConfig>> всех блоков, т.е. в файле `app.properties` модуля `core`, в файле `web-app.properties` модуля `web` и так далее. Это по умолчанию обеспечивает Studio.

* Если в проекте имеется много общих представлений, их можно разместить в нескольких файлах, например в стандартном `views.xml` и в дополнительных `foo-views.xml`, `bar-views.xml`. Все файлы должны быть зарегистрированы в свойстве `cuba.viewsConfig`:
+
----
cuba.viewsConfig = +com/company/sales/views.xml com/company/sales/foo-views.xml com/company/sales/bar-views.xml
----

* Если существуют представления, которые необходимы только какому-то одному блоку приложения, то можно определить их в аналогичном файле данного блока, например, `web-views.xml`, и добавить этот файл в свойство `cuba.viewsConfig` этого блока, т.е. в данном случае в файл `web-app.properties`.

Если на момент развертывания некоторого представления в репозитории уже есть представление для этого же класса сущности и с таким же именем, то новое будет проигнорировано. Для того чтобы представление заменило имеющееся в репозитории и гарантированно было развернуто, в XML-описателе должен быть явно указан атрибут `overwrite = "true"`.

[TIP]
====
Рекомендуется давать представлениям "описательные" имена. Например, не "browse", а "customer-browse". Это упрощает поиск XML-описателей представлений по имени в процессе разработки приложения.
====
--
