:sourcesdir: ../../../../source

[[appContext]]
==== AppContext

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/core/sys/AppContext.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`AppContext` - системный класс, в статических полях которого хранятся ссылки на некоторые общие для любого <<app_tiers,блока>> приложения компоненты:

* `ApplicationContext` фреймворка *Spring*

* Набор <<app_properties,свойств приложения>>, загруженных из файлов `app.properties`

* `ThreadLocal` переменная, хранящая экземпляры `SecurityContext`

* Коллекция слушателей жизненного цикла приложения (`AppContext.Listener`)

`AppContext` инициализируется на запуске приложения классами-загрузчиками, специфичными для типа <<app_tiers,блока>> приложения:

* загрузчик Middleware - `AppContextLoader`

* загрузчик Web Client - `WebAppContextLoader`

* загрузчик Web Portal - `PortalAppContextLoader`

`AppContext` может быть использован в прикладном коде для решения следующих задач:

* Получения значений <<app_properties,свойств приложения>>, хранимых в файлах `app.properties`, если они недоступны через <<config_interfaces,конфигурационные интерфейсы>>.

* Передачи `SecurityContext` в новые потоки выполнения, см. <<authentication,Аутентификация пользователей>>.

* Регистрации слушателей, срабатывающих после полной инициализации и перед закрытием приложения, например:
+
[source, java]
----
include::{sourcesdir}/common/appcontext_1.java[]
----
+
[WARNING]
====
Рекомендуемый способ выполнения кода в момент запуска и остановки приложения - это использование <<app_lifecycle_events>>.
====

