:sourcesdir: ../../../../source

[[infrastructure_interfaces]]
==== Интерфейсы инфраструктуры

Интерфейсы инфраструктуры обеспечивают доступ к часто используемой функциональности платформы. Большинство из этих интерфейсов расположены в <<app_modules,модуле>> *global* и могут быть использованы как на среднем слое, так и в <<app_tiers,блоках>> клиентского уровня, но некоторые (например, <<persistence,Persistence>>) доступны только коду среднего слоя.

Интерфейсы инфраструктуры реализуются бинами Spring Framework, поэтому они могут быть инжектированы в любые другие управляемые компоненты (<<managed_beans,Managed Beans>>, <<services,сервисы среднего слоя>>, <<screen_controller,контроллеры>> экранов универсального пользовательского интерфейса).

Кроме того, как и любые другие бины, интерфейсы инфраструктуры могут быть получены с помощью статических методов класса `AppBeans` и использоваться в неуправляемых компонентах (POJO, вспомогательных классах и пр.).

include::infrastructure_interfaces/configuration.adoc[]

include::infrastructure_interfaces/messages.adoc[]

include::infrastructure_interfaces/metadata.adoc[]

include::infrastructure_interfaces/resources.adoc[]

include::infrastructure_interfaces/scripting.adoc[]

include::infrastructure_interfaces/security.adoc[]

include::infrastructure_interfaces/timeSource.adoc[]

include::infrastructure_interfaces/userSessionSource.adoc[]

include::infrastructure_interfaces/uuidSource.adoc[]

include::infrastructure_interfaces/dataManager.adoc[]

include::infrastructure_interfaces/entityStates.adoc[]

include::infrastructure_interfaces/events.adoc[]

