:sourcesdir: ../../../../source

[[screen_validation]]
==== ScreenValidation

Бин `ScreenValidation` используется для запуска валидации в экранах. Он имеет следующие методы:

* `ValidationErrors validateUiComponents()` - используется при коммите изменений в экранах `StandardEditor`, `InputDialog`, и `MasterDetailScreen`.  Принимает на вход коллекцию из компонентов или контейнер компонентов и возвращает ошибки валидации в этих компонентах (объект `ValidationErrors`). Метод `validateUiComponents()` также может быть использован в произвольном экране. Например:
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_1.java[]
----

* `showValidationErrors()` - показывает нотификацию со всеми ошибками и проблемными компонентами. Метод принимает на вход экран и объект `ValidationErrors`. Также используется по умолчанию в экранах `StandardEditor`, `InputDialog`, и `MasterDetailScreen`.

* `validateCrossFieldRules()` - принимает на вход экран и сущность и возвращает объект `ValidationErrors`. Выполняет правила перекрестной проверки, установленные на поля сущности. Экраны редактирования выполняют валидацию ограничений уровня класса при коммите, если ограничения включают группу `UiCrossFieldChecks`, и все проверки ограничений уровня атрибутов прошли успешно (больше информации см. в разделе <<bean_validation_custom_constraints,Собственные ограничения>>). Валидацию данного типа можно отключить с помощью метода контроллера `setCrossFieldValidate()`. По умолчанию используется в экранах `StandardEditor`, `MasterDetailScreen`, в <<gui_DataGrid_inline_editor,редакторе>> `DataGrid`. Метод `validateCrossFieldRules()` также может быть использован в произвольном экране.
+
В качестве примера рассмотрим сущность `Event`, для которой мы можем определить аннотацию уровня класса, для проверки того, что дата *Start date* должна быть раньше даты *End date*.
+
.Сущность Event
[source, java]
----
include::{sourcesdir}/common/screen_validation_5.java[]
----
Определение аннотации выглядит следующим образом:
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_6.java[]
----
+
.EventDateValidator
[source, java]
----
include::{sourcesdir}/common/screen_validation_7.java[]
----
Далее вы можете использовать метод `validateCrossFieldRules()` в произвольном экране.
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_2.java[]
----

* `showUnsavedChangesDialog()` - показывает стандартный диалог несохраненных изменений ("Вы действительно хотите закрыть экран?") с кнопками *Да* и *Нет*. Используется в экране редактора `StandardEditor`. Метод `showUnsavedChangesDialog()` имеет обработчик, который реагирует на действия пользователя (кнопку, которую он нажал):
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_3.java[]
----

* `showSaveConfirmationDialog()` - показывает стандартный диалог подтверждения сохранения измененных данных ("Сохранить изменения перед закрытием экрана?") с кнопками *Сохранить*, *Не сохранять*, *Отмена*. Используется в экране редактора `StandardEditor`. Метод `showSaveConfirmationDialog()` имеет обработчик, который реагирует на действия пользователя (кнопку, которую он нажал):
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_4.java[]
----

Вы можете настроить тип диалога с помощью свойства приложения <<cuba.gui.useSaveConfirmation,cuba.gui.useSaveConfirmation>>.