:sourcesdir: ../../../../source

[[gui_notifications]]
==== Notifications

Notifications are pop-ups displayed in the center or in the corner of the main application window. They can disappear automatically or when the user clicks on the screen or presses Esc.

In order to show a notification, inject the `Notifications` bean into the screen controller and use its fluent interface. In the following example, a notification is shown on the button click:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_1.java[]
----

[[gui_notifications_description]]
Notification can have a description which is displayed under the caption in a lighter font:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_2.java[]
----

[[gui_notifications_type]]
Notifications can be of the following types:

** `TRAY` – a notification is displayed in the bottom right corner of the application and disappears automatically.

** `HUMANIZED` – a standard notification displayed in the center of the screen, disappears automatically.

** `WARNING` – a warning. Disappears when the user clicks on the screen.

** `ERROR` – a notification about an error. Disappears when the user clicks on the screen.

The default type is `HUMANIZED`. You can provide another type in the `create()` method:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_3.java[]
----

[[gui_notifications_contentMode]]
You can use `\n` characters for line breaks in messages. In order to show HTML, use the `withContentMode()` method:

[source, java]
----
include::{sourcesdir}/gui/notifications/gui_notifications_4.java[]
----

When using HTML, don't forget to escape data to prevent code injection.

[[gui_notifications_position]]
You can set the position of the notification using the `withPosition()` method. The standard values are:

* `TOP_RIGHT`
* `TOP_LEFT`
* `TOP_CENTER`
* `MIDDLE_RIGHT`
* `MIDDLE_LEFT`
* `MIDDLE_CENTER`
* `BOTTOM_RIGHT`
* `BOTTOM_LEFT`
* `BOTTOM_CENTER`

[[gui_notifications_delay]]
You can also set the delay in milliseconds before the notification disappears, using the `withHideDelayMs()` method. The `-1` value is used to require the user to click the message.