:sourcesdir: ../../../../source

[[gui_data]]
==== Data Components

Data components are non-visual elements of screens that provide loading of data from the middle tier, binding it to data-aware visual components and saving changed data back to the middle tier. There are the following categories of data components:

* <<gui_data_containers,Containers>> provide the thin layer between entities and data-aware visual components. Different types of containers hold either single instances or collections of entities.

* <<gui_data_loaders,Loaders>> load data from the middle tier to containers.

* <<gui_DataContext,DataContext>> tracks changes in entities and saves changed instances back to the middle tier upon request.

Usually, data components are defined in the screen XML descriptor in the `<data>` element. They can be injected into the controller in the same way as visual components.

Data components of a particular screen are registered in the `ScreenData` object which is associated with the screen controller and available through its `getScreenData()` method. This object is useful when you need to load all data for the screen, for example:

[source, java]
----
@Subscribe
protected void onBeforeShow(BeforeShowEvent event) {
    getScreenData().loadAll();
}
----

[TIP]
====
Please note that `StandardEditor`, `StandardLookup` and `MasterDetailScreen` base classes load data automatically when the `@LoadDataBeforeShow` annotation is present on the controller class. So you should invoke this method only when there is no such anntotation or in custom screens inherited directly from `Screen`.
====

include::gui_data/gui_data_containers.adoc[]

include::gui_data/gui_data_loaders.adoc[]

include::gui_data/gui_DataContext.adoc[]

include::gui_data/gui_using_data_comp.adoc[]
