:sourcesdir: ../../../../source

[[gui_data]]
==== Data Components

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.0/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.0</span>
    </a>
</div>
++++

Data components are non-visual elements of screens that provide loading of data from the middle tier, binding it to data-aware visual components and saving changed data back to the middle tier. There are the following categories of data components:

* <<gui_data_containers,Containers>> provide the thin layer between entities and data-aware visual components. Different types of containers hold either single instances or collections of entities.

* <<gui_data_loaders,Loaders>> load data from the middle tier to containers.

* <<gui_DataContext,DataContext>> tracks changes in entities and saves changed instances back to the middle tier upon request.

Usually, data components are defined in the screen XML descriptor in the `<data>` element. They can be injected into the controller in the same way as visual components:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_4.java[]
----

Data components of a particular screen are registered in the `ScreenData` object which is associated with the screen controller and available through its `getScreenData()` method. This object is useful when you need to load all data for the screen, for example:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_5.java[]
----

[TIP]
====
Please note that screens load data automatically when the `@LoadDataBeforeShow` annotation is present on the controller class. So programmatic loading is needed only when there is no such anntotation or the annotation value is set to `false`. It is usually required when you need to set some loading parameters, as in the example above.
====

include::gui_data/gui_data_containers.adoc[]

include::gui_data/gui_data_loaders.adoc[]

include::gui_data/gui_DataContext.adoc[]

include::gui_data/gui_using_data_comp.adoc[]
