:sourcesdir: ../../../../source

[[gui_facets]]
==== Non-Visual Components

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

A screen can contain non-visual components defined in the `facets` element of the XML descriptor. The framework provides the following non-visual components:

* <<gui_Timer,Timer>>
* <<gui_ClipboardTrigger,ClipboardTrigger>>
* <<gui_DataLoadCoordinator,DataLoadCoordinator>>

The application or an add-on can provide its own non-visual components. In order to create a custom facet, follow the steps below:

. Create an interface extending `com.haulmont.cuba.gui.components.Facet`.

. Create implementation class based on `com.haulmont.cuba.web.gui.WebAbstractFacet`.

. Create a Spring bean implementing the `com.haulmont.cuba.gui.xml.FacetProvider` interface parameterized by the type of your facet.

. Create an XSD to be used in screens XML.

Classes `ClipboardTrigger`, `WebClipboardTrigger` and `ClipboardTriggerFacetProvider` of the framework can be a good example of creating a facet.

include::gui_facets/gui_Timer.adoc[]

include::gui_facets/gui_ClipboardTrigger.adoc[]

include::gui_facets/gui_DataLoadCoordinator.adoc[]
