:sourcesdir: ../../../../source

[[gui_dialogs]]
==== Dialogs

The `Dialogs` interface is designed to display standard dialogs windows. Its `createMessageDialog()`, `createOptionDialog()` and `createInputDialog()` methods are the entry points to the fluent API that allows you to construct and show dialogs.

Appearance of the dialogs can be customized using SCSS variables with `$cuba-window-modal-*` prefix. You can change these variables in the visual editor after creating a <<web_theme_extension,theme extension>> or a <<web_theme_creation,custom theme>>.

[[gui_message_dialog]]
Message Dialog::
+
--
In the following example, a message dialog is shown when the user clicks a button:

[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_dialogs_1.java[]
----

You can use `\n` characters for line breaks in messages. In order to show HTML, use the `withContentMode()` method with `ContentMode.HTML` parameter. When using HTML, don't forget to escape data to prevent code injection.

The following methods allow you to customize the look and behavior of the message dialog:

* `withModal()` - if `false` is passed, the dialog is shown as non-modal, which allows a user to interact with the other parts of the application.

* `withCloseOnClickOutside()` - when `true` is passed and the dialog is modal, allows a user to close the dialog by clicking on the application window outside of the dialog.

* `withWidth()`, `withHeight()` allow you to specify the desired dialog geometry.

For example:

[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_dialogs_2.java[]
----
--

[[gui_option_dialog]]
Option Dialog::
+
--
The option dialog displays a message and a set of buttons for user reaction. Use `withActions()` method to provide <<gui_Action,actions>>, each of which is represented by a button in the dialog. For example:

[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_dialogs_3.java[]
----

When a button is clicked, the dialog closes and invokes `actionPerform()` method of the corresponding action.

The `DialogAction` base class is designed to create actions with standard names and icons. Five types of actions defined by the `DialogAction.Type` enum are supported: `OK`, `CANCEL`, `YES`, `NO`, `CLOSE`. Names of corresponding buttons are extracted from the <<main_message_pack,main message pack>>.

The second parameter of the `DialogAction` constructor is used to assign a special visual style for a button representing the action. `Status.PRIMARY` highlights the corresponding button and makes it selected, which is provided by the `c-primary-action` style. If multiple actions with `Status.PRIMARY` are defined for the dialog, only the first action's button will get the style and focus.
--

[[gui_input_dialog]]
Input Dialog::
+
--
Input dialog is a versatile tool which allows you to construct input forms using API and can often save you from creating <<gui_screens,screens>> for trivial data input. It enables entering values of different types, validates the input and provides different actions to be selected by the user.

Let's consider some examples.

. Input dialog with parameters of standard types and standard OK/Cancel actions:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_1.java[]
----
<1> - specifies a mandatory string parameter.
<2> - specifies a double parameter with default value.
<3> - specifies an entity parameter.
<4> - specifies an enumeration parameter.
<5> - specifies a set of actions represented by buttons at the bottom of the dialog.
<6> - in the close listener, we can check what action was used by the user.
<7> - the close event contains entered values that can be obtained using parameter identifiers.

. Input dialog with a custom parameter:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_2.java[]
----
<1> - specifies a custom parameter.
<2> - a caption for the custom parameter is specified in the created component.
<3> - value of the custom parameter is obtained in the same way as for standard parameters.

. Input dialog with custom actions:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_3.java[]
----
<1> - `withActions()` method can accept an array of custom actions.
<2> - in the action handler, you can get a parameter value from the dialog.
<3> - custom action does not close the dialog itself, so you should do it at some moment.

. Input dialog with custom validator:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_4.java[]
----
<1> - the custom validator is needed to ensure at least one parameter is entered.
<2> - in the validator, parameter values can be obtained from the context object.

. Input dialog with a `FileDescriptor` parameter:
+
[source, java]
----
include::{sourcesdir}/gui/dialogs/gui_input_dialog_5.java[]
----
<1> - specifies a `FileDescriptor` parameter.
<2> - the close event contains entered value that can be obtained using parameter identifier.
--