:sourcesdir: ../../../../source

[[gui_facets]]
==== Facets

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.1/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

Facets are screen elements that are not added to the screen layout, unlike visual components. Instead, they add supplementary behavior to the screen or one of its components.

Facets defined in the `facets` element of the XML descriptor. The framework provides the following facets:

* <<gui_Timer,Timer>>
* <<gui_ClipboardTrigger,ClipboardTrigger>>
* <<gui_DataLoadCoordinator,DataLoadCoordinator>>
* <<gui_NotificationFacet,NotificationFacet>>
* <<gui_MessageDialogFacet,MessageDialogFacet>>
* <<gui_OptionDialogFacet,OptionDialogFacet>>
* <<gui_InputDialogFacet,InputDialogFacet>>
* <<gui_ScreenFacet,ScreenFacet>>
* <<gui_EditorScreenFacet,EditorScreenFacet>>
* <<gui_LookupScreenFacet,LookupScreenFacet>>

The application or an add-on can provide its own facets. In order to create a custom facet, follow the steps below:

. Create an interface extending `com.haulmont.cuba.gui.components.Facet`.

. Create implementation class based on `com.haulmont.cuba.web.gui.WebAbstractFacet`.

. Create a Spring bean implementing the `com.haulmont.cuba.gui.xml.FacetProvider` interface parameterized by the type of your facet.

. Create an XSD to be used in screens XML.

Classes `ClipboardTrigger`, `WebClipboardTrigger` and `ClipboardTriggerFacetProvider` of the framework can be a good example of creating a facet.

include::gui_facets/gui_Timer.adoc[]

include::gui_facets/gui_ClipboardTrigger.adoc[]

include::gui_facets/gui_DataLoadCoordinator.adoc[]

include::gui_facets/gui_NotificationFacet.adoc[]

include::gui_facets/gui_MessageDialogFacet.adoc[]

include::gui_facets/gui_OptionDialogFacet.adoc[]

include::gui_facets/gui_InputDialogFacet.adoc[]

include::gui_facets/gui_ScreenFacet.adoc[]

include::gui_facets/gui_EditorScreenFacet.adoc[]

include::gui_facets/gui_LookupScreenFacet.adoc[]
