:sourcesdir: ../../../../source

[[html_attributes]]
==== DOM and CSS Attributes

The framework provides the ad-hoc HTML attributes API for setting DOM and CSS attributes to visual components.

The `HtmlAttributes` bean allows setting DOM/CSS attributes programmatically using the following methods:

* `setDomAttribute()` - sets DOM attribute on the top-most element of the UI component. It accepts the component's identifier, DOM attribute name (e.g. `title`) and the attribute value.

* `setCssProperty()` - sets CSS property value on the top-most element of UI component. It accepts the component's identifier, CSS property name (e.g. `border-color`) and the attribute value.

The most common DOM attribute names and CSS property names are available in the `HtmlAttributes` bean class as constants, but you can use any custom attributes as well.

[WARNING]
====
The functioning of a particular attribute may vary depending on the component this attribute is applied to. Some visual components may implicitly use the same attributes for their own purposes, so the methods above may not work in some cases.
====

The `HtmlAttributes` bean should be injected in the screen controller and used as follows:

.XML descriptor
[source, xml]
----
include::{sourcesdir}/gui/html_attributes.xml[]
----

.Screen controller
[source, java]
----
include::{sourcesdir}/gui/HtmlAttributes.java[]
----

