:sourcesdir: ../../../../source

[[pluggable_component_factories]]
==== Pluggable Component Factories

The pluggable component factories mechanism extends the standard component creation procedure and allows you to create different edit fields in <<gui_FieldGroup, FieldGroup>>, <<gui_Table, Table>> and <<gui_DataGrid, DataGrid>>. It means that application components or your project itself can provide custom strategies that will create non-standard components and/or support custom data types.

An entry point to the mechanism is the `ComponentsFactory.createComponent(ComponentGenerationContext)` method. It works as follows:

* Tries to find `ComponentGenerationStrategy` implementations. If at least one strategy exists, then:
** Iterates over strategies according to the `org.springframework.core.Ordered` interface.
** Returns the first created not `null` component.

`ComponentGenerationStrategy` implementations are used to create UI components. A project can contain any number of such strategies.

`ComponentGenerationContext` is a class which stores the following information that can be used when creating a component:

* `metaClass` - defines the entity for which the component is created.
* `property` - defines the entity attribute for which the component is created.
* `datasource` - a datasource.
* `optionsDatasource` - a datasource that can be used to show options.
* `xmlDescriptor` - an XML descriptor which contains additional information, in case the component is declared in an XML descriptor.
* `componentClass` - a component class for which a component is created, e.g. `FieldGroup`, `Table`, `DataGrid`.

There are two built-in component strategies:

* `DefaultComponentGenerationStrategy` - used to create a component according to the given `ComponentGenerationContext` object. Has the order value `ComponentGenerationStrategy.LOWEST_PLATFORM_PRECEDENCE` (1000).
* `DataGridEditorComponentGenerationStrategy` - used to create a component according to the given `ComponentGenerationContext` object for a DataGrid Editor. Has the order value `ComponentGenerationStrategy.HIGHEST_PLATFORM_PRECEDENCE + 30` (130).

The sample below shows how to replace the default *FieldGroup* component generation for a certain attribute of a specific entity.

[source, java]
----
include::{sourcesdir}/gui/pluggable_field_factories1.java[]
----

[WARNING]
====
Pay attention that overriding existing generation strategies may produce errors in case of changing returned component type, because some screen controllers may have code that expects a certain component type.


For example, in case of using the strategy above, the following injection will produce the exception:

[source, java]
----
@Named("fieldGroup.date")
private DateField dateField;
----

If you try to open such screen you will get the following exception:

----
IllegalArgumentException: Can not set com.haulmont.cuba.gui.components.DateField field com.company.sales.web.order.OrderEdit.dateField to com.haulmont.cuba.web.gui.components.WebDatePicker
----

====

The sample below shows how to define a `ComponentGenerationStrategy` for a specific <<datatype,datatype>>.

[source, java]
----
include::{sourcesdir}/gui/pluggable_field_factories2.java[]
----

