:sourcesdir: ../../../../source

[[shortcuts]]
==== Keyboard Shortcuts

This section provides a list of keyboard shortcuts used in the generic user interface of the application. All the <<app_properties,application properties>> listed below belong to the `ClientConfig` interface and can be used in Web Client and Desktop Client application blocks. 

* Main application window.

** *CTRL-SHIFT-PAGE_DOWN* – switch to the next tab. Defined by the `cuba.gui.nextTabShortcut` property.

** *CTRL-SHIFT-PAGE_UP* – switch to the previous tab. Defined by the `cuba.gui.previousTabShortcut` property.

* Folders panel.

** *ENTER* – open the selected <<folders_pane,folder>>.

** *SPACE* - select/deselect the focused folder.

** *ARROW UP*, *ARROW DOWN* - switch between folders.

** *ARROW LEFT*, *ARROW RIGHT* - collapse/expand a folder with subfolders or jump to the owning folder.

* Screens.

** *ESCAPE* – close the current <<abstractWindow,screen>>. Defined by the `cuba.gui.closeShortcut` property.

** *CTRL-ENTER* – close the current <<abstractEditor,editor>> and save the changes. Defined by the `cuba.gui.commitShortcut` property.

* Standard actions for list components (<<gui_Table,Table>>, <<gui_GroupTable,GroupTable>>, <<gui_TreeTable,TreeTable>>, <<gui_Tree,Tree>>). In addition to these application properties, a shortcut for a particular action can be set by calling it's `setShortcut()` method.

** *CTRL-\* – call the <<createAction,CreateAction>>. Defined by the `cuba.gui.tableShortcut.insert` property.

** *CTRL-ALT-\* – call the <<addAction,AddAction>>. Defined by the `cuba.gui.tableShortcut.add` property.

** *ENTER* – call the <<editAction,EditAction>>. Defined by the `cuba.gui.tableShortcut.edit` property.

** *CTRL-DELETE* – call the <<removeAction,RemoveAction>> and <<excludeAction,ExcludeAction>>. Defined by the `cuba.gui.tableShortcut.remove` property.

* Drop-down lists (<<gui_LookupField,LookupField>>, <<gui_LookupPickerField,LookupPickerField>>).

** *SHIFT-DELETE* – clear the value.

* Standard actions for lookup fields (<<gui_PickerField,PickerField>>, <<gui_LookupPickerField,LookupPickerField>>, <<gui_SearchPickerField,SearchPickerField>>). In addition to these application properties, a shortcut for a particular action can be set by calling its `setShortcut()` method.
+
--
** *CTRL-ALT-L* – call the <<lookupAction,LookupAction>>. Defined by the `cuba.gui.pickerShortcut.lookup`.

** *CTRL-ALT-O* – call the <<openAction,OpenAction>>. Defined by the `cuba.gui.pickerShortcut.open` property.

** *CTRL-ALT-C* – call the <<clearAction,ClearAction>>. Defined by the `cuba.gui.pickerShortcut.clear` property.

In addition to these shortcuts, lookup fields support action calls with CTRL-ALT-1, CTRL-ALT-2 and so on, depending on the number of actions. If you click CTRL-ALT-1 the first action in the list will be called; clicking CTRL-ALT-2 calls the second action, etc. The CTRL-ALT combination can be replaced with any other combination specified in `cuba.gui.pickerShortcut.modifiers` property.
--

* <<gui_Filter,Filter>> component.

** *SHIFT-BACKSPACE* – open the filter selection popup. Defined by the `cuba.gui.filterSelectShortcut` property.

** *SHIFT-ENTER* – apply the selected filter. Defined by the `cuba.gui.filterApplyShortcut` property.

