:sourcesdir: ../../../../source

[[url_history_navigation]]
==== URL browser history and navigation


CUBA History and Routing API provides some browser history and navigation functionality which is essential for web applications.

This functionality consists of three main parts:

* **History** – browser `Back`/`Forward` buttons support.
* **Routes and Navigation** – screen routes registration and handling.
* **Routing API** – a set of methods that enables to react to the fragment change to be able to handle it on the application level.

The [[url_fragment]] _fragment_ is a remaining part of address coming after the "#" symbol. So-called fragments are used as [[url_route]]_routes_.

For example, an address is:

`host:port/app/#main/42/orders/edit?id=17`

In this case fragment is equal to `main/42/orders/edit?id=17`, where:

* `main` – root screen (Main Window) route;
* `42` – <<url_state_mark,URL state mark>>;
* `orders/edit` – nested screen`s route;
* `?id=17` – GET-like parameters part.

include::url_history_navigation/url_quick_start.adoc[]

include::url_history_navigation/url_configuration.adoc[]

include::url_history_navigation/url_history.adoc[]

include::url_history_navigation/url_changes_handling_and_ui_state_reflection.adoc[]

include::url_history_navigation/url_routing.adoc[]