:sourcesdir: ../../../../../source

[[cluster_mw_server]]
===== Настройка взаимодействия серверов Middleware

Сервера Middleware могут поддерживать общие списки <<userSession,пользовательских сессий>> и других объектов, а также координировать сброс кэшей. Для этого достаточно на каждом их них включить свойство приложения <<cuba.cluster.enabled,cuba.cluster.enabled>>. Пример файла `app_home/local.app.properties`:

[source, plain]
----
cuba.cluster.enabled = true

cuba.webHostName = host3
cuba.webPort = 8080
cuba.webContextName = app-core
----

Для серверов Middleware обязательно нужно указать правильные значения свойств <<cuba.webHostName,cuba.webHostName>> и <<cuba.webPort,cuba.webPort>> для формирования уникального <<serverId,Server Id>>.

Механизм взаимодействия основан на библиотеке link:$$http://www.jgroups.org$$[JGroups]. Платформа содержит два конфигурационных файла для JGroups:

* `jgroups.xml` - стек протоколов основанный на UDP, пригодный для работы в локальной сети с разрешенными широковещательными сообщениями. Данная конфигурация используется по умолчанию.

* `jgroups_tcp.xml` - стек протоколов основанный на TCP, пригодный для работы в любой сети. Он требует явного указания адресов узлов кластера в параметрах `TCP.bind_addr` и `TCPPING.initial_hosts`. Для использования данной конфигурации настройте свойство приложения <<cuba.cluster.jgroupsConfig,cuba.cluster.jgroupsConfig>>.

Для настройки параметров JGroups для вашего окружения скопируйте подходящий файл `jgroups.xml` из корня архива `cuba-core-<version>.jar` в модуль *core* вашего проекта или в каталог `tomcat/conf/app-core`, и настройте его нужным образом.

Программный интерфейс для взаимодействия в кластере Middleware обеспечивает бин `ClusterManagerAPI`. Его можно использовать в приложении - см. JavaDocs и примеры использования в коде платформы.

