:sourcesdir: ../../../../source

[[uberjar_settings]]
==== UberJar Settings

*UberJAR Settings* page allows you to set up deployment to Uber JAR. After completing the setup, the {main_man_url}/build.gradle_buildUberJar.html[buildUberJar] task will be created in your `build.gradle`.

* *Build Uber JAR* - if checked, the `buildUberJar` task is configured in `build.gradle`.

* *Single Uber JAR* - if checked, the `buildUberJar` task creates a single Uber JAR from all application modules.

* *Logback configuration file* - a path relative to the project root to the `logback.xml` configuration file. Click *Generate* to create this file automatically.

* *Custom Jetty environment file* - a path relative to the project root to the `jetty-env.xml` configuration file to be used by the embedded Jetty server. Required field. Click *Generate* to create this file automatically.

* *App properties* - a set of application properties to define for this deployment. The properties will be added to the `/WEB-INF/local.app.properties` file inside the Uber JARs.

* *Core port, Web port, Portal port* fields allow you to set ports for the embedded servers of the corresponding application blocks. Not available if Single Uber JAR checked. Default port values are described in the {main_man_url}/build.gradle_buildUberJar.html[documentation]. You can also set ports when running the JARs using the `-port` command line argument.