:sourcesdir: ../../../source

[[rest_api_v2]]
=== REST API

The universal REST API provides the following functionality:

* CRUD operations on entities.
* Execution of predefined JPQL queries.
* Execution of service methods.
* Getting metadata (entities, views, enumerations, datatypes).
* Getting current user permissions (access to entities, attributes, specific permissions).
* Getting current user information (name, language, time zone, etc.).
* Uploading and downloading files.

REST API uses the OAuth2 protocol for authentication and supports anonymous access.

[TIP]
====
The detailed documentation for the API is written according to http://swagger.io/specification[Swagger specification] and is available at the following URL: {rest_swagger_url}.

Also, any running CUBA application exports the project-specific documentation, see <<rest_swagger,>>.
====

The <<rest_api_v2_usage_example>> cookbook section contains a lot of examples demonstrating REST API features in action.

Below we provide a formal description of some features and configuration options.

include::rest_api_v2/rest_api_v2_queries_config.adoc[]

include::rest_api_v2/rest_api_v2_services_config.adoc[]

include::rest_api_v2/rest_api_v2_data_model_versioning.adoc[]

include::rest_api_v2/rest_api_v2_cors.adoc[]

include::rest_api_v2/rest_api_v2_anonymous.adoc[]

include::rest_api_v2/rest_api_v2_settings.adoc[]

include::rest_api_v2/rest_api_v2_custom_controllers.adoc[]

include::rest_api_v2/rest_api_v2_security_constraints.adoc[]

include::rest_api_v2/rest_api_v2_persistent_token_store.adoc[]

include::rest_api_v2/rest_swagger.adoc[]

