:sourcesdir: ../../../../source

[[email_sending]]
==== Email Sending

The platform provides email sending facilities with the following features:

* Synchronous or asynchronous sending. In case of synchronous sending, the calling code waits till the message is sent to the SMTP server. In case of asynchronous sending, the message is persisted to the database and the control is returned immediately to the calling code. The actual sending is done later by a <<scheduled_tasks,scheduled task>>.

* Reliable tracking of message sending timestamp or errors in the database for both synchronous and asynchronous modes.

* User interface to search and view information about sent messages, including all message attributes and content, sending status and the number of attempts.

See an example of using this mechanism in the <<sending_emails_recipe,Sending Emails>> development recipe.

include::email_sending/email_sending_methods.adoc[]

include::email_sending/email_attachments.adoc[]

include::email_sending/email_sending_properties.adoc[]

