:sourcesdir: ../../../../source

[[entityImportExport]]
==== Export and Import Entities in JSON

The platform provides an API for exporting and importing graphs of entities in JSON format. It is available on Middleware via the `EntityImportExportAPI` interface and on the client tier via `EntityImportExportService`. These interfaces have an identical set of methods which are described below. The export/import implementation delegates to the `EntitySerializationAPI` interface which can also be used directly.

* `exportEntitiesToJSON()` - serializes a collection of entities to JSON.
+
[source, java]
----
include::{sourcesdir}/common/entityImportExportService_1.java[]
----

* `exportEntitiesToZIP()` - serializes a collection of entities to JSON and packs the JSON file into ZIP archive. In the following example, the ZIP archive is saved to the file storage using the <<fileLoader,FileLoader>> interface:
+
[source, java]
----
include::{sourcesdir}/common/entityImportExportService_2.java[]
----

* `importEntitiesFromJSON()` - deserializes the JSON and persists deserialized entities according to the rules, described by the `entityImportView` parameter (see JavaDocs on the `EntityImportView` class). If an entity is not present in the database, it will be created. Otherwise the fields of the existing entity that are specified in the `entityImportView` will be updated.

* `importEntitiesFromZIP()` - reads a ZIP archive that contains a JSON file, deserializes the JSON and persists deserialized entities like the `importEntitiesFromJSON()` method.
+
[source, java]
----
include::{sourcesdir}/common/entityImportExportService_3.java[]
----

