:sourcesdir: ../../../../source

[[folders_pane]]
==== Folders Panel

The folders panel provides quick access to frequently used information. It is a panel on the left side of the main application window containing a hierarchical structure of folders. Clicking on folders shows the corresponding system screens with certain parameters.

At the moment of writing, the panel is available for the *Web Client* only.

The platform supports three types of folders: _application folders_, _search folders_ and _record sets_. Application folders are displayed at the top of the panel as a separate folder tree. Search folders and record sets are displayed at the bottom of the panel in a combined tree. Folders support keyboard <<shortcuts,shortcuts>> if the <<cuba.web.foldersPaneEnabled,cuba.web.foldersPaneEnabled>> property is `true`.

* Application folders:

** Open screens with or without a <<gui_Filter,filter>>.

** The set of folders depend on the current user session. Folder visibility is defined by a Groovy script.

** Application folders can be created and changed only by users with special <<permissions,permissions>>.

** Folder headers may show the record count calculated by a Groovy script.

** Folder headers are updated on timer events, which means that record count and display style for each folder can be updated.

* Search folders:

** Open screens with a <<gui_Filter,filter>>.

** Search folders can be local or global, accessible only by the user who created them or by all users, respectively.

** Local folders can be created by any user, while global are created only by users with special permissions.

* Record sets:

** Open screens with a <<gui_Filter,filter>> containing a condition to select specific records by their identifiers.

** Record set content can be edited using the dedicated table <<gui_Action,actions>>: Add to set and Remove from set.

** Record sets are available only to the user who created them.

The following application properties can influence the functionality of the folder panel:

* <<cuba.web.foldersPaneEnabled,cuba.web.foldersPaneEnabled>>

* <<cuba.web.foldersPaneVisibleByDefault,cuba.web.foldersPaneVisibleByDefault>>

* <<cuba.web.foldersPaneDefaultWidth,cuba.web.foldersPaneDefaultWidth>>

* <<cuba.web.appFoldersRefreshPeriodSec,cuba.web.appFoldersRefreshPeriodSec>>

* <<cuba.web.showFolderIcons,cuba.web.showFolderIcons>>

include::folders_pane/application_folder.adoc[]

include::folders_pane/search_folder.adoc[]

include::folders_pane/record_set.adoc[]

