:sourcesdir: ../../../../source

[[myBatis]]
==== Integration with MyBatis

MyBatis framework offers wider capabilities for running SQL and mapping query results to objects than ORM <<nativeQuery,native query>> or <<queryRunner,QueryRunner>>.

Follow the steps below to set up integration with MyBatis in a CUBA project.

. Create UUID type handler class in the root package of the *core* module.
+
[source, java]
----
include::{sourcesdir}/features/MyBatis.java[]
----

. Create `mybatis.xml` configuration file in the *core* module next to <<spring.xml,spring.xml>> with a correct reference to `UUIDTypeHandler`:
+
[source, xml]
----
include::{sourcesdir}/features/MyBatis_2.xml[]
----

. Add the following beans into `spring.xml` file to use MyBatis in the project:
+
--
[source, xml]
----
include::{sourcesdir}/features/MyBatis.xml[]
----

The `sqlSessionFactory` bean provides the reference to the created `mybatis.xml`.

The `MapperLocations` parameter defines a path to `mapperLocations` mapping files (according to the rules of `ResourceLoader` Spring interface).
--

. Finally, add MyBatis dependencies to the `core` module in <<build.gradle,build.gradle>>:
+
[source, groovy]
----
compile('org.mybatis:mybatis:3.2.8')
compile('org.mybatis:mybatis-spring:1.2.5')
----

Below is an example of a mapping file for loading an instance of `Order` together with a related `Customer` and a collection of `Order` items:

[source, xml]
----
include::{sourcesdir}/features/mapper.xml[]
----

The following code can be used to retrieve query results from the example above:

[source, java]
----
try (Transaction tx = persistence.createTransaction()) {
    SqlSession sqlSession = AppBeans.get("sqlSession");
    Order order = (Order) sqlSession.selectOne("com.sample.sales.selectOrder", orderId);
    tx.commit();
}
----

