:sourcesdir: ../../../../source

[[pessimistic_locking]]
==== Pessimistic Locking

Pessimistic locking should be used when there is a high probability of simultaneous editing of a single entity instance. In such cases the standard <<optimistic_locking,optimistic locking>>, based on entity versioning, usually creates too many collisions.

Pessimistic locking explicitly locks an entity instance when it is opened in the <<screen_edit,editor>>. As a result, only one user can edit this particular entity instance in a given moment of time.

Pessimistic locking mechanism can also be used to manage simultaneous execution of arbitrary processes. The key benefit is that the locks are distributed, since they are replicated in the Middleware cluster. More information is available in JavaDocs for the `LockManagerAPI` and `LockService` interfaces.

Pessimistic locking can be enabled for any entity class on application development or production stage using *Administration > Locks > Setup* screen, or as follows:

* Insert a new record with the following field values into the *SYS_LOCK_CONFIG* table with the following field values:
+
--
** *ID* – an arbitrary UUID-type identifier.

** *NAME* – the name of the object to be locked. For an entity, it should be the name of its <<metaClass,meta class>>.

** *TIMEOUT_SEC* – lock expiration timeout in seconds.

Example:

[source, sql]
----
insert into sys_lock_config (id, create_ts, name, timeout_sec) values (newid(), current_timestamp, 'sales$Order', 300)
----
--

* Restart the server or call `reloadConfiguration()` method of the `app-core.cuba:type=LockManager` JMX bean.

Current state of locks can be tracked via the `app-core.cuba:type=LockManager` JMX bean or through the *Administration > Locks* screen. This screen also enables unlocking of any object.

