:sourcesdir: ../../../../source

[[docker_deployment]]
==== Развертывание в Docker

Данный раздел описывает порядок развертывания приложения CUBA в https://www.docker.com/[Docker®].

[TIP]
=====
Это руководство охватывает процесс развертывания проекта с использованием базы данных PostgreSQL.
=====

UberJAR – это простейший способ запустить приложение CUBA в режиме эксплуатации. Вы собираете единый all-in-one JAR-файл с помощью задачи Gradle <<build.gradle_buildUberJar>> и запускаете приложение из командной строки, используя команду `java`. Таким образом, нет необходимости использовать специальные веб-серверы или контейнеры сервлетов. Все параметры приложения определяются во время сборки, но могут быть переопределены при запуске.

В этом разделе показано, как настроить монолитную и распределенную конфигурации приложений с Docker контейнерами.

include::docker_deployment/single_jar_deployment.adoc[]

include::docker_deployment/distributed_jar_deployment.adoc[]

include::docker_deployment/docker_plugin.adoc[]

include::docker_deployment/heroku_container.adoc[]

