:sourcesdir: ../../../../source

[[uberjar_deployment]]
==== Развертывание UberJAR

UberJAR - это простейший способ запустить приложение CUBA в режиме эксплуатации. Вы собираете единый all-in-one JAR-файл с помощью задачи Gradle <<build.gradle_buildUberJar>> (см. также вкладку *Deployment settings > Uber JAR* в Studio) и запускаете приложение из командной строки, используя команду `java`:

[source,plain]
----
java -jar app.jar
----

Все параметры приложения определяются во время сборки, но могут быть переопределены при запуске (см. ниже). Порт веб-приложения по умолчанию - `8080`, и оно доступно по адресу `++http://host:8080/app++`. Если в проекте есть Polymer UI, он будет доступен по умолчанию по адресу `++http://host:8080/app-front++`.

Можно также собрать отдельные JAR файлы для Middleware и Web Client, и запустить их аналогично:

----
java -jar app-core.jar

java -jar app.jar
----

Порт веб-клиента по умолчанию - `8080`, он будет подключаться к middleware, использующему `localhost:8079`. Таким образом, выполнив эти две команды в двух разных терминалах Windows, вы сможете подключиться к веб-клиенту приложения по адресу `++http://localhost:8080/app++`.

Вы можете изменить параметры, определяемые во время сборки, передав свойства приложения через системные свойства Java. Кроме того, порты, имена контекстов и пути к конфигурационным файлам можно передавать в качестве аргументов командной строки.

Аргументы командной строки::
+
--
* `port` - задаёт порт, на котором будет работать встроенный HTTP-сервер. Например:
+
[source,plain]
----
java -jar app.jar -port 9090
----
+
Следует учесть, что при указании порта для блока core необходимо также задать свойство приложения <<cuba.connectionUrlList,cuba.connectionUrlList>> для клиентских блоков, указав соответствующие адрес Middleware:
+
[source,plain]
----
java -jar app-core.jar -port 7070

java -Dcuba.connectionUrlList=http://localhost:7070/app-core -jar app.jar
----

* `contextName` - имя веб-контекста для данного блока приложения. Например, чтобы получить доступ к веб-клиенту по адресу `++http://localhost:8080/sales++`, выполните следующую команду:
+
[source,plain]
----
java -jar app.jar -contextName sales
----

* `frontContextName` - имя веб-контекста для Polymer UI (имеет смысл для единого, web или portal JAR файлов).

* `portalContextName` - имя веб-контекста для модуля portal, работающего в едином JAR.

* `jettyEnvPath` - путь к файлу окружения Jetty, который переопределяет настройки, заданные внутри JAR параметром сборки `coreJettyEnvPath`. Может быть как абсолютным путём, так и относительным рабочего каталога.

* `jettyConfPath` - путь к файлу конфигурации сервера Jetty, который переопределяет настройки, заданные внутри JAR параметром сборки `webJettyConfPath/coreJettyConfPath/portalJettyConfPath`. Может быть как абсолютным путём, так и относительным рабочего каталога.
--

Домашний каталог приложения::
+
--
По умолчанию <<app_home,домашним каталогом>> является рабочий каталог приложения. Это означает, что <<app_dirs,каталоги приложения>> будут созданы в каталоге, из которого приложение запущено. Домашний каталог может быть также указан в системном свойстве `app.home`. Например, чтобы иметь домашний каталог в `/opt/app_home`, необходимо указать следующее в командной строке:

[source,plain]
----
java -Dapp.home=/opt/app_home -jar app.jar
----
--

Логирование::
+
--
Если необходимо изменить настройки логирования, заданные внутри JAR, то можно передать системное свойство Java `logback.configurationFile` с URL для загрузки внешнего конфигурационного файла, например:

[source,plain]
----
java -Dlogback.configurationFile=file:./logback.xml -jar app.jar
----

Здесь подразумевается, что файл `logback.xml` расположен в папке, из которой запускается приложение.

Для правильного задания <<log_dir,каталога логов>> убедитесь, что свойство `logDir` в `logback.xml` указывает на подкаталог `logs` домашнего каталога приложения:

[source, xml]
----
include::{sourcesdir}/deployment/log_dir_1.xml[]
----
--

Остановка приложения::
+
--
Корректно остановить приложение можно следующими способами:

* Нажав *Ctrl+C* в окне терминала, в котором работает приложение.

* Выполнив `kill <PID>` в Unix-like системе.

* Послав ключ (последовательность символов) остановки на порт, указанный в командной строке запущенного приложения. Следующие аргументы командной строки имеют отношение к остановке:

** `stopPort` - порт прослушивания и посылки ключа остановки.
** `stopKey` - ключ остановки. Если не указан, используется `SHUTDOWN`.
** `stop` - остановить другой процесс отсылкой ключа.

Например:

[source,plain]
----
# Start application 1 and listen to SHUTDOWN key on port 9090
java -jar app.jar -stopPort 9090

# Start application 2 and listen to MYKEY key on port 9090
java -jar app.jar -stopPort 9090 -stopKey MYKEY

# Shutdown application 1
java -jar app.jar -stop -stopPort 9090

# Shutdown application 2
java -jar app.jar -stop -stopPort 9090 -stopKey MYKEY
----
--

include::uberjar_deployment/uberjar_https.adoc[]

