:sourcesdir: ../../../../source

[[war_deployment]]
==== Развертывание WAR в Jetty

Рассмотрим пример сборки WAR-файлов и их развертывания на сервере *Jetty*.

Мы будем использовать следующую структуру каталогов:

* `C:\work\jetty-home\` - дистрибутив Jetty;
* `C:\work\jetty-base\` - директория конфигурации Jetty, в ней хранятся конфигурационные файлы Jetty, дополнительные библиотеки и веб-приложения.
* `C:\work\app_home\` - <<app_home,домашний каталог>> CUBA приложения.

. Используйте диалог *Дерево проектов CUBA > Project > Deployment > WAR Settings* в Studio или вручную добавьте в конец <<build.gradle,build.gradle>> задачу сборки <<build.gradle_buildWar,buildWar>>:
+
[source, groovy]
----
include::{sourcesdir}/deployment/warDeployment_1.groovy[]
----
+
В данном случае собирается два WAR-файла, отдельно для блоков Middleware и Web Client.

. Запустите сборку, выбрав `buildWar` через командную строку (подразумевается что Gradle wrapper создан заранее):
+
[source, plain]
----
gradlew buildWar
----
+
В результате в подкаталоге `build\distributions\war` проекта будут созданы файлы `app-core.war` и `app.war`.

. Создайте <<app_home,домашний каталог приложения>> на сервере, например, `c:\work\app_home`.
. Скопируйте файл `logback.xml` из локального сервера Tomcat (под-каталог проекта `deploy/tomcat/conf`) в домашний каталог приложения (`c:\work\app_home`) и отредактируйте свойство `logDir` в этом файле:
+
[source, xml]
----
<property name="logDir" value="${app.home}/logs"/>
----
. Загрузите и установите сервер Jetty, например в каталог `c:\work\jetty-home`. Данный пример тестировался на версии `jetty-distribution-9.4.22.v20191022.zip`.

. Создайте каталог `c:\work\jetty-base`, откройте в нем командную строку и выполните:
+
[source, plain]
----
java -jar c:\work\jetty-home\start.jar --add-to-start=http,jndi,deploy,plus,ext,resources
----

. Создайте файл `c:\work\jetty-base\app-jetty.xml`, содержащий определение пула соединений к базе данных. Содержимое файла для БД PostgreSQL должно основываться на следующем шаблоне:
+
[source, xml]
----
include::{sourcesdir}/deployment/warDeployment_2.xml[]
----
+
Файл `app-jetty.xml` для MS SQL должен соответствовать следующему шаблону:
+
[source, xml]
----
include::{sourcesdir}/deployment/warDeployment_5.xml[]
----

. Скачайте следующие JAR-файлы, необходимые для функционирования пула соединений к БД и скопируйте их в папку `c:\work\jetty-base\lib\ext`. Два из них можно взять из проектного под-каталога `deploy\tomcat\shared\lib`:
+
[source, plain]
----
commons-pool2-2.6.2.jar
commons-dbcp2-2.7.0.jar
commons-logging-1.2.jar
----

. Скопируйте файл `start.ini` из дистрибутива Jetty в каталог `c:\work\jetty-base`. Добавьте следующий текст в начало файла `c:\work\jetty-base\start.ini`:
+
[source, plain]
----
include::{sourcesdir}/deployment/warDeployment_3.ini[]
----

. Скопируйте JDBC-драйвер используемой базы данных в каталог `c:\work\jetty-base\lib\ext`. Файл драйвера можно взять из каталога `deploy\tomcat\lib` проекта. В случае PostgreSQL это файл `postgresql-42.2.5.jar`.

. Скопируйте файлы WAR в каталог `c:\work\jetty-base\webapps`.

. Откройте командную строку в каталоге `c:\work\jetty-base` и выполните:
+
[source, plain]
----
java -jar c:\work\jetty-home\start.jar
----

. Откройте `++http://localhost:8080/app++` в веб-браузере.

