:sourcesdir: ../../../../source

[[qs_contract_edit_controller]]
==== Контроллер экрана редактирования договора

Откройте экран `ContractEdit` и замените его содержимое на следующий код:

[source,java]
----
include::{sourcesdir}/quickstart/ContractEdit.java[]
----

Рассмотрим код контроллера более подробно.

`ProcessActionsFragment` − это стандартный фрагмент для отображения кнопок доступных в данный момент процессных действий. Во время инициализации фрагмента по двум параметрам (код процесса и сущность) ищется связанный экземпляр `ProcInstance`. Если процесс не находится, то создается новый `ProcInstance`, и фрагмент отображает кнопку запуска процесса. Если связанный с сущностью процесс найден, то проверяется, имеется ли незавершенная процессная задача для текущего пользователя, и если да, то отображаются кнопки завершения данной задачи. Подробнее о `ProcActionsFragment` см. <<proc_actions_fragment>>.

В контроллере редактора договора инициализация фрагмента процессных действий происходит в методе `onBeforeShow()`. Самая важная часть метода − вызов `init(PROCESS_CODE, getEditedEntity())`. Константа `PROCESS_CODE` хранит код процесса (`contractApproval` − это значение мы видели при развёртывании процесса, см. <<qs_process_model_deployment>>). Второй аргумент `getEditedEntity()` − текущий договор.

Стандартная инициализация фрагмента (`standard()`) делает следующее:

* Инициализирует стандартные предикаты для действий запуска процесса и завершения задачи. Предикаты вызывают коммит редактора договора.

* Инициализирует стандартные слушатели, вызываемые после завершения процессного действия. Данные слушатели отображают уведомления ("Процесс запущен", "Действие выполнено", и т.п.), а также обновляют `procActionsFragment`.

