:sourcesdir: ../../source

[[overview]]
== Обзор дополнения

Дополнение BI предоставляет следующую функциональность:

* Универсальные шаблоны экранов для регистрации и запуска отчётов Pentaho. Доступ к зарегистрированным отчётам можно ограничить с помощью ролей в подсистеме безопасности CUBA.

* Визуальный компонент для встраивания отчётов Pentaho в любой экран приложения.

* Технология единого входа (SSO) между приложениями CUBA и Pentaho, которая работает следующим образом:

** Имя пользователя в приложении CUBA и Pentaho должно совпадать.

** Когда пользователь открывает отчёт, приложение создаёт тикет и прикрепляет имя пользователя и тикет к запросу на Pentaho. Тикет хранится в сессии пользователя.

** <<setup_pentaho,Плагин>> для CUBA на сервере Pentaho обнаруживает тикет, пришедший вместе с запросом, и в ответном запросе к приложению проверяет, действителен ли тикет.

** Если тикет действителен, плагин авторизует пользователя на сервере Pentaho, применив к нему роли, настроенные для этого пользователя в Pentaho.

