:sourcesdir: ../../../source

[[user_task]]
=== Пользовательская задача (User Task)

Для определения пользователя, на которого будет назначена задача, необходимо в свойстве *Process role* элемента *User task* выбрать одну из процессных ролей, определенных в модели. При достижении процессом задачи среди участников процесса (ProcActor) будут найдены участники с указанной процессной ролью, и задача будет назначена на них.

.Задание процессной роли для задачи

[source, xml]
----
<userTask id="managerApproval" name="Manager approval">
    <extensionElements>
        <cuba:procRole>manager</cuba:procRole> 
    </extensionElements>
</process>
----

Если необходимо, чтобы задача была назначена одновременно нескольким пользователям, то в свойстве *Multi-instance type* элемента *User task* необходимо выбрать значение `Parallel` или `Sequential`.

Задать участника возможно и не указывая его заранее в объекте ProcActor, а задав в свойстве *assignee* элемента User Task. Свойство может содержать строку с идентификатором пользователя CUBA: `da8159cc-757f-7f59-6579-7f629ac02f72`, переменную процесса, которая содержит строку с идентификатоом пользователя: `${varialbeName}`, или выражение вызова сервиса, который возвращает строку с идентификатором пользователя: `${someService.getSomeUserId()}`. При этом свойство *procRole* элемета UserTask должно быть заполнено. Когда процесс достигает подобной задачи, сначала ищется объект ProcActor с указанным пользователем и процессной ролью. Если ProcActor не найден, будет создан новый экземпляр ProcActor. Для задания свойства *assignee* в редакторе моделей выделите элемент User Task, кликните на ссылку *Show advanced properties*, откройте редактор свойства *Assignments* и в появившемся диалоге заполните поле *Assignee*.

Также возможен вариант, когда задача не должна быть сразу назначена на пользователя, а должна появиться в списке доступных, и один из пользователей должен забрать задачу себе. Для определения такой задачи необходимо установить флажок *Claim allowed*. В этом случае задача появится в списке доступных у всех участников процесса с ролью, заданной в свойстве *Process role*.

.Задача без конкретного участника
[source, xml]
----
<userTask id="managerApproval" name="Manager approval">
    <extensionElements>
        <cuba:claimAllowed>true</cuba:claimAllowed>
    </extensionElements>
</process>
----

