= Платформа CUBA. Отображение диаграмм и карт
:toc: left
:toc-title: Содержание
:sectnums:
:linkcss:
:source-highlighter: pygments
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:docinfo:
:sectlinks:
:sectanchors:
:icons: font
:lang: ru
:hide-uri-scheme:

[[preface]]
[preface]
== Предисловие

Данный документ содержит описание двух функциональных модулей платформы CUBA - подсистем отображения диаграмм и географических карт. Эти подсистемы реализованы в одном базовом проекте платформы - *charts*, и могут быть подключены в прикладной проект только вместе. 

Функциональность отображения диаграмм и карт в настоящий момент доступна только в веб клиенте приложения.

[[audience]]
=== Целевая аудитория

Данное руководство предназначено для разработчиков приложений на платформе CUBA. Предполагается, что читатель ознакомлен с Руководством по разработке приложений, доступным по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

[[additional_info]]
=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

Подсистема отображения диаграмм платформы CUBA основана на библиотеке *AmCharts*, поэтому знакомство с ее устройством будет полезным. См. link:$$http://www.amcharts.com/$$[www.amcharts.com/]. 

[[feedback]]
=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, обратитесь, пожалуйста, в службу поддержки по адресу link:$$https://ru.cuba-platform.com/support/topics$$[ru.cuba-platform.com/support/topics]. 

При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска. 

include::chart.adoc[]

include::map.adoc[]

