= Платформа CUBA. Отображение диаграмм и карт
:toc: left
:toc-title: Содержание
:appendix-caption: Приложение
:toclevels: 6
:sectnumlevels: 6
:linkcss:
:stylesheet: cuba.css
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: ru
:revnumber: 6.3
:version-label: Версия
:revremark: Copyright (c) 2016 Haulmont (www.haulmont.com)
:figure-caption: Рисунок

:!sectnums:

[[preface]]
[preface]
== Предисловие

Данный документ содержит описание двух функциональных модулей платформы CUBA - подсистем отображения диаграмм и географических карт. Эти подсистемы реализованы в одном компоненте платформы - *charts*, и могут быть подключены в прикладной проект только вместе.

Функциональность отображения диаграмм и карт в настоящий момент доступна только в веб клиенте приложения.

[[audience]]
=== Целевая аудитория

Данное руководство предназначено для разработчиков приложений на платформе CUBA. Предполагается, что читатель ознакомлен с Руководством по разработке приложений, доступным по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

[[additional_info]]
=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

Подсистема отображения диаграмм платформы CUBA основана на библиотеке *AmCharts*, поэтому знакомство с ее устройством будет полезным. См. link:$$http://www.amcharts.com/$$[www.amcharts.com/]. 

[[feedback]]
=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, обратитесь, пожалуйста, в службу поддержки по адресу link:$$https://www.cuba-platform.ru/support/topics$$[www.cuba-platform.ru/support/topics].

При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска. 

:sectnums:

include::chart.adoc[]

include::map.adoc[]

include::pivot_table.adoc[]

