:sourcesdir: ../../../../../source

[[session_attr]]
===== Session Attributes

An access group can define <<userSession,session>> attributes for the users belonging to this group. These attributes can be used in the application code and in <<constraints,constraints>>.

When a user logs in, all the attributes set for the user's group and for all the groups up the hierarchy will be placed into the user session. If an attribute is found in several levels of the hierarchy, the uppermost group value will be used. Hence, overriding the attribute values at the lower levels of the hierarchy is impossible. The framework prints a warning message to the server <<logging,log>> if it encounters an attempt to override an attribute value.

Session attributes can be defined together with constraints in a class that is used to define the <<groups,access group>>. The class must be located in the `core` module. Below is an example of an access group that defines the `accessLevel` session attribute with value `1`:

[source,java]
----
include::{sourcesdir}/security/session_attr_1.java[]
----

Session attributes can also be defined at run time in the *Access Groups* screen: select the group to create the attribute for and go to the *Session Attributes* tab.

Session attributes can be accessed in the application code through the `UserSession` object:

[source, java]
----
@Inject
private UserSessionSource userSessionSource;
...
Integer accessLevel = userSessionSource.getUserSession().getAttribute("accessLevel");
----

Session attributes can be used in the <<constraints,constraints>> as JPQL parameters with the `session$` prefix:

[source,plain]
----
{E}.accessLevel = :session$accessLevel
----


