:sourcesdir: ../../../../../../source

[[datatype_format_strings]]
====== Datatype Format Strings

Locale-dependent parsing formats are provided in the <<main_message_pack,main messages pack>> of the application or its <<app_components,components>>. They follow the logic of standard Java SE classes, such as `DecimalFormat` (see link:$$https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html$$[https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html]) or `SimpleDateFormat` (see link:$$https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html$$[https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html]).

The formats should be provided in the strings with the following keys:

* `numberDecimalSeparator` – decimal separator for numeric types.
+
[source, properties]
----
# comma as decimal separator
numberDecimalSeparator=,
----

* `numberGroupingSeparator` – thousands separator for numeric types.
+
[source, properties]
----
# space as thousands grouping separator
numberGroupingSeparator = \u0020
----

* `integerFormat` – format for `Integer` and `Long` types.
+
[source, properties]
----
# disable thousands grouping separator for integers
integerFormat = #0
----

* `doubleFormat` – format for `Double` type.
+
[source, properties]
----
# comma as thousands grouping separator, period as decimal separator, rounding up to three digits after decimal separator
doubleFormat=#,##0.###
----

* `decimalFormat` – format for `BigDecimal` type.
+
[source, properties]
----
# always display two digits after decimal separator, e.g. for currencies
decimalFormat = #,##0.00
----

* `dateTimeFormat` – format for `java.util.Date` type.
+
[source, properties]
----
# Russia date+time format
dateTimeFormat = dd.MM.yyyy HH:mm
----

* `dateFormat` – format for `java.sql.Date` type.
+
[source, properties]
----
# United States date format
dateFormat = MM/dd/yyyy
----

* `timeFormat` – format for `java.sql.Time` type.
+
[source, properties]
----
# United States time format (e.g. 12:40 PM)
timeFormat=h:mm a
----

* `trueString` – string corresponding to `Boolean.TRUE`.
+
[source, properties]
----
# alternative displaying for boolean values
trueString = yes
----

* `falseString` – string corresponding to `Boolean.FALSE`.
+
[source, properties]
----
# alternative displaying for boolean values
falseString = no
----

[TIP]
====
Studio allows you to set format strings for languages used in your application. Edit *Project Properties*, click the button in the *Available locales* field, then click *Show data format strings*.
====

Format strings for a locale can be obtained using the `FormatStringsRegistry` bean.

