:sourcesdir: ../../../../../source

[[db_update_in_prod_cmdline]]
===== Инициализация и обновление БД из командной строки

Скрипты создания и обновления БД могут быть запущены из командной строки с помощью класса `com.haulmont.cuba.core.sys.utils.DbUpdaterUtil`, входящего в состав блока *Middleware* платформы. При запуске должны быть переданы следующие аргументы:

* `dbType` – <<dbms_types,тип СУБД>>, возможные значения: postgres, mssql, oracle, mysql.

* `dbVersion` – <<dbms_version,версия СУБД>> (необязательный аргумент).

* `dbDriver` - имя класса JDBC-драйвера (необязательный аргумент). Если не передан, имя класса драйвера определяется исходя из `dbType`.

* `dbUser` - имя пользователя БД.

* `dbPassword` - пароль пользователя БД.

* `dbUrl` - URL для подключения к БД. Для выполнения первичной инициализации указанная база данных должна быть пустой, никакой предварительной очистки ее не производится.

* `scriptsDir` - абсолютный путь к каталогу, содержащему скрипты в стандартной структуре. Как правило, используется <<db_dir,каталог скриптов базы данных>>, поставляемый с приложением.

* одна из возможных команд:

** `create` - выполнить инициализацию базы данных.

** `check` - отобразить список невыполненных скриптов обновления.

** `update` - выполнить обновление базы данных.

Пример скрипта для Linux, запускающего `DbUpdaterUtil`:

[source, bash]
----
include::{sourcesdir}/database/dbupdate.sh[]
----

Данный скрипт рассчитан на работу с БД с именем `mydb`, расположенной на локальном сервере PostgreSQL. Скрипт должен быть расположен в каталоге `bin` сервера Tomcat, и запускаться с параметрами `{имя пользователя}`, `{пароль}`, `{команда}`, например:

[source]
----
./dbupdate.sh cuba cuba123 update
----

Ход выполнения скриптов отображается в консоли. При возникновении ошибок обновления следует поступать так же, как описано в предыдущем разделе для механизма автоматического обновления.

[WARNING]
====
При обновлении БД из командной строки имеющиеся Groovy-скрипты запускаются, но реально отрабатывает только их основная часть. По причине отсутствия контекста сервера PostUpdate-часть игнорируется с выдачей в консоль соответствующего сообщения.
====

