:sourcesdir: ../../../../../source

[[transaction_listeners]]
===== Transaction Listeners

Transaction listeners are designed to react on transaction lifecycle events. Unlike <<entity_listeners,entity listeners>>, they are not tied to an entity type and invoked for each transaction.

A listener is a <<managed_beans,managed bean>> implementing one or both `BeforeCommitTransactionListener` and `AfterCompleteTransactionListener` interfaces.

BeforeCommitTransactionListener::
+
--
`beforeCommit()` method is called before transaction commit after all <<entity_listeners,entity listeners>> if the transaction is not read-only. The method accepts a current <<entityManager,EntityManager>> and a collection of entities in the current persistence context.

The listener can be used to enforce complex business rules involving multiple entities. In the following example, the `amount` attribute of the `Order` entity must be calculated based on `discount` value located in the order, and `price` and `quantity` of `OrderLine` entities constituted the order.

[source,java]
----
include::{sourcesdir}/middleware/tx_listener_1.java[]
----
--

AfterCompleteTransactionListener::
+
--
`afterComplete()` method is called after transaction is completed. The method accepts a parameter indicating whether the transaction was successfully committed and a collection of detached entities contained in the persistence context of the completed transaction.

Usage example:

[source,java]
----
include::{sourcesdir}/middleware/tx_listener_2.java[]
----
--

