:sourcesdir: ../../../../../source

[[transactions_prog]]
===== Programmatic Transaction Management

Programmatic transaction management is done using the `com.haulmont.cuba.core.Transaction` interface. A reference to it can be obtained via the `createTransaction()` or `getTransaction()` methods of the <<persistence,Persistence>> infrastructure interface.

The `createTransaction()` method creates a new transaction and returns the `Transaction` interface. Subsequent calls of `commit()`, `commitRetaining()`, `end()` methods of this interface control the created transaction. If at the moment of creation there was another transaction, it will be suspended and resumed after the completion of the newly created one.

The `getTransaction()` method either creates a new transaction or attaches to an existing one. If at the moment of the call there is an active transaction, then the method completes successfully, but subsequent calls of `commit()`, `commitRetaining()`, `end()` have no influence on the existing transaction. However calling `end()` without a prior call to `commit()` will mark current transaction as `RollbackOnly`.

Examples of programmatic transaction management:

[source, java]
----
include::{sourcesdir}/middleware/transactions_1.java[]
----

`Transaction` interface has also the `execute()` method accepting an action class or a lambda expression. The action will be performed in the transaction. This enables organizing transaction management in functional style, for example:

[source, java]
----
include::{sourcesdir}/middleware/transactions_2.java[]
----

Keep in mind that `execute()` method of a given instance of `Transaction` may be called only once because the transaction ends after the action code is executed.

