:sourcesdir: ../../../../../source

[[transactions_interaction]]
===== Examples of Transactions Interaction

Rollback of a Nested Transaction::
+
--
If a nested transaction was created via `getTransaction()` and rolled back, then commit of the enclosing transaction will be impossible. For example: 

[source, java]
----
include::{sourcesdir}/middleware/transactions_3.java[]
----

If the transaction in `methodB()` is created with `createTransaction()` instead, then rolling it back will have no influence on the enclosing transaction in `methodA()`.
--

Reading and Modifying Data in a Nested Transaction::
+
--
Let us first have a look at a dependent nested transaction created using `getTransaction()`: 

[source, java]
----
include::{sourcesdir}/middleware/transactions_4.java[]
----

Now, let us have a look at the same example with an independent nested transaction created with `createTransaction()`:

[source, java]
----
include::{sourcesdir}/middleware/transactions_5.java[]
----

In the last example, the exception at point (8) will only occur if the entity supports optimistic locking, i.e. if it implements `Versioned` interface.
--

