:sourcesdir: ../../../../../source

[[rest_api_v2_ex_service_get]]
===== Service Method Invocation (GET)

Suppose there is an `OrderService` <<services, service>> in the system. The implementation looks as follows:

[source, java]
----
include::{sourcesdir}/features/OrderServiceBean.java[]
----

Before the execution with the REST API a service method invocation must be allowed in the <<rest_api_v2_services_config, configuration file>>. The `rest-services.xml` file must be created in the main package of the *web* module (e.g. `com.company.sales`). Then the file must be defined in the application properties file of the *web* module (web-app.properties).

[source, properties]
----
cuba.rest.servicesConfig = +com/company/sales/rest-services.xml
----

`rest-services.xml` content:

[source, xml]
----
include::{sourcesdir}/rest/sales-rest-services.xml[]
----

To invoke the service method the following *GET* request must be executed:

`\http://localhost:8080/app/rest/v2/services/sales_OrderService/calculatePrice?orderNumber=00001`

The request URL parts:

* `sales_OrderService` - a service name.
* `calculatePrice` - a method name.
* `orderNumber` - an argument name with the value.

An OAuth token must be put in the `Authorization` header with the `Bearer` type.

A service method may return a result of simple datatype, an entity, an entities collection or a serializable POJO. In our case a BigDecimal is returned, so the response body contains just a number:

  39.2

