:sourcesdir: ../../../../../source

[[opening_screens]]
===== Открытие экранов

[[screens_intf]]
С помощью интерфейса Screens::
+
--
Интерфейс `Screens` позволяет создавать и отображать экраны всех типов.

Предположим, у нас есть экран для демонстрации сообщения с особым форматированием:

.Контроллер экрана
[source, java]
----
include::{sourcesdir}/gui/screens/screens_1.java[]
----

.XML-дескриптор экрана
[source, xml]
----
include::{sourcesdir}/gui/screens/screens_1.xml[]
----

В этом случае мы можем создать и открыть его из другого экрана следующим образом:

[source, java]
----
include::{sourcesdir}/gui/screens/screens_2.java[]
----

Обратите внимание, что мы сначала создаём экземпляр экрана, передаём в него параметр, а затем отображаем экран.

Если экран не требует передачи параметров из вызывающего кода, его можно создать и открыть одной строкой:

[source, java]
----
include::{sourcesdir}/gui/screens/screens_3.java[]
----

[WARNING]
====
`Screens` не является Spring-бином, поэтому его можно только инжектировать в контроллер экрана или получить его с помощью статического метода `ComponentsHelper.getScreenContext(component).getScreens()`.
====
--

[[screenBuilders]]
С помощью бина ScreenBuilders::
+
--
Бин `ScreenBuilders` позволяет открывать все типы экранов с различными параметрами.

Одной из часто встречающихся задач является необходимость выполнить некоторый код после закрытия вызываемого экрана. Ниже приведён пример использования метода `withAfterCloseListener()` при открытии произвольного экрана:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_withAfterCloseListener.java[]
----

Далее мы рассмотрим работу с экранами редактирования и выбора сущностей.

Пример открытия редактора по умолчанию для сущности `Customer`:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor.java[]
----

В данном примере редактор изменит экземпляр сущности `Customer`, но вызывающий экран не получит назад обновлённую сущность.

Часто требуется отредактировать сущность, отображаемую, к примеру, компонентом `Table` или `DataGrid`. В этом случае следует использовать другую форму вызова редактора, она короче и позволяет автоматически обновить исходный экземпляр в таблице:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_2.java[]
----

Чтобы создать новый экземпляр сущности и открыть экран его редактирования, достаточно вызвать метод `newEntity()` builder'а:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_3.java[]
----

[TIP]
====
Редактор сущности по умолчанию определяется по следующей схеме:

. Если существует экран редактирования с аннотацией <<PrimaryEditorScreen_annotation,@PrimaryEditorScreen>>, будет использован он.
. Если такого экрана нет, будет использован экран с идентификатором вида `++{entity_name}.edit++` (например, `sales_Customer.edit`).
====

Builder предоставляет множество методов для передачи дополнительных параметров в открываемый экран. К примеру, следующий код создаёт сущность, сначала инициализируя новый экземпляр, в конкретном экране редактирования, открываемом в режиме диалогового окна:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_4.java[]
----

Экраны выбора сущностей также можно открывать с различными параметрами.

Пример открытия экрана выбора по умолчанию для сущности `User`:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup.java[]
----

Если нужно установить выбранную сущность в качестве значения поля, используйте краткую форму вызова:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_2.java[]
----

[TIP]
====
Экран выбора сущности по умолчанию определяется по следующей схеме:

. Если существует экран выбора с аннотацией <<PrimaryLookupScreen_annotation,@PrimaryLookupScreen>>, будет использован он.
. Если такого экрана нет, будет использован экран с идентификатором вида `++{entity_name}.lookup++` (например, `sales_Customer.lookup`).
. Если и такого экрана нет, будет использован экран с идентификатором вида `++{entity_name}.browse++` (например, `sales_Customer.browse`).
====

Как и в случае с экранами редактирования, вы можете использовать методы builder'а для передачи дополнительных параметров в открываемые экраны. Например, следующий код поможет выбрать сущность `User` в конкретном экране выбора, открываемом в режиме диалогового окна:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_3.java[]
----
--