:sourcesdir: ../../../../../source

[[screen_descriptors]]
===== XML-дескриптор экрана

Дескриптор экрана - это файл формата XML, декларативно описывающий <<gui_vcl,визуальные компоненты>>, <<gui_data,компоненты данных>> и некоторые параметры экрана.

Пример:
[source, xml]
----
include::{sourcesdir}/gui/descriptor_example.xml[]
----

Схема XML доступна по адресу {xsd_url}/screen/window.xsd.

Дескриптор содержит корневой элемент `window`.

Атрибуты корневого элемента:

* `class` − имя класса <<screen_controller,контроллера>>.

* `messagesPack` − <<message_packs,пакет сообщений>> данного экрана по умолчанию. Он будет использован при получении локализованных строк без указания пакета из XML-дескриптора и из контроллера методом `getMessage()`.

* `caption` − заголовок экрана, может содержать <<messageTools.loadString,ссылку на сообщение>> из вышеуказанного пакета, например,
+
[source, properties]
----
caption="msg://credits"
----

* `focusComponent` − идентификатор компонента, который получит фокус ввода при отображении экрана.

Элементы дескриптора:

* `data` − описывает <<gui_data,компоненты данных>> экрана.

* `dialogMode` - определяет параметры геометрии и поведения экрана при открытии его в виде диалогового окна.
+
--
Атрибуты `dialogMode`:

** `closeable` - определяет наличие в диалоговом окне кнопки закрытия. Возможные значения: `true`, `false`.

** `closeOnClickOutside` - определяет возможность закрыть окно кликом по окружающей области, если диалог открыт в модальном режиме. Возможные значения: `true`, `false`.

** `forceDialog` - указывает, что экран должен всегда открываться в режиме диалога, независимо от того, какой `WindowManager.OpenType` был выбран в вызывающем коде. Возможные значения: `true`, `false`.

** `height` - устанавливает высоту диалогового окна.

** `maximized` - если выбрано значение `true`, диалог будет развёрнут во весь экран. Возможные значения: `true`, `false`.

** `modal` - устанавливает модальный режим диалогового окна. Возможные значения: `true`, `false`.

** `positionX` - задаёт положение левого верхнего угла диалога по оси `x`.

** `positionY` - задаёт положение левого верхнего угла диалога по оси `y`.

** `resizable` - определяет возможность пользователя изменять размеры диалога. Возможные значения: `true`, `false`.

** `width` - устанавливает ширину диалогового окна.

Пример использования `dialogMode`:

[source, xml]
----
include::{sourcesdir}/gui/dialogs_4.xml[]
----
--

* `actions` – определяет список <<gui_Action,действий>> данного экрана.

* `timers` – определяет список <<gui_Timer,таймеров>> данного экрана.

* `layout` − корневой элемент компоновки экрана.