:sourcesdir: ../../../../../source

[[war_settings]]
===== WAR Settings

*WAR Settings* page allows you to set up the deployment to WAR file. After completing the setup, the {main_man_url}/build.gradle_buildWar.html[buildWar] task will be created in your `build.gradle`.

* *Build WAR* - if checked, the `buildWar` task is configured in `build.gradle`.

* *Include JDBC driver* - whether JDBC driver should be included in WAR file.

* *Include Tomcat's context.xml* - whether `context.xml` (Tomcat deployment descriptor) should be included in WAR file.

* *Custom context.xml path* - a path relative to the project root to the `context.xml` Tomcat deployment descriptor. Enabled if *Include Tomcat's context.xml* is checked. Click *Generate* to create this file automatically.

* *Single WAR for Middleware and Web Client* - whether to build a single WAR comprising the Middleware and Web Client application blocks.

* *Custom web.xml path* is the file to be used as a special `web.xml` of the single WAR. Click *Generate* to create this file automatically.

* *Logback configuration file* - a path relative to the project root to the `logback.xml` configuration file. Click *Generate* to create this file automatically.

* *App properties* - a set of application properties to define for this deployment. The properties will be added to the `/WEB-INF/local.app.properties` file inside the WAR.