:sourcesdir: ../../../../../../source

[[config_interface_property_types]]
====== Property Types

The following property types are supported in the platform out-of-the-box:

* `String`, primitive types and their object wrappers (`boolean`, `Boolean`, `int`, `Integer`, etc.)

* `enum`. The property value is stored in a file or in the database as the value name of the enumeration.
+

If the enum implements the `EnumClass` interface and has the static `fromId()` method for getting a value by an identifier, you can specify that the enum identifier should be stored instead of value with the `@EnumStore` annotation. For example:
+
[source, java]
----
include::{sourcesdir}/common/configinterface_8.java[]
----

* Persistent <<data_model,entity>> classes. When accessing a property of the entity type, the instance defined by the property value is loaded from the database.

To support arbitrary types, use `TypeStringify` and `TypeFactory` classes to convert the value to/from a string and specify these classes for the property with `@Stringify` and `@Factory` annotations.

Let us consider this process using the `UUID` type as an example.

* Create class `com.haulmont.cuba.core.config.type.UuidTypeFactory` inherited from `com.haulmont.cuba.core.config.type.TypeFactory` and implement the following method in it:
+
[source, java]
----
include::{sourcesdir}/common/configinterface_4.java[]
----

* There is no need to create `TypeStringify` as `toString()` method is sufficient in this case. 

* Annotate the property in the configuration interface:
+
[source, java]
----
include::{sourcesdir}/common/configinterface_5.java[]
----

The platform provides `TypeFactory` implementations for the following types:

* `UUID` – `UuidTypeFactory`, as described above.

* `java.util.Date` – `DateFactory`. Date value must be specified in `yyyy-MM-dd HH:mm:ss.SSS` format, for example:
+
[source, properties]
----
cuba.test.dateProp = 2013-12-12 00:00:00.000
----

* `List<Integer>` (the list of integers) – `IntegerListTypeFactory`. The property value must be specified in the form of numbers, separated by spaces, for example:
+
[source, properties]
----
cuba.test.integerListProp = 1 2 3
----

* `List<String>` (the list of strings) – `StringListTypeFactory`. The property value must be specified as a list of strings separated by "|" sign, for example:
+
[source, properties]
----
cuba.test.stringListProp = aaa|bbb|ccc
----

