:sourcesdir: ../../../../../../source

[[cdp_xml_descriptor]]
====== Screen XML Descriptor

Open the *Screens* tab in CUBA Studio and create a screen in the *web* module. Enter the value `com/company/sampler/web/screens/stackedarea-chart.xml` in the *Descriptor* field. The fields - *Id*, *Controller Name*
and *Messages Pack* will be filled in with appropriate values. Save changes. Open the *XML* tab and replace its content with the following code:

[source, xml]
----
include::{sourcesdir}/chart/stackedarea-chart.xml[]
----

The root element of the screen descriptor contains a new `xmlns:chart` attribute:

[source, xml]
----
<window xmlns:chart="http://schemas.haulmont.com/charts/charts.xsd"
    ...
>
----

`chart:serialChart` attributes:

* `categoryField` - a key from the set of pairs contained in the `DataItem` objects listed in a `DataProvider` instance; this key is used to determine the labels for the category axis.

The elements of `chart:serialChart`:

* `chart:chartCursor` - an optional element adding a cursor to the chart; the cursor follows the mouse pointer and shows a tooltip with the value of the corresponding point on a chart.
** The `cursorAlpha` attribute defines opacity of the cursor line.

* `chart:legend` - an element that defines the chart legend.
** The `position` attribute defines the location of the legend relative to the chart.
** The `equalWidths` attribute specifies if each of legend entry should be equal to the most wide entry.
** The `periodValueText` attribute defines the text which will be displayed in the value portion of the legend when user is not hovering above any data point. The tags should be made out of two parts - the name of a field (value / open / close / high / low) and the value of the period you want to be show - open / close / high / low / sum / average / count.
** The `valueAlign` attribute defines alignment of the value text. Possible values are "left" and "right".
** The `valueWidth` attribute defines width of the value text.

* `chart:valueAxes` - an element that defines vertical value axes. In our case, only one vertical axis is used; the axis is described by the `chart:axis` element.
** The `position` attribute defines position of the value axis relative to the chart.
** The `title` attribute defines the title of the value axis.
** Setting `stackType` to `REGULAR` makes the chart display a rolling value. Setting this attribute to `none` refers to a non-rolling value.
** The `gridAlpha` defines opacity of grid lines.

* `chart:graphs` - an element that contains the collection of `chart:graph` elements; the graph is described by the `chart:graph` element.
** The `type` attribute defines the type of the graph and can be: line, column, step line, smoothed line, ohlc and candlestick.
** The `valueField` attribute defines a key from the list of pairs contained in the `DataItem` objects listed in a `DataProvider` instance; this key is used to determine the value.
** The `fillAlphas` attribute defines opacity of fill.
** The `lineAlpha` attribute defines opacity the line (or column border). Value range is 0 - 1.
** The `hidden` attribute specifies whether the graph is hidden.

* `chart:categoryAxis` - an element that describes the category axis.
** Setting `startOnAxis` to `true` causes drawing the chart right from the value axis. The default value for this attribute is `false`. In this case, there will be a small gap between the value axis and the chart.
** The `gridAlpha` attribute defines opacity of grid lines.
** The `axisColor` attribute defines axis color.

* `chart:export` – an optional element that enables chart export.

