:sourcesdir: ../../../../source

[[appContext]]
==== AppContext

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/sys/AppContext.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`AppContext` is a system class, which stores references to certain common components for each application <<app_tiers,block>> in its static fields:

* `ApplicationContext` of Spring Framework.
* Set of <<app_properties,application properties >> loaded from `app.properties` files.
* `ThreadLocal` variable, storing <<securityContext,SecurityContext>> instances.
* Collection of application lifecycle listeners (`AppContext.Listener`).

When the application is started, `AppContext` is initialized using loader classes, specific for each application <<app_tiers,block>>:

* Middleware loader – `AppContextLoader`
* Web Client loader – `WebAppContextLoader`
* Web Portal loader – `PortalAppContextLoader`
* Desktop Client loader – `DesktopAppContextLoader`

`AppContext` can be used in the application code for the following tasks:

* Getting the <<app_properties,application property>> values, stored in `app.properties` files in case they are not available through <<config_interfaces,configuration interfaces>>.

* Passing `SecurityContext` to new execution threads, see <<authentication>>.

* Registering listeners, triggered after full initialization and before termination of the application, for example:
+
[source, java]
----
include::{sourcesdir}/common/appcontext_1.java[]
----
+
[WARNING]
====
Please note that the recommended way to run code on the application startup and shutdown is using <<app_lifecycle_events>>.
====

