:sourcesdir: ../../../../source

[[data_model]]
==== Data Model

Data model entities are divided into two categories:

* Persistent – instances of such entities are stored in the database using <<orm,ORM>>.
* Non-persistent – instances exist only in memory, or are stored somewhere via different mechanisms.

The entities are characterized by their attributes. An attribute corresponds to a field and a pair of access methods (get / set) of the field. If the setter is omitted, the attribute becomes read-only.

Persistent entities may include attributes that are not stored in the database. For a non-persistent attribute, the field is optional and you can create only access methods.

The entity class should meet the following requirements:

* Be inherited from one of the base classes provided by the platform (see <<base_entity_classes,below>>).

* Have a set of fields and access methods corresponding to attributes.

* The class and its fields (or access methods if the attribute has no corresponding field) must be <<entity_annotations,annotated>> to provide information for the <<orm, ORM>> (in case of a persistent entity) and <<metadata_framework,metadata>> frameworks.

The following types can be used for entity attributes:

* `java.lang.String`
* `java.lang.Boolean`
* `java.lang.Integer`
* `java.lang.Long`
* `java.lang.Double`
* `java.math.BigDecimal`
* `java.util.Date`
* `java.sql.Date`
* `java.sql.Time`
* `java.util.UUID`
* `byte[]`
* `enum`
* Entity

Base entity classes (see below) override `equals()` and `hashCode()` methods to check entity instances equivalence by comparing their identifiers. I.e., instances of the same class are considered equal if their identifiers are equal.

include::data_model/base_entity_classes.adoc[]

include::data_model/entity_annotations.adoc[]

include::data_model/enum_attributes.adoc[]

include::data_model/soft_deletion.adoc[]

