:sourcesdir: ../../../../source

[[screen_validation]]
==== ScreenValidation

The `ScreenValidation` bean should be used to run validation in screens. It has the following methods:

* `ValidationErrors validateUiComponents()` is used by default when committing changes in the `StandardEditor`, `InputDialog`, and `MasterDetailScreen`. The method accepts a collection of components or a component container and returns validation errors in these components (`ValidationErrors` object). The `validateUiComponents()` method also can be used in an arbitrary screen. For example:
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_1.java[]
----

* `showValidationErrors()` - displays a notification with all errors and problematic components. The method accepts the screen and `ValidationErrors` object. It is also used by default in the `StandardEditor`, `InputDialog`, and `MasterDetailScreen`.

* `validateCrossFieldRules()` - accepts a screen and an entity and returns the `ValidationErrors` object. Performs cross-field validation rules. Editor screens validate class-level constraints on the commit if the constraints include the `UiCrossFieldChecks` group and all attribute-level constraint checks are successful (see more information in the <<bean_validation_custom_constraints,Custom Constraints>> section). You can disable this type of validation using the `setCrossFieldValidate()` method of the controller. By default, it is used in the `StandardEditor`, `MasterDetailScreen`, in the <<gui_DataGrid_inline_editor,editor>> of the `DataGrid`. The `validateCrossFieldRules()` method also can be used in an arbitrary screen.
+
As an example, let's look at the `Event` entity for which we can define a class-level annotation `@EventDate` to check that the *Start date* must be lower than the *End date*.
+
.Event entity
[source, java]
----
include::{sourcesdir}/common/screen_validation_5.java[]
----
The annotation definition looks like this:
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_6.java[]
----
+
.EventDateValidator
[source, java]
----
include::{sourcesdir}/common/screen_validation_7.java[]
----
Then you can use the `validateCrossFieldRules()` method in an arbitrary screen.
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_2.java[]
----

* `showUnsavedChangesDialog()` - shows the standard dialog for unsaved changes ("Do you want to discard unsaved changes?") with the *Yes* and *No* buttons. It is used in the `StandardEditor`. The `showUnsavedChangesDialog()` method has a handler that responds to user actions (the button that was clicked):
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_3.java[]
----

* `showSaveConfirmationDialog()` - shows the standard dialog for confirming saving changed data ("Do you want to save changes before close?") with the *Save*, *Do not save*, *Cancel* buttons. It is used in the `StandardEditor`. The `showSaveConfirmationDialog()` method has a handler that responds to user actions (the button that was clicked):
+
[source, java]
----
include::{sourcesdir}/common/screen_validation_4.java[]
----

You can adjust the dialog type using the <<cuba.gui.useSaveConfirmation,cuba.gui.useSaveConfirmation>> application property.