:sourcesdir: ../../../../source

[[rest_api_v2_services_config]]
==== Настройка сервисов среднего слоя

Список методов сервисов, доступных для вызова через REST API, должен быть объявлен в приложении в конфигурационных файлах, заданных свойством приложения <<cuba.rest.servicesConfig, cuba.rest.servicesConfig>>. Свойство должно быть определено в модуле *web* или *portal* (например, в файле `web-app.properties`):

[source,properties]
----
cuba.rest.servicesConfig = +com/company/myapp/rest-services.xml
----

Файл `rest-services.xml` должен находиться в главном пакете модуля *web* или *portal* (например, `com.company.myapp`). Его содержимое определяется схемой http://schemas.haulmont.com/cuba/{revnumber}/rest-services-v2.xsd[rest-services-v2.xsd], например:

[source, xml]
----
include::{sourcesdir}/rest/rest-services-config.xml[]
----

Типы параметров метода могут быть опущены, если сервис не содержит перегруженного метода с тем же количеством аргументов. Иначе типы параметров обязательны к указанию.

Если тип параметра является примитивным типом, то достаточно просто указать имя типа (`int`, `double`, etc.) в файле конфигурации:

[source, xml]
----
<param name="intParam" type="int"/>
----

В случае объектов, в том числе и сущностей, указывается полное имя класса:

[source, xml]
----
<param name="stringParam" type="java.lang.String"/>
<param name="entityParam" type="com.company.entity.Order"/>
----

В случае коллекции объектов указывается тип коллекции:

[source, xml]
----
<param name="entitiesCollectionParam" type="java.util.List"/>
----

Пример конфигурирования и вызова сервиса можно увидеть в разделах <<rest_api_v2_ex_service_get>> и <<rest_api_v2_ex_service_post>>.

Если необходимо иметь возможность вызова метода сервиса без аутентификации даже при отключенном <<rest_api_v2_anonymous, анонимном доступе>> к REST API, то можно пометить метод сервиса атрибутом `anonymousAllowed="true"` в конфигурационном файле:

[source, xml]
----
include::{sourcesdir}/rest/rest-services-config-anonymous.xml[]
----