:sourcesdir: ../../../../source

[[rest_api_v2_queries_config]]
==== Настройка предопределенных JPQL запросов

В приложении на CUBA предопределенные JPQL запросы должны быть объявлены в файлах, определенных свойством приложения <<cuba.rest.queriesConfig, cuba.rest.queriesConfig>>. Свойство должно быть определено в модуле *web* или *portal* (например, в файле `web-app.properties`):

[source,properties]
----
cuba.rest.queriesConfig = +com/company/myapp/rest-queries.xml
----

Файл `rest-queries.xml` должен находиться в главном пакете модуля *web* или *portal* (например, `com.company.myapp`). Его содержимое определяется схемой http://schemas.haulmont.com/cuba/{revnumber}/rest-queries.xsd[rest-queries.xsd], например:

[source, xml]
----
include::{sourcesdir}/rest/rest-queries-config.xml[]
----

Пример конфигурирования и исполнения запроса можно увидеть в разделе <<rest_api_v2_ex_query_get>> и <<rest_api_v2_ex_query_post>>.

Платформа также предоставляет встроенный запрос `all` для получения списка всех экземпляров некоторой сущности. Он может быть использован совместно с `/count` чтобы получить общее количество экземпляров сущности, например:

  http://localhost:8080/app/rest/v2/queries/sales$Order/all/count

Атрибут `cacheable` элемента `query` включает <<entity_cache,кэширование>> данного запроса.

Запрос может содержать предопределенные параметры, которые принимают значения идентификатора и логина текущего пользователя: `session$userId` и `session$userLogin`. Их не нужно объявлять в элементе `params` (см. пример выше).

