:sourcesdir: ../../../../source

[[rest_api_v2_settings]]
==== Прочие настройки REST API

<<cuba.rest.client.id, cuba.rest.client.id>> - определяет id клиента REST API по умолчанию.

<<cuba.rest.client.secret, cuba.rest.client.secret>> - определяет пароль клиента REST API по умолчанию.

<<cuba.rest.client.tokenExpirationTimeSec, cuba.rest.client.tokenExpirationTimeSec>> - определяет время жизни access токена в секундах для клиента по умолчанию.

<<cuba.rest.client.refreshTokenExpirationTimeSec, cuba.rest.client.refreshTokenExpirationTimeSec>> - определяет время жизни refresh токена в секундах для клиента по умолчанию.

<<cuba.rest.client.authorizedGrantTypes, cuba.rest.client.authorizedGrantTypes>> - определяет список типов авторизации (grant type), поддерживаемых клиентом по умолчанию. Для отключения поддержки refresh-токенов, удалите элемент `refresh_token` из значения свойства.

<<cuba.rest.maxUploadSize, cuba.rest.maxUploadSize>> - определяет максимальный размер файла, который может быть загружен с помощью REST API.

<<cuba.rest.reuseRefreshToken, cuba.rest.reuseRefreshToken>> - определяет должен ли refresh-токен быть повторно использован.

<<cuba.rest.requiresSecurityToken,cuba.rest.requiresSecurityToken>> - указывает, что в JSON сущности должен пересылаться дополнительный системный атрибут. Подробнее см. <<rest_api_v2_security_constraints>>.

<<cuba.rest.tokenMaskingEnabled,cuba.rest.tokenMaskingEnabled>> - указывает, должны ли значения токенов REST API быть маскированы в логах приложения.

