:sourcesdir: ../../../../source

[[rest_api_v2_custom_controllers]]
==== Собственные контроллеры, защищенные OAuth2

Если вам необходимо создать свой REST контроллер, защищенный с помощью OAuth2, сделайте следующее:

. Предположим, ваш контроллер выглядит следующим образом:
+
[source, java]
----
include::{sourcesdir}/features/MyController.java[]
----

. Создайте новый файл конфигурации Spring с именем `rest-dispatcher-spring.xml` внутри корневого пакета (например, `com.company.test`) модуля *web* или *portal*. Содержимое файла должно быть следующим:
+
[source, xml]
----
include::{sourcesdir}/rest/rest-dispatcher-spring.xml[]
----

. Задайте <<additive_app_properties,аддитивное>> свойство приложения `cuba.restSpringContextConfig` в файле свойств соответствующего модуля, например, в `portal-app.properties`:
+
[source, properties]
----
cuba.restSpringContextConfig = +com/company/test/rest-dispatcher-spring.xml
----

. Новый контроллер будет помещен в контекст, связанный с сервлетом `CubaRestApiServlet`, поэтому URL для доступа к методам контроллера будут начинаться с `/rest`, т.е. метод doSmth() будет доступен по адресу: `\http://localhost:8080/app-portal/rest/myapi/dosmth`.
+
[WARNING]
====
Адреса для доступа к методам кастомных контроллеров НЕ ДОЛЖНЫ начинаться с `/rest/v2`.
====

