:sourcesdir: ../../../../../../source

[[config_interface_usage]]
====== Using Configuration Interfaces

To create a configuration interface in your application, do the following:

* Create an interface inherited from `com.haulmont.cuba.core.config.Config` (not to be confused with the entity class `com.haulmont.cuba.core.entity.Config`).

* Add `@Source` annotation to specify where the property values should be stored:

** `SourceType.SYSTEM` – values will be taken from the system properties of the given JVM using the `System.getProperty()` method.

** `SourceType.APP` – values will be taken from `*app.properties` files.

** `SourceType.DATABASE` – values will be taken from the database.

* Create property access methods (getters / setters). If you are not going to change the property value from the application code, do not create setter. A getter return type defines the property type. Possible property types are described <<config_interface_property_types,below>>.

* Add `@Property` annotation defining the property name to the getter.

* You can optionally set `@Source` annotation for a particular property if its source differs from the interface source.

* If the `@Source` value is `SourceType.DATABASE`, the property can be edited on the *Administration > Application Properties* screen provided by the platform. You can use the `@Secret` annotation in order to mask the value on this screen (<<gui_PasswordField,PasswordField>> will be used instead of the regular text field).

Example:

[source, java]
----
include::{sourcesdir}/common/configinterface_3.java[]
----

Do not create any implementation classes because the platform will create a required proxy automatically when you inject the configuration interface or obtain it through <<configuration,Configuration>>.

