:sourcesdir: ../../../source

[[chart_listeners]]
=== События

Имеется возможность настроить реакцию на различные типы событий. Следующие типы слушателей событий доступны для всех видов диаграмм:

* `LegendItemHideListener` - скрытие элемента легенды.
* `LegendItemShowListener` - показ элемента легенды.
* `LegendLabelClickListener` - щелчок по ярлыку легенды.
* `LegendMarkerClickListener` - щелчок по маркеру легенды.

Для каждого вида диаграмм также доступны свои типы слушателей, описанные в соответствующих <<chart_types,разделах>> документации.

Пример использования событий проиллюстрирован в разделе <<section_use_of_events>>.

Чтобы мигрировать старый код, в котором используются слушатели событий, на новую версию платформы, необходимо привести компонент `Chart` к конкретному типу диаграммы или заново инжектировать его с конкретным типом диаграммы:
[source,java]
----
include::{sourcesdir}/chart/injectChart.java[]
----
[source,java]
----
((PieChart)pieChart).addSliceClickListener(event -> {});
----

Кроме обработки событий, интерфейс `SeriesBasedChart` содержит методы `zoomOut`, `zoomToIndexes` и `zoomToDates` для манипуляций с осями диаграммы.

Подобные методы для управления осями значений также есть и в интерфейсе `CoordinateChart`: `zoomOutValueAxes`, `zoomOutValueAxis`, `zoomOutValueAxis`, `zoomValueAxisToValues` и `zoomValueAxisToValues`.


