:sourcesdir: ../../../source

[[chart_data_binding]]
=== Связь с данными

Реализовано три варианта передачи данных в диаграмму: через интерфейс `DataProvider`, через механизм источников данных, или с использованием <<chart_data_simplified,упрощённого API>>, позволяющего привязывать данные напрямую при помощи метода `addData()` и удобных конструкторов класса `MapDataItem`. Последний способ подходит для диаграмм, не привязанных к какому-либо источнику данных.

[[chart_data_provider]]
DataProvider: ::
+
--
Интерфейс `DataProvider` имеет стандартную реализацию: класс `ListDataProvider`. Он содержит список экземпляров `DataItem` из которых будут браться данные для диаграммы. Существует несколько стандартных реализаций интерфейса `DataItem`:

* `EntityDataItem` принимает экземпляр сущности.
* `MapDataItem` содержит набор пар ключ-значение.
* `SimpleDataItem` принимает экземпляр любого `public` класса.

Экземпляр `DataProvider` передается методу `setDataProvider()` конфигурации диаграммы. Данный способ предоставления данных для диаграммы наиболее универсален, однако требует создания экземпляров `DataProvider` и `DataItem` в коде контроллера экрана.
--

[[chart_datasource]]
Datasource: ::
+
--
Источник данных типа `CollectionDatasource` устанавливается для компонента `Chart` вызовом метода `setDatasource()`. Данный вариант требует наличия сущности, представляющей данные диаграммы. Он удобен, когда такая сущность уже есть в модели данных приложения, а также когда данные диаграммы нужно отобразить и в виде таблицы.

В главе <<chart_example>> проиллюстрированы все три способа получения данных.

Используемые для отображения свойства сущности или значения, содержащиеся в экземпляре `DataProvider`, задаются в атрибутах диаграммы, причем атрибуты различаются для разных типов диаграмм. Например для компонента `chart:pieChart` необходимо задать атрибуты `valueField` и `titleField`.В качестве значений могут выступать типы `Integer`, `Long`, `Double`, `String`, `Boolean`, `Date`.

Динамическое добавление данных в существующий график поддерживается для обоих механизмов.
--

[[chart_data]]
Элемент chart:data: ::
+
--
Этот способ удобен для быстрого прототипирования диаграмм. Элемент `chart:data` и вложенные в него элементы `item` позволяют вручную указать фиксированные значения прямо в XML-дескрипторе диаграммы, например:

[source, xml]
----
include::{sourcesdir}/chart/chart_data.xml[]
----
--

