:sourcesdir: ../../../../../../source

[[datatype_custom_example]]
====== Пример специализированного Datatype

В качестве примера рассмотрим следующую задачу: в приложении есть атрибуты сущностей, хранящие годы в виде целых чисел. Пользователи должны иметь возможность просматривать и редактировать годы, причем если пользователь вводит только две цифры, приложение должно преобразовать их в год между 2000 и 2100. В противном случае, все введенное число считается годом.

Создайте класс в модуле *global*:

[source, java]
----
include::{sourcesdir}/common/datatype_1.java[]
----

Затем добавьте элемент `datatypes` в файл <<metadata.xml,metadata.xml>> вашего проекта:

[source, xml]
----
include::{sourcesdir}/common/datatype_2.xml[]
----

В элементе `datatype` можно также указать атрибут `sqlType`, содержащий SQL-тип вашей базы данных, подходящий для хранения значений нового типа. Этот SQL-тип будет использоваться CUBA Studio при генерации скриптов базы данных. Studio может автоматически определить SQL-тип для следующих типов Java:

* `java.lang.Boolean`
* `java.lang.Integer`
* `java.lang.Long`
* `java.math.BigDecimal`
* `java.lang.Double`
* `java.lang.String`
* `java.util.Date`
* `java.util.UUID`
* `byte[]`

В нашем случае класс предназначен для работы с типом `Integer` (что декларируется аннотацией `@JavaClass` со значением `Integer.class`), поэтому атрибут `sqlType` можно не указывать.

Наконец, укажите новый тип данных для требуемых атрибутов (программно или с помощью интерфейса Studio):

[source, java]
----
@MetaProperty(datatype = "year")
@Column(name = "ISSUE_YEAR")
private Integer issueYear;
----

После выполнения перечисленных действий атрибут `issueYear` везде в приложении будет отображаться в нужном формате.

