:sourcesdir: ../../../../../../source

[[datatype_format_strings]]
====== Строки форматов Datatype

Форматы для преобразований с учетом локали задаются в <<main_message_pack,главном пакете локализованных сообщений>> проекта или его <<app_components,компонентов>>, в строках со следующими ключами:

* `numberDecimalSeparator` - задает символ разделителя целой и дробной части для числовых типов

* `numberGroupingSeparator` - задает символ разделителя групп разрядов для числовых типов

* `integerFormat` - формат для типов `Integer` и `Long`

* `doubleFormat` - формат для типа `Double`

* `decimalFormat` - формат для типа `BigDecimal`

* `dateTimeFormat` - формат для типа `java.util.Date`

* `dateFormat` - формат для типа `java.sql.Date`

* `timeFormat` - формат для типа `java.sql.Time`

* `trueString` - строка, соответствующая `Boolean.TRUE`

* `falseString` - строка, соответствующая `Boolean.FALSE`

[TIP]
====
Форматы для используемых в приложении языков могут быть заданы в Studio. Для этого откройте на редактирование *Project Properties*, нажмите кнопку в поле *Available locales*, затем нажмите *Show data format strings*.
====

Строки форматов могут быть получены из бина `FormatStringsRegistry`.

