:sourcesdir: ../../../../../../source

[[datatype_format_strings]]
====== Строки форматов Datatype

Форматы для преобразований с учетом локали задаются в <<main_message_pack,главном пакете локализованных сообщений>> проекта или его <<app_components,компонентов>>, следуя логике стандартных классов Java SE, таких как `DecimalFormat` (см. link:$$https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html$$[https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html]) и `SimpleDateFormat` (см. link:$$https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html$$[https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html]).

Форматы задаются в строках со следующими ключами:

* `numberDecimalSeparator` - задает символ разделителя целой и дробной части для числовых типов, например:
+
[source, properties]
----
# использование запятой в качестве разделителя
numberDecimalSeparator=,
----

* `numberGroupingSeparator` - задает символ разделителя групп разрядов для числовых типов
+
[source, properties]
----
# использование пробела в качестве разделителя
numberGroupingSeparator = \u0020
----

* `integerFormat` - формат для типов `Integer` и `Long`
+
[source, properties]
----
# запретить отображение разделителя тысяч для целых чисел
integerFormat = #0
----

* `doubleFormat` - формат для типа `Double`. Обратите внимание, что символы десятичного разделителя и разделителя групп разрядов задаются отдельно в своих собственных ключах (см. выше).
+
[source, properties]
----
# округление до трёх цифр после десятичного разделителя
doubleFormat=#,##0.###
----

* `decimalFormat` - формат для типа `BigDecimal`. Обратите внимание, что символы десятичного разделителя и разделителя групп разрядов задаются отдельно в своих собственных ключах (см. выше).
+
[source, properties]
----
# всегда отображать две цифры после десятичного разделителя, например, в денежных единицах
decimalFormat = #,##0.00
----

* `dateTimeFormat` - формат для типа `java.util.Date`
+
[source, properties]
----
# формат дата+время для России
dateTimeFormat = dd.MM.yyyy HH:mm
----

* `dateFormat` - формат для типа `java.sql.Date`
+
[source, properties]
----
# формат даты для США
dateFormat = MM/dd/yyyy
----

* `timeFormat` - формат для типа `java.sql.Time`
+
[source, properties]
----
# формат времени часы:минуты
timeFormat=HH:mm
----

* `trueString` - строка, соответствующая `Boolean.TRUE`
+
[source, properties]
----
# альтернативное отображение булевых значений
trueString = да
----

* `falseString` - строка, соответствующая `Boolean.FALSE`
+
[source, properties]
----
# альтернативное отображение булевых значений
falseString = нет
----

[TIP]
====
Форматы для используемых в приложении языков могут быть заданы в Studio. Для этого откройте экран *Project Properties*, нажмите кнопку в поле *Available locales*, затем нажмите *Show data format strings*.
====

Строки форматов могут быть получены из бина `FormatStringsRegistry`.

