:sourcesdir: ../../../../source

[[db_update_in_prod_cmdline]]
==== Initializing and Updating a Database from The Command Line

Database create and update scripts can be run from the command line using the `com.haulmont.cuba.core.sys.utils.DbUpdaterUtil` class included in the platform's Middleware block. At startup, the following arguments should be specified:

* `dbType` – <<dbms_types,DBMS type>>, possible values: postgres, mssql, oracle, mysql.

* `dbVersion` – <<dbms_version,DBMS version>> (optional argument).

* `dbDriver` - JDBC driver class name (optional argument). If not provided, the driver class name will be derived from `dbType`.

* `dbUser` – database user name.

* `dbPassword` – database user password.

* `dbUrl` – database connection URL. For primary initialization, the specified database should be empty; the database is not cleared automatically in advance.

* `scriptsDir` – absolute path to the folder containing scripts in the standard structure. Typically, this is the <<db_dir,database scripts directory>> supplied with the application.

* one of the possible commands:

** `create` – initialize the database.

** `check` – show all unexecuted update scripts.

** `update` – update the database.

An example of a script for Linux running `DbUpdaterUtil`:

[source, bash]
----
include::{sourcesdir}/database/dbupdate.sh[]
----

This script is designed to work with the database named `mydb` running on the local *PostgreSQL* server. The script should be located in the `bin` folder of the Tomcat server and should be started with `{username}`, `{password}` and `{command}`, for example:

[source]
----
./dbupdate.sh cuba cuba123 update
----

Script execution progress is displayed in the console. If any error occurs, same actions as described in the previous section for the automatic update mechanism should be performed.

[WARNING]
====
When updating the database from the command line, the existing Groovy scripts are started, but only their main part gets executed. Due to the lack of the server context, the script's `PostUpdate` part is ignored with the corresponding message written to the console.
====

