= CUBA Platform. Full Text Search
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.9
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)
:main_man_url: https://doc.cuba-platform.com/manual-{revnumber}

:!sectnums:

[[preface]]
== Preface

This document serves as a guide for using _full text search_ (_FTS_) subsystem of the CUBA platform.

[[audience]]
=== Target Audience

This manual is intended for developers building CUBA applications with full text search support. It is assumed that the reader is familiar with the *Developer's Manual*, which is available at https://www.cuba-platform.com/manual.

[[additional_info]]
=== Additional Materials

This guide, as well as any other CUBA platform documentation, is available at https://www.cuba-platform.com/en/manual.

CUBA full text search subsystem is based on the *Apache Lucene* framework, therefore familiarity with the framework will be beneficial. See http://lucene.apache.org/core.

[[feedback]]
=== Feedback

If you have any suggestions for improving this manual, feel free to report issues in the source repository on https://github.com/cuba-platform/documentation[GitHub]. If you see a spelling or wording mistake, a bug or inconsistency, don't hesitate to fork the repo and fix it. Thank you!

:sectnums:

include::chapter1.adoc[]

include::chapter2.adoc[]

[[fts_config]]
[appendix]
== FTS Configuration File

The full text search configuration file is an XML file, which is usually located in the `src` directory of the *core* module and contains the description of indexed entities and their attributes.

The file is specified in the <<cuba.ftsConfig,cuba.ftsConfig>> application property.

The file has the following structure: 

`fts-config` - root element.

`fts-config` elements:

* `entities` - list of entities to be indexed and searched.
+
`entities` elements:

** entity - indexed entity description.
+
`entity` attributes:
+
--
*** `class` - entity Java class.
*** `show` - defines whether this entity should appear in the search results. The `false` value is used for connecting entities which are not of interest to the user, but are required, for example, to link uploaded files and entities of the domain model. Default is `true`.
--
+
`entity` elements:

*** `include` - determines whether to include a single or multiple entity attributes in the index.+
`include` attributes:

**** `re` - regular expression to select attributes by name.

**** `name` - attribute name. It can be reference attributes path (divided by period). The type is not checked. However, if the name is defined by a path, then two options are possible. 
+
--
. The final attribute must be a non-embeddable entity. Including non-entity type attribute does not make sense here, as it must be indexed within its owning entity.
. The final attribute must be a non-entity field of the embedded entity. For example, if the indexed entity has an "address" field of the Address type (embeddable entity) then the attribute name should be "address.city" or "address.street", but not the "address".
--

*** `exclude` - excludes attributes previously included by `include` element. Possible attributes are the same as in include.

*** `searchables` - a Groovy script to add arbitrary entities associated with the changed one to the indexing queue.
+
For example, when a `CardAttachment` instance is either added or removed, the associated `Card` instance should also be re-indexed. The reason is that the `Card` instance itself will not be added to the queue, as it has not been changed (it stores a collection of `CardAttachment` instances). Thus it will not be shown in search results if matching data is found in its linked entity - a newly added `CardAttachment`.
+
The following objects are passed into the script at invocation: 
+
--
**** `searchables` - the list of entities that should be appended.
**** `entity` - the current entity instance, which is being added to the queue automatically.
--
+
Script example:
+
[source,xml]
----
include::{sourcesdir}/fts_config_1.xml[]
----

*** `searchableIf` - a Groovy script to exclude certain instances of the indexed entity from the queue.
+
For example, you may not want to index old versions of documents. 
+
When running the script, the `entity` variable - the current entity instance - is passed into it. The script should return a boolean value: `true` if the current instance should be indexed, and `false` otherwise.
+
Script example:
+
[source, xml]
----
include::{sourcesdir}/fts_config_2.xml[]
----

FTS configuration file example:

[source, xml]
----
include::{sourcesdir}/fts_config_3.xml[]
----

[[fts_properties]]
[appendix]
== Application Properties

This section lists the application properties that are relevant to the full text search subsystem.

[[cuba.ftsConfig]]
cuba.ftsConfig::

Additive property defining a FTS configuration file of the project.
+
The file is loaded using the `Resources` interface, so it can be located in classpath or in the configuration directory.
+
Used in the Middleware block.
+
Example:
+
[source, properties]
----
cuba.ftsConfig = +com/company/sample/fts.xml
----

All properties that are described below are runtime parameters stored in the database and available in the application code via the `FtsConfig` configuration interface.

[[fts.enabled]]
fts.enabled:: The flag enabling the FTS functionality in the project.
+
Can be changed via the *Enabled* attribute of the `app-core.fts:type=FtsManager` JMX bean.
+
Default value: `false`

[[fts.indexDir]]
fts.indexDir:: Absolute path to the directory storing indexed files. If not specified, the `ftsindex` subdirectory of the application work directory (defined by the cuba.dataDir property) is used; in the default deployment configuration, it is *tomcat/work/app-core/ftsindex*.
+
Default value: unspecified

[[fts.indexingBatchSize]]
fts.indexingBatchSize:: Number of records extracted from the indexing queue per one invocation of `processQueue()`.
+
This limitation is relevant to the situation when the indexing queue contains a very large number of records, for example, after executing the `reindexAll()` method of the `app-core.fts:type=FtsManager` JMX bean. In this case, indexing is done in batches, which takes more time, but creates a limited and predictable server load.
+
Default value: `300`

[[fts.reindexBatchSize]]
fts.reindexBatchSize::
+
--
Number of records put to the indexing queue per one invocation of `reindexNextBatch()`.

Default value: `5000`
--

[[fts.maxSearchResults]]
fts.maxSearchResults:: The maximum number of entries in the search result.
+
Default value: `100`

[[fts.searchResultsBatchSize]]
fts.searchResultsBatchSize:: Number of elements in a single batch of search results. A user will need to click *More* on the results screen to view the next batch.
+
Default value: `5`