:sourcesdir: ../../source

[[fts_properties]]
[appendix]
== Application Properties

This section lists the application properties that are relevant to the full text search subsystem.

[[cuba.ftsConfig]]
cuba.ftsConfig::

Additive property defining a FTS configuration file of the project.
+
The file is loaded using the `Resources` interface, so it can be located in classpath or in the configuration directory.
+
Used in the Middleware block.
+
Example:
+
[source, properties]
----
cuba.ftsConfig = +com/company/sample/fts.xml
----

All properties that are described below are runtime parameters stored in the database and available in the application code via the `FtsConfig` configuration interface.

[[fts.enabled]]
fts.enabled:: The flag enabling the FTS functionality in the project.
+
Can be changed via the *Enabled* attribute of the `app-core.fts:type=FtsManager` JMX bean.
+
Default value: `false`

[[fts.indexDir]]
fts.indexDir:: Absolute path to the directory storing indexed files. If not specified, the `ftsindex` subdirectory of the application work directory (defined by the cuba.dataDir property) is used; in the default deployment configuration, it is *tomcat/work/app-core/ftsindex*.
+
Default value: unspecified

[[fts.indexingBatchSize]]
fts.indexingBatchSize:: Number of records extracted from the indexing queue per one invocation of `processQueue()`.
+
This limitation is relevant to the situation when the indexing queue contains a very large number of records, for example, after executing the `reindexAll()` method of the `app-core.fts:type=FtsManager` JMX bean. In this case, indexing is done in batches, which takes more time, but creates a limited and predictable server load.
+
Default value: `300`

[[fts.reindexBatchSize]]
fts.reindexBatchSize::
+
--
Number of records put to the indexing queue per one invocation of `reindexNextBatch()`.

Default value: `5000`
--

[[fts.maxSearchResults]]
fts.maxSearchResults:: The maximum number of entries in the search result.
+
Default value: `100`

[[fts.searchResultsBatchSize]]
fts.searchResultsBatchSize:: Number of elements in a single batch of search results. A user will need to click *More* on the results screen to view the next batch.
+
Default value: `5`
