:sourcesdir: ../../source

[[general_info]]
== FTS Subsystem Overview

Full-text search (FTS) capabilities of the CUBA platform provide unstructured search within the values of entity attributes and content of uploaded files.

A distinctive aspect of full-text search implementation in CUBA is its focus on business applications with complex data models. Particularly, search results include not only the entities that directly contain the search string but also the related entities which use this attribute when being displayed. For example, if an `Order` entity contains a link to a `Customer` and the search string contains the name of the customer, then search results will include both the `Customer` and the related `Order`. This behavior is logical for a user who typically sees the name of the customer in the order editing screen.

Search results are filtered according to the limitations applied by the framework's security subsystem. I.e. if the current user's access group does not allow access to certain entity instances, such instances will not appear in search results.

Full-text search subsystem contains two mutually related mechanisms: indexing and search.

include::general_info/indexing.adoc[]

include::general_info/search.adoc[]

include::general_info/index_search_example.adoc[]

