:sourcesdir: ../../../../../../source

[[datatype_format_strings]]
====== Datatype Format Strings

Locale-dependent parsing formats are provided in the <<main_message_pack,main messages pack>> of the application or its <<app_components,components>>, in the strings with the following keys:

* `numberDecimalSeparator` – decimal separator for numeric types.

* `numberGroupingSeparator` – thousands separator for numeric types.

* `integerFormat` – format for `Integer` and `Long` types.

* `doubleFormat` – format for `Double` type.

* `decimalFormat` – format for `BigDecimal` type.

* `dateTimeFormat` – format for `java.util.Date` type.

* `dateFormat` – format for `java.sql.Date` type.

* `timeFormat` – format for `java.sql.Time` type.

* `trueString` – string corresponding to `Boolean.TRUE`.

* `falseString` – string corresponding to `Boolean.FALSE`.

[TIP]
====
Studio allows you to set format strings for languages used in your application. Edit *Project Properties*, click the button in the *Available locales* field, then click *Show data format strings*.
====

Format strings for a locale can be obtained using the `FormatStringsRegistry` bean.

