:sourcesdir: ../../../../../../source

[[screen_api]]
====== Screen API

Below is the description of the main methods and events available in CUBA screen controllers:

[[screen_InitEvent]]
* `InitEvent` - an event sent when the screen controller and all its declaratively defined components are created, and dependency injection is completed. Nested fragments are not initialized yet. Some visual components are not fully initialized, for example buttons are not linked with actions.
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_InitEvent.java[]
----

[[screen_InitEntityEvent]]
* `InitEntityEvent` - an event sent before the new entity instance is set to edited entity container. Use this event listener to initialize default values in the new entity instance, for example:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_InitEntityEvent.java[]
----
+
This event is available for the screens extending `StandardEditor`.

[[screen_AfterInitEvent]]
* `AfterInitEvent` - an event sent when the screen controller and all its declaratively defined components are created, dependency injection is completed, and all components have completed their internal initialization procedures. Nested screen fragments (if any) have sent their `InitEvent` and `AfterInitEvent`. In this event listener, you can create visual and data components and perform additional initialization if it depends on initialized nested fragments.

[[screen_BeforeCloseEvent]]
* `BeforeCloseEvent` - an event sent right before the screen is closed by its `close(CloseAction)` method. The screen is still displayed and fully functional. Component settings are not saved yet. In this event listener, you can check any conditions and prevent screen closing using the `preventWindowClose()` method of the event, for example:
+
--
[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeCloseEvent.java[]
----

The `CloseOrigin` marker interface describes the way a window was closed. Its default implementation `CloseOriginType` supports three following types:

* `BREADCRUMBS` - a screen is closed by clicking on the breadcrumbs link;
* `CLOSE_BUTTON` - a screen is closed with one of the following approaches: screen's close button, <<gui_TabSheet,TabSheet>> tabs' close actions (Close, Close All, Close Others);
* `SHORTCUT` - a screen is closed with `ClientConfig.getCloseShortcut()`.

Use the `getCloseOrigin()` method of the event to obtain its origin type, for example:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeCloseEvent_origin.java[]
----
--

[[screen_BeforeShowEvent]]
* `BeforeShowEvent` - an event sent right before the screen is shown, i.e. it is not added to the application UI yet. Security restrictions are applied to UI components. Saved component settings are not yet applied to UI components. Data is not loaded yet for screens annotated with `@LoadDataBeforeShow`. In this event listener, you can load data, check permissions and modify UI components. For example:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeShowEvent.java[]
----

[[screen_AfterShowEvent]]
* `AfterShowEvent` - an event sent right after the screen is shown, i.e. when it is added to the application UI. Saved component settings are applied to UI components. In this event listener, you can show notifications, dialogs or other screens. For example:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_AfterShowEvent.java[]
----

[[screen_AfterCloseEvent]]
* `AfterCloseEvent` - an event sent after the screen is closed by its `close(CloseAction)` method and after `Screen.AfterDetachEvent`. Component settings are saved. In this event listener, you can show notifications or dialogs after closing the screen, for example:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_AfterCloseEvent.java[]
----

[[screen_AfterDetachEvent]]
* `AfterDetachEvent` - an event sent after the screen is removed from the application UI when it is closed by the user or when the user logs out. This event listener can be used for releasing resources acquired by the screen. Note that this event is not sent on HTTP session expiration.

[[screen_UrlParamsChangedEvent]]
* `UrlParamsChangedEvent` - an event sent when browser URL parameters corresponding to opened screen are changed. Event is fired before screen is shown that enables to do some preparatory work. In this event listener, you can load some data or change screen controls state depending on new params:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_UrlParamsChangedEvent.java[]
----

[[screen_saveSettings]]
* `saveSettings()` - saves the screen settings of the current user to the database when the screen is closed.
+
For example, the screen contains a checkBox *showPanel* that manages some panel's visibility. In the following method we create an XML element for the checkBox, then add an attribute `showPanel` containing the checkBox value to this element, and finally we save the `settings` element to the XML descriptor for the current user in the database:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_saveSettings.java[]
----

[[screen_applySettings]]
* `applySettings()` - restores settings saved in the database for the current user when the screen is opened.
+
This method can be overridden to restore custom settings. For example, in the method below we get the XML element of the checkBox from the previous example, then we make sure the required attribute is not null, and if it isn't, we set the restored value to the checkBox:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_applySettings.java[]
----
+
Another example of managing settings is the standard *Server Log* screen from the *Administration* menu of CUBA application that automatically saves and restores recently opened log files.