:sourcesdir: ../../../../../../source

[[screen_controller_methods]]
====== Screen Controller Methods

In your code you can call the following methods of the screen controllers:

[[screen_close]]
* `close()` - requests closing of the screen caused by the given action or, in case of editor or lookup screen, an outcome. The close action passed as a parameter is propagated to <<screen_BeforeCloseEvent,BeforeCloseEvent>> and <<screen_AfterCloseEvent,AfterCloseEvent>>. Thus, the information about the reason why the window was closed can be obtained from the code that initiated the closing event.
+
--
It is recommended to use the following constants for closing edit screens: `++Window.COMMIT_ACTION_ID++` after committing changes, `++Window.CLOSE_ACTION_ID++` – without committing changes.

If any of the data containers contains unsaved changes, a dialog with a corresponding message will be displayed before the screen is closed. You can adjust the notification type using the <<cuba.gui.useSaveConfirmation,cuba.gui.useSaveConfirmation>> application property.

The `close()` method returns `Status.SUCCESS` status if the screen is closed successfully and `++Status.FAIL++` – if closing procedure was interrupted.

For the examples on standard actions and outcomes, see <<screen_return_values,Executing code after close and returning values>>.
--

[[screen_closeWithDefaultAction]]
* `closeWithDefaultAction()` - closes the screen with `++Window.CLOSE_ACTION_ID++`.

[[screen_closeWithCommit]]
* `closeWithCommit()` - tries to validate and commit data. If the data id committed successfully, then closes the screen with `++Window.COMMIT_ACTION_ID++` action. May show validation errors or open an additional dialog before closing the screen.

[[screen_closeWithDiscard]]
* `closeWithDiscard()` - ignores the unsaved changes and closes the screen with `++Window.CLOSE_ACTION_ID++` action.

[[screen_getEditedEntity]]
* `getEditedEntity()` -  returns an instance of the entity being edited, which is set in the main data container of the screen (i.e. an `InstanceContainer` defined in the <<EditedEntityContainer_annotation,@EditedEntityContainer>> annotation).

[[screen_validateAdditionalRules]]
Screen validation::
+
--
For additional screen validation, you can implement the `validateAdditionalRules()` template method.
The method stores validation errors information in a `ValidationErrors` object which is passed to it. Afterwards this information is displayed together with the errors of standard validation. For example:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_methods.java[]
----
--