:sourcesdir: ../../../../../../source

[[polymer_working_with_data]]
====== Работа с данными

Для загрузки данных просто поместите элементы https://cuba-elements.github.io/cuba-elements/components/cuba-data/[cuba-data]
в HTML и укажите требуемые атрибуты.

*Загрузка Сущностей*

Используйте https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entities[cuba-entities] для загрузки сущностей.
Если указаны атрибуты `entity-name` и `view`, элемент загрузит список сущностей и передаст его для привязки данных в
Polymer через свойство `data`:

[source,html]
----
<cuba-entities entity-name="sec$User" view="_local" data="{{users}}"></cuba-entities>
----

Теперь отобразить данные можно очень просто:

[source,html]
----
<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----

*Использование предопределенных JPQL запросов*

Составьте запрос, как описано {rest_man_url}#rest_api_v2_queries_config[здесь].

Используйте элемент https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-query[cuba-query] для получения результатов запроса.
При необходимости в запрос можно передать параметры с помощью свойства `params`:

[source,html]
----
<cuba-query id="query"
            auto="[[auto]]"
            entity-name="sec$User"
            query-name="usersByName"
            data="{{users}}">
</cuba-query>

<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----

*Вызов Сервиса*

Зарегистрируйте сервис и его методы, как описано {rest_man_url}#rest_api_v2_services_config[здесь].
Используйте элемент https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-service[cuba-service] для вызова метода:

[source,html]
----
<cuba-service service-name="cuba_ServerInfoService"
              method="getReleaseNumber"
              data="{{releaseNumber}}"
              handle-as="text"></cuba-service>

Release number: [[releaseNumber]]
----

*Создание Сущности*

С помощью элементов `cuba-entity-form` и `cuba-service-form` можно легко отправлять данные на backend.

В примере ниже мы связываем объект `user`, который нужно сохранить, со свойством `entity`.

[source,html]
----
<cuba-entity-form id="entityForm"
                  entity-name="sec$User"
                  entity="[[user]]"
                  on-cuba-form-response="_handleFormResponse"
                  on-cuba-form-error="_handleFormError">

  <label>Login: <input type="text" name="login" value="{{user.login::input}}"></label>
  <label>Name: <input type="text" name="login" value="{{user.name::input}}"></label>

  <button on-tap="_submit">Submit</button>

</cuba-entity-form>

<paper-toast id="successToast">Entity created</paper-toast>
<paper-toast id="errorToast">Entity creation error</paper-toast>
----

[source,javascript]
----
_submit: function() {
  this.$.entityForm.submit();
},
_handleFormResponse: function() {
  this.user = getUserStub();
  this.$.successToast.open();
},
_handleFormError: function() {
  this.$.errorToast.open();
}
----

[TIP]
====
Необходимо разрешить {rest_man_url}#rest_api_v2_anonymous[анонимный доступ] к REST API, если вы хотите использовать приведённые выше примеры без обязательного входа в систему.
====


