:sourcesdir: ../../../../../source

[[service_creation]]
===== Creating a Service

The name of service interface should end with `Service`, the names of implementation class – with `ServiceBean`.

The following steps are required for creating a service:

. Create the service interface in the *global* <<app_modules,module>>, as the service interface must be available at all <<app_tiers,tiers>>), and specify the service name in it. It is recommended to specify the name in the following format: `++{project_name}_{interface_name}++`. For example:
+
[source, java]
----
include::{sourcesdir}/middleware/service_1.java[]
----

. Create the service class in the *core* module and add the `@org.springframework.stereotype.Service` annotation to it with the name specified in the interface: 
+
[source, java]
----
include::{sourcesdir}/middleware/service_2.java[]
----

The service class, being a <<managed_beans,managed bean>>, should be placed inside the package tree with the root specified in the `context:component-scan` element of the <<spring.xml,spring.xml>> file. In this case, the `spring.xml` file contains the element:

[source, xml]
----
include::{sourcesdir}/middleware/service_3.xml[]
----

which means that the search for annotated beans for this application block will be performed starting with the `com.sample.sales` package.

If different services or other Middleware components require calling the same business logic, it should be extracted and encapsulated inside an appropriate <<managed_beans,managed bean>>. For example:

[source, java]
----
include::{sourcesdir}/middleware/service_7_1.java[]
----

[source, java]
----
include::{sourcesdir}/middleware/service_7_2.java[]
----

[source, java]
----
include::{sourcesdir}/middleware/service_7_3.java[]
----

