:sourcesdir: ../../../../../source

[[service_import]]
===== Using a Service

In order to call a service, the corresponding proxy object should be created in the client block of the application. There is a special factory that creates service proxies: for the Web Client block, it is `WebRemoteProxyBeanCreator`, for Web Portal – `PortalRemoteProxyBeanCreator`, for Desktop Client – `RemoteProxyBeanCreator`.

The proxy object factory is configured in <<spring.xml,spring.xml>> of the corresponding client block and contains service names and interfaces.

For example, to call the `++sales_OrderService++` service from the web client in the *sales* application, add the following code into the `web-spring.xml` file of the *web* module:

[source, xml]
----
include::{sourcesdir}/middleware/service_4.xml[]
----

All imported services should be declared in the single `remoteServices` property in the `map/entry` elements.

[TIP]
====
CUBA Studio automatically registers services in all client blocks of the project.
====

From the application code perspective, the service's proxy object at the client level is a standard Spring bean and can be obtained either by injection or through `AppBeans` class. For example:

[source, java]
----
include::{sourcesdir}/middleware/service_5.java[]
----

or

[source, java]
----
include::{sourcesdir}/middleware/service_6.java[]
----

