:sourcesdir: ../../../../../../source

[[AddAction]]
====== AddAction

AddAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для добавления существующих экземпляров сущности из экрана выбора в контейнер данных. Например, оно используется для заполнения many-to-many коллекций.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.AddAction` и объявляется в XML с помощью атрибута `type="add"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action` element, подробнее см. раздел <<declarative_actions>>. Ниже рассматриваются параметры, специфичные для класса `AddAction`.

Следующие параметры можно установить и в XML и в Java:

* `openMode` - режим открытия экрана выбора, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию AddAction открывает экран выбора в режиме `THIS_TAB`.

* `screenId` - строковый идентификатор экрана выбора. По умолчанию AddAction использует экран, аннотированный `@PrimaryLookupScreen`, или имеющий идентификатор вида `<entity_name>.lookup` или `<entity_name>.browse`, например `demo_Customer.browse`.

* `screenClass` - класс Java экрана выбора. Данный параметр имеет более высокий приоритет, чем `screenId`.

Например, если необходимо открыть определенный экран выбора в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/add/01.xml[]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java]
----
include::{sourcesdir}/gui/std_actions/add/02.java[]
----

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте закладку *Handlers* окна инструментов *Component Inspector* в Studio.

* `screenOptionsSupplier` - обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран выбора. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/03.java[]
----
+
Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

* `screenConfigurer` - обработчик, принимающий экран выбора для его конфигурирования перед открытием. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/04.java[]
----
+
Конфигуратор экрана вступает в действие, когда экран уже инициализирован, но еще не показан, то есть после `InitEvent` и `AfterInitEvent`, и до `BeforeShowEvent`.

* `selectValidator` - обработчик, вызываемый когда пользователь нажимает *Select* в экране выбора. Он принимает объект, содержащий выбранные сущности. Данный обработчик можно использовать для проверки выбора по каким-либо критериям. Обработчик должен вернуть `true` для того, чтобы процесс был продолжен и экран выбора закрылся. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/05.java[]
----

* `transformation` - обработчик, вызываемый после того, как сущности выбраны и провалидированы в экране выбора. Он принимает коллекцию выбранных сущностей и может быть использован для того, чтобы преобразовать содержимое коллекции перед добавлением сущностей в контейнер данных. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/06.java[]
----

* `afterCloseHandler` - обработчик, вызываемый после закрытия экрана выбора. Принимает `AfterCloseEvent`. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/08.java[]
----

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/add/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана выбора `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры:  caption, icon, и т.д. Например:

[source,java]
----
include::{sourcesdir}/gui/std_actions/add/10.java[]
----