:sourcesdir: ../../../../../../source

[[BulkEditAction]]
====== BulkEditAction

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/actions/list/BulkEditAction.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=bulk-edit-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

BulkEditAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для изменения значений атрибутов сразу нескольких выбранных экземпляров сущностей. Оно открывает специальный экран, в котором пользователь может ввести желаемые значения атрибутов. После этого, действие обновляет выбранные сущности в базе данных и в контейнере данных UI-компонента.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.BulkEditAction` и объявляется в XML с помощью атрибута `type="bulkEdit"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел <<declarative_actions>>. Ниже рассматриваются параметры, специфичные для класса `BulkEditAction`.

* `openMode` - режим открытия экрана задания значений атрибутов, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию, экран открывается в режиме `DIALOG`.

* `columnsMode` - количество колонок в экране, задаваемое значением перечисления `ColumnsMode`. По умолчанию `TWO_COLUMNS`.

* `exclude` - регулярное выражение для исключения некоторых атрибутов сущности из экрана.

* `includeProperties` - список атрибутов сущности, которые должны быть показаны в экране. Данный список имеет более высокий приоритет чем выражение `exclude`.

* `loadDynamicAttributes` - отображать ли динамические атрибуты в экране. По умолчанию true.

* `useConfirmDialog` - отображать ли диалог подтверждения перед применением изменений. По умолчанию true.

Например:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/01.xml[]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/02.java[]
----

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте закладку *Handlers* окна инструментов *Component Inspector* в Studio.

* `fieldSorter` - обработчик, принимающий список объектов `MetaProperty`, соответствующих атрибутам сущности, и возвращающий мэп этих объектов на желаемую позицию в экране. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/03.java[]
----

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается кастомный диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать `BulkEditors` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры:  caption, icon, и т.д. Например:

[source, java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/10.java[]
----
Внешний вид экрана задания значений атрибутов можно настроить с помощью переменных SCSS с префиксом `$c-bulk-editor-*`. Эти переменные можно изменить в визуальном редакторе после <<web_theme_extension,расширения темы>> или создания <<web_theme_creation,новой темы>>.