:sourcesdir: ../../../../../../source

[[ClearAction]]
====== ClearAction

ClearAction - <<standard_picker_actions,действие поля выбора сущности>>, предназначенное для очистки значения поля. Если поле связано с атрибутом, являющимся one-to-one composition, то экземпляр сущности, отображаемый в поле, будет удален при коммите <<gui_DataContext,DataContext>> (если экран является редактором сущности, это происходит при нажатии пользователем на *OK*).

Действие реализовано классом `com.haulmont.cuba.gui.actions.picker.ClearAction` и объявляется в XML с помощью атрибута `type="picker_clear"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action` element, подробнее см. раздел <<declarative_actions>>.

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/clear/09.java[]
----
