:sourcesdir: ../../../../../../source

[[CreateAction]]
====== CreateAction

CreateAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для создания новых экземпляров сущности. Оно создает новый экземпляр и открывает экран редактирования сущности с этим экземпляром. После того, как экземпляр сохранен в базу данных экраном редактирования, действие добавляет его в контейнер данных UI-компонента.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.CreateAction` и объявляется в XML с помощью атрибута `type="create"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action` element, подробнее см. раздел <<declarative_actions>>. Ниже рассматриваются параметры, специфичные для класса `CreateAction`.

Следующие параметры можно установить и в XML и в Java:

* `openMode` - режим открытия экрана редактирования, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию экран открывается в режиме `THIS_TAB`.

* `screenId` - строковый идентификатор экрана редактирования. По умолчанию используется экран, аннотированный `@PrimaryEditorScreen`, или имеющий идентификатор вида `<entity_name>.edit`, например `demo_Customer.edit`.

* `screenClass` - класс Java экрана редактирования. Данный параметр имеет более высокий приоритет, чем `screenId`.

Например, если необходимо открыть определенный экран редактирования в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/create/01.xml[]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java]
----
include::{sourcesdir}/gui/std_actions/create/02.java[]
----

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте закладку *Handlers* окна инструментов *Component Inspector* в Studio.

* `screenOptionsSupplier` - обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран редактирования. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/create/03.java[]
----
+
Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

* `screenConfigurer` - обработчик, принимающий экран редактирования для его конфигурирования перед открытием. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/create/04.java[]
----
+
Конфигуратор экрана вступает в действие, когда экран уже инициализирован, но еще не показан, то есть после `InitEvent` и `AfterInitEvent`, и до `BeforeShowEvent`.

* `newEntitySupplier` - обработчик, возвращающий новый экземпляр сущности для отображения в экране редактирования. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/create/05.java[]
----

* `initializer` - обработчик, принимающий новый экземпляр для его инициализации перед отображением в экране редактирования. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/create/06.java[]
----

* `afterCommitHandler` - обработчик, вызываемый после коммита созданного экземпляра сущности в экране редактирования. Принимает созданный и сохраненный в БД экземпляр сущности. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/create/07.java[]
----

* `afterCloseHandler` - обработчик, вызываемый после закрытия экрана редактирования. Принимает `AfterCloseEvent`. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/create/08.java[]
----

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/create/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана редактирования `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры:  caption, icon, и т.д. Например:

[source,java]
----
include::{sourcesdir}/gui/std_actions/create/10.java[]
----