:sourcesdir: ../../../../../../source

[[ExcelAction]]
====== ExcelAction

ExcelAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для экспорта содержимого таблицы в файл XLS.

Если в таблице есть выделенные строки, то действие предлагает пользователю выбор: экспортировать только выделенные строки, или все содержимое. Заголовок и сообщение диалога выбора можно переопределить в проекте путем добавления в главный пакет сообщений с ключами `actions.exportSelectedTitle` и `actions.exportSelectedCaption`.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.ExcelAction` и объявляется в XML с помощью атрибута `type="excel"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action` element, подробнее см. раздел <<declarative_actions>>. Ниже рассматриваются параметры, специфичные для класса `ExcelAction`.

* `fileName` - имя файла экспорта. Если не задано, то генерируется автоматически на основе имени сущности.

* `exportAggregation` - экспортировать ли строки агрегации, если они существуют в таблице. По умолчанию true.

Например:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/excel/01.xml[]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java]
----
include::{sourcesdir}/gui/std_actions/excel/02.java[]
----

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/excel/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать класс `ExcelExporter` напрямую.
