:sourcesdir: ../../../../../../source

[[ExcludeAction]]
====== ExcludeAction

ExcludeAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для удаления экземпляров сущности из контейнера данных в UI. В отличие от <<RemoveAction>>, ExcludeAction не удаляет сущности из базы данных, что требуется, например, при работе с many-to-many коллекциями.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.ExcludeAction` и объявляется в XML с помощью атрибута `type="exclude"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action` element, подробнее см. раздел <<declarative_actions>>. Ниже рассматриваются параметры, специфичные для класса `ExcludeAction`.

Следующие параметры можно установить и в XML и в Java:

* `confirmation` - булевское значение, указывающее, отображать ли диалог подтверждения перед удалением. По умолчанию true.

* `confirmationMessage` - сообщение диалога подтверждения. По умолчанию, берется из главного пакета сообщений по ключу `dialogs.Confirmation.Remove`.

* `confirmationTitle` - заголовок диалога подтверждения. По умолчанию, берется из главного пакета сообщений по ключу `dialogs.Confirmation` key.

Например, если необходимо задать определенное сообщение диалога подтверждения, можно сконфигурировать действие в XML:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/exclude/01.xml[]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java]
----
include::{sourcesdir}/gui/std_actions/exclude/02.java[]
----

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте закладку *Handlers* окна инструментов *Component Inspector* в Studio.

* `afterActionPerformedHandler` - обработчик, вызываемый после того, как выбранные сущности удалены. Принимает объект события, который можно использовать для получения выбранных для удаления экземпляров. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/exclude/07.java[]
----

* `actionCancelledHandler` - обработчик, вызываемый если операция удаления отменена пользователем в диалоге подтверждения. Принимает объект события, который можно использовать для получения выбранных для удаления экземпляров. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/exclude/08.java[]
----

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается кастомный диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/exclude/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать `RemoveOperation` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры:  caption, icon, и т.д. Например:

[source,java]
----
include::{sourcesdir}/gui/std_actions/exclude/10.java[]
----