:sourcesdir: ../../../../../../source

[[RefreshAction]]
====== RefreshAction

RefreshAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для перезагрузки контейнера данных, используемого таблицей или деревом.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.RefreshAction` и объявляется в XML с помощью атрибута `type="refresh"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action`, подробнее см. раздел <<declarative_actions>>.

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/refresh/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, запустить нужный загрузчик напрямую. Например:

[source,java]
----
include::{sourcesdir}/gui/std_actions/refresh/10.java[]
----
