:sourcesdir: ../../../../../../source

[[std_list_actions]]
====== Стандартные действия с коллекцией

Для наследников `ListComponent` (это <<gui_DataGrid,DataGrid>>, <<gui_Table,Table>>, <<gui_GroupTable,GroupTable>>, <<gui_TreeTable,TreeTable>> и <<gui_Tree,Tree>>) в платформе определён набор стандартных действий. Классы их реализации находятся в пакете `com.haulmont.cuba.gui.actions.list`.

Пример использования стандартных действий в таблице: 

[source, xml]
----
include::{sourcesdir}/gui/std_actions/listActions_1.xml[]
----

Стандартные действия для перечисленных выше компонентов включают в себя следующие типы:

* `create` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.CreateAction`. Предназначено для создания нового экземпляра сущности в экране редактирования для этого экземпляра по умолчанию.

* `edit` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.EditAction`. Открывает экран редактирования по умолчанию для выбранного экземпляра сущности.

* `remove` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.RemoveAction`. Предназначено для удаления выбранного экземпляра сущности.

* `add` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.AddAction`. Предназначено для выбора существующего экземпляра сущности в экране просмотра по умолчанию и добавления его в связанный контейнер данных . Типичный сценарий использования этого действия - добавление сущностей в коллекцию many-to-many.

* `exclude` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.ExcludeAction`. Позволяет исключать экземпляры сущности из контейнера данных с типом collection, не удаляя их из базы данных. Типичный сценарий использования этого действия - удаление сущностей из коллекции many-to-many.

* `refresh` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.RefreshAction`. Предназначено для обновления (перезагрузки) коллекции сущностей, хранящейся в контейнере данных.

* `excel` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.ExcelAction`. Предназначено для экспорта данных таблицы в формат XLS и выгрузки соответствующего файла.
+
++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/actions/list/BulkEditAction.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++
+
++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=bulk-edit-simple" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

[[gui_BulkEditAction]]
* `bulkEdit` - действие, определяемое классом `com.haulmont.cuba.gui.actions.list.BulkEditAction`. Предназначено для изменения значения атрибутов сразу нескольких выбранных экземпляров сущностей. Используется так же, как и любые другие действия, например:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/actions_bulkEdit.xml[]
----
+
В дополнение к этому, `BulkEditorWindow` может быть создано программно с помощью нового бина `com.haulmont.cuba.gui.BulkEditors`:
+
[source, java]
----
include::{sourcesdir}/gui/std_actions/builder_bulkEdit.java[]
----


Для основных параметров стандартных действий определены значения по умолчанию: заголовки, значки, горячие клавиши, а также стандартное поведение при вызове действия. Вы можете передать свои собственные значения основных параметров декларативно в XML так же, как и для любого другого действия. Например, можно установить для действия другой значок:

[source, xml]
----
include::{sourcesdir}/gui/std_actions/listActions_2.xml[]
----

Для того чтобы изменить стандартное поведение действия, необходимо подписаться на событие `ActionPerformedEvent` для этого действия в контроллере экрана. Код стандартного действия не будет выполняться, если для него определён альтернативный action listener. По сути, обработчик события `ActionPerformedEvent` переопределяет стандартное поведение действия.

В следующем примере мы переопределяем стандартное поведение действия `create`, чтобы создавать новые экземпляры сущности `Customer` в конкретном экране, открываемом в режиме модального диалога:

[source, java]
----
include::{sourcesdir}/gui/std_actions/listActions_3.java[]
----

Поведение действия `edit` можно изменить так же, как и `create`. Более подробно о переопределении действий см. в описании бина <<screenBuilders,ScreenBuilders>>.

Действие `add` также использует бин `ScreenBuilders`, и переопределить его поведение можно следующим образом:

[source, java]
----
include::{sourcesdir}/gui/std_actions/listActions_4.java[]
----