:sourcesdir: ../../../../../../source

[[std_picker_actions]]
====== Стандартные действия поля выбора

В платформе определен набор стандартных действий для компонентов выбора <<gui_PickerField,PickerField>>, <<gui_LookupPickerField,LookupPickerField>> и <<gui_SearchPickerField,SearchPickerField>>.

Пример использования стандартных действий в компоненте выбора: 

[source, xml]
----
include::{sourcesdir}/gui/std_actions/pickerActions_1.xml[]
----

Стандартные действия для компонентов выбора включают в себя следующие типы:

* `picker_lookup` - действие, определяемое классом `com.haulmont.cuba.gui.actions.picker.LookupAction`. It is designed to select an entity instance from a lookup screen and set it to the picker field. Предназначено для выбора экземпляра сущности в отдельном экране выбора и установки его в качестве значения компонента.

* `picker_open` - действие, определяемое классом `com.haulmont.cuba.gui.actions.picker.OpenAction`. Предназначено для открытия экрана редактирования экземпляра сущности, являющегося текущим значением компонента.

* `picker_clear` - действие, определяемое классом `com.haulmont.cuba.gui.actions.picker.ClearAction`. Предназначено для очистки (то есть установки в `null`) текущего значения компонента.

Для основных параметров стандартных действий определены значения по умолчанию: заголовки, значки, горячие клавиши, а также стандартное поведение при вызове действия. Вы можете передать свои собственные значения основных параметров декларативно в XML так же, как и для любого другого действия. Например, можно установить для действия другой значок:

[source, xml]
----
include::{sourcesdir}/gui/std_actions/pickerActions_2.xml[]
----

Для того чтобы изменить стандартное поведение действия, необходимо подписаться на событие `ActionPerformedEvent` для этого действия в контроллере экрана. Код стандартного действия не будет выполняться, если для него определён альтернативный action listener. По сути, обработчик события `ActionPerformedEvent` переопределяет стандартное поведение действия.

В следующем примере мы переопределяем стандартное поведение действия `picker_lookup`, чтобы выбирать экземпляр сущности `User` в конкретном экране, открываемом в режиме модального диалога:

[source, java]
----
include::{sourcesdir}/gui/std_actions/pickerActions_3.java[]
----

Более подробно о переопределении действий см. в описании бина <<screenBuilders,ScreenBuilders>>.