:sourcesdir: ../../../../../../source

[[ViewAction]]
====== ViewAction

ViewAction - <<standard_list_actions,действие с коллекцией>>, предназначенное для просмотра и редактирования экземпляров сущности. Оно открывает экран редактирования таким же образом, как <<EditAction>>, но делает все поля ввода нередактируемыми и запрещает действия, реализующие интерфейс `Action.DisabledWhenScreenReadOnly`. Если необходимо дать пользователю возможность переключить экран в режим редактирования, добавьте в экран кнопку и свяжите ее с предопределенным действием `enableEditing`:

[source,xml]
----
<hbox id="editActions" spacing="true">
    <button action="windowCommitAndClose"/>
    <button action="windowClose"/>
    <button action="enableEditing"/> <!-- this button is shown only when the screen is in read-only mode -->
</hbox>
----

Заголовок действия `enableEditing` можно переопределить в главном пакете сообщений, используя ключ `actions.EnableEditing`, или непосредственно в экране путем указания атрибута `caption` у соответствующей кнопки.

Действие реализовано классом `com.haulmont.cuba.gui.actions.list.ViewAction` и объявляется в XML с помощью атрибута `type="view"`. Общие свойства действий можно конфигурировать с помощью атрибутов элемента `action` element, подробнее см. раздел <<declarative_actions>>. Ниже рассматриваются параметры, специфичные для класса `ViewAction`.

Следующие параметры можно установить и в XML и в Java:

* `openMode` - режим открытия экрана редактирования, задаваемый значением перечисления `OpenMode`: `NEW_TAB`, `DIALOG`, и т.д. По умолчанию экран открывается в режиме `THIS_TAB`.

* `screenId` - строковый идентификатор экрана редактирования. По умолчанию используется экран, аннотированный `@PrimaryEditorScreen`, или имеющий идентификатор вида `<entity_name>.edit`, например `demo_Customer.edit`.

* `screenClass` - класс Java экрана редактирования. Данный параметр имеет более высокий приоритет, чем `screenId`.

Например, если необходимо открыть определенный экран редактирования в режиме диалога, действие можно сконфигурировать в XML следующим образом:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/view/01.xml[]
----

В качестве альтернативы, действие можно инжектировать в контроллер экрана и сконфигурировать, используя сеттеры:

[source,java]
----
include::{sourcesdir}/gui/std_actions/view/02.java[]
----

Далее рассматриваются параметры, которые можно сконфигурировать только программно в Java. Для генерации корректно аннотированных методов для этих параметров используйте закладку *Handlers* окна инструментов *Component Inspector* в Studio.

* `screenOptionsSupplier` - обработчик, возвращающий объект `ScreenOptions` для передачи в открываемый экран редактирования. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/view/03.java[]
----
+
Возвращаемый объект `ScreenOptions` будет доступен в `InitEvent` открываемого экрана.

* `screenConfigurer` - обработчик, принимающий экран редактирования для его конфигурирования перед открытием. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/view/04.java[]
----
+
Конфигуратор экрана вступает в действие, когда экран уже инициализирован, но еще не показан, то есть после `InitEvent` и `AfterInitEvent`, и до `BeforeShowEvent`.

* `afterCommitHandler` - обработчик, вызываемый после коммита редактируемого экземпляра сущности в экране редактирования, если пользователь переключил экран в режим редактирования используя действие `enableEditing`, упомянутое выше. Принимает сохраненный в БД экземпляр сущности. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/view/07.java[]
----

* `afterCloseHandler` - обработчик, вызываемый после закрытия экрана редактирования. Принимает `AfterCloseEvent`. Например:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/view/08.java[]
----

Для того, чтобы произвести какие-либо проверки, или взаимодействовать с пользователем перед выполнением действия, необходимо подписаться на событие `ActionPerformedEvent` действия и в нужный момент вызвать метод `execute()`. Действие будет вызвано со всеми параметрами, которые были для него заданы. В примере ниже перед выполнением действия отображается диалог подтверждения:

[source,java]
----
include::{sourcesdir}/gui/std_actions/view/09.java[]
----

Можно также подписаться на `ActionPerformedEvent`, и вместо вызова метода `execute()` действия, использовать для открытия экрана редактирования `ScreenBuilders` API напрямую. По сути, в этом случае все специфичные параметры действия игнорируются, и действуют только общие параметры:  caption, icon, и т.д. Например:

[source,java]
----
include::{sourcesdir}/gui/std_actions/view/10.java[]
----