:sourcesdir: ../../source

[[installation]]
== Installation

First, make sure your system meets the requirements explained in the {main_man_url}/setup.html[Setup] section of the CUBA Developer's Manual.

Below are the instructions for how to install CUBA Studio as an application for your operating system or as a plugin for IntelliJ IDEA. Installers for Windows, macOS and Linux can be downloaded from https://www.cuba-platform.com/download.

[[install_windows]]
Installation on Windows::
+
--
. Download the `cuba-studio-X.Y.Z.exe` installer.

. Run the installer and follow its instructions: choose the install location, launcher type, folder name, and complete the installation.

. Launch the installed application.
--

[[install_macos]]
Installation on macOS::
+
--
. Download the `cuba-studio-X.Y.Z.dmg` installer.

. Double-click the installer, then drag and drop `CUBA Studio.app` to the `Applications` folder. If you have a previous version of Studio and you want to keep it, select _Keep Both_ in the appeared dialog.

. Launch the *CUBA Studio* application.
--

[[install_linux]]
Installation on Linux::
+
--
. Install the required dependency:
+
----
$ sudo apt-get install libgconf-2-4
----

. Download the `cuba-studio-X.Y.Z.tar.gz` archive.

. Move the archive to an appropriate folder, e.g. `~/lib` and unpack it:
+
----
$ tar -xvf cuba-studio-X.Y.Z.tar.gz
----

. Go to the `bin` directory and launch the application:
+
----
$ cd ~/lib/cuba-studio-X.Y.Z/bin
$ ./cuba-studio.sh
----
--

[[install_plugin]]
IntelliJ IDEA Plugin Installation::
+
--
TODO
--