:sourcesdir: ../../source

[[installation]]
== Installation

Before installing CUBA Studio, make sure your system meets the requirements explained in the {main_man_url}/setup.html[Setup] section of the CUBA Developer's Manual.

You can install CUBA Studio in two different forms: as a standalone application for your operating system or as a plugin for existing IntelliJ IDEA. The Studio standalone application is a special build of IntelliJ IDEA Community Edition which includes the CUBA plugin. If you haven't used IntelliJ IDEA before, we recommend using the standalone application.

The application has a version corresponding to the IntelliJ IDEA in use, for example, {idea-version}. The CUBA plugin has its own version starting from {plugin-version}.

Installers of the standalone application for Windows, macOS and Linux can be downloaded from https://www.cuba-platform.com/download. The plugin is available in the IntelliJ plugins repository (see <<install_plugin,below>>).

[[install_windows]]
Installation on Windows::
+
--
. Download the `cuba-studio-VERSION.exe` installer.

. Run the installer and follow its instructions: choose the install location, launcher type, folder name, and complete the installation.

. Launch the installed application.
--

[[install_macos]]
Installation on macOS::
+
--
. Download the `cuba-studio-VERSION.dmg` installer.

. Double-click the installer, then drag and drop `CUBA Studio.app` to the `Applications` folder. If you have a previous version of Studio and you want to keep it, select _Keep Both_ in the appeared dialog.

. Launch the *CUBA Studio* application.
--

[[install_linux]]
Installation on Linux::
+
--
. Install the required dependency:
+
----
$ sudo apt-get install libgconf-2-4
----

. Download the `cuba-studio-VERSION.tar.gz` archive.

. Move the archive to an appropriate folder, e.g. `~/lib` and unpack it:
+
----
$ tar -xvf cuba-studio-VERSION.tar.gz
----

. Go to the `bin` directory and launch the application:
+
----
$ cd ~/lib/cuba-studio-VERSION/bin
$ ./cuba-studio.sh
----
--

[[install_plugin]]
IntelliJ IDEA Plugin Installation::
+
--
. Start IntelliJ IDEA {idea-version} or newer.

. Open the *Plugins* dialog.

. Click to the "gear" icon and select *Manage Plugin Repositories*.

. Click *Add* and enter the following in the *Repository URL* field:
+
----
https://plugins.jetbrains.com/plugins/haulmont/list
----

. After adding the repository, switch to the *Marketplace* tab.

. Enter the following into the search field:
+
----
repository:"https://plugins.jetbrains.com/plugins/haulmont/list"
----

. You will see the CUBA plugin in search results.

. Click *Install* and follow further instructions of the IDE.
--