:sourcesdir: ../../source

[[studio_functions]]
== Studio Functionality

In addition to the functionality described in the <<studio_ui,Studio User Interface>> section, CUBA Studio provides a lot of implicit developer-friendly features that boost the coding process.

All these features can be broadly divided into four categories:

* Actions
* Intentions
* Inspections
* References

Actions::
+
--
Global actions on the project level are available from <<studio_ui_menu,CUBA menu>>, while finer-grained actions can be found in <<studio_ui_tree,CUBA tree>> tool window and in the context menu of its elements.

List of most common used actions:

Manage modules::
* Create, edit and remove modules: core, desktop, gui, portal, web, and web-toolkit.

DB actions::
* Generate {main_man_url}/db_scripts.html[database scripts],
* {main_man_url}/build.gradle_createDb.html[Create] database,
* {main_man_url}/build.gradle_updateDb.html[Update] database,
* Generate custom database.

Data model::
* Generate data model upon the existing database,
* Create entity,
* Create enumeration,
* Generate entity attributes,
* Create, edit and delete {main_man_url}/views.html[views].

Middleware::
* Create {main_man_url}/services.html[service],
* Create {main_man_url}/managed_beans.html[managed bean].

Generic UI::
* Create {main_man_url}/web_theme_extension.html[theme extension],
* Edit theme variables,
* Create a {main_man_url}/web_theme_creation.html[custom theme],
* Generate event handlers,
* Create screens, including entity {main_man_url}/screen_lookup.html[browser] and {main_man_url}/screen_edit.html[editor].

REST API::
* Create predefined {main_man_url}/rest_api_v2_queries_config.html[REST query] configuration,
* Create {main_man_url}/rest_api_v2_services_config.html[REST service] configuration.

Build actions::
* Assemble the project,
* Clean the project,
* Create or update Gradle wrapper,
* Update IDEA project files.

Run actions::
* {main_man_url}/build.gradle_deploy.html[Deploy] and undeploy the application,
* Perform {main_man_url}/hot_deploy.html[hot deploy],
* Start, restart or stop the application,
* Open application in a web- or an embedded browser.

Deployment settings::
* Configure deployment to UberJAR,
* Configure deployment to WAR.

Application components::
* Create {main_man_url}/app_components_recipes.html[app component] descriptor,
* Install application component.
--

Intentions::
+
--
Intentions are suggested to the developer on Alt+Enter click.

* Create message in the {main_man_url}/message_packs.html[message bundle]:
+
For example, when you create a new entity attribute, its name will be highlighted to remind you of creating corresponding messages for all available languages. This can be done in one click.

* Safe delete an attribute:
+
Studio will check the occurrences of this attribute in other project files.

* Add entity attribute to a screen:
+
The new window will appear for you to define whether the attribute should be added to the new table column in browser or to the editor form.

* Generate the name pattern of an entity:
+
If the `@NamePattern` annotation is not set for the entity, you can generate it and select the entity attribute for an instance name from the list.

* Register REST method.
--

Inspections::
+
--
// TODO
Inspections highlight the errors and tips in applications classes, for example, in case of visual component type mismatch for this very attribute, or when the platform reminds you to generate something important.

* Add attribute

* Create new view

* Fix duplicate property error

* Inject missing element

* Generate messages

etc
--

References::
+
--
// TODO
Enable auto-complete, code highlight and easy switch between components and files

* Class or package by FQN references

* Switch between XML descriptor and Java controller

* Message references

etc
--

include::studio_functions/studio_project_properties.adoc[]

include::studio_functions/studio_modules.adoc[]

include::studio_functions/deployment.adoc[]

include::studio_functions/data_model.adoc[]

include::studio_functions/middleware.adoc[]

include::studio_functions/generic_ui.adoc[]