:sourcesdir: ../../source

[[studio_ui]]
== Studio User Interface

The CUBA Studio (IntelliJ Edition) main window mainly repeats the conventional IntelliJ IDEA's interface laced with the following elements:

[[studio_ui_tree]]
1. *CUBA tree* tool window (by default, on the left).
+
[source, plain]
----
CUBA
    Application
            http://localhost:8080/app
    Project
        Properties
        Build Script
            build.gradle
            settings.gradle
        Modules
            global
                metadata.xml
                persistence.xml
                views.xml
            core
                app.properties
                spring.xml
            web
                web-app.properties
                web-dispatcher-spring.xml
                web-menu.xml
                web-permissions.xml
                web-screens.xml
                web-spring.xml
        Data Stores
            _MAIN_
        Deployment
            WAR Settings
            UberJAR Settings
    Data Model
    Middleware
        Services
        Beans
    Generic UI
        Web menu
        Main Message Pack
            messages.properties
        Screens
        Themes
    REST API
----

Application::
The *Application* menu allows you to switch to the web browser or an embedded browser and open the running application address.

Project Properties Editor::
+
--
*Project Properties* editor allows you to configure your project.

The *Main* tab displays the basic settings.

* The *Repositories* field display the repositories currently used in the project. Studio scans these repositories to discover what platform versions are available. Use the buttons next to the field to configure the access to repository. For more details see https://doc.cuba-platform.com/manual-latest/access_to_repo.html[documentation]. You can also manually register in `build.gradle` any number of additional repositories containing application components.

* The *Platform version* field allows you to select a version of the platform. If you choose a newer version, an automatic migration will be performed if required.

* In the *App components* panel, you can add the platform or custom application components that will be used in your project.

* If you need to change the path to the application server, specify the new path in the *Tomcat path* field. The next execution of `gradlew deploy` or `gradlew start` will install Tomcat into that location.

* The *Tomcat ports* group allows you to assign non-standard ports for the Tomcat application server installed in the `deploy/tomcat` folder as a result of https://doc.cuba-platform.com/manual-latest/fast_deployment.html[fast deployment].

* In particular, the *HTTP port* field affects the port Tomcat is listening on for HTTP connection, as well as `cuba.webPort`, `cuba.webAppUrl`, `cuba.restApiUrl` and `cuba.connectionUrlList` application properties.

* In the *AJP port* field, you can set the port for AJP Connector.

* In the *Shutdown port* field, you can set the port Tomcat is listening on for SHUTDOWN command.

* In the *Debug port* field, you can set the port Tomcat is listening on for Java debugger connection. If you change this port, you should also change it in the debug configuration of your IDE.

* *Available locales* field allows you to set https://doc.cuba-platform.com/manual-latest/localization.html[locales] used in your application. Open the locales editor by clicking the button next to the field. The *Locale select visible* checkbox located in the editor window controls the value of the https://doc.cuba-platform.com/manual-latest/app_properties_reference.html#cuba.localeSelectVisible[cuba.localeSelectVisible] application property. The editor also enables defining or overriding format strings for https://doc.cuba-platform.com/manual-latest/datatype.html[parsing and formatting data].

// TODO
* *Groovy support* checkbox DOES SOMETHING I DON'T KNOW // TODO

The *Databases* tab displays the database settings of the project.

* You can select the type of your database server in the *Database type* field. The fields below allow you to change the database URL, and specify the username, password and optional connection parameters.

* Format of connection parameters depends on the selected DBMS. The string should include a separator between the database name and parameters. For example, to specify a Microsoft SQL Server 2008+ instance name, use the following string in the field: `;instanceName=myinstance`.

* A custom database connection URL can be specified if *Custom database URL* checkbox is enabled. *Host* and *Database* name should be provided in this case, as they are used in `build.gradle` separately.

* In case of HSQLDB the Studio itself serves the database and stores its files in the `build/hsqldb` directory.

* The *Additional data stores* panel contains the list of additional https://doc.cuba-platform.com/manual-latest/data_store.html[data stores] registered in the project. The *Data store* dialog appears when you create or edit a data store. It has the following fields:
+
** *Data store name* - the name of the data store. It may contain only alphanumeric characters and underscores and should be different from the project name.
+
** *Data store type* - the type of the data store: either `RdbmsStore` or `Custom`, see the documentation for details. The fields explained below should be set in case of `RdbmsStore`.
+
** *DataSource JNDI name* - automatically set by Studio on the basis of the data store name.
+
** *Database type*, *URL*, etc. - database connection parameters.
--

Build Scripts::
The *Build Script* menu contains two main project scripts: https://doc.cuba-platform.com/manual-latest/build.gradle.html[build.gradle] (defines the build configuration) and `settings.gradle` (defines the project name and the set of modules).

Modules::
+
--
The *Modules* menu contains the application https://doc.cuba-platform.com/manual-latest/app_modules.html[modules]: by default, the *global*, *core*, and *web*.

* *global* – includes entity classes, service interfaces, and other classes common for all tiers. It is used in all https://doc.cuba-platform.com/manual-latest/app_tiers.html[application blocks]. A new empty project already contains these configuration files by dafault:
** https://doc.cuba-platform.com/manual-latest/metadata.xml.html[metadata.xml]
** https://doc.cuba-platform.com/manual-latest/persistence.xml.html[persistence.xml]
** https://doc.cuba-platform.com/manual-latest/views.xml.html[views.xml]
* *core* – implements services and all other components of the middle tier. It is used only in *Middleware*.
** https://doc.cuba-platform.com/manual-latest/app_properties.html[app.properties]
** https://doc.cuba-platform.com/manual-latest/spring.xml.html[spring.xml]
* *web* – the implementation of the generic user interface based on *Vaadin* and other specific web client classes. It is used in *Web Client* block.
** https://doc.cuba-platform.com/manual-latest/app_properties.html[web-app.properties]
** https://doc.cuba-platform.com/manual-latest/dispatcher-spring.xml.html[web-dispatcher-spring.xml]
** https://doc.cuba-platform.com/manual-latest/menu.xml.html[web-menu.xml]
** https://doc.cuba-platform.com/manual-latest/permissions.xml.html[web-permissions.xml]
** https://doc.cuba-platform.com/manual-latest/screens.xml.html[web-screens.xml]
** https://doc.cuba-platform.com/manual-latest/spring.xml.html[web-spring.xml]
--

Data Stores::
The *Data Stores* menu displays the list of https://doc.cuba-platform.com/manual-latest/data_store.html[data stores] the project is connected to. By default, it contains only one `_MAIN_` data store.

Deployment::
+
--
The *Deployment* menu is used to set up the https://doc.cuba-platform.com/manual-latest/deployment_variants.html[deployment options].

* *WAR Settings* page allows you to set up the deployment to WAR file. After completing the setup, the https://doc.cuba-platform.com/manual-latest/build.gradle_buildWar.html[buildWar] task will be created in your `build.gradle`.
** *Build WAR* - if checked, the `buildWar` task is configured in `build.gradle`.
** *Include JDBC driver* - whether JDBC driver should be included in WAR file.
** *Include Tomcat's context.xml* - whether `context.xml` (Tomcat deployment descriptor) should be included in WAR file.
** *Custom context.xml path* - a path relative to the project root to the `context.xml` Tomcat deployment descriptor. Enabled if *Include Tomcat's context.xml* is checked. Click *Generate* to create this file automatically.
** *Single WAR for Middleware and Web Client* - whether to build a single WAR comprising the Middleware and Web Client application blocks.
** *Custom web.xml path* is the file to be used as a special `web.xml` of the single WAR. Click *Generate* to create this file automatically.
** *Logback configuration file* - a path relative to the project root to the `logback.xml` configuration file. Click *Generate* to create this file automatically.
** *App properties* - a set of application properties to define for this deployment. The properties will be added to the `/WEB-INF/local.app.properties` file inside the WAR.
* *UberJAR Settings* page allows you to set up deployment to Uber JAR. After completing the setup, the https://doc.cuba-platform.com/manual-latest/build.gradle_buildUberJar.html[buildUberJar] task will be created in your `build.gradle`.
** *Build Uber JAR* - if checked, the `buildUberJar` task is configured in `build.gradle`.
** *Single Uber JAR* - if checked, the `buildUberJar` task creates a single Uber JAR from all application modules.
** *Logback configuration file* - a path relative to the project root to the `logback.xml` configuration file. Click *Generate* to create this file automatically.
** *Custom Jetty environment file* - a path relative to the project root to the `jetty-env.xml` configuration file to be used by the embedded Jetty server. Required field. Click *Generate* to create this file automatically.
** *App properties* - a set of application properties to define for this deployment. The properties will be added to the `/WEB-INF/local.app.properties` file inside the Uber JARs.
** *Core port, Web port, Portal port* fields allow you to set ports for the embedded servers of the corresponding application blocks. Not available if Single Uber JAR checked. Default port values are described in the https://doc.cuba-platform.com/manual-latest/build.gradle_buildUberJar.html[documentation]. You can also set ports when running the JARs using the `-port` command line argument.
--

Data model::
+
--
The *Data model* section shows the https://doc.cuba-platform.com/manual-latest/data_model.html[data model] of your project.

* Select *New* in the context menu to create a new entity or enumeration class. If you select an existing entity beforehand, the context menu will also enable you to create a new https://doc.cuba-platform.com/manual-latest/views.html[view] or a UI screen for the selected entity.
* The *Generate DB scripts* command in the context menu automatically generates https://doc.cuba-platform.com/manual-latest/db_scripts.html[initialization and update scripts] for your project's database and opens the *Database scripts* page that allows you to review and save these scripts.
* The *Generate model* command allows you to create data model and standard UI screens for an existing database.
--

Middleware::
The *Middleware* section enables creating stubs for middleware https://doc.cuba-platform.com/manual-latest/services.html[services], https://doc.cuba-platform.com/manual-latest/managed_beans.html[beans], https://doc.cuba-platform.com/manual-latest/entity_listeners.html[entity listeners] and https://doc.cuba-platform.com/manual-latest/transaction_listeners.html[transaction listeners].

Generic UI::
+
--
The *Generic UI* section shows the https://doc.cuba-platform.com/manual-6.10/gui_framework.html[Generic UI] screens, themes and messages of your project.

* *Web menu* allows you to open the menu editor of the corresponding module.
* https://doc.cuba-platform.com/manual-latest/main_message_pack.html[Main Message Pack] contains messages for main menu entries and common UI elements names.
* https://doc.cuba-platform.com/manual-latest/screens.html[Screens] displays the created application screens.
* https://doc.cuba-platform.com/manual-latest/gui_themes.html[Themes] are used to manage the visual presentation of the application.
--

REST API::
The *REST API* section allows you to configure the https://doc.cuba-platform.com/manual-latest/rest_api_v2.html[REST API] functionality.

[[studio_ui_menu]]
2. The CUBA menu in the top toolbar containing the base functionality on the project level. Partially it repeats the functionality described above but mostly is less-specific.
+
[source, plain]
----
CUBA
    Project Browser
    Project Properties
    --------
    Start Application Server
    Stop Application Server
    Restart Application Server
    --------
    Generate Database Scripts
    Create Database
    Update Database
    --------
    Build Tasks
            Assemble
            Clean
            Deploy
            Undeploy
            Hot Deploy To Configuration Directory
            Cleanup Configuration Directory
    --------
    Deployment
                War Settings
                UberJAR Settings
    --------
    Advanced
                Generate Model
                Define Custom Database
                Manage Modules
                            Create module
                            Remove module
                App Component Descriptor
                Install App Component
                Manage Themes
                            Create Theme Extension
                            Creae Custom Theme
    --------
    Settings
----