:sourcesdir: ../../source

[[studio_functions]]
== Studio Functionality

In addition to the functionality described in the <<studio_ui,Studio User Interface>> section, CUBA Studio provides a lot of implicit developer-friendly features that boost the coding process.

////
All these features can be broadly divided into four categories:

* Actions
* Intentions
* Inspections
* References

Actions::
+
--
Global actions on the project level are available from <<studio_ui_menu,CUBA menu>>, while finer-grained actions can be found in <<studio_ui_tree,CUBA tree>> tool window and in the context menu of its elements.

List of most common used actions:

Generic UI::
* Create {main_man_url}/web_theme_extension.html[theme extension],
* Edit theme variables,
* Create a {main_man_url}/web_theme_creation.html[custom theme],
* Generate event handlers,
* Create screens, including entity {main_man_url}/screen_lookup.html[browser] and {main_man_url}/screen_edit.html[editor].

REST API::
* Create predefined {main_man_url}/rest_api_v2_queries_config.html[REST query] configuration,
* Create {main_man_url}/rest_api_v2_services_config.html[REST service] configuration.

Build actions::
* Assemble the project,
* Clean the project,
* Create or update Gradle wrapper,
* Update IDEA project files.

Run actions::
* {main_man_url}/build.gradle_deploy.html[Deploy] and undeploy the application,
* Perform {main_man_url}/hot_deploy.html[hot deploy],
* Start, restart or stop the application,
* Open application in a web- or an embedded browser.

Deployment settings::
* Configure deployment to UberJAR,
* Configure deployment to WAR.

Application components::
* Create {main_man_url}/app_components_recipes.html[app component] descriptor,
* Install application component.
--

Intentions::
+
--
Intentions are suggested to the developer on Alt+Enter click.

* Safe delete an attribute:
+
Studio will check the occurrences of this attribute in other project files.

* Add entity attribute to a screen:
+
The new window will appear for you to define whether the attribute should be added to the new table column in browser or to the editor form.

* Register REST method.
--

Inspections::
+
--
// TODO
Inspections highlight the errors and tips in applications classes, for example, in case of visual component type mismatch for this very attribute, or when the platform reminds you to generate something important.

* Add attribute

* Create new view

* Fix duplicate property error

* Inject missing element

* Generate messages

etc
--

References::
+
--
// TODO
Enable auto-complete, code highlight and easy switch between components and files

* Class or package by FQN references

* Switch between XML descriptor and Java controller

* Message references

etc
--
////

include::studio_functions/studio_project_properties.adoc[]

include::studio_functions/studio_modules.adoc[]

include::studio_functions/deployment.adoc[]

include::studio_functions/data_model.adoc[]

include::studio_functions/middleware.adoc[]

include::studio_functions/generic_ui.adoc[]