:sourcesdir: ../../source

[[update]]
== Update

[[update_ide]]
Updating the standalone IDE::
+
--
You can just download the newer version of the standalone Studio IDE from the https://www.cuba-platform.com/download[website] and install it on top of the existing version. All your settings will be preserved.

Instead of downloading and installing the entire IDE application, you can set up automatic update of the CUBA plugin from the plugins repository:

. Open the *Plugins* dialog.

. Click to the "gear" icon and select *Manage Plugin Repositories*.

. Click *Add* and enter the following in the *Repository URL* field:
+
----
https://plugins.jetbrains.com/plugins/haulmont/list
----

. After adding the repository, switch to the *Updates* tab.

. If there are updates available, you will see them in the list. Click *Update* for the CUBA plugin, and the IDE will download the plugin.

. After the download process completes, you will have to restart the IDE to apply the new version of the plugin.
--

[[update_plugin]]
Updating IntelliJ IDEA plugin::
+
--
. Click *Help > Check for Update* on Windows and Linux or *IntelliJ IDEA > Check for Updates* on macOS.

. If there are updates available, you will see them in the list. Select the CUBA plugin and click *Update*. The IDE will download the plugin.

. After the download process completes, you will have to restart the IDE to apply the new version of the plugin.
--