:sourcesdir: ../../../../../source

[[app_properties_files]]
===== Хранение свойств в файлах

Свойства, определяющие конфигурацию и параметры развертывания, задаются в специальных файлах свойств, имеющих имя вида `++*app.properties++`. Каждый <<app_tiers,блок>> приложения имеет набор таких файлов, который задается в <<web.xml,web.xml>> в параметре `appPropertiesConfig`.

Например, набор файлов свойств блока Middleware задается в файле `web/WEB-INF/web.xml` модуля `core`, и выглядит следующим образом:

[source, xml]
----
<context-param>
    <param-name>appPropertiesConfig</param-name>
    <param-value>
        classpath:com/company/sample/app.properties
        /WEB-INF/local.app.properties
        "file:${app.home}/local.app.properties"
    </param-value>
</context-param>
----

Здесь префикс `classpath:` означает, что данный файл нужно искать в Java classpath, префикс `file:` − в файловой системе. Путь без такого префикса означает путь внутри веб-приложения относительно его корня. Возможно использование системных свойств Java, в данном случае `app.home` содержит путь к <<app_home,домашнему каталогу>> приложения.

Порядок перечисления файлов важен, так как значения, указанные в каждом последующем файле, заменяют значения одноименных свойств, заданные в предыдущих файлах. Если некоторого файла нет, он игнорируется.

Последний файл в приведенном наборе − `local.app.properties`. Он может использоваться для переопределения свойств приложения при развертывании.

[TIP]
====
Правила задания информации в файлах `*.properties`:

* Кодировка файла - `UTF-8`

* Ключ может состоять из латинских букв, цифр, точек и знаков подчеркивания

* Значение пишется после знака равно (`=`)

* Значение не нужно брать в кавычки " или '

* Файловые пути записываются либо в UNIX-виде (`/opt/haulmont/`), либо в Windows-виде (`c:\\haulmont\\`)

* Возможно использование кодов `\n \t \r`. Символ `\` является зарезервированным, для вставки в значение экранируется сам собой (`\\`). Подробнее см.: link:$$http://docs.oracle.com/javase/tutorial/java/data/characters.html$$[http://docs.oracle.com/javase/tutorial/java/data/characters.html]

* Для ввода значения в нескольких строках файла используйте символ `\` в конце строки, для того чтобы данное значение продолжалось на следующей строке.

====

