:sourcesdir: ../../../../../source

[[config_interfaces]]
===== Конфигурационные интерфейсы

Данный механизм позволяет работать со свойствами приложения через методы Java-интерфейсов, что дает следующие преимущества:

* Типизированность - прикладной код работает с нужными типами (String, Boolean, Integer и пр.), а не только со строками.

* В прикладном коде вместо строковых идентификаторов свойств используются методы интерфейсов, имена которых проверяются компилятором и подсказываются средой разработки.

Пример получения значения таймаута транзакции в блоке Middleware:

[source, java]
----
include::{sourcesdir}/common/configinterface_1.java[]
----

При невозможности инжекции можно получить ссылку на конфигурационный интерфейс через <<configuration,Configuration>>:

[source, java]
----
include::{sourcesdir}/common/configinterface_2.java[]
----

[WARNING]
====
Конфигурационные интерфейсы не являются нормальными бинами Spring, не пытайтесь получить их через `AppBeans.get()` - только непосредственной инжекцией самого интерфейса или через `Configuration.getConfig()`.
====

include::config_interfaces/config_interface_usage.adoc[]

include::config_interfaces/config_interface_property_types.adoc[]

include::config_interfaces/config_interface_default_values.adoc[]

