:sourcesdir: ../../../../../source

[[managed_beans_creation]]
===== Создание бина

Для создания управляемого бина достаточно добавить классу Java аннотацию `@org.springframework.stereotype.Component`. Например:

[source, java]
----
include::{sourcesdir}/common/managedbean_1.java[]
----

Рекомендуется присваивать бину уникальное имя вида `++{имя_проекта}_{имя_класса}++`, и определять его в константе `NAME`. 

[TIP]
====
Аннотация `@javax.annotation.ManagedBean` также может ипользоваться для определения бина, однако ее наличие может вызывать проблемы при развертывании в некоторые сервера приложений. Поэтому мы рекомендуем использовать только аннотацию `@Component` из Spring Framework.
====


Класс управляемого бина должен находиться внутри дерева пакетов с корнем, заданным в элементе `context:component-scan` файла <<spring.xml,spring.xml>>. В нашем случае файл `spring.xml` содержит элемент:

[source, xml]
----
<context:component-scan base-package="com.sample.sales"/>
----

что означает, что поиск аннотированных бинов для данного блока приложения будет происходить начиная с пакета `com.sample.sales`.

Управляемые бины можно создавать на любом <<app_tiers,уровне>>, так как контейнер Spring Framework используется во всех стандартных блоках приложения.

