= CUBA Platform. Workflow Subsystem
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 7.1
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)

:!sectnums:

[[preface]]
[preface]
== Preface

This document is the user manual for the CUBA Platform Workflow Subsystem.

=== Target Audience

This manual is intended for developers who use the CUBA platform to create applications with _business processes_ management functionality. It is assumed that the reader is familiar with the *Developer's Manual*, which is available at https://www.cuba-platform.com/manual.

=== Additional Materials

This manual, as well as other documentation on the CUBA platform, are available at https://www.cuba-platform.com/manual.

=== Feedback

If you have any suggestions for improving this manual, please contact Technical Support at https://www.cuba-platform.com/support/topics.

When reporting errors in the documentation, please indicate the chapter number and include a small portion of the surrounding text to make the search easier. 

:sectnums:

include::chapter1.adoc[]

include::chapter2.adoc[]

[[appendix_workflow_properties]]
[appendix]
== Application Properties

This section lists the application properties relevant to the Workflow subsystem.

workflow.designerUrl::
File path to load the visual designer host-HTML file, relative to the URL of the web application.
+
Default value: `wfdesigner/workflow/main.ftl`
+
Interface: `WfConfig`
+
Used in the Web Client block.

