:sourcesdir: ../../../../../../source

[[abstractFrame]]
====== AbstractFrame

`AbstractFrame` is the root of the controller classes hierarchy. Below is the description of its main methods:

[[abstractFrame_init]]
* `init()` is called by the framework after creating components tree described by an XML-descriptor, but before a screen is displayed.
+
--
`init()` method accepts a map of parameters that can be used in controller. These parameters can be passed both from the controller of the calling screen (using `openWindow()`, `openLookup()` or `openEditor()` methods) or defined in the screen registration file <<screens.xml,screens.xml>>.

`init()` method should be implemented if it is necessary to initialize screen components, for example:

[source, java]
----
include::{sourcesdir}/gui/abstractframe_1.java[]
---- 
--

[[abstractFrame_getMessage]]
* `getMessage()`, `formatMessage()` – methods for retrieving localized messages from a <<message_packs,pack>>, defined for a screen in the XML-descriptor. They work as shortcuts for calling the corresponding methods of the <<messages,Messages>> interface.

[[abstractFrame_openFrame]]
* `openFrame()` – loads a frame according to an identifier registered in <<screens.xml,screens.xml>> file. If the method receives a container component from the invoking code, the frame is shown within the container. The method returns frame controller. For example:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_3.java[]
---- 
+
It is not required to pass the container immediately via `openFrame()` method, instead it is possible to load the frame first and then add it to the necessary container: 
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_4.java[]
---- 

[[abstractFrame_openWindow]]
* `openWindow()`, `openLookup()`, `openEditor()` – open a simple screen, a lookup screen, or an edit screen respectively. Methods return a controller of the created screen.
+
For the dialog mode, the method `openWindow()` can be called with parameters, for example:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_7.java[]
----
These parameters will be considered if they don't conflict with the higher-priority parameters of the window being opened. The latter can be set either in the <<dialogOptions,getDialogOptions()>> method of screen controller or in <<screen_xml,XML descriptor>> of the screen:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_8.xml[]
----
+
`CloseListener` can be added in order to perform actions after the invoked screen closes, for example: 
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_5.java[]
---- 
+
Use `CloseWithCommitListener` to be notified only when the invoked screen closes by an action with the `Window.COMMIT_ACTION_ID` name (i.e. *OK* button), for example:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_5_1.java[]
----

[[abstractFrame_showMessageDialog]]
* `showMessageDialog()` – shows a dialog box with a message.

[[abstractFrame_showOptionDialog]]
* `showOptionDialog()` – shows a dialog box with a message and an option for user to invoke certain actions. Actions are defined by an array of <<gui_Action,Action>> type items displayed as buttons in the dialog.
+
It is recommended to use `DialogAction` objects for display of standard buttons such as *OK*, *Cancel* and other, for example:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_6.java[]
---- 

[[abstractFrame_showNotification]]
* `showNotification()` – shows a pop up notification.

[[abstractFrame_showWebPage]]
* `showWebPage()` – opens specified web page in a browser.

'''

API::
<<abstractFrame_getMessage,formatMessage()>> -
<<abstractFrame_getMessage,getMessage()>> -
<<abstractFrame_init,init()>> -
<<abstractFrame_openFrame,openFrame()>> -
<<abstractFrame_openWindow,openEditor()>> -
<<abstractFrame_openWindow,openLookup()>> -
<<abstractFrame_openWindow,openWindow()>> -
<<abstractFrame_showMessageDialog,showMessageDialog()>> -
<<abstractFrame_showNotification,showNotification()>> -
<<abstractFrame_showOptionDialog,showOptionDialog()>> -
<<abstractFrame_showWebPage,showWebPage()>>

