:sourcesdir: ../../../../../../source

[[companions]]
====== Controller Companions

Controller base classes are located in the *gui* <<app_modules,module>> of the *cuba* <<app_components,application component>> and do not contain references to the implementation of visual component classes (*Swing* or *Vaadin*). This allows you to use them in both types of clients.

At the same time concrete controller classes can be created in *gui*, *web* or *desktop* modules, depending on screen specifics and client <<app_tiers,blocks>> used in the project. If a controller is common for all client types but additional functionality is required for different client types, it can be implemented in so-called _companion classes_.

Companion class is located in client module of the corresponding client type (web or desktop) and implements an interface defined in the controller that uses the companion class. A companion class should be defined in the `companions` element of the screen XML-descriptor. Controller can retrieve a reference to the companion instance using injection or by invoking `getCompanion()`, and then pass control to the companion instance when appropriate, e.g. for extended initialization of visual components in a way specific to a given client type.

For example, on some screen, you need to initialize a table differently for web and desktop clients. Then in the screen controller located in *gui* module, define a companion interface and delegate the table initialization to it:

[source, java]
----
include::{sourcesdir}/gui/companion_1.java[]
----

Create companion implementations in *web* and *desktop* modules:

[source, java]
----
include::{sourcesdir}/gui/companion_2.java[]
----

[source, java]
----
include::{sourcesdir}/gui/companion_3.java[]
----

And register the implementation classes in the screen XML descriptor:

[source, xml]
----
include::{sourcesdir}/gui/companion_4.xml[]
----

The companion classes are located in *web* and *desktop* modules, therefore you can use  <<webComponentsHelper,WebComponentsHelper.unwrap()>> and <<desktopComponentsHelper,DesktopComponentsHelper.unwrap()>> to get references to Vaadin and Swing components implementing the table.

