:sourcesdir: ../../../../../source

[[build.gradle_createDb]]
===== createDb

`createDb` – the task of the `CubaDbCreation` type which creates application database by executing the corresponding <<db_scripts,scripts>>. It is declared in the *core* module. Parameters:

* `dbms` – the <<dbms_types, DBMS type>>, specified as the string `hsql`, `postgres`, `mssql`, or `oracle`.

* `dbName` – the database name.

* `dbUser` – the DBMS username.

* `dbPassword` – the DBMS user password.

* `host` – the DBMS host and port (optional) in the `host[:port]` format. If not specified, `localhost` is used.

* `connectionParams` - an optional connection parameters string which will be appended to the end of the connection URL.

* `masterUrl` – the URL used to connect when creating the database. If not specified, the default value that depends on the DBMS type and the `host` parameter is used.

* `dropDbSql` – the SQL command to delete the database. If not specified, the default value that depends on the DBMS type is used.

* `createDbSql` – the SQL command to create a database. If not specified, the default value that depends on the DBMS type is used.

* `driverClasspath` – the list of JAR files containing the JDBC driver. The items in the list are separated by ":" on Linux and by ";" on Windows. If not specified, the system uses the dependencies that are part of the current module's `jdbc` configuration. Explicit definition of `driverClasspath` is necessary when using Oracle, because its JDBC driver is not available in the dependencies.

* `oracleSystemPassword` – the SYSTEM user password for Oracle.

Example for PostgreSQL:

[source, groovy]
----
task createDb(dependsOn: assemble, description: 'Creates local database', type: CubaDbCreation) {
    dbms = 'postgres'
    dbName = 'sales'
    dbUser = 'cuba'
    dbPassword = 'cuba'
}
----

Example for MS SQL Server:

[source, groovy]
----
task createDb(dependsOn: assemble, description: 'Creates local database', type: CubaDbCreation) {
    dbms = 'mssql'
    dbName = 'sales'
    dbUser = 'sa'
    dbPassword = 'saPass1'
    connectionParams = ';instance=myinstance'
}
----

Example for Oracle:

[source, groovy]
----
task createDb(dependsOn: assemble, description: 'Creates database', type: CubaDbCreation) {
    dbms = 'oracle'
    host = '192.168.1.10'
    dbName = 'orcl'
    dbUser = 'sales'
    dbPassword = 'sales'
    oracleSystemPassword = 'manager'
    driverClasspath = "$tomcatDir/lib/ojdbc6.jar"
}
----

