:sourcesdir: ../../../../../source

[[build.gradle_buildInfo]]
===== buildInfo

The `buildInfo` task is automatically added to your `global` module configuration by the CUBA Gradle plugin. It writes the `build-info.properties` file with the information about your application into the `global` artifact (e.g. `app-global-1.0.0.jar`). This information is read by the `BuildInfo` bean at runtime and is displayed on the *Help > About* window. This bean can also be invoked by different mechanisms to get the information about the application name, version, etc.

You can optionally change the following task parameters:

* `appName` - application name. By default, the project name set in `settings.gradle` is used.

* `artifactGroup` - artifact group, which is by convention equal to the root package of the project.

* `version` - application version. By default, the version set in the `cuba.artifact.version` property is used.

* `properties` - a map of arbitrary properties, empty by default.

Example of specifying custom properties of the `buildInfo` task:

[source, groovy]
----
include::{sourcesdir}/development/build_gradle_buildInfo_1.groovy[]
----

