:sourcesdir: ../../../source

[[overview]]
=== Обзор платформы

Платформа CUBA предназначена для разработки корпоративных решений, характеризующихся сложной моделью данных, десятками или сотнями экранов, большим количеством бизнес-логики, а также требованиями к контролю прав доступа, масштабируемости и отказоустойчивости.

Широкий набор готовой функциональности, развитые средства генерации кода, визуальный дизайнер интерфейсов, а также поддержка hot deploy радикально сокращают время и стоимость разработки решения.

Платформа полностью построена на стеке открытых Java технологий, что позволяет использовать наработки крупнейшей экосистемы свободного ПО в мире, а также контролировать исходный код всего стека. Открытая архитектура позволяет переопределять поведение большинства механизмов платформы, обеспечивая высокую гибкость. Разработчики могут использовать популярные Java IDE и имеют полный доступ к исходному коду.

Приложения на платформе легко встраиваются в ИТ-инфраструктуру благодаря поддержке основных баз данных и серверов приложений, а также возможности работы в облаке. Платформа позволяет обеспечить отказоустойчивость и масштабируемость решений, а универсальный REST API предоставляет средства интеграции с внешними системами.

