:sourcesdir: ../../../../source

[[db_connection]]
==== Подключение к базам данных

CUBA-приложение получает соединение с базой данных через JDBC `DataSource`. Источник данных может быть сконфигурирован в приложении или получен из JNDI. Способ получения источника данных задается свойством приложения `cuba.dataSourceProvider`: его значение может быть либо `application`, либо `jndi`.

Соединения с главным и дополнительным хранилищами можно легко сконфигурировать в CUBA Studio, см. его {studio_man_url}/#data_stores[документацию]. Информация, приведенная ниже, может быть полезна при поиске проблем и при необходимости задания параметров, недоступных в Studio, например параметров пула соединений.

[[db_connection_app]]
Конфигурирование источника данных в приложении::
+
--
++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

Если источник данных сконфигурирован в приложении, фреймворк создает пул соединений используя https://github.com/brettwooldridge/HikariCP[HikariCP]. При этом и параметры соединения, и параметры пула задаются <<app_properties,свойствами приложения>>, расположенными в файле `app.properties` модуля `core`. Данный способ является рекомендуемым, если вам не нужен специфический пул соединений, предоставляемый сервером приложения.

Следующие свойства приложения задают тип БД и параметры соединения:

* `cuba.dbmsType` - задает <<dbms_types,тип СУБД>>.
* `cuba.dataSourceProvider` - значение `application` указывает, что источник данных должен быть сконфигурирован свойствами приложения.
* `cuba.dataSource.username` - имя пользователя БД.
* `cuba.dataSource.password` - пароль пользователя БД.
* `cuba.dataSource.dbName` - имя БД.
* `cuba.dataSource.host` - имя хоста сервера БД.
* `cuba.dataSource.port` - необязательный параметр, задает порт сервера БД, если он отличается от стандартного для данного типа СУБД.
* `cuba.dataSource.jdbcUrl` - необязательный параметр, задает полный JDBC URL если необходимо передать дополнительные параметры соединения. При этом все остальные отдельные параметры описанные выше все равно необходимы для работы <<db_update_gradle,задач миграции>>.

Для конфигурирования параметров пула соединений необходимо указать свойства HikariCP с префиксом `cuba.dataSource.`, например `cuba.dataSource.maximumPoolSize` или `cuba.dataSource.connectionTimeout`. См. полный список поддерживаемых свойств и их значений по умолчанию в https://github.com/brettwooldridge/HikariCP#frequently-used[документации] по HikariCP.

Если в вашем приложении используются дополнительные <<data_store,хранилища>>, необходимо указать такой же набор параметров для каждого хранилища. При этом имя хранилища добавляется ко второй части имени свойства:

Например:
[source, properties]
----
include::{sourcesdir}/dbms/db_connection_1.properties[]
----

Кроме того, для каждого хранилища необходимо в файле `spring.xml` модуля `core` задать определение бина `CubaDataSourceFactoryBean` с соответствующим параметром `storeName`. Например:

[source,xml]
----
include::{sourcesdir}/dbms/db_connection_2.xml[]
----

Если источник данных сконфигурирован в приложении, задачи Gradle по миграции БД могут не иметь параметров, так как они могут быть получены из свойств приложения. Это является дополнительным преимуществом данного способа определения источника даннных. Например:

[source,groovy]
----
include::{sourcesdir}/dbms/db_connection_3.groovy[]
----
--

[[db_connection_jndi]]
Получение источника данных из JNDI::
+
--
Если необходимо использовать источник данных, предоставляемый сервером приложения через JNDI, задайте следующие свойства приложения в файле `app.properties` модуля `core`:

* `cuba.dbmsType` - задает <<dbms_types,тип СУБД>>.
* `cuba.dataSourceProvider` - значение `jndi` указывает, что источник данных должен быть получен из JNDI.

JNDI-имя источника данных задается свойством <<cuba.dataSourceJndiName,cuba.dataSourceJndiName>>, которое по умолчанию имеет значение `java:comp/env/jdbc/CubaDS`. Для дополнительных хранилищ необходимо задать свойство с таким же именем, но с добавлением имени хранилища.

Например:
[source, properties]
----
include::{sourcesdir}/dbms/db_connection_4.properties[]
----

Кроме того, для каждого хранилища необходимо в файле `spring.xml` модуля `core` задать определение бина `CubaDataSourceFactoryBean` с соответствующими параметрами `storeName` и `jndiNameAppProperty`. Например:

[source,xml]
----
include::{sourcesdir}/dbms/db_connection_5.xml[]
----

Источники данных, получаемые из JNDI конфигурируются специфичным для используемого сервера приложения способом. Для Tomcat это делается в файле <<context.xml>>. CUBA Studio записывает параметры соединения в файл `modules/core/web/META-INF/context.xml` и использует его в процессе <<fast_deployment,стандартного развертывания>> при разработке приложения.

Если источник данных сконфигурирован в `context.xml`, задачи миграции БД должны иметь собственные параметры подключения к БД, например:

[source,groovy]
----
include::{sourcesdir}/dbms/db_connection_6.groovy[]
----
--

include::db_connection/db_schema_connection.adoc[]
