:sourcesdir: ../../../../source

[[db_scripts]]
==== Скрипты создания и обновления БД

Проект CUBA-приложения всегда содержит два набора скриптов (см. также раздел <<db_update_in_dev,>>):

* Скрипты _создания_ БД, предназначенные для создания базы данных с нуля. Они содержат набор DDL и DML операторов, после выполнения которых на пустой БД схема базы данных полностью соответствует текущему состоянию <<data_model,модели данных>> приложения. Скрипты создания могут также наполнять БД необходимыми первичными данными.

* Скрипты _обновления_ БД - предназначены для поэтапного приведения структуры БД к текущему состоянию модели данных.

При изменении модели данных необходимо отразить соответствующее изменение схемы БД и в скриптах создания, и в скриптах обновления. Например, при добавлении атрибута `address` в сущность `Customer`, нужно:

. Изменить оператор создания таблицы в скрипте создания:
+
[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_1.sql[]
----

. Добавить скрипт обновления, содержащий оператор модификации таблицы:
+
[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_2.sql[]
----
+
[TIP]
====
Обратите внимание, что генератор скриптов Studio не отслеживает изменения *Column definition* и `sqlType` специализированных <<datatype,datatype>>. Таким образом, при их изменении соответствующие скрипты обновления необходимо создавать вручную.
====

Скрипты создания располагаются в каталоге `/db/init` модуля *core*. Для каждого типа СУБД, поддерживаемой приложением, создается свой набор скриптов и располагается в подкаталоге с именем, соответствующим свойству приложения <<cuba.dbmsType,cuba.dbmsType>>, например, `/db/init/postgres`. Имена скриптов создания должны иметь вид `{optional_prefix}create-db.sql`.

Скрипты обновления располагаются в каталоге `/db/update` модуля *core*. Для каждого типа СУБД, поддерживаемой приложением, создается свой набор скриптов и располагается в подкаталоге с именем, соответствующим свойству приложения <<cuba.dbmsType,cuba.dbmsType>>, например, `/db/update/postgres`.

Скрипты обновления могут быть двух типов: с расширением `++*.sql++` или с расширением `++*.groovy++`. SQL-скрипты являются основным средством обновления базы данных. Groovy-скрипты выполняются только <<db_update_server,механизмом запуска скриптов БД сервером>>, поэтому применяются в основном на этапе эксплуатации приложения - как правило, это процессы миграции или импорта данных, которые невозможно реализовать на SQL. Чтобы пропустить скрипты Groovy при обновлении, вы можете выполнить следующую команду из командной строки:

[source, sql]
----
delete from sys_db_changelog where script_name like '%groovy' and create_ts > (now() - interval '1 hour')
----

Скрипты обновления должны иметь имена, которые при сортировке в алфавитном порядке образуют правильную последовательность их выполнения (обычно это хронологическая последовательность их создания). Поэтому при ручном создании рекомендуется задавать имя скрипта обновления в виде `{yymmdd}-{description}.sql`, где `yy` - год, `mm` - месяц, `dd` - день, `description` - краткое описание скрипта. Например, `121003-addCodeToCategoryAttribute.sql`. Studio при автоматической генерации скриптов также придерживается этого формата.

Чтобы groovy-скрипты также выполнялись командой `updateDb`, они обязательно должны иметь расширение `.upgrade.groovy` и ту же логику именования, что и sql-скрипты. Действия из набора `Post update` в этих скриптах не поддерживаются, для привязки к данным используются стандартные <<db_scripts_groovy,переменные>> `ds` (доступ к источнику данных) и `log` (доступ к журналу сервера). Выполнение groovy-скриптов можно запретить, прописа `executeGroovy = false` в команде `updateDb` в `build.gradle`.

Скрипты обновления можно группировать в подкаталоги, главное, чтобы путь к скрипту с учетом подкаталога не нарушал хронологической последовательности. Например, можно создавать подкаталоги по номеру года или по году и месяцу.

В развернутом приложении скрипты создания и обновления БД располагаются в специальном <<db_dir,каталоге скриптов базы данных>>, задаваемым свойством приложения <<cuba.dbDir,cuba.dbDir>>.

include::db_scripts/db_scripts_sql.adoc[]

include::db_scripts/db_scripts_groovy.adoc[]

