:sourcesdir: ../../../source

[[cuba__rest]]
=== Using Services and Queries

In most cases, applications are not limited to CRUD operations with entities. CUBA REST API provides special endpoints for invoking middleware {manual-address}/rest_api_v2_services_config.html[services] and running predefined {manual-address}/rest_api_v2_queries_config.html[queries]. These are places where you can put your business logic and invoke it from the front-end using the https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-service[cuba-service] and https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-query[cuba-query] components.

By default, the components automatically load data on initialization.
You can disable this behavior by assigning `false` to property `auto` and calling `load()` method programmatically.

*Usage example*

[source, html]
----
    <cuba-query id="query"
                entity-name="sec$User"
                query-name="usersByName"
                data="{{users}}">
    </cuba-query>
    ...
    <cuba-service service-name="cuba_ServerInfoService"
                  method="getReleaseNumber"
                  data="{{releaseNumber}}">
    </cuba-service>
----

https://cuba-elements.github.io/cuba-elements/components/cuba-form/#cuba-service-form[cuba-service-form] can be used instead of `cuba-service` when it's semantically more correct to use form submit
instead of information requests. However, it's not mandatory, and under the hood they use the same REST API.

