:sourcesdir: ../../../source

[[cuba__entities]]
=== Working with Entities

CUBA provides a number of components for CRUD operations with entities.

Before we proceed, it's worth to remind some basic concepts related to entities:

--
* _Entity name_ uniquely identifies the class of entity. It consists of two parts divided by "$": `{namespace$concept}`.
For example: `taxi$Driver`, `statistics$FieldDescription`, etc.
On the middleware, an entity name is specified in the `@Entity` annotation of the entity Java class.

* _Entity view_ is a descriptor of what attributes of the entity and its related entities should be loaded from the database.
For the sake of performance, a view should contain a minimal possible number of attributes.
See more in the {manual-address}/views.html[Developer's Manual].
--

Entity browse::
+
--
* The https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entities[cuba-entities] component is designed for loading a list of entities.

* The https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entity[cuba-entity] component is designed for loading one entity instance by its id.

Below is an example of how these components can be used - a book browser application.
A user sees a list of books and can select any book to see its details.

The list of books is loaded by `cuba-entities`, `cuba-entity` is used to re-load a particular book. When we show a list of books we load as little information as possible for better performance.
When a single book is selected by the user, we can afford loading a lot more: author biography, editions, even a photo of a cover page.

*Book browser*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/src/cuba/entity/stub/cuba-books-browser-stub.html"></iframe>
++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/entity/books-browser.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <books-browser></books-browser>
</body>
</html>
----

.src/cuba/entity/books-browser.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/entity/books-browser.html[]
----

In this example we have omitted a code for login simplicity.
In real applications, REST API won't work until you login or enable {manual-address}/rest_api_v2_anonymous.html[anonymous access].
--

Entity creation::
+
--
The `cuba-entity-form` component provides an ability to create new entities.
Basically, you have to provide an entity name and an entity instance you want to persist. After that, you can call the `submit` method and the entity will be saved.

*Book creator*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/src/cuba/entity/stub/cuba-book-creator-stub.html"></iframe>
++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/entity/book-creator.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <book-creator></book-creator>
</body>
</html>
----

.src/cuba/entity/book-creator.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/entity/book-creator.html[]
----
--

Entity removal::
+
--
The `cuba-entities` component has method `remove()`, which you can use to remove an entity instance.
--

Entity update::
+
--
Entity can be updated using the `cuba-entity-form` component.
--

Conclusion::
+
--
That was an overview of how CUBA Polymer components can be used to work with entities.
But the components provide more functionality than was described in this section. For example,
`cuba-entity` allows you to set the `debounce` parameter to avoid excessive requests to a server;
`cuba-entities` can sort entities by any field;
and so on. To learn more, check out the public API at https://cuba-elements.github.io/cuba-elements and the source code of components.
--

