:sourcesdir: ../../../source

[[cuba_rest_js]]
=== cuba-rest-js Library

Under the hood, <<cuba_app,cuba-app>> uses the https://github.com/cuba-platform/cuba-rest-js[cuba-rest-js] library.
This library provides a convenient methods for working with CUBA REST API, such as:

* `login(login: string, password: string, options: object): Promise`.

* `loadEntities(entityName: string, optoins: object): Promise`.

* `getUserInfo(): Promise`.

* and so on.

As you can see, a lot of methods return promises. You can read about promises in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[MDN documentation].

In some cases you may want to use this API directly instead of using CUBA Polymer components.
It can be achieved by implementing the `CubaAppAwareBehavior` behavior.
This behavior provides the `app` property that has public API mentioned above.

For example, below is a simple application that shows an information about the currently authenticated user.

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/init/user-info-component.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <user-info-component></user-info-component>
</body>
</html>
----

.src/cuba/init/user-info-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/init/user-info-component.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="150"
        class="polymer-iframe-container"
        src="html/src/cuba/init/stub/user-info-component-stub.html"></iframe>
++++

Content of the `userInfo` object is described in the REST API Swagger http://files.cuba-platform.com/swagger/{revnumber}[documentation].

The way we extended `CubaAppAwareBehavior` might seem unintuitive.
The reason is that CUBA elements are currently in hybrid mode,
which means that they support both Polymer 1.0 and Polymer 2.0 syntax.
In Polymer 1.0 there were behaviors instead of mixins.
You can find more information about hybrid elements at https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements.

