:sourcesdir: ../../../source

[[cuba__login]]
=== Login Form

All CUBA REST API methods require an OAuth token.
In order to obtain this token the client must authenticate using user's login and password.
This mechanism is described in the {manual-address}/rest_api_v2_ex_get_token.html[Developer's Manual].

The https://cuba-elements.github.io/cuba-elements/components/cuba-login/[cuba-login] web component allows you to create a login form. It's a simple UI component with 2 fields ("User Name", "Password")
and the "Login" button. It sends two events on login attempt: `cuba-login-success` and `cuba-login-error`.

Below is a working example, please use login `test` and password `test`.

[subs="none"]
++++
    <iframe
        height="200"
        class="polymer-iframe-container"
        src="html/src/cuba/login/stub/cuba-app-with-login-stub.html"></iframe>
++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/login/app-with-login.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <app-with-login></app-with-login>
</body>
</html>
----

.src/cuba/login/app-with-login.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/login/app-with-login.html[]
----

Styling::
+
--
If you check `cuba-login` source code, you can see that the component is opened for extension by using https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#custom-property-mixins[custom property mixins].

.bower_components/cuba-login/cuba-login.html
[source, html]
----
  #form {
    @apply --cuba-login-form;
  }
  #username {
    @apply --cuba-login-username-input;
  }
  #password {
    @apply --cuba-login-password-input;
  }
  #submit {
    @apply --cuba-login-submit-button;
  }
  .actions {
    display: flex;
    flex-direction: row-reverse;
    @apply --cuba-login-actions;
  }
  ...
  <form id="form">
    <div class="fields">
      <paper-input type="text" id="username" label="[[msg('User Name')]]" value="{{username}}"></paper-input>
      <paper-input type="password" id="password" label="[[msg('Password')]]" value="{{password}}"></paper-input>
    </div>
    <div class="actions">
      <paper-button id="submit" on-tap="submit">[[msg('Login')]]</paper-button>
    </div>
  </form>
----

Below you can see how these mixins can be implemented. The example is the same as above but contains the `<style/>` section.

.src/cuba/login/app-with-login-styled.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/login/app-with-login-styled.html[]
----

*Result of styling*

[subs="none"]
++++
    <iframe
        height="200"
        class="polymer-iframe-container"
        src="html/src/cuba/login/stub/cuba-app-with-login-styled-stub.html"></iframe>
++++
--

Writing your own login form::
+
--
`cuba-login`, as any other CUBA component uses `cuba-rest` component API under the hood.
It means that if you need some very custom login page, you can use the API directly. See an example below.

.src/cuba/login/app-with-login-custom.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/login/app-with-login-custom.html[]
----

*Custom login form*

[subs="none"]
++++
    <iframe
        height="150"
        class="polymer-iframe-container"
        src="html/src/cuba/login/stub/cuba-app-with-login-custom-stub.html"></iframe>
++++
--

Token expiration::
+
--
A Polymer application receives a token after authentication and then uses it with every request.

By default, a token is valid for 12 hours. After this period requests stop working and the user has to re-login. We recommend to increase the {manual-address}/app_properties_reference.html#cuba.rest.client.tokenExpirationTimeSec[token expiration time] and use the {manual-address}/rest_api_v2_persistent_token_store.html[persistent token store] to save tokens on server restart.

`cuba-app` sends the `cuba-token-expired` event that can be used to handle the expiration appropriately.
--

