:sourcesdir: ../../../../../source

[[arbitrary_dbms]]
===== Поддержка произвольных СУБД

На уровне прикладного проекта можно реализовать работу с любой СУБД, поддерживаемой фреймворком <<orm,ORM>> (EclipseLink). Для этого достаточно выполнить следующее:

* Указать тип СУБД в виде произвольного кода в свойстве <<cuba.dbmsType,cuba.dbmsType>>. Код должен отличаться от используемых в платформе кодов `hsql`, `postgres`, `mssql`, `oracle`.

* Реализовать интерфейсы `DbmsFeatures`, `SequenceSupport`, `DbTypeConverter` классами с именами соответственно `TypeDbmsFeatures`, `TypeSequenceSupport`, `TypeDbTypeConverter`, где `Type` - код типа СУБД. Пакет класса имплементации должен быть таким же, как у интерфейса.

* Если источник данных сконфигурирован в приложении, необходимо указать полный URL соединения в требуемом СУБД формате, как описано в разделе <<db_connection>>.

* Создать скрипты инициализации и обновления БД в каталогах с кодом СУБД. Скрипты инициализации должны включать создание всех объектов БД, необходимых для сущностей платформы (их можно скопировать из имеющихся в каталоге `10-cuba` и др. скриптов и исправить для данной СУБД).

* Для создания и обновления БД задачами Gradle в build.gradle необходимо для этих задач указать дополнительные параметры:
+
[source, java]
----
include::{sourcesdir}/dbms/dbtasks_1.gradle[]
----

