:sourcesdir: ../../../../../source

[[db_mysql_features]]
===== Особенности MySQL

[WARNING]
====
Если в вашей базе данных используется кодировка, отличная от UTF-8, некоторые скрипты фреймворка не смогут быть выполнены. В этом случае необходимо изменить свойства базы данных _Charset_ и _Collation name_, передав следующие параметры подключения в поле *Connection params* окна *Data Store Properties*:

[source, plain]
----
?useUnicode=true&characterEncoding=UTF-8
----
====

MySQL не поддерживает частичные (partial) индексы, поэтому единственная возможность создать ограничение уникальности для <<soft_deletion,soft deleted>> сущности - это использовать в составе индекса колонку `DELETE_TS`. Однако, существует другая проблема: MySQL позволяет иметь несколько NULLs в колонке с ограничением уникальности. Так как стандартная колонка `DELETE_TS` является nullable, она не может быть использована в уникальном индексе. Рекомендуется следующий способ создания уникальных ограничений для сущностей с мягким удалением:

. Создайте в таблице колонку `DELETE_TS_NN` с параметром not null и значением по умолчанию:
+
[source, sql]
----
create table DEMO_CUSTOMER (
    ...
    DELETE_TS_NN datetime(3) not null default '1000-01-01 00:00:00.000',
    ...
)
----

. Создайте триггер, изменяющий `DELETE_TS_NN` когда меняется `DELETE_TS`:
+
[source, sql]
----
create trigger DEMO_CUSTOMER_DELETE_TS_NN_TRIGGER before update on DEMO_CUSTOMER
for each row
    if not(NEW.DELETE_TS <=> OLD.DELETE_TS) then
        set NEW.DELETE_TS_NN = if (NEW.DELETE_TS is null, '1000-01-01 00:00:00.000', NEW.DELETE_TS);
    end if
----

. Создайте уникальный индекс, включающий в себя уникальные колонки и `DELETE_TS_NN`:
+
[source, sql]
----
create unique index IDX_DEMO_CUSTOMER_UNIQ_NAME on DEMO_CUSTOMER (NAME, DELETE_TS_NN)
----

