:sourcesdir: ../../../../../source

[[dbms_version]]
===== Версия СУБД

В дополнение к свойству приложения <<cuba.dbmsType,cuba.dbmsType>> существует опциональное свойство <<cuba.dbmsVersion,cuba.dbmsVersion>>. Оно влияет на выбор имплементаций интерфейсов `DbmsFeatures`, `SequenceSupport`, `DbTypeConverter`, и на поиск скриптов создания и обновления БД.

Имя класса имплементации интеграционного интерфейса формируется следующим образом: `TypeVersionName`. Здесь `Type` - значение `cuba.dbmsType` с заглавной буквы, `Version` - значение `cuba.dbmsVersion`, `Name` - имя интерфейса. Пакет класса должен быть таким же, как у интерфейса. Если класс с таким именем отсутствует, предпринимается попытка найти класс с именем без версии: `TypeName`. Если и такого класса нет, выдается исключение.

Например, в платформе определен класс `com.haulmont.cuba.core.sys.persistence.Mssql2012SequenceSupport`, который вступит в силу, если в проекте указаны следующие свойства:

[source, properties]
----
cuba.dbmsType = mssql
cuba.dbmsVersion = 2012
----

При поиске <<db_scripts,скриптов создания и обновления БД>> каталог с именем `type-version` имеет приоритет над каталогом с именем `type`. Это значит, что скрипты каталога `type-version` заменяют одноименные скрипты каталога `type`. В каталоге `type-version` могут быть и скрипты с собственными именами, они будут также добавлены в общий набор скриптов для выполнения. Сортировка скриптов производится по пути начиная с каталога, вложенного в `type` или `type-version`, то есть без учета того, в каком каталоге (с версией или без) находится скрипт.

Например, следующим образом можно определить скрипты создания БД для Microsoft SQL Server для версий ниже и выше 2012:

[source, plain]
----
modules/core/db/init/
   mssql/
       10.create-db.sql
       20.create-db.sql
       30.create-db.sql
   mssql-2012/
       10.create-db.sql 
----

