:sourcesdir: ../../../../../source

[[entity_log_view]]
===== Viewing the Entity Log

The entity log content can be viewed on a dedicated screen available at *Administration > Entity Log*.

The change log for a certain entity can also be accessed from any application screen by loading a collection of `EntityLogItem` and the associated `EntityLogAttr` instances into the data containers and creating the visual components connected to these containers.

The example below shows the fragment of the screen XML descriptor of a `Customer` entity which has a tab with the entity log content.

.The fragment of the customer-edit.xml
[source, xml]
----
include::{sourcesdir}/features/entity_log.xml[]
----
Let us have a look on the `Customer` screen controller:

.The fragment of the Customer screen controller
[source, java]
----
include::{sourcesdir}/features/entity_log_controller.java[]
----

Notice that the screen has no `@LoadDataBeforeShow` annotation, because loading is triggered explicitly.

<1> − the `onBeforeShow` method loads data before showing the screen.
<2> − in the `ItemChangeEvent` handler of the `customerDc` container, a parameter is set to the dependent loader and it is triggered.

Logged attributes should contain the <<localizedValue_annotation,@LocalizedValue>> annotation in order to display localized values. When annotated, the logging mechanism populates the `EntityLogAttr.messagesPack` field, and the table in the example above is able to use `locValue` column instead of `value`:

[source, xml]
----
<table id="attrTable" width="100%" height="200px" dataContainer="logAttrDc">
  <columns>
      <column id="name"/>
      <column id="locValue"/>
  </columns>
</table>
----

