:sourcesdir: ../../../../source

[[rest_api_v2_services_config]]
==== Services Configuration

The list of service methods that are available via the REST API must be configured in the CUBA application in files registered in the <<cuba.rest.servicesConfig, cuba.rest.servicesConfig>> application property of the *web* or *portal* module (e.g in the `web-app.properties file`):

[source,properties]
----
cuba.rest.servicesConfig = +com/company/myapp/rest-services.xml
----

The content of the `rest-services.xml` must be placed in the root package of the *web* or *portal* module (e.g. `com.company.myapp`). Its content is defined by the http://schemas.haulmont.com/cuba/{revnumber}/rest-services-v2.xsd[rest-services-v2.xsd] schema, for example:

[source, xml]
----
include::{sourcesdir}/rest/rest-services-config.xml[]
----

Method parameter types can be omitted if the service doesn't contain an overloaded method with the same number of parameters. Otherwise, types must be defined.

If parameter type is a primitive datatype then use a primitive type name (`int`, `double`, etc.) in the services config:

[source, xml]
----
<param name="intParam" type="int"/>
----

In case of object or entity use a fully-qualified class name as a parameter type:

[source, xml]
----
<param name="stringParam" type="java.lang.String"/>
<param name="entityParam" type="com.company.entity.Order"/>
----

In case of entity collection or POJO collection, use the collection type:

[source, xml]
----
<param name="entitiesCollectionParam" type="java.util.List"/>
----

An example of how to configure and invoke a service can be found in the <<rest_api_v2_ex_service_get>> and <<rest_api_v2_ex_service_post>> chapters.

If some service method needs to be invoked without authentication even when the <<rest_api_v2_anonymous, anonymous access>> to the REST API is disabled, then this method may be marked with the `anonymousAllowed="true"` attribute in the services configuration file:

[source, xml]
----
include::{sourcesdir}/rest/rest-services-config-anonymous.xml[]
----
