:sourcesdir: ../../../../source

[[rest_api_v2_data_model_versioning]]
==== Data Model Versioning

REST API can handle data model changes. It is useful when, for example, some entity attribute was renamed, but REST API client doesn't know about this modification and expects the attribute to have an old name.

For such cases REST API allows you to define transformation rules for entities JSON. If the client application sends the data model version in the request query parameter then the JSON in REST API method response or request body will be transformed according to transformation rules defined for that particular domain model version.

JSON transformation rules must be specified in files registered in <<cuba.rest.jsonTransformationConfig, cuba.rest.jsonTransformationConfig>> application property of the *web* or *portal* module (e.g in the `web-app.properties` file):

[source,properties]
----
cuba.rest.jsonTransformationConfig = +com/company/myapp/rest-json-transformations.xml
----

The `rest-json-transformations.xml` file must be placed in the *web* or *portal* module (e.g. in package `com.company.myapp`). Its content is defined by the {xsd_url}/rest-json-transformations.xsd[rest-json-transformations.xsd] schema. File example:

[source, xml]
----
include::{sourcesdir}/rest/rest-json-transformations.xml[]
----

Standard transformers configured in the config file can perform the following transformations of entity JSON:

* rename entity

* rename entity attribute

* remove entity attribute

JSON transformation works for the following REST API endpoints:

* */entities* - getting entities list, getting a single entity, entity create, entity update, entity delete

* */queries* - entities JSON returned by the query will be transformed

* */services* - JSON transformations will be applied both to entities returned by the service method and to entities passed as a service method argument

JSON transformations are applied if the request to the REST API contains the `modelVersion` URL parameter with the data model version number.

See the <<rest_api_v2_ex_json_transformations>> to understand how to configure data model versioning and use it from the client application.

