:sourcesdir: ../../../../source

[[rest_api_v2_queries_config]]
==== Predefined JPQL Queries Configuration

In the CUBA application, predefined JPQL queries must be specified in files registered in the <<cuba.rest.queriesConfig, cuba.rest.queriesConfig>> application property of the *web* or *portal* module (e.g in the `web-app.properties file`):

[source,properties]
----
cuba.rest.queriesConfig = +com/company/myapp/rest-queries.xml
----

The `rest-queries.xml` file must be placed in the root package of the *web* or *portal* module (e.g. `com.company.myapp`). Its content is defined by the http://schemas.haulmont.com/cuba/{revnumber}/rest-queries.xsd[rest-queries.xsd] schema, for example:

[source, xml]
----
include::{sourcesdir}/rest/rest-queries-config.xml[]
----

An example of how to configure and execute a query can be found in the <<rest_api_v2_ex_query_get>> and <<rest_api_v2_ex_query_post>> chapter.

The platform also provides the predefined `all` query for getting all instances of a specified entity type. It can be used with `/count` to receive the total number of entity instances, for example:

  http://localhost:8080/app/rest/v2/queries/sales$Order/all/count

The `query` element can have the `cacheable` attribute that enables <<entity_cache,caching>> of the query.

A query can contain predefined parameters that take the values of the current user id and login: `session$userId` and `session$userLogin`. You don't have to declare them in the `params` element (see the example above).

