:sourcesdir: ../../../../source

[[rest_api_v2_custom_controllers]]
==== Creating Custom OAuth2 Protected Controllers

If you need to create a custom REST controller protected with the OAuth2 authentication then you have to do the following:

. Suppose you have the following REST controller:
+
[source, java]
----
include::{sourcesdir}/features/MyController.java[]
----

. Create a new Spring configuration file with name `rest-dispatcher-spring.xml` under the root package (`com.company.test`) of *web* or *portal* module. The content of the file must be as follows:
+
[source, xml]
----
include::{sourcesdir}/rest/rest-dispatcher-spring.xml[]
----

. Define an <<additive_app_properties,additive>> application property `cuba.restSpringContextConfig` in the properties file of the module,.e.g. `portal-app.properties`:
+
[source, properties]
----
cuba.restSpringContextConfig = +com/company/test/rest-dispatcher-spring.xml
----

. The new controller runs in the context of the `CubaRestApiServlet`. So the URL for controller methods will start with the `/rest`, i.e. the doSmth() method will be accesed by the URL: `\http://localhost:8080/app-portal/rest/myapi/dosmth`.
+
[WARNING]
====
URL of the custom controller MUST NOT start with the `/rest/v2`.
====

