:sourcesdir: ../../../../source

[[app_structure]]
==== Состав приложения

Вышеописанные архитектурные принципы напрямую отражаются в структуре собранного приложения. Рассмотрим ее на примере простого приложения, которое состоит из двух блоков – Middleware и Web Client; и включает в себя функциональность компонентов *cuba* и *reports*.

.Состав простого приложения
image::SampleAppArtifacts.svg[align="center"]

На рисунке изображено содержимое некоторых каталогов сервера *Tomcat* с развернутым в нем приложением.

Блок Middleware реализован веб-приложением `app-core`, блок Web Client – веб-приложением `app`. Исполняемый код веб-приложений содержится в каталогах `WEB-INF/lib` в наборе JAR-файлов. Каждый JAR представляет собой результат сборки (<<artifact,артефакт>>) одного из <<app_modules,модулей>> приложения или его <<app_components,компонента>>.

Например, состав JAR-файлов веб-приложения среднего слоя `app-core` определяется тем, что блок Middleware состоит из модулей *global* и *core*, и приложение использует компоненты *cuba* и *reports*.


