:sourcesdir: ../../../../../source

[[managed_beans_creation]]
===== Creating a Bean

To create a managed bean, add the `@org.springframework.stereotype.Component` annotation to the Java class. For example:
[source, java]
----
include::{sourcesdir}/common/managedbean_1.java[]
----

It is recommended to assign a unique name to the bean in the `++{project_name}_{class_name}++` form and to define it in the `NAME` constant.

[TIP]
====
The `@javax.annotation.ManagedBean` can also be used for the managed bean definition, but it can cause problems when deploying the application into some application servers. Therefore we recommend to use only `@Component` annotation from Spring Framework.
====

The managed bean class should be placed inside the package tree with the root specified in the `context:component-scan` element of the <<spring.xml,spring.xml>> file. In this case, the `spring.xml` file contains the element:

[source, xml]
----
include::{sourcesdir}/common/managedbean_2.xml[]
----

which means that the search for annotated beans for this application block will be performed starting with the `com.sample.sales` package.

Managed beans can be created on any <<app_tiers,tier>>, because the Spring Framework container is used in all standard blocks of the application.

