:sourcesdir: ../../../../../source

[[jmx_beans_creation]]
===== Создание JMX-бина

Рассмотрим процесс создания JMX-бина на примере.

* Интерфейс JMX-бина:
+
[source, java]
----
include::{sourcesdir}/common/jmxbean_1.java[]
----

** Интерфейс и его методы могут содержать аннотации для задания описания JMX-бина и его операций. Это описание будет отображаться во всех инструментах, работающих с данным JMX-интерфейсом, тем самым помогая администратору системы.

** Аннотацию `@JmxRunAsync` можно использовать для указания длительных операций. Если такая операция запускается через встроенную <<jmx_console,консоль JMX>>, платформа отображает диалог с неопределенным индикатором прогресса и кнопкой *Cancel*. Пользователь может прервать операцию и продолжить работу с приложением. Аннотация может также содержать параметр `timeout`, который устанавливает максимальное время выполнения в миллисекундах, например:
+
[source, java]
----
@JmxRunAsync(timeout = 30000)
String calculateTotals();
----
+
Если таймаут превышен, диалог закрывается с сообщением об ошибке.
+
[WARNING]
====
Пожалуйста имейте в виду, что если операция прервана пользователем или по таймауту, она все равно продолжает работать в фоне, то есть данные действия не прерывают самого выполнения, а только возвращают управление пользователю.
====

** Так как инструменты JMX поддерживают ограниченный набор типов данных, параметры и результат метода желательно задавать типа `String`, и при необходимости выполнять конвертацию внутри метода. Помимо `String`, поддерживаются следующие типы параметров: `boolean`, `double`, `float`, `int`, `long`, `Boolean`, `Integer`.

* Класс JMX-бина:
+
[source, java]
----
include::{sourcesdir}/common/jmxbean_2.java[]
----
+
Аннотация `@Component` определяет, что данный класс является управляемым бином с именем `++sales_OrdersMBean++`. Имя указано напрямую в аннотации, а не в константе, так как доступ к JMX-бину из кода Java не требуется.
+
Рассмотрим реализацию метода `calculateTotals()`.

** Метод имеет аннотацию `@Authenticated`, т.е. при входе в метод и при отсутствии в потоке выполнения <<userSession,пользовательской сессии>> выполняется <<system_authentication,системная аутентификация>>.

** Тело метода обернуто в блок try/catch, так что метод в случае успешного выполнения возвращает строку "Done", а в случае ошибки - stacktrace исключения в виде строки.
+
В данном случае все исключения обрабатываются, а значит, не попадают в `MBeanInterceptor` и не выводятся в журнал автоматически. Поэтому при необходимости логировать исключения здесь нужно добавить вызов логгера в секции `catch`.

** Логика метода заключается в том, что он стартует транзакцию, загружает экземпляр сущности `Order` по идентификатору и передает управление бину `OrderWorker` для обработки.

* Регистрация JMX-бина в `spring.xml`:
+
[source, xml]
----
include::{sourcesdir}/common/jmxbean_3.xml[]
----
+
Все JMX-бины проекта объявляются в одном экземпляре `MBeanExporter` в элементах `map/entry` свойства `beans`. Ключом элемента здесь является JMX ObjectName, значением - имя бина, заданное в аннотации `@Component`. ObjectName начинается с имени веб-приложения, так как в одном экземпляре сервера приложения (т.е. в одной JVM) может быть развернуто несколько веб-приложений, экспортирующих одинаковые JMX-интерфейсы.

