:sourcesdir: ../../../../source

[[orm]]
==== Слой ORM

Object-Relational Mapping - объектно-реляционное отображение - технология связывания таблиц реляционной базы данных с объектами языка программирования. В платформе CUBA используется реализация ORM на основе фреймворка *EclipseLink*.

Использование ORM дает ряд очевидных преимуществ:

* Позволяет работать с данными реляционной СУБД, манипулируя объектами Java.

* Упрощает программирование, избавляя от рутины написания тривиальных SQL-запросов.

* Упрощает программирование, позволяя извлекать и сохранять целые графы объектов одной командой.

* Обеспечивает легкое портирование приложения на различные СУБД.

* Позволяет использовать лаконичный язык запросов <<jpql,JPQL>>.

В то же время, имеются и некоторые недостатки. Во-первых, разработчик, использующий ORM непосредственно, должен хорошо понимать особенности работы этой технологии. Во-вторых, усложняется оптимизация SQL и использование особенности применяемой СУБД.

[TIP]
====
Если вы столкнулись с проблемами производительности при доступе к БД, начните с того, что проверьте, какие конкретно SQL-операторы выполняются в вашем приложении. Вы можете использовать <<logging_useful_loggers,логгер>> `eclipselink.sql` для вывода всех SQL-операторов, генерируемых ORM, в файл лога.
====

include::orm/entityManager.adoc[]

include::orm/entity_states.adoc[]

include::orm/lazy_loading.adoc[]

include::orm/query.adoc[]

include::orm/nativeQuery.adoc[]

include::orm/entity_listeners.adoc[]

