:sourcesdir: ../../../../source

[[orm]]
==== Слой ORM

Object-Relational Mapping - объектно-реляционное отображение - технология связывания таблиц реляционной базы данных с объектами языка программирования. 

Преимущества использования ORM::: 

* Позволяет работать с данными реляционной СУБД, манипулируя объектами Java.

* Упрощает программирование, избавляя от рутины написания тривиальных SQL-запросов.

* Упрощает программирование, позволяя извлекать и сохранять целые графы объектов одной командой.

* Обеспечивает легкое портирование приложения на различные СУБД.

* Позволяет использовать лаконичный язык запросов <<jpql,JPQL>>.

Недостатки:::

* Требует понимания особенностей работы с ORM.

* Усложняет оптимизацию SQL и использование особенности применяемой СУБД.

В платформе CUBA используется реализация ORM основе фреймворка *EclipseLink*.

include::orm/entityManager.adoc[]

include::orm/entity_states.adoc[]

include::orm/lazy_loading.adoc[]

include::orm/query.adoc[]

include::orm/nativeQuery.adoc[]

include::orm/entity_listeners.adoc[]

