:sourcesdir: ../../../../../source

[[gui_using_data_comp]]
===== Using Data Components

[[gui_data_comp_declaration]]
Declarative Creation of Data Components::
+
--
The simplest way to create data components for a screen is to define them in the screen XML descriptor in the `<data>` element.

Let's consider the data model consisting of `Customer`, `Order` and `OrderLine` entities. The edit screen for the `Order` entity can have the following XML definition:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_1.xml[]
----

In this case, the following data components are created:

* `DataContext` instance.

* `InstanceContainer` with `orderDc` id and `InstanceLoader` for the `Order` entity.

* `CollectionPropertyContainer` with `linesDc` id for the `OrderLines` entity. It is bound to the `Order.lines` collection attribute.

* `CollectionContainer` with `customersDc` id for the `Customer` entity. It is loaded by `CollectionLoader` using the specified query.

The data containers can be used in visual components as follows:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_2.xml[]
----

<1> Standalone fields have `dataContainer` and `property` attributes.
<2> `form` propagates `dataContainer` to its fields so they need only `property` attribute.(
<3> Lookup fields have `optionsContainer` attribute.
<4> Tables have only `dataContainer` attribute.
--

[[gui_data_comp_prog]]
Programmatic Creation of Data Components::
+
--
Data components can be created and used in visual components programmatically.

In the example below, we create an editor screen with the same data and visual components as defined in the <<gui_using_data_comp,previous section>> using only Java code without any XML descriptor.

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_3.java[]
----

<1> `DataComponents` is a factory to create data components.
<2> `DataContext` instance is registered in the screen for standard commit action to work properly.
<3> `orderDl` loader will load data to `orderDc` container.
<4> `orderDl` loader will merge loaded entities into data context for change tracking.
<5> `linesDc` is created as a property container.
<6> A query is specified for the `customersDl` loader.
<7> `ContainerValueSource` is used to bind single fields to containers.
<8> `ContainerOptions` is used to provide options to lookup fields.
<9> `ContainerTableItems` is used to bind tables to containers.
<10> `getEditedEntityContainer()` is overridden to specify the container instead of `@EditedEntityContainer` annotation.
<11> Load data before showing the screen. The edited entity id will be set to `orderDl` by the framework automatically.
--