:sourcesdir: ../../../../../source

[[gui_data_loaders]]
===== Data Loaders

Loaders are designed to load data from the middle tier to <<gui_data_containers,containers>>.

There are slightly different interfaces of loaders depending on containers they work with:

* `InstanceLoader` loads a single instance to `InstanceContainer` by entity id or JPQL query.

* `CollectionLoader` loads a collection of entities to `CollectionContainer` by a JPQL query. You can specify paging, sorting and other optional parameters.

* `KeyValueCollectionLoader` loads a collection of `KeyValueEntity` instances to `KeyValueCollectionContainer`. In addition to `CollectionLoader` parameters, you can specify a <<data_store,data store>> name.

In screen XML descriptors, all loaders are defined by the same `<loader>` element and the type of a loader is determined by what container it is enclosed in.

Loaders are optional because you can just load data using `DataManager` or your custom service and set directly to containers, but they simplify this process in declaratively defined screens, especially with the <<gui_Filter,Filter>> component. Usually, a collection loader obtains a JPQL query from the screen XML descriptor and query parameters from the filter component, creates `LoadContext` and invokes `DataManager` to load entities. So the typical XML descriptor looks like this:

[source, xml]
----
include::{sourcesdir}/gui/data_loaders/loader_1.xml[]
----

Attributes of the `loader` XML element allow you to define optional parameters like `cacheable`, `softDeletion`, etc.

In an entity editor screen, the loader XML element is usually empty, because the instance loader requires an entity identifier which is specified programmatically by the `StandardEditor` base class:

[source, xml]
----
include::{sourcesdir}/gui/data_loaders/loader_2.xml[]
----

Loaders can delegate actual loading to a function which can be provided using the `setLoadDelegate()` method or declaratively using the `@Install` annotation in the screen controller, for example:

[source, java]
----
include::{sourcesdir}/gui/data_loaders/loader_3.java[]
----

In the example above, the `customersDlLoadDelegate()` method will be used by the `customersDl` loader to load the list of `Customer` entities. The method accepts `LoadContext` which will be created by the loader based on its parameters: query, filter (if any), etc. In the example, the loading is done via `DataManager` which is effectively the same as the standard loader implementation, but you can use a custom service or perform any post-processing of the loaded entities.

You can listen to `PreLoadEvent` and `PostLoadEvent` to add some logic before or after loading:

[source, java]
----
include::{sourcesdir}/gui/data_loaders/loader_5.java[]
----

A loader can also be created and configured programmatically, for example:

[source, java]
----
include::{sourcesdir}/gui/data_loaders/loader_4.java[]
----

When <<gui_DataContext,DataContext>> is set for a loader (which is always the case when the loader is defined in XML descriptor), all loaded entities are automatically merged into the data context.

[[gui_data_loader_query_conditions]]
Query conditions::
+
--
Sometimes you need to modify a data loader query at runtime to filter the loaded data at the database level. The simplest way to provide filtering based on parameters entered by users is to connect the <<gui_Filter,Filter>> visual component to the data loader.

Instead of the universal filter or in addition to it, you can create a set of conditions for the loader query. A condition is a set of query fragments with parameters. These fragments are added to the resulting query text _only when all parameters used in the fragments are set for the query_. Conditions are processed on the <<data_store,data store>> level, so they can contain fragments of different query languages supported by data stores. The framework provides conditions for JPQL.

Let's consider creating a set of conditions for filtering a `Customer` entity by two of its attributes: string `name` and boolean `status`.

Loader query conditions can be defined either declaratively in the `<condition>` XML element, or programmatically using the `setCondition()` method. Below is an example of configuring the conditions in XML:

[source, xml]
----
include::{sourcesdir}/gui/data_loaders/loader_condition_1.xml[]
----
<1> - add the JPQL conditions namespace
<2> - define the `condition` element inside `query`
<3> - if you have more than one condition, add `and` or `or` element
<4> - define a JPQL condition with optional `join` element and mandatory `where` element

Suppose that the screen has two UI components for entering the condition parameters: `nameFilterField` text field and `statusFilterField` check box. In order to refresh the data when a user changes their values, add the following event listeners to the screen controller:

[source, java]
----
include::{sourcesdir}/gui/data_loaders/loader_condition_1.java[]
----
<1> - notice how we use <<query_case_insensitive>> provided by ORM

As mentioned above, a condition is included in the query only when its parameters are set. So the resulting query executed on the database will depend on what is entered in the UI components:

.Only nameFilterField has a value
[source]
----
select e from demo_Customer e where e.name like :name
----

.Only statusFilterField has a value
[source]
----
select e from demo_Customer e where e.status = :status
----

.Both nameFilterField and statusFilterField have values
[source]
----
select e from demo_Customer e where (e.name like :name) and (e.status = :status)
----
--