:sourcesdir: ../../../../../source

[[gui_DataContext]]
===== DataContext

`DataContext` is an interface for tracking changes in entities loaded to the client tier. Tracked entities are marked as "dirty" on any modification of their attributes, and `DataContext` saves dirty entities to the middle tier when its `commit()` method is invoked.

Within `DataContext`, an entity with the given identifier is represented by a single object instance, no matter where and how many times it is used in object graphs.

In order to be tracked, an entity must be put into `DataContext` using its `merge()` method.

[WARNING]
====
The main rule of using the `merge()` method is to continue working with the returned instance and forgetting about the passed one. It follows from the fact that the context could already contain an instance with the same identifier, and in this case that instance would be returned. This principle allows the context to always have only one instance of an entity with a particular identifier.
====

Example of merging an entity into `DataContext`:

[source, java]
----
include::{sourcesdir}/gui/data_context/dataContext_1.java[]
----

A single instance of `DataContext` exists for a given <<gui_screens,screen>> and all its nested fragments. It is created if the `<data>` element exists in the screen XML descriptor.

The `<data>` element can have `readOnly="true"` attribute, in that case a special "no-op" implementation is used which actually doesn't track entities and hence doesn't affect performance. By default, entity browsers scaffolded by Studio have the read-only data context, so if you need to track changes and commit dirty entities in a browser, remove the `readOnly="true"` XML attribute.