:sourcesdir: ../../../../source

[[studio_modules]]
=== Modules

The *Modules* menu contains the application {main_man_url}/app_modules.html[modules]: by default, the *global*, *core*, and *web*.

* *global* – includes entity classes, service interfaces, and other classes common for all tiers. It is used in all {main_man_url}/app_tiers.html[application blocks]. A new empty project already contains these configuration files by dafault:
** {main_man_url}/metadata.xml.html[metadata.xml]
** {main_man_url}/persistence.xml.html[persistence.xml]
** {main_man_url}/views.xml.html[views.xml]
* *core* – implements services and all other components of the middle tier. It is used only in *Middleware*.
** {main_man_url}/app_properties.html[app.properties]
** {main_man_url}/spring.xml.html[spring.xml]
* *web* – the implementation of the generic user interface based on *Vaadin* and other specific web client classes. It is used in *Web Client* block.
** {main_man_url}/app_properties.html[web-app.properties]
** {main_man_url}/dispatcher-spring.xml.html[web-dispatcher-spring.xml]
** {main_man_url}/menu.xml.html[web-menu.xml]
** {main_man_url}/permissions.xml.html[web-permissions.xml]
** {main_man_url}/screens.xml.html[web-screens.xml]
** {main_man_url}/spring.xml.html[web-spring.xml]