= CUBA Platform. BPM subsystem
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.9
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)

:!sectnums:

[[preface]]
== Preface

This manual describes the CUBA Platform Business Process Management subsystem.

We assume that the reader is familiar with the CUBA Platform Developer's Manual which is available at https://www.cuba-platform.com/manual.

CUBA business process management subsystem is based on the Activiti framework, therefore general knowledge of the framework is beneficial. See http://www.activiti.org to learn more about Activiti. Processes are defined according to the BPMN 2.0 notation, so it is assumed that the reader is familiar with the notation. More information about BPMN 2.0 specification can be found at  http://www.bpmn.org.

If you have any suggestions for improving this manual, feel free to report issues in the source repository on https://github.com/cuba-platform/documentation[GitHub]. If you see a spelling or wording mistake, a bug or inconsistency, don't hesitate to fork the repo and fix it. Thank you!

:sectnums:

include::quickstart.adoc[]

include::datamodel.adoc[]

include::functionality.adoc[]

include::services.adoc[]

include::ui.adoc[]

include::examples.adoc[]

[[app_properties]]
[appendix]
== Application properties

bpm.activiti.asyncExecutorEnabled:: Possible values: `true` or `false`. Defines whether Job Executor for timers and asynchronous tasks is enabled. The default value is `false`.