:sourcesdir: ../../../source

[[security_web]]
=== Web Security

*Are CUBA applications secure?*

CUBA Platform as a framework follows good security practices and provides you with automatic protection against some of the most common vulnerabilities in web applications. Its architecture promotes a secure programming model, allowing you to concentrate on your business and application logic.

1. *UI State and Validation*
+
<<gui_web,Web Client>> is a server-side application, where all of your application state, business and UI logic resides on the server. Unlike client driven frameworks, Web Client never exposes its internals to the browser, where vulnerabilities can be leveraged by an attacker. The data validation is always done on the server and therefore cannot be by-passed with client-side attacks, the same applies to <<rest_api_v2,REST API>> validation.

2. *Cross-Site Scripting (XSS)*
+
Web Client has built-in protection against cross-site scripting (XSS) attacks. It converts all data to use HTML entities before the data is rendered in the user's browser.

3. *Cross-Site Request Forgery (CSRF)*
+
All requests between the client and the server are included with a user session specific CSRF token. All communication between the server and the client is handled by https://vaadin.com/framework/[Vaadin Framework], so you do not need to remember to include the CSRF tokens manually.

4. *Web Services*
+
All communication in Web Client goes through one web service used for RPC requests. You never open up your business logic as web services and thus there are less attack entry points to your application.
+
Generic REST API automatically applies roles, permissions and all security constraints for both logged in and anonymous users.

5. *SQL Injection*
+
The platform uses <<orm,ORM>> layer based on EclipseLink that is protected against SQL injections. Parameters of SQL queries are always passed to JDBC as parameters array and not interpolated into SQL queries as raw strings.

