:sourcesdir: ../../../../../source

[[build.gradle_deployWar]]
===== deployWar

`deployWar` - the task of the `CubaJelasticDeploy` type which deploys the WAR file to Jelastic server.

[TIP]
====
The task can be configured using the *Deployment settings > Cloud* page in Studio. See its context help for details.
====

For example:

[source, groovy]
----
task deployWar(type: CubaJelasticDeploy, dependsOn: buildWar) {
   email = '<your@email.address>'
   password = '<your password>'
   context = '<app contex>'
   environment = '<environment name or ID>'
   hostUrl = '<Host API url>'
}
----

Task parameters:

* `appName` - the name of the web application. By default, it corresponds to the Modules prefix, e.g., `app`.

* `email` - Jelastic server account login.

* `password` - Jelastic account password.

* `context` - the application context. Default value: `ROOT`.

* `environment` - the environment where the application WAR will be deployed. You can set either the environment name or its ID.

* `hostUrl` - URL of the API host. Typically it is `app.jelastic.<host name>`.

* `srcDir` - the directory where the WAR is located. By default it is `"${project.buildDir}/distributions/war"`.

