:sourcesdir: ../../../../../source

[[jespa_conf]]
===== Настройка конфигурации

* Выполнить настройки, описанные в разделе *Installation* → *Step 1: Create the Computer Account for NETLOGON Communication* руководства *Jespa Operator's Manual*, которое можно загрузить по адресу link:$$http://www.ioplex.com/support.html$$[http://www.ioplex.com/support.html].

* Задать параметры доменов в <<app_properties_files,local.app.properties>> в свойстве приложения `activeDirectory.domains`. Каждый описатель домена имеет формат `++domain_name|full_domain_name|service_account_name|service_account_password++`. Описатели доменов отделяются друг от друга точкой с запятой.
+
Например:
+
[source, properties]
----
activeDirectory.domains = MYCOMPANY|mycompany.com|JESPA$@MYCOMPANY.COM|password1;TEST|test.com|JESPA$@TEST.COM|password2
----

* Разрешить интеграцию с Active Directory, установив в `local.app.properties` свойство приложения `activeDirectory.integrationEnabled`:
+
[source, properties]
----
activeDirectory.integrationEnabled = true
----

* Задать в `local.app.properties` дополнительные свойства для библиотеки (см. *Jespa Operator's Manual*). Например:
+
[source, properties]
----
jespa.log.level=3
----
+
Если приложение развернуто на Tomcat, лог-файл Jespa находится в `tomcat/logs`.

* Добавить адрес сервера в местную интрасеть в настройках браузера:

** Для *Internet Explorer* и *Chrome*: *Свойства обозревателя* > *Безопасность* > *Местная интрасеть* > *Узлы* > *Дополнительно*.

** Для *Firefox*: `about:config` > `network.automatic-ntlm-auth.trusted-uris=http://myapp.mycompany.com`.

* Создать в приложении пользователя с доменной учетной записью.

