:sourcesdir: ../../../../../../source

[[cdp_xml_descriptor]]
====== XML-дескриптор экрана

Откройте в CUBA Studio вкладку *Screens* и создайте экран в модуле *web*. Введите значение `com/company/sampler/web/screens/stackedarea-chart.xml` в поле *Descriptor*. В полях *Id*, *Controller Name* и *Messages Pack* будут сгенерированы подходящие значения. Сохраните изменения. Далее перейдите на вкладку *XML* и замените ее содержимое на следующий код:

[source, xml]
----
include::{sourcesdir}/chart/stackedarea-chart.xml[]
----

В корневой элемент дескриптора экрана добавлен атрибут `xmlns:chart`:

[source, xml]
----
<window xmlns:chart="http://schemas.haulmont.com/charts/charts.xsd"
    ...
>
----

Компонент `chart:serialChart` содержит следующие атрибуты:

* `categoryField` - ключ из набора пар, содержащихся в объектах `DataItem`, список которых хранится в экземпляре `DataProvider`, по которому будут взяты значения для подписи оси категорий.

Компонент `chart:serialChart` содержит следующие элементы:

* `chart:chartCursor` - необязательный элемент, добавляющий курсор к диаграмме. Курсор следует за указателем мыши и показывает всплывающие подсказки со значениями элементов диаграммы над которыми находится указатель мыши.
** Атрибут `cursorAlpha` задает степень непрозрачности линий курсора.

* `chart:legend` - определяет легенду графика.
** Атрибут `position` определяет положение легенды относительно диаграммы.
** Атрибут `equalWidths` определяет, должны ли все элементы легенды быть такой же ширины как самый широкий.
** Атрибут `periodValueText` задает текст, который будет показан в значении легенды, когда пользователь не располагает указатель мыши ни над одним элементом данных. Теги должны состоять из пары значений - название поля (value / open / close / high / low) и значение периода, для которого дожно быть показано значение - open / close / high / low / sum / average / count.
** Атрибут `valueAlign` задает выравнивание значения. Возможные значения "left" и "right".
** Атрибут `valueWidth` задает ширину значения.

* `chart:valueAxes` - элемент, описывающий вертикальные оси значений. В данном случае используется только одна ось, описываемая элементом `chart:axis`
** Атрибут `position` задает положение оси значений относительно диаграммы.
** Атрибут `title` задает заголовок оси значения.
** Установка атрибуту `stackType` значения `REGULAR` говорит о том, что используется диаграмма с накоплением. По умолчанию значение этого атрибута - `none`, в таком случае используется диаграмма без накопления.
** Атрибут `gridAlpha` задает степень непрозрачности линий сетки.

* `chart:graphs` - элемент, описывающий графы диаграммы. Граф описывается элементом `chart:graph`.
** Атрибут `type` задает тип графа и может быть: line, column, step line, smoothed line, ohlc и candlestick.
** Атрибут `valueField` определяет ключ из набора пар, содержащихся в объектах `DataItem`, список которых хранится в экземпляре `DataProvider`, по которому будет взято значение.
** Атрибут `fillAlphas` задает степень непрозрачности заполнения.
** Атрибут `lineAlpha` задает степень непрозрачности линии (или рамки колонки).
** Атрибут `hidden` определяет, будет ли граф отображаться.

* `chart:categoryAxis` - элемент, описывающий ось категорий.
** Установка атрибуту `startOnAxis` значения `true` дает указание начинать отрисовывать график сразу от оси значений. По умолчанию этот атрибут имеет значение `false`. В этом случае между осью значений и графиком имеется некоторый промежуток.
** Атрибут `gridAlpha` задает степень непрозрачности линий сетки.
** Атрибут `axisColor` задает цвет оси.

* `chart:export` – добавляет возможность сохранить полученный график.

