[[setup_pentaho]]
== Setting Up Pentaho

. Download and install Pentaho from http://www.pentaho.com/download

. Stop _Pentaho Server_ and _Pentaho Solution Repository_ background processes in Windows Services or its equivalent.

. Change Pentaho default port to 8081.
+
--
* Navigate to `$PENTAHO_HOME/server/pentaho-server/tomcat/conf`, where `$PENTAHO_HOME` is the directory where Pentaho is installed.

* Change default Tomcat port to 8081 in the `server.xml`:

[source,xml]
----
include::{sourcesdir}/bi_port.xml[]
----
--

. Setup authentication of CUBA users in Pentaho.
+
--
* Download https://dl.bintray.com/cuba-platform/main/com/haulmont/addon/bi/cuba-bi-pentaho/{addonVer}/cuba-bi-pentaho-{addonVer}.jar and copy it to `$PENTAHO_HOME$/server/pentaho-server/tomcat/webapps/pentaho/WEB-INF/lib`.

* Create new `cuba-pentaho-authentication.xml` file in the `$PENTAHO_HOME/server/pentaho-server/pentaho-solutions/system` folder with the following content:
+
[source,xml]
----
include::{sourcesdir}/cuba-pentaho-authentication.xml[]
----
+
[TIP]
====
Specify URL of your CUBA application in the `cubaConnectionUrl` property of the `cubaAuthenticationFilter` bean.
====

* Edit `pentaho-spring-beans.xml` in `pentaho-solutions/system` and add the line `<import resource="cuba-pentaho-authentication.xml" />` after the `<import resource="applicationContext-spring-security.xml" />` line:
+
[source,xml]
----
include::{sourcesdir}/bi_beans.xml[]
----
--

. Start _Pentaho Server_ and _Pentaho Solution Repository_ background processes in Windows Services or its equivalent.
