:sourcesdir: ../../../../../source

[[entity_localization]]
===== Entity and Attributes Names Localization

To display localized names of the entities and attributes in UI, create special message packs in the Java packages containing the entities. Use the following format in message files: 

* Key of the entity name – simple class name (without package).

* Key of the attribute name – simple class name, then the name of the attribute separated by period.

The example of default English localization of `com.abc.sales.entity.Customer` entity – `/com/abc/sales/entity/messages.properties` file:

[source, xml]
----
Customer=Customer
Customer.name=Name
Customer.email=Email

Order=Order
Order.customer=Customer
Order.date=Date
Order.amount=Amount
----

Such message packs are usually used implicitly by the framework, for example, by <<gui_Table,Table>> and <<gui_FieldGroup,FieldGroup>> visual components. Besides, you can obtain the names of the entities and attributes using the following methods:

* Programmatically – by <<messageTools,MessageTools>> `getEntityCaption()`, `getPropertyCaption()` methods;

* In XML screen descriptor – by reference to the message according to <<messageTools.loadString,MessageTools.loadString()>> rules: `++msg://{entity_package}/{key}++`, for example:
+
[source, xml]
----
caption="msg://com.abc.sales.entity/Customer.name"
----

