:sourcesdir: ../../../../../source

[[main_message_pack]]
===== Main Message Pack

Each standard application <<app_tiers,block>> should have its own _main_ message pack. For the client tier blocks the main message pack contains main menu entries and common UI elements names (for example, names of *OK* and *Cancel* buttons). The main pack also determines <<datatype,Datatype>> transformation formats for all application blocks, including Middleware.

<<cuba.mainMessagePack,cuba.mainMessagePack>> application property is used to specify the main message pack. The property value can be either a single pack or list of packs separated by spaces. For example: 
[source, properties]
----
cuba.mainMessagePack=com.haulmont.cuba.web com.abc.sales.web
----

In this case the messages in the second pack of the list will override those from the first pack. Thus, the messages defined in the <<app_components,application components>> packs can be overridden in the application project.

Existing messages from CUBA base projects can be also overridden by specifying new messages in the project's main message pack:

[source, plain]
----
com.haulmont.cuba.gui.backgroundwork/backgroundWorkProgress.timeoutMessage = Overridden Error Message
----

