:sourcesdir: ../../../source

[[settings]]
=== CUBA Settings

If you click the *CUBA > Settings* main menu item, you will see the IDE settings window filtered by the *cuba* word. Find the *CUBA* section under *Languages & Frameworks*.

The *CUBA* section itself contains the settings common to all projects opened in this Studio instance.

* *Ask before saving DB scripts with DROP statements* - suggest to exclude update scripts containing DROP statements from automatic execution.

* *Show warning if application server port is in use* - show a warning when you open a project and its Tomcat port is currently busy.

* *Use embedded browser to open application* - if selected, the embedded web browser will be used when you double-click to the application URL in the *Runs At* project tree section.

* *Visual designer theme* - theme of visual designers. Use `Autodetect` to select automatically depending on your IDE theme.

* *Visual designer zoom* - default zoom of visual designers. You can adjust it in a concrete designer using context menu opened by right-click.

* *Old Studio integration enabled* - select this checkbox if you want to integrate this IDE instance with the old Studio SE or Studio Browser Edition. You will be able to open projects from the old Studio in this IDE.

* *Listening port* - a port for the old Studio integration. Make sure it is the same as specified in the old Studio *IDE Port* field.

* *Enable transaction block folding* - if selected, Java code editor will fold old-style `try-finally` blocks used for transaction control.

The nested *Project settings* section contains the settings of the currently opened project. All non-default values are stored in the `studio-intellij.xml` file in the project root directory, which can be added to the version control system to share project settings between all developers in your team.

* *Check compatibility between data model and database scheme* - show a warning whenever you start the application server and the current state of the data model differs from the database schema.

* *Generate DROP statements in separate update scripts* - generate more safe update scripts when you remove an entity, an attribute, or change an attribute’s datatype. Such scripts are split into two parts: in the first part, the column or table is renamed to `*__UNUSED`, and in the second part these objects are actually dropped.

* *Use NVARCHAR when generating scripts for MS SQL Server* - if this option is on, NVARCHAR column type will be used for all String attributes if the database type is Microsoft SQL Server.

* *Generate script name in format* - specify `yyMMddHHmm` to add current time to the names of generated database update scripts, which may help to ensure correct sequence of scripts when working in a team.

* *Do not delete columns started with* - this field allows you to specify a prefix for table columns, that should not be tracked by Studio. If you add a column to a table mapped to an entity, and not map the column to an entity attribute, Studio will generate an update script dropping this column. To avoid dropping, you can exclude this script in the *Database Scripts* dialog, and it will not be generated again. Alternatively, you can set a common prefix for such columns in the *Do not delete columns started with* field and name the column accordingly. For example, enter `NOT_MAPPED_` in the field and name the column `NOT_MAPPED_CODE`.

* *Column length for enums with ID of String type* - this field allows you to set a length of the database column which is mapped to an attribute of enum type with the identifier of String type. For example, if you use short identifiers always consisting of one character, you can set 1 in this field to save database space.

* *Make plural forms* - make plural forms of nouns according to English grammar.

* *Repeat entity parent package for screens* - if the entity is located in an additional package inside entity, Studio will add this package for Generic UI screens generated by templates. For example, if the `Customer` entity is inside `com.company.sample.entity.crm`, the default package for its screens will be `com.company.sample.web.crm.customer`.

* *Use underscores in generated package names* - if selected, package names will include underscores separating words according to camel case in a corresponding entity name. For example, when generating screens for the `com.company.sample.CustomerGrade` entity, the package of the screens will be `com.company.sample.customer_grade`. If the option is off, the package name will be `com.company.sample.customergrade`.

* *Default parent package name for screens* - this field allows you to specify a default package to be used instead of screens when generating a Generic UI screen from template not associated with an entity. It is also added before the package with entity name for templates associated with an entity. For example, if you set ui in this field and create a blank screen, the default value for the package will be `com.company.sample.web.ui`.

* *Default access modifier* - sets the modifier which Studio uses when generates entity fields.

* *Generate entity name with underscore symbol* - if selected, entity names will have `namespace_ClassName` format, for example `sales_Customer`. Otherwise it will be `namespace$ClassName`.

* *Show module prefix migration dialog* - on project opening, suggest migrating build scripts to the new format with module prefix defined in a variable.

* *Instant hot deploy* - this checkbox allows you to turn off hot deploy. If hot deployment is enabled, Studio dynamically updates the UI of your deployed web application as you apply or save changes to views, screens, messages or the main menu.

* *Hot Deploy Settings* - opens a dialog to customize hot deployment directories. For example, you might want to add folders where your web portal HTML and JavaScript files are located. When you change these files, Studio will copy them to respective destinations inside Tomcat. So you can just reload your web portal page to view the changes.

* *Fold messages in* - allows you to control message folding in screen descriptors and controllers. If selected, the message keys will be replaced with actual values from the appropriate message pack.

* *Message folding locale* - what message file to use when folding messages.
