= CUBA Platform. Displaying Charts And Maps
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.5
:version-label: Version
:revremark: Copyright (c) 2017 Haulmont (www.haulmont.com)

:!sectnums:

[[preface]]
[preface]
== Preface

This document describes two functional modules of the CUBA platform, which display charts and geographic maps respectively. These subsystems are implemented in the same application component – *charts* – and thus can only be included in an application project together.

Charts and map display functionality is currently available only for the web client.

[[audience]]
=== Target Audience

This manual is intended for developers building applications using CUBA platform. It is assumed that the reader is familiar with the *Developer's Manual*, which is available at https://www.cuba-platform.com/manual.

[[additional_info]]
=== Additional Materials

This guide, as well as any other documentation on CUBA platform, is available at https://www.cuba-platform.com/manual.

CUBA charts display subsystem implementation is based on *AmCharts* library, therefore familiarity with this library may be beneficial. See http://www.amcharts.com.

[[feedback]]
=== Feedback

If you have any feedback or would like to suggest an improvement for this manual, please contact support at https://www.cuba-platform.com/support/topics.

If you find an error in this document, please specify the section number and attach a small piece of surrounding text to help us find it.

:sectnums:

include::chart.adoc[]

include::map.adoc[]

include::pivot_table.adoc[]