= CUBA Platform. Displaying Charts And Maps
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.10
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)

:!sectnums:

[[preface]]
[preface]
== Preface

This document describes two functional modules of the CUBA platform, which display charts and geographic maps respectively. These subsystems are implemented in the same application component – *charts* – and thus can only be included in an application project together.

Charts and map display functionality is currently available only for the web client.

[[audience]]
=== Target Audience

This manual is intended for developers building applications using CUBA platform. It is assumed that the reader is familiar with the *Developer's Manual*, which is available at https://www.cuba-platform.com/manual.

[[additional_info]]
=== Additional Materials

This guide, as well as any other documentation on CUBA platform, is available at https://www.cuba-platform.com/manual.

CUBA charts display subsystem implementation is based on *AmCharts* library, therefore familiarity with this library may be beneficial. See http://www.amcharts.com.

[[feedback]]
=== Feedback

If you have any suggestions for improving this manual, feel free to report issues in the source repository on https://github.com/cuba-platform/documentation[GitHub]. If you see a spelling or wording mistake, a bug or inconsistency, don't hesitate to fork the repo and fix it. Thank you!

:sectnums:

include::chart.adoc[]

include::map.adoc[]

include::pivot_table.adoc[]