:sourcesdir: ../../../../source

[[docker_deployment]]
==== Deployment to Docker

The section describes how to deploy CUBA applications with https://www.docker.com/[Docker®].

[TIP]
=====
This tutorial covers deployment of a project using PostgreSQL database.
=====

The simplest way to run your CUBA application in a production environment is to use the Uber JAR approach. You can build an all-in-one JAR file using the Gradle task, and then you will be able to run the application from the command line using the `java` executable, so there is no need to use special web servers or servlet containers. Simply start your application as an executable. All parameters of the application are defined at the build time but can be overridden when running.

We will show you how to set up monolithic and distributed application configurations with Docker containers.

include::docker_deployment/single_jar_deployment.adoc[]

include::docker_deployment/distributed_jar_deployment.adoc[]

include::docker_deployment/docker_plugin.adoc[]

include::docker_deployment/heroku_container.adoc[]

