:sourcesdir: ../../../../source

[[war_deployment]]
==== WAR deployment to Jetty

Below is an example of deployment of the WAR files to the *Jetty* web server.

We are going to use the following directory structure:

* `C:\work\jetty-home\` - Jetty distribution folder;
* `C:\work\jetty-base\` - Jetty configuration directory, used to store Jetty configuration files, additional libraries and web applications.
* `C:\work\app_home\` - CUBA <<app_home,application home>> directory.

. Use the *CUBA project tree > Project > Deployment > WAR Settings* dialog in Studio or just manually add the <<build.gradle_buildWar, buildWar>> task to the end of <<build.gradle,build.gradle>>:
+
[source, groovy]
----
include::{sourcesdir}/deployment/warDeployment_1.groovy[]
----
+
Please note that we are building two separate WAR files for Middleware and Web Client blocks here.

. Start build process by running `buildWar` from the command line (provided that you have created the Gradle wrapper beforehand):
+
[source, plain]
----
gradlew buildWar
----
+
As a result, the `app-core.war` and `app.war` files will be created in the `build\distributions\war` project subdirectory.

. Create an <<app_home,application home>> directory, for example, `c:\work\app_home`.
. Copy the `logback.xml` file from the development Tomcat (`deploy/tomcat/conf` project sub-folder) to the application home and edit the `logDir` property in this file:
+
[source, xml]
----
<property name="logDir" value="${app.home}/logs"/>
----
. Download and install Jetty to a local directory, for example, `c:\work\jetty-home`. This example has been tested on `jetty-distribution-9.4.22.v20191022.zip`.

. Create the `c:\work\jetty-base` directory, open the command prompt in it and execute:
+
[source, plain]
----
java -jar c:\work\jetty-home\start.jar --add-to-start=http,jndi,deploy,plus,ext,resources
----

. Create the `c:\work\jetty-base\app-jetty.xml` file defining the database connection pool. Contents of the file for a PostgreSQL database should be based on the following template:
+
[source, xml]
----
include::{sourcesdir}/deployment/warDeployment_2.xml[]
----
+
The `app-jetty.xml` file for MS SQL databases should correspond to the following template:
+
[source, xml]
----
include::{sourcesdir}/deployment/warDeployment_5.xml[]
----

. Download the following JARs required for the DB connection pool and put them to the `c:\work\jetty-base\lib\ext` folder. Two of these files can be found in the `deploy\tomcat\shared\lib` project sub-folder:
+
[source, plain]
----
commons-pool2-2.6.2.jar
commons-dbcp2-2.7.0.jar
commons-logging-1.2.jar
----

. Copy the `start.ini` file from the Jetty distribution to the `c:\work\jetty-base` folder. Add the following text to the beginning of the `c:\work\jetty-base\start.ini` file:
+
[source, plain]
----
include::{sourcesdir}/deployment/warDeployment_3.ini[]
----

. Copy the JDBC driver for your database to the `c:\work\jetty-base\lib\ext` directory. You can take the driver file from the `deploy\tomcat\lib` project directory. In case of PostgreSQL database, it is `postgresql-42.2.5.jar`.

. Copy WAR files to the `c:\work\jetty-base\webapps` directory.

. Open the command prompt in the `c:\work\jetty-base` directory and run:
+
[source, plain]
----
java -jar c:\work\jetty-home\start.jar
----

. Open `++http://localhost:8080/app++` in your web browser.

