:sourcesdir: ../../../../../../source

[[metadataTools]]
====== MetadataTools

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/global/MetadataTools.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`MetadataTools` is a <<managed_beans,managed bean>>, containing additional methods for working with metadata. You can access `MetadataTools` interface by either using `Metadata.getTools()` method, or as any other bean – by means of injection or through `AppBeans` class.

`MetadataTools `methods:

* `getAllPersistentMetaClasses()` – returns the collection of persistent entities <<metaClass,meta-classes>>.
* `getAllEmbeddableMetaClasses()` – returns the collection of embeddable entities meta-classes.
* `getAllEnums()` – returns the collection of enumeration classes used as entity attributes types.
* `format()` – formats the passed value according to data type of the given <<metaProperty,meta-property>>.
* `isSystem()` – checks if a meta-property is system, i.e. specified in one of the <<entity_base_classes,basic entity interfaces>>.
* `isPersistent()` – checks if a meta-property is persistent, i.e. stored in the database.
* `isTransient()` – checks if a meta-property or an arbitrary attribute is non-persistent.
* `isEmbedded()` – checks if a meta-property is an embedded object.
* `isAnnotationPresent()` – checks if an annotation is present on the class or on one of its ancestors.
* `getNamePatternProperties()` – returns collection of meta-properties of attributes included in the instance name, returned by `Instance.getInstanceName()` method. See <<namePattern_annotation,@NamePattern>>.

You can <<bean_extension,override>> `MetadataTools` bean in your application to extend the set of its methods. The examples of working with the extended interface:

[source, java]
----
include::{sourcesdir}/common/metadatatools_1.java[]
----

[source, java]
----
include::{sourcesdir}/common/metadatatools_2.java[]
----

