:sourcesdir: ../../../../../source

[[url_routing]]
===== API для маршрутизации

В этом разделе описываются ключевые понятия API для маршрутизации.

[[url_route_registration]]
Регистрация маршрута::
+
--
Для регистрации маршрута экрана добавьте аннотацию `@Route` к контроллеру экрана, например:

[source, java]
----
include::{sourcesdir}/gui/url_new_screen_registration.java[]
----

Аннотация имеет два параметра:

* `path` (или `value`) – маршрут на самого себя;
* `parentPrefix` используется для сжатия маршрутов (смотрите <<url_route_squashing,ниже>>).

Если вам нужно определить маршрут для <<screens,устаревшего экрана>>, добавьте атрибуты `route` (и `routeParentPrefix` для сжатия) к элементу экрана в файле <<screens.xml,screens.xml>>, например:

[source, xml]
----
include::{sourcesdir}/gui/url_legacy_screen_registration.xml[]
----
--

[[url_route_squashing]]
Сжатие маршрута::
+
--
Эта функция предназначена для того, чтобы URL-адрес был понятным и читаемым при открытии нескольких экранов с маршрутами, имеющими одинаковые части.

Предположим, что у нас есть экраны браузера и редактора для сущности `Order`:

[source, java]
----
include::{sourcesdir}/gui/url_routes_squashing1.java[]
----

Сжатие URL-адреса используется, чтобы избежать повторения маршрута `orders` в URL-адресе, когда экран редактора открывается сразу после браузера. Просто укажите повторяющуюся часть в параметре `parentPrefix` аннотации `@Route` на экране редактора:

[source, java]
----
include::{sourcesdir}/gui/url_routes_squashing2.java[]
----

Теперь, когда редактор открыт в той же вкладке, что и браузер, полученный адрес будет похож на `app/#main/0/orders/edit?id=...`

--

[[url_ui_state_mapping]]
Отображение состояния пользовательского интерфейса на URL::
+
--

`UrlRouting` бин позволяет изменять текущий URL приложения в соответствии с текущим экраном и некоторыми параметрами. Он имеет следующие методы:

* `pushState()` – изменяет адрес и отправляет новую запись истории браузера;
* `replaceState()` – заменяет адрес без добавления новой записи истории браузера;
* `getState()` – возвращает текущее состояние как объект `NavigationState`.

Методы `pushState()/replaceState()` принимают текущий контроллер экрана и дополнительный мэп параметров.

Смотрите пример использования `UrlRouting` в разделе <<mapping_state_to_url,ниже>>.

--

[[url_navigation_filter]]
Фильтр навигации::
+
--
Механизм фильтров навигации позволяет предотвратить переход на некоторые маршруты.

Фильтр навигации – это управляемый бин, реализующий интерфейс `NavigationFilter`. Аннотацию `@Order` можно использовать для настройки порядка вызова всех фильтров навигации. Используйте константы `NavigationFilter.HIGHEST_PLATFORM_PRECEDENCE` и `NavigationFilter.LOWEST_PLATFORM_PRECEDENCE` чтобы задать диапазон, используемый фильтрами, определенными в фреймворке.

Интерфейс `NavigationFilter` имеет метод `allowed()`, который принимает два аргумента: текущее состояние навигации `fromState` и запрошенное состояние навигации `toState`. Метод возвращает экземпляр `AccessCheckResult` и проверяет, разрешен ли переход из текущего состояния навигации в запрошенное состояние.

`CubaLoginScreenFilter` является примером фильтра навигации. Он предназначен для проверки подлинности текущего сеанса, чтобы предотвратить переход к экрану входа в систему, когда пользователь уже вошел в систему:

[source, java]
----
include::{sourcesdir}/gui/url_navigation_filter.java[]
----
--