:sourcesdir: ../../../../source

[[access_to_repo]]
==== Настройка доступа к репозиторию

Основной репозиторий::
+
--
При создании нового проекта в CUBA Studio вам необходимо выбрать основной репозиторий, содержащий артефакты платформы. По умолчанию имеется два таких репозитория (может быть больше если установлен <<private_repo,приватный репозиторий>>):

* `++https://repo.cuba-platform.com/content/groups/work++` - репозиторий, расположенный на сервере Haulmont. Он требует передачи общих имени и пароля, которые указываются прямо в скрипте сборки (`cuba` / `cuba123`).

* `++https://dl.bintray.com/cuba-platform/main++` - репозиторий, находящийся в https://bintray.com[JFrog Bintray]. Он предоставляет анонимный доступ.

Оба репозитория имеют идентичное содержимое для последних версий платформы, но Bintray не содержит снэпшотов. Мы предполагаем, что Bintray является более надежным для доступа из любой точки мира.

В случае Bintray, скрипт сборки сконфигурирован также для использования репозиториев Maven Central, JCenter и Vaadin Add-ons по отдельности.
--

[[access_to_premium_repo]]
Доступ к премиум-дополнениям CUBA::
+
--

[TIP]
====
Начиная с версии 7.0, дополнения BPM, Charts, Full-Text Search и Reposrts распространяются свободно. Они располагаются в основном репозитории, поэтому конфигурировать доступ к премиум-репозиторию нужно только для использования других премиум-дополнений, например WebDAV.
====

Если ваш проект использует премиум-дополнения, Studio добавляет еще один репозиторий:

* В случае `repo.cuba-platform.com` это `++https://repo.cuba-platform.com/content/groups/premium++`

* В случае Bintray это `++https://cuba-platform.bintray.com/premium++`

Если используется <<private_repo,приватный репозиторий>>, автоматически ничего не добавляется, так как предполагается, что он проксирует все CUBA-репозитории, включая премиум.

Оба репозитория премиум-дополнений требуют указания имени пользователя и пароля, которые предоставляются по подписке на разработчика. Первая часть лицензионного ключа до тире представляет собой имя пользователя, вторая часть после тире - пароль. Например, если ваш ключ `111111222222-abcdefabcdef`, то имя - `111111222222`, пароль - `abcdefabcdef`

Studio передает Gradle параметры подключения когда запускает скрипт сборки. При сборке проекта вне Studio передайте `premiumRepoUser` и `premiumRepoPass` в командной строке в аргументах `-P`. В случае Bintray, к имени пользователя нужно в конце добавить `@cuba-platform`.

Пример сборки используя `repo.cuba-platform.com`:

[source]
----
gradlew assemble -PpremiumRepoUser=111111222222 -PpremiumRepoPass=abcdefabcdef
----

Пример сборки используя Bintray:

[source]
----
gradlew assemble -PpremiumRepoUser=111111222222@cuba-platform -PpremiumRepoPass=abcdefabcdef
----

Чтобы при сборке проекта из командной строки не передавать имя и пароль каждый раз, можно однократно задать их одним из следующих способов.

* Либо создать файл `~/.gradle/gradle.properties` и указать параметры в нем:

[source]
----
premiumRepoUser=111111222222
premiumRepoPass=abcdefabcdef
----

* Либо указать параметры в следующих переменных среды операционной системы:

* `CUBA_PREMIUM_USER` - используется если не передан `premiumRepoUser`.

* `CUBA_PREMIUM_PASSWORD` - используется если не передан `premiumRepoPass`.
--

[[custom_repositories]]
Дополнительные репозитории::
+
--
Проект может использовать любые дополнительные репозитории, содержащие <<app_components,компоненты приложения>>. Они должны быть вручную указаны в `build.gradle` *после* основного репозитория, например:

[source,groovy]
----
include::{sourcesdir}/development/access_to_repo_1.groovy[]
----
--

