:sourcesdir: ../../../../source

[[build_task_start]]
==== Запуск задач сборки

Задачи (tasks) Gradle, описанные в скриптах сборки, запускаются на исполнение следующими способами:

* Если работа с проектом ведется с помощью CUBA Studio, то многие команды, которые запускаются из главного меню *CUBA*, делегируют выполнение задачам Gradle: это все команды пункта *Build Tasks*, команды *Start/Stop/Restart Application Server* и *Create/Update Database*.

* С помощью исполняемого скрипта `gradlew` (Gradle wrapper), включенного в проект.

* С помощью установленного вручную Gradle версии {gradleVersion}. В этом случае используется исполняемый файл `gradle`, находящийся в подкаталоге `bin` установленного Gradle.

Например, чтобы выполнить компиляцию Java файлов и сборку JAR файлов артефактов проекта, необходимо запустить следующую команду:

.Windows:
[source]
----
gradlew assemble
----

.Linux & macOS:
[source]
----
./gradlew assemble
----

[WARNING]
====
Если ваш проект использует премиум-дополнения, и вы запускаете сборку вне Studio, необходимо передать в Gradle имя и пароль доступа к премиум-репозиторию. См. раздел <<access_to_premium_repo, выше>> для получения подробной информации.
====

Рассмотрим типичные задачи сборки в обычном порядке их использования.

* `assemble` - выполнить компиляцию Java файлов и сборку JAR файлов артефактов проекта в подкаталогах `build` модулей.

* `clean` - удалить подкаталоги `build` всех модулей проекта.

* <<build.gradle_setupTomcat,setupTomcat>> - установить сервер *Tomcat* в путь, заданный свойством `cuba.tomcat.dir` скрипта `build.gradle`.

* <<build.gradle_deploy,deploy>> - <<fast_deployment,быстрое развертывание>> приложения на сервере *Tomcat*, предварительно установленном задачей `setupTomcat`.

* <<build.gradle_createDb,createDb>> - создание базы данных приложения и выполнение соответствующих <<db_scripts,скриптов>>.

* <<build.gradle_updateDb,updateDb>> - обновление существующей базы данных приложения путем выполнения соответствующих <<db_scripts,скриптов>>.

* <<build.gradle_start,start>> - запуск сервера Tomcat.

* <<build.gradle_stop,stop>> - остановка запущенного сервера Tomcat.

* <<build.gradle_restart,restart>> - последовательное выполнение задач `stop`, `deploy`, `start`. 

