:sourcesdir: ../../../../source

[[build.gradle]]
==== Структура build.gradle

В данном разделе описывается структура и основные элементы скрипта `build.gradle`.

buildscript::
+
--
В секции `buildscript` задается следующее:

* Версия платформы, на которой основан данный проект.

* Набор репозиториев, из которых будут загружаться зависимости проекта. Настройка доступа к репозиториям описана <<access_to_repo,ниже>>.

* Зависимости, используемые системой сборки, включая плагин CUBA для Gradle.

После секции `buildscript` объявляются несколько переменных, используемых далее в скрипте.
--

cuba::
+
--
Логика сборки, специфичная для CUBA, сосредоточена в Gradle плагине `cuba`. Он подключается в корне скрипта и в секциях `configure` каждого модуля:

[source, groovy]
----
apply(plugin: 'cuba')
----

Параметры плагина *cuba* задаются в секции `cuba`:

[source, groovy]
----
include::{sourcesdir}/development/build_gradle_1.groovy[]
----

Рассмотрим доступные параметры:

* `artifact` - задает группу и версию собираемых <<artifact,артефактов>> проекта. Имена артефактов формируются на основе имен модулей, заданных в `settings.gradle`.

** `group` - группа артефактов.
** `version` - версия артефактов.
** `isSnapshot` - если установлено в `true`, то в именах артефактов будет присутствовать суффикс `SNAPSHOT`.
+
Версию артефактов можно переопределить в командной строке, например:
+
[source, plain]
----
gradle assemble -Pcuba.artifact.version=1.1.1
----

* `tomcat` - задает параметры сервера Tomcat, который используется для <<fast_deployment, быстрого развертывания>>.

** `dir` - расположение каталога <<build.gradle_setupTomcat, установки>> Tomcat.
** `port` - порт сервера; по умолчанию 8080.
** `debugPort` - порт для подключения Java отладчика; по умолчанию 8787.
** `shutdownPort` - порт для передачи команды `SHUTDOWN`; по умолчанию 8005.
** `ajpPort` - порт AJP connector; по умолчанию 8009.

// TODO update for new Studio
* `ide` - задает некоторые параметры для Studio и IDE.

** `vcs` - тип используемой в проекте VCS. В данный момент поддерживаются только `Git` и `svn`.
** `copyright` - текст Copyright Notice, вставляемый в начало файлов исходных текстов.
** `classComment` - текст комментария, который будет расположен над объявлением класса в исходных текстах Java.

* `uploadRepository` - задает параметры <<artifact_repository,репозитория>>, в который будут выгружаться собранные артефакты проекта при выполнении задачи `uploadArchives`.
+
** `url` - URL репозитория. По умолчанию используется репозиторий Haulmont.
** `user` - имя пользователя репозитория.
** `password` - пароль пользователя репозитория.
+
Параметры репозитория выгрузки артефактов можно передать в командной строке с помощью следующих аргументов:
+
[source]
----
gradlew uploadArchives -PuploadUrl=http://myrepo.com/content/repositories/snapshots -PuploadUser=me -PuploadPassword=mypassword
----
--

dependencies::
+
--
Данная секция описывает набор <<app_components,компонентов приложения>>, используемых в проекте. Зависимости бывают двух типов: `appComponent` - для компонентов CUBA и `uberJar` - для библиотек, которые загружаются перед стартом приложения. Компоненты CUBA указываются координатами артефакта их модуля *global*. В примере ниже используются три компонента: `com.haulmont.cuba` (компонент *cuba* платформы), `com.haulmont.reports` (премиум-дополнение *reports*) и `com.company.base` (кастомный компонент):

[source, groovy]
----
dependencies {
  appComponent("com.haulmont.cuba:cuba-global:$cubaVersion")
  appComponent("com.haulmont.reports:reports-global:$cubaVersion")
  appComponent("com.company.base:base-global:0.1-SNAPSHOT")
}
----
--

configure::
+
--
Секции `configure` описывают конфигурацию <<app_modules,модулей>>. Наиболее важная часть конфигурации - описание зависимостей, например:

[source,groovy]
----
include::{sourcesdir}/development/build_gradle_2.groovy[]
----

[[build.gradle_enhance]]
Блок `entitiesEnhancing` позволяет описать конфигурацию bytecode enhancement (weaving) классов сущностей. Его нужно объявить как минимум в модуле *global*, однако можно включить его в конфигурацию каждого модуля по-отдельности.

Секции `main` и `test` здесь - это наборы исходников проекта и тестов, а необязательный параметр `persistenceConfig` позволяет явно указать набор файлов <<persistence.xml, persistence.xml>>. Если не установлено, задача будет обрабатывать все персистентные сущности, перечисленные в файлах `*persistence.xml`, найденных в CLASSPATH.

[source,groovy]
----
include::{sourcesdir}/development/build_gradle_3.groovy[]
----

Нестандартные зависимости модулей можно задавать в Studio в экране *Project properties > Advanced*. См. также контекстную помощь Studio.
--

[TIP]
====
В случае транзитивных зависимостей и конфликта версий будет использована стандартная стратегия разрешения версий Maven. Согласно этой стратегии, релизные версии имеют приоритет над snapshot-версиями, а более точный числовой квалификатор имеет приоритет над более общим. При прочих равных, строковые квалификаторы приоритизируются в алфавитном порядке. Пример:

[source, plain]
----
1.0-beta1-SNAPSHOT         // низкий приоритет
1.0-beta1
1.0-beta2-SNAPSHOT         |
1.0-rc1-SNAPSHOT           |
1.0-rc1                    |
1.0-SNAPSHOT               |
1.0                        |
1.0-sp                     V
1.0-whatever
1.0.1                      // высокий приоритет
----
====

