:sourcesdir: ../../../../source

[[private_repo]]
==== Установка приватного репозитория артефактов

В этом разделе рассказывается, как установить приватный Maven репозиторий, чтобы использовать его для хранения артефактов платформы и других зависимостей, вместо публичного репозитория CUBA. Это рекомендуется делать в следующих случаях:

- У вас нестабильное или слабое интернет-соединение. Несмотря на то что Gradle кэширует артефакты на компьютере разработчика, время от времени все-таки необходимо подключаться к репозиторию артефактов, например, при первом запуске проекта или при переключении на новую версию платформы.
- У вас ограничен доступ к интернету из-за политики безопасности организации.
- Вы не собираетесь продлевать подписку на премиум-дополнения, но вы бы хотели продолжить разработку вашего приложения в будущем, используя загруженные версии артефактов.

Процесс установки приватного репозитория состоит из следующих шагов:

- Разверните локальный менеджер репозиториев, подключенный к интернету.
- Настройте приватный репозиторий как прокси для публичного репозитория CUBA.
- Настройте build-скрипт вашего проекта на использование приватного репозитория. Это можно сделать через Studio, либо через правку файла `build.gradle`.
- Выполните полную сборку проекта, чтобы все необходимые артефакты закэшировались в приватный репозиторий.
- Если требуется разрабатывать приложение CUBA в изолированной сети, то установите еще одну копию менеджера репозиториев в изолированной сети и скопируйте в него содержимое кэша из первого репозитория.

include::private_repo/private_repo_install.adoc[]

include::private_repo/private_repo_configure.adoc[]

include::private_repo/private_repo_usage.adoc[]

include::private_repo/private_repo_in_isolated_network.adoc[]

include::private_repo/private_repo_studio_in_isolated_network.adoc[]

