:sourcesdir: ../../../../source

[[credits]]
==== Информация об используемом ПО

Платформа предоставляет средства для регистрации и отображения в пользовательском интерфейсе информации об используемом в приложении стороннем программном обеспечении (credits). Информация включает в себя название, ссылку на веб-сайт и текст лицензии.

<<app_components,Компоненты>> платформы содержат собственные файлы описаний `com/haulmont/cuba/credits.xml`, `com/haulmont/reports/credits.xml` и т.д. В проекте приложения можно создать аналогичный файл и в свойстве приложения <<cuba.creditsConfig,cuba.creditsConfig>> указать этот файл.

Структура файла `credits.xml`:

* Элемент `items` - перечисление используемых библиотек с указанием текста лицензии либо во вложенном элементе `license`, либо атрибутом `license` со ссылкой на текст в секции `licenses`.
+
Cсылаться можно на лицензии, объявленные не только в этом же файле, но и в любом другом файле, объявленном в переменной `cuba.creditsConfig` раньше, чем текущий.

* Элемент `licenses` - перечисление текстов общеупотребительных лицензий.

Для отображения общего списка используемого ПО предназначен фрейм `com/haulmont/cuba/gui/app/core/credits/credits-frame.xml`, загружающий информацию из файлов, заданных в свойстве `cuba.creditsConfig`. Пример использования фрейма в экране:

[source, xml]
----
<dialogMode width="500" height="400"/>
<layout expand="creditsBox">
  <groupBox id="creditsBox"
            caption="msg://credits"
            width="100%">
      <frame id="credits"
              src="/com/haulmont/cuba/gui/app/core/credits/credits-frame.xml"
              width="100%"
              height="100%"/>
  </groupBox>
</layout>
----

Если экран с фреймом открывается в диалоговом режиме (`WindowManager.OpenType.DIALOG`), ему необходимо задать высоту, иначе возможна неправильная работа скроллинга. См. элемент `dialogMode` в примере выше.

