:sourcesdir: ../../../../source

[[email_sending]]
==== Отправка email

Платформа предоставляет средства отправки сообщений электронной почты со следующими возможностями:

* Синхронная или асинхронная отправка. В случае синхронной отправки вызывающий код ожидает, пока сообщение не будет передано на SMTP сервер. При асинхронной отправке сообщение сохраняется в базе данных, и управление немедленно возвращается вызывающему коду. Отправка производится позже путем вызова из <<scheduled_tasks,назначенного задания>>.

* Надежная фиксация факта отправки и ошибок в базе данных, как для синхронной, так и для асинхронной отправки.

* Пользовательский интерфейс для поиска и просмотра информации о посылаемых сообщениях, включая все атрибуты и содержимое сообщений, а также статус отправки и количество предпринятых попыток.

Пример использования данного механизма рассмотрен в рецепте <<sending_emails_recipe,Отправка email>>.


include::email_sending/email_sending_methods.adoc[]

include::email_sending/email_attachments.adoc[]

include::email_sending/email_sending_properties.adoc[]

