:sourcesdir: ../../../../source

[[entityImportExport]]
==== Экспорт и импорт сущностей в JSON

Платформа предоставляет API для экспортирования и импортирования графов сущностей в формате JSON. Он доступен на Middleware в виде интерфейса `EntityImportExportAPI`, и на клиентском уровне в виде сервиса `EntityImportExportService`. Эти интерфейсы имеют одинаковый набор методов, описанный ниже. Реализация экспорта/импорта делегирует выполнение интерфейсу `EntitySerializationAPI`, который при необходимости может быть использован напрямую.

* `exportEntitiesToJSON()` - сериализует коллекцию сущностей в JSON.
+
[source, java]
----
include::{sourcesdir}/common/entityImportExportService_1.java[]
----

* `exportEntitiesToZIP()` - сериализует коллекцию сущностей в JSON и упаковывает его в ZIP-архив. В следующем примере упакованный архив сохраняется в хранилище данных с помощью интерфейса <<fileLoader,FileLoader>>:
+
[source, java]
----
include::{sourcesdir}/common/entityImportExportService_2.java[]
----

* `importEntitiesFromJSON()` - десериализует граф сущностей из JSON и сохраняет десериализованные сущности согласно правилам, описанным в параметре `entityImportView` (см. JavaDocs на класс `EntityImportView`). Если некоторой сущности нет в базе данных, она создается, в противном случае атрибуты, переданные в `entityImportView`, обновляются у сущности, уже имеющейся в базе данных.

* `importEntitiesFromZIP()` - читает ZIP-архив, содержащий JSON, распаковывает его и обрабатывает аналогично методу `importEntitiesFromJSON()`.
+
[source, java]
----
include::{sourcesdir}/common/entityImportExportService_3.java[]
----

