:sourcesdir: ../../../../source

[[entity_log]]
==== Журнал изменений сущностей

Механизм журналирования предназначен для отслеживания изменений атрибутов произвольных сущностей в процессе работы приложения. Измененные значения сохраняются в специальной таблице базы данных, список изменений для конкретного экземпляра сущности может быть отображен в пользовательском интерфейсе.

Данный механизм перехватывает сохранение сущностей в БД на уровне <<entity_listeners,Entity Listeners>>, т.е. гарантированно отслеживаются все изменения, проходящие через персистентный контекст <<entityManager,EntityManager>>. Непосредственное изменение сущностей в базе данных с помощью SQL, в том числе изнутри системы через <<nativeQuery,NativeQuery>> и <<queryRunner,QueryRunner>>, в журнал не попадает.

Измененные экземпляры сущностей перед сохранением в БД отправляются в методы `registerCreate()`, `registerModify()`, `registerDelete()` бина `EntityLogAPI`. Параметр `auto` этих методов позволяет отделить автоматическое журналирование посредством Entity Listeners от ручного вызова этих же методов в прикладном коде. При вызове из Entity Listeners в параметре `auto` передается `true`.

Журнал содержит информацию о том, кто и когда изменил данный экземпляр, а также новые значения измененных атрибутов. Записи журнала сохраняются в таблице *SEC_ENTITY_LOG* базы данных, соответствующей сущности `EntityLogItem`. Измененные значения атрибутов хранятся в этой же таблице в колонке *CHANGES*, а при чтении на *Middleware* преобразуются в экземпляры сущности `EntityLogAttr`.

include::entity_log/entity_log_setup.adoc[]

include::entity_log/entity_log_view.adoc[]

