:sourcesdir: ../../../../source

[[folders_pane]]
==== Панель папок

Панель папок предназначена для быстрого доступа пользователя к часто используемой информации. Она представляет собой скрываемую панель в левой части главного окна приложения, в которой располагается иерархическая структура, нажатие на элементы которой (папки) приводит к отображению соответствующих экранов системы с определенными параметрами.

На момент написания данного руководства панель папок реализована только для <<app_tiers,Web Client>>.

Платформа поддерживает три вида папок: _папки приложения_, _папки поиска_ и _наборы_ записей. Папки приложения отображаются в верхней части панели в отдельной иерархии, папки поиска и наборы - в нижней части панели в совместной иерархии. Чтобы использовать в папках <<shortcuts,горячие клавиши>>, свойство <<cuba.web.foldersPaneEnabled,cuba.web.foldersPaneEnabled>> должно иметь значение `true`.

* Папки приложения:

** Открывают экраны с <<gui_Filter,фильтром>> или без него.

** Набор папок может зависеть от текущего сеанса пользователя. Видимость конкретной папки определяется путем выполнения скрипта Groovy.

** Пользователь может создавать или изменять папки приложения, только если у него есть специальное право.

** В заголовке папки может отображаться текущее количество входящих в папку записей, вычисляемое скриптом Groovy.

** Заголовки папок приложения обновляются по таймеру, тем самым может изменяться счетчик записей и стиль отображения каждой папки.

* Папки поиска:

** Открывают экраны с <<gui_Filter,фильтром>>.

** Могут быть как локальными - доступными только пользователю, их создавшему, так и глобальными - доступными всем пользователям.

** Локальные папки может создавать и изменять любой пользователь, глобальные - только имеющий специальное право.

* Наборы:

** Открывают экраны с <<gui_Filter,фильтром>>, содержащим условие отбора отдельных записей по их идентификаторам.

** Содержимое набора редактируется с помощью специальных <<gui_Action,действий>> таблицы: *Добавить в набор*, *Удалить из набора*.

** Наборы локальны, то есть доступны только создавшему их пользователю.

На функционирование панели папок влияют следующие свойства приложения:

* <<cuba.web.foldersPaneEnabled,cuba.web.foldersPaneEnabled>>

* <<cuba.web.foldersPaneVisibleByDefault,cuba.web.foldersPaneVisibleByDefault>>

* <<cuba.web.foldersPaneDefaultWidth,cuba.web.foldersPaneDefaultWidth>>

* <<cuba.web.appFoldersRefreshPeriodSec,cuba.web.appFoldersRefreshPeriodSec>>

* <<cuba.web.showFolderIcons,cuba.web.showFolderIcons>>

include::folders_pane/application_folder.adoc[]

include::folders_pane/search_folder.adoc[]

include::folders_pane/record_set.adoc[]

