:sourcesdir: ../../../../source

[[myBatis]]
==== Интеграция с MyBatis

В состав платформы включен фреймворк link:$$http://www.mybatis.org$$[MyBatis], обладающий, по сравнению с <<nativeQuery,ORM>> и <<queryRunner,QueryRunner>>, более широкими возможностями по выполнению SQL и отображению результатов на объекты предметной области.

Для использования MyBatis в проекте необходимо выполнить следующие шаги.

. Создайте класс-обработчик UUID в корневом пакете модуля *core*.
+
[source, java]
----
include::{sourcesdir}/features/MyBatis.java[]
----

. Создайте файл конфигурации `mybatis.xml` в модуле *core* рядом с файлом <<spring.xml,spring.xml>>, указав в нём ссылку на обработчик `UUIDTypeHandler`:
+
[source, xml]
----
include::{sourcesdir}/features/MyBatis_2.xml[]
----

. Добавьте следующие бины в файл <<spring.xml,spring.xml>> модуля *core*:
+
--
[source, xml]
----
include::{sourcesdir}/features/MyBatis.xml[]
----

Бин `sqlSessionFactory` содержит ссылку на созданный ранее `mybatis.xml`.

В параметре `mapperLocations` задается путь (по правилам интерфейса `ResourceLoader` *Spring*) к файлам отображений *MyBatis*.
--

. Наконец, добавьте зависимости MyBatis в секцию модуля `core` в файле <<build.gradle,build.gradle>>:
+
[source, groovy]
----
compile('org.mybatis:mybatis:3.2.8')
compile('org.mybatis:mybatis-spring:1.2.5')
----

Пример файла отображения для загрузки экземпляра сущности `Заказ` вместе со связанным `Покупателем` и коллекцией `Пунктов заказа`:

[source, xml]
----
include::{sourcesdir}/features/mapper.xml[]
----

Для получения результатов запроса в приведенном выше примере можно использовать следующий код:

[source, java]
----
Transaction tx = persistence.createTransaction();
try {
  SqlSession sqlSession = AppBeans.get("sqlSession");
  Order order = (Order) sqlSession.selectOne("com.sample.sales.selectOrder", orderId);
  tx.commit();
} finally {
  tx.end();
}
----

