:sourcesdir: ../../../../source

[[pessimistic_locking]]
==== Пессимистичная блокировка

Пессимистичная блокировка сущностей применяется, если велика вероятность одновременного редактирования одного и того же экземпляра, и стандартная <<optimistic_locking,оптимистичная блокировка>>, основанная на версионности сущностей, порождает слишком много коллизий.

Пессимистичная блокировка использует явное блокирование экземпляра сущности при открытии его в <<screen_edit,экране редактирования>>. В результате только один пользователь в некоторый момент времени может редактировать данный экземпляр сущности.

Механизм пессимистичной блокировки можно использовать также для управления совместным выполнением произвольных процессов. Причем блокировки являются распределенными, т.к. информация о них реплицируется в кластере Middleware. Подробнее см. JavaDoc интерфейсов `LockManagerAPI` и `LockService`.

Режим пессимистичной блокировки может быть задан для любого класса сущности в процессе настройки или эксплуатации системы с помощью экрана *Administration > Locks > Setup*, либо следующим образом:

* вставить в таблицу *SYS_LOCK_CONFIG* запись со следующими значениями полей:

** *ID* - произвольный идентификатор типа UUID.

** *NAME* - наименование блокируемого объекта. Для сущности это должно быть имя ее <<metaClass,мета-класса>>.

** *TIMEOUT_SEC* - таймаут истечения блокировки в секундах.
+
Например:
+
[source, sql]
----
insert into sys_lock_config (id, create_ts, name, timeout_sec) values (newid(), current_timestamp, 'sales_Order', 300)
----

* перезапустить сервер или выполнить метод `reloadConfiguration()` JMX-бина `app-core.cuba:type=LockManager`.

Текущее состояние блокировок можно отслеживать через JMX-бин `app-core.cuba:type=LockManager`, или через специальный экран, доступный в меню *Administration > Locks*. Экран также позволяет разблокировать любой объект принудительно.

