:sourcesdir: ../../../../source

[[userSession_log]]
==== Журналирование пользовательских сессий

Механизм журналирования предназначен для отслеживания факта входа пользователей в систему. В журнале администратор системы может найти информацию, кто и когда вошёл в систему и вышел из неё. Механизм основан на отслеживании <<userSession,пользовательских сессий>>. При каждом создании объекта `UserSession` в базу данных сохраняется следующая информация:

* ID сессии пользователя,

* ID пользователя,

* ID <<user_substitution,замещаемого пользователя>>,

* последнее действие пользователя (логин / выход / истечение срока сессии / сессия прервана),

* удаленный IP-адрес, с которого пришёл запрос на вход в систему,

* тип клиента (web, desktop, portal),

* ID сервера (например, `localhost:8080/app-core`),

* дата и время начала сессии,

* дата и время окончания сессии,

* информация о клиенте (окружение сессии: операционная система, веб-браузер и т.д.).

По умолчанию записи о пользовательских сессиях не сохраняются. Простейший способ активировать журналирование - воспользоваться кнопкой *Enable* *Logging* в экране приложения *Administration > User Session Log*. В качестве альтернативы можно установить в `true` значение свойства приложения `cuba.UserSessionLogEnabled` и перезапустить сервер.

При необходимости можно создать отчёт для сущности `sec$SessionLogEntry`.

