:sourcesdir: ../../../../../../source

[[web_theme_reusable]]
====== Повторное использование тем

Любую тему можно создать и использовать отдельно от <<web_theme_inheritance,компонента приложения>>. Для создания темы, которую можно использовать повторно, необходимо создать с нуля отдельный Java-проект и собрать его в единый JAR-файл. Ниже приведена инструкция, как подготовить тему `facebook` из предыдущих примеров для многократного использования.

. Создайте в IDE новый Java-проект, содержащий файлы SCSS и свойства темы, со следующей структурой:
+
--
[source, plain]
----
include::{sourcesdir}/gui/themes/themes_31.scss[]
----

Этот проект также доступен на https://github.com/cuba-labs/halo-facebook[GitHub].

* Содержание скрипта `build.gradle`:
+
[source, groovy]
----
include::{sourcesdir}/gui/themes/themes_32.groovy[]
----

* Содержание файла `settings.gradle`:
+
[source, groovy]
----
include::{sourcesdir}/gui/themes/themes_33.groovy[]
----

* Содержание файла `app-component.scss`:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_34.scss[]
----

* Содержание файла `halo-facebook.scss`:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_35.scss[]
----

* Содержание файла `halo-facebook-defaults.scss`:
+
[source, css]
----
include::{sourcesdir}/gui/themes/themes_36.css[]
----

* Содержание файла `halo-facebook-theme.properties`:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_37.scss[]
----
--

. Соберите и установите проект с помощью задачи Gradle:
+
[source, plain]
----
gradle assemble install
----

. Теперь добавьте эту тему в свой CUBA-проект в качестве зависимости Maven в двух конфигурациях: themes и compile, добавив в `build.gradle` следующие строки:
+
[source, groovy]
----
include::{sourcesdir}/gui/themes/themes_38.groovy[]
----
+
Если вы установили тему локально, не забудьте добавить локальный репозиторий Maven к списку используемых в проекте репозиториев. Для этого перейдите на вкладку *Advanced* в окне Studio *Project Properties* и установите флажок *Use local Maven repository*.

. Чтобы унаследовать тему и добавить модификации для конкретного проекта, необходимо сначала расширить эту тему. Расширьте тему `halo` и переименуйте каталог `themes/halo` в `themes/halo-facebook`:
+
[source, plain]
----
include::{sourcesdir}/gui/themes/themes_39.scss[]
----

. Внесите следующие изменения в файл `styles.scss`:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_40.scss[]
----

. Последним шагом будет добавление ссылки на `halo-facebook-theme.properties` в файле `web-app.properties`:
+
[source, plain]
----
include::{sourcesdir}/gui/themes/themes_41.scss[]
----

Теперь тема `halo-facebook` будет доступна в меню приложения *Help* > *Settings*. Вы также можете установить тему по умолчанию, используя свойство приложения `cuba.web.theme`.

