:sourcesdir: ../../../../../source

[[standard_actions]]
===== Standard Actions

Standard <<gui_Action,actions>> are provided by the framework to solve common tasks, such as invocation of an edit screen for an entity selected in a table. A standard action can be declared in screen XML descriptor by specifying its type in the `type` attribute, for example:

[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_1.xml[]
----

The standard action configures itself depending on its type and owning component. It may or may not require additional parameters.

There are two categories of standard actions:

* <<std_list_actions,Actions over collections>> of entities that are displayed in tables or trees.

* <<std_picker_actions,Picker field actions>>.

You can create similar actions or override existing standard types in your project.

For example, imagine that you need an action that would show the instance name of the currently selected entity in a table, and you would like to use this action in multiple screens by specifying its type only. Below are the steps to create such action.

. Create an action class and add the `@ActionType` annotation with the desired type name:
+
[source, java]
----
include::{sourcesdir}/gui/std_actions/std_actions_2.java[]
----

. In the `web-spring.xml` file, add `<gui:actions>` element with the `base-packages` attribute pointing to a package where to find your annotated actions:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_2_1.xml[]
----

. Now you can use the action in screen descriptors by specifying its type:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_2_2.xml[]
----

include::standard_actions/std_list_actions.adoc[]

include::standard_actions/std_picker_actions.adoc[]

