:sourcesdir: ../../../../../source

[[private_repo_configure]]
===== Configure the Proxy Repository

Click to the *Repositories* link on the left panel.

On the opened *Repositories* page click the *Add* button, then choose *Proxy Repository*. A new repository will be added. Fill in required fields at *Configuration* tab:

- *Repository ID*: `cuba-work`
- *Repository Name*: `cuba-work`
- *Provider*: `Maven2`
- *Remote Storage Location*: `++https://repo.cuba-platform.com/content/groups/work++`
- *Auto Blocking Enabled*: `false`
- Enable *Authentication*, set *Username*: `cuba`, *Password*: `cuba123`
- Click *Save* button.

Create a Repository Group, in Nexus click *Add* button, then choose *Repository Group* and do the following on *Configuration* tab:

- Enter the *Group ID*: `cuba-group`
- Enter the *Group Name*: `cuba-group`
- *Provider*: `Maven2`
- Add the repository *cuba-work* from *Available Repositories* to *Ordered Group Repositories*
- Click *Save* button.

If you have a subscription to the Premium Add-ons, add one more repository with the following settings:

- *Repository ID*: `cuba-premium`
- *Repository Name*: `cuba-premium`
- *Provider*: `Maven2`
- *Remote Storage Location*: `++https://repo.cuba-platform.com/content/groups/premium++`
- *Auto Blocking Enabled*: `false`
- Enable *Authentication*, set the first part of your license key (before dash) in the *Username* field and the second part of your license key (after dash) in the *Password* field.
- Click *Save* button.
- Click *Refresh* button.
- Select the *cuba-group* group.
- On the *Configuration* tab, add *cuba-premium* repository to the group below *cuba-work*.
- Click *Save* button.

