:sourcesdir: ../../../../source

[[app_tiers]]
==== Application Tiers and Blocks

The framework enables building multi-tiered applications with the distinct client, middle and database tiers. Further on, we will consider mainly the middle and client tiers, so the words "all tiers" will refer to these tiers only.

An application can have one or more _blocks_ on each tier. A block is a separate executable program interacting with other blocks of the application. Usually, a block is a web application running on JVM.

.Application Tiers and Blocks
image::AppTiers.svg[align="center"]

Middleware:: The middle tier contains core business logic of the application and provides access to the database. It is represented by a separate web application running on a Java servlet container. See <<middleware>>.

Web Client:: A main block of the client tier. It contains the interface designed primarily for internal (back-office) users. It is represented by a separate web application running on a Java servlet container. The user interface is based on the *Vaadin* framework. See <<gui_framework>>.

Web Portal:: An additional block of the client tier. It can contain an interface for external users and entry points for integration with mobile devices and third-party applications. It is represented by a separate web application running on a Java servlet container. The user interface is based on the *Spring MVC* framework. See <<portal>>.

Frontend UI:: An optional UI layer designed for external users and written in pure JavaScript. It is based on the *Google Polymer* or *React* frameworks and communicates with the middleware via <<rest_api_v2,REST API>> running either in Web Client or in Web Portal blocks. See <<polymer_ui>>.

Middleware is the mandatory block for any application. User interface can be implemented by one or several blocks, such as Web Client and Web Portal.

All of the Java-based client blocks interact with the middle tier uniformly via HTTP protocol which enables deploying the middle tier arbitrarily, behind a firewall as well. In the simplest case, when the middle tier and the web client are deployed on the same server, local interaction between them can bypass the network stack for better performance.

