:sourcesdir: ../../../../source

[[app_structure]]
==== Application Structure

The above-listed architectural principles are directly reflected in the structure of the assembled application. Suppose we have a simple application which has two blocks – Middleware and Web Client; and includes the functionality of two application components - *cuba* and *reports*.

.The structure of a simple application 
image::SampleAppArtifacts.svg[align="center"]

The figure demonstrates the contents of several directories of the *Tomcat* server with the deployed application.

The Middleware block is represented by the `app-core` web application, the Web Client block – by the `app` web application. The web applications contain the JAR files located in the `WEB-INF/lib` directories. Each JAR (<<artifact, artifact>>) is a result of building a single <<app_modules,module>> of an application or one of its <<app_components,components>>.

For instance, the set of JAR files of the `app-core` web application is determined by the fact that the Middleware block includes *global* and *core* modules; and the application uses *cuba* and *reports* components.

