:sourcesdir: ../../../../source

[[app_components]]
==== Application Components

The framework enables splitting the application functionality into components. Each _application component_ (AKA add-on) can have its own data model, business logic and user interface. The application uses the component as a library and includes its functionality.

The concept of application components allows us to keep the framework relatively small, while delivering optional business functionality in the components like Reporting, Full-Text Search, Charts, WebDAV and others. At the same time, the application developers can use this mechanism to decompose large projects into a set of functional modules which can be developed independently and have a different release cycle. Of course, application components can be reusable and provide a domain-specific layer of abstraction on top of the framework.

Technically, the core framework is also an application component called *cuba*. The only difference is that it is mandatory for any application. All other components depend on *cuba* and can also have dependencies between each other.

Below is a diagram showing dependencies between the standard components typically used in an application. Solid lines demonstrate mandatory dependencies, dashed lines mean optional ones.

image::BaseProjects.svg[align="center"]

The following diagram illustrates a possible structure of dependencies between standard and custom application components.

image::AppComponents2.svg[align="center"]

Any CUBA application can be easily turned into a component and provide some functionality to another application. In order to be used as a component, an application project should contain an <<app-component.xml,app-component.xml>> descriptor and a special entry in the manifest of the *global* module JAR. CUBA Studio allows you to generate the descriptor and manifest entry for the current project automatically.

See the step-by-step guide to working with a custom application component in the <<app_components_sample>> section.
