:sourcesdir: ../../../../../source

[[oto_single_editor]]
===== Композиция One-to-One в одном редакторе

++++
<div class="manual-live-demo-container">
    <a href="https://demo3.cuba-platform.com/generic-ui/open?screen=sample$Customer.browse" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Сущности, связанные композицией с типом <<composition_oto_recipe,один-к-одному>>, часто бывает удобно создавать в одном общем экране редактирования. Рассмотрим, как можно реализовать такой экран, на примере отношений сущностей https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/global/src/com/company/sample/entity/Customer.java[Customer] и https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/global/src/com/company/sample/entity/CustomerDetails.java[CustomerDetails].

* https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/web/src/com/company/sample/web/customer/customer-edit.xml[customer-edit.xml] содержит основной источник данных `customerDs` и вложенный в него `detailsDs`:
+
--
[source, xml]
----
include::{sourcesdir}/cookbook/oto_single_editor.xml[]
----

Поля для редактирования обеих сущностей сгруппированы в один компонент `fieldGroup`, где отдельные поля привязаны к вложенному источнику данных:

[source, xml]
----
include::{sourcesdir}/cookbook/oto_single_editor_2.xml[]
----
--

* В контроллере экрана https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/web/src/com/company/sample/web/customer/CustomerEdit.java[CustomerEdit] мы переопределяем метод `initNewItem()`. В нём создаём новый экземпляр `CustomerDetails` и связываем его с только что созданным экземпляром `Customer`:
+
--
[source, java]
----
include::{sourcesdir}/cookbook/oto_single_editor_3.java[]
----

Напоследок обработаем ситуацию, когда пользователь нажимает *Create*, а затем закрывает редактор экрана без каких-либо изменений в полях покупателя. По умолчанию, пользователю будет предложено сохранить или отменить изменения, так как `detailsDs` уже содержит пустой экземпляр `CustomerDetails`, а значит, метод `isModified()` вернёт `true`. Чтобы предотвратить появление такого диалога для пустых сущностей, заставим метод `isModified()` принимать во внимание только изменения в главном источнике данных экрана:

[source, java]
----
include::{sourcesdir}/cookbook/oto_single_editor_4.java[]
----
--

Теперь обе сущности можно создавать и редактировать в одном экране.

