:sourcesdir: ../../../../../../source

[[scheduled_tasks_cuba_impl]]
====== Особенности реализации

* Период вызова обработки заданий (метода `SchedulingAPI.processScheduledTasks()`) задается в `cuba-spring.xml` и по умолчанию равен 1 сек. Он задает минимальное значение периода запуска задания, которое должно быть в два раза больше, т.е. 2 сек. Уменьшать эти времена не рекомендуется.

* Текущая реализация планировщика основана на синхронизации с помощью блокировки строк в таблице базы данных. Это означает, что при значительной нагрузке БД может не успевать вовремя отвечать планировщику, и необходимо увеличивать период запуска (>1сек), и, соответственно, минимальный период запуска заданий также будет увеличиваться.

* Синглтон-задания в случае незаданного атрибута Permitted servers выполняются только на мастер-узле кластера (при выполнении прочих условий). Следует иметь в виду, что отдельный сервер вне кластера также является мастером.

* Задание не запускается, если оно в данный момент не закончило предыдущее выполнение, и не истек указанный Timeout. Для синглтон-заданий в текущей реализации это обеспечивается информацией в базе данных, для не-синглтонов поддерживается таблица статуса выполнения в памяти сервера.

* Механизм выполнения создает и кэширует <<userSession,пользовательские сессии>> в соответствии с указанными для заданий *User name*, либо свойством приложения <<cuba.jmxUserLogin,cuba.jmxUserLogin>>. Сессия доступна в потоке выполнения запускаемого задания обычным способом - через интерфейс <<userSessionSource,UserSessionSource>>.

[WARNING]
====
Для нормальной работы синглтон-заданий необходима точная синхронизация серверов *Middleware* по времени!
====

