:sourcesdir: ../../../../../source

[[entityStates]]
===== EntityStates

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.0/com/haulmont/cuba/core/global/EntityStates.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Интерфейс для получения информации о персистентных сущностях, сохраняемых через  <<orm,ORM>>. В отличие от бинов <<persistence,Persistence>> и <<persistenceTools,PersistenceTools>> доступен на всех <<app_tiers,уровнях>> приложения.

Методы `EntityStates`:

* `isNew()` - определяет, является ли переданный экземпляр только что созданным. Он может быть либо в состоянии <<entity_states,New>>, либо <<entity_states,Managed>>, но только что сохраненным в текущей транзакции. Также возвращает `true` для неперсистентных сущностей.

* `isManaged()` - определяет, находится ли переданный экземпляр в состоянии <<entity_states,Managed>>, то есть присоединен к персистентному контексту.

* `isDetached()` - определяет, находится ли переданный экземпляр в состоянии <<entity_states,Detached>>. Возвращает `true`, также если экземпляр не является персистентной сущностью.

*  `isLoaded()` - определяет, загружен ли данный атрибут сущности. Атрибут загружается, если он включен в <<views,представление>>, или если это локальный атрибут и никакое представление не использовалось в процессе загрузки через <<entityManager,EntityManager>> или <<dataManager,DataManager>>. Данный метод поддерживает проверку только непосредственных атрибутов сущностей.

* `checkLoaded()` - то же самое что и `isLoaded()`, но выбрасывает `IllegalArgumentException` если хотя бы один из переданных атрибутов не загружен.

* `isLoadedWithView()` - принимает экземпляр сущности и представление, и возвращает true если все атрибуты требуемые в представлении на самом деле загружены.

* `checkLoadedWithView()` - то же самое что и `isLoadedWithView()`, но выбрасывает `IllegalArgumentException` вместо возврата false.

* `makeDetached()` - принимает только что созданный экземпляр сущности и переводит его в состояние detached. Detached-объект можно передать в `DataManager.commit()` или `EntityManager.merge()` для сохранения его состояния в базе данных. Подробнее см. API docs.

* `makePatch()` - принимает только что созданный экземпляр сущности и превращает его в _patch-объект_. Patch-объект можно передать в `DataManager.commit()` или `EntityManager.merge()` для сохранения его состояния в базе данных, при этом в отличие от detached-объекта, будут сохранены только не-null атрибуты. Подробнее см. API docs.

include::entityStates/persistenceHelper.adoc[]

