:sourcesdir: ../../../../../source

[[events]]
===== Events

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.0/com/haulmont/cuba/core/global/Events.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Бин `Events` реализует функциональность публикации объектов-событий уровня приложения. События могут использоваться для передачи данных между слабо связанными компонентами приложения. Бин `Events` является простым фасадом для объекта `ApplicationEventPublisher` Spring Framework.

[source, java]
----
include::{sourcesdir}/common/events.java[]
----

Этот бин имеет только один метод - `publish()`, принимающий объект события. Метод `Events.publish()` уведомляет все слушатели, зарегистрированные в приложении и подписанные на события того же типа, что и переданный объект. Вы может использовать класс-обёртку `PayloadApplicationEvent` для публикации любых объектов в качестве событий.

См. также https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2[руководство Spring Framework].

[[bean_events]]
Обработка событий в компонентах приложения::
+
--

Прежде всего, необходимо создать класс события. Он должен быть наследником класса `ApplicationEvent`. Класс события может включать любые дополнительные данные. Например:
[source, java]
----
include::{sourcesdir}/common/events_DemoEvent.java[]
----

Бины могут публиковать события, используя бин `Events`:
[source, java]
----
include::{sourcesdir}/common/events_DemoBean.java[]
----

По умолчанию все события обрабатываются синхронно.

Есть два способа обработки событий:

- Реализовать интерфейс `ApplicationListener`.
- Использовать аннотацию `@EventListener` для метода.

В первом случае, мы должны создать бин, реализующий интерфейс `ApplicationListener` с указанием типа события:
[source, java]
----
include::{sourcesdir}/common/events_DemoEventListener.java[]
----

Второй способ может использоваться для сокрытия деталей реализации обработчика событий и обработки множества различных событий в одном бине:
[source, java]
----
include::{sourcesdir}/common/events_MultipleEventListener.java[]
----

[TIP]
====
По умолчанию, события в Spring требуют модификаторов доступа `protected`, `package` или `public` для методов, аннотированных `@EventListener`. Обратите внимание, что модификатор `private` не поддерживается.
====

[WARNING]
====
Методы, аннотированные `@EventListener`, не работают в компонентах JMX. При их использовании вы на старте приложения будет выброшено исключение:
----
BeanInitializationException: Failed to process @EventListener annotation on bean. Need to invoke method declared on target class, but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
----
Реализуйте интерфейс `ApplicationListener` с типом нужного события.
====

Вы можете использовать интерфейс `Ordered` и аннотацию `@Order` Spring Framework для указания порядка исполнения обработчиков событий. Все бины и обработчики событий платформы используют значение `order` от 100 до 1000, таким образом, вы можете добавить обработчик событий как до, так и после обработчиков события платформы. Если вы хотите добавить свой обработчик события до обработчиков из платформы, то используйте значение меньше 100.

См. также <<login_events,События логина>>.
--

[[ui_events]]
Обработка событий в экранах::
+
--
Обычно, бин `Events` делегирует публикацию события объекту `ApplicationContext`. Для блоков Web Client / Desktop Client это поведение отличается от стандартного, вы можете использовать дополнительный интерфейс для классов событий - `UiEvent`. Это интерфейс-маркер для событий, которые должны быть доставлены в экраны пользовательского интерфейса текущего экземпляра UI (текущей вкладки веб-браузера). Важно отметить, что экземпляры событий, реализующих `UiEvent`, не доставляются в бины Spring и не могут быть обработаны за пределами UI.

Пример класса события:
[source, java]
----
include::{sourcesdir}/common/events_UserRemovedEvent.java[]
----

События публикуются при помощи бина `Events` из контроллера экрана так же, как и из бинов Spring:
[source, java]
----
include::{sourcesdir}/common/events_publish.java[]
----

Чтобы обработать событие, вы должны объявить в экране метод с аннотацией `@EventListener` (Интерфейс `ApplicationListener` не поддерживается):
[source, java]
----
include::{sourcesdir}/common/events_EventListener.java[]
----

Вы можете использовать аннотацию `@Order`, чтобы задать порядок вызова обработчиков события.

Если класс события реализует `UiEvent`, и объект такого события опубликован при помощи бина `Events` из потока UI, то будут вызваны обработчики событий этого типа в открытых на данный момент окнах и фреймах. Обработка событий синхронная. Только экраны и фреймы текущей активной вкладки веб-браузера получат уведомление о событии.
--

