:sourcesdir: ../../../../../source

[[messages]]
===== Messages

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/core/global/Messages.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Интерфейс `Messages` обеспечивает получение <<localization,локализованных строк сообщений>>.

Рассмотрим методы интерфейса подробнее.

* `getMessage()` - возвращает локализованное сообщение по ключу, имени пакета сообщений и требуемой локали. Существует несколько модификаций данного метода в зависимости от набора параметров. Если локаль не указана в параметре метода, используется локаль текущего пользователя.
+
Примеры:
+
[source, java]
----
@Inject
protected Messages messages;
...
String message1 = messages.getMessage(getClass(), "someMessage");
String message2 = messages.getMessage("com.abc.sales.web.customer", "someMessage");
String message3 = messages.getMessage(RoleType.STANDARD);
----

* `formatMessage()` - находит локализованное сообщение по ключу, имени пакета сообщений и требуемой локали, и использует его для форматирования переданных параметров. Формат задается по правилам метода `String.format()`. Существует несколько модификаций данного метода в зависимости от набора параметров. Если локаль не указана в параметре метода, используется локаль текущего пользователя.
+
Пример:
+
[source, java]
----
String formattedValue = messages.formatMessage(getClass(), "someFormat", someValue);
----

* `getMainMessage()` - возвращает локализованное сообщение из <<main_message_pack,главного пакета>> данного <<app_tiers,блока>> приложения.
+
Пример:
+
[source, java]
----
protected Messages messages = AppBeans.get(Messages.class);
...
messages.getMainMessage("actions.Ok");
----

* `getMainMessagePack()` - возвращает имя <<main_message_pack,главного пакета>> сообщений данного блока приложения.
+
Пример:
+
[source, java]
----
String formattedValue = messages.formatMessage(messages.getMainMessagePack(), "someFormat", someValue);
----

* `getTools()` - возвращает экземпляр интерфейса `MessageTools` (см. ниже).

include::messages/messageTools.adoc[]

