:sourcesdir: ../../../../../source

[[metadata]]
===== Metadata

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/core/global/Metadata.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Интерфейс `Metadata` обеспечивает доступ к сессии <<metadata_framework,метаданных>> и репозиторию <<views,представлений>>.

Методы интерфейса:

* `getSession()` - возвращает экземпляр сессии <<metadata_framework,метаданных>> 

* `getViewRepository()` - возвращает экземпляр репозитория <<views,представлений>>

* `getExtendedEntities()` - возвращает экземпляр `ExtendedEntities`, предназначенный для работы с расширенными сущностями. Подробнее см. <<entity_extension,>>

* `create()` - создать экземпляр сущности, учитывая возможность <<entity_extension,расширения>>.
+
Для персистентных наследников `BaseLongIdEntity` и `BaseIntegerIdEntity` данный метод также присваивает идентификаторы. Значения идентификаторов получаются из автоматически создаваемых в базе данных последовательностей. По умолчанию последовательности создаются в <<data_store,основном хранилище>>. Если же свойство приложения <<cuba.useEntityDataStoreForIdSequence,cuba.useEntityDataStoreForIdSequence>> установлено в true, последовательности будут создаваться в хранилище, к которому принадлежит данная сущность.

* `getTools()` - возвращает экземпляр интерфейса `MetadataTools` (см. ниже).

include::metadata/metadataTools.adoc[]

