:sourcesdir: ../../../../../source

[[resources]]
===== Resources

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/core/global/Resources.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Обеспечивает загрузку ресурсов по следующим правилам:

. если указанное местонахождение представляет собой URL, ресурс загружается из этого URL;

. если указанное местонахождение начинается с префикса `classpath:`, ресурс загружается из classpath;

. если не URL и не начинается с `classpath:`, то:

.. в <<conf_dir,каталоге конфигурации>> приложения ищется файл, используя указанное местонахождение как относительный путь. Если файл найден, ресурс загружается из него;

.. если ресурс не найден на предыдущих этапах, он загружается из classpath.

На практике явное указание URL или префикса `classpath:` используется редко, т.е. обычно ресурсы загружаются либо из <<conf_dir,конфигурационного каталога>>, либо из classpath. Ресурс в конфигурационном каталоге замещает одноименный ресурс в classpath.

Методы `Resources`:

* `getResourceAsStream()` - возвращает `InputStream` для указанного ресурса, либо `null`, если ресурс не найден. Поток должен быть закрыт после использования, например:
+
[source, java]
----
include::{sourcesdir}/common/resources_1.java[]
----
+
Возможно использование "try with resources":
+
[source, java]
----
include::{sourcesdir}/common/resources_2.java[]
----

* `getResourceAsString()` - возвращает указанный ресурс в виде строки, либо `null`, если ресурс не найден

