= CUBA Platform. BPM subsystem
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.8
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)

:!sectnums:

++++++++++++++
<span style="color: red;">A newer version is available at the <a style="color: inherit; text-decoration: underline;" href="https://www.cuba-platform.com/documentation">documentation home</a>.</span>
++++++++++++++

[[preface]]
== Preface

This manual describes the CUBA Platform Business Process Management subsystem.

We assume that the reader is familiar with the CUBA Platform Developer's Manual, which is available at https://www.cuba-platform.com/manual.

CUBA business process management subsystem is based on the Activiti framework, therefore general knowledge on the framework is beneficial. See http://www.activiti.org to learn more about Activiti. Processes are defined according to the BPMN 2.0 notation, so it is assumed that the reader is familiar with the notation. More information about BPMN 2.0 specification can be found at  http://www.bpmn.org.

If you have any suggestions for improving this manual, please contact Technical Support at http://www.cuba-platform.com/support. When reporting errors in the documentation, please indicate the chapter and surrounding text to point the error.

:sectnums:

include::quickstart.adoc[]

include::datamodel.adoc[]

include::functionality.adoc[]

include::services.adoc[]

include::ui.adoc[]

include::examples.adoc[]

[[app_properties]]
[appendix]
== Application properties

bpm.activiti.asyncExecutorEnabled:: Possible values: `true` or `false`. Defines whether Job Executor for timers and asynchronous tasks is enabled. The default value is `false`.