[[examples]]
== Examples

[[process_runtime_service_usage]]
=== Starting a Process Programmatically

A convenient way to start a new process from the entity editor is to use the `ProcActionsFrame`, but sometimes a process needs to be started programmatically. To do so, we need to create a new ProcInstance object with filled ProcActors collection (if required). The ProcIntance object graph may be created in a regular way (using the Metadata bean), but BPM add-on has a handy method for this: `BpmEntitiesService.createProcInstance(ProcInstanceDetails procInstanceDetails)`. 

Suppose, we have deployed a process definition with the code `orderProcessing`. This process definition has two roles: `manager` and `storekeeper`.

To create a `ProcInstance` object using the `BpmEntitiesService` you may use a code like this:

[source, java]
----
include::{sourcesdir}/start_process.java[]
----

The code above will create a not persistent instance of the `ProcInstance` entity. Its `procDefinition` property will be set to the process definition with the code `orderProcessing` (if such process definition is not found, an exception will be thrown). Also, the process instance object will have two process actors: one for the process role with a code `manager` (the current user), and another one for the process role with a code `storekeeper` (someOtherUser which was evaluated beforehand). If the process definition doesn't have roles with given codes, an exception will be thrown.

After the process instance is created we need to pass it to the `ProcessRuntimeService.startProcess()`. The method will start the process and save the ProcInstance and ProcActors entities to the database.