[[preface]]
== Preface

This document is the user manual for the CUBA Platform business process management subsystem.

=== Target Audience

This manual is intended for developers who use the CUBA platform to create applications with business processes management functionality. It is assumed that the reader is familiar with the Developer's Manual, which is available at https://www.cuba-platform.com/manual.

=== Additional Materials

This manual, as well as other documentation on the CUBA platform, are available at https://www.cuba-platform.com/manual.

CUBA business process management subsystem is based on the Activiti framework, therefore general knowledge on  the framework is beneficial. See http://www.activiti.org to learn more about the Activity framework.

An executable process description employs the BPMN 2.0 notation. Consequently, it is assumed that the reader is familiar with the notation. More information about BPMN 2.0 specification can be found at  http://www.bpmn.org.


=== Feedback

If you have any suggestions for improving this manual, please contact Technical Support at http://www.cuba-platform.com/support/topics.

When reporting errors in the documentation, please indicate the chapter and surrounding text to point the error.