[[intro]]
== Introduction

This document is the user manual for the CUBA Platform business process management subsystem.

=== Target Audience

This manual is intended for developers who use the CUBA platform to create applications with business processes management functionality. It is assumed that the reader is familiar with the Developer's Manual, which is available at http://www.cuba-platform.com/en/manual.

=== Additional Materials

This manual, as well as other documentation on the CUBA platform, are available at http://www.cuba-platform.com/en/manual.

CUBA business process management subsystem is based on the Activiti framework, therefore familiarity with the framework will be beneficial. See http://www.activiti.org.

An executable process should be described in BPMN 2.0 notation. A developer should be familiar with this notation. See http://www.bpmn.org.

=== Feedback

If you have any suggestions for improving this manual, please contact Technical Support at http://www.cuba-platform.com/support/topics.

When reporting errors in the documentation, please indicate the chapter number and include a small portion of the surrounding text to make the search easier.