[[services]]
== Main services

[[process-repository-service]]
=== ProcessRepositoryService

It serves for a working with process definitions. The service is used for:

* load a process definition from XML
* undeploy a process from Activiti engine
* transform a JSON model to BPMN XML

To access the service functionality on middleware layer use  ProcessRepositoryManager.

[[process-runtime-service]]
=== ProcessRuntimeService

It serves for a working with process instances . The service methods allows to:

* start a process
* cancel a process
* complete a task
* assign a task to the user

To access the service functionality on middleware layer use ProcessRuntimeManager.

[[process-form-service]]
=== ProcessFormService

The service is used for getting an information about:

* task outcomes
* forms that should be displayed for outcomes
* forms on process start and cancel

To access the service functionality on middleware layer use ProcessFormManager.

[[process-messages-service]]
=== ProcessMessagesService

The service is used for accessing to localized messages defined in the process. 

To access the service functionality on middleware layer use ProcessMessagesManager.

[[model-service]]
=== ModelService

It is used for creating and updation of models in Activiti internal tables, and for getting a model JSON.