[[services]]
== Main Services

This section contains only general description of the services. Detailed service methods description is available in Java classes documentation.

[[process_repository_service]]
=== ProcessRepositoryService

It is designed to work with process definitions. The service is used to:

* load a process definition from XML
* undeploy a process from Activiti engine
* transform the JSON model to BPMN XML

To access the service functionality on middleware, use the `ProcessRepositoryManager` bean.

[[process_runtime_service]]
=== ProcessRuntimeService

It is designed to work with process instances. The service methods allows you to:

* <<process_runtime_service_usage,start a process>>
* cancel a process
* complete a task
* assign a task to the user

When a process is started, the following process variables are created automatically:

* `bpmProcInstanceId` - `ProcInstance` object ID
* `entityName` - linked entity name
* `entityId` - linked entity ID

To access the service functionality on middleware, use the `ProcessRuntimeManager` bean.

[[process_runtime_service_usage]]
==== Starting a Process Programmatically

Below is an example of starting a service programmatically from a screen controller using the `ProcessRuntimeService` instance. This sample project is also available on https://github.com/Haulmont/cuba-bpm[GitHub].

. First of all, load the <<ProcDefinition,process definition>> by its code:
+
--
[source, java]
----
ProcDefinition procDefinition = dataManager.load(
        LoadContext.create(ProcDefinition.class)
                .setQuery(new LoadContext.Query("select pd from bpm$ProcDefinition pd where pd.code = :code")
                        .setParameter("code", PROCESS_CODE))
                .setView("procDefinition-procInstanceEdit")
);
----
--

. Next, create the <<ProcInstance,process instance>> and associate it with the process definition and entity:
+
--
[source, java]
----
ProcInstance procInstance = metadata.create(ProcInstance.class);
procInstance.setProcDefinition(procDefinition);
procInstance.setEntityId(getItem().getUuid());
procInstance.setEntityName(getItem().getMetaClass().getName());
----
--

. Create <<ProcActor,process actors>> with the <<ProcRole,roles>> assigned:
+
--
[source, java]
----
ProcActor manager = metadata.create(ProcActor.class);
manager.setUser(userSession.getUser());
manager.setOrder(0);
manager.setProcInstance(procInstance);
manager.setProcRole(procDefinition.getProcRoles().get(0));

ProcActor mechanic = metadata.create(ProcActor.class);
mechanic.setUser(getItem().getMechanic().getUser());
mechanic.setOrder(1);
mechanic.setProcInstance(procInstance);
mechanic.setProcRole(procDefinition.getProcRoles().get(1));
----
--

. Associate the set of actors with the process instance:
+
--
[source, java]
----
Set<ProcActor> procActors = new HashSet<>();
procActors.add(manager);
procActors.add(mechanic);

procInstance.setProcActors(procActors);
----
--

. Commit created actors and process instances to the database:
+
--
[source, java]
----
Set<Entity> committed = dataManager.commit(new CommitContext()
        .addInstanceToCommit(manager)
        .addInstanceToCommit(mechanic)
        .addInstanceToCommit(procInstance));
----
--

. Start the persisted process instance:
+
--
[source, java]
----
ProcInstance committedProcInstance = (ProcInstance) committed.stream()
        .filter(p -> p.equals(procInstance))
        .findFirst()
        .orElseThrow(() -> new RuntimeException("Error"));

processRuntimeService.startProcess(committedProcInstance, "Started!", new HashMap<>());
----
--

The complete code of the `startProcess()` method in the screen controller invoked on a button click:

[source, java]
----
include::{sourcesdir}/start_process.java[]
----

[[process_form_service]]
=== ProcessFormService

The service is used to provide information about:

* task outcomes
* forms that should be displayed for outcomes
* forms to appear on process start and cancel

To access the service functionality on middleware, use the `ProcessFormManager` bean.

[[process_messages_service]]
=== ProcessMessagesService

The service is used to access localized messages which are defined in the process.

To access the service functionality on middleware, use the `ProcessMessagesManager` bean.

[[model_service]]
=== ModelService

The service is used to create and update models in Activiti internal tables. Also, it works with the JSON representation of the model.