[[services]]
== Main Services

The chapter contains only general description of the services. Detailed service methods description is available in Java classes documentation.

[[process_repository_service]]
=== ProcessRepositoryService

It serves to work with process definitions. The service is used to:

* load a process definition from XML
* undeploy a process from Activiti engine
* transform the JSON model to BPMN XML

To access the service functionality on middleware layer use the `ProcessRepositoryManager` bean.

[[process_runtime_service]]
=== ProcessRuntimeService

It serves to work with process instances. The service methods allows to:

* start a process
* cancel a process
* complete a task
* assign a task to the user

When a process is started the following process variables are automatically created:

* `bpmProcInstanceId` - ProcInstance object ID
* `entityName` - linked entity name
* `entityId` - linked entity ID

To access the service functionality on middleware layer use the `ProcessRuntimeManager` bean.

[[process_form_service]]
=== ProcessFormService

The service is used to provide information about:

* task outcomes
* forms that should be displayed for outcomes
* forms to appear on process start and cancel

To access the service functionality on middleware layer use the `ProcessFormManager` bean.

[[process_messages_service]]
=== ProcessMessagesService

The service is used to access the localized messages which are defined in the process. 

To access the service functionality on middleware layer use the `ProcessMessagesManager` bean.

[[model_service]]
=== ModelService

The service is used to create and update models in Activiti internal tables. Also it serves to work with the JSON representation of the model.