[[ui_components]]
== UI Components

[[proc_actions_frame]]
=== ProcActionsFrame

The `ProcActionsFrame` can be embedded to application screens. If the frame is linked with the process instance, the following components will be automatically displayed:

* the start process button, in case if the process is not started yet
* the buttons for task outcomes, in case if the process is started and the current user has an active task
* the cancel process button
* the task information panel (name and creation date)

The predicative listener can be assigned to each of the process actions in order to check if the action can be performed (e.g. predicate commits an editor and if the commit failed, a process action is not performed). The post-action listener can also be defined (e.g. listener will close the editor and show the notification).

The sequence of steps to initialize the frame in the screen controller code: 

* Assign all required predicates and post-action listeners to the frame
* Invoke the `init()` method with the `procInstance` argument

[[process_forms]]
=== Process forms

[[proc_form_interface]]
==== ProcForm Interface

When you declare user task outcomes or the start event node in the model editor it is possible to set a form that will be displayed to the user. The form should implement the `ProcForm` interface.
The methods of the `ProcForm` interface:

* `String getComment()` - returns the value that will be written to the `comment` field of the ProcTask object or to the `startComment` field of the ProcInstance if the form is displayed on a process start.
* `Map<String, Object> getFormResult()` - returns a list of objects that will be added to process variables after the form commit.

[[bpm_forms]]
==== A List of Forms for a Process Model Designer

A list of forms available in a process model designer is built according to the configuration files that are defined in a `bpm.formsConfig` application property. To add a new process form do the following:

. Create and register a screen for the form. Screen controller must implement the `ProcForm` interface.

. Create an XML file with custom forms description. Put it under the `src` directory of the *web* or the *gui* module.
+
.app-bpm-forms.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns="http://schemas.haulmont.com/cuba/5.5/bpm-forms.xsd">
    <form name="myCustomForm" defult="true">
        <param name="someParam" value="hello"/>
        <param name="otherParam"/>
    </form>
</forms>
----
+
`myCustomForm` is a screen id.
+
The above configuration also describes available form parameters with their names and default values.
+
A form with a `default="true"` attribute will be used as the default form in the model.

. Override a `bpm.formsConfig` property in the `web-app.properties` file.
+
[source]
----
bpm.formsConfig = bpm-forms.xml app-bpm-forms.xml
----

