[[ui-components]]
== UI components

[[proc-actions-frame]]
=== ProcActionsFrame

ProcActionsFrame can be embedded to application screens. After the frame is linked with the process instance the next components will be automatically displayed:

* start process button, if the process is not started yet
* buttons for task outcomes, if the process is started and the current user has an active task
* cancel process button
* task information (name and creation date)

A predicate can be assigned to each process action. A predicate is evaluated before the action, that allows to check whether the action can be performed at the current time (e.g. to commit the editor and if the commit failed, not to perform a process action). A listener, that will be invoked after the action, can also be defined (e.g. to close the editor and to show a notification).

A sequence of steps to initialize a frame in the screen controller code: 

* Assign all required predicates and listeners
* Invoke an init() method with a procInstance argument

[[process-forms]]
=== Process forms

[[proc-form-interface]]
==== ProcForm interface

It is possible to set a form that will be displayed to the user when describing user task outcomes or start event node. The form should implement a ProcForm interface.
The methods of a ProcForm interface:

* String getComment() - a value returned by this method will be written to the comment field of the ProcTask object or to the startComment field of a ProcInstance if the form is displayed on a process start.
* Map<String, Object> getFormResult() - returns a list of objects that will be added to process variables after form commit.

[[bpm-forms]]
==== A list of forms for a process model designer

A list of forms available in a process model designer is built based on configuration files that are defined in a bpm.formsConfig application property.

.bpm-forms.xml example
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<forms xmlns="http://schemas.haulmont.com/cuba/5.5/bpm-forms.xsd">
    <form name="standardProcForm" default="true">
        <param name="commentRequired" value="true"/>
        <param name="procActorsVisible" value="true"/>
        <param name="attachmentsVisible" value="true"/>
    </form>
    <form name="otherForm">
        <param name="someParam" value="hello"/>
    </form>
</forms>
----

Besides the form name a file describes names of form available parameters and their default values.

A form with a default="true" attribute value will be used as a default form in the model.