[[ui-components]]
== UI Components

[[proc-actions-frame]]
=== ProcActionsFrame

The `ProcActionsFrame` can be embedded to application screens. After the frame is linked with the process instance, the next components will be automatically displayed:

* a start process button, if the process is not started yet
* buttons for task outcomes, if the process is started and the current user has an active task
* a cancel process button
* a task information (a name and a creation date)

A predicate can be assigned to each of the process actions. A predicate is evaluated before the action, that allows to check whether an action can be performed at the current time (e.g. predicate commits an editor and if the commit failed, a process action is not performed). A listener, that will be invoked after the action, can also be defined (e.g. listener will close the editor and show the notification).

A sequence of steps to initialize the frame in the screen controller code: 

* Assign all required predicates and listeners to the frame
* Invoke an `init()` method with a `procInstance` argument

[[process-forms]]
=== Process forms

[[proc-form-interface]]
==== ProcForm Interface

When you describe user task outcomes or a start event node in the model editor, it is possible to set a form that will be displayed to the user. The form should implement a `ProcForm` interface.
The methods of a `ProcForm` interface:

* `String getComment()` - a value returned by this method will be written to the `comment` field of the ProcTask object or to the `startComment` field of a ProcInstance if the form is displayed on a process start.
* `Map<String, Object> getFormResult()` - returns a list of objects that will be added to process variables after form commit.

[[bpm-forms]]
==== A List of Forms for a Process Model Designer

A list of forms available in a process model designer is built based on configuration files that are defined in a `bpm.formsConfig` application property.

.bpm-forms.xml example
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<forms xmlns="http://schemas.haulmont.com/cuba/5.5/bpm-forms.xsd">
    <form name="standardProcForm" default="true">
        <param name="commentRequired" value="true"/>
        <param name="procActorsVisible" value="true"/>
        <param name="attachmentsVisible" value="true"/>
    </form>
    <form name="otherForm">
        <param name="someParam" value="hello"/>
    </form>
</forms>
----

Besides the form name the file describes the names of available form parameters and their default values.

A form with a `default="true"` attribute will be used as the default form in the model.