[[ui_components]]
== UI Components

This section contains description of user interface components provided by the BPM subsystem.

[[proc_actions_frame]]
=== ProcActionsFrame

The `ProcActionsFrame` is designed to work with process actions. After the frame is initialized, the following components will be automatically displayed:

* the start process button, in case if the process is not started yet
* the buttons for task outcomes, in case the process is started and the current user has an active task
* the cancel process button
* the task information panel (name and creation date)

A predicate can be assigned to each of the process actions in order to check if the action can be performed (e.g. the predicate commits an editor, and if the commit failed, the process action is not performed). The post-action listener can also be defined (e.g. the listener will close the editor and show a notification).

The `ProcActionsFrame` must be linked with the `ProcInstance`. The linking is performed during frame initialization.

An example of frame initialization:

[source,java]
----
include::{sourcesdir}/quickstart/ProcActionsFrameInitialization.java[]
----

* The `initializer()` method returns an object that is used for frame initialization.

* The `setBeforeStartProcessPredicate` method sets the predicate that will be evaluated before the process start. If the predicate returns `false` then the process start will be interrupted.

* The `setAfterStartProcessListener` method defines a listener that will be invoked after the process start action is performed.

* The `init` method has two parameters: process code and entity instance. When this method is invoked, a search for the `ProcInstance` object that is related with the entity instance and has a reference to the `ProcDefinition` with the given code is performed. If the `ProcInstance` exists then the frame is linked to it, otherwise a new `ProcInstance` object is created.

Below is the list of methods used for customizing the frame.

Process life cycle::
+
--
[[ProcActionsFrame_initializer]]
* `initializer()` - returns a new instance of frame initializer.

[[ProcActionsFrame_init]]
* `init()` - tries to find the process instance by the specified process code and the entity reference. If the process instance is not found then a new one is created. Then the UI for available actions for the current user and the process instance is initialized.
--

Process configuration::
+
--
[[ProcActionsFrame_setStartProcessEnabled]]
* `setStartProcessEnabled()` - defines whether the process can be started.

[[ProcActionsFrame_setCancelProcessEnabled]]
* `setCancelProcessEnabled()` - defines whether the process can be cancelled.

[[ProcActionsFrame_setCompleteTaskEnabled]]
* `setCompleteTaskEnabled()` - defines whether the task can be completed.

[[ProcActionsFrame_setClaimTaskEnabled]]
* `setClaimTaskEnabled()` - defines whether the task can be assigned to a user by himself.

[[ProcActionsFrame_setTaskInfoEnabled]]
* `setTaskInfoEnabled()` - defines whether the layout with the localized task name and its start date is enabled.

[[ProcActionsFrame_setButtonWidth]]
* `setButtonWidth()` - sets the width of the action control button. The default value is 150 px.
--

Predicates::
+
--
[[ProcActionsFrame_setBeforeStartProcessPredicate]]
* `setBeforeStartProcessPredicate()` - sets the predicate that will be evaluated before the process start. If the predicate returns `false` then the process start will be interrupted.

[[ProcActionsFrame_setBeforeCompleteTaskPredicate]]
* `setBeforeCompleteTaskPredicate()` - sets the predicate that will be evaluated before the task completion. If the predicate returns `false` then the task completion will be interrupted.

[[ProcActionsFrame_setBeforeClaimTaskPredicate]]
* `setBeforeClaimTaskPredicate()` - sets the predicate that will be evaluated before the task is claimed to a user. If the predicate returns `false` then the task assignment will be interrupted.

[[ProcActionsFrame_setBeforeCancelProcessPredicate]]
* `setBeforeCancelProcessPredicate()` - sets the predicate that will be evaluated before the task cancellation. If the predicate returns `false` then the task will not be cancelled.
--

Process and task listeners::
+
--
[[ProcActionsFrame_setAfterStartProcessListener]]
* `setAfterStartProcessListener()` - defines a listener that will be invoked after the process start action is performed.

[[ProcActionsFrame_setAfterCompleteTaskListener]]
* `setAfterCompleteTaskListener()` - defines a listener that will be invoked after the task complete action is performed.

[[ProcActionsFrame_setAfterClaimTaskListener]]
* `setAfterClaimTaskListener()` - defines a listener that will be invoked after the task claim action is performed.

[[ProcActionsFrame_setAfterCancelProcessListener]]
* `setAfterCancelProcessListener()` - defines a listener that will be invoked after the process cancel action is performed.
--

'''

ProcActionsFrame API::
<<ProcActionsFrame_initializer,initializer>>

Initializer API::
<<ProcActionsFrame_init,init>> -
<<ProcActionsFrame_setAfterCancelProcessListener,setAfterCancelProcessListener>> -
<<ProcActionsFrame_setAfterClaimTaskListener,setAfterClaimTaskListener>> -
<<ProcActionsFrame_setAfterCompleteTaskListener,setAfterCompleteTaskListener>> -
<<ProcActionsFrame_setAfterStartProcessListener,setAfterStartProcessListener>> -
<<ProcActionsFrame_setBeforeCancelProcessPredicate,setBeforeCancelProcessPredicate>> -
<<ProcActionsFrame_setBeforeClaimTaskPredicate,setBeforeClaimTaskPredicate>> -
<<ProcActionsFrame_setBeforeCompleteTaskPredicate,setBeforeCompleteTaskPredicate>> -
<<ProcActionsFrame_setBeforeStartProcessPredicate,setBeforeStartProcessPredicate>> -
<<ProcActionsFrame_setButtonWidth,setButtonWidth>> -
<<ProcActionsFrame_setCancelProcessEnabled,setCancelProcessEnabled>> -
<<ProcActionsFrame_setClaimTaskEnabled,setClaimTaskEnabled>> -
<<ProcActionsFrame_setCompleteTaskEnabled,setCompleteTaskEnabled>> -
<<ProcActionsFrame_setStartProcessEnabled,setStartProcessEnabled>> -
<<ProcActionsFrame_setTaskInfoEnabled,setTaskInfoEnabled>>

'''

[[process_forms]]
=== Process Forms

[[proc_form_interface]]
ProcForm Interface::
+
--
When you declare user task outcomes or the start event node in the model editor, it is possible to set a form that will be displayed to the user. The form class should implement the `ProcForm` interface.

The methods of the `ProcForm` interface:

[[proc_form_getComment]]
* `getComment(): String` - returns the value that will be written to the `comment` field of the `ProcTask` object or to the `startComment` field of `ProcInstance` if the form is displayed on a process start.

[[proc_form_getFormResult]]
* `getFormResult(): Map<String, Object>` - returns a list of objects that will be added to process variables after the form commit.
--

[[bpm_forms]]
A List of Forms for a Process Model Designer::
+
--
A list of forms available in the process model designer is built according to the configuration files that are defined in the `bpm.formsConfig` application property. To add a new process form, do the following:

. Create and register a screen for the form. Screen controller must implement the `ProcForm` interface.

. Create an XML file, e.g. `app-bpm-forms.xml`, which will contain a description of custom forms, and place it under the `src` directory of the *web* or *gui* module. For example:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns="http://schemas.haulmont.com/cuba/bpm-forms.xsd">
    <form name="myCustomForm" default="true">
        <param name="someParam" value="hello"/>
        <param name="otherParam"/>
    </form>
</forms>
----
+
`myCustomForm` here is a screen id.
+
The above configuration also describes available form parameters with their names and default values.
+
A form with the `default="true"` attribute will be used as the default form in the model.

. Override the `bpm.formsConfig` property in the `web-app.properties` file.
+
[source]
----
bpm.formsConfig = bpm-forms.xml app-bpm-forms.xml
----
--

'''

API::
<<proc_form_getComment,getComment>> -
<<proc_form_getFormResult,getFormResult>>

'''