:sourcesdir: ../../../../source

[[picker_actions]]
==== Действия поля выбора (устаревшее)

[WARNING]
====
См. <<std_picker_actions>> для информации о новом API доступном начиная с релиза 7.0.
====

Для компонентов <<gui_PickerField,PickerField>>, <<gui_LookupPickerField,LookupPickerField>> и <<gui_SearchPickerField,SearchPickerField>> набор стандартных действий определен в перечислении `PickerField.ActionType`. Реализации являются внутренними классами интерфейса `PickerField`.

Пример использования стандартных действий в компоненте выбора: 

[source, xml]
----
include::{sourcesdir}/gui/pickerActions_1.xml[]
---- 

[[lookupAction]]
*LookupAction*

`LookupAction` - действие с идентификатором *lookup*. Предназначено для выбора экземпляра сущности и установки его в качестве значения компонента. При срабатывании открывает <<screen_lookup,экран выбора>> сущностей.

В классе `LookupAction` определены следующие специфические методы:

* `setLookupScreenOpenType()` - позволяет задать режим открытия экрана выбора сущности. По умолчанию экран открывается в режиме `++THIS_TAB++`. 

* `setLookupScreen()` - позволяет задать идентификатор экрана выбора сущности. По умолчанию используется экран `++{имя_сущности}.lookup++`, например `sales$Customer.lookup`. Если такого экрана не существует, то делается попытка открыть экран `++{имя_сущности}.browse++`, например `sales$Customer.browse`.

* `setLookupScreenParams()` - позволяет задать параметры экрана выбора, передаваемые в его метод `init()`.

* `afterSelect()` - вызывается действием после того, как выбранный экземпляр установлен в качестве значения компонента. Данный метод не имеет реализации и может быть переопределен в наследниках для реакции на это событие. 

* `afterCloseLookup()` - вызывается действием в последнюю очередь после закрытия экрана выбора, независимо от того, был сделан выбор или нет. Данный метод не имеет реализации и может быть переопределен в наследниках для реакции на это событие.  

[[clearAction]]
*ClearAction*

`ClearAction` - действие с идентификатором *clear*. Предназначено для очистки (то есть установки в `null`) текущего значения компонента. 

[[openAction]]
*OpenAction*

`OpenAction` - действие с идентификатором *open*. Предназначено для открытия экрана редактирования экземпляра сущности, являющегося текущим значением компонента. 

В классе `OpenAction` определены следующие специфические методы:

* `setEditScreenOpenType()` - позволяет задать режим открытия экрана редактирования сущности. По умолчанию экран открывается в режиме `++THIS_TAB++`. 

* `setEditScreen()` - позволяет задать идентификатор экрана редактирования сущности. По умолчанию используется экран `++{имя_сущности}.edit++`, например `sales$Customer.edit`.

* `setEditScreenParams()` - позволяет задать параметры экрана редактирования, передаваемые в его метод `init()`.

* `afterWindowClosed()` - вызывается действием после закрытия экрана редактирования. Данный метод не имеет реализации и может быть переопределен в наследниках для реакции на это событие. 

