:sourcesdir: ../../../../source

[[sso_example]]
==== Пример настройки SSO

В данном разделе рассмотрен пример настройки <<sso,SSO>> для двух приложений: Fish и Chips. Fish будет одновременно выполнять роль Identity Provider и Service Provider, Chips будет являться Service Provider.

. Оба приложения будут запущены на localhost, поэтому создайте алиасы в файле `hosts`:
+
[source]
----
127.0.0.1    fish
127.0.0.1    chips
----

. Создайте поочередно два проекта в Studio и назначьте разные порты Tomcat.
+
|===
| Проект | HTTP port | AJP port | Shutdown port

| Fish
| 8081
| 8011
| 8051

| Chips
| 8082
| 8012
| 8052
|===

. В проекте Fish отредактируйте файл `modules/web/web/WEB-INF/web.xml` добавив следующую конфигурацию IDP:
+
[source,xml]
----
include::{sourcesdir}/security/sso_1.xml[]
----

. В проекте Fish отредактируйте файл `web-app.properties` модуля *web*, добавив следующие свойства:
+
[source,properties]
----
include::{sourcesdir}/security/sso_2.properties[]
----

. В проекте Chips отредактируйте файл `web-app.properties` модуля *web*, добавив следующие свойства:
+
[source,properties]
----
include::{sourcesdir}/security/sso_3.properties[]
----

. Запустите сервер Fish с помощью скрипта `tomcat/bin/startup.*`.

. Перейдите по адресу `++http://fish:8081/app/++` в веб-браузере. Вы будете перенаправлены на страницу логина IDP. Войдите с именем и паролем `admin` / `admin`. Создайте нового пользователя, например `u1`.

. Запустите сервер Chips с помощью скрипта `tomcat/bin/startup.*`.

. Перейдите по адресу `++http://chips:8082/app/++` в том же веб-браузере. Если вы по-прежнему аутентифицированы в приложении Fish, то вы автоматически войдете как `admin` и в приложение Chips. Создайте пользователя `u1` (пароль не важен) в приложении Chips.

. Теперь вы сможете входить как `admin` или `u1` в оба приложения через единую форму логина, и если вы аутентифицированы в одном приложении, то вход во второе будет автоматическим, минуя форму.

