:sourcesdir: ../../../source

[[proc_actions_fragment]]
=== ProcActionsFragment

The `ProcActionsFragment` is designed to work with process actions. After the fragment is initialized, the following components will be automatically displayed:

* the start process button, in case if the process is not started yet;
* the buttons for task outcomes, in case the process is started and the current user has an active task;
* the cancel process button;
* the task information panel (name and creation date).

A predicate can be assigned to each of the process actions in order to check if the action can be performed (e.g. the predicate commits an editor, and if the commit failed, the process action is not performed). The post-action listener can also be defined (e.g. the listener will close the editor and show a notification).

The `ProcActionsFragment` must be linked with the `ProcInstance`. The linking is performed during fragment initialization.

An example of fragment initialization:

[source,java]
----
include::{sourcesdir}/quickstart/ProcActionsFragmentInitialization.java[]
----

* The `initializer()` method returns an object that is used for fragment initialization.

* The `setBeforeStartProcessPredicate` method sets the predicate that will be evaluated before the process start. If the predicate returns `false` then the process start will be interrupted.

* The `setAfterStartProcessListener` method defines a listener that will be invoked after the process start action is performed.

* The `init` method has two parameters: process code and entity instance. When this method is invoked, a search for the `ProcInstance` object that is related with the entity instance and has a reference to the `ProcDefinition` with the given code is performed. If the `ProcInstance` exists then the fragment is linked to it, otherwise a new `ProcInstance` object is created.

The easiest way to initialize the `ProcActionsFragment` is to use the `standard()` initializer:

[source,java]
----
include::{sourcesdir}/quickstart/ProcActionsFragmentStandardInitialization.java[]
----

The standard initializer does the following:

* creates predicates that commit entity editor before start process and complete task actions;

* creates listeners that show notifications like "Process started" or "Task completed" and refresh the `ProcActionsFragment`.

Below is the list of methods used for customizing the fragment.

Process life cycle::
+
--
[[ProcActionsFragment_initializer]]
* `initializer()` – returns a new instance of fragment initializer.

[[ProcActionsFragment_init]]
* `init()` – tries to find the process instance by the specified process code and the entity reference. If the process instance is not found then a new one is created. Then the UI for available actions for the current user and the process instance is initialized.
--

Process configuration::
+
--
[[ProcActionsFragment_setStartProcessEnabled]]
* `setStartProcessEnabled()` – defines whether the process can be started.

[[ProcActionsFragment_setCancelProcessEnabled]]
* `setCancelProcessEnabled()` – defines whether the process can be canceled.

[[ProcActionsFragment_setCompleteTaskEnabled]]
* `setCompleteTaskEnabled()` – defines whether the task can be completed.

[[ProcActionsFragment_setClaimTaskEnabled]]
* `setClaimTaskEnabled()` – defines whether the task can be assigned to a user by himself.

[[ProcActionsFragment_setTaskInfoEnabled]]
* `setTaskInfoEnabled()` – defines whether the layout with the localized task name and its start date is enabled.

[[ProcActionsFragment_setButtonWidth]]
* `setButtonWidth()` – sets the width of the action control button. The default value is 150 px.

[[ProcActionsFragment_addActionButton]]
* `addActionButton()` – allows adding a custom button to the fragment alongside with buttons that were automatically generated.
--

Predicates::
+
--
[[ProcActionsFragment_setBeforeStartProcessPredicate]]
* `setBeforeStartProcessPredicate()` – sets the predicate that will be evaluated before the process start. If the predicate returns `false` then the process start will be interrupted.

[[ProcActionsFragment_setBeforeCompleteTaskPredicate]]
* `setBeforeCompleteTaskPredicate()` – sets the predicate that will be evaluated before the task completion. If the predicate returns `false` then the task completion will be interrupted.

[[ProcActionsFragment_setBeforeClaimTaskPredicate]]
* `setBeforeClaimTaskPredicate()` – sets the predicate that will be evaluated before the task is claimed to a user. If the predicate returns `false` then the task assignment will be interrupted.

[[ProcActionsFragment_setBeforeCancelProcessPredicate]]
* `setBeforeCancelProcessPredicate()` – sets the predicate that will be evaluated before the task cancellation. If the predicate returns `false` then the task will not be canceled.
--

Process and task listeners::
+
--
[[ProcActionsFragment_setAfterStartProcessListener]]
* `setAfterStartProcessListener()` – defines a listener that will be invoked after the process start action is performed.

[[ProcActionsFragment_setAfterCompleteTaskListener]]
* `setAfterCompleteTaskListener()` – defines a listener that will be invoked after the task complete action is performed.

[[ProcActionsFragment_setAfterClaimTaskListener]]
* `setAfterClaimTaskListener()` – defines a listener that will be invoked after the task claim action is performed.

[[ProcActionsFragment_setAfterCancelProcessListener]]
* `setAfterCancelProcessListener()` – defines a listener that will be invoked after the process cancel action is performed.
--

Variables and parameters suppliers::
+
--
[[ProcActionsFragment_setStartProcessActionProcessVariablesSupplier]]
* `setStartProcessActionProcessVariablesSupplier()` – sets the process variables suppliers. Process variable suppliers return a map of process variables that must be added to Activiti process instance on process start.

[[ProcActionsFragment_setCompleteTaskActionProcessVariablesSupplier]]
* `setCompleteTaskActionProcessVariablesSupplier()` – sets the process variables suppliers. Process variable suppliers return a map of process variables that must be added to Activiti process instance on task completion.

[[ProcActionsFragment_setStartProcessActionScreenParametersSupplier]]
* `setStartProcessActionScreenParametersSupplier()` – sets the process form screen parameters suppliers. These screen parameters suppliers return a map of screen parameters that will be passed to the process form displayed by `StartProcessAction`.

[[ProcActionsFragment_setCompleteTaskActionScreenParametersSupplier]]
* `setCompleteTaskActionScreenParametersSupplier()` – sets the process form screen parameters suppliers. These screen parameters suppliers return a map of screen parameters that will be passed to the process form displayed by `CompleteTaskAction`.
--

'''

ProcActionsFragment API::
<<ProcActionsFragment_addActionButton,addActionButton>> –
<<ProcActionsFragment_initializer,initializer>>

Initializer API::
<<ProcActionsFragment_init,init>> –
<<ProcActionsFragment_setAfterCancelProcessListener,setAfterCancelProcessListener>> –
<<ProcActionsFragment_setAfterClaimTaskListener,setAfterClaimTaskListener>> –
<<ProcActionsFragment_setAfterCompleteTaskListener,setAfterCompleteTaskListener>> –
<<ProcActionsFragment_setAfterStartProcessListener,setAfterStartProcessListener>> –
<<ProcActionsFragment_setBeforeCancelProcessPredicate,setBeforeCancelProcessPredicate>> –
<<ProcActionsFragment_setBeforeClaimTaskPredicate,setBeforeClaimTaskPredicate>> –
<<ProcActionsFragment_setBeforeCompleteTaskPredicate,setBeforeCompleteTaskPredicate>> –
<<ProcActionsFragment_setBeforeStartProcessPredicate,setBeforeStartProcessPredicate>> –
<<ProcActionsFragment_setButtonWidth,setButtonWidth>> –
<<ProcActionsFragment_setCancelProcessEnabled,setCancelProcessEnabled>> –
<<ProcActionsFragment_setClaimTaskEnabled,setClaimTaskEnabled>> –
<<ProcActionsFragment_setCompleteTaskActionProcessVariablesSupplier,setCompleteTaskActionProcessVariablesSupplier>> –
<<ProcActionsFragment_setCompleteTaskActionScreenParametersSupplier,setCompleteTaskActionScreenParametersSupplier>> –
<<ProcActionsFragment_setCompleteTaskEnabled,setCompleteTaskEnabled>> –
<<ProcActionsFragment_setStartProcessActionProcessVariablesSupplier,setStartProcessActionProcessVariablesSupplier>> –
<<ProcActionsFragment_setStartProcessActionScreenParametersSupplier,setStartProcessActionScreenParametersSupplier>> –
<<ProcActionsFragment_setStartProcessEnabled,setStartProcessEnabled>> –
<<ProcActionsFragment_setTaskInfoEnabled,setTaskInfoEnabled>>

'''

