:sourcesdir: ../../../../../source

[[timeZone]]
===== Time Zone

By default, all temporal values are displayed in the server's time zone. The server's time zone is the one returned by `TimeZone.getDefault()` method of an application <<app_tiers,block>>. This default time zone is typically obtained from the operating system but can be set explicitly by `user.timezone` Java system property. For example, to set the time zone to GMT for web client and middleware running on Tomcat under Unix, add the following line to `tomcat/bin/setenv.sh` file: 

[source, properties]
----
CATALINA_OPTS="$CATALINA_OPTS -Duser.timezone=GMT"
---- 

A user can view and edit timestamp values in a time zone different from the server's time zone. There are two ways to manage user's time zone:

* An administrator can do it in the User editor screen.

* The user can change their time zone in the *Help > Settings* window.

In both cases, the time zone settings consist of two fields: 

* Time zone name dropdown allows a user to select the time zone explicitly.

* *Auto* checkbox indicates that the time zone will be obtained from the current environment (web browser for the web client).

If both fields are empty, no time zone conversions are performed for the user. Otherwise, the platform saves time zone in the <<userSession,UserSession>> object when the user logs in and uses it for displaying and entering timestamp values. The application code can also use the value returned by `UserSession.getTimeZone()` for custom functionality.

If a time zone is in use for the current session, its short name and offset from GMT are displayed in the application main window next to the current user's name.

[TIP]
====
Time zone conversions are performed only for <<datatype,DateTimeDatatype>> entity attributes, i.e., timestamps. Attributes storing date (`DateDatatype`) and time (`TimeDatatype`) separately are not affected. You can also deny conversions for a timestamp attribute by annotating it with <<ignoreUserTimeZone,@IgnoreUserTimeZone>>.
====

