:sourcesdir: ../../../../../source

[[entity_localization]]
===== Локализация названий сущностей и атрибутов

Для отображения в UI локализованных названий сущностей и их атрибутов необходимо создать специальные пакеты сообщений в тех же Java-пакетах, что и сами сущности. Формат файлов сообщений должен быть следующим:

* Ключ названия сущности - простое имя класса (без пакета)

* Ключ названия атрибута - простое имя класса, затем через точку имя атрибута

Пример русской локализации сущности `com.abc.sales.entity.Customer` - файл `/com/abc/sales/entity/messages_ru.properties`:

[source, plain]
----
Customer=Покупатель
Customer.name=Имя
Customer.email=Email

Order=Заказ
Order.customer=Покупатель
Order.date=Дата
Order.amount=Сумма
----

Такие пакеты сообщений, как правило, используются неявно для разработчика, например, визуальными компонентами <<gui_Table,Table>> и <<gui_FieldGroup,FieldGroup>>. Кроме того, названия сущностей и атрибутов могут быть также получены следующими методами:

* программно - методами <<messageTools,MessageTools>> `getEntityCaption()`, `getPropertyCaption()`

* в XML-дескрипторе экрана - указанием ссылки на сообщение по правилам `MessageTools.loadString`: `++msg://{entity_package}/{key}++`, например,
+
[source, xml]
----
caption="msg://com.abc.sales.entity/Customer.name"
----

