:sourcesdir: ../../../../../source

[[main_message_pack]]
===== Главный пакет сообщений

Каждый стандартный <<app_tiers,блок>> приложения определяет для себя один _главный_ пакет сообщений. Для блоков клиентского уровня этот пакет содержит названия пунктов главного меню и общих элементов UI (например, названия кнопок *OK* и *Cancel*). Для всех блоков приложения, включая Middleware, главный пакет определяет форматы преобразований <<datatype,Datatype>>.

Для указания главного пакета сообщений используется свойство приложения <<cuba.mainMessagePack,cuba.mainMessagePack>>. Значением свойства может быть либо один пакет, либо список пакетов, разделенный пробелами. Например:

[source, properties]
----
cuba.mainMessagePack=com.haulmont.cuba.web com.abc.sales.web
----

В данном случае сообщения, заданные во втором пакете списка, будут перекрывать сообщения из первого пакета. Таким образом, в проекте приложения можно переопределять сообщения, заданные в пакетах <<app_components,компонентов приложения>>.

Сообщения, заданные в пакетах базовых проектов CUBA, также можно переопределять в главном пакете сообщений проекта:

[source, plain]
----
com.haulmont.cuba.gui.backgroundwork/backgroundWorkProgress.timeoutMessage = Новое сообщение об ошибке
----

