:sourcesdir: ../../../../source

[[composition_recipe]]
==== Composite Structures

CUBA platform supports two types of relationship between entities: association and composition. They are called ASSOCIATION and COMPOSITION respectively in the CUBA Studio interface. Association is a relationship between the objects that can exist separately from each other. Composition, on the other hand, is used for "master-detail" relations, when the detail instances can exist only as part of the master. A case of an airport and its terminals may be considered an example of composition: a terminal that does not belong to any airport does not make sense.

Typically, the entities belonging to a composition are edited together since it is more natural. For example, a user opens the airport editing screen and sees the list of terminals, so the user can create and edit them, but all changes both for the airport and the terminals are saved to the database together in one transaction, and only after the user confirms saving of the master entity (the airport).

include::composition_recipe/composition_impl_recipe.adoc[]

include::composition_recipe/composition_deep_recipe.adoc[]

include::composition_recipe/composition_deep3_recipe.adoc[]

include::composition_recipe/composition_oto_recipe.adoc[]

