:sourcesdir: ../../../../../source

[[exception_classes]]
===== Классы исключений

При создании собственных классов исключений следует придерживаться следующих правил:

* Если исключение является нормальной частью бизнес-логики и при его возникновении требуется предпринимать некоторые нетривиальные действия, то класс исключения следует делать декларируемым (наследником `Exception`). Обработка таких исключений производится вызывающим кодом.

* Если исключение сигнализирует об ошибочной ситуации, и реакцией на него должно быть прерывание хода выполнения и простое действие типа отображения информации об ошибке пользователю, то класс исключения следует делать недекларируемым (наследником `RuntimeException`). Обработка таких исключений производится специальными классами-обработчиками, зарегистрированными в клиентских блоках приложения.

* Если исключение выбрасывается и обрабатывается в рамках одного <<app_tiers,блока>> приложения, то класс исключения следует объявлять в соответствующем <<app_modules,модуле>>. Если же исключение выбрасывается на Middleware, а обрабатывается на клиентском уровне, то класс исключения необходимо объявлять в модуле *global*.

Платформа содержит специальный класс недекларируемого исключения `SilentException`, который можно использовать для прерывания хода выполнения без выдачи каких-либо сообщений пользователю или в лог. `SilentException` объявлен в модуле *global*, поэтому доступен как на Middleware, так и в клиентских блоках.

