:sourcesdir: ../../../../../source

[[exceptionHandlers]]
===== Обработчики исключений клиентского уровня

[WARNING]
====
Данный раздел будет обновлен перед выходом релиза 7.0
====

Необработанные исключения в <<app_tiers,блоках>> Web Client и Desktop Client, возникшие на клиентском уровне или переданные с Middleware, попадают в специальный механизм обработчиков. Этот механизм реализован в <<app_modules,модуле>> *gui* и доступен обоим клиентам.

Собственные классы обработчиков можно создавать в корневом пакете модуля *gui*, *web* или *desktop* проекта.  Обработчик должен быть <<managed_beans,управляемым бином>>, реализовывать интерфейс `GenericExceptionHandler`, в методе `handle()` которого производить обработку и возвращать `true`, либо сразу возвращать `false`, если данный обработчик не может обработать переданное ему исключение. Такое поведение позволяет организовать "цепочку ответственности" обработчиков.

Рекомендуется наследовать классы своих обработчиков от базового класса `AbstractGenericExceptionHandler`, который умеет разбирать цепочку исключений (с учетом упакованных внутри `RemoteException`) и реагировать на конкретные типы исключений. Типы исключений, для которых предназначен данный обработчик, указываются в массиве строк, передаваемом в конструкторе обработчика базовому конструктору. Каждая строка массива должна содержать одно полное имя класса обрабатываемого исключения, например: 

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_1.java[]
---- 

Если класс исключения недоступен на клиенте, следует указывать его имя строковым литералом: 

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_2.java[]
---- 

В случае использования в качестве базового класса `AbstractGenericExceptionHandler` логика обработки располагается в методе `doHandle()`, и может выглядеть следующим образом: 

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_3.java[]
---- 

Если имени класса исключения недостаточно для того, чтобы принять решение о применимости данного обработчика к исключению, следует определить метод `canHandle()`, получающий кроме прочего текст исключения. Метод должен вернуть `true`, если данный обработчик применим для исключения. Например:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_4.java[]
---- 

[[dialogs_showExceptionDialog]]
`WindowManager` предоставляет метод `showExceptionDialog()` для отображения диалогового окна с выброшенным исключением и его stacktrace. Метод принимает следующие параметры:

** `throwable` - экземпляр `Throwable`.

** `caption` - заголовок диалога. Это необязательный параметр, если он не установлен, используется заголовок по умолчанию.

** `message` - сообщение диалога. Это необязательный параметр, если он не установлен, используется сообщение по умолчанию.

Пример вызова диалога в обработчике исключения:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_5.java[]
----

Для <<localization,локализации>> сообщений об ошибках нужно переопределить ключи для соответствующего обработчика в <<main_message_pack,главном пакете сообщений>>. Ниже приведён пример ключей для `RowLevelSecurityExceptionHandler`, обрабатывающего нарушения ограничений прав доступа (<<roles,row-level security>>):

** `rowLevelSecurity.caption.User.create` - заголовок уведомления о конкретной сущности и операции,
** `rowLevelSecurity.caption.Group` -  заголовок уведомления о конкретной сущности,
** `rowLevelSecurity.entityAndOperationMessage.User.create` - тело сообщения о конкретной сущности и операции,
** `rowLevelSecurity.entityAndOperationMessage.Group` - тело сообщения о конкретной сущности.

