:sourcesdir: ../../../../../source

[[exceptionHandlers]]
===== Обработчики исключений клиентского уровня

Необработанные исключения, возникшие на клиентском уровне или переданные с Middleware, попадают в специальный механизм обработчиков блока Web Client.

Обработчик должен быть <<managed_beans,Spring-бином>>, реализовывать интерфейс `UiExceptionHandler`, в методе `handle()` которого производить обработку и возвращать `true`, либо сразу возвращать `false`, если данный обработчик не может обработать переданное ему исключение. Такое поведение позволяет организовать "цепочку ответственности" обработчиков.

Рекомендуется наследовать классы своих обработчиков от базового класса `AbstractUiExceptionHandler`, который умеет разбирать цепочку исключений (с учетом упакованных внутри `RemoteException`) и реагировать на конкретные типы исключений. Типы исключений, для которых предназначен данный обработчик, указываются в массиве строк, передаваемом в конструкторе обработчика базовому конструктору. Каждая строка массива должна содержать одно полное имя класса обрабатываемого исключения.

Предположим, имеется следующий класс исключения:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_0.java[]
----

Тогда обработчик должен иметь следующий конструктор:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_1.java[]
---- 

Если класс исключения недоступен на клиенте, следует указывать его имя строковым литералом: 

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_2.java[]
---- 

В случае использования в качестве базового класса `AbstractUiExceptionHandler` логика обработки располагается в методе `doHandle()`, и может выглядеть следующим образом:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_3.java[]
---- 

Если имени класса исключения недостаточно для того, чтобы принять решение о применимости данного обработчика к исключению, следует определить метод `canHandle()`, получающий кроме прочего текст исключения. Метод должен вернуть `true`, если данный обработчик применим для исключения. Например:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_4.java[]
---- 

[[dialogs_showExceptionDialog]]
Интерфейс `Dialogs`, доступный через параметр `UiContext` метода `doHandle()`, предоставляет специальный диалог для отображения исключений, содержащий схлопываемое поле с полным stack trace исключения. Данный диалог используется в обработчике по умолчанию, но вы можете использовать его и для конкретных исключений:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_5.java[]
----


include::exceptionHandlers/unique_constraint_violation_exceptions.adoc[]
