:sourcesdir: ../../../source

[[ide_integration]]
=== Интеграция CUBA Studio с IDE

Для интеграции с *IntelliJ IDEA* или *Eclipse* выполните следующие шаги:

. Откройте или <<qs_create_project,создайте новый>> проект в Studio.

. Перейдите в секцию *Project properties* и нажмите кнопку *Edit*. Выберите нужную *Java IDE* флажками *IntelliJ IDEA* или *Eclipse*.

. В главном меню Studio выберите пункт меню *Build → Create or update <IDE> project files*. В каталоге проекта будут созданы соответствующие файлы.

. Для интеграции с IntelliJ IDEA:

.. Запустите IntelliJ IDEA 13+ и установите плагин *CUBA Framework Integration*, доступный в репозитории плагинов: *File > Settings > Plugins > Browse Repositories*.

. Для интеграции с Eclipse:

.. Запустите Eclipse 4.3+, откройте *Help > Install New Software*, добавьте репозиторий `++http://files.cuba-platform.com/eclipse-update-site++` и установите плагин *CUBA Plugin*.

.. В Eclipse в меню *Window > Preferences* в секции *CUBA* установите флажок *Studio Integration Enabled* и нажмите на кнопку *OK*.

Обратите внимание, что в панели статуса Studio загорелась надпись *IDE: on port 48561*. Теперь при нажатии кнопок *IDE* в Studio соответствующие файлы исходных кодов будут открываться редактором IDE.


