:sourcesdir: ../../../../../source

[[transaction_params]]
===== Transaction Parameters

[[transaction_timeout]]
Transaction Timeout::
+
--
You can set a timeout in seconds for created transaction. When the timeout is exceeded, the transaction is interrupted and rolled back. Transaction timeout effectively limits the maximum duration of a database request.

When transactions are managed programmatically, the timeout is specified by passing `TransactionParams` object to the `Persistence.createTransaction()` method. For example:

[source, java]
----
include::{sourcesdir}/middleware/transactions_6.java[]
----

In case of declarative transactions management, use the `timeout` parameter of the `@Transactional` annotation:

[source, java]
----
include::{sourcesdir}/middleware/transactions_7.java[]
----

The default timeout can be defined using the <<cuba.defaultQueryTimeoutSec,cuba.defaultQueryTimeoutSec>> application property.
--

[[transaction_read_only]]
Read-only Transactions::
+
--
A transaction can be marked as read-only if it is intended only for reading data from the database. For example, all `load` methods of <<dataManager,DataManager>> use read-only transactions by default. Read-only transactions yield better performance because the platform does not execute code that handles possible entity modifications. `BeforeCommit` <<transaction_listeners,transaction listeners>> are not invoked as well.

[WARNING]
====
If the persistence context of a read-only transaction contains modified entities, `IllegalStateException` will be thrown on attempt to commit the transaction. It means that you should mark a transaction as read-only only when you are sure that it doesn't modify any entity.
====

When transactions are managed programmatically, the read-only sign is specified by passing `TransactionParams` object to the `Persistence.createTransaction()` method. For example:

[source, java]
----
include::{sourcesdir}/middleware/transactions_8.java[]
----

In case of declarative transactions management, use the `readOnly` parameter of the `@Transactional` annotation:

[source, java]
----
include::{sourcesdir}/middleware/transactions_9.java[]
----
--

