:sourcesdir: ../../../../source

[[logging_setup_desktop]]
==== Настройка логирования в десктоп-клиенте

Для десктоп клиента файл `logback.xml` должен находиться в каталоге исходников модуля *desktop* проекта. При сборке приложения он упаковывается в соответствующий JAR файл и доступен в CLASSPATH.

Для настройки логирования в своем проекте выполните следующее:

* Создайте в каталоге `src` модуля *desktop* новый файл, например, `sample-logback.xml`, и скопируйте в него содержимое файла `cuba-logback.xml`. Файл `cuba-logback.xml` находится внутри одного из JAR-файлов платформы и его легко найти поиском в IDE.

* Установите путь к файлу лога в параметре `file` аппендера `FILE`.

* Добавьте настройки для логгеров вашего проекта.

* В классе-наследнике `com.haulmont.cuba.desktop.App` вашего проекта, например `SampleApp`, переопределите метод `getDefaultLogConfig()` и верните в нем путь относительно корня CLASSPATH к вашему файлу настроек. Например:
+
[source, java]
----
include::{sourcesdir}/development/logging_2.java[]
----

* При необходимости можно переопределить местонахождение файла конфигурации на старте приложения с помощью системного свойства <<logback.configurationFile,logback.configurationFile>>.

