:sourcesdir: ../../../../source

[[logging_useful_loggers]]
==== Полезные логгеры

В данном разделе приведен список логгеров фреймворка, которые могут быть полезны при поиске проблем в приложении.

eclipselink.sql::
+
--
При установке в `DEBUG`, EclipseLink ORM логгирует все SQL-операторы и время их выполнения. Данный логгер уже определен в стандартном `logback.xml`, поэтому достаточно только изменить его уровень. Например:

[source, xml]
----
<configuration>
    ...
    <logger name="eclipselink.sql" level="DEBUG"/>
----

Пример вывода в лог:

[source, log]
----
2018-09-21 12:48:18.583 DEBUG [http-nio-8080-exec-5/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - loadList: metaClass=sec$User, view=com.haulmont.cuba.security.entity.User/user.browse, query=select u from sec$User u, max=50
2018-09-21 12:48:18.586 DEBUG [http-nio-8080-exec-5/app-core/admin] eclipselink.sql - <t 891235430, conn 1084868057> SELECT t1.ID AS a1, t1.ACTIVE AS a2, t1.CHANGE_PASSWORD_AT_LOGON AS a3, t1.CREATE_TS AS a4, t1.CREATED_BY AS a5, t1.DELETE_TS AS a6, t1.DELETED_BY AS a7, t1.EMAIL AS a8, t1.FIRST_NAME AS a9, t1.IP_MASK AS a10, t1.LANGUAGE_ AS a11, t1.LAST_NAME AS a12, t1.LOGIN AS a13, t1.LOGIN_LC AS a14, t1.MIDDLE_NAME AS a15, t1.NAME AS a16, t1.PASSWORD AS a17, t1.POSITION_ AS a18, t1.TIME_ZONE AS a19, t1.TIME_ZONE_AUTO AS a20, t1.UPDATE_TS AS a21, t1.UPDATED_BY AS a22, t1.VERSION AS a23, t1.GROUP_ID AS a24, t0.ID AS a25, t0.DELETE_TS AS a26, t0.DELETED_BY AS a27, t0.NAME AS a28, t0.VERSION AS a29 FROM SEC_USER t1 LEFT OUTER JOIN SEC_GROUP t0 ON (t0.ID = t1.GROUP_ID) WHERE (t1.DELETE_TS IS NULL) LIMIT ? OFFSET ?
	bind => [50, 0]
2018-09-21 12:48:18.587 DEBUG [http-nio-8080-exec-5/app-core/admin] eclipselink.sql - <t 891235430, conn 1084868057> [1 ms] spent
----
--

com.haulmont.cuba.core.sys.AbstractWebAppContextLoader::
+
--
При установке в `TRACE`, фреймворк логгирует <<app_properties_files,свойства приложения, заданные в файлах>> и полученные из компонентов приложения во время старта сервера, что может помочь в случае если сервер не запускается нормально.

Имейте в виду, что может понадобиться также установить порог `TRACE` для соответствующего `appender`, так как обычно они имеют более высокий порог. Например:

[source, xml]
----
<configuration>
    ...
    <appender name="File" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>TRACE</level>
        </filter>
    ...
    <logger name="com.haulmont.cuba.core.sys.AbstractWebAppContextLoader" level="TRACE"/>
----

Пример вывода в лог:

[source, log]
----
2018-09-21 12:38:59.525 TRACE [localhost-startStop-1] com.haulmont.cuba.core.sys.AbstractWebAppContextLoader - AppProperties of the 'core' block:
cuba.anonymousSessionId=9c91dbdf-3e73-428e-9088-d586da2434c5
cuba.automaticDatabaseUpdate=true
...
----
--