:sourcesdir: ../../../../../../source

[[datasource_query_params]]
====== Параметры запроса

[WARNING]
====
Это устаревший API. Новый API, доступный начиная с v.7.0, описан в разделе <<gui_data>>.
====

JPQL-запрос в источнике данных может содержать параметры нескольких видов. Вид параметра определяется по префиксу имени параметра. Префиксом является часть имени до знака "$". Интерпретация имени после "$" рассматривается ниже.

[[datasource_query_params_ds]]
* Префикс `ds`.
+
Значением параметра являются данные другого источника данных, зарегистрированного в этом же `DsContext`. Например:
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_6.xml[]
----
+
В данном случае параметром запроса источника данных `ordersDs` будет текущий экземпляр сущности, находящийся в источнике данных `customersDs`. 
+
При использовании параметров с префиксом `ds` между источниками данных автоматически создаются зависимости, приводящие к обновлению источника если меняется значение его параметра. В приведенном примере если изменяется выбранный Покупатель, автоматически обновляется список его Заказов. 
+
Обратите внимание, что в примере запроса с параметром левой частью оператора сравнения является значение идентификатора `o.customer.id`, а правой - экземпляр `Customer`, содержащийся в источнике `customersDs`. Такое сравнение допустимо, так как при выполнении запроса на *Middleware* реализация интерфейса <<query,Query>>, присваивая значения параметрам запроса, автоматически подставляет ID сущности вместо переданного экземпляра сущности.
+
В имени параметра после префикса и имени источника может быть также указан путь по графу сущностей к атрибуту, из которого нужно взять значение, например: 
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_7.xml[]
----
+
или
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_8.xml[]
----

[[datasource_query_params_custom]]
* Префикс `custom`.
+
Значение параметра будет взято из объекта `Map<String, Object>`, переданного в метод `refresh()` источника данных. Например:
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_9.xml[]
----
+
[source, java]
----
include::{sourcesdir}/gui/datasources_10.java[]
----
+
Приведение экземпляра при необходимости к его идентификатору осуществляется аналогично параметрам с префиксом `ds`. Путь по графу сущностей в имени параметра в данном случае не поддерживается. 

[[datasource_query_params_param]]
* Префикс `param`.
+
Значение параметра будет взято из объекта `Map<String, Object>`, переданного при открытии экрана в метод `init()` <<screen_controller,контроллера>>. Например:
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_15.xml[]
----
+
[source, java]
----
include::{sourcesdir}/gui/datasources_18.java[]
----
+
Приведение экземпляра при необходимости к его идентификатору осуществляется аналогично параметрам с префиксом `ds`. Поддерживается путь к атрибуту по графу сущностей в имени параметра.

[[datasource_query_params_component]]
* Префикс `component`.
+
Значением параметра будет текущее значение визуального компонента, путь к которому указан в имени параметра. Например:
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_11.xml[]
----
+
Путь к компоненту должен включать все вложенные <<frame,фреймы>>.
+
Приведение экземпляра при необходимости к его идентификатору аналогично параметрам `ds`. Поддерживается путь к атрибуту по графу сущностей в имени параметра как продолжение пути к компоненту.
+
[TIP]
====
При изменении значения компонента источник данных автоматически не обновляется.
====

[[datasource_query_params_session]]
* Префикс `session`.
+
Значением параметра будет значение атрибута <<userSession,пользовательской сессии>>, указанного в имени параметра.
+
Значение извлекается методом `UserSession.getAttribute()`, поэтому поддерживаются также предопределенные имена атрибутов сессии: 

** `userId` - ID текущего зарегистрированного или замещенного пользователя;

** `userLogin` - логин текущего зарегистрированного или замещенного пользователя в нижнем регистре.
+
Пример:
+
[source, xml]
----
include::{sourcesdir}/gui/datasources_12.xml[]
----
+
Приведение экземпляра при необходимости к его идентификатору аналогично параметрам `ds`. Путь по графу сущностей в имени параметра в данном случае не поддерживается.

[WARNING]
====
Если значение параметра не найдено по правилам, задаваемым префиксом, для данного параметра устанавливается значение `null`. То есть если, например, в запросе указан параметр с именем `++param$some_name++`, а в мэп параметров экрана нет ключа `++some_name++`, то для параметра `++param$some_name++` устанавливается значение `null`.
====

