:sourcesdir: ../../../source

[[history_output_documents]]
=== Выходные документы

Механизм предусматривает возможность сохранения выходных документов –  файлов результатов отчётов –  в {main_man_url}/file_storage.html[хранилище файлов]. Эта функция использует дисковое пространство для хранения файлов; она настраивается отдельно и по умолчанию отключена. Для ее включения определите свойство <<reporting.executionHistory.saveOutputDocument,reporting.executionHistory.saveOutputDocument>> в экране *Administration > Application Properties*:

[source, properties]
----
reporting.executionHistory.saveOutputDocument = true
----

Теперь, если в таблице просмотра истории выбрана запись, кнопка *Download document* становится доступной. При нажатии на кнопку скачивается документ, представляющий собой файл результата отчёта.

Отчёты с типом вывода <<template_chart,chart>>, <<pivotTable_output,pivot table>> и <<table_output,table>> не имеют результирующих файлов, поэтому история исполнения таких отчётов не сохраняет никаких документов.

Если вы вызываете запуск отчёта программно с помощью метода `createAndSaveReport()`, он сохраняет другую копию того же выходного документа в хранилище файлов. Эти два файла помещаются в хранилище независимо друг от друга.
