:sourcesdir: ../../../source

[[qs_indexing]]
=== Настройка вызова процесса индексирования

Для периодического вызова процесса индексирования удобно воспользоваться механизмом {main_man_url}/scheduled_tasks_cuba.html[назначенных заданий] фреймворка CUBA.

Сначала необходимо активировать весь механизм запуска задач. Добавьте в файл `app.properties` модуля *core* проекта приложения следующее свойство:

[source, properties]
----
cuba.schedulingActive = true
----

Перезапустите сервер приложения, войдите в систему пользователем `admin`, откройте экран *JMX Console*, найдите и откройте JMX-бин `app-core.cuba:type=Scheduling` и убедитесь, что атрибут *Active* имеет значение `true`.

Далее откройте экран *Administration* -> *Scheduled Tasks*, нажмите *Create* и задайте следующие значения атрибутов новой задачи:

* *Defined by*: Bean

* *Bean name*: cuba_FtsManager

* *Method name*: processQueue()

* *Singleton*: true

* *Period, sec*: 30

Сохраните задачу, выделите ее в таблице и нажмите *Activate*. С этого момента каждые 30 секунд будет вызываться процесс индексирования измененных сущностей.

[WARNING]
====
Автоматическое индексирование не затрагивает сущности, созданные до его запуска. Для постановки таких сущностей в очередь на индексацию воспользуйтесь методами `reindexAll()` или `asyncReindexAll()` JMX-бина `app-core.fts:type=FtsManager`. Подробнее см. <<reindex>>.
====

