:sourcesdir: ../../../source

[[reindex]]
=== Запуск и настройка переиндексации сущностей

Если полнотекстовый поиск был подключен в момент, когда в систему уже внесены какие-либо данные, то эти данные нужно проиндексировать. Добавление записей в очередь на индексацию осуществляется с помощью методов JMX-бина `app-core.fts:type=FtsManager`. Удобный способ вызвать метод JMX-бина – воспользоваться экраном *JMX Console* пункта меню *Администрирование*.

JMX-бин `app-core.fts:type=FtsManager` предоставляет два метода для постановки сущностей в очередь на индексацию:

* `reindexAll()` – синхронно добавляет все сущности, описанные в файле конфигурации FTS, в очередь на индексацию. При больших объемах данных этот процесс может занять длительное время, и в этом случае рекомендуется воспользоваться методом `asyncReindexAll()`.

* `asyncReindexAll()` – сущности добавляются в очередь на индексацию пакетами с помощью метода `FtsManager.reindexNextBatch()`. Размер пакета задается конфигурационным параметром <<fts.reindexBatchSize,fts.reindexBatchSize>>. Метод `FtsManager.reindexNextBatch()` должен вызываться механизмом назначенных заданий или с помощью планировщика Spring. Пока формирование очереди не завершено, индексация не производится.

