:sourcesdir: ../../../../source

[[polymer_ui]]
==== Пользовательский интерфейс на Polymer

Клиентский блок пользовательского интерфейса на Polymer предоставляет возможность быстрого создания front-end порталов с mobile-first responsive веб-интерфейсом. Он основан на библиотеке https://polymer-library.polymer-project.org[Polymer] и обеспечивает тесную интеграцию с мобильными браузерами для добавления веб-приложений на home screen устройстваи для работы оффлайн.

Polymer UI платформы CUBA имеет следующие особенности:

* Система сборки Polymer полностью интегрирована в систему сборки проекта, основанную на Gradle, так что все инструменты сборки загружаются и устанавливаются автоматически. В то же время, после создания в проекте модуля Polymer, front-end разработчики могут продолжить работу над ним, используя стандартные инструменты Polymer.

* Платформа предоставляет набор веб-компонентов для работы с middleware через стандартный {rest_man_url}[REST API]. См. описание компонентов <<cuba_web_components,ниже>>.

* CUBA Studio позволяет быстро создать клиентский модуль Polymer и генерировать код веб-компонентов приложения по модели данных проекта. Studio содержит обширный и расширяемый набор шаблонов для генерации компонентов, работающих с сущностями модели данных.

На данный момент наш подход заключается в максимальном использовании https://polymer-library.polymer-project.org/2.0/start/install-2-0[методов и инструментов], предоставляемых командой Polymer для создания https://developers.google.com/web/progressive-web-apps/[Progressive Web Apps]. Мы стараемся не отходить далеко от примеров и практик описанных в документации Polymer, чтобы снизить порог вхождения
и унифицировать процесс изучения технологии. Приложения на базе Polymer не только используют https://www.webcomponents.org/[Веб-компоненты], но и сами состоят из них.

По умолчанию, Studio генерирует пользовательский интерфейс на основе https://www.webcomponents.org/collection/PolymerElements/paper-elements[paper-elements] - набора элементов от Polymer, который построен на принципах http://www.google.com/design/spec/material-design/introduction.html[material design] от Google. Также можно использовать и другие компоненты, создав для них свои шаблоны в Studio.

Для эффективной разработки необходимо ознакомиться с основами Polymer: https://github.com/Polymer/polymer#polymer-in-1-minute. Предпочтительнее изучить тему глубже: https://polymer-library.polymer-project.org/2.0/start/. Так как Polymer строится вокруг Web стандартов, изучая его, вы, во многом, изучаете саму веб-платформу.

include::polymer/polymer_requirements.adoc[]

include::polymer/polymer_supported_browsers.adoc[]

include::polymer/polymer_in_studio.adoc[]

include::polymer/polymer_build_and_structure.adoc[]

include::polymer/cuba_web_components.adoc[]

include::polymer/polymer_styling.adoc[]

include::polymer/polymer_offline.adoc[]

include::polymer/polymer2_typescript.adoc[]

include::polymer/polymer_troubleshooting.adoc[]
