:sourcesdir: ../../../../../../source

[[gui_instance_container]]
====== InstanceContainer

Интерфейс `InstanceContainer` - корневой элемент иерархии контейнеров. Он предназначен для работы с единственным экземпляром сущности и содержит следующие методы:

--
* `setItem()` - устанавливает экземпляр сущности для контейнера.

* `getItem()` - возвращает экземпляр, содержащийся в контейнере. Если контейнер пуст, метод выбрасывает исключение. Используйте этот метод, если вы уверены, что экземпляр был установлен, тогда вам не придётся проверять полученное значение экземпляра на null.

* `getItemOrNull()` - возвращает экземпляр, содержащийся в контейнере. Если контейнер пуст, метод возвращает null. Всегда проверяйте полученное значение на null перед его использованием.

* `getEntityMetaClass()` - возвращает <<metaClass,мета-класс>> сущности, которая может храниться в этом контейнере.

* `setView()` - устанавливает представление, с которым сущности должны загружаться в этот контейнер. Обратите внимание, что контейнеры сами по себе не загружают данные, поэтому данный атрибут просто обозначает желаемое представление для <<gui_data_loaders,загрузчика>>, соединенного с данным контейнером.

* `getView()` - возвращает представление, с которым сущности должны загружаться в этот контейнер.
--

[[gui_instance_container_events]]
События InstanceContainer::
+
--
Интерфейс `InstanceContainer` позволяет регистрировать слушатели для следующих событий.

* `ItemPropertyChangeEvent` вызывается, если изменилось значение какого-либо атрибута сущности, находящейся в данный момент в контейнере. Пример подписки на событие для контейнера, объявленного в XML с идентификатором `customerDc`:
+
[source, java]
----
include::{sourcesdir}/gui/data_containers/instance_events_1.java[]
----

* `ItemChangeEvent` вызывается при смене выбранного экземпляра (или null), установленного для данного контейнера. Пример подписки на событие для контейнера, объявленного в XML с идентификатором `customerDc`:
+
[source, java]
----
include::{sourcesdir}/gui/data_containers/instance_events_2.java[]
----
--