:sourcesdir: ../../../../../../source

[[gui_keyvalue_containers]]
====== Контейнеры KeyValue

Контейнеры `KeyValueContainer` и `KeyValueCollectionContainer` предназначены для работы с сущностями типа `KeyValueEntity`. Такая сущность может содержать произвольный набор атрибутов, задаваемый во время работы приложения.

Контейнеры KeyValue содержат следующие специфичные методы:

* `addProperty()` - так как контейнер может содержать сущности с произвольным количеством атрибутов, с помощью данного метода необходимо указать, какие атрибуты ожидаются. Он принимает имя атрибута и его тип в виде <<datatype,Datatype>> или Java-класса. В последнем случае класс должен быть либо сущностью, либо классом, поддерживаемым одним из типов данных (datatypes).

* `setIdName()` - опциональный метод, позволяющий назначить один из атрибутов идентификатором сущности. Это означает, что экземпляры `KeyValueEntity`, содержащиеся в данном контейнере, будут иметь идентификаторы, получаемые из данного атрибута. В противном случае, экземпляры `KeyValueEntity` получают случайно сгенерированные UUIDs.

* `getEntityMetaClass()` возвращает динамическую реализацию интерфейса `MetaClass`, которая представляет текущую схему экземпляров `KeyValueEntity`, заданную вызовами метода `addProperty()`.

`KeyValueContainer` и `KeyValueCollectionContainer` могут быть заданы декларативно в XML-дескрипторе как `KeyValueInstance` и `KeyValueCollection`.

XML-описание контейнеров KeyValue должно содержать элемент `properties`, который задает атрибуты `KeyValueEntity`, содержащихся в источнике данных. Порядок элементов `property` должен соответствовать порядку колонок в результирующем наборе, возвращаемом запросом. Например, в следующем определении атрибут `customer` получит значение из колонки `o.customer`, а атрибут `sum` из колонки `sum(o.amount)`:

[source, xml]
----
include::{sourcesdir}/gui/data_containers/keyvalue_containers.xml[]
---- 

Контейнеры KeyValue предназначены только для чтения данных, так как сущность `KeyValueEntity` является неперсистентной и не может быть сохранена стандартным механизмом работы с БД.
