:sourcesdir: ../../../../../source

[[service_creation]]
===== Создание сервиса

Имена интерфейсов сервисов должны заканчиваться на `Service`, имена классов реализации на `ServiceBean`.

CUBA Studio позволяет легко создавать заглушки интерфейса и класса сервисов, а также автоматически регистрирует созданные сервисы в `spring.xml`. Для создания сервиса используйте команду *New > Service* в контекстном меню секции *Middleware* проектного дерева CUBA Studio.

При создании сервиса вручную без Studio необходимо выполнить следующее:

. Создать интерфейс в <<app_modules,модуле>> `global` (т.к. интерфейс сервиса должен быть доступен на всех <<app_tiers,уровнях>>) и задать в нем имя сервиса. Имя рекомендуется задавать в формате `++{имя_проекта}_{имя_интерфейса}++`. Например:
+
[source, java]
----
include::{sourcesdir}/middleware/service_1.java[]
----

. Создать класс сервиса в модуле `core` и добавить ему аннотацию `@org.springframework.stereotype.Service` с именем, заданным в интерфейсе
+
[source, java]
----
include::{sourcesdir}/middleware/service_2.java[]
----

Класс сервиса, как и класс любого другого <<managed_beans,Spring-бина>>, должен находиться внутри дерева пакетов с корнем, заданным в элементе `context:component-scan` файла <<spring.xml,spring.xml>>. В нашем случае файл `spring.xml` содержит элемент:

[source, xml]
----
include::{sourcesdir}/middleware/service_3.xml[]
----

что означает, что поиск аннотированных бинов для данного блока приложения будет происходить начиная с пакета `com.sample.sales`.

Если некоторую бизнес-логику требуется вызывать из разных сервисов либо других компонентов Middleware, ее необходимо выделить и инкапсулировать внутри соответствующего <<managed_beans,Spring-бина>>. Например:

[source, java]
----
include::{sourcesdir}/middleware/service_7_1.java[]
----

[source, java]
----
include::{sourcesdir}/middleware/service_7_2.java[]
----

[source, java]
----
include::{sourcesdir}/middleware/service_7_3.java[]
----

