:sourcesdir: ../../../../../source

[[service_import]]
===== Использование сервиса

Для того чтобы вызывать сервис, в клиентском блоке приложения для него должен быть создан соответствующий прокси-объект. Делается это путем объявления имени и интерфейса сервиса в параметрах фабрики прокси-объектов. Для блока Web Client это бин класса `WebRemoteProxyBeanCreator`, для Web Portal - `PortalRemoteProxyBeanCreator`.

Фабрика прокси-объектов конфигурируется в файле <<spring.xml,spring.xml>> соответствующего клиентского блока.

Например, чтобы в приложении *sales* вызвать с веб-клиента сервис `++sales_OrderService++`, необходимо добавить в файл `web-spring.xml` модуля *web* следующее:

[source, xml]
----
include::{sourcesdir}/middleware/service_4.xml[]
----

Все импортируемые сервисы объявляются в одном свойстве `remoteServices` в элементах `map/entry`.

[TIP]
====
CUBA Studio автоматически регистрирует сервисы во всех клиентских блоках приложения.
====

С точки зрения прикладного кода прокси-объект сервиса на клиентском уровне является обычным бином Spring и может быть получен либо инжекцией, либо с помощью класса `AppBeans`, например:

[source, java]
----
include::{sourcesdir}/middleware/service_5.java[]
----

