:sourcesdir: ../../../../source

[[userSession_log]]
==== User Session Log

This mechanism is designed for retrieving historical data on the users' login and logout by the system administrators. The logging mechanism is based on tracking <<userSession,user sessions>>. Each time the `UserSession` object is created, the log record is saved to the database containing the following fields:

* user session ID.

* user ID.

* <<user_substitution,substituted user>> ID.

* user's last action (login / logout / expiration / termination).

* remote IP address where login request came from.

* user session client type (web, desktop, portal).

* server ID (for example, `localhost:8080/app-core`).

* event start date.

* event end date.

* client information (session environment: OS, web browser etc).

By default, the user session logging mechanism is not activated. The simplest way to activate logging is using the *Enable Logging* button on the *Administration > User Session Log* application screen. Alternatively, you can use `cuba.UserSessionLogEnabled` application property.

If needed, you can create a report for the `sec$SessionLogEntry` entity.

