:sourcesdir: ../../../../../source

[[sending_emails_recipe]]
===== Отправка email

В данном разделе рассматривается пример использования <<email_sending,механизма>> рассылки email.

Рассмотрим следующую задачу:

--
* Имеется сущность `NewsItem` и экран ее редактирования `NewsItemEdit`.

* Сущность `NewsItem` имеет следующие атрибуты: `date`, `caption`, `content`.

* Необходимо отсылать электронные письма каждый раз, когда через экран `NewsItemEdit` создается новый экземпляр сущности. Email должен содержать `NewsItem.caption` в качестве темы письма, тело письма должно формироваться на основе шаблона, включающего `NewsItem.content`.
--

. Добавьте следующий код в `NewsItemEdit.java`:
+
--
[source, java]
----
include::{sourcesdir}/features/email/sending_emails_1.java[]
----

<1> - флаг, указывающий, что в этом редакторе был создан новый экземпляр сущности `NewsItem`.
<2> - этот метод вызывается при инициализации нового экземпляра сущности.
<3> - этот метод вызывается после коммита в data context.
<4> - если новый экземпляр был сохранен в базе данных, попросить пользователя об отправке сообщения по электронной почте.
<5> - помещает электронное письмо в очередь для асинхронной отправки.
<6> - получатели.
<7> - тема.
<8> - адрес отправителя берется из свойства приложения <<cuba.email.fromAddress,cuba.email.fromAddress>>.
<9> - путь до шаблона.
<10> - параметры шаблона.

Как видно, метод `sendByEmail()` вызывает сервис `EmailService` и передает ему экземпляр `EmailInfo`, описывающий сообщение. Тело сообщений будет создаваться на основе шаблона `news_item.txt`.
--

. Создайте шаблон тела письма в файле `news_item.txt` в пакете `com.company.demo.templates` модуля *core*:
+
--
[source, plain]
----
include::{sourcesdir}/features/email/sending_emails_2.txt[]
----

Это шаблон link:http://freemarker.incubator.apache.org[Freemarker], который использует параметры, переданные в `EmailInfo` (в данном случае единственный параметр `newsItem`).
--

. Запустите приложение, откройте браузер сущности `NewsItem` и нажмите *Create*. Откроется экран редактирования сущности. Заполните поля и нажмите *OK*. Появится диалог подтверждения с вопросом об отсылке email. Нажмите *Yes*.

. Перейдите в экран *Administration > Email History* вашего приложения. Вы увидите две записи (по числу получателей) со статусом `Queue`. Он означает, что сообщения находятся в очереди и еще не отосланы.

. Для обработки очереди необходимо создать <<scheduled_tasks_cuba,назначенное задание>>. Перейдите в экран *Administration > Scheduled Tasks* вашего приложения. Создайте новую задачу и установите ей следующие параметры:
+
--
* *Bean Name* - `cuba_Emailer`
* *Method Name* - `processQueuedEmails()`
* *Singleton* - да (этот параметр важен только при эксплуатации кластера серверов middleware)
* *Period, sec* - 10
--
+
Сохраните задачу и нажмите на ней *Activate*.
+
Если вы ранее не настраивали выполнение назначенных заданий для данного приложения ранее, то на данном этапе ничего не произойдет - новая задача не начнет выполняться, пока вы не запустите весь механизм назначенных заданий.

. Откройте файл `modules/core/src/app.properties` и добавьте в него следующее <<cuba.schedulingActive,свойство>>:
+
[source, properties]
----
cuba.schedulingActive = true
----
+
Перезапустите сервер приложения. Механизм выполнения заданий теперь активен и вызывает обработку очереди email.

. Перейдите в экран *Administration > Email History*. Статус сообщений будет либо `Sent`, если они успешно отосланы, либо, что более вероятно, `Sending` или `Queue`, если произошла ошибка отправки. В последнем случае вы можете открыть журнал приложения в файле `build/tomcat/logs/app.log` и выяснить причину. Механизм отсылки email предпримет несколько (по умолчанию 10) попыток и в случае неудачи переведет сообщения в статус `Not sent`.

. Наиболее очевидной причиной ошибки отправки является то, что вы не настроили <<email_sending_properties,параметры>> SMTP-сервера. Эти параметры могут быть заданы в базе данных с помощью  JMX бина `app-core.cuba:type=Emailer` или в свойствах приложения блока middleware. Рассмотрим второй способ. Откройте файл `modules/core/src/app.properties` и добавьте в него требуемые <<email_sending_properties,параметры>>:
+
[source, properties]
----
include::{sourcesdir}/features/email/sending_emails_3.properties[]
----
+
Перезапустите сервер приложения. Перейдите в экран *Administration > JMX Console*, найдите JMX бин `Emailer` и попробуйте послать самому себе тестовое сообщение с помощью операции `sendTestEmail()`.

. Теперь механизм отсылки email настроен корректно, однако он не будет отсылать сообщения, уже переведенные в статус `Not sent`. Поэтому необходимо создать новый экземпляр `NewsItem` через экран редактирования. Сделайте это и понаблюдайте, как статус новых сообщений в экране *Email History* изменится на `Sent`.

