:sourcesdir: ../../../../../../source

[[screen_lookup]]
====== Экран выбора

[WARNING]
====
Это устаревший API. Новый API, доступный начиная с v.7.0, описан в разделе <<screen_controllers>>.
====

Экран выбора (lookup) предназначен для выбора и возврата экземпляров и списков сущностей. Стандартное действие <<lookupAction,LookupAction>> в таких визуальных компонентах, как <<gui_PickerField,PickerField>> и <<gui_LookupPickerField,LookupPickerField>>, вызывает экраны выбора для поиска связанных сущностей.

При вызове экрана выбора методом `openLookup()` отображается панель с кнопками для выбора. Когда пользователь выбирает один или несколько экземпляров, экран вызывает переданный ему обработчик, тем самым возвращая вызывающему коду результаты выбора. При вызове методом `openWindow()` или, например, из главного меню, панель с кнопками выбора не отображается, что превращает экран выбора в <<screen_simple,простой экран>>.

Контроллер экрана выбора должен быть унаследован от класса <<abstractLookup,AbstractLookup>>. В XML экрана в атрибуте `lookupComponent` должен быть указан компонент (например, <<gui_Table,Table>>), из которого будет взят экземпляр сущности при выборе.

[TIP]
====
Экран выбора для сущности можно создать в Studio с помощью шаблонов *Entity browser* или *Entity combined screen*.
====

По умолчанию, действие <<lookupAction,LookupAction>> использует экран, зарегистрированный в файле <<screens.xml,screens.xml>> с идентификатором вида `{имя_сущности}.lookup` или `{имя_сущности}.browse`, например, `sales$Customer.lookup`. Поэтому при использовании вышеупомянутых компонентов убедитесь, что такой экран создан. Studio регистрирует browse-экраны с идентификаторами вида `{имя_сущности}.browse`, поэтому они автоматически вызываются в качестве экранов выбора.

[[screen_lookup_customization]]
Настройка вида и поведения экрана выбора::
+
--
* Для того, чтобы заменить панель выбора (кнопки *Select* и *Cancel*) для всех экранов выбора в проекте, создайте фрейм и зарегистрируйте его с идентификатором `lookupWindowActions`. Стандартный фрейм расположен в файле `/com/haulmont/cuba/gui/lookup-window.actions.xml`. Новый фрейм должен содержать кнопку, связанную с действием `lookupSelectAction` (которое автоматически добавляется в экран, когда он открывается как экран выбора).

* Чтобы заменить панель выбора в некотором экране, создайте в нем кнопку, связанную с действием `lookupSelectAction`. В этом случае стандартный фрейм не будет показан. Например:
+
[source, xml]
----
include::{sourcesdir}/gui/screen_lookup_1.xml[]
----

* Чтобы заменить стандартное действие выбора своим, просто добавьте его в контроллере:
+
[source, java]
----
include::{sourcesdir}/gui/screen_lookup_2.java[]
----
+
В качестве базового класса используйте `com.haulmont.cuba.gui.components.SelectAction`, переопределив требуемые методы.
--

