:sourcesdir: ../../../../../../source

[[screen_edit]]
====== Экран редактирования

[WARNING]
====
Это устаревший API. Новый API, доступный начиная с v.7.0, описан в разделе <<screen_controllers>>.
====

Экран редактирования предназначен для отображения и редактирования экземпляра сущности. Поддерживает функциональность установки редактируемого экземпляра и <<gui_Action,действия>> по коммиту изменений в базу данных. Экран редактирования должен вызываться методом `openEditor()` с передачей экземпляра сущности.

Стандартные действия <<createAction,CreateAction>> и <<editAction,EditAction>> открывают экран, зарегистрированный в файле <<screens.xml,screens.xml>> с идентификатором вида `{имя_сущности}.edit`, например, `sales$Customer.edit`.

Контроллер экрана редактирования должен быть унаследован от класса <<abstractEditor,AbstractEditor>>.

[TIP]
====
Экран редактирования для сущности можно создать в Studio с помощью шаблона *Entity editor*.
====

В XML экрана в атрибуте `datasource` указывается источник данных, в который проставляется редактируемый экземпляр сущности. Для отображения действий, выполняющих коммит или отмену изменений, в XML можно использовать следующие стандартные фреймы с кнопками:

* `editWindowActions` (файл `com/haulmont/cuba/gui/edit-window.actions.xml`) - содержит кнопки *OK* и *Cancel*

* `extendedEditWindowActions` (файл `com/haulmont/cuba/gui/extended-edit-window.actions.xml`) - содержит кнопки *OK & Close*, *OK* и *Cancel*

В экране редактирования неявно создаются следующие действия:

* `windowCommitAndClose` (соответствует константе `++Window.Editor.WINDOW_COMMIT_AND_CLOSE++`) - действие, выполняющее коммит изменений в базу данных и закрывающее экран. Создается при наличии в экране визуального компонента с идентификатором `windowCommitAndClose`, в частности, при использовании вышеописанного стандартного фрейма `extendedEditWindowActions` отображается кнопкой *OK & Close*.

* `windowCommit` (соответствует константе `++Window.Editor.WINDOW_COMMIT++`) - действие, выполняющее коммит изменений в базу данных. При отсутствии действия `windowCommitAndClose` после коммита закрывает экран. Создается всегда, и при наличии в экране вышеописанных стандартных фреймов отображается кнопкой *OK*.

* `windowClose` (соответствует константе `++Window.Editor.WINDOW_CLOSE++`) - действие, закрывающее экран без коммита изменений. Создается всегда, и при наличии в экране вышеописанных стандартных фреймов отображается кнопкой *Cancel*.

Таким образом, если в экран добавлен фрейм `editWindowActions`, то кнопка *OK* коммитит изменения и закрывает экран, а кнопка *Cancel* - закрывает без коммита. Если же добавлен фрейм `extendedEditWindowActions`, то кнопка *OK* только коммитит изменения, оставляя экран открытым, кнопка *OK & Close* коммитит и закрывает экран, кнопка *Cancel* - закрывает без коммита.

Вместо стандартных фреймов для отображения действий можно использовать произвольные компоненты, например, <<gui_LinkButton,LinkButton>>.

