:sourcesdir: ../../../../source

[[recipes__conventions__private_methods]]
==== Private Methods and Properties

Any Polymer component can expose an API consisting of a number of methods and properties.
These component members can be called public.
But there are also properties and methods that are supposed to be used only by the component itself.
We can call these members private.

It's a good practice to prefix private methods and properties with underscore.

See an example below.

*Disco lights application*

[subs="none"]
++++

<link rel="import" href="html/src/recipes/convention/access-control/disc-jockey.html">

<div class="polymer-demo-container">
    <disc-jockey></disc-jockey>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/convention/access-control/disc-jockey.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <disc-jockey></disc-jockey>
</body>
</html>
----

.src/recipes/convention/access-control/disc-jockey.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/access-control/disc-jockey.html[]
----

.src/recipes/convention/access-control/disco-lights.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/access-control/disco-lights.html[]
----

[TIP]
====
The `_currentColor` property is made private, but for a component which is designed to be reusable across many projects this property could be public. Another option would be creating an event with the information about currently selected color.
====

By adopting this convention we achieve at least the following goals:

* We explicitly declare what element members can be used.

* We make an API more clear and obvious.

* During refactoring, we clearly see names of properties and methods that shouldn't be changed.

