:sourcesdir: ../../../../../source

[[notifications]]
===== Notifications

Notifications can be invoked using `showNotification()` method of the `Frame` interface. This interface is implemented by <<screen_controller,screen controller>>, so this method can be invoked directly from the controller code.

`showNotification()` method takes the following parameters:

* `caption` - notification text. In case of HTML-type (see below), you can format message text using HTML-tags. When using HTML, don't forget to escape data to prevent code injection in the web-client. You can use `\n` characters for line breaks in non-HTML messages.

* `description` – an optional description displayed under the caption. You can also use `\n` character or HTML-formatting.

* `type` – notification type. Possible values:

** `TRAY`, `++TRAY_HTML++` - a notification is displayed in the bottom right corner of the application and disappears automatically.

** `HUMANIZED`, `++HUMANIZED_HTML++` – a standard notification displayed in the center of the screen, disappears automatically.

** `WARNING`, `++WARNING_HTML++` – a warning. Disappears when clicked.

** `ERROR`, `++ERROR_HTML++` – a notification about an error. Disappears when clicked.

Examples of invoking a notification: 

[source, java]
----
include::{sourcesdir}/gui/notifications_1.java[]
---- 

