:sourcesdir: ../../../source

[[qs_project_creation]]
=== Создание проекта
. Создайте новый проект в CUBA Studio, как это описано в разделе {studio_man_url}/create_project.html[Создание нового проекта] в {studio_man_url}/index.html[Руководстве пользователя CUBA Studio]:

* Project name: `bpm-demo`
* Project namespace: `demo`
* Root package: `com.company.bpmdemo`

[start=2]
. Откройте редактор свойств проекта в CUBA Studio: главное меню *CUBA > Project Properties*. В списке *App components* добавьте элемент *bpm*. Когда Studio предложит пересоздать скрипты Gradle, согласитесь.

. Соберите проект. Выберите пункт главного меню *CUBA > Build Tasks > Assemble*. На этом этапе будут загружены необходимые библиотеки, и в подкаталогах build {main_man_url}/app_modules.html[модулей] приложения будут собраны {main_man_url}/glossary.html#artifact[артефакты] проекта.

. Создайте базу данных на локальном сервере *HyperSQL*. Выберите пункт меню *CUBA > Create database*. Имя БД по умолчанию совпадает с пространством имен проекта.

. Выберите пункт меню *CUBA > Build Tasks > Deploy*. В подкаталоге `deploy` проекта будет установлен сервер *Tomcat* с собранным приложением.

. Выберите пункт меню *CUBA > Start application server*. Ссылка на локальный сервер в секции *Runs at…​* позволит перейти к приложению непосредственно из Studio.

Логин и пароль пользователя − `admin` / `admin`.

Запущенное приложение содержит два главных пункта меню (*Administration* и *Help*), функциональность подсистемы {main_man_url}/security_subsystem.html[безопасности] и администрирования системы.

