:sourcesdir: ../../../../../source

[[gui_api]]
===== API of Components

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Common::
+
--
[[gui_api_unwrap]]
* `unwrap()` - returns client-specific component instance (Vaadin or Swing component). Can be used in client module to simplify invocation of underlying API, see <<webComponentsHelper>> section.
+
[source, java]
----
com.vaadin.ui.TextField vTextField = textField.unwrap(com.vaadin.ui.TextField.class);
----

* `unwrapComposition()` - returns the outmost external container of client-specific component instance. Can be used in client module to simplify invocation of underlying API.

Available for all components.
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.Buffered.html[Component.Buffered]::
+
--
[[gui_api_commit]]
* `commit()` - updates all changes made since the previous commit to the data source.

[[gui_api_discard]]
* `discard()` - discards all changes since last commit. The object updates its value from the data source.

[[gui_api_isModified]]
* `isModified()` - returns `true` if the object value has been modified since it was last updated from the data source.

[source, java]
----
if (textArea.isModified()) {
    textArea.commit();
}
----

Available for components:

<<gui_CheckBox,CheckBox>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_PickerField,PickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.Collapsable.html[Component.Collapsable]::
+
--
[[gui_api_expanded]]
* `addExpandedStateChangeListener()` - adds the listener implementing the `ExpandedStateChangeListener` interface to intercept the component's expanded state change events.
+
[source, java]
----
groupBox.addExpandedStateChangeListener(e ->
        showNotification("Expanded: " + groupBox.isExpanded()));
----
Available for components:

<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.Container.html[Component.Container]::
+
--
[[gui_api_add]]
* `add()` - adds child component to the container.

[[gui_api_remove]]
* `remove()` - removes the child component from the container.

[[gui_api_removeAll]]
* `removeAll()` - removes all children components from te container.

[[gui_api_getOwnComponent]]
* `getOwnComponent()` - returns the component directly owned by this container.

[[gui_api_getComponent]]
* `getComponent()` - returns the component belonging to the whole components tree below this container.

[[gui_api_getComponentNN]]
* `getComponentNN()` - returns the component belonging to the whole components tree below this container. Throws an exception if not found.

[[gui_api_getOwnComponents]]
* `getOwnComponents()` - returns all components directly owned by this container.

[[gui_api_getComponents]]
* `getComponents()` - returns all components belonging to the whole components tree below this container.

Available for components:

<<gui_Accordion,Accordion>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_HtmlBoxLayout,HtmlBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_TabSheet,TabSheet>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.OrderedContainer.html[Component.OrderedContainer]::
+
--
[[gui_api_indexOf]]
* `indexOf()` - returns the index of a given component in an ordered container.

Available for components:

<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_Frame,Frame>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.HasContextHelp.html[Component.HasContextHelp]::
+
--
[[gui_api_contextHelp]]
* `setContextHelpIconClickHandler()` - sets a context help icon click handler. Click handler has priority over <<gui_attr_contextHelpText,context help text>>, i.e. no tooltip with context help text will be shown if the click handler is set.

[source, java]
----
textArea.setContextHelpIconClickHandler(event ->
        showMessageDialog("Title", "Body message",
                MessageType.CONFIRMATION_HTML
                        .modal(false)));
----

Available for components:

<<gui_CheckBox,CheckBox>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.HasSettings.html[Component.HasSettings]::
+
--
[[gui_api_settings]]
* `applySettings()` - restores the last user settings for this component.

* `saveSettings()` - saves current user settings for this component.

Available for components:

<<gui_DataGrid,DataGrid>> -
<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_Table,Table>> -
<<gui_TextArea,TextArea>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.HasValue.html[Component.HasValue]::
+
--
[[gui_api_addValueChangeListener]]
* `addValueChangeListener()` - adds the listener implementing the `ValueChangeListener` interface to intercept the component's value changes. If the component is bound to a datasource, in terms of the screen lifecycle, it is often preferable to use a <<datasource_listeners,datasource listener>> instead.
+
[source, java]
----
textField.addValueChangeListener(e ->
        showNotification("Before: " + e.getPrevValue() + ". After: " + e.getValue()));
----

Available for components:

<<gui_CheckBox,CheckBox>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_Label,Label>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_ProgressBar,ProgressBar>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.LayoutClickNotifier.html[Component.LayoutClickNotifier]::
+
--
[[gui_api_addLayoutClickListener]]
* `addLayoutClickListener()` - adds the listener implementing the `LayoutClickListener` interface to intercept the clicks on the component area.
+
[source, java]
----
vbox.addLayoutClickListener(event ->
                showNotification("Clicked"));
----

Available for components:

<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.Margin.html[Component.Margin]::
+
--
[[gui_api_margin]]
* `setMargin()` - sets the margins for the component.
+
** Sets margins on all sides of the component:
+
[source, java]
----
vbox.setMargin(true);
----
+
** Sets margins only on the top and the bottom of the component:
+
[source, java]
----
vbox.setMargin(true, false, true, false);
----
+
** Creates new instance of `MarginInfo` configuration class:
+
[source, java]
----
vbox.setMargin(new MarginInfo(true, false, false, true));
----

* `getMargin()` - returns margin configuration as an instance of `MarginInfo` class.

<<gui_BoxLayout,BoxLayout>> -
<<gui_Filter,Filter>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>>
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.OuterMargin.html[Component.OuterMargin]::
+
--
[[gui_api_outerMargin]]
* `setOuterMargin()` - sets the outer margins outside the border of the component.
+
** Sets outer margins on all sides of the component:
+
[source, java]
----
groupBox.setOuterMargin(true);
----
+
** Sets outer margins only on the top and the bottom of the component:
+
[source, java]
----
groupBox.setOuterMargin(true, false, true, false);
----
+
** Creates new instance of `MarginInfo` configuration class:
+
[source, java]
----
groupBox.setOuterMargin(new MarginInfo(true, false, false, true));
----

* `getOuterMargin()` - returns outer margin configuration as an instance of `MarginInfo` class.

Available for component:

<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.ShortcutNotifier.html[Component.ShortcutNotifier]::
+
--
[[gui_api_shortcut]]
* `addShortcutAction()` - adds an action which is triggered when the user presses a given key combination.
+
[source, java]
----
include::{sourcesdir}/gui_vcl/cssLayout.java[]
----

Available for components:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Component.Spacing.html[Component.Spacing]::
+
--
[[gui_api_spacing]]
* `setSpacing()` - adds space between the component and its child components.
+
[source, java]
----
vbox.setSpacing(true);
----

Available for components:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>>
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

