:sourcesdir: ../../../../../source

[[gui_api]]
===== API of Components

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Component.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Common::
+
--
[[gui_api_unwrap]]
* `unwrap()` - returns client-specific component instance (Vaadin or Swing component). Can be used in client module to simplify invocation of underlying API, see <<webComponentsHelper>> section.
+
[source, java]
----
com.vaadin.ui.TextField vTextField = textField.unwrap(com.vaadin.ui.TextField.class);
----

* `unwrapComposition()` - returns the outmost external container of client-specific component instance. Can be used in client module to simplify invocation of underlying API.

Available for all components.
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Buffered.html[Buffered]::
+
--
[[gui_api_commit]]
* `commit()` - updates all changes made since the previous commit to the data source.

[[gui_api_discard]]
* `discard()` - discards all changes since last commit. The object updates its value from the data source.

[[gui_api_isModified]]
* `isModified()` - returns `true` if the object value has been modified since it was last updated from the data source.

[source, java]
----
if (textArea.isModified()) {
    textArea.commit();
}
----

Available for components:

<<gui_CheckBox,CheckBox>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Collapsable.html[Collapsable]::
+
--
[[gui_api_expanded]]
* `addExpandedStateChangeListener()` - adds the listener implementing the `ExpandedStateChangeListener` interface to intercept the component's expanded state change events.
+
[source, java]
----
@Subscribe("groupBox")
protected void onGroupBoxExpandedStateChange(Collapsable.ExpandedStateChangeEvent event) {
    notifications.create()
            .withCaption("Expanded: " + groupBox.isExpanded())
            .show();
}
----
Available for components:

<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/ComponentContainer.html[ComponentContainer]::
+
--
[[gui_api_add]]
* `add()` - adds child component to the container.

[[gui_api_remove]]
* `remove()` - removes the child component from the container.

[[gui_api_removeAll]]
* `removeAll()` - removes all children components from te container.

[[gui_api_getOwnComponent]]
* `getOwnComponent()` - returns the component directly owned by this container.

[[gui_api_getComponent]]
* `getComponent()` - returns the component belonging to the whole components tree below this container.

[[gui_api_getComponentNN]]
* `getComponentNN()` - returns the component belonging to the whole components tree below this container. Throws an exception if not found.

[[gui_api_getOwnComponents]]
* `getOwnComponents()` - returns all components directly owned by this container.

[[gui_api_getComponents]]
* `getComponents()` - returns all components belonging to the whole components tree below this container.

Available for components:

<<gui_Accordion,Accordion>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_FieldGroup,FieldGroup>> -
<<gui_Form,Form>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_HtmlBoxLayout,HtmlBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_TabSheet,TabSheet>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/OrderedContainer.html[OrderedContainer]::
+
--
[[gui_api_indexOf]]
* `indexOf()` - returns the index of a given component in an ordered container.

Available for components:

<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_Frame,Frame>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasContextHelp.html[HasContextHelp]::
+
--
[[gui_api_contextHelp]]
* `setContextHelpText()` - sets context help text. If set, then a special icon will be added for a field, see <<gui_attr_contextHelpText,contextHelpText>>.

* `setContextHelpTextHtmlEnabled()` - defines if context help text should be rendered as HTML, see <<gui_attr_contextHelpTextHtmlEnabled,contextHelpTextHtmlEnabled>>.

* `setContextHelpIconClickHandler()` - sets a context help icon click handler. Click handler has priority over <<gui_attr_contextHelpText,context help text>>, i.e. no tooltip with context help text will be shown if the click handler is set.

[source, java]
----
textArea.setContextHelpIconClickHandler(contextHelpIconClickEvent ->
        dialogs.createMessageDialog()
                .withCaption("Title")
                .withMessage("Message body")
                .withType(Dialogs.MessageType.CONFIRMATION)
                .show()
);
----

Available for almost all components:

<<gui_Accordion,Accordion>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_BrowserFrame,BrowserFrame>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_Calendar,Calendar>> -
<<gui_CheckBox,CheckBox>> -
<<gui_CheckBoxGroup,CheckBoxGroup>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CssLayout,CssLayout>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DataGrid,DataGrid>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_Embedded,Embedded>> -
<<gui_FieldGroup,FieldGroup>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_Filter,Filter>> -
<<gui_Form,Form>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_GroupTable,GroupTable>> -
<<gui_HtmlBoxLayout,HtmlBoxLayout>> -
<<gui_Image,Image>> -
<<jsComponent,JavaScriptComponent>> -
<<gui_Label,Label>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_PopupView,PopupView>> -
<<gui_ProgressBar,ProgressBar>> -
<<gui_RadioButtonGroup,RadioButtonGroup>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_SuggestionField,SuggestionField>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_Table,Table>> -
<<gui_TabSheet,TabSheet>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_Tree,Tree>> -
<<gui_TreeDataGrid,TreeDataGrid>> -
<<gui_TreeTable,TreeTable>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasSettings.html[HasSettings]::
+
--
[[gui_api_settings]]
* `applySettings()` - restores the last user settings for this component.

* `saveSettings()` - saves current user settings for this component.

Available for components:

<<gui_DataGrid,DataGrid>> -
<<gui_Filter,Filter>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_SplitPanel,SplitPanel>> -
<<gui_Table,Table>> -
<<gui_TextArea,TextArea>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasUserOriginated.html[HasUserOriginated]::
+
--
[[gui_api_UserOriginated]]
* `isUserOriginated()` - provides information of the event origin. Returns `true` if this event was triggered by user interaction, on the client side, or `false` if it was triggered programmatically, on the server side.
+
Usage example:
+
[source, java]
----
@Subscribe("customersTable")
protected void onCustomersTableSelection(Table.SelectionEvent<Customer> event) {
    if (event.isUserOriginated())
        notifications.create()
                .withCaption("You selected " + event.getSelected().size() + " customers")
                .show();
}
----

The `isUserOriginated()` method is available for the following events:

* `CollapseEvent` in <<gui_TreeDataGrid,TreeDataGrid>>,
* `ColumnCollapsingChangeEvent` in <<gui_DataGrid,DataGrid>>,
* `ColumnReorderEvent` in <<gui_DataGrid,DataGrid>>,
* `ColumnResizeEvent` in <<gui_DataGrid,DataGrid>>,
* `ExpandedStateChangeEvent` in <<gui_Filter,Filter>> and <<gui_GroupBoxLayout,GroupBoxLayout>> (see <<gui_api_expanded,Collapsable>>),
* `ExpandEvent` in <<gui_TreeDataGrid,TreeDataGrid>>,
* `SelectedTabChangeEvent` in <<gui_TabSheet,TabSheet>>,
* `SelectionEvent` in <<gui_DataGrid,DataGrid>>,
* `SelectionEvent` in <<gui_Table,Table>>,
* `SortEvent` in <<gui_DataGrid,DataGrid>>,
* `SplitPositionChangeEvent` in <<gui_SplitPanel,SplitPanel>>,
* `ValueChangeEvent` of the components implementing `HasValue` interface (see <<gui_api_addValueChangeListener,ValueChangeListener>>).
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasValue.html[HasValue]::
+
--
[[gui_api_addValueChangeListener]]
* `addValueChangeListener()` - adds the listener implementing the `ValueChangeListener` interface to intercept the component's value changes.
+
[source, java]
----
@Inject
private TextField<String> textField;
@Inject
private Notifications notifications;

@Subscribe
protected void onInit(InitEvent event) {
    textField.addValueChangeListener(stringValueChangeEvent ->
            notifications.create()
                    .withCaption("Before: " + stringValueChangeEvent.getPrevValue() +
                            ". After: " + stringValueChangeEvent.getValue())
                    .show());
}
----
+
For the same purpose, you can subscribe to a dedicated event of a component, for example:
+
[source, java]
----
@Subscribe("textField")
protected void onTextFieldValueChange(HasValue.ValueChangeEvent<String> event) {
    notifications.create()
            .withCaption("Before: " + event.getPrevValue() +
                    ". After: " + event.getValue())
            .show();
}
----

See also <<gui_api_UserOriginated,UserOriginated>>.

Available for components:

<<gui_CheckBox,CheckBox>> -
<<gui_CheckBoxGroup,CheckBoxGroup>> -
<<gui_ColorPicker,ColorPicker>> -
<<gui_CurrencyField,CurrencyField>> -
<<gui_DateField,DateField>> -
<<gui_DatePicker,DatePicker>> -
<<gui_FileUploadField,FileUploadField>> -
<<gui_Label,Label>> -
<<gui_LookupField,LookupField>> -
<<gui_LookupPickerField,LookupPickerField>> -
<<gui_MaskedField,MaskedField>> -
<<gui_OptionsGroup,OptionsGroup>> -
<<gui_OptionsList,OptionsList>> -
<<gui_PasswordField,PasswordField>> -
<<gui_PickerField,PickerField>> -
<<gui_ProgressBar,ProgressBar>> -
<<gui_RadioButtonGroup,RadioButtonGroup>> -
<<gui_RichTextArea,RichTextArea>> -
<<gui_SearchPickerField,SearchPickerField>> -
<<gui_SourceCodeEditor,SourceCodeEditor>> -
<<gui_SuggestionField,SuggestionField>> -
<<gui_SuggestionPickerField,SuggestionPickerField>> -
<<gui_TextArea,TextArea>> -
<<gui_TextField,TextField>> -
<<gui_TimeField,TimeField>> -
<<gui_TokenList,TokenList>> -
<<gui_TwinColumn,TwinColumn>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/LayoutClickNotifier.html[LayoutClickNotifier]::
+
--
[[gui_api_addLayoutClickListener]]
* `addLayoutClickListener()` - adds the listener implementing the `LayoutClickListener` interface to intercept the clicks on the component area.
+
[source, java]
----
vbox.addLayoutClickListener(layoutClickEvent ->
    notifications.create()
            .withCaption("Clicked")
            .show());
----
+
For the same purpose, you can subscribe to a dedicated event of a component, for example:
+
[source, java]
----
@Subscribe("vbox")
protected void onVboxLayoutClick(LayoutClickNotifier.LayoutClickEvent event) {
    notifications.create()
            .withCaption("Clicked")
            .show();
}
----

Available for components:

<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_BoxLayout,BoxLayout>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasMargin.html[HasMargin]::
+
--
[[gui_api_margin]]
* `setMargin()` - sets the margins for the component.
+
** Sets margins on all sides of the component:
+
[source, java]
----
vbox.setMargin(true);
----
+
** Sets margins only on the top and the bottom of the component:
+
[source, java]
----
vbox.setMargin(true, false, true, false);
----
+
** Creates new instance of `MarginInfo` configuration class:
+
[source, java]
----
vbox.setMargin(new MarginInfo(true, false, false, true));
----

* `getMargin()` - returns margin configuration as an instance of `MarginInfo` class.

<<gui_BoxLayout,BoxLayout>> -
<<gui_Filter,Filter>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>>
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasOuterMargin.html[HasOuterMargin]::
+
--
[[gui_api_outerMargin]]
* `setOuterMargin()` - sets the outer margins outside the border of the component.
+
** Sets outer margins on all sides of the component:
+
[source, java]
----
groupBox.setOuterMargin(true);
----
+
** Sets outer margins only on the top and the bottom of the component:
+
[source, java]
----
groupBox.setOuterMargin(true, false, true, false);
----
+
** Creates new instance of `MarginInfo` configuration class:
+
[source, java]
----
groupBox.setOuterMargin(new MarginInfo(true, false, false, true));
----

* `getOuterMargin()` - returns outer margin configuration as an instance of `MarginInfo` class.

Available for component:

<<gui_GroupBoxLayout,GroupBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/HasSpacing.html[HasSpacing]::
+
--
[[gui_api_spacing]]
* `setSpacing()` - adds space between the component and its child components.
+
[source, java]
----
vbox.setSpacing(true);
----

Available for components:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_Frame,Frame>> -
<<gui_GridLayout,GridLayout>>
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--

http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/ShortcutNotifier.html[ShortcutNotifier]::
+
--
[[gui_api_shortcut]]
* `addShortcutAction()` - adds an action which is triggered when the user presses a given key combination.
+
[source, java]
----
include::{sourcesdir}/gui_vcl/cssLayout.java[]
----

Available for components:

<<gui_BoxLayout,BoxLayout>> -
<<gui_ButtonsPanel,ButtonsPanel>> -
<<gui_CssLayout,CssLayout>> -
<<gui_GridLayout,GridLayout>> -
<<gui_GroupBoxLayout,GroupBoxLayout>> -
<<gui_ScrollBoxLayout,ScrollBoxLayout>>
--