:sourcesdir: ../../../../../source

[[pt_create_model]]
===== Создание сущности

Сначала создадим перечисления. В секции *Data Model* дерева CUBA нажмите *New → Enumeration* и создайте следующие перечисления:

* `Sex` со значениями: `MALE`, `FEMALE`
* `Smoker` со значениями: `YES`, `NO`
* `Day` со значениями: `SUN`, `MON`, `TUE`, `WED`, `THU`, `FRI`, `SAT`
* `Time` со значениями: `DINNER`, `LUNCH`

Создадим класс сущности `Tip`.

1. В секции *Data Model* дерева CUBA нажмите *New → Entity*. Появится диалоговое окно *New CUBA Entity*.
2. В поле *Entity name* введите название класса сущности  – `Tip`, выберите тип `Not persistent` в поле *Entity type*, после чего нажмите кнопку *OK*. В рабочей области откроется страница дизайнера сущности.
3. Используя *Entity Designer* добавьте атрибуты:

* `row` типа `Integer`
* `totalBill` типа `Double`
* `sex` типа `Sex` 
* `smoker` типа `Smoker`
* `day` типа `Day`
* `time` типа `Time`
* `size` типа `Integer`
* `tip` типа `Double`

4. Перейдите на вкладку *Text*. Здесь отображается исходный код класса `Tip`.

На этом создание сущности `Tip` завершено.

