:sourcesdir: ../../../../source

[[main_servlets_registration]]
==== Registration of Main Servlets and Filters Programmatically

Usually, the main servlets (`CubaApplicationServlet`, `CubaDispatcherServlet`) and filters (`CubaHttpFilter`) are registered in the *Web Client* block's <<web.xml,web.xml>> configuration file:

[source, xml]
----
include::{sourcesdir}/extension/main_servlets_registration.xml[]
----

However, sometimes the main servlets and filters have to be registered programmatically.

Here is an example of a <<initializer_bean_for_servlet_registration,bean>> that initializes the main servlets and filters:

[source, java]
----
include::{sourcesdir}/extension/MainServletsInitializer.java[]
----

<1> - registration and initializing of the `CubaApplicationServlet`.
<2> - registration and initializing of the `CubaDispatcherServlet`.
<3> - registration and initializing of the `CubaHttpFilter`.
<4> - we need to register servlet first in order to initialize Atmosphere Framework.
<5> - initialize the JSR 356 explicitly.
<6> - initialize the servlet.

See https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/web/sys/singleapp/SingleAppWebContextLoader.html[SingleAppWebContextLoader] for more details.