:sourcesdir: ../../../../../source

[[gui_data_loaders]]
===== Data Loaders

TODO

////
Loaders are designed to load data from the middle tier to <<gui_data_containers,containers>>.

There are slightly different interfaces of loaders depending on containers they work with:

* `InstanceLoader` loads a single instance to `InstanceContainer` by entity id or JPQL query.

* `CollectionLoader` loads a collection of entities to `CollectionContainer` by a JPQL query. You can specify paging, sorting and other optional parameters.

* `KeyValueCollectionLoader` loads a collection of `KeyValueEntity` instances to `KeyValueCollectionContainer`. In addition to `CollectionLoader` parameters, you can specify a <<data_store,data store>> name.

In screen XML descriptors, all loaders are defined by the same `<loader>` element and the type of a loader is determined by what container it is enclosed in.

Loaders are optional because you can just load data using `DataManager` or your custom service and set directly to containers, but they simplify this process in declaratively defined screens, especially with the <<gui_Filter,Filter>> component. Usually, a collection loader obtains a JPQL query from the screen XML descriptor and query parameters from the filter component, creates `LoadContext` and invokes `DataManager` to load entities. So the typical XML descriptor looks like this:

[source, xml]
----
include::{sourcesdir}/gui/data_loaders/loader_1.xml[]
----

Attributes of the `loader` XML element allow you to define optional parameters like `cacheable`, `softDeletion`, etc.

In an entity editor screen, the loader XML element is usually empty, because the instance loader requires an entity identifier which is specified programmatically by the `StandardEditor` base class:

[source, xml]
----
include::{sourcesdir}/gui/data_loaders/loader_2.xml[]
----

Loaders can delegate actual loading to a function which can be provided using the `setLoadDelegate()` method or declaratively using the `@Install` annotation in the screen controller, for example:

[source, java]
----
include::{sourcesdir}/gui/data_loaders/loader_3.java[]
----

In the example above, the `customersDlLoadDelegate()` method will be used by the `customersDl` loader to load the list of `Customer` entities. The method accepts `LoadContext` which will be created by the loader based on its parameters: query, filter (if any), etc. In the example, the loading is done via `DataManager` which is effectively the same as the standard loader implementation, but you can use a custom service or perform any post-processing of the loaded entities.

A loader can also be created and configured programmatically, for example:

[source, java]
----
include::{sourcesdir}/gui/data_loaders/loader_4.java[]
----

When <<gui_DataContext,DataContext>> is set for a loader (which is always the case when the loader is defined in XML descriptor), all loaded entities are automatically merged into the data context.
////