:sourcesdir: ../../../../source

[[rest_api_v2_ex_create_entity]]
==== Создание экземпляра сущности

Для создания нового экземпляра сущности `sales$Order` необходимо выполнить *POST* запрос по адресу:

`\http://localhost:8080/app/rest/v2/entities/sales$Order`

OAuth-токен должен быть передан в заголовке запроса `Authorization` с типом *Bearer*.

Тело запроса должно содержать JSON объект, описывающий новый экземпляр, например:

[source, json]
----
include::{sourcesdir}/rest/rest-create-order-request.json[]
----

Ниже приведен пример POST запроса для создания нового экземпляра `Order` в https://curl.haxx.se/[cURL]:

[source, plain]
----
include::{sourcesdir}/rest/rest_api_v2_ex_create_entity.txt[]
----

В теле запроса передается коллекция позиций заказа `items` и ссылка на клиента `customer`. Рассмотрим, как будут обработаны эти атрибуты.

Сначала посмотрим на класс `Order`:

[source, java]
----
include::{sourcesdir}/features/Order.java[]
----

В сущности `Order` коллекция `items` аннотирована <<composition_annotation, @Composition>>. Методы создания и обновления сущности REST API создают новые экземпляры для всех элементов таких коллекций. Т.е. вместе с заказом (`Order`) будет создано две позиции заказа (`OrderItem`).

Ссылка `customer` не имеет аннотации @Composition, поэтому метод REST API попытается найти клиента с переданным идентификатором и проставить его в поле `customer`. Если клиент не будет найден, заказ не будет создан и метод вернет ошибку.

В случае успеха возвращается полный граф созданной сущности:

[source, json]
----
include::{sourcesdir}/rest/rest-create-order-response.json[]
----

