[[cuba_components]]
== CUBA Web Components

CUBA platform provides a set of specific web components for solving common problems that arise when working
with CUBA applications:

* <<cuba_app, cuba-app>> - initializes a CUBA application. It is required in order to use any other CUBA web component.

* <<cuba__login, cuba-login>> - a login form with material design. It allows users to log in using the
same credentials as for the standard CUBA UI.

* <<cuba__entities, cuba-entity, cuba-entities, cuba-entity-form>> - components for loading and saving entities.

* <<cuba__rest, cuba-query, cuba-service, cuba-service-form>> - components for using custom elements of CUBA REST API.

* <<cuba__file, cuba-file-field>> - a component for uploading files to the server.

In order to create an application with a custom design, our UI components (`cuba-login`, `cuba-file-field`) can be used as a template for creating your own components.

Components that work with entities (`cuba-entity`, `cuba-entities`, `cuba-entity-form`) are most convenient if an application has a relatively simple data model. For more complex cases, use custom service methods and
queries (`cuba-query`, `cuba-service`, `cuba-service-form`).

[[cuba_app]]
=== Application Setup

https://cuba-elements.github.io/cuba-elements/components/cuba-app[cuba-app] is a mandatory element for any CUBA Polymer application.
It should be defined in your application as early as possible.
`cuba-app` contains initialization logic that is required by other CUBA Polymer components.
That is, all other CUBA Polymer components won't work if `cuba-app` is absent in your code.

Below is an example of using `cuba-app` element.

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/init/empty-app.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <empty-app></empty-app>
</body>
</html>
----

.src/cuba/init/empty-app.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/init/empty-app.html[]
----

After including `cuba-app`, you can use all other CUBA Polymer components.

[[cuba_rest_js]]
=== cuba-rest-js Library

Under the hood, <<cuba_app,cuba-app>> uses the https://github.com/cuba-platform/cuba-rest-js[cuba-rest-js] library.
This library provides a convenient methods for working with CUBA REST API, such as:

* `login(login: string, password: string, options: object): Promise`.

* `loadEntities(entityName: string, optoins: object): Promise`.

* `getUserInfo(): Promise`.

* and so on.

As you can see, a lot of methods return promises. You can read about promises in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[MDN documentation].

In some cases you may want to use this API directly instead of using CUBA Polymer components.
It can be achieved by implementing the `CubaAppAwareBehavior` behavior.
This behavior provides the `app` property that has public API mentioned above.

For example, below is a simple application that shows an information about the currently authenticated user.

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/init/user-info-component.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <user-info-component></user-info-component>
</body>
</html>
----

.src/cuba/init/user-info-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/init/user-info-component.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="150"
        class="polymer-iframe-container"
        src="html/src/cuba/init/stub/user-info-component-stub.html"></iframe>
++++

Content of the `userInfo` object is described in the REST API Swagger http://files.cuba-platform.com/swagger/{revnumber}[documentation].

The way we extended `CubaAppAwareBehavior` might seem unintuitive.
The reason is that CUBA elements are currently in hybrid mode,
which means that they support both Polymer 1.0 and Polymer 2.0 syntax.
In Polymer 1.0 there were behaviors instead of mixins.
You can find more information about hybrid elements at https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements.

[[cuba__login]]
=== Login Form

All CUBA REST API methods require an OAuth token.
In order to obtain this token the client must authenticate using user's login and password.
This mechanism is described in the {manual-address}/rest_api_v2_ex_get_token.html[Developer's Manual].

The https://cuba-elements.github.io/cuba-elements/components/cuba-login/[cuba-login] web component allows you to create a login form. It's a simple UI component with 2 fields ("User Name", "Password")
and the "Login" button. It sends two events on login attempt: `cuba-login-success` and `cuba-login-error`.

Below is a working example, please use login `test` and password `test`.

[subs="none"]
++++
    <iframe
        height="200"
        class="polymer-iframe-container"
        src="html/src/cuba/login/stub/cuba-app-with-login-stub.html"></iframe>
++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/login/app-with-login.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <app-with-login></app-with-login>
</body>
</html>
----

.src/cuba/login/app-with-login.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/login/app-with-login.html[]
----

Styling::
+
--
If you check `cuba-login` source code, you can see that the component is opened for extension by using https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#custom-property-mixins[custom property mixins].

.bower_components/cuba-login/cuba-login.html
[source, html]
----
  #form {
    @apply --cuba-login-form;
  }
  #username {
    @apply --cuba-login-username-input;
  }
  #password {
    @apply --cuba-login-password-input;
  }
  #submit {
    @apply --cuba-login-submit-button;
  }
  .actions {
    display: flex;
    flex-direction: row-reverse;
    @apply --cuba-login-actions;
  }
  ...
  <form id="form">
    <div class="fields">
      <paper-input type="text" id="username" label="[[msg('User Name')]]" value="{{username}}"></paper-input>
      <paper-input type="password" id="password" label="[[msg('Password')]]" value="{{password}}"></paper-input>
    </div>
    <div class="actions">
      <paper-button id="submit" on-tap="submit">[[msg('Login')]]</paper-button>
    </div>
  </form>
----

Below you can see how these mixins can be implemented. The example is the same as above but contains the `<style/>` section.

.src/cuba/login/app-with-login-styled.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/login/app-with-login-styled.html[]
----

*Result of styling*

[subs="none"]
++++
    <iframe
        height="200"
        class="polymer-iframe-container"
        src="html/src/cuba/login/stub/cuba-app-with-login-styled-stub.html"></iframe>
++++
--

Writing your own login form::
+
--
`cuba-login`, as any other CUBA component uses `cuba-rest` component API under the hood.
It means that if you need some very custom login page, you can use the API directly. See an example below.

.src/cuba/login/app-with-login-custom.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/login/app-with-login-custom.html[]
----

*Custom login form*

[subs="none"]
++++
    <iframe
        height="150"
        class="polymer-iframe-container"
        src="html/src/cuba/login/stub/cuba-app-with-login-custom-stub.html"></iframe>
++++
--

Token expiration::
+
--
A Polymer application receives a token after authentication and then uses it with every request.

By default, a token is valid for 12 hours. After this period requests stop working and the user has to re-login. We recommend to increase the {manual-address}/app_properties_reference.html#cuba.rest.client.tokenExpirationTimeSec[token expiration time] and use the {manual-address}/rest_api_v2_persistent_token_store.html[persistent token store] to save tokens on server restart.

`cuba-app` sends the `cuba-token-expired` event that can be used to handle the expiration appropriately.
--

[[cuba__entities]]
=== Working with Entities

CUBA provides a number of components for CRUD operations with entities.

Before we proceed, it's worth to remind some basic concepts related to entities:

--
* _Entity name_ uniquely identifies the class of entity. It consists of two parts divided by "$": `{namespace$concept}`.
For example: `taxi$Driver`, `statistics$FieldDescription`, etc.
On the middleware, an entity name is specified in the `@Entity` annotation of the entity Java class.

* _Entity view_ is a descriptor of what attributes of the entity and its related entities should be loaded from the database.
For the sake of performance, a view should contain a minimal possible number of attributes.
See more in the {manual-address}/views.html[Developer's Manual].
--

Entity browse::
+
--
* The https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entities[cuba-entities] component is designed for loading a list of entities.

* The https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entity[cuba-entity] component is designed for loading one entity instance by its id.

Below is an example of how these components can be used - a book browser application.
A user sees a list of books and can select any book to see its details.

The list of books is loaded by `cuba-entities`, `cuba-entity` is used to re-load a particular book. When we show a list of books we load as little information as possible for better performance.
When a single book is selected by the user, we can afford loading a lot more: author biography, editions, even a photo of a cover page.

*Book browser*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/src/cuba/entity/stub/cuba-books-browser-stub.html"></iframe>
++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/entity/books-browser.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <books-browser></books-browser>
</body>
</html>
----

.src/cuba/entity/books-browser.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/entity/books-browser.html[]
----

In this example we have omitted a code for login simplicity.
In real applications, REST API won't work until you login or enable {manual-address}/rest_api_v2_anonymous.html[anonymous access].
--

Entity creation::
+
--
The `cuba-entity-form` component provides an ability to create new entities.
Basically, you have to provide an entity name and an entity instance you want to persist. After that, you can call the `submit` method and the entity will be saved.

*Book creator*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/src/cuba/entity/stub/cuba-book-creator-stub.html"></iframe>
++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/entity/book-creator.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <book-creator></book-creator>
</body>
</html>
----

.src/cuba/entity/book-creator.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/entity/book-creator.html[]
----
--

Entity removal::
+
--
The `cuba-entities` component has method `remove()`, which you can use to remove an entity instance.
--

Entity update::
+
--
Entity can be updated using `cuba-entity-form` component
--

Conclusion::
+
--
That was an overview of how CUBA Polymer components can be used to work with entities.
But the components provide more functionality than was described in this section. For example,
`cuba-entity` allows you to set the `debounce` parameter to avoid excessive requests to a server;
`cuba-entities` can sort entities by any field;
and so on. To learn more, check out the public API at https://cuba-elements.github.io/cuba-elements and the source code of components.
--

[[cuba__rest]]
=== Using Services and Queries

In most cases, applications are not limited to CRUD operations with entities. CUBA REST API provides special endpoints for invoking middleware {manual-address}/rest_api_v2_services_config.html[services] and running predefined {manual-address}/rest_api_v2_queries_config.html[queries]. These are places where you can put your business logic and invoke it from the front-end using the https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-service[cuba-service] and https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-query[cuba-query] components.

By default, the components automatically load data on initialization.
You can disable this behavior by assigning `false` to property `auto` and calling `load()` method programmatically.

*Usage example*

[source, html]
----
    <cuba-query id="query"
                entity-name="sec$User"
                query-name="usersByName"
                data="{{users}}">
    </cuba-query>
    ...
    <cuba-service service-name="cuba_ServerInfoService"
                  method="getReleaseNumber"
                  data="{{releaseNumber}}">
    </cuba-service>
----

https://cuba-elements.github.io/cuba-elements/components/cuba-form/#cuba-service-form[cuba-service-form] can be used instead of `cuba-service` when it's semantically more correct to use form submit
instead of information requests. However, it's not mandatory, and under the hood they use the same REST API.

[[cuba__file]]
=== Uploading Files

The https://cuba-elements.github.io/cuba-elements/components/cuba-file-field[cuba-file-field] component allows you to to upload files to the server.

The example below is a stub and doesn't upload any files, so you can safely test it.

[subs="none"]
++++
    <iframe
        height="200"
        class="polymer-iframe-container"
        src="html/src/cuba/file/stub/file-upload-app-stub.html"></iframe>
++++

*Source code:*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/cuba/file/file-upload-app.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <file-upload-app></file-upload-app>
</body>
</html>
----

.src/cuba/file/file-upload-app.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/cuba/file/file-upload-app.html[]
----