[[polymer_manual__advanced]]
=== Polymer Core Advanced

Despite the name of this section, techniques considered here are required to build almost any real web application
that consists of more than a couple of components.


[[polymer_manual__advanced__dom]]
==== Accessing DOM Elements

The simplest and the most straightforward method to access an HTML element from JS code is to use id-s. Consider an example below.

Click on the button to see what it's doing:
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/dom/colored-square-controller.html">

<div class="polymer-demo-container">
    <colored-square-controller></colored-square-controller>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/dom/colored-square-controller.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <colored-square-controller></colored-square-controller>
</body>
</html>
----

.src/polymer-advanced/dom/colored-square-controller.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square-controller.html[]
----

.src/polymer-advanced/dom/colored-square.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square.html[]
----

As you can see, Polymer has special shortcut — `this.$`, which can be used to retrieve an element by its id. In found element, you can change properties and call methods.

[TIP]
====
Please note that we used attribute `black$` instead of `black`. What's the difference?

If we used just `black`, then during the component initialization Polymer would or would not put `black` attribute in DOM on `div` based on if `black` property is true or false. And if the `black` property changed later Polymer wouldn't add/remove this attribute from the `div`. Therefore, it would be impossible to use this attribute in CSS (`.square[black]`). But when we use `black$`, Polymer automatically updates HTML attribute `black` based on changes in the `black` property.

That is if in our example we used `black` instead of `black$`, then the square would always be white, no matter how much we press the button.
====

However, the `this.$` syntax won't always work. Let's put the `colored-square` component inside an if-template.
In this case `this.$.square` won't work even if the condition is true. See more in the https://www.polymer-project.org/2.0/docs/devguide/dom-template#node-finding[official guide].

.src/polymer-advanced/dom/colored-square-controller-with-if.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square-controller-with-if.html[]
----

In such cases you can use native DOM API to find a required element: `this.shadowRoot.querySelector("selector")`. This method will search for the element dynamically.

.src/polymer-advanced/dom/colored-square-controller-with-if-fixed.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/dom/colored-square-controller-with-if-fixed.html[]
----

What we have learned so far::
+
--
* `this.$.{id}` can be used to retrieve an element by id. However, it won't work if this element is
added/removed dynamically from DOM.

* Native DOM API `this.shadowRoot.querySelector("{selector}")` can be used to find an element by CSS selector.

* We can change properties on the found element and call its methods.

* Use special syntax ("black$=") if you want to change attribute (not property). Mostly, it's required
when we want to use these attributes in our CSS.
--

[[polymer_manual__advanced__computed]]
==== Computed Properties

Sometimes you may need properties that depend on other properties. For example, you have properties `firstName`, `lastName`
and also need property `fullName` that concatenates first and last names.
Or you have a boolean property that defines if a button is enabled or disabled, and this property depends on a number of other properties.

Obviously, you shouldn't manually change a value for such synthetic properties, it should be calculated automatically. Luckily, Polymer provides so called computed properties, and below is an example of using them.

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/computed-properties/service-agreement.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <service-agreement></service-agreement>
</body>
</html>
----

.src/polymer-advanced/computed-properties/service-agreement.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/computed-properties/service-agreement.html[]
----

*Result*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/computed-properties/service-agreement.html">

<div class="polymer-demo-container">
    <service-agreement></service-agreement>
</div>

++++

In this example, users cannot submit a form until they type in their name and accept an agreement.

It's essential to specify what properties we depend on. You cannot just type `computed: "isContinueEnabled()"` and then use `this.name` and `this.agreementConfirmed` in the `isContinueEnabled` method, because then Polymer won't know what properties we depend on and it won't re-calculate a computed property when required.

What we have learned so far::
+
--
* We can use computed properties when we need some information that can be calculated based on other properties.
--

[[polymer_manual__advanced__observers]]
==== Observers

Sometimes, it is needed to listen to changes in some properties and react on them. For example, we may want
to send some notifications to a server when users enter some information.

The example below demonstrates it. Basically, users can choose a type of their company and we save this information somewhere in a database.

*Company type selector*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/observers/company-type-select.html">

<div class="polymer-demo-container">
    <company-type-select></company-type-select>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/observers/company-type-select.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <company-type-select></company-type-select>
</body>
</html>
----

.src/polymer-advanced/observers/company-type-select.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/observers/company-type-select.html[]
----

Observers can be much more complex. For example, you may want to monitor changes in several different properties.

Let's enhance our previous example by adding a contact name input.

.src/polymer-advanced/observers/company-type-select-enhanced.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/observers/company-type-select-enhanced.html[]
----

*Enhanced company type selector*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/observers/company-type-select-enhanced.html">

<div class="polymer-demo-container">
    <company-type-select-enhanced></company-type-select-enhanced>
</div>

++++

What we have learned so far::
+
--
* We can monitor changes in a single property by using an `observer` attribute. An observer function accepts 2 arguments:
an old value and a new one.

* We can monitor several properties at the same time by using observers array. But we lose information about old values in this case.
--

[[polymer_manual__advanced__lifecycle]]
==== Lifecycle Callbacks

Polymer components allow you to define code that would be called in response to certain lifecycle events.

To use this feature, implement methods with the following names:

- `constructor` - called when an element is created but before property values are set.

- `connectedCallback` - called when an element is created and properties are set.

- `disconnectedCallback` - called when an element is removed from a document.

For example, a user opens some profile page and we would like to load all required details from the server
before showing them to the user.

[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/lifecycle/profile-page.html">

<div class="polymer-demo-container">
    <profile-page></profile-page>
</div>

++++

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/lifecycle/profile-page.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <profile-page></profile-page>
</body>
</html>
----

.src/polymer-advanced/lifecycle/profile-page.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/lifecycle/profile-page.html[]
----

.src/polymer-advanced/lifecycle/personal-details-page.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/lifecycle/personal-details-page.html[]
----

.src/polymer-advanced/lifecycle/preferences-page.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/lifecycle/preferences-page.html[]
----

What we have learned so far::
+
--
* During their lifecycle, Polymer elements call a number of callback methods.
We can use these methods to invoke our initialization logic.
--

[[polymer_manual__advanced__mixins]]
==== Mixins

Inheritance in Polymer is implemented with so called *mixins*. A mixin is a set of methods, properties, observers and lifecycle callback methods that can be inherited by any Polymer component.

Each web component can use any number of mixins. Web components can use mixins' methods and properties as if they were
their own. And mixins can use web components' methods and properties.

Below is an example demonstrating how to write and use mixins. It's a spelling improvement program that offers
a user to type a word. If the user fails to spell it correctly then the input will be highlighted with red. On any typing
the highlighting will be removed. Logic for setting/removing error state in the component is implemented by a mixin called
`ValidatedElementMixin`.

*Spelling checker*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/mixins/spelling-checker.html">

<div class="polymer-demo-container">
    <spelling-checker word="Elephant"></spelling-checker>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/mixins/spelling-checker.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <spelling-checker word="Elephant"></spelling-checker>
</body>
</html>
----

.src/polymer-advanced/mixins/spelling-checker.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/mixins/spelling-checker.html[]
----

.src/polymer-advanced/mixins/input-with-validation.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/mixins/input-with-validation.html[]
----

.src/polymer-advanced/mixins/validated-element-mixin.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/mixins/validated-element-mixin.html[]
----

`input-with-validation` represents a common UI component that supports validation.
`ValidatedElementMixin` can be used with other types of elements: comboboxes, text areas, radio-buttons, etc.

[TIP]
====
Please note what we marked the `value` property in `input-with-validation.html` with the `notify` attribute.
It's a necessary detail if want to allow clients of this element to use this property with 2-way binding.
====

In this example, we used just one mixin, but it's possible to use any number of mixins by including them one into another.
For example, we could create something like that:

[source, javascript]
----
class PowerfulInput extends ElementWithDebounceMixin(SelfPersistedElementMixin(ValidatedElementMixin(Polymer.Element)))
----

[TIP]
====
Please note that prior to version 2.0, Polymer used so called *behaviors* instead of mixins. They are elements
similar to mixins with the same purpose and possibilities but using another syntax for creation and usage.
You don't need to create or use behaviors in your code but you might encounter them in third-party components.
See more details in https://www.polymer-project.org/1.0/docs/devguide/behaviors.
====

What we have learned so far::
+
--
* We can use mixins to implement some common logic and share it between components.

* Mixins can contain methods, properties, lifecycle callback methods and observers.

* After extending a mixin, a Polymer component doesn't know which properties/methods are inherited and which are not.
So, the component treats them the same.

* In order to allow some property to be used by clients in two-way binding, we have to mark it with the `notify` parameter.
--