= CUBA Platform. Polymer UI
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: highlightjs
:highlightjsdir: js/highlight-js
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.7
:version-label: Version
:revremark: Copyright (c) 2017 Haulmont (www.haulmont.com)
:!sectnums:

:manual-address: https://doc.cuba-platform.com/manual-6.7

[[preface]]
== Preface

This guide aims to give you information on how to use CUBA Polymer UI to develop front-end applications working with CUBA middleware.

It's divided into three sections:

* <<polymer_manual>>: an introduction to Polymer which contains everything that you should know to start building front-end applications on Polymer.

* <<cuba_components>>: our Polymer components that facilitate creating applications based on the CUBA platform.

* <<recipes>>: our solutions to tasks a developer has to accomplish while creating web applications. This includes: how to build a navigation block, how to implement dependency injection and so on. In this section we accumulate some tips and best practices that can be useful to draft an architecture of your front-end project.

The manual contains a lot of examples. For almost every topic we provide:

* Commented source code of web components illustrating a subject;

* `index.html` that represents the application entry point;

* A result of executing this code.

All examples can be copy-pasted into your CUBA project in order to examine them closely. The easiest way to do it is to create
a new project in Studio and create a Polymer UI module using the *Project Properties → Manage modules → Create polymer client module* command. After that, deploy the application and run the server. You will have the `deploy/tomcat/webapps/app-front` folder with your front-end application, where you can copy our examples as is and just reload a web page to see them in action.

include::polymer_manual.adoc[]

include::cuba_components.adoc[]

include::recipes.adoc[]