= CUBA Platform. Polymer UI Tutorial
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: highlightjs
:highlightjsdir: js/highlight-js
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.9
:version-label: Version
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)
:!sectnums:

:manual-address: https://doc.cuba-platform.com/manual-6.9

[[preface]]
== Preface

This tutorial will teach you how to use CUBA Polymer UI to develop front-end applications working with CUBA middleware. It's designed primarily for developers who are not familiar with the Web Components technology and Google Polymer library, but have good knowledge of HTML, JavaScript and CSS.

The tutorial is divided into three chapters:

* <<polymer_manual>>: an introduction to Polymer which contains everything that you should know to start building front-end applications using this technology.

* <<cuba_components>>: our Polymer components that facilitate creating applications based on the CUBA platform.

* <<recipes>>: a collection of our recipes to common problems a developer has to solve while creating web applications. For example: how to build a navigation block, implement dependency injection and so on.

The manual contains a lot of examples. For almost every topic we provide:

* Commented source code of web components illustrating a subject;

* `index.html` that represents the application entry point;

* A result of executing this code.

All examples can be copy-pasted into your CUBA project in order to examine them closely. The simplest way to do it is to create
a new project in CUBA Studio and then create a Polymer UI module using the *Project Properties → Manage modules → Create polymer client module* command. After that, deploy the application and run the server. You will have the `deploy/tomcat/webapps/app-front` folder with your front-end application, where you can copy our examples as is and just reload a web page to see them in action.

include::polymer_manual.adoc[]

include::cuba_components.adoc[]

include::recipes.adoc[]