= CUBA Platform. Polymer UI
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: highlightjs
:highlightjsdir: js/highlight-js
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.7
:version-label: Version
:revremark: Copyright (c) 2017 Haulmont (www.haulmont.com)
:!sectnums:

:manual-address: https://doc.cuba-platform.com/manual-6.7

[[preface]]
== Preface

This guide aims to give an overview of how CUBA Polymer UI can be used to develop front-end applications.

It's divided into 3 sections:

* <<polymer_manual,Polymer Core>>. An introduction to Polymer. It contains everything that is required to know to start building your
own Polymer applications.

* <<cuba_components,CUBA Web Components>>. Our Polymer components that facilitate creating applications based on CUBA Platform.

* <<recipes,Common problems and techniques>>. Google Polymer is a library that doesn't provide out-the-box solutions for a number
of tasks a developer has to accomplish while creating web applications. Polymer doesn't provide solutions for these tasks but we do.
This includes: how to build a navigation block, how to implement dependency injection and so on. In this section we
accumulated some tips and best practices that can be useful to draft an architecture of your front-end project.

[.lead]
Examples

The manual contains a rich number of examples. For almost every topic we provide:

* A commented source code of Web Components illustrating a subject;

* `index.html` that represents an entry point of the application;

* A result of this code.

All examples can be copy-pasted into your project in order to examine them closely. The easiest way to do it is to create
a new project in Studio and create a Polymer UI module at *Project Properties → Manage modules → Create polymer client module*.
Essentially that's it. You can copy our examples as is into your Polymer module folder (`modules/polymer-client/`).

All *.html files inside `src` folder are hot-deployed when you make any changes to them. So, you can change our examples
and see the result immediately. However, `index.html` is not hot-deployed because it's supposed that it won't be changed
after initial configuration and all changes will be made to `*-shell.html` file instead.

This limitation can be easily circumvented by passing our example code into `*-shell.html` instead of `index.html`.

If last 2 paragraphs don't make sense to you or you are new to Web Components then you can copy presented source code as is
and re-deploy an application on any change of `index.html` until you read the 1st section of this manual.

TIP: Please note, that to run our examples in your CUBA application a version of your CUBA Studio should be 6.7.0 or higher.

include::polymer_manual.adoc[]

include::cuba_components.adoc[]

include::recipes.adoc[]