[[recipes]]
== Common Tasks

From project to project, from one framework to another, we face the same set of standard problems:

* How to implement internationalization?

* How to build a navigation block?

* How to inject services into components?

* And so on.

Polymer doesn't have a goal to solve these problems for us.
It's primary intention was to provide convenient means for creating custom reusable components.
Dependency injection, navigation, etc. are beyond this task.

In this chapter, we discuss some of the common problems encountered in front-end development
and offer solutions for them. Please consider our recommendations not as ultimate truth but as one of the possible ways to handle a problem.

[[recipes__conventions]]
=== Organizing Your Code

This section contains some tips that can help you to achieve better readability of the code and
facilitate its maintenance.

[[recipes__conventions__css]]
==== Shared CSS

Polymer elements use Shadow DOM and their styles don't overlap with each other. It's a very useful feature, but sometimes
you may want to share some CSS between elements.

Let's examine an example of how to re-use CSS.

First of all we need to create an element that contains common styles we want to share.

.src/recipes/convention/css/shared-styles.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/css/shared-styles.html[]
----

So, we have declared a class and a variable with a color. Now, we can use them in other components.

.src/recipes/convention/css/blue-button.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/css/blue-button.html[]
----

The resulting `blue-button` element looks as follows:

[subs="none"]
++++

<link rel="import" href="html/src/recipes/convention/css/blue-button.html">

<div class="polymer-demo-container">
    <blue-button></blue-button>
</div>

++++

[[recipes__conventions__private_methods]]
==== Private Methods and Properties

Any Polymer component can expose an API consisting of a number of methods and properties.
These component members can be called public.
But there are also properties and methods that are supposed to be used only by the component itself.
We can call these members private.

It's a good practice to prefix private methods and properties with underscore.

See an example below.

*Disco lights application*

[subs="none"]
++++

<link rel="import" href="html/src/recipes/convention/access-control/disc-jockey.html">

<div class="polymer-demo-container">
    <disc-jockey></disc-jockey>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/convention/access-control/disc-jockey.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <disc-jockey></disc-jockey>
</body>
</html>
----

.src/recipes/convention/access-control/disc-jockey.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/access-control/disc-jockey.html[]
----

.src/recipes/convention/access-control/disco-lights.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/access-control/disco-lights.html[]
----

[TIP]
====
The `_currentColor` property is made private, but for a component which is designed to be reusable across many projects this property could be public. Another option would be creating an event with the information about currently selected color.
====

By adopting this convention we achieve at least the following goals:

* We explicitly declare what element members can be used.

* We make an API more clear and obvious.

* During refactoring, we clearly see names of properties and methods that shouldn't be changed.

[[recipes__conventions__import]]
==== Managing Imports

In this section, we consider the problem of correct usage of HTML imports.

Let's look at the next example.
There are 2 components.
The first one contains a paper button and a 2nd component.
The 2nd component also contains a paper button.
The buttons do nothing, but the example demonstrates some interesting details about imports.

[subs="none"]
++++

<link rel="import" href="html/src/recipes/convention/import/parent-button-component.html">

<div class="polymer-demo-container">
    <parent-button-component></parent-button-component>
</div>

++++

*Source code:*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/convention/import/parent-button-component.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <parent-button-component></parent-button-component>
</body>
</html>
----

.src/recipes/convention/import/parent-button-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/import/parent-button-component.html[]
----

.src/recipes/convention/import/child-button-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/import/child-button-component.html[]
----

As you can see, we forgot to import the button component into the child component but the example application still works.

What will happen if we later refactor our `parent-button-component` and decide that
the simple HTML `<button/>` will suffice and remove `paper-button`?
See below.

.src/recipes/convention/import/parent-simple-button-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/import/parent-simple-button-component.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="50"
        class="polymer-iframe-container"
        src="html/src/recipes/convention/import/iframe/parent-simple-button-component-app.html">

    </iframe>
++++

So, we have broken the child component involuntary.

It's a simple case to present a matter.
In real applications, there are dozens of components that import each other.
So, `paper-button` could be used not in a direct child but in one of the great-great-great-grandchild components.
After a complex refactoring, it's possible to not notice that something broke.
And when you finally discover that something doesn't work, it can be difficult to find a cause.

But there can be even more complicated cases.
In our example, we imported `paper-button` into the parent component and didn't import it into the child component.
But we could do the opposite thing: import it into the child component and do not import it into the parent one.
And it would work! Apparently, in this case it can be broken even easier.

The point of all this is that we should use imports carefully.
We recommend importing all required components in each custom component,
and if you remove some HTML code later, check and remove redundant imports.
In this case, all your components are guaranteed to work when other components are removed or refactored.

There is an ability to check imports automatically by running `polymer lint` command. In order to use it, you must install
 https://www.polymer-project.org/2.0/docs/tools/polymer-cli[polymer-cli].

There are other conventions that can be used.
For example, you can import all paper and iron elements in a root component and use them afterwards everywhere
without import statements.
Or you can even import all components in your root component, so you won't need to use imports elsewhere in the code.
The choice should be made by each team based on their preferences.
In this case any convention, good or bad, is better than no convention at all.

[TIP]
====
If you bundle your client code before production, the problem is entirely in the area of development environment.
Production and test code has no import statements because there is a single HTML file containing all code.
====

[[recipes__i18n]]
=== Internationalization

Internationalization is a common task for many projects.
And even if we don't need to support multiple languages, it still can be useful to store all user messages together to
have better perspective and avoid duplication.

CUBA provides the `CubaLocalizeBehavior` that can assist you in this task.
Basically, it just introduces the `msg()` method that gets messages from the `messages` property depending on the current locale. See an example below.

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/i18n/simple-greeting-component.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <simple-greeting-component></simple-greeting-component>
</body>
</html>
----

.src/recipes/i18n/simple-greeting-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/i18n/simple-greeting-component.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="100"
        class="polymer-iframe-container"
        src="html/src/recipes/i18n/stub/simple-greeting-component-stub.html"></iframe>
++++

`CubaLocalizeBehavior` requires an initialized <<cuba_app,cuba-app>>.

How the default locale is determined is up to you: you can set a locale on component initialization or provide some kind of language switcher that changes the locale. Below is an example of switching locale.

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/i18n/locale-switcher.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <locale-switcher></locale-switcher>
</body>
</html>
----

.src/recipes/i18n/locale-switcher.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/i18n/locale-switcher.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="100"
        class="polymer-iframe-container"
        src="html/src/recipes/i18n/stub/locale-switcher-stub.html"></iframe>
++++

Still it would be more convenient to have a single place where all messages are stored.
It can be easily achieved by creating a proxy between `CubaLocalizeBehavior` and the rest of your application.

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/i18n/calcium-adv.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <calcium-adv></calcium-adv>
</body>
</html>
----

.src/recipes/i18n/calcium-adv.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/i18n/calcium-adv.html[]
----

.src/recipes/i18n/i18n-mixin.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/i18n/i18n-mixin.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="200"
        class="polymer-iframe-container"
        src="html/src/recipes/i18n/stub/calcium-adv-stub.html"></iframe>
++++

As you can see, now the components just implement `I18nMixin` and don't contain any actual messages.

[[recipes__fetch]]
=== Using REST API

This section contains some recommendations on consuming third-party REST APIs.

Fetch API::
+
--
`index.html` generated by CUBA Studio contains a polyfill for Fetch API because it's used by CUBA Polymer components.

So, you can easily use `fetch` in your own code.

.src/recipes/ajax/fetch-example.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/ajax/fetch-example.html[]
----

Read https://developers.google.com/web/updates/2015/03/introduction-to-fetch[this article] to learn more about Fetch API.
--

iron-ajax::
+
--
`iron-ajax` component is an another convenient option to perform AJAX requests.

.src/recipes/ajax/iron-ajax-example.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/ajax/iron-ajax-example.html[]
----
--

[[recipes__di]]
=== Services and Dependency Injection

In this section, by a service we mean a program component that provides some specific functionality to other components. The most common examples of services are components working with REST APIs, internationalization, utility services, caches, etc.

There is a number of approaches of creating services and injecting them into your web components. We recommend to adopt
the way described below.

Let's imagine an application that shows notifications to users.
These notifications are represented by a piece of text that is shown to users for a short time to inform them about some event. Different parts of the application need an ability to show notifications.

Here is a possible implementation:

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/di/forbidden-button.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <forbidden-button></forbidden-button>
</body>
</html>
----

.src/recipes/di/forbidden-button.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/di/forbidden-button.html[]
----

.src/recipes/di/notification-service.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/di/notification-service.html[]
----

*Result*
[subs="none"]
++++

<link rel="import" href="html/src/recipes/di/forbidden-button.html">

<div class="polymer-demo-container">
    <forbidden-button></forbidden-button>
</div>

++++

So, basically we just instantiate some object, put it in a global variable and assign this variable to a component's
property.

[[recipes__navigation]]
=== Navigation

Certainly navigation is one of the most common features that we have to implement while creating a web application.
In this section, we'll consider one of the possible ways to do it.

The implementation is based on two components: `app-route` and `iron-lazy-pages`.

* `app-route` is used to analyze URL currently opened in the browser.

* `iron-lazy-pages` manages what page with which content should be opened.

Below is a simple example demonstrating how the result of using these elements might work. It's put in `<iframe/>` because
we have to change current location in order to show how navigation works.

*Navigation example*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/app-with-navigation.html">

    </iframe>
++++

*Code in iframe*

.app-with-navigation.html
[source, html]
----
include::{sourcesdir}/polymer-build/app-with-navigation.html[]
----

*Polymer element implementing navigation*

.src/recipes/navigation/thermodynamic-laws.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/navigation/thermodynamic-laws.html[]
----

Navigation can contain multiple levels. It can be achieved with the help of the same `app-route` and `iron-lazy-pages` components. In the example below, click on the "Paper Elements" link and you will be presented with the second level of navigation.

*2-level navigation*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/app-with-2-level-navigation.html">

    </iframe>
++++

*Source code:*

.src/recipes/navigation/polymer-elements-registry.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/navigation/polymer-elements-registry.html[]
----

.src/recipes/navigation/paper-elements-registry.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/navigation/paper-elements-registry.html[]
----

The same method can be used to create any navigation tree.

[[recipes__library]]
=== Adding a Library

Currently CUBA Polymer UI module uses https://bower.io/[Bower] as a package manager.
Therefore, you can import any library that is published on https://github.com[GitHub].

Imagine that you want to use https://www.webcomponents.org/element/PolymerElements/paper-toggle-button[paper-toggle-button] in your project.
Its source code is located at https://github.com/PolymerElements/paper-toggle-button.

There are two ways to add this library to your project:

. Via command line:
+
[source,bash]
----
$ bower install PolymerElements/paper-toggle-button --save
----

. Manually add it to `bower.json`:
+
[source,javascript]
----
...
"dependencies": {
  ...
  "paper-toggle-button": "PolymerElements/paper-toggle-button"
},
...
----

The library will be downloaded to `bower_components/paper-toggle-button` folder and can be used in your code.

By default, Bower uses a default branch of the required dependency.
If you want to use another version, specify it after the `#` sign:

[source,bash]
----
$ bower install PolymerElements/paper-toggle-button#3.0.0-pre.1 --save
----