:sourcesdir: ../../../../source

[[servlet_registration_sample]]
==== Registering DispatcherServlet from Application Component

This section will learn you how to propagate the servlets and filters configuration from an application <<app_components,component>> to the owning application. To avoid the duplication of code in the <<web.xml,web.xml>> file, you need to register your servlets and filters in the component using the special `ServletRegistrationManager` bean.

The most common case of servlets registration is described through the example of <<servlet_registration,HTTP servlet registration>>. Let's consider a more complex example: an application component with a custom implementation of `DispatcherServlet` for processing web requests.

This servlet loads its config from the `demo-dispatcher-spring.xml` file, so to see it working you should create an empty file with such name in the root source directory (e.g. `web/src`).

[source,java]
----
include::{sourcesdir}/cookbook/servlet_sample.java[]
----

To register `DispatcherServlet`, you have to load the class manually, instantiate it and initialize, otherwise different ClassLoaders may cause an issue in case of SingleWAR/SingleUberJAR <<deployment_variants,deployment>>. Moreover, the custom `DispatcherServlet` should be ready to double initialization - first time we initialize it manually, second time it is initialized by a servlet container.

Here is an example of a component that initializes `WebDispatcherServlet`:

[source,java]
----
include::{sourcesdir}/cookbook/servlet_sample_2.java[]
----

The `createServlet()` method of the injected `ServletRegistrationManager` bean takes the application <<appContext,context>> from `ServletContextInitializedEvent` and the fully-qualified name of the `WebDispatcherServlet` class. In order to initialize the servlet, we pass the instance of `ServletContext` obtained from `ServletContextInitializedEvent` and the servlet name. The `addMapping()` method is used to define an HTTP mapping for accessing the servlet via URL: `/webd/`.

