:sourcesdir: ../../../../../source

[[opening_screens]]
===== Opening Screens

A screen can be opened from the <<menu.xml,main menu>>, by <<url_history_navigation,navigating to a URL>>, by a <<standard_actions,standard action>> (when working with browse and edit entity screens), or programmatically from another screen. In this section, we explain how to open screens programmatically.

'''

<<screens_intf,Using the Screens interface>>

<<screenBuilders,Using the ScreenBuilders bean>>

<<screen_parameters,Passing parameters to screens>>

<<screen_return_values,Executing code after close and returning values>>

'''

[[screens_intf]]
Using the Screens interface::
+
--
The `Screens` interface allows you to create and show screens of any type.

Suppose we have a screen to show a message with some special formatting:

.Screen controller
[source, java]
----
include::{sourcesdir}/gui/screens/screens_1.java[]
----
<1> - a screen parameter

.Screen descriptor
[source, xml]
----
include::{sourcesdir}/gui/screens/screens_1.xml[]
----

Then we can create and open it from another screen as follows:

[source, java]
----
include::{sourcesdir}/gui/screens/screens_2.java[]
----

Notice how we create the screen instance, provide a parameter for it and then show the screen.

If the screen does not require any parameters from the caller code, you can create and open it in one line:

[source, java]
----
include::{sourcesdir}/gui/screens/screens_3.java[]
----

[WARNING]
====
`Screens` is not a Spring bean, so you can only inject it to screen controllers or obtain using `ComponentsHelper.getScreenContext(component).getScreens()` static method.
====
--

[[screenBuilders]]
Using the ScreenBuilders bean::
+
--
The `ScreenBuilders` bean allows you to open all kinds of screens with various parameters. 

[TIP]
====
Learn https://www.cuba-platform.com/guides/initial-entity-values#external_initialization_via_screen_builders[Initial Entity Values] guide, which shows external initialization  via `ScreenBuilders`.
====

Below is an example of using it for opening a screen and executing some code after the screen is closed (see more details <<screen_return_values,here>>):

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_withAfterCloseListener.java[]
----

Next we'll consider working with editor and lookup screens. Note that in most cases you open such screens using <<standard_actions,standard actions>> (such as <<CreateAction>> or <<LookupAction>>), so you don't have to use the `ScreenBuilders` API directly. However, the examples below can be useful if you don't use standard actions but open a screen from a <<baseAction>> or <<gui_Button>> handler.

Example of opening a default editor for the `Customer` entity instance:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor.java[]
----

In this case, the editor will update the entity, but the caller screen will not receive the updated instance.

Often you need to edit an entity displayed by some `Table` or `DataGrid` component. Then you should use the following form of invocation, which is more concise and automatically updates the table:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_2.java[]
----

In order to create a new entity instance and open the editor screen for it, just call the `newEntity()` method on the builder:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_3.java[]
----

[TIP]
====
The default editor screen is determined by the following procedure:

. If an editor screen annotated with <<PrimaryEditorScreen_annotation,@PrimaryEditorScreen>> exists, it is used.
. Otherwise, an editor screen with `++<entity_name>.edit++` id is used (for example, `sales_Customer.edit`).
====

The builder provides a lot of methods to set optional parameters of the opened screen. For example, the following code creates an entity first initializing the new instance, in a particular editor opened as a dialog:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_4.java[]
----

Entity lookup screens can also be opened with various parameters.

Below is an example of opening a default lookup screen of the `User` entity:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup.java[]
----

If you need to set the looked up entity to a field, use the more concise form:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_2.java[]
----

[TIP]
====
The default lookup screen is determined by the following procedure:

. If a lookup screen annotated with <<PrimaryLookupScreen_annotation,@PrimaryLookupScreen>> exists, it is used.
. Otherwise, if a screen with `++<entity_name>.lookup++` id exists, it is used (for example, `sales_Customer.lookup`).
. Otherwise, a screen with `++<entity_name>.browse++` id is used (for example, `sales_Customer.browse`).
====

As with edit screens, use the builder methods to set optional parameters of the opened screen. For example, the following code looks up the `User` entity using a particular lookup screen opened as a dialog:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_3.java[]
----
--

[[screen_parameters]]
Passing parameters to screens::
+
--
The recommended way of passing parameters to an opened screen is to use public setters of the screen controller, as demonstrated in the example <<screens_intf,above>>.

With this approach, you can pass parameters to screens of any type, including entity edit and lookup screens opened using <<screenBuilders,ScreenBuilders>> or from the <<menu.xml_screen_properties,main menu>>. The invocation of the same `FancyMessageScreen` using `ScreenBuilders` with passing the parameter looks as follows:

[source, java]
----
include::{sourcesdir}/gui/screens/passing_parameters_1.java[]
----

If you are opening a screen using a standard action such as <<CreateAction>>, use its `screenConfigurer` handler to pass parameters via screen public setters.

Another way is to define a special class for parameters and pass its instance to the standard `withOptions()` method of the screen builder. The parameters class must implement the `ScreenOptions` marker interface. For example:

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_1.java[]
----

In the opened `FancyMessageScreen` screen, the options can be obtained in <<screen_InitEvent,InitEvent>> and <<screen_AfterInitEvent,AfterInitEvent>> handlers:

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_2.java[]
----

The invocation of the `FancyMessageScreen` screen using `ScreenBuilders` with passing `ScreenOptions` looks as follows:

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_3.java[]
----

As you can see, this approach requires type casting in the controller receiving the parameters, so use it wisely and prefer the type-safe setters approach explained above.

If you are opening a screen using a standard action such as <<CreateAction>>, use its `screenOptionsSupplier` handler to create and initialize the required `ScreenOptions` object.

Usage of the `ScreenOptions` object is the only way to get parameters if the screen is opened from a screen based on the <<abstractFrame_openWindow,legacy API>>. In this case, the options object is of type `MapScreenOptions` and you can handle it in the opened screen as follows:

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_4.java[]
----
--

[[screen_return_values]]
Executing code after close and returning values::
+
--
Each screen sends `AfterCloseEvent` when it closes. You can add a listener to a screen to be notified when the screen is closed, for example:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_1.java[]
----

When using `ScreenBuilders`, the listener can be provided in the `withAfterCloseListener()` method:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_2.java[]
----

The event object provides an information about how the screen was closed. This information can be obtained in two ways: by testing whether the screen was closed with one of standard outcomes defined by the `StandardOutcome` enum, or by getting the `CloseAction` object. The former approach is simpler while the latter is much more flexible.

Let's consider the first approach: to close a screen with a standard outcome and test for it in the calling code.

The following screen is to be invoked:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_3.java[]
----
<1> - on "OK" button click, set some result state and close the screen with `StandardOutcome.COMMIT` enum value.
<2> - on "Cancel" button click, close the with `StandardOutcome.CLOSE`.

In the `AfterCloseEvent` listener, you can check how the screen was closed using the `closedWith()` method of the event, and read the result value if needed:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_4.java[]
----

Another way of returning values from screens is using custom `CloseAction` implementations. Let's rewrite the above example to use the following action class:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_5.java[]
----

Then we can use this action when closing the screen:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_6.java[]
----
<1> - on "OK" button click, create the custom close action and set the result value in it.
<2> - on "Cancel" button click, close with a default action provided by the framework.

In the `AfterCloseEvent` listener, you can get the `CloseAction` from the event and read the result value:

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_7.java[]
----

As you can see, when values are returned through a custom `CloseAction`, the caller doesn't have to know the opened screen class because it doesn't invoke methods of the concrete screen controller. So the screen can be created by its string id.

Of course, the same approach for returning values through close actions can be used when opening screens using `ScreenBuilders`.
--