:sourcesdir: ../../../../../source

[[opening_screens]]
===== Opening Screens

[[screens_intf]]
Using the Screens interface::
+
--
The `Screens` interface allows you to create and show screens of any type.

Suppose we have a screen to show a message with some special formatting:

.Screen controller
[source, java]
----
include::{sourcesdir}/gui/screens/screens_1.java[]
----

.Screen descriptor
[source, xml]
----
include::{sourcesdir}/gui/screens/screens_1.xml[]
----

Then we can create and open it from another screen as follows:

[source, java]
----
include::{sourcesdir}/gui/screens/screens_2.java[]
----

Notice how we create the screen instance, provide a parameter for it and then show the screen.

If the screen does not require any parameters from the caller code, you can create and open it in one line:

[source, java]
----
include::{sourcesdir}/gui/screens/screens_3.java[]
----

[WARNING]
====
`Screens` is not a Spring bean, so you can only inject it to screen controllers or obtain using `ComponentsHelper.getScreenContext(component).getScreens()` static method.
====
--

[[screenBuilders]]
Using the ScreenBuilders bean::
+
--
The `ScreenBuilders` bean allows you to open all kinds of screens with various parameters.

One of the common tasks is to run some code when the opened screen closes. Below is an example of using `withAfterCloseListener()` builder method when opening an arbitrary screen:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_withAfterCloseListener.java[]
----

Next we'll consider working with editor and lookup screens.

Example of opening a default editor for the `Customer` entity instance:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor.java[]
----

In this case, the editor will update the entity, but the caller screen will not receive the updated instance.

The most common case is when you need to edit an entity displayed by some `Table` or `DataGrid` component. Then you should use the following form of invocation, which is more concise and automatically updates the table:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_2.java[]
----

In order to create a new entity instance and open the editor screen for it, just call the `newEntity()` method on the builder:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_3.java[]
----

[TIP]
====
The default editor screen is determined by the following procedure:

. If an editor screen annotated with <<PrimaryEditorScreen_annotation,@PrimaryEditorScreen>> exists, it is used.
. Otherwise, an editor screen with `++{entity_name}.edit++` id is used (for example, `sales_Customer.edit`).
====

The builder provides a lot of methods to set optional parameters of the opened screen. For example, the following code creates an entity first initializing the new instance, in a particular editor opened as a dialog:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_4.java[]
----

Entity lookup screens can also be opened with various parameters.

Below is an example of opening a default lookup screen of the `User` entity:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup.java[]
----

If you need to set the looked up entity to a field, use the more concise form:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_2.java[]
----

[TIP]
====
The default lookup screen is determined by the following procedure:

. If a lookup screen annotated with <<PrimaryLookupScreen_annotation,@PrimaryLookupScreen>> exists, it is used.
. Otherwise, if a screen with `++{entity_name}.lookup++` id exists, it is used (for example, `sales_Customer.lookup`).
. Otherwise, a screen with `++{entity_name}.browse++` id is used (for example, `sales_Customer.browse`).
====

As with edit screens, use the builder methods to set optional parameters of the opened screen. For example, the following code looks up the `User` entity using a particular lookup screen opened as a dialog:

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_3.java[]
----
--