:sourcesdir: ../../../../../source

[[screen_descriptors]]
===== Screen XML Descriptors

Screen descriptor is an XML file containing declarative definition of <<gui_vcl,visual components>>, <<gui_data,data components>> and some screen parameters.

XML schema is available at {xsd_url}/screen/window.xsd.

A descriptor has the `window` the root element.

The root element attributes:

* `class` − name of a <<screen_controller,controller>> class.

* `messagesPack` − a default <<message_packs,message pack>> for the screen. It is used to obtain localized messages in the controller using `getMessage()` method and in the XML descriptor using message key without specifying the pack.

* `caption` − window caption, can contain a <<messageTools.loadString,link to a message>> from the above mentioned pack, for example,
+
[source, properties]
----
caption="msg://credits"
----

* `focusComponent` − identifier of a component which should get input focus when the screen is displayed.

Elements of the descriptor:

* `data` − defines <<gui_data,data components>> of the screen.

* `dialogMode` - defines the settings of geometry and behaviour of the screen when it is opened as a dialog.
+
--
Attributes of `dialogMode`:

** `closeable` - defines whether the dialog window has close button. Possible values: `true`, `false`.

** `closeOnClickOutside` - defines if the dialog window should be closed by click on outside the window area, when the window has a modal mode. Possible values: `true`, `false`.

** `forceDialog` - specifies that the screen should always be opened as a dialog regardless of what `WindowManager.OpenType` was selected in the calling code. Possible values: `true`, `false`.

** `height` - sets the height of the dialog window.

** `maximized` - if the `true` value is set, the dialog window will be maximized across the screen. Possible values: `true`, `false`.

** `modal` - specifies the modal mode for the dialog window. Possible values: `true`, `false`.

** `positionX` - sets the `x` position of the top-left corner of the dialog window.

** `positionY` - sets the `y` position of the top-left corner of the dialog window.

** `resizable` - defines whether the user can change the size of the dialog window. Possible values: `true`, `false`.

** `width` - sets the width of the dialog window.

For example:

[source, xml]
----
include::{sourcesdir}/gui/dialogs_4.xml[]
----
--

* `actions` – defines the list of <<gui_Action,actions>> for the screen.

* `timers` – defines the list of <<gui_Timer,timers>> for the screen.

* `layout` − root element of the screen layout.