:sourcesdir: ../../../../source

[[persistence]]
==== The Persistence Interface

The `Persistence` interface is designed to be an entry point to the data storage functionality provided by the <<orm,ORM>> layer.

The interface has the following methods:

* `createTransaction()`, `getTransaction()` – obtain the interface for managing <<transactions,transactions>>. The methods can accept a <<data_store,data store>> name. If it is not provided, the main data store is assumed.

* `callInTransaction()`, `runInTransaction()` - execute an action in a new transaction with or without return value. The methods can accept a <<data_store,data store>> name. If it is not provided, the main data store is assumed.

* `isInTransaction()` – checks if there is an active transaction the moment.

* `getEntityManager()` – returns an <<entityManager,EntityManager>> instance bound to the current transaction. The method can accept a <<data_store,data store>> name. If it is not provided, the main data store is assumed.

* `isSoftDeletion()` – allows you to determine if the <<soft_deletion,soft deletion>> mode is active.

* `setSoftDeletion()` – enables or disables the soft deletion mode. Setting this property affects all newly created `EntityManager` instances. Soft deletion is enabled by default.

* `getDbTypeConverter()` – returns the <<dbTypeConverter,DbTypeConverter>> instance for the main database or for an additional data store.

* `getDataSource()` – returns the `javax.sql.DataSource` instance for the main database or for an additional data store.
+
[WARNING]
====
For all `javax.sql.Connection` objects obtained through `getDataSource().getConnection()` method the `close()` method should be called in the `finally` section after using the connection. Otherwise, the connection will not be returned to the pool. Over time, the pool will overflow and the application will not be able to execute database queries.
====

* `getTools()` – returns an instance of the `PersistenceTools` interface (see below).

include::persistence/persistenceTools.adoc[]

include::persistence/dbTypeConverter.adoc[]

