[[cookbook]]
== Сборник рецептов

// for backward compatibility
[[dev_recipes]]

[WARNING]
====
Данный раздел будет обновлен перед выходом релиза 7.0
====

Данный раздел представляет собой коллекцию практических рецептов по решению типичных задач, встающих перед разработчиками при использовании платформы CUBA. В каждом подразделе информация организована от простого к сложному, поэтому вы в любой момент можете перейти к другой секции или заняться кодированием.

Большинство разделов снабжены демо-приложениями. Вы можете увидеть их в работе онлайн, посмотреть исходный код на GitHub, или загрузить и запустить локально.

[TIP]
====
Данный раздел находится в работе и будет постоянно дополняться. Если у вас есть идеи новых рецептов и задач, решение которых стоило бы продемонстрировать, вы можете создать запрос в виде issue в исходниках документации на https://github.com/cuba-platform/documentation[GitHub].
====

include::cookbook/business_logic_recipes.adoc[]

include::cookbook/modeling_domain_recipes.adoc[]

include::cookbook/ui_recipes.adoc[]

include::cookbook/data_recipes.adoc[]

include::cookbook/rest_api_v2_usage_example.adoc[]

include::cookbook/app_components_recipes.adoc[]

include::cookbook/misc_recipes.adoc[]

