[[extension]]
=== Расширение функциональности

Платформа позволяет расширять и переопределять свою функциональность в приложениях в следующих аспектах:

* расширение набора атрибутов сущностей

* расширение функциональности экранов

* расширение и переопределение бизнес-логики, сосредоточенной в бинах *Spring* 

Рассмотрим две первые задачи на примере добавления поля `Адрес` в сущность `User` подсистемы безопасности платформы.

[[entity_extension]]
==== Расширение сущности

Создадим в проекте приложения класс сущности, унаследованный от `com.haulmont.cuba.security.entity.User` и добавим в него требуемый атрибут с соответствующими методами доступа: 

[source, java]
----
include::{sourcesdir}/extension/entity_extension_1.java[]
----

В аннотации `<<entity_annotation,@Entity>>` должно быть указано новое имя сущности. Так как базовая сущность не объявляет <<inheritance_annotation,стратегию наследования>>, то по умолчанию это `SINGLE_TABLE`. Это означает, что унаследованная сущность будет храниться в той же таблице, что и базовая, и аннотация `<<table_annotation,@Table>>` не требуется. Другие аннотации базовой сущности - `<<namePattern_annotation,@NamePattern>>`, `<<listeners_annotation,@Listeners>>` и прочие - автоматически применяются к расширяющей сущности, но могут быть переопределены в ее классе.

Важным элементом класса новой сущности является аннотация `@Extends` с базовым классом в качестве параметра. Она позволяет сформировать реестр расширяющих сущностей, и заставить механизмы платформы использовать их повсеместно вместо базовых. Реестр реализуется классом `ExtendedEntities`, который является бином *Spring* с именем `cuba_ExtendedEntities`, и доступен также через интерфейс `<<metadata,Metadata>>`.

Добавим локализованное название нового атрибута в <<message_packs,пакет>> `com.sample.sales.entity`:

`messages.properties`

[source, properties]
----
ExtUser.address=Address
----

`messages_ru.properties`

[source, properties]
----
ExtUser.address=Адрес
----

Зарегистрируем новую сущность в файле `<<persistence.xml,persistence.xml>>` проекта:

[source, xml]
----
<class>com.sample.sales.entity.ExtUser</class>
----

Добавим в <<db_scripts,скрипты создания и обновления базы данных>> команду модификации соответствующей таблицы:

[source, sql]
----
include::{sourcesdir}/extension/entity_extension_2.sql[]
----

Чтобы использовать новые атрибуты сущности в экранах, создадим <<views,представления>> для новой сущности с теми же именами, что у представлений базовой сущности. Новые представления должны расширять базовые и определять новые атрибуты. Например:

[source, xml]
----
include::{sourcesdir}/extension/entity_extension_3.xml[]
----

Расширяющее представление включает в себя все атрибуты базового представления. Расширяющее представление не требуется, если базовое расширяет `_local` и вы добавляете только локальные атрибуты. Поэтому в описываемом случае данный шаг может быть пропущен.

[[screen_extension]]
==== Расширение экранов

Платформа позволяет создавать новые <<screen_xml,XML-дескрипторы>> экранов путем наследования от существующих.

Наследование XML выполняется путем указания в корневом элементе `window` атрибута `extends`, содержащего путь к базовому дескриптору.

Правила переопределения элементов XML экрана:

* Если в расширяющем дескрипторе указан некоторый элемент, в базовом дескрипторе будет произведен поиск соответствующего элемента по следующему алгоритму:

** Если переопределяющий элемент - `view`, то ищется соответствующий элемент по атрибутам `name`, `class`, `entity`.

** Если переопределяющий элемент - `property`, то ищется соответствующий элемент по атрибуту `name`.

** В других случаях, если в переопределяющем элементе указан атрибут `id`, ищется соответствующий элемент с таким же `id`. 

** Если поиск дал результат, то найденный элемент *переопределяется*.

** Если поиск не дал результата, то определяется, сколько в базовом дескрипторе элементов по данному пути и с данным именем. Если ровно один - он *переопределяется*.

** Если поиск не дал результата, и в базовом дескрипторе по данному пути с данным именем нет элементов, либо их больше одного, *добавляется* новый элемент.

* В переопределяемом либо добавляемом элементе устанавливается текст из расширяющего элемента. 

* В переопределяемый либо добавляемый элемент копируются все атрибуты из расширяющего элемента. При совпадении имени атрибута значение берется из расширяющего элемента.

* Добавление нового элемента по умолчанию производится в конец списка соседних элементов. Чтобы добавить новый элемент в начало или с произвольным индексом, необходимо выполнить следующее: 

** определить в расширяющем дескрипторе дополнительный namespace: `xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"`

** добавить в расширяющий элемент атрибут `ext:index` с желаемым индексом, например: `ext:index="0".`

Для отладки преобразования дескрипторов можно включить вывод в журнал сервера результирующего XML. Делается это путем указания уровня `TRACE` для логгера `com.haulmont.cuba.gui.xml.XmlInheritanceProcessor` в файле конфигурации *Logback*.

Пример XML-дескриптора экрана браузера сущностей `ExtUser`:

[source, xml]
----
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
      xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"
      extends="/com/haulmont/cuba/gui/app/security/user/browse/user-browse.xml">
  <layout>
      <groupTable id="usersTable">
          <columns>
              <column id="address" ext:index="2"/>
          </columns>
      </groupTable>
  </layout>
</window>
----

В данном примере дескриптор унаследован от стандартного браузера сущностей `User` платформы, и в таблицу добавлена колонка `address` с индексом `2`, т.е. отображающаяся после `login` и `name`.

Зарегистрируем новый экран в `<<screens.xml,screens.xml>>` с теми же идентификаторами, которые использовались для базового экрана. После этого новый экран будет повсеместно вызываться взамен старого.

[source, xml]
----
<screen id="sec$User.browse"
      template="com/sample/sales/gui/extuser/extuser-browse.xml"/>
<screen id="sec$User.lookup"
      template="com/sample/sales/gui/extuser/extuser-browse.xml"/>
----

Аналогично создаем экран редактирования:

[source, xml]
----
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
      xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"
      extends="/com/haulmont/cuba/gui/app/security/user/edit/user-edit.xml">
  <layout>
      <fieldGroup id="fieldGroup">
          <column id="fieldGroupColumn2">
              <field property="address" ext:index="4"/>
          </column>
      </fieldGroup>
  </layout>
</window>
----

Регистрируем его в `screens.xml` с идентификатором базового экрана:

[source, xml]
----
<screen id="sec$User.edit"
      template="com/sample/sales/gui/extuser/extuser-edit.xml"/>
----

После выполнения описанных выше действий в приложении вместо платформенной сущности `User` будет использоваться `ExtUser` с соответствующими экранами.

Контроллер экрана может быть расширен путем создания нового класса, унаследованного от контроллера базового экрана. Имя класса указывается в атрибуте `class` корневого элемента расширяющего XML дескриптора, при этом выполняются обычные правила наследования XML, описанные выше. 

[[bean_extension]]
==== Расширение бизнес-логики

Основная часть бизнес-логики платформы сосредоточена в бинах *Spring*, что позволяет легко расширить или переопределить ее в приложении.

Для подмены реализации бина достаточно создать свой класс, реализующий интерфейс или расширяющий базовый класс платформы, и зарегистрировать его в <<spring.xml,spring.xml>> приложения. Аннотацию `@Component` в расширяющем классе применять нельзя, переопределение бинов возможно только с помощью конфигурации в XML.

Рассмотрим пример добавления метода в бин <<persistenceTools,PersistenceTools>>.

Создаем класс с нужным методом:

[source, java]
----
public class ExtPersistenceTools extends PersistenceTools {

  public Entity reloadInSeparateTransaction(final Entity entity, final String... viewNames) {
      Entity result = persistence.createTransaction().execute(new Transaction.Callable<Entity>() {
          @Override
          public Entity call(EntityManager em) {
              return em.reload(entity, viewNames);
          }
      });
      return result;
  }
}
----

Регистрируем класс в `spring.xml` модуля *core* проекта с тем же идентификатором, что и бин платформы:

[source, xml]
----
<bean id="cuba_PersistenceTools" class="com.sample.sales.core.ExtPersistenceTools"/>
----

После этого контекст *Spring* вместо экземпляра базового класса `PersistenceTools` будет всегда возвращать `ExtPersistenceTools`, например:

[source, java]
----
Persistence persistence;
PersistenceTools tools;

persistence = AppBeans.get(Persistence.class);
tools = persistence.getTools();
assertTrue(tools instanceof ExtPersistenceTools);

tools = AppBeans.get(PersistenceTools.class);
assertTrue(tools instanceof ExtPersistenceTools);

tools = AppBeans.get(PersistenceTools.NAME);
assertTrue(tools instanceof ExtPersistenceTools);
----

Таким же образом можно переопределять логику сервисов, например, из <<app_components_sample,компонентов приложения>>: для подмены реализации бина нужно создать класс, расширяющий функциональность исходного сервиса. В следующем примере мы создали новый класс `NewOrderServiceBean`, чтобы переопределить в нём метод из исходного сервиса `OrderServiceBean`:

[source, java]
----
public class NewOrderServiceBean extends OrderServiceBean {
    @Override
    public BigDecimal calculateOrderAmount(Order order) {
        BigDecimal total = super.calculateOrderAmount(order);
        BigDecimal vatPercent = new BigDecimal(0.18);
        return total.multiply(BigDecimal.ONE.add(vatPercent));
    }
}
----

Теперь, после регистрации нового класса в `spring.xml`, новая реализация будет использоваться в приложении вместо исходной, заданной в `OrderServiceBean`. Обратите внимание, что в определении бина используется идентификатор из компонента приложения и полное имя нового класса:

[source, xml]
----
<bean id="workshop_OrderService" class="com.company.retail.service.NewOrderServiceBean"/>
----

[[servlet_registration]]
==== Регистрация сервлетов и фильтров

Чтобы использовать сервлеты и фильтры Spring Security, настроенные в <<app_components,компоненте приложения>>, их нужно зарегистрировать из компонента так, чтобы регистрация динамически распространялась и на родительское приложение. По умолчанию, в рамках одного приложения сервлеты регистрируются в файле конфигурации <<web.xml,web.xml>>, но в случае с подключением компонентов такой подход не работает.

Для динамической регистрации сервлетов и фильтров используется бин `ServletRegistrationManager`: он гарантирует, что при загрузке каждого сервлета будет использован корректный ClassLoader, и позволяет обращаться к статическим классам, таким как <<appContext,AppContext>>. Этот бин необходимо использовать для корректной работы компонентов независимо от <<deployment_variants,варианта развёртывания>> приложения.

Бин `ServletRegistrationManager` имеет два метода:

. `createServlet()` - создаёт сервлет указанного класса. Он загружает класс сервлета с нужным экземпляром `ClassLoader`, который получает из контекста приложения. Таким образом, новый сервлет может использовать статические классы платформы, например, `AppContext` или бин <<messages,Messages>>.

. `createFilter()` - создаёт фильтр аналогично созданию сервлетов.

Для использования этого бина мы рекомендуем создать в компоненте приложения отдельный бин-инициализатор. Этот бин должен представлять собой обычный класс  с аннотацией `@Component` и содержать слушатели событий создания и уничтожения контекста приложения: <<ServletContextInitializedEvent,ServletContextInitializedEvent>> и `ServletContextDestroyedEvent`.

Пример бина-инициализатора:

[source, java]
----
include::{sourcesdir}/extension/WebInitializer.java[]
----

Здесь класс `WebInitializer` содержит только один слушатель, который используется для регистрации HTTP-сервлета из компонента приложения в родительском приложении.

Метод `createServlet()` принимает контекст приложения, полученный из события `ServletContextInitializedEvent`, и полное имя класса HTTP-сервлета. Далее мы регистрируем сервлет по его имени (`my_servlet`) и указываем URL, по которому будет доступен сервлет (`/myservlet/`). Теперь при подключении этого компонента к другому приложению сервлет `MyHttpServlet` будет зарегистрирован сразу после инициализации `AppContext` и `ServletContext`.

Более сложный пример использования бина `ServletRegistrationManager` приведён в разделе <<servlet_registration_sample,Регистрация DispatcherServlet из компонента приложения>>.

[[servlet_registration_single_war]]
Регистрация сервлетов для развертывания в единый WAR-файл::
+
--
Для корректной загрузки сервлетов и фильтров при развертывании <<build.gradle_buildWar_single,в единый WAR-файл>> следуйте инструкции ниже:

. Создайте класс, расширяющий `javax.servlet.ServletContextListener`, который будет выполнять создание сервлетов/фильтров:
+
[source, java]
----
include::{sourcesdir}/extension/CustomWebListener.java[]
----

. Добавьте новый параметр `context-param` со ссылкой на созданный класс в файл `single-war-web.xml`:
+
[source, xml]
----
include::{sourcesdir}/extension/servlet_registration_single_war.xml[]
----
--