[[glossary]]
[glossary]
== Основные определения и понятия

[[artifact]]
*Артефакт*::
В контексте данного руководства под артефактом понимается файл (обычно JAR или ZIP), содержащий исполняемый или другой код, получившийся в результате сборки проекта. Артефакт имеет соответствующее некоторым правилам имя и версию, и может хранится в репозитории артефактов.

*БД*::
Реляционная база данных

[[browser_glossentry]]
*Браузер сущностей*::
Экранная форма, на которой размещается таблица со списком сущностей, а также кнопки создания, редактирования, удаления сущности.

[[dependency_injection]]
*Внедрение зависимости*::
Известно также как принцип Inversion Of Control (IoC). Механизм для получения ссылок на используемые объекты, при котором объект только декларирует, от каких объектов он зависит, а контейнер создает нужные объекты и инжектирует в зависимый объект. 

+
См. link:$$http://ru.wikipedia.org/wiki/%D0%92%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8$$[http://ru.wikipedia.org/wiki/Внедрение_зависимости]

*Главный пакет сообщений*::
См. <<main_message_pack,>>

[[lazy_loading_glossterm]]
*Загрузка по требованию*::
См. <<lazy_loading,>>

*Источник данных*::
См. <<datasources,>>

[[container]]
*Контейнер*::
Контейнер управляет жизненным циклом и конфигурацией программных объектов. Является базовым компонентом технологии Dependency Injection (или Inversion of Control).

+
В платформе CUBA используется контейнер *Spring Framework*. Для получения более подробной информации см. <<additional_info,>> 

[[screen_controller_glossentry]]
*Контроллер экрана*::
`Java` класс, содержащий логику инициализации и обработки событий экрана. Связан с XML-дескриптором экрана.

+
См. <<screen_controller,>>

[[local_attribute]]
*Локальный атрибут*::
Атрибут сущности, не являющийся ссылкой или коллекцией ссылок на другую сущность. Значения всех локальных атрибутов сущности, как правило, хранятся в одной таблице (исключение составляют некоторые стратегии наследования сущностей). 

*Пакет локализованных сообщений*::
См. <<message_packs,>>

[[persistence_context]]
*Персистентный контекст*::
Набор экземпляров сущностей, загруженных из базы данных или только что созданных. Персистентный контекст является кэшем данных в рамках текущей транзакции. При коммите транзакции все изменения сущностей в персистентном контексте сохраняются в БД. 

+
См. <<entityManager,>>

*Представление*::
См. <<views,>>

*Рабочий каталог*::
Локальный каталог файловой системы, в котором содержится проект приложения. Содержит скрипты сборки `build.gradle`, `settings.gradle` и проектные файлы *IDE*.

+
См. <<chapter_development,>> 

[[artifact_repository]]
*Репозиторий артефактов*::
Сервер, осуществляющий хранение артефактов в определенной структуре. В процессе сборки некоторого проекта из репозитория загружаются артефакты, от которых зависит данный проект.

[[entity]]
*Сущность*::
Основной элемент модели данных, см. <<data_model,>>

[[eager_fetching]]
*Жадная загрузка*::
Загрузка данных подклассов и связанных объектов одновременно с основной запрашиваемой сущностью.

*Application Tiers*::
См. <<app_tiers,>>

[[app_properties_glossentry]]
*Application Properties*::
Свойства приложения − именованные данные различных типов, определяющие всевозможные аспекты конфигурации и функционирования приложения.

*Application Units*::
См. <<app_tiers,>>

*Datasource*::
См. <<datasources,>>

*Eager Fetching*::
*EntityManager*::
Программный компонент среднего слоя, служащий для работы с персистентными <<data_model,сущностями>>.

+
См. <<entityManager,>>

[[interceptor]]
*Interceptor*::
Элемент AOP (Aspect Oriented Programming), позволяющий изменить или расширить обычный вызов метода объекта.

+
См. link:$$http://en.wikipedia.org/wiki/Interceptor_pattern$$[http://en.wikipedia.org/wiki/Interceptor_pattern]

[[javaee_web_profile]]
*Java EE Web Profile*::
Упрощенный профиль Java Enterprise Edition, разработанный для веб-приложений, для которых не требуются такие технологии как EJB, JTA и т.д.

[[jmx]]
*JMX*::
Java Management Extensions − технология, которая предоставляет инструменты для управления приложениями, объектами системы, устройствами. Определяет стандарт для написания JMX-компонентов − <<jmx_beans,MBeans>>. 

+
Более подробную информацию можно найти по адресу: link:$$http://www.oracle.com/technetwork/java/javase/tech/javamanagement-140525.html$$[http://www.oracle.com/technetwork/java/javase/tech/javamanagement-140525.html]

+
См. также <<jmx_tools,>>

[[jpa]]
*JPA*::
Java Persistence API - стандартная спецификация технологии объектно-реляционного отображения (<<orm,ORM>>). В платформе CUBA используется фреймворк *Apache OpenJPA*, реализующий эту спецификацию.

[[jpql]]
*JPQL*::
Платформо-независимый объектно-ориентированный язык запросов, определенный как часть спецификации JPA. 

+
Более подробную информацию можно найти по адресу: link:$$http://openjpa.apache.org/builds/2.2.0/apache-openjpa/docs/jpa_langref.html$$[http://openjpa.apache.org/builds/2.2.0/apache-openjpa/docs/jpa_langref.html]

*Lazy loading*::
См. <<lazy_loading,>>

*Managed Beans*::
Программные компоненты *Middleware*, содержащие бизнес-логику приложения.

+
См. <<managed_beans,>>

*MBeans*::
<<managed_beans,Managed Beans>>, имеющие JMX-интерфейс. Как правило, имеют внутреннее состояние (например, кэш, конфигурационные данные или статистику), к которому нужно обеспечить доступ через JMX.

[[middleware_glossentry]]
*Middleware*::
Средний слой − <<app_tiers,уровень>> приложения, содержащий бизнес-логику, работающий с базой данных, и предоставляющий общий интерфейс для верхних (клиентских) уровней приложения.

[[optimistic_locking]]
*Optimistic locking*::
Оптимистичная блокировка - способ управления совместным доступом к данным различными пользователями, при котором предполагается, что возможность одновременного изменения ими одного и того же экземпляра сущности мала. В этом случае блокировка как таковая отсутствует, вместо нее в момент сохранения изменений производится проверка, нет ли в БД более новой версии данных, сохраненной другим пользователем. Если есть, выбрасывается исключение, и текущий пользователь должен снова загрузить данный экземпляр сущности.

+
См. также link:$$http://en.wikipedia.org/wiki/Optimistic_concurrency_control$$[http://en.wikipedia.org/wiki/Optimistic_concurrency_control]

*ORM*::
Object-Relational Mapping - объектно-реляционное отображение - технология связывания таблиц реляционной базы данных с объектами языка программирования. 

+
См. <<orm,>>

[[pojo]]
*POJO*::
Plain Old Java Object − «простой Java-объект в старом стиле» − Java-объект, не унаследованный ни от какого специфического класса и не реализующий никаких служебных интерфейсов сверх тех, которые нужны для описания бизнес-логики. 

*Services*::
Сервисы среднего слоя предоставляют интерфейс для вызова бизнес-логики клиентами и образуют границу *Middleware*. Сервисы могут содержать бизнес-логику внутри себя, либо делегировать выполнение <<managed_beans,Managed Beans>>.

+
См. <<services,>>

[[sso]]
*Single Sign-On, SSO*::
Технология, при использовании которой пользователь переходит от одного приложения к другому без повторной аутентификации. Интеграция CUBA-приложения с <<ldap,Active Directory>> позволяет пользователям *Windows* входить в приложение без ввода имени и пароля.

*Soft deletion*::
См. <<soft_deletion,>>

*UI*::
User Interface - пользовательский интерфейс

*View*::
См. <<views,>>

[[screen_xml_glossentry]]
*XML-дескриптор*::
Файл в формате XML, содержащий описание <<datasources,источников данных>> и расположения визуальных компонентов экрана.

+
См. <<screen_xml,>>

