[[introduction]]
== Введение

В данной главе приводятся сведения о назначении и возможностях платформы CUBA. 

[[overview]]
=== Обзор платформы

Платформа CUBA предназначена для разработки корпоративных решений, характеризующихся сложной моделью данных, десятками или сотнями экранов, большим количеством бизнес-логики, а также требованиями к контролю прав доступа, масштабируемости и отказоустойчивости.

Широкий набор готовой функциональности, развитые средства генерации кода, визуальный дизайнер интерфейсов, а также поддержка hot deploy радикально сокращают время и стоимость разработки решения.

Платформа полностью построена на стеке открытых Java технологий, что позволяет использовать наработки крупнейшей экосистемы свободного ПО в мире, а также контролировать исходный код всего стека.

Открытая архитектура позволяет переопределять поведение большинства механизмов платформы, обеспечивая высокую гибкость. Разработчики могут использовать популярные Java IDE и имеют полный доступ к исходному коду.

Приложения на платформе легко встраиваются в ИТ-инфраструктуру благодаря поддержке основных баз данных и серверов приложений, а также возможности работы в облаке. Платформа позволяет обеспечить отказоустойчивость и масштабируемость решений и предоставляет средства интеграции с внешними системами.

[[hardware_requirements]]
=== Технические требования

*Минимальные требования* для ведения разработки на платформе CUBA:

* Оперативная память - 4 ГБ.

* Место на жестком диске - 5 ГБ.

* Операционная система - *Microsoft Windows*, *Linux* или *Mac OS X*.

[[release_notes]]
=== Release Notes

Список изменений в платформе доступен по адресу http://files.cuba-platform.com/cuba/platform/platform-{revnumber}-changelog.html.
