[[chapter_introduction]]
== Введение

В данной главе приводятся сведения о назначении и возможностях платформы CUBA. 

[[overview]]
=== Обзор платформы

*Ключевые особенности*

* Использование платформы *Java*, а, следовательно, возможность работы под управлением практически любых операционных систем на серверах и рабочих станциях

* Полностью открытый исходный код

* Независимость от специфики СУБД

* Создаваемые на базе платформы приложения легко могут быть развернуты в отказоустойчивой конфигурации.

* Наличие эффективных средств разработки <<gui_framework,пользовательского интерфейса>> с помощью только *Java* и *XML*.

* Мощные средства <<chapter_security,разграничения прав доступа>> пользователей к информации с возможностью настройки в работающем приложении.

* Встроенный механизм создания и генерации отчетов с выводом в форматы офисных документов и PDF (см. руководство *Генератор отчетов*).

* Механизм создания и выполнения бизнес-процессов с интегрированным визуальным редактором процессов (см. руководство *Business Process Management*).

* Полнотекстовый поиск по атрибутам <<entity,сущностей>> и по содержимому загруженных файлов (см. руководство *Полнотекстовый поиск*).

* Возможность отображения диаграмм, в том числе, диаграммы Ганта (см. руководство *Отображение диаграмм*).

* Встроенный <<rest_api,REST API>> с передачей данных в форматах XML или JSON для быстрой интеграции со сторонними приложениями.

* <<extension,Механизм создания расширений функциональности>>, позволяющий адаптировать тиражируемые продукты для конкретных заказчиков, не затрудняя при этом обновления версий продуктов.

* <<cubaStudio_install,CUBA Studio>> - инструмент быстрой разработки на платформе. Studio включает в себя средства создания нового проекта, описания модели данных, визуальный редактор экранов и других элементов проекта. Использование Studio не исключает возможности программирования в классической Java IDE, тем самым достигается максимальная эффективность при работе над проектом с помощью обоих инструментов:

** Studio используется для быстрого старта проекта, визуального создания модели данных и компоновки экранов UI;

** Java IDE используется для программирования бизнес-логики и обработки событий UI.
+
CUBA Studio содержит средства для взаимодействия с *IntelliJ IDEA* и *Eclipse*, позволяющие быстро переходить из Studio в IDE и обратно. 

*Преимущества использования платформы CUBA*

* Система, строящаяся на платформе, приобретает эффективную архитектуру, опробованную на множестве приложений, созданных компанией *Haulmont* и другими разработчиками.

* Декларативный подход к созданию пользовательского интерфейса имеет следующие преимущества:

** абстрагирует разработчика от сложностей разнородных технологий (HTML/JavaScript, Swing, и т.п.)

** четко разделяет визуальное расположение и логику инициализации и реакции на события, облегчая понимание и изменение кода.

* Созданные таким образом экраны одинаково работоспособны в обоих типах клиентов, поддерживаемых платформой: веб и десктоп, что позволяет с минимумом усилий создавать системы, использующие преимущества веб-интерфейса и/или настольных приложений.

* Платформой предоставляется готовая функциональность на следующих уровнях:

** Системный уровень

*** Инфраструктура и средства организации бизнес-логики на <<middleware,среднем слое>>.

*** <<gui_vcl,Библиотека визуальных компонентов>> и инфраструктура клиентского уровня.

*** Средства работы с параметрами конфигурации и <<localization,локализованными сообщениями>>.

*** Средства выполнения <<background_tasks,фоновых задач>> пользовательского интерфейса.

*** Механизмы запуска на среднем слое <<scheduled_tasks,задач по расписанию>>.

*** Возможность применения <<dynamic_attributes,динамических атрибутов>>, позволяющих задавать новые атрибуты сущностей на этапе настройки и эксплуатации системы.

** Прикладной уровень

*** Подсистема безопасности.

*** Подсистема генерации отчетов.

*** Подсистема работы с бизнес-процессами.

*** Полнотекстовый поиск.

*** Механизм надежной асинхронной <<email_sending,рассылки email>>.

*** <<entity_log,Средства ведения журнала аудита>> изменений сущностей и <<entity_snapshots, сохранения версий>>.

** Уровень развертывания

*** Возможность работы в отказоустойчивой конфигурации.

*** Готовые средства <<rest_api,интеграции со сторонними приложениями>>.

*** Возможность независимого создания <<extension,расширений>> основного продукта для адаптации под конкретного заказчика.

* Функциональность платформы позволяет значительно сократить сроки разработки и удешевить проект.

* Для создания веб-клиента приложения на основе CUBA не обязательно хорошее знание классических веб-технологий: HTML, CSS, JavaScript.

[[hardwareRequirements]]
=== Технические требования

*Минимальные требования* для ведения разработки на платформе CUBA:

* Оперативная память - 4 ГБ.

* Место на жестком диске - 5 ГБ.

* Операционная система - *Microsoft Windows*, *Linux* или *Mac OS X*.

[[releaseNotes]]
=== Release Notes

Список изменений в платформе доступен по адресу http://files.cuba-platform.com/cuba/platform/platform-6.0-changelog.html.
