= Платформа CUBA. Руководство по разработке приложений
:toc: left
:toc-title: Содержание
:appendix-caption: Приложение
:toclevels: 6
:sectnumlevels: 6
:linkcss:
:stylesheet: cuba.css
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: ru
:revnumber: 6.7
:version-label: Версия
:revremark: Copyright (c) 2017 Haulmont (www.haulmont.com)
:gradleVersion: 3.4
:figure-caption: Рисунок
:xsd_url: http://schemas.haulmont.com/cuba/{revnumber}
:fts_man_url: https://doc.cuba-platform.com/fts-{revnumber}-ru


:!sectnums:

[[preface]]
== Предисловие

Данное руководство содержит справочную информацию по платформе CUBA и охватывает наиболее важные темы разработки бизнес-приложений на платформе.

Для успешной работы с платформой требуется знание следующих технологий:

* Java Standard Edition

* Реляционные базы данных (SQL, DDL)

Для глубокого понимания принципов работы платформы полезным является знакомство со следующими технологиями и фреймворками:

* link:https://docs.gradle.org/{gradleVersion}/userguide/userguide.html[Gradle] build system

* link:$$http://projects.spring.io/spring-framework$$[Spring Framework]

* link:$$http://en.wikipedia.org/wiki/Java_Persistence_API$$[Java Persistence API]

* link:$$https://vaadin.com/book$$[Vaadin] web applications framework

* HTML / CSS / JavaScript

* Java Servlets

Настоящее руководство, а также другая документация по платформе CUBA, доступны по адресу link:https://www.cuba-platform.ru/manual[www.cuba-platform.ru/manual]. Обучающие видео-материалы и презентации располагаются по адресу link:https://www.cuba-platform.ru/tutorials[www.cuba-platform.ru/tutorials]. Онлайн демо-приложения могут быть запущены со страницы link:https://www.cuba-platform.ru/online-demo[www.cuba-platform.ru/online-demo].

Если у Вас имеются предложения по улучшению данного руководства, обратитесь пожалуйста в службу поддержки по адресу link:https://www.cuba-platform.ru/support[www.cuba-platform.ru/support]. При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска.

:sectnums:

include::introduction.adoc[]

include::setup.adoc[]

include::quick_start.adoc[]

include::cookbook.adoc[]

[[framework]]
== Устройство платформы

Данная глава содержит подробное описание архитектуры, компонентов и механизмов платформы.

include::architecture.adoc[]

include::common.adoc[]

include::dbms.adoc[]

include::middleware.adoc[]

include::gui.adoc[]

include::polymer.adoc[]

include::portal.adoc[]

include::rest.adoc[]

include::features.adoc[]

include::extension.adoc[]

include::development.adoc[]

include::deployment.adoc[]

include::database.adoc[]

include::security.adoc[]

include::config_files.adoc[]

include::app_properties.adoc[]

include::system_properties.adoc[]

include::glossary.adoc[]

