[[polymer_ui]]
=== Пользовательский интерфейс на Polymer

Клиентский блок пользовательского интерфейса на Polymer предоставляет возможность быстрого создания front-end порталов
с mobile-first responsive веб-интерфейсом. Он основан на фреймворке https://www.polymer-project.org[Google Polymer]
и обеспечивает тесную интеграцию с мобильными браузерами для добавления веб-приложений на home screen устройства
и для работы оффлайн.

Polymer UI платформы CUBA имеет следующие особенности:

* Система сборки Polymer полностью интегрирована в систему сборки проекта, основанную на Gradle, так что все инструменты сборки загружаются и устанавливаются автоматически. В то же время, после создания в проекте модуля Polymer, front-end разработчики могут продолжить работу над ним, используя стандартные инструменты Polymer.

* Платформа предоставляет набор веб-компонентов для работы с middleware через стандартный <<rest_api_v2,REST API>>. См. описание компонентов <<cuba_web_components,ниже>>.

* CUBA Studio позволяет быстро создать клиентский модуль Polymer и генерировать код веб-компонентов приложения по модели данных проекта. Studio содержит обширный и расширяемый набор шаблонов для генерации компонентов, работающих с сущностями модели данных.

На данный момент наш подход заключается в максимальном использовании https://www.polymer-project.org/1.0/start/toolbox/set-up[методов и инструментов]
предоставляемых командой Polymer для создания https://developers.google.com/web/progressive-web-apps/[Progressive Web Apps].
Мы стараемся не отходить далеко от примеров и практик описанных в документации Polymer чтобы снизить порог вхождения
и унифицировать процесс изучения технологии.
Приложения на базе Polymer не только используют https://www.webcomponents.org/[Веб-компоненты]
но и сами состоят из них.

По умолчанию, Studio генерирует пользовательский интерфейс на основе https://www.webcomponents.org/collection/PolymerElements/paper-elements[paper-elements]
- набора элементов от Polymer, который построен на принципах http://www.google.com/design/spec/material-design/introduction.html[material design] от Google.
Также можно использовать и другие компоненты, создав для них свои шаблоны в Studio.

Для эффективной разработки необходимо ознакомиться с основнами Polymer: https://github.com/Polymer/polymer/tree/1.x#polymer-in-1-minute.
Предпочтительнее изучить тему глубже: https://www.polymer-project.org/1.0/start.
Так как Polymer строится вокруг Web стандартов, изучая его, вы, во многом, изучаете саму Веб платформу.

[[polymer_requirements]]
==== Требования
http://git-scm.com/downloads[Git] должен быть установлен и доступен из командной строки.
Он необходим для https://bower.io/[bower] - системы управления пакетами для front-end приложений.


[[polymer_supported_browsers]]
==== Поддерживаемые браузеры
См. список поддерживаемых браузеров на https://www.polymer-project.org/1.0/docs/browsers[сайте Polymer].

[WARNING]
====
Не рекомендуется использовать Polymer-клиент если в вашем проекте требуется поддержка устаревших браузеров.
====

[[polymer_in_studio]]
==== Polymer UI в Studio

Для добавления в проект клиентского модуля Polymer, откройте его в CUBA Studio и нажмите *Create module > Create polymer client module* на вкладке *Project Properties* навигатора. Studio создаст модуль *polymer-client* и сконфигурирует соответствующим образом `build.gradle`. Модуль будет содержать заглушку приложения, которая позволяет подключаться к REST API и выполнять login и logout пользователя в middleware.

После создания модуля, запустите сервер приложения и откройте `++http://localhost:8080/app-front++` в веб-браузере. Вы увидите форму логина. После успешного входа будет отображено главное окно с вертикальным меню и responsive дизайном.

Для создания экрана UI, работающего с сущностью, выберите сущность в навигаторе Studio и нажмите *New > Polymer UI component*. Выберите шаблон (например, *Entity cards list with editor*), заполните свойства шаблона и нажмите *Create*. Веб-компонент будет сгенерирован и добавлен в меню приложения. Studio обеспечивает hot-deploy компонентов Polymer, так что вам необходимо лишь обновить страницу в браузере и вы увидите в меню элемент, вызывающий только-что созданный экран.

[[polymer_build_and_structure]]
==== Структура Проекта и Система Сборки
В системе сборки Polymer-клиента используются следующие инструменты:

* https://nodejs.org/en/[Node.js]
* https://bower.io/[bower]
* http://gulpjs.com/[gulp]
* https://github.com/Polymer/polymer-build[polymer-build]

По умолчанию, установкой и запуском этих инструментов занимается Gradle, однако можно использовать их и напрямую, см. <<polymer_tools,Использование нативных инструментов Polymer>>.

[[polymer_directory_structure]]
===== Структура папок

----
polymer-client/
|-- src/
|   |-- app-shell.html
|   |-- shared-styles.html
|-- images
|   |-- app-icon/
|   |-- favicon.ico
|-- .gitignore
|-- bower.json
|-- gulpfile.js
|-- index.html
|-- manifest.json
|-- package.json
|-- polymer.json
|-- service-worker.js
|-- sw-precache-config.js
----

src:: Директория содержашая веб-компоненты.

package.json:: Список модулей Node.js, используемых при сборке.

bower.json:: Список зависимостей используемых в самом приложении (преимущественно Веб-компоненты).

polymer.json:: https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build[Конфигурация сборки] Polymer.

gulpfile.js:: Build-файл http://gulpjs.com/[Gulp]. В него можно добавить дополнительную обработку, например,
минификацию. Больше информации здесь: https://github.com/Polymer/polymer-build#polymerproject.

index.html:: Входная точка приложения. Содержит логику загрузки полифилов и импорт <appname>-shell.html.

manifest.json:: Web app manifest. Содержит информацию, используемую при добавлении приложения на домашний экран
мобильного устройства. Больше информации здесь: https://developer.mozilla.org/en-US/docs/Web/Manifest

service-worker.js:: Заглушка Service worker.

sw-precache-config.js:: Файл конфигурации, используемый библиотекой https://github.com/GoogleChrome/sw-precache[sw-precache]
для генерации service worker при сборке. По умолчанию отключено. См. <<polymer_offline>>.

[[polymer_hot_deploy]]
===== Hot Deploy
При запуске и развёртывании приложений из CUBA Studio или с помощью gradle система сборки упакует компоненты в бандлы в
соответствии конфигурацией в `polymer.json`. По умолчанию, всё приложение упаковывается в один файл
`<appname>-shell.html`. Если проект запущен, то при изменении компонентов Studio автоматически копирует их в Tomcat.
Также она заменит собраный бандл `<appname>-shell.html` на его исходную версию, чтобы подтягивались изменения
в отдельных компонентах. Необходимо обратить на это внимание при развёртывании приложений в production напрямую
из `tomcat/webapps`.

[[polymer_tools]]
===== Использование Нативных Инструментов Polymer

Вы можете использовать нативный инструментарий фреймворка Polymer.
Это может быть удобно, если над проектом работает отдельная команда front-end разработчиков.
В этом случае, в системе должен быть установлен `Node.js`.
Установите `bower` и `gulp` глобально:

[source]
----
npm install bower gulp-cli -g
----

Теперь вы можете собирать и запускать веб-приложение без Gradle:

[source]
----
cd modules/polymer-client
npm install
bower install
gulp serve
----

Чтобы запускать приложение на dev сервере Polymer вместо Tomcat внесите следующие изменения:

* Откройте `modules/polymer-client/index.html` и измените элемент `base`, как показано ниже:
+
[source,html]
----
<base href="/">
----

* Откройте `modules/polymer-client/src/<appname>-shell.html` на редактирование и измените элемент `cuba-app`, как показано ниже:
+
[source,html]
----
<cuba-app api-url="http://localhost:8080/app/rest/" on-cuba-token-expired="_handleTokenExpired"></cuba-app>
----

Теперь приложение будет доступно по адресу `++http://localhost:8081++`, а доступ к его REST API будет осуществляться по `++http://localhost:8080/app/rest/++`.

[[cuba_web_components]]
==== Веб-компоненты CUBA

Подробный справочник по API CUBA-элементов находится https://cuba-elements.github.io/cuba-elements/[здесь].

[[polymer_inintialization]]
===== Инициализация
Для того, чтобы использовать `cuba-` элементы, необходимо инициализировать подключение к REST API с помощью элемента `cuba-app`:

[source,html]
----
<cuba-app api-url="/app/rest/"></cuba-app>
----

Его необходимо добавить один раз в ваше приложение как можно раньше.
Нельзя изменять свойства элемента динамичаески а также удалять элемент после инициализации.

[[polymer_working_with_data]]
===== Работа с Данными

Для загрузки данных просто поместите элементы https://cuba-elements.github.io/cuba-elements/components/cuba-data/[cuba-data]
в HTML и укажите требуемые атрибуты.

*Загрузка Сущностей*

Используйте https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entities[cuba-entities] для загрузки сущностей.
Если указаны атрибуты `entity-name` и `view`, элемент загрузит список сущностей и передаст его для привязки данных в
Polymer через свойство `data`:

[source,html]
----
<cuba-entities entity-name="sec$User" view="_local" data="{{users}}"></cuba-entities>
----

Теперь отобразить данные можно очень просто:

[source,html]
----
<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----

*Использование предопределенных JPQL запросов*

Составьте запрос, как описано <<rest_api_v2_queries_config,здесь>>.

Используйте элемент https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-query[cuba-query] для получения результатов запроса.
При необходимости в запрос можно передать параметры с помощью свойства `params`:

[source,html]
----
<cuba-query id="query"
            auto="[[auto]]"
            entity-name="sec$User"
            query-name="usersByName"
            data="{{users}}">
</cuba-query>

<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----

*Вызов Сервиса*

Зарегистрируйте сервис и его методы, как описано <<rest_api_v2_services_config,здесь>>.
Используйте элемент https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-service[cuba-service] для вызова метода:

[source,html]
----
<cuba-service service-name="cuba_ServerInfoService"
              method="getReleaseNumber"
              data="{{releaseNumber}}"
              handle-as="text"></cuba-service>

Release number: [[releaseNumber]]
----

*Создание Сущности*

С помощью элементов `cuba-entity-form` и `cuba-service-form` можно легко отправлять данные на backend.

В примере ниже мы связываем объект `user`, который нужно сохранить, со свойством `entity`.

[source,html]
----
<cuba-entity-form id="entityForm"
                  entity-name="sec$User"
                  entity="[[user]]"
                  on-cuba-form-response="_handleFormResponse"
                  on-cuba-form-error="_handleFormError">

  <label>Login: <input type="text" name="login" value="{{user.login::input}}"></label>
  <label>Name: <input type="text" name="login" value="{{user.name::input}}"></label>

  <button on-tap="_submit">Submit</button>

</cuba-entity-form>

<paper-toast id="successToast">Entity created</paper-toast>
<paper-toast id="errorToast">Entity creation error</paper-toast>
----

[source,javascript]
----
_submit: function() {
  this.$.entityForm.submit();
},
_handleFormResponse: function() {
  this.user = getUserStub();
  this.$.successToast.open();
},
_handleFormError: function() {
  this.$.errorToast.open();
}
----

[TIP]
====
Необходимо разрешить <<rest_api_v2_anonymous,анонимный доступ>> к REST API, если вы хотите использовать
приведённые выше примеры без обязательного входа в систему.
====


[[polymer_styling]]
==== Настройка Стилей
Ознакомьтесь с Polymer's https://www.polymer-project.org/1.0/docs/devguide/styling[styling guide].
Основное отличие от традиционного подхода состоит в способе описания глобальных стилей. Так как в элементах Polymer используется Shadow DOM,
глобальные стили не работают внутри компонентов. Вместо этого необходимо использовать
https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules[style-modules].
Для описания общих стилей используйте фаил `shares-styles.html` который импортируется во все компоненты приложения.

[[polymer_offline]]
==== Использование Offline

[WARNING]
====
Экспериментальная технология!

Ещё не все браузеры поддерживают технологии из списка ниже (к примеру, service workers [пока не поддерживаются](https://jakearchibald.github.io/isserviceworkerready) в Safari).
====

В настоящее время мы рекомендуем вместе с Polymer использовать технологии https://developers.google.com/web/progressive-web-apps/[Progressive Web Applications], такие как https://developer.mozilla.org/en-US/docs/Web/Manifest[web app manifest] https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/[2], чтобы добиться *native-like* присутствия на домашнем экране пользователя. См. файл `manifest.json` в модуле клиента Polymer.

Существуют два основных подхода:

* Service Workers используется преимущественно для кеширования самого приложения. См. файл `sw-precache-config.js`, сгенерированный  при создании Polymer клиента. Чтобы разрешить генерацию service worker, измените команду `assemble` модуля Polymer следующим образом:
```
    ...
    task assemble(type: NodeTask, dependsOn: installBowerPackages) {
        script = file("node_modules/gulp/bin/gulp.js")
        args = ['build-sw']
    ...
```
Больше информации о том, как настроить и использовать service workers, вы можете найти https://www.polymer-project.org/1.0/toolbox/service-worker[здесь].

* https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage[Local storage] и
https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API[Indexed DB], используемые для локального хранения данных. Примеры использования этой функциональности в соответствуюших элементах Polymer:
https://elements.polymer-project.org/elements/app-storage?active=app-localstorage-document[app-localstorage-document]
https://elements.polymer-project.org/elements/app-storage?active=app-indexeddb-mirror[app-indexeddb-mirror].


[[polymer_troubleshooting]]
==== Возможные проблемы
Proxy::
Для работы через прокси может потребоваться соответствующая конфигурация `bower` и `npm`.
Чтобы разрешить `bower и `npm` работать через прокси, создайте следующие файлы в папке `modules/polymer-client/`:

 .bowerrc
[source,json]
----
{
    "proxy":"http://<user>:<password>@<host>:<port>",
    "https-proxy":"http://<user>:<password>@<host>:<port>"
}
----

 .npmrc
[source]
----
proxy=http://<user>:<password>@<host>:<port>
https-proxy=http://<user>:<password>@<host>:<port>
----