[[portal]]
=== Компоненты портала

В данном руководстве _порталом_ называется клиентский <<app_tiers,блок>>, способный решать следующие задачи:

* предоставлять альтернативный веб-интерфейс, как правило, предназначенный для пользователей за пределами организации;

* предоставлять интерфейс для интеграции с мобильными приложениями и со сторонними системами.

Конкретное приложение может содержать несколько портальных модулей, предназначенных для различных целей, например, в случае приложения, автоматизирующего бизнес такси, это может быть публичный веб-сайт для клиентов, интеграционный модуль мобильного приложения заказа такси, интеграционный модуль мобильного приложения водителей, и т.д. 

<<base_projects,Базовый проект>> *cuba* платформы содержит в своем составе модуль *portal*, который является заготовкой для создания порталов в проектах. Он, во-первых, предоставляет базовую функциональность клиентского блока для работы с *Middleware*, а во-вторых, включает в себя универсальный <<rest_api,REST API>> для работы с сущностями.

[[portal_basic_func]]
==== Базовая функциональность

Рассмотрим основные компоненты, предоставляемые платформой для построения портала.

* `PortalAppContextLoader` - загрузчик `
              <<appContext,AppContext>>
            `, должен быть зарегистрирован в элементе `listener` файла `web.xml`.

* `PortalDispatcherServlet` - центральный сервлет, распределяющий запросы по контроллерам *Spring MVC*, как для веб-интерфейса, так и для REST API. Набор файлов конфигурации контекста Spring определяется свойством приложения `
              <<cuba.dispatcherSpringContextConfig,cuba.dispatcherSpringContextConfig>>
            `. Данный сервлет должен быть зарегистрирован в `web.xml` и отображен на корневой URL веб-приложения.

* `App` - объект, содержащий информацию о текущем HTTP запросе и ссылку на объект `Connection`. Экземпляр `App` может быть получен в прикладном коде вызовом статического метода `App.getInstance()`.

* `Connection` - позволяет выполнять логин и логаут пользователя на *Middleware*.

* `PortalSession` - специфичесий для портала объект <<userSession,пользовательской сессии>>. Возвращается интерфейсом инфраструктуры `
              <<userSessionSource,UserSessionSource>>
            `, а также статическим методом `PortalSessionProvider.getUserSession()`.
+
Имеет дополнительный метод `isAuthenticated()`, возвращающий `true`, если данная сессия принадлежит неанонимному, т.е. явно зарегистрировавшемуся с логином и паролем, пользователю.
+
При первом обращении некоторого пользователя к порталу `SecurityContextHandlerInterceptor` создает для него (или привязывает уже имеющуюся) анонимную сессию, регистрируясь на *Middleware* с именем пользователя, указанным в свойстве приложения `
              <<cuba.portal.anonymousUserLogin,cuba.portal.anonymousUserLogin>>
            `. Регистрация производится методом `
              <<login,loginTrusted()>>
            `, поэтому в блоке портала необходимо установить также свойство `
              <<cuba.trustedClientPassword,cuba.trustedClientPassword>>
            `. Таким образом, любой анонимный пользователь портала может работать с сервисами *Middleware* с правами пользователя `cuba.portal.anonymousUserLogin`.
+
Если портал содержит страницу регистрации пользователя с именем и паролем, то после выполнения `Connection.login()` при обработке запросов `SecurityContextHandlerInterceptor` устанавливает в потоке выполнения пользовательскую сессию явно зарегистрированного пользователя, и работа с *Middleware* происходит от его имени.

* `PortalLogoutHandler` - обрабатывает навигацию на страницу логаута. Должен быть зарегистрирован в файле `portal-security-spring.xml` проекта.

Пример портала, содержащего страницу регистрации пользователей, включен в шаблон проекта, рассмотренный в <<qs_setup,>>

[[rest_api]]
==== REST API

Универсальный REST API платформы позволяет выполнять загрузку и сохранение любых сущностей модели данных приложения посредством отправки простых HTTP запросов. Это открывает возможность легкой интеграции со сторонними приложениями самого широкого спектра − от JavaScript кода, выполняющегося в браузере, до произвольных систем, работающих на Java, .NET, PHP или любой другой платформе. 

Основные возможности API:

* загрузка экземпляров сущностей из базы данных по идентификатору или по JPQL запросу с параметрами

* сохранение новых и измененных экземпляров, удаление экземпляров

* получение описания модели данных в формате HTML

* представление данных в форматах JSON и XML на выбор

* аутентификация пользователя

* вызов сервисов среднего слоя.

Все функции работают с данными в кодировке UTF-8. 

[[rest_api_adding]]
===== Включение в проект

REST API реализован в модуле *portal* базового проекта *cuba*, поэтому для его использования необходимо создать модуль *portal* в проекте приложения. Простейший способ сделать это - использовать команду *Create portal module* панели *Project properties* навигатора <<cubaStudio_install,CUBA Studio>>.

Основные элементы настройки:

* Добавить контроллеры REST API в контекст Spring, определяемый файлом `
                <<dispatcher-spring.xml,portal-dispather-spring.xml>>
              `:
+
[source, xml]
----
<context:component-scan base-package="com.haulmont.cuba.portal.restapi"/>
----

* Установить режим доступа в `portal-security-spring.xml`:
+
[source, xml]
----
<intercept-url pattern="/api/**" access="IS_AUTHENTICATED_ANONYMOUSLY"/>
----

[[rest_api_func]]
===== Описание функций

При стандартных настройках модуля *portal* все запросы к REST API должны иметь URL, начинающийся с `{host:port}/app-portal/api`.

Все функции требуют наличия сессии аутентифицированного пользователя, то есть сначала необходимо выполнить логин, и передавать полученный идентификатор сессии в последующие запросы.

[[rest_api.login]]
====== Логин

Логин можно выполнить либо GET, либо POST запросом.

GET запрос:: 
+
--
В случае GET запроса сформируйте URL `{host:port}/app-portal/api/login` с параметрами:

* *u* − логин пользователя

* *p* − пароль пользователя

* *l* − локаль пользователя (опционально)

Например:

[source]
----
http://localhost:8080/app-portal/api/login?u=admin&p=admin&l=ru
----

--

POST запрос:: 
+
--
Для выполнения логина через POST необходимо выполнить запрос по адресу `{host:port}/app-portal/api/login`, при этом в теле запроса передается JSON (заголовок `Content-Type` имеет значение `application/json`) или форма (заголовок `Content-Type` имеет значение `application/x-www-form-urlencoded`)

Пример формата JSON:

[source, json]
----
{
  "username" : "admin",
  "password" : "admin",
  "locale" : "en"
}
----

Пример формы:

[source]
----
username: admin
password: admin
locale: en
----

--

В ответ сервис вернет `userSessionId` в теле ответа и статус 200, либо статус 401, если аутентификация не удалась.

Чтобы иметь возможность входить через REST API, пользователь должен иметь специфическое <<permissions,разрешение>> `cuba.restApi.enabled`. Заметьте, что пользователь будет иметь разрешение если ни одна <<roles,роль>> явно не отбирает его.

[[rest_api.logout]]
====== Логаут

Логаут также можно выполнить либо GET, либо POST запросом.

GET запрос:: 
+
--
В случае GET запроса сформируйте URL `{host:port}/app-portal/api/logout` с параметром *session* - идентификатором текущей сессии, полученным вызовом `login`.

Например:

[source]
----
http://localhost:8080/app-portal/api/logout?session=64f7d59d-2cf5-acfb-f4d3-f55b7882da72
----

--

POST запрос:: 
+
--
Для выполнения логина через POST необходимо выполнить запрос по адресу `{host:port}/app-portal/api/logout`, при этом в теле запроса передается JSON (заголовок `Content-Type` имеет значение `application/json`) или форма (заголовок `Content-Type` имеет значение `application/x-www-form-urlencoded`)

Пример формата JSON:

[source, json]
----
{
  "session" : "64f7d59d-2cf5-acfb-f4d3-f55b7882da72"
}
----

Пример формы:

[source]
----
session: 64f7d59d-2cf5-acfb-f4d3-f55b7882da72
----

--

В ответ сервис вернет статус 200.

[[rest_api.find]]
====== Загрузка экземпляра персистентного объекта из базы данных по идентификатору

Для получения объекта необходимо выполнить GET запрос `{host:port}/app-portal/api/find.<format>?e=<entityRef>&s=<sessionId>` с параметрами:

* *e* − описание требуемого объекта в формате `<entity-id>` или `<entity-id-view>`(см. класс `EntityLoadInfo`), например, `++sales$Order-43c61345-d23c-48fe-ab26-567504072f05-_local++`. То есть формат позволяет указать требуемое <<views,представление>> загруженного объекта.

* *s* − идентификатор текущей сессии.

Элемент запроса *format* задает формат получения результата. Принимает два значения: `xml` или `json`.

Пример запроса, возвращающего результат в формате `xml`:

[source]
----
http://localhost:8080/app-portal/api/find.xml?e=sales$Order-60885987-1b61-4247-94c7-dff348347f93-orderWithCustomer&s=c38f6bf4-fae7-4ee6-a412-9d93ff243f23
----

Пример запроса, возвращающего результат в формате `json`

[source]
----
http://localhost:8080/app-portal/api/find.json?e=sales$Order-60885987-1b61-4247-94c7-dff348347f93-orderWithCustomer&s=c38f6bf4-fae7-4ee6-a412-9d93ff243f23
----

[[rest_api.query]]
====== Выполнение JPQL запроса для выборки данных

Для выполнения запроса необходимо выполнить GET запрос `++{host:port}/app-portal/api/query.<format>?e=<entity>&s=<sessionId>&q=<encoded query string>&param1=<value 1>$param1_type=<type 1>&paramN=<value N>&paramN_type=<type N>&view=<viewName>&firstResult=<firstResult>&maxResults=<maxResults>++` с параметрами:

* *e* − имя сущности

* *q* − строка запроса к данным на <<jpql,JPQL>>. Запрос может содержать параметры. Их значения указываются как значения одноименных параметров HTTP запроса.

* *s* − идентификатор текущей сессии

* *view* − опционально, <<views,представление>>, с которым требуется загружать данные

* *max* − опционально, максимальное количество строк возвращаемых данных (аналогично JPA `setMaxResults`)

* *first* − опционально, номер первой строки возвращаемых данных (аналогично JPA `setFirstResult`)

*format* задает формат получения результата. Принимает два значения: `xml` или `json`.

Например:

[source]
----
http://localhost:8080/app-portal/api/query.json?e=sales$Customer&q=select+c+from+sales$Customer+c&s=748e5d3f-1eaf-4b38-bf9d-8d838587367d&view=_local
----

[source]
----
http://localhost:8080/app-portal/api/query.json?e=sales$Customer&q=select+c+from+sales$Customer+c+where+c.name=:name&s=748e5d3f-1eaf-4b38-bf9d-8d838587367d&name=Петров
----

Для каждого из передаваемых параметров можно явно указать его тип, добавив в запрос одноименный параметр с суффиксом `++_type++`. Например:

[source]
----
http://localhost:8080/app-portal/api/query.json?e=sales$Customer&q=select+c+from+sales$Customer+c+where+c.name=:name&s=748e5d3f-1eaf-4b38-bf9d-8d838587367d&name=Петров&name_type=string
----

Указание типа параметра не является обязательным, но позволяет избежать ошибок парсинга, если система не сможет определить тип.

В общем случае тип стоит указывать лишь для строковых параметров, которые по какой-либо причине имеют формат более узких типов (дат, чисел, uuid), но должны интерпретироваться именно как строки.

Список доступных типов можно увидеть в описании мета-модели (пункт меню *Помощь* −> *Модель данных*) или получив <<getHTMLModel,HTML-описание модели>>.

[[rest_api.commit]]
====== Коммит новых и измененных экземпляров, удаление

Функция коммита позволяет выполнять операции над переданными ей объектами и возвращает их новое состояния. Формат результата определяется тем, какой формат (JSON или XML) был использован для запроса (заголовок `Content-Type`). 

Формат JSON:: 
+
--
В качестве заголовка `Content-Type` следует использовать значение `application/json`.

Создание сущности покупателя с автоматически сгенерированным идентификатором:

[source, json]
----
{
  "commitInstances": [{
      "id": "NEW-sales$Customer",
      "name": "Saltikov",
      "email": "saltikov@mail.com"
      }
  ]
}
----

Создание сущности покупателя с указанным идентификатором:

[source, json]
----
{
  "commitInstances": [{
      "id": "NEW-sales$Customer-b32a6412-d4d9-11e2-a20b-87b22b1460c7",
      "name": "Titov",
      "email": "titov@mail.com"
      }
  ]
}
----

Создание сущности заказа с указанием ссылки на новую сущность покупателя и заполнение атрибутами сущности данного покупателя:

[source, json]
----
{
  "commitInstances": [{
      "id": "NEW-sales$Order",
      "amount": 15,
      "customer":
          {"id": "NEW-sales$Customer-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff"
          }
      },{
          "id": "sales$Customer-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff",
          "name": "Dudkin",
          "email": "dudkin@mail.com"
         }
  ]
}
----

Изменение одновременно двух сущностей покупателей:

[source, json]
----
{
  "commitInstances": [{
        "id": "sales$Customer-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff",
        "email": "dudkin@mail.ru"
      },
      {
        "id": "sales$Customer-32261b09-b7f7-4b8c-88cc-6dee6fa8e6ab",
        "email": "saltikov@mail.ru"
      }
  ]
}
----

Удаление сущности покупателя с поддержкой <<soft_deletion,мягкого удаления>>:

[source, json]
----
{
  "removeInstances": [{
      "id": "sales$Customer-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff"
      }
  ],
  "softDeletion": "true"
}
----

* Массив `commitInstances` содержит создаваемые или изменяемые сущности. 

** При создании сущности в качестве значения поля `id` указывается значение `NEW-<entityName>` или `NEW-<entityName>-<entityId>`.

** При изменении сущности в качестве значения поля `id` указывается значение `<entityName>-<entityId>`.

** Далее в списке элементов через запятую указываются названия атрибутов создаваемой или изменяемой сущности и их значения.
+
Если при изменении сущности требуется установить какой-либо атрибут в `null`, то в идентификаторе необходимо указать также представление, включающее этот атрибут. Например:
+
[source, json]
----
{
  "commitInstances": [{
      "id": "sales$Customer-b32a6412-d4d9-11e2-a20b-87b22b1460c7-customer-edit",
      "name": "John Doe",
      "channel": null
      }
  ]
}
----

Здесь представление `customer-edit` должно содержать атрибут `channel`, в противном случае его значение не изменится. Для установки в `null` локального атрибута можно указать всегда доступное представление `++_local++`.

* Массив `removeInstances` содержит удаляемые объекты. При удалении объекта обязательно указывать значение поля `id`. Перед удалением будет выполнен `merge()` переданных объектов, что позволяет, например, проверить, не изменилась ли версия удаляемого объекта.

* Поле `softDeletion` управляет режимом <<soft_deletion,мягкого удаления>>.

Функция вызывается посредством POST обращения к `{host:port}/app-portal/api/commit?s=<sessionId>`. JSON передается в теле запроса. Функция возвращает массив объектов JSON. Например, при изменении поля `email` у сущности покупателя будет возвращен следующий массив объектов JSON:

[source, json]
----

[
   {"id":"sales$Customer-32261b09-b7f7-4b8c-88cc-6dee6fa8e6ab",
       "createTs":"2013-06-14T14:07:15.040",
       "createdBy":"admin",
       "deleteTs":null,
       "deletedBy":null,
       "email":"saltikovvvv@mail.ru",
       "name":"Saltikov",
       "updateTs":"2013-06-14T15:07:03.463",
       "updatedBy":"admin",
       "version":"3"
   }
]                   
----

--

Формат XML:: 
+
--
В качестве заголовка `Content-Type` следует использовать значение `text/xml`.

Пример формата XML

[source, xml]
----

<CommitRequest>
  <commitInstances>
      <instance id="sales$Order-9873c8a8-d4e7-11e2-85c0-33423bc08c84">
          <field name="date">2015-01-30</field>
          <field name="amount">3500.00</field>
          <reference name="customer" id="sales$Customer-32261b09-b7f7-4b8c-88cc-6dee6fa8e6ab"/>
      </instance>
  </commitInstances>
  <removeInstances>
      <instance id="sales$Customer-d67c10f0-4d28-4904-afca-4bc45654985d"/>
  </removeInstances>
  <softDeletion>true</softDeletion>
</CommitRequest>                 
----

Семантика полей XML-документа определяется в схеме link:$$http://schemas.haulmont.com/cuba/5.6/restapi-commit-v2.xsd$$[http://schemas.haulmont.com/cuba/5.6/restapi-commit-v2.xsd].

В случае запроса в формате XML установка поля в null осуществляется с помощью атрибута `null="true"`. Кроме того, в идентификаторе должно быть указано <<views,представление>>, содержащее данный атрибут. Например: 

[source, xml]
----

<CommitRequest>
    <commitInstances>
        <instance id="Order-9873c8a8-d4e7-11e2-85c0-33423bc08c84">
            <field name="amount" null="true"/>
            <reference name="customer" null="true"/>
        </instance>
    </commitInstances>
</CommitRequest>                        
----

Функция вызывается посредством POST запроса по адресу `{host:port}/app-portal/api/commit?s=<sessionId>`. XML передается в теле запроса. Запрос возвращает массив объектов XML вида

[source, xml]
----

<instances>
   <instance ...>
   <instance ...>
</instances>              
----

Схема, содержащая описание результата вызова функции, находится по адресу link:$$http://schemas.haulmont.com/cuba/5.6/restapi-instance-v2.xsd$$[http://schemas.haulmont.com/cuba/5.6/restapi-instance-v2.xsd]
--

[[rest_download_file]]
====== Загрузка файла из хранилища

Для загрузки файла из <<file_storage,FileStorage>> необходимо выполнить GET запрос `{host:port}/app-portal/api/download?f=<fileDescriptorId>&s=<sessionId>` с параметрами:

* *f* − идентификатор соответствующего экземпляра `FileDescriptor`.

* *s* − идентификатор текущей сессии.

[[getHTMLModel]]
====== Получение описания модели данных в формате HTML

Обращение GET по адресу `/printDomain?s=<sessionId>` позволяет разработчику получить описание модели данных. Сервис возвращает простой HTML, содержайщий список имен базовых типов данных, описание всех сущностей метамодели, их атрибутов и определенных для сущностей <<views,представлений>>.

[[rest_api.deployViews]]
====== Cоздание новых представлений на сервере

Запрос POST по адресу `/deployViews?s=<sessionId>` позволяет загрузить на сервер нужные клиенту определения объектов-<<views,представлений>>. Объекты-представления отсылаются в виде стандартного xml-описания представления, используемого в платформе. XML помещается в тело запроса. Подробнее о формате см. <<views,>>

[[rest_api.invokeService]]
====== Вызов сервисов

Доступные для вызова методы <<services,сервисов>> перечислены в конфигурационном файле, имя которого задается свойством <<cuba.restServicesConfig,cuba.restServicesConfig>>.

Пример файла конфигурации сервисов для REST API:

[source, xml]
----

<services xmlns="http://schemas.haulmont.com/cuba/restapi-service-v2.xsd">
   <service name="refapp_PortalTestService">
      <method name="findAllCars"/>
      <method name="updateCarVin"/>
   </service>
</services>
----

Вызов метода сервиса можно осуществить как с помощью GET, так и с помощью POST запроса. POST запрос дополнительно позволяет передавать сущность или коллекцию сущностей в вызываемый метод.

======= Вызов сервиса с помощью GET запроса

Формат запроса:

[source]
----
{host:port}/app-portal/api/service.<format>?service=<serviceName>&method=<methodName>&view=<view>&param0=<value 0>&paramN=<value N>&param0_type=<type 0>&paramN_type=<type N>&s=<sessionId>
----

* `format` - задает формат вывода результата. Принимает два значения: `xml` или `json`.

* `service` - имя вызываемого сервиса.

* `method` - имя вызываемого метода.

* `param0 .. paramN` - значения параметров метода.

* `++param0_type .. paramN_type++` - типы параметров метода.

* `s` - идентификатор текущей сессии

Если сервис имеет лишь один метод с указанным именем и количеством параметров, то явное определение типов параметров не обязательно. В противном случае указывать типы параметров необходимо.

======= Вызов сервиса с помощью POST запроса

Формат запроса:

[source]
----
{host:port}/app-portal/api/service?s=<sessionId>
----

* `s` - идентификатор текущей сессии.

В теле запроса передается JSON или XML с описанием вызова метода.

Формат JSON:: 
+
--
В качестве заголовка `Content-Type` следует использовать значение `application/json`.

[source, json]
----

{
"service": "refapp_PortalTestService",
"method": "updateCarVin",
"view": "carEdit",
"params": {
    "param0": {
        "id": "ref$Car-32261b09-b7f7-4b8c-88cc-6dee6fa8e6ab",
        "vin": "WV00001",
        "colour" : {
            "id": "ref$Colour-b32a6412-d4d9-11e2-a20b-87b22b1460c7",
            "name": "Red"
        },
        "driverAllocations": [
            {
                "id": "ref$DriverAllocation-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff"
            },
            {
                "id": "NEW-ref$DriverAllocation"
            }
        ]
    },
        "param1": "WV00001",
        "param0_type": "com.haulmont.refapp.core.entity.Car",
        "param1_type": "java.lang.String"
        }
    }
                          
----

Свойства передаваемого объекта:

* `service` - имя вызываемого сервиса.

* `method` - имя вызываемого метода.

* `param0 .. paramN` - значения параметров метода.

* `++param0_type .. paramN_type++` - типы параметров метода.

--

Формат XML:: 
+
--
В качестве заголовка `Content-Type` следует использовать значение `text/xml`.

[source, xml]
----

<ServiceRequest xmlns="http://schemas.haulmont.com/cuba/restapi-service-v2.xsd">
    <service>refapp_PortalTestService</service>
    <method>updateCarVin</method>
    <view>carEdit</view>
    <params>
        <param name="param0">
            <instance id="ref$Car-32261b09-b7f7-4b8c-88cc-6dee6fa8e6ab">
                <field name="vin">WV00000</field>
                <reference name="colour">
                    <instance id="ref$Colour-b32a6412-d4d9-11e2-a20b-87b22b1460c7">
                        <field name="name">Red</field>
                    </instance>
                </reference>
                <collection name="driverAllocations">
                    <instance id="ref$DriverAllocation-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff"/>
                    <instance id="NEW-ref$DriverAllocation"/>
                </collection>
            </instance>
        </param>
        <param name="param1">WV00001</param>
        <param name="param0_type">com.haulmont.refapp.core.entity.Car</param>
        <param name="param1_type">java.lang.String</param>
        </params>
</ServiceRequest>
                          
----

Основные элементы передаваемого документа:

* `service` - имя вызываемого сервиса.

* `method` - имя вызываемого метода.

* `param` - значение параметра метода или тип параметра. Имя параметра (атрибут `name`) должно быть вида `param0 .. paramN` или `++param0_type .. paramN_type++`.

Если сервис имеет лишь один метод с указанным именем и количеством параметров, то явное определение типов параметров не обязательно. В противном случае указывать типы параметров необходимо.

Элемент `<param>` может содержать в себе как текст (для задания значений простых типов данных), так и вложенный элемент `<instance>` для сущности или `<instances>` для коллекции сущностей.

XSD запроса доступна по адресу link:$$http://schemas.haulmont.com/cuba/5.6/restapi-service-v2.xsd$$[http://schemas.haulmont.com/cuba/5.6/restapi-service-v2.xsd]
--

======= Поддерживаемые типы параметров метода сервиса

* примитивные типы Java. В качестве имени типа указывается `long`, `int`, `boolean` и т.д.

* обертки для примитивных типов Java. В качестве имени типа указывается полное имя класса: `java.lang.Boolean`, `java.lang.Integer` и т.д.

* строка (`java.lang.String`).

* дата (`java.util.Date`).

* UUID (`java.util.UUID`).

* BigDecimal (`java.math.BigDecimal`).

======= Результат вызова сервиса

В зависимости от объявления вызова метода, результат будет в формате JSON или XML. В настоящее временя поддерживается возврат из методов простых типов данных, сущностей и коллекций сущностей.

Пример результата в формате JSON::: 
+
--
Результат имеет простой тип данных:

[source, json]
----

{
   "result": "10"
}                          
----

Результатом является сущность:

[source, json]
----

{
   "result": {
      "id" : "ref$Colour-b32e43e8-d4d9-11e2-8c8b-2b2939d67fff",
	   "name": "Red"
	}
}	                          
----

--

Пример результата в формате XML::: 
+
--
Результат имеет простой тип данных:

[source, xml]
----

<result>
        10
</result>                          
----

Результатом является сущность:

[source, xml]
----

<result>
   <instance id="ref$Colour-b32a6412-d4d9-11e2-a20b-87b22b1460c7">
      <field name="name">Red</field>
   </instance>
</result>                          
----

XSD результата доступна по адресу link:$$http://schemas.haulmont.com/cuba/5.6/restapi-service-v2.xsd$$[http://schemas.haulmont.com/cuba/5.6/restapi-service-v2.xsd]
--

