[[preface]]
== Предисловие

Данное руководство содержит справочную информацию по платформе CUBA и охватывает наиболее важные темы разработки бизнес-приложений на платформе.

Для успешной работы с платформой требуется знание следующих технологий:

* Java Standard Edition

* Реляционные базы данных (SQL, DDL)

Для глубокого понимания принципов работы платформы полезным является знакомство со следующими технологиями и фреймворками:

* link:https://docs.gradle.org/{gradleVersion}/userguide/userguide.html[Gradle] build system

* link:$$http://projects.spring.io/spring-framework$$[Spring Framework]

* link:$$https://en.wikipedia.org/wiki/Java_Persistence_API$$[Java Persistence API]

* link:$$https://vaadin.com/book$$[Vaadin] web applications framework

* HTML / CSS / JavaScript

* Java Servlets

Если у Вас имеются предложения по улучшению данного руководства, мы будем рады принять ваши pull request'ы и issues в исходниках документации на https://github.com/cuba-platform/documentation[GitHub]. Если вы увидели ошибку или несоответствие в документе - пожалуйста, форкните репозиторий и исправьте проблему. Заранее спасибо!

:sectnums:

