[[security_subsystem]]
== Подсистема безопасности

Платформа CUBA включает в себя следующие средства разграничения прав доступа пользователей к информации:

* Система назначения пользователям <<permissions,разрешений>>, основанная на <<roles,ролях>>; при этом набор ролей и разрешений настраивается администратором системы на этапе внедрения.

* Иерархическая структура <<groups,групп доступа>> с наследованием <<constraints,ограничений>>.

* Контроль доступа на следующих уровнях:

** Операции над сущностями предметной области (чтение, создание, изменение, удаление): например, пользователь `*Иванов*` может просматривать документы, но не может создавать, изменять и удалять их.

** Атрибуты сущностей (изменение, чтение, запрет): пользователь `*Иванов*` видит все атрибуты документов, кроме суммы.

** Доступ к определенным экземплярам сущностей (контроль доступа на уровне строк): пользователь `*Иванов*` видит только те документы, которые были созданы в его отделе.

* Интеграция с <<ldap,LDAP>> с возможностью реализации технологии единого входа (Single Sign-On) для пользователей *Windows*. Подробную информацию о том, как настроить SSO в приложении, см. в https://github.com/cuba-platform/idp-addon/wiki[документации] к дополнению IDP.

include::security_subsystem/security_web.adoc[]

include::security_subsystem/security_components.adoc[]

include::security_subsystem/security_examples.adoc[]

include::security_subsystem/ldap.adoc[]

include::security_subsystem/sso.adoc[]

include::security_subsystem/social_login.adoc[]

