[[setup]]
== Установка и настройка инструментария

Минимально необходимым набором программного обеспечения является:

Java SE Development Kit (JDK) 8::
+
--
* Установите Java SE Development Kit (JDK) 8 и проверьте его работоспособность, выполнив в консоли команду

`java -version`

В ответ должно быть выведено сообщение с номером версии Java, например `++1.8.0_152++`.

[WARNING]
====
Java 9 пока не поддерживается. Собирать и запускать CUBA-приложения можно только на Java 8.
====

Для сборки и запуска проектов вне Studio в переменной окружения `++JAVA_HOME++` необходимо установить путь к корневому каталогу JDK, например `C:\Program Files\Java\jdk1.8.0_152`.

* Для *Windows* это можно сделать, открыв *Компьютер* → *Свойства системы* → *Дополнительные параметры системы* → *Дополнительно* → *Переменные среды*, и задав значение переменной в списке *Системные переменные*.

* Для *macOS* `JAVA_HOME` рекомендуется задать в `~/.bash_profile`:
+
`export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`
+
Если вы установили Java 9 на macOS, CUBA Studio и приложения перестанут запускаться, независимо от значения `JAVA_HOME`. В этом случае обратитесь к информации в разделе <<setup_troubleshooting, решение проблем>> ниже.
--

Cреда разработки на Java::
+
--
*IntelliJ IDEA* или *Eclipse*. Рекомендуется использовать *IntelliJ IDEA* (Community или Ultimate).
--

База данных::
+
--
В простейшем случае в качестве сервера баз данных приложений используется встроенный *HyperSQL* (link:$$http://hsqldb.org$$[http://hsqldb.org]), что вполне подходит для исследования возможностей платформы и прототипирования приложений. Для создания реальных приложений рекомендуется установить и использовать в проекте какую-либо из полноценных СУБД, <<dbms_types,поддерживаемых платформой>>, например *PostgreSQL*.
--

Веб-браузер::
+
--
Веб-интерфейс приложений, создаваемых на основе платформы, поддерживает все популярные современные браузеры, в том числе *Google Chrome*, *Mozilla Firefox*, *Safari*, *Opera 15+*, *Internet Explorer 9+*, *Microsoft Edge*.
--

[[setup_troubleshooting]]
Решение проблем::
+
--
. Если по какой-то причине вы установили Java 9 на macOS, CUBA Studio и приложения перестанут запускаться. Для того, чтобы восстановить работоспособность, выполните следующее:

.. Сделайте инсталляцию JDK 9 не используемой по умолчанию в системе: переименуйте файл `/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Info.plist` в `Info.plist.disabled` (замените `jdk-9.0.1.jdk` реальной версией вашего JDK 9).

.. Замените `JavaAppletPlugin.plugin`, установленный Java 9 на плагин из Java 8:
*** Удалите или переименуйте `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin`
*** Установите JDK 8 снова, при этом плагин будет переустановлен.

.. Убедитесь что вы указали получение `JAVA_HOME` с аргументом `-v 1.8`, как показано выше. Перелогиньтесь или выполните `source .bash_profile` после внесения изменений.

. Убедитесь, что ваше окружение нe содержит переменных `CATALINA_HOME`, `CATALINA_BASE` и `CLASSPATH`. Эти переменные могут вызвать проблемы с запуском веб-сервера *Apache Tomcat*, который используется во время разработки. Перезагрузите компьютер после удаления переменных.
--

include::setup/cubaStudio_install.adoc[]

include::setup/ide_integration.adoc[]

