[[system_properties]]
[appendix]
== Системные свойства

Системные свойства задаются при запуске JVM с помощью аргумента командной строки `-D` и могут быть получены или установлены методами `getProperty()`, `setProperty()` класса `System`.

Системные свойства можно использовать для установки или переопределения значений <<app_properties,свойств приложения>>. Например, следующий аргумент командной строки переопределит значение свойства <<cuba.connectionUrlList,cuba.connectionUrlList>>, которое обычно задается в файле `web-app.properties`:

[source,plain]
----
-Dcuba.connectionUrlList=http://somehost:8080/app-core
----

[WARNING]
====
Имейте в виду, что системные свойства влияют на всю JVM, то есть все блоки приложения, выполняющиеся на данной JVM, получат одинаковое значение свойства.
====

Ниже приведены системные свойства, используемые в платформе, но не являющиеся свойствами приложения.

[[logback.configurationFile]]
logback.configurationFile::
+
--
Определяет местонахождение файла конфигурации фреймворка *Logback*.

Для <<app_tiers,блоков>> приложения, работающих на веб-сервере Tomcat, данное системное свойство задается в файлах `tomcat/bin/setenv.bat` и `tomcat/bin/setenv.sh`. По умолчанию оно указывает на конфигурационный файл `tomcat/conf/logback.xml`.

Для Desktop Client, если данное свойство не задано при запуске JVM, оно задается в коде самого приложения и по умолчанию указывает на файл `cuba-logback.xml`, расположенный в корне CLASSPATH. Подробнее см. <<logging_setup_desktop>>.
--

[[cuba.desktop.home]]
cuba.desktop.home:: 
+
--
Для <<app_tiers,блока>> *Desktop Client* задает расположение домашнего каталога, в котором по умолчанию находятся каталоги, определяемые свойствами приложения <<cuba.confDir,cuba.confDir>>, <<cuba.logDir,cuba.logDir>>, <<cuba.tempDir,cuba.tempDir>>, <<cuba.dataDir,cuba.dataDir>>.

Если данное свойство не задано при запуске JVM, то будет использовано значение `${user.home}/.haulmont/cuba`, которое можно изменить в прикладном проекте, переопределив метод `getDefaultHomeDir()` класса `com.haulmont.cuba.desktop.App`. 
--

[[cuba.unitTestMode]]
cuba.unitTestMode:: 
+
--
Данное системное свойство устанавливается в значение `true` в режиме выполнения интеграционных тестов базовым классом `CubaTestCase`.

Пример использования:

[source, java]
----
if (!Boolean.valueOf(System.getProperty("cuba.unitTestMode")))
  return "Not in test mode";
----
--


