[[system_properties]]
[appendix]
== Системные свойства

Системные свойства задаются при запуске JVM с помощью аргумента командной строки `-D` и могут быть получены или установлены методами `getProperty()`, `setProperty()` класса `System`.

[[log4j.configuration]]
log4j.configuration:: 
+
--
Определяет местонахождение файла конфигурации фреймворка `link:$$http://logging.apache.org/log4j/1.2/manual.html$$[Apache log4j]`.

Для <<app_tiers,блоков приложения>>, работающих на веб-сервере *Tomcat*, данное системное свойство задается в файлах `tomcat/bin/setenv.bat` и `tomcat/bin/setenv.sh`. По умолчанию оно указывает на конфигурационный файл `tomcat/conf/log4j.xml`.

Для *Desktop Client*, если данное свойство не задано при запуске JVM, оно задается в коде самого приложения и по умолчанию указывает на файл `cuba-log4j.xml`, расположенный в корне CLASSPATH. Задать другой файл конфигурации можно, переопределив метод `getDefaultLog4jConfig()` класса `com.haulmont.cuba.desktop.App`.
--

[[cuba.desktop.home]]
cuba.desktop.home:: 
+
--
Для <<app_tiers,блока>> *Desktop Client* задает расположение домашнего каталога, в котором по умолчанию находятся каталоги, определяемые свойствами приложения `<<cuba.confDir,cuba.confDir>>`, `<<cuba.logDir,cuba.logDir>>`, `<<cuba.tempDir,cuba.tempDir>>`, `<<cuba.dataDir,cuba.dataDir>>`.

Если данное свойство не задано при запуске JVM, то будет использовано значение `${user.home}/.haulmont/cuba`, которое можно изменить в прикладном проекте, переопределив метод `getDefaultHomeDir()` класса `com.haulmont.cuba.desktop.App`. 
--

[[cuba.unitTestMode]]
cuba.unitTestMode:: 
+
--
Данное системное свойство устанавливается в значение `true` в режиме выполнения интеграционных тестов базовым классом `CubaTestCase`.

Пример использования:

[source, java]
----
if (!Boolean.valueOf(System.getProperty("cuba.unitTestMode")))
  return "Not in test mode";
----
--

