:sourcesdir: ../../../../../source

[[record_set]]
===== Наборы

Для того, чтобы использовать наборы в некотором экране, выполните следующее:

. Соедините компонент <<gui_Filter,Filter>> с <<gui_Table,Table>> с помощью атрибута `applyTo`.
. Добавьте в таблицу предопределенное действие `addToSet`. После этого пользователи смогут добавлять сущности в наборы, используя команду контекстного меню таблицы.
. Добавьте кнопку, представляющую действие, на панель кнопок.

Например:

[source, xml]
----
<layout>
  <filter id="customerFilter" dataLoader="customersDl"
          applyTo="customersTable"/>

  <groupTable id="customersTable" dataContainer="customersDc">
      <actions>
          <action id="addToSet" type="addToSet"/>
          ...
      </actions>
      <buttonsPanel>
          <button action="customersTable.addToSet"/>
          ...
      </buttonsPanel>
----

Когда экран отображает некоторый набор, т.е. он открыт щелчком по набору в панели папок, в контекстном меню таблицы автоматически появляются команды *Add to current set* / *Remove from current set*. Если таблица содержит внутри себя компонент `buttonsPanel` (как в приведенном выше примере), команды контекстного меню будут продублированы соответствующими кнопками.

Наборы представляют собой экземпляры сущности `SearchFolder` и хранятся в связанных таблицах *SYS_FOLDER* и *SEC_SEARCH_FOLDER*.

