:sourcesdir: ../../../../../source

[[arbitrary_dbms]]
===== Support for Other DBMSs

In the application project, you can use any DBMS supported by the <<orm,ORM>> framework (EclipseLink). Follow the steps below:

* Specify the type of database in the form of an arbitrary code in the <<cuba.dbmsType,cuba.dbmsType>> property. The code must be different from those used in the platform: `hsql`, `postgres`, `mssql`, `oracle`.

* Implement the `DbmsFeatures`, `SequenceSupport`, `DbTypeConverter` interfaces by classes with the following names: `TypeDbmsFeatures`, `TypeSequenceSupport`, and `TypeDbTypeConverter`, respectively, where `Type` is the DBMS type code. The package of the implementation class must be the same as of the interface.

* Create database init and update scripts in the directories marked with the DBMS type code. Init scripts must create all database objects required by the platform entities (you can copy them from the existing `10-cuba`, etc. directories and modify for your database).

* To create and update the database by Gradle tasks, you need to specify the additional parameters for these tasks in `build.gradle`:
+
[source, java]
----
include::{sourcesdir}/dbms/dbtasks_1.gradle[]
----

