:sourcesdir: ../../../../../source

[[screen_xml]]
===== XML-Descriptor

XML-descriptor is a file in XML format describing <<datasources,datasources>> and screen layout.

XML schema is available at {xsd_url}/window.xsd.

Descriptor has the following structure:

`window` − root element.

`window` attributes:

* `class` − name of a <<screen_controller,controller>> class.

* `messagesPack` − a default <<message_packs,message pack>> for the screen. It is used to obtain localized messages in the controller using `getMessage()` method and in the XML descriptor using message key without specifying the pack.

* `caption` − window caption, can contain a <<messageTools.loadString,link to a message>> from the above mentioned pack, for example, 
+
[source, properties]
----
caption="msg://credits"
----

* `focusComponent` − identifier of a component which should get input focus when the screen is displayed.

* `lookupComponent` – mandatory attribute for a <<screen_lookup,lookup screen>>; defines the identifier of a visual component that the entity instance should be selected from. Supports the following types of components (and their subclasses):

** `Table`

** `Tree`

** `LookupField`

** `PickerField`

** `OptionsGroup`

* `datasource` – mandatory attribute for an <<screen_edit,edit screen>> which defines the identifier of the <<datasources,datasource>> containing the edited entity instance.

`window` elements:

* `metadataContext` − the element initializing the <<views,views>> required for the screen. It is recommended to define all views in a single <<views.xml,views.xml>> file, because all view descriptors are deployed into a common repository, so it is difficult to ensure unique names if the descriptors are scattered across multiple files.

* `dsContext` − defines <<datasources,datasource>> for the screen.

* `dialogMode` - defines the settings of geometry and behaviour of the screen when it is opened as a dialog.
+
--
Attributes of `dialogMode`:

** `closeable` - defines whether the dialog window has close button. Possible values: `true`, `false`.

** `closeOnClickOutside` - defines if the dialog window should be closed by click on outside the window area, when the window has a modal mode. Possible values: `true`, `false`.

** `forceDialog` - specifies that the screen should always be opened as a dialog regardless of what `WindowManager.OpenType` was selected in the calling code. Possible values: `true`, `false`.

** `height` - sets the height of the dialog window.

** `maximized` - if the `true` value is set, the dialog window will be maximized across the screen. Possible values: `true`, `false`.

** `modal` - specifies the modal mode for the dialog window. Possible values: `true`, `false`.

** `positionX` - sets the `x` position of the top-left corner of the dialog window.

** `positionY` - sets the `y` position of the top-left corner of the dialog window.

** `resizable` - defines whether the user can change the size of the dialog window. Possible values: `true`, `false`.

** `width` - sets the width of the dialog window.

For example:

[source, xml]
----
include::{sourcesdir}/gui/dialogs_4.xml[]
----
--

* `actions` – defines the list of <<gui_Action,actions>> for the screen.

* `timers` – defines the list of timers for the screen.

* `companions` – defines the list of <<companions,companion>> classes for the screen controller.
+
--
Elements of `companions`:

** `web` – defines a companion implemented in the *web* module.

** `desktop` – defines a companion implemented in the *desktop* module.

Each of these elements contains `class` attribute defining the companion class.
--

* `layout` − root element of the screen layout, a container with a vertical layout of components, similar to <<gui_BoxLayout,vbox>>.
+
Attributes of `layout`:

** <<gui_attr_spacing,spacing>>

** <<gui_attr_margin,margin>>

** <<gui_attr_expand,expand>>

** <<gui_attr_stylename,stylename>>

** <<gui_attr_height,height>>

** <<gui_attr_width,width>>

