:sourcesdir: ../../../../../../source

[[web_theme_reusable]]
====== Creating a Reusable Theme

Any theme can be packed and reused without an <<web_theme_inheritance,application component>>. To create a theme package, you need to create a Java project from scratch and bundle it in a single JAR file. Follow the steps below to create a distribution of `facebook` theme from the previous examples.

. Create a new project with the following structure in IDE. It will be a simple Java project that consists of SCSS files and theme properties:
+
--
[source, plain]
----
include::{sourcesdir}/gui/themes/themes_31.scss[]
----

This sample theme project can be downloaded from https://github.com/cuba-labs/halo-facebook[GitHub].

* `build.gradle` script:
+
[source, groovy]
----
include::{sourcesdir}/gui/themes/themes_32.groovy[]
----

* `settings.gradle` file:
+
[source, groovy]
----
include::{sourcesdir}/gui/themes/themes_33.groovy[]
----

* `app-component.scss` file:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_34.scss[]
----

* `halo-facebook.scss` file:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_35.scss[]
----

* `halo-facebook-defaults.scss` file:
+
[source, css]
----
include::{sourcesdir}/gui/themes/themes_36.css[]
----

* `halo-facebook-theme.properties` file:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_37.scss[]
----
--

. Build and install the project with the Gradle task:
+
[source, plain]
----
gradle assemble install
----

. Add the theme to your CUBA-based project as a Maven dependency in two configurations: themes and compile, by modifying you `build.gradle` file:
+
[source, groovy]
----
include::{sourcesdir}/gui/themes/themes_38.groovy[]
----
+
If you install the theme locally, don't forget to add `mavenLocal()` to the list of repositories: open the *Advanced* tab of *Project Properties* section in Studio and check the *Use local Maven repository* checkbox.

. To inherit this theme and modify it in your project, you have to extend this theme. Extend the `halo` theme and rename `themes/halo` folder to `themes/halo-facebook`:
+
[source, plain]
----
include::{sourcesdir}/gui/themes/themes_39.scss[]
----

. Modify `styles.scss` file:
+
[source, scss]
----
include::{sourcesdir}/gui/themes/themes_40.scss[]
----

. The last step is to define `halo-facebook-theme.properties` file in `web-app.properties` file:
+
[source, plain]
----
include::{sourcesdir}/gui/themes/themes_41.scss[]
----

Now, you can choose `halo-facebook` theme from *Help* > *Settings* menu or set the default theme using `cuba.web.theme` application property.

