:sourcesdir: ../../../../../../source

[[config_interface_usage]]
====== Использование

Для создания конфигурационного интерфейса необходимо:

* Создать интерфейс, унаследованный от `com.haulmont.cuba.core.config.Config` (не путать с классом сущности `com.haulmont.cuba.core.entity.Config`)

* Добавить интерфейсу аннотацию `@Source` для указания источника (способа хранения) параметров:

** `SourceType.SYSTEM` - значение свойства будет взято из системных свойств данной JVM, т.е. методом `System.getProperty()`.

** `SourceType.APP` - значение свойства будет взято из файлов `app.properties`.

** `SourceType.DATABASE` - значение свойства будет взято из базы данных.

* Создать методы доступа к свойству (getter / setter). Если значение свойства не предполагается изменять из кода приложения, метод доступа на запись не нужен. Тип, вовращаемый методом доступа на чтение, определяет тип свойства. Возможные типы рассмотрены <<config_interface_property_types,ниже>>.

* Добавить методу доступа на чтение аннотацию `@Property`, определяющую имя свойства.

* Опционально аннотацию `@Source` можно задать для отдельного свойства в интерфейсе, если его источник отличается от заданного для всего интерфейса.

* Если аннотация `@Source` имеет значение `SourceType.DATABASE`, то свойство можно редактировать на экране *Administration > Application Properties*. Если вы хотите, чтобы значение свойства было замаскировано, задайте на свойстве аннотацию `@Secret`. В этом случае на данном экране будет использован компонент <<gui_PasswordField,PasswordField>> вместо обычного текстового поля.

Например:

[source, java]
----
include::{sourcesdir}/common/configinterface_3.java[]
----

Создавать класс реализации конфигурационного интерфейса не нужно - при получении ссылки на интерфейс инжекцией или через <<configuration,Configuration>> будет автоматически создан необходимый прокси-объект.

