:sourcesdir: ../../../source

[[indexing]]
=== Индексирование

Если в приложении подключен компонент *fts* и включено свойство <<fts.enabled,fts.enabled>>, то при каждом сохранении в базу данных сущности, подлежащей индексированию, ее идентификатор записывается в очередь на индексацию – таблицу *SYS_FTS_QUEUE*.

Чтобы процесс индексирования запускался автоматически в фоновом режиме, необходимо создать и активировать <<qs_indexing, назначенное задание>>. Отдельный асинхронный процесс периодически извлекает идентификаторы изменившихся сущностей из очереди, загружает экземпляры сущностей и индексирует их. Индексация производится с помощью библиотеки *Apache Lucene*. Документ Lucene содержит следующие поля:

* Имя сущности и идентификатор экземпляра.

* Поле `all` – конкатенация индексируемых атрибутов сущности, но только локальных и типа `FileDescriptor`. Если атрибут имеет тип `FileDescriptor`, то индексируется содержимое соответствующего файла. Локальные атрибуты бывают одного из следующих типов: строка, число, дата, перечисление.

* Поле `links` – конкатенация идентификаторов сущностей, которые содержатся в ссылочных индексируемых атрибутах.

Под индексируемыми атрибутами понимаются атрибуты данной сущности и, возможно, связанных с ней сущностей, объявленные в дескрипторе FTS.

Индекс хранится в файловой системе, по умолчанию в подкаталоге `ftsindex` рабочего каталога приложения (задаваемого свойством `cuba.dataDir`), в стандартном варианте развертывания это `tomcat/work/app-core/ftsindex`. Расположение индекса можно изменить с помощью свойства <<fts.indexDir,fts.indexDir>>.

