:sourcesdir: ../../../../../source

[[session_attr]]
===== Атрибуты сессии

Группа доступа может определять список атрибутов <<userSession,сессии>> для пользователей, входящих в данную группу. Эти атрибуты можно использовать в коде приложения и при настройке <<constraints,ограничений>>.

В пользовательскую сессию при входе в систему будут помещены все атрибуты, заданные для группы, в которой находится пользователь, и для всех родительских групп вверх по иерархии. При этом если атрибут встречается в иерархии групп несколько раз, значение он получит от самой верхней группы, то есть переопределение значений атрибутов на нижнем уровне невозможно. При попытке переопределения в <<logging,журнал>> сервера будет выведено сообщение с уровнем `WARN`.

Атрибуты сессии могут быть заданы вместе с ограничениями в классе, используемом для задания <<groups,группы доступа>>. Класс должен быть расположен в модуле `core`. Ниже приведен пример группы доступа, которая определяет атрибут `accessLevel` со значением `1`:

[source,java]
----
include::{sourcesdir}/security/session_attr_1.java[]
----

Атрибуты сессии могут быть также заданы во время работы приложения с помощью экрана *Access Groups*: выберите группу и перейдите на вкладку *Session Attributes*.

Получить атрибут <<userSession,сессии>> в коде приложения можно с помощью объекта `UserSession`:

[source, java]
----
@Inject
private UserSessionSource userSessionSource;
...
Integer accessLevel = userSessionSource.getUserSession().getAttribute("accessLevel");
----

Использовать атрибут в <<constraints,ограничениях>> можно, указав его в параметре JPQL с префиксом `session$`:

[source, java]
----
{E}.accessLevel = :session$accessLevel
----

