= Платформа CUBA. Подсистема Workflow
:toc: left
:toc-title: Содержание
:appendix-caption: Приложение
:toclevels: 6
:sectnumlevels: 6
:linkcss:
:stylesheet: cuba.css
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: ru
:revnumber: 6.0
:version-label: Версия
:revremark: Copyright (c) 2015 Haulmont (www.haulmont.com)
:figure-caption: Рисунок

:!sectnums:

[[preface]]
[preface]
== Предисловие

Данный документ является руководством по применению подсистемы Workflow платформы CUBA.

[[audience]]
=== Целевая аудитория

Данное руководство предназначено для разработчиков, создающих на платформе CUBA приложения с элементами управления _бизнес-процессами_. Предполагается, что читатель ознакомлен с *Руководством по разработке приложений*, доступным по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

[[additional_info]]
=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

[[feedback]]
=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, обратитесь, пожалуйста, в службу поддержки по адресу: link:$$https://ru.cuba-platform.com/support/topics$$[ru.cuba-platform.com/support/topics].

При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска.

:sectnums:

include::chapter1.adoc[]

include::chapter2.adoc[]

[[appendix_workflow_properties]]
[appendix]
== Свойства приложения

В данном разделе перечислены свойства приложения, имеющие отношение к подсистеме Workflow.

workflow.designerUrl:: 
+
--
Путь для загрузки файла host-HTML визуального дизайнера относительно корневого URL веб-приложения.

Значение по умолчанию: `wfdesigner/workflow/main.ftl`

Интерфейс: `WfConfig`

Используется в блоке Web Client.
--

