:sourcesdir: ../../../../../source

[[notifications]]
===== Уведомления

[WARNING]
====
Это устаревший API. Новый API, доступный начиная с v.7.0, описан в разделе <<gui_notifications>>.
====

Уведомления вызываются методом `showNotification()` интерфейса `Frame`. Этот интерфейс реализуется <<screen_controller,контроллером экрана>>, поэтому данный метод можно вызывать напрямую в коде контроллера.

Метод `showNotification()` принимает следующие параметры:

* `caption` - текст уведомления. В случае HTML-типа (см. ниже) в сообщении можно использовать теги HTML для форматирования. При использовании HTML обязательно экранируйте данных из БД во избежание code injection в веб-клиенте. В не-HTML сообщениях можно использовать символы `\n` для переноса строки.

* `description` - опциональное описание, которое будет отображено ниже `caption`. Также можно использовать символы `\n` или HTML-форматирование.

* `type` - тип уведомления. Возможные типы:

** `TRAY`, `++TRAY_HTML++` - уведомление показывается в правом нижнем углу приложения и исчезает автоматически. 

** `HUMANIZED`, `++HUMANIZED_HTML++` - стандартное уведомление в центре экрана, исчезает автоматически.

** `WARNING`, `++WARNING_HTML++` - предупреждение. Исчезает при клике пользователя.

** `ERROR`, `++ERROR_HTML++` - уведомление об ошибке. Исчезает при клике пользователя.

Примеры вызова уведомлений:

[source, java]
----
showNotification(getMessage("selectBook.text"), NotificationType.HUMANIZED);

showNotification("Validation error", "<b>Date</b> is incorrect", NotificationType.TRAY_HTML);
----

