:sourcesdir: ../../../../../../source

[[AddAction]]
====== AddAction

AddAction is a <<standard_list_actions,list action>> designed to add existing entity instances to a data container by selecting them in a lookup screen. For example, it can be used to fill a many-to-many collection.

The action is implemented by `com.haulmont.cuba.gui.actions.list.AddAction` class and should be defined in XML using `type="add"` action's attribute. You can configure common action parameters using XML attributes of the `action` element, see <<declarative_actions>> for details. Below we describe parameters specific to the `AddAction` class.

The following parameters can be set both in XML and in Java:

* `openMode` - the lookup screen opening mode as a value of the `OpenMode` enum: `NEW_TAB`, `DIALOG`, etc. By default, AddAction opens the lookup screen in `THIS_TAB` mode.

* `screenId` - string id of the lookup screen to use. By default, AddAction uses either a screen, annotated with `@PrimaryLookupScreen`, or having identifier in the format of `<entity_name>.lookup` or `<entity_name>.browse`, e.g. `demo_Customer.browse`.

* `screenClass` - Java class of the lookup screen controller to use. It has higher priority than `screenId`.

For example, if you want to open a specific lookup screen as a dialog, you can configure the action in XML:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/add/01.xml[]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java]
----
include::{sourcesdir}/gui/std_actions/add/02.java[]
----

Now let's consider parameters that can be configured only in Java code. In order to generate correctly annotated method stubs for these parameters, use *Handler* tab of the *Component Inspector* tool window in Studio.

* `screenOptionsSupplier` - a handler that returns `ScreenOptions` object to be passed to the opened lookup screen. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/03.java[]
----
+
The returned `ScreenOptions` object will be available in the `InitEvent` of the opened screen.

* `screenConfigurer` - a handler that accepts the lookup screen and can initialize it before opening. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/04.java[]
----
+
Note that screen configurer comes into play when the screen is already initialized but not yet shown, i.e. after its `InitEvent` and `AfterInitEvent` and before `BeforeShowEvent` are sent.

* `selectValidator` - a handler that is invoked when the user clicks *Select* in the lookup screen. It accepts the object that contains the selected entities. You can use this handler to check if the selection matches some criteria. The handler must return `true` to proceed and close the lookup screen. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/05.java[]
----

* `transformation` - a handler that is invoked after entities are selected and validated in the lookup screen. It accepts the collection of selected entities. You can use this handler to transform the selection before adding entities to the receiving data container. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/06.java[]
----

* `afterCloseHandler` - a handler that is invoked after the lookup screen is closed. `AfterCloseEvent` is passed to the handler. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/add/08.java[]
----

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action's `ActionPerformedEvent` and invoke `execute()` method of the action when needed. The action will be invoked with all parameters that you defined for it. In the example below, we show a confirmation dialog before executing the action:

[source,java]
----
include::{sourcesdir}/gui/std_actions/add/09.java[]
----

You can also subscribe to `ActionPerformedEvent` and instead of invoking the action's `execute()` method, use `ScreenBuilders` API directly to open the lookup screen. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like caption, icon, etc. For example:

[source,java]
----
include::{sourcesdir}/gui/std_actions/add/10.java[]
----