:sourcesdir: ../../../../../../source

[[BulkEditAction]]
====== BulkEditAction

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/actions/list/BulkEditAction.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=bulk-edit-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

BulkEditAction is a <<standard_list_actions,list action>> designed to change attribute values for multiple entity instances at once. It opens a special screen where the user can enter desired attribute values. After that, the action updates the selected entities in the database and in the data container of the UI component.

The action is implemented by `com.haulmont.cuba.gui.actions.list.BulkEditAction` class and should be defined in XML using `type="bulkEdit"` action's attribute. You can configure common action parameters using XML attributes of the `action` element, see <<declarative_actions>> for details. Below we describe parameters specific to the `BulkEditAction` class.

* `openMode` - the bulk edit screen opening mode as a value of the `OpenMode` enum: `NEW_TAB`, `DIALOG`, etc. By default, the screen is opened in `DIALOG` mode.

* `columnsMode` - the number of columns in the bulk edit screen as a value of the `ColumnsMode` enum. `TWO_COLUMNS` by default.

* `exclude` - a regular expression to exclude entity attributes from displaying in the editor.

* `includeProperties` - a list of entity attributes to be shown in the editor. This list has higher priority than `exclude` expression.

* `loadDynamicAttributes` - whether to display dynamic attributes in the editor screen. True by default.

* `useConfirmDialog` - whether to show a confirmation dialog before saving the changes. True by default.

For example:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/01.xml[]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/02.java[]
----

The parameter below can be configured only in Java code. In order to generate correctly annotated method stub for it, use *Handlers* tab of the *Component Inspector* tool window in Studio.

* `fieldSorter` - a handler that accepts the list of `MetaProperty` object denoting entity attributes and returns a map of this objects to desired index in the edit screen. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/03.java[]
----

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action's `ActionPerformedEvent` and invoke `execute()` method of the action when needed. In the example below, we show a custom confirmation dialog before executing the action:

[source,java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/09.java[]
----

You can also subscribe to `ActionPerformedEvent` and instead of invoking the action's `execute()` method, use `BulkEditors` API directly. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like caption, icon, etc. For example:

[source, java]
----
include::{sourcesdir}/gui/std_actions/bulkEdit/10.java[]
----

The appearance of the bulk edit screen can be customized using SCSS variables with `$c-bulk-editor-*` prefix. You can change these variables in the visual editor after creating a <<web_theme_extension,theme extension>> or a <<web_theme_creation,custom theme>>.