:sourcesdir: ../../../../../../source

[[picker_actions]]
====== Standard Actions of the Picker Field

For <<gui_PickerField,PickerField>>, <<gui_LookupPickerField,LookupPickerField>> and <<gui_SearchPickerField,SearchPickerField>> components, a set of standard actions is defined in the `PickerField.ActionType` enumeration. Implementations are inner classes of the `PickerField` interface, which are described in details below. 

The example of standard actions usage in a picker component: 

[source, xml]
----
include::{sourcesdir}/gui/pickerActions_1.xml[]
---- 

[[lookupAction]]
*LookupAction*

`LookupAction` – action with *lookup* identifier, intended for selecting an entity instance and setting it as the component's value. When triggered, it opens an entities <<screen_lookup,lookup screen>>.

The following specific methods are defined in the `LookupAction` class:

* `setLookupScreenOpenType()` allows you to specify entity selection screen open mode. `++THIS_TAB++` by default.

* `setLookupScreen()` allows you to specify entity selection screen identifier. `++{entity_name}.lookup++` by default, for example, `sales$Customer.lookup`. If such screen does not exist, attempts to open `++{entity_name}.browse++` screen, for example, `sales$Customer.browse`.

* `setLookupScreenParams()` allows you to set selection screen parameters, passed into its `init()` method.

* `afterSelect()` is invoked by the action after the selected instance is set as the component's value. This method does not have implementation and can be overridden.

* `afterCloseLookup()` is the last method invoked by the action after closing the lookup screen regardless of whether an instance has been selected or not. This method does not have implementation and can be overridden.

[[clearAction]]
*ClearAction*

`ClearAction` - an action with *clear* identifier, intended for clearing (i.e. for setting to `null`) the value of the component.

[[openAction]]
*OpenAction*

`OpenAction` - action with *open* identifier, intended for opening an edit screen for the entity instance which is the current value of the component.

The following specific methods are defined in the `OpenAction` class:

* `setEditScreenOpenType()` allows you to specify entity selection screen open mode. `++THIS_TAB++` by default.

* `setEditScreen()` allows you to specify entity edit screen identifier. `++{entity_name}.edit++` screen is used by default, for example, `sales$Customer.edit`.

* `setEditScreenParams()` allows you to set edit screen parameters, passed to its `init()`method.

* `afterWindowClosed()` is invoked by the action after closing the edit screen. This method does not have implementation and can be overridden in inheritors to handle this event. 

