:sourcesdir: ../../../../../../source

[[RefreshAction]]
====== RefreshAction

RefreshAction is a <<standard_list_actions,list action>> designed to reload the data container which is used by the table or tree component.

The action is implemented by `com.haulmont.cuba.gui.actions.list.RefreshAction` class and should be defined in XML using `type="refresh"` action's attribute. You can configure common action parameters using XML attributes of the `action` element, see <<declarative_actions>> for details.

If you want to perform some checks or interact with the user before the action is executed, subscribe to the action's `ActionPerformedEvent` and invoke `execute()` method of the action when needed. In the example below, we show a custom confirmation dialog before executing the action:

[source,java]
----
include::{sourcesdir}/gui/std_actions/refresh/09.java[]
----

You can also subscribe to `ActionPerformedEvent` and instead of invoking the action's `execute()` method, trigger the data loader directly. For example:

[source,java]
----
include::{sourcesdir}/gui/std_actions/refresh/10.java[]
----
