:sourcesdir: ../../../../../../source

[[RemoveAction]]
====== RemoveAction

RemoveAction is a <<standard_list_actions,list action>> designed to remove entity instances from a data container in UI and from the database.

The action is implemented by `com.haulmont.cuba.gui.actions.list.RemoveAction` class and should be defined in XML using `type="remove"` action's attribute. You can configure common action parameters using XML attributes of the `action` element, see <<declarative_actions>> for details. Below we describe parameters specific to the `RemoveAction` class.

The following parameters can be set both in XML and in Java:

* `confirmation` - boolean value specifying whether to show confirmation dialog before removing the selected entities. True by default.

* `confirmationMessage` - confirmation dialog message. By default, it is taken from the main message pack using the `dialogs.Confirmation.Remove` key.

* `confirmationTitle` - confirmation dialog title. By default, it is taken from the main message pack using the `dialogs.Confirmation` key.

For example, if you want to show a specific confirmation message, you can configure the action in XML:

[source,xml]
----
include::{sourcesdir}/gui/std_actions/remove/01.xml[]
----

Alternatively, you can inject the action into the screen controller and configure it using setters:

[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/02.java[]
----

Now let's consider parameters that can be configured only in Java code. In order to generate correctly annotated method stubs for these parameters, use *Handlers* tab of the *Component Inspector* tool window in Studio.

* `afterActionPerformedHandler` - a handler that is invoked after selected entities are removed. It accepts the event object that can be used to get the entities selected for removal. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/07.java[]
----

* `actionCancelledHandler` - a handler that is invoked when the remove operation is cancelled by user in the confirmation dialog. It accepts the event object that can be used to get the entities selected for removal. For example:
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/08.java[]
----

If you want to perform some checks or interact with the user in a special way before the action is executed, subscribe to the action's `ActionPerformedEvent` and invoke `execute()` method of the action when needed. The action will be invoked with all parameters that you defined for it. In the example below, we show a custom confirmation dialog before executing the action:

[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/09.java[]
----

You can also subscribe to `ActionPerformedEvent` and instead of invoking the action's `execute()` method, use `RemoveOperation` API directly to remove the selected entities. In this case, you are ignoring all specific action parameters and behavior and using only its common parameters like caption, icon, etc. For example:

[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/10.java[]
----