:sourcesdir: ../../../../../../source

[[std_list_actions]]
====== List Component Actions

The framework provides a set of standard actions for visual components implementing the `ListComponent` interface (<<gui_DataGrid,DataGrid>>, <<gui_Table,Table>>, <<gui_GroupTable,GroupTable>>, <<gui_TreeTable,TreeTable>> and <<gui_Tree,Tree>>). They are located in the `com.haulmont.cuba.gui.actions.list` package.

An example of using standard actions in a table:

[source, xml]
----
include::{sourcesdir}/gui/std_actions/listActions_1.xml[]
----

The standard list component actions include the following types:

* `create` type is implemented by the `com.haulmont.cuba.gui.actions.list.CreateAction` class. It is designed to create a new entity using its default edit screen.

* `edit` type is implemented by the `com.haulmont.cuba.gui.actions.list.EditAction` class. It is designed to edit the selected entity using its default edit screen.

* `remove` type is implemented by the `com.haulmont.cuba.gui.actions.list.RemoveAction` class. It is designed to remove the selected entity.

* `add` type is implemented by the `com.haulmont.cuba.gui.actions.list.AddAction` class. It is designed to select an entity from a default lookup screen and add it to the associated data container. A typical use case for this action is to add entities to a many-to-many collection.

* `exclude` type is implemented by the `com.haulmont.cuba.gui.actions.list.ExcludeAction` class. It is designed to remove an entity from a collection data container without removing it from the database. A typical use case for this action is to remove entities from a many-to-many collection.

* `refresh` type is implemented by the `com.haulmont.cuba.gui.actions.list.RefreshAction` class. It is designed to reload the data container which is used by the list component.

* `excel` type is implemented by the `com.haulmont.cuba.gui.actions.list.ExcelAction` class. It is designed to output the list component content to an XLS file.
+
++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.1/com/haulmont/cuba/gui/actions/list/BulkEditAction.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++
+
++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=bulk-edit-simple" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

[[gui_BulkEditAction]]
* `bulkEdit` type is implemented by the `com.haulmont.cuba.gui.actions.list.BulkEditAction` class. It is designed to change attribute values for several entity instances at once. The usage is the same as for any other actions, for instance:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/actions_bulkEdit.xml[]
----
+
In addition to that, the `BulkEditorWindow` can be created programmatically using the new `com.haulmont.cuba.gui.BulkEditors` bean:
+
[source, java]
----
include::{sourcesdir}/gui/std_actions/builder_bulkEdit.java[]
----


Standard actions provide default values for basic parameters: caption, icon and shortcut; and default behavior when executed. You can provide your own values to basic parameters in XML, just like for any other action. For example, you can specify a custom icon:

[source, xml]
----
include::{sourcesdir}/gui/std_actions/listActions_2.xml[]
----

In order to customize the execution behavior, you should subscribe to the action's `ActionPerformedEvent`. All standard actions do not execute their code if an alternative action listener is provided. It means that your `ActionPerformedEvent` handler effectively overrides the default action behavior.

For example, the following code overrides the default `create` action behavior to create `Customer` entity using a specific screen opened as a modal dialog:

[source, java]
----
include::{sourcesdir}/gui/std_actions/listActions_3.java[]
----

You can customize behavior of the `edit` action in the same way as for `create`. See <<screenBuilders,ScreenBuilders>> bean description for more details.

The `add` action also uses the `ScreenBuilders` bean, so you can customize it as follows:

[source, java]
----
include::{sourcesdir}/gui/std_actions/listActions_4.java[]
----