:sourcesdir: ../../../../../source

[[nativeQuery]]
===== Running SQL Queries

ORM enables execution of SQL queries returning either the lists of individual fields or entity instances. To do this, create a `Query` or `TypedQuery` object by calling one of the `EntityManager.createNativeQuery()` methods.

If individual columns are selected, the resulting list will include the rows as `Object[]`. For example:

[source, java]
----
include::{sourcesdir}/middleware/sqlquery_1.java[]
----

If a single column or aggregate function is selected, the result list will contain these values directly:

[source, java]
----
include::{sourcesdir}/middleware/sqlquery_3.java[]
----

If the resulting entity class is passed to `EntityManager.createNativeQuery()` along with the query text, `TypedQuery` is returned, and ORM attempts to map the query results to entity attributes. For example:

[source, java]
----
include::{sourcesdir}/middleware/sqlquery_2.java[]
----

Keep in mind when using SQL, that the columns corresponding to entity attributes of `UUID` type are returned as `UUID` or as `String` depending on the DBMS in use:

* *HSQLDB* – `String`
* *PostgreSQL* – `UUID`
* *Microsoft SQL Server* – `String`
* *Oracle* – `String`
* *MySQL* – `String`

Parameters of this type should also be passed either as `UUID` or using their string representation, depending on the DBMS. To ensure that your code does not depend on the DBMS specifics, use `DbTypeConverter`. It provides methods to convert data between Java objects and JDBC parameters and results.

Native queries support positional and named parameters. Positional parameters are marked in the query text with ? followed by the parameter number starting from 1. Named parameters are marked with the number sign (#). See the examples above.

Behavior of SQL queries returning entities and modifying queries (`update`, `delete`) in relation to the current persistence context is similar to that of <<query,JPQL queries>> described above.

