:sourcesdir: ../../../../../../source

[[gui_Link]]
====== Link

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=simple-link" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Link.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Ссылка (`Link`) − компонент-гиперссылка, позволяющая открывать внешние веб-ресурсы единообразно для веб и десктоп клиента.

XML-имя компонента: `link`

Пример XML-описания компонента `link`: 

[source, xml]
----
<link caption="Link" url="https://www.cuba-platform.com" target="_blank"/>
----

Атрибуты `link`: 

[[gui_Link_url]]
* `url` - адрес ресурса.

[[gui_Link_target]]
* `target` - для веб-клиента задает способ открытия страницы, аналогичен атрибуту `target` HTML-тега `<a>`.

[[gui_Link_rel]]
* `rel` - необязательный атрибут, определяющий отношения между текущим документом и документом, на который ведет ссылка. Он соответствует атрибуту `rel` HTML-тега `<a>`.
+
Значение по умолчанию `"noopener noreferrer"`.
+
** `noopener` - указывает, что открываемая страница не должна иметь доступа к родительской вкладке, иными словами, он устанавливает для `window.opener` значение `null`.
+
** `noreferrer` указывает, что при открытии ссылки не будут переданы HTTP-заголовки.

'''

Атрибуты link::
<<gui_attr_align,align>> -
<<gui_attr_caption,caption>> -
<<gui_attr_description,description>> -
<<gui_attr_enable,enable>> -
<<gui_attr_expandRatio,box.expandRatio>> -
<<gui_attr_icon,icon>> -
<<gui_attr_id,id>> -
<<gui_Link_rel,rel>> -
<<gui_attr_stylename,stylename>> -
<<gui_Link_url,url>> -
<<gui_Link_target,target>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

'''

