:sourcesdir: ../../../../../../source

[[gui_Embedded]]
====== Embedded (Deprecated)

[WARNING]
====
Начиная с версии 6.8 платформы, компонент `Embedded` объявлен устаревшим (Deprecated). Используйте компонент <<gui_Image,Image>> для отображения графического содержимого и компонент <<gui_BrowserFrame,BrowserFrame>> для встраивания веб-страниц.
====

Компонент `Embedded` предназначен для вывода изображений и встраивания в экран произвольных веб-страниц.

XML-имя компонента: `embedded`

Компонент реализован для блоков *Web Client* и *Desktop Client*. В десктоп-клиенте поддерживается только вывод изображений.

Рассмотрим пример использования компонента для вывода изображения из файла, сохраненного в <<file_storage,FileStorage>>. 

* Объявляем компонент в XML-дескрипторе экрана:
+
[source, xml]
----
include::{sourcesdir}/gui_vcl/embedded_1.xml[]
----

* В контроллере экрана инжектируем компонент и интерфейс `FileStorageService`. Затем в методе `init()` получаем из параметров экрана переданный из вызывающего кода `FileDescriptor`, загружаем соответствующий файл в байтовый массив, создаем для него `ByteArrayInputStream` и передаем в метод `setSource()` компонента:
+
[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_2.java[]
----

[[gui_Embedded_type]]
Компонент `Embedded` может отображать содержимое различных типов, которые по-разному отрисовываются в HTML. Тип содержимого можно задать методом `setType()`. Поддерживаются следующие типы:

* `OBJECT`  - позволяет встраивать файлы некоторых типов в элементы HTML <object> и <embed>.

* `IMAGE`  - встраивает изображения в HTML-элемент <img>.

* `BROWSER`  - встраивает контейнер для отображения других независимых документов внутри элемента HTML <iframe>.

В веб-клиенте компонент позволяет отображать файлы, находящиеся внутри каталога `VAADIN`. Например:

[[gui_Embedded_relativeSrc]]
[source, xml]
----
include::{sourcesdir}/gui_vcl/embedded_6.xml[]
----

или

[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_5.java[]
----

Кроме того, можно определить каталог ресурсных файлов в свойстве приложения <<cuba.web.resourcesRoot,cuba.web.resourcesRoot>>, и указать для компонента `Embedded` имя файла внутри этого каталога с префиксом значения атрибута: `file://` , `url://` или `theme://`:

[[gui_Embedded_src]]
[source, xml]
----
include::{sourcesdir}/gui_vcl/embedded_7.xml[]
----

или

[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_3.java[]
----

Для встраивания в экран веб-клиента внешней веб-страницы необходимо передать компоненту URL:

[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_4.java[]
----

'''

Атрибуты embedded::
<<gui_attr_align,align>> -
<<gui_attr_height,height>> -
<<gui_attr_id,id>> -
<<gui_Embedded_relativeSrc,relativeSrc>> -
<<gui_Embedded_src,src>> -
<<gui_attr_stylename,stylename>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

'''

