:sourcesdir: ../../../../../../source

[[gui_Label]]
====== Label

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=simple-label" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.0/com/haulmont/cuba/gui/components/Label.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

Надпись (`Label`) − текстовый компонент, отображающий статический текст либо значение атрибута сущности.

XML-имя компонента: `label`

Пример задания надписи с текстом, взятым из <<message_packs,пакета локализованных сообщений>>:

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_1.xml[]
----

[[gui_Label_value]]
Атрибут `value` предназначен для задания текста надписи.

В веб-клиенте текст, содержащийся в атрибуте `value`, будет разбит на несколько строк, если по длине он превысит значение атрибута <<gui_attr_width,width>>. Поэтому для отображения многострочной надписи, достаточно указать абсолютное значение атрибута <<gui_attr_width,width>>. Если текст надписи слишком длинный, а значение атрибута <<gui_attr_width,width>> не определено, то текст будет урезан.

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_2.xml[]
----

Параметры надписи можно задать в контроллере экрана. Для этого необходимо задать компоненту идентификатор, по которому получить ссылку на него в контроллере:

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_3.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_vcl/label_4.java[]
----

Компонент `Label` может отображать значение атрибута сущности. Для этого используются атрибуты <<gui_attr_dataContainer,dataContainer>> и <<gui_attr_property,property>>. Например:

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_5.xml[]
----

В данном случае компонент отображает атрибут `name` сущности `Customer`, находящейся в контейнере данных `customerDc`.

[[gui_Label_htmlEnabled]]
Атрибут `htmlEnabled` указывает, каким образом будет рассматриваться значение атрибута <<gui_Label_value,value>>: при `htmlEnabled="true"` как HTML-код, иначе как строка.

[[gui_Label_stylenames]]
Стили компонента Label::
+
--
В веб-клиенте с темой, основанной на Halo, к компоненту `Label` можно применить заданные <<gui_Label_stylenames,стили>>. Стили задаются в XML-дексрипторе или контроллере экрана с помощью атрибута `stylename`:
[source, xml]
----
include::{sourcesdir}/gui_vcl/label_6.xml[]
----
Чтобы применить стиль программно, выберите одну из констант класса `HaloTheme` с префиксом компонента `LABEL_`:
[source, java]
----
include::{sourcesdir}/gui_vcl/label_7.java[]
----

[[gui_label_bold]]
* `bold` - жирный шрифт. Подходит для выделения важных текстовых элементов UI.

[[gui_label_colored]]
* `colored` - цветной текст.

[[gui_label_failure]]
* `failure` - стиль сообщения об ошибке. Добавляет рамку вокруг компонента и значок рядом с текстом. Используется как уведомление рядом с другим компонентом.

[[gui_label_h1]]
* `h1` - стиль основных заголовков приложения.

[[gui_label_h2]]
* `h2` - стиль заголовков разделов приложения.

[[gui_label_h3]]
* `h3` - стиль подзаголовков.

[[gui_label_h4]]
* `h4` - стиль подзаголовков.

[[gui_label_light]]
* `light` - облегченный шрифт. Подходит для выделения второстепенных текстовых элементов UI.

[[gui_label_no-margin]]
* `no-margin` - убирает отступы заголовков.

[[gui_label_spinner]]
* `spinner` - стиль спиннера. Используйте для пустых компонентов `Label`, чтобы создать спиннер.

[[gui_label_success]]
* `success` - стиль сообщения об успешном выполнении. Добавляет рамку вокруг компонента и значок рядом с текстом. Используется как уведомление рядом с другим компонентом.

--

'''

Атрибуты label::
<<gui_attr_align,align>> -
<<gui_attr_css,css>> -
<<gui_attr_dataContainer,dataContainer>> -
<<gui_attr_datasource,datasource>> -
<<gui_attr_description,description>> -
<<gui_attr_descriptionAsHtml,descriptionAsHtml>> -
<<gui_attr_enable,enable>> -
<<gui_attr_expandRatio,box.expandRatio>> -
<<gui_attr_height,height>> -
<<gui_Label_htmlEnabled,htmlEnabled>> -
<<gui_attr_icon,icon>> -
<<gui_attr_id,id>> -
<<gui_attr_property,property>> -
<<gui_attr_stylename,stylename>> -
<<gui_Label_value,value>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

Элементы label::
<<gui_formatter,formatter>>

Предопределенные стили label::
<<gui_label_bold,bold>> -
<<gui_label_colored,colored>> -
<<gui_label_failure,failure>> -
<<gui_label_h1,h1>> -
<<gui_label_h2,h2>> -
<<gui_label_h3,h3>> -
<<gui_label_h4,h4>> -
<<gui_attr_stylename_huge,huge>> -
<<gui_attr_stylename_large,large>> -
<<gui_label_light,light>> -
<<gui_label_no-margin,no-margin>> -
<<gui_attr_stylename_small,small>> -
<<gui_label_spinner,spinner>> -
<<gui_label_success,success>> -
<<gui_attr_stylename_tiny,tiny>>

API::
<<gui_api_addValueChangeListener,addValueChangeListener>>

'''

