:sourcesdir: ../../../source

[[hot_deploy]]
=== Hot Deploy

[WARNING]
====
Данный раздел будет обновлен перед выходом релиза 7.0
====

Платформа CUBA поддерживает технологию Hot Deploy, которая позволяет мгновенно отображать сделанные в проекте изменения в работающем приложении без необходимости перезапускать сервер. Принцип работы Hot deploy заключается во временном копировании изменённых ресурсов и исходных файлов Java проекта в <<conf_dir,конфигурационный каталог>> приложения, откуда они загружаются и компилируются работающим приложением.

Как это работает::
+
--
Когда в каком-то файле исходного кода производятся изменения, Studio копирует этот файл в конфигурационный каталог веб-приложения (`tomcat/conf/app` или `tomcat/conf/app-core`). Ресурсы в конфигурационном каталоге имеют приоритет над ресурсами в JAR-файлах приложения, поэтому работающее приложение загрузит именно эти ресурсы, когда они понадобятся. Если загружается файл исходного кода на Java, то приложение компилирует его на лету и загружает результирующий класс.

Кроме того, Studio посылает приложению специальные сигналы для того чтобы заставить его очистить кэши и перезагрузить измененные ресурсы. Это кэш локализованных сообщений и конфигурации представлений, зарегистрированных экранов и меню.

При перезагрузке сервера приложения все файлы в конфигурационном каталоге удаляются, и JAR-файлы содержат последние версии вашего кода.
--

Какие изменения применяются через hot deploy::
+
--
* <<screen_xml,XML-дескрипторы>> и <<screen_controller,контроллеры>> экранов (включая статические методы), расположенные в <<app_modules,модулях>> *web* и *gui*.
* Реализации <<services,сервисов>> среднего слоя, расположенные в модуле *core*.
* Шаблоны <<portal,портала>>.

Изменения в прочих классах и бинах UI и среднего слоя, включая их статические методы, могут применяться на лету только тогда, когда изменяется ещё хотя бы один файл экрана или реализации сервиса, который их используют.

Причина такого поведения в том, что перезагрузка классов вызывается только по сигналу: для контроллера экрана это переоткрытие этого экрана пользователем, а для сервисов Studio генерирует особый файл-триггер, который будет распознан сервером и использован для перезагрузки конкретного класса сервиса и всех его зависимостей.
--

Какие изменения не применяются через hot deploy::
+
--
* Любые классы в модуле *global*, включая интерфейсы сервисов среднего слоя, <<base_entity_classes,сущности>>, <<entity_listeners,entity listeners>> и т.д.
--

Использование hot deploy в Studio::
+
--
Настройки Hot deploy можно изменить в Studio на странице *Help > Settings*:

* Диалог *Hot deploy settings* позволяет конфигурировать отображение между каталогами исходного кода и каталогами Tomcat.

* Флажок *Instant hot deploy* позволяет отключить автоматический hot deploy для текущего проекта.

Если мгновенный hot deploy отключен, применение изменений можно вызвать вручную командой меню *Run > Hot deploy conf*.
--

