:sourcesdir: ../../../source

[[spring_profiles]]
=== Использование профилей Spring

Профили Spring позволяют кастомизировть приложение для работы в различном окружении. В зависимости от активного профиля можно инстанциировать различные реализации одного и того же бина, а также присваивать различные значения свойствам приложения.

Если Spring-бин имеет аннотацию `@Profile`, он будет инстанциирован только если указанный в аннотации профиль соответствует какому-либо активному профилю. В примере ниже `SomeDevServiceBean` будет использован когда активен профиль `dev`, а `SomeProdServiceBean` будет использован когда активен профиль `prod`:

[source,java]
----
include::{sourcesdir}/development/spring_profile_1.java[]
----

Для того, чтобы определить некоторые специфичные для профиля свойства приложения, создайте файл `<profile>-app.properties` в том же пакете, что и основной файл `app.properties`, например:

[source]
----
com/company/demo/app.properties
com/company/demo/prod-app.properties
----

Специфичный для профиля файл будет загружен сразу после базового файла, поэтому объявленные в нем свойства переопределят свойства, заданные в базовом файле. В примере ниже для профиля `prod` задаются параметры подключения к некоторой базе данных:

.prod-app.properties
[source,properties]
----
include::{sourcesdir}/development/spring_profile_2.properties[]
----

Список активных профилей задается для приложения следующими способами:

* В servlet context параметре `spring.profiles.active` в файле `web.xml`, например:
+
[source,xml]
----
include::{sourcesdir}/development/spring_profile_3.xml[]
----

* В системном свойстве Java `spring.profiles.active`. Например, при запуске <<uberjar_deployment,Uber JAR>>:
+
[source]
----
java -Dspring.profiles.active=prod -jar app.jar
----