:sourcesdir: ../../../source

[[testing]]
=== Тестирование

Приложения CUBA можно тестировать с помощью общеизвестных подходов: модульных тестов, интеграционных тестов и тестов UI.

Модульные тесты хорошо подходят для тестирования логики, инкапсулированной в определенных классах, слабо связанных с инфраструктурой приложения. Для того, чтобы начать писать JUnit-тесты, достаточно создать каталог `test` в модулях `global`, `core` или `web` вашего проекта. Если вам нужны моки, добавьте зависимость от предпочтительного мок-фреймворка или link:http://jmockit.github.io/[JMockit], который уже используется в CUBA. Зависимость должна быть добавлена в `build.gradle` перед JUnit:

[source, groovy]
----
include::{sourcesdir}/development/testing_jmockit_dep.groovy[]
----
<1> - зависимость от мок-фреймворка
<2> - в случае JMockit при запуске тестов необходимо указать аргумент `-javaagent`
<3> - класс, который находит JMockit JAR в classpath и формирует требуемое значение `-javaagent`

Интеграционные тесты запускаются в контейнере Spring, поэтому они могут тестировать большинство аспектов приложения, включая взаимодействие с базой данных и экраны UI. В данном разделе рассматривается создание интеграционных тестов на среднем слое и в веб-клиенте.

Для UI-тестов рекомендуется использовать библиотеку https://github.com/cuba-platform/masquerade[Masquerade], которая предоставляет набор полезных абстракций для тестирования CUBA-приложений. См. README и Wiki на GitHub.

include::testing/integration_tests_mw.adoc[]

include::testing/integration_tests_client.adoc[]

