:sourcesdir: ../../../../../../source

[[metadataTools]]
====== MetadataTools

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/core/global/MetadataTools.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

<<managed_beans,ManagedBean>>, содержащий вспомогательные методы работы с метаданными. Интерфейс `MetadataTools` можно получить либо методом `Metadata.getTools()`, либо как любой другой бин - инжекцией или через класс `AppBeans`.

Методы `MetadataTools`:

* `getAllPersistentMetaClasses()` - возвращает коллекцию <<metaClass,мета-классов>> персистентных сущностей

* `getAllEmbeddableMetaClasses()` - возвращает коллекцию <<metaClass,мета-классов>> встраиваемых сущностей

* `getAllEnums()` - возвращает коллекцию классов перечислений, используемых в качестве типов атрибутов сущностей

* `format()` - форматирует переданное значение в соответствии с типом данных заданного <<metaProperty,мета-свойства>>

* `isSystem()` - определяет, является ли переданное <<metaProperty,мета-свойство>> системным, т.е. заданным в одном из <<base_entity_classes,базовых интерфейсов сущностей>>

* `isPersistent()` - определяет, является ли переданное мета-свойство персистентным, т.е. хранимым в БД

* `isTransient()` - определяет, является ли переданное мета-свойство или произвольный атрибут неперсистентным

* `isEmbedded()` - определяет, является ли переданное мета-свойство встроенным объектом

* `isAnnotationPresent()` - определяет наличие указанной аннотации на классе или его предках

* `getNamePatternProperties()` - возвращает коллекцию мета-свойств атрибутов, входящих в имя экземпляра, возвращаемого методом `Instance.getInstanceName()`. См. <<namePattern_annotation,@NamePattern>>.

Для расширения набора вспомогательных методов в конкретном приложении бин `MetadataTools` можно <<bean_extension,переопределить>>. Примеры работы с расширенным интерфейсом:

[source, java]
----
MyMetadataTools tools = metadata.getTools();
tools.foo();
----

[source, java]
----
((MyMetadataTools) metadata.getTools()).foo();
----

