:sourcesdir: ../../../../../../source

[[entity_class_annotations]]
====== Class Annotations

++++
<div class="manual-live-demo-container">
    <a href="http://docs.oracle.com/javaee/7/api/javax/persistence/Embeddable.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[embeddable_annotation]]
@Embeddable::
+
--
Defines an embedded entity stored in the same table as the owning entity.

<<metaclass_annotation,@MetaClass>> annotation should be used to specify the entity name.
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/entity/annotation/EnableRestore.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[enableRestore_annotation]]
@EnableRestore::
Indicates that the entity instances are available for recovery after <<soft_deletion,soft deletion>> on the `core$Entity.restore` screen available through the *Administration > Data Recovery* main menu item.

++++
<div class="manual-live-demo-container">
    <a href="http://docs.oracle.com/javaee/7/api/javax/persistence/Entity.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[entity_annotation]]
@Entity::
+
--
Declares a class to be a data model entity.

Parameters:

* `name` – the name of the entity, must begin with a prefix, separated by a `$` sign. It is recommended to use a short name of the project as a prefix to form a separate namespace.

Example:

[source, java]
----
@Entity(name = "sales$Customer")
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/entity/annotation/Extends.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[extends_annotation]]
@Extends::
Indicates that the entity is an extension and it should be used everywhere instead of the base entity. See <<extension>>.

++++
<div class="manual-live-demo-container">
    <a href="http://docs.oracle.com/javaee/7/api/javax/persistence/DiscriminatorColumn.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[discriminatorColumn_annotation]]
@DiscriminatorColumn::
+
--
Is used for defining a database column responsible for the distinction of entity types in the cases of `++SINGLE_TABLE++` and `JOINED` inheritance strategies.

Parameters:

* `name` – the discriminator column name
* `discriminatorType` – the discriminator column type

Example:

[source, java]
----
@DiscriminatorColumn(name = "TYPE", discriminatorType = DiscriminatorType.INTEGER)
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://docs.oracle.com/javaee/7/api/javax/persistence/DiscriminatorValue.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[discriminatorValue_annotation]]
@DiscriminatorValue::
+
--
Defines the discriminator column value for this entity.

Example:

[source, java]
----
@DiscriminatorValue("0")
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://docs.oracle.com/javaee/7/api/javax/persistence/Inheritance.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[inheritance_annotation]]
@Inheritance::
+
--
Defines the inheritance strategy to be used for an entity class hierarchy. It is specified on the entity class that is the root of the entity class hierarchy.

Parameters:

* `strategy` – inheritance strategy, `++SINGLE_TABLE++` by default
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/entity/annotation/Listeners.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[listeners_annotation]]
@Listeners::
+
--
Defines the list of listeners intended for reaction to the entity instance lifecycle events on the middle <<app_tiers,tier>>.

The annotation value should be a string or an array of strings containing bean names of the listeners. See <<entity_listeners>>.

Examples:
[source, java]
----
@Listeners("sample_UserEntityListener")
----

[source, java]
----
@Listeners({"sample_FooListener","sample_BarListener"})
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://docs.oracle.com/javaee/7/api/javax/persistence/MappedSuperclass.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[mappedSuperclass_annotation]]
@MappedSuperclass::
+
--
Defines that the class is an ancestor for some entities and its attributes must be used as part of descendant entities. Such class is not associated with any particular database table.
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/chile/core/annotations/MetaClass.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[metaclass_annotation]]
@MetaClass::
+
--
Is used for declaring non-persistent or <<embeddable_annotation,embedded>> entity (meaning that `@javax.persistence.Entity` annotation cannot be applied)

Parameters:

* `name` – the entity name, must begin with a prefix, separated by a `$` sign. It is recommended to use a short name of the project as prefix to form a separate namespace.

Example:

[source, java]
----
@MetaClass(name = "sales$Customer")
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/chile/core/annotations/NamePattern.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[namePattern_annotation]]
@NamePattern::
+
--
Determines the way of getting the name of the instance returned by the `Instance.getInstanceName()` method.

The annotation value should be a string in the `{0}|{1}` format, where:

* `{0}` – formatting string according to the `String.format()` rules, or this object method name with the prefix `#`. The method should return `String` and should have no parameters.

* `{1}` – a list of field names separated by commas, corresponding to `{0}` format. If the method is used in `{0}`, the list of fields is still required as it forms the `++_minimal++` <<views,view>>.

Examples:

[source, java]
----
@NamePattern("%s|name")
----

[source, java]
----
@NamePattern("#getCaption|login,name")
----
--

++++
<div class="manual-live-demo-container">
    <a href="https://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[postConstruct_entity_annotation]]
@PostConstruct::
This annotation can be specified for a method. Such method will be invoked right after the entity instance is created by the <<metadata,Metadata.create()>> method. This is convenient when instance initialization requires invocation of <<managed_beans,managed beans>>. For example, see <<init_values_in_class>>.

++++
<div class="manual-live-demo-container">
    <a href="https://docs.oracle.com/javaee/7/api/javax/persistence/PrimaryKeyJoinColumn.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[primaryKeyJoinColumn_annotation]]
@PrimaryKeyJoinColumn::
+
--
Is used in the case of `JOINED` inheritance strategy to specify a foreign key column for the entity which refers to the primary key of the ancestor entity.

Parameters:

* `name` – the name of the foreign key column of the entity
* `referencedColumnName` – the name of primary key column of the ancestor entity

Example:

[source, java]
----
@PrimaryKeyJoinColumn(name = "CARD_ID", referencedColumnName = "ID")
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/entity/annotation/SystemLevel.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[systemLevel_annotation]]
@SystemLevel::
Indicates that the entity is system only and should not be available for selection in various lists of entities, such as <<gui_Filter,generic filter>> parameter types or <<dynamic_attributes,dynamic attribute>> type.

++++
<div class="manual-live-demo-container">
    <a href="https://docs.oracle.com/javaee/7/api/javax/persistence/Table.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[table_annotation]]
@Table::
+
--
Defines database table for the given entity.

Parameters:

* `name` – the table name

Example:

[source, java]
----
@Table(name = "SALES_CUSTOMER")
----
--

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/core/entity/annotation/TrackEditScreenHistory.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[[trackEditScreenHistory_annotation]]
@TrackEditScreenHistory::
Indicates that <<screen_edit,editor screens>> opening history will be recorded with the ability to display it on the `sec$ScreenHistory.browse` screen available through the *Help > History* main menu item.

