:sourcesdir: ../../../source

[[settings]]
=== Меню настроек CUBA Settings

При выборе элемента *CUBA > Settings* в главном меню откроется окно настроек IDE, отфильтрованных по слову *cuba*. Найдите секцию *CUBA* под секцией *Languages & Frameworks*.

В секции *CUBA* содержатся общие настройки, которые распространяются на все проекты, открываемые в данной установленной Studio.

* *Ask before saving DB scripts with DROP statements* - предлагать исключить скрипты обновления БД, содержащие команду DROP, из списка скриптов для автоматического выполнения.

* *Show warning if application server port is in use* - показывать предупреждение при открытии проекта, если используемый в нём порт Tomcat в данный момент занят.

* *Use embedded browser to open application* - если установлен этот флажок, то при двойном клике на секции дерева *Runs At* запущенное приложение будет открываться во встроенном веб-браузере.

* *Visual designer theme* - тема визуальных дизайнеров. Используйте `Autodetect`, чтобы тема автоматически подстраивалась под тему, выбранную для IDE.

* *Visual designer zoom* - масштаб (zoom) визуальных дизайнеров по умолчанию. Масштаб можно настроить и для каждого дизайнера отдельно, используя контекстное меню, открываемое правым щелчком мыши.

* *Old Studio integration enabled* - поставьте этот флажок, если вы хотите интегрировать текущий экземпляр IDE со старой Studio SE или Studio Browser Edition. Так вы сможете открывать проекты из старой Studio в этой IDE.

* *Listening port* - порт интеграции со старой Studio. Убедитесь, что этот же порт указан в настройках старой Studio в поле *IDE Port*.

* *Enable transaction block folding* - если установлен этот флажок, редактор кода Java свернёт в старом стиле блоки `try-finally`, использующиеся для контроля транзакций.

Вложенная секция *Project settings* содержит настройки IDE для текущего открытого проекта. Все настройки, отличные от настроек по умолчанию, сохраняются в файле `studio-intellij.xml` в корневом каталоге проекта. Этот файл можно добавить в систему контроля версий, чтобы поделиться настройками с другими разработчиками данного проекта.

* *Check compatibility between data model and database scheme* - показывать предупреждение при каждом запуске сервера приложения, если текущее состояние модели данных приложения отличается от текущей схемы базы данных.

* *Generate DROP statements in separate update scripts* - генерировать более безопасные скрипты обновления БД при удалении сущности и удалении или изменении типа данных её атрибута. Такие скрипты разделены на две части: в первой части скрипта колонка или вся таблица переименовываются в `*__UNUSED`, а во второй части эти объекты удаляются по-настоящему.

* *Use NVARCHAR when generating scripts for MS SQL Server* - если включена эта опция и выбран тип БД Microsoft SQL Server, то для всех строковых атрибутов будет использоваться тип колонки NVARCHAR.

* *Generate script name in format* - укажите `yyMMddHHmm`, чтобы добавлять текущее время к именам генерируемых скриптов обновления базы данных. Это обеспечит правильную последовательность скриптов при совместной работе над проектом.

* *Do not delete columns started with* - в этом поле можно указать префикс для колонок таблицы, которые нужно исключить из отслеживания Studio. Если вы добавляете колонку в таблицу, сопоставленную с некой сущностью, и не совмещаете колонку с атрибутом этой сущности, Studio сгенерирует скрипт обновления БД, удаляющий эту колонку. Чтобы избежать удаления, вы можете исключить этот скрипт в диалоговом окне *Database Scripts*, и он больше не будет сгенерирован. В качестве альтернативы вы можете указать общий префикс для таких колонок в поле *Do not delete columns started with* и использовать этот префикс в именах колонок. Например, можно ввести `NOT_MAPPED_` в указанном поле и назвать колонку `NOT_MAPPED_CODE`.

* *Column length for enums with ID of String type* - в этом поле можно установить длину колонки в БД, которая соответствует атрибуту сущности с типом `enum`, имеющим строковый идентификатор. К примеру, если вы хотите использовать короткие идентификаторы, состоящие из одного символа, вы можете указать значение 1 в этом поле и тем самым сэкономить место в базе данных.

* *Make plural forms* - образовывать формы множественного числа для существительных в соответствии с правилами английской грамматики.

* *Repeat entity parent package for screens* - если сущность расположена в дополнительном пакете внутри пакета `entity`, Studio добавит этот пакет к пути стандартных экранов Generic UI, автоматически генерируемых по шаблонам. Например, если сущность `Customer` лежит в пакете `com.company.sample.entity.crm`, пакетом для её экранов по умолчанию будет `com.company.sample.web.crm.customer`.

* *Use underscores in generated package names* - если флажок установлен, слова в именах пакетов будут разделены нижним подчёркиванием в соответствии с camel-регистром в имени соответствующей сущности. К примеру, при генерации экранов для сущности `com.company.sample.CustomerGrade`, имя пакета будет выглядеть как `com.company.sample.customer_grade`. Если опция выключена, пакет будет назван `com.company.sample.customergrade`.

* *Default parent package name for screens* - здесь можно указать пакет по умолчанию, который будет использоваться для экранов вместо `screens` при генерации экранов пользовательского интерфейса, не относящимся к какой-либо сущности. Например, если в этом поле указать значение `ui` и создать пустой экран по шаблону `blank screen`, пакетом по умолчанию для этого экрана будет `com.company.sample.web.ui`.

* *Default access modifier* - здесь можно установить модификатор доступа для генерируемых полей сущностей.

* *Generate entity name with underscore symbol* - если флажок установлен, имена сущностей будут образованы в формате `namespace_ClassName`, например, `sales_Customer`. В противном случае будет использован формат `namespace$ClassName`.

* *Show module prefix migration dialog* - при открытии проекта предлагать миграцию скриптов сборки на новый формат с префиксом модулей, заданным в виде переменной.

* *Instant hot deploy* - этот флажок позволяет отключить механизм мгновенного применения изменений (hot deploy). Если hot deploy разрешён, Studio будет динамически обновлять UI уже развёрнутого приложения по мере внесения изменений в представления (views), экраны, пакеты сообщений или главное меню.

* *Hot Deploy Settings* - открывает диалоговое окно, в котором можно настроить каталоги hot deployment. Это может быть полезно в случае, если вы захотите добавить, например, каталоги, где размещены файлы HTML и JavaScript модуля *web portal* вашего проекта. При изменении этих файлов Studio будет копировать их в соответствующие каталоги внутри Tomcat. Таким образом, чтобы увидеть изменения, вам потребуется всего лишь перезагрузить страницу веб-портала.

* *Fold messages in* - позволяет контролировать свёртывание сообщений в дескрипторах и контроллерах экрана. Если флажок установлен, ключи сообщений будут заменены на их реальные значения из соответствующих пакетов сообщений.

* *Message folding locale* - позволяет указать, сообщения из какого пакета (какой локали) должны быть использованы при свёртывании.