:sourcesdir: ../../../../../source

[[db_scripts_groovy]]
===== The Structure of Groovy scripts

Groovy update scripts have the following structure:

* The __main__ part, which contains the code executed before the start of the <<appContext,application context>>. In this section, you can use any Java, Groovy and the Middleware application block classes. However, it should be kept in mind that no beans, infrastructure interfaces and other application objects have yet been instantiated and it is impossible to use them.
+
The main part is primarily designed to update the database schema, as usually done with ordinary SQL scripts.

* The __PostUpdate__ part – a set of closures, which will be executed after the start of the application context and once the update process is finished. Inside these closures, it is possible to use any Middleware objects.
+
In this part of the script, it is convenient to perform data import as it is possible to use the <<persistence,Persistence>> interface and data model objects.

The execution mechanism passes the following variables to the Groovy scripts:

* `ds` – instance of `javax.sql.DataSource` for the application database;
* `log` – instance of `org.apache.commons.logging.Log` to output messages in the server log;
* `postUpdate` – object that contains the `add(Closure closure)` method to add PostUpdate closures described above.

[WARNING]
====
Groovy scripts are executed only by <<db_update_server,the server mechanism to launch database scripts>>.
====

An example of the Groovy update script:

[source, java]
----
include::{sourcesdir}/dbms/groovyupdate_1.groovy[]
----

