:sourcesdir: ../../../../../source

[[screen_xml]]
===== XML-дескриптор

XML-дескриптор - это файл формата XML, описывающий <<datasources,источники данных>> и расположение визуальных компонентов экрана.

Схема XML доступна по адресу {xsd_url}/window.xsd.

Рассмотрим структуру дескриптора.

`window` − корневой элемент.

Атрибуты `window`:

* `class` − имя класса <<screen_controller,контроллера>>

* `messagesPack` − <<message_packs,пакет сообщений>> данного экрана, который будет использован при получении локализованных строк без указания пакета из XML-дескриптора и из контроллера методом `getMessage()`

* `caption` − заголовок экрана, может содержать <<messageTools.loadString,ссылку на сообщение>> из вышеуказанного пакета, например, 
+
[source, properties]
----
caption="msg://caption"
----

* `focusComponent` − идентификатор компонента, который получит фокус ввода при отображении экрана

* `lookupComponent` - обязательный для <<screen_lookup,экрана выбора>> атрибут, задающий идентификатор визуального компонента, из которого будет выбран экземпляр сущности. Поддерживаются компоненты следующих типов (и их наследников):

** `Table`

** `Tree`

** `LookupField`

** `PickerField`

** `OptionsGroup`

* `datasource` - обязательный для <<screen_edit,экрана редактирования>> атрибут, задающий идентификатор <<datasources,источника данных>>, в который будет проставлен экземпляр редактируемой сущности.

Элементы `window`:

* `metadataContext` − элемент для инициализации <<views,представлений>> (views), необходимых данному экрану. Предпочтительным является определение всех представлений в одном общем файле <<views.xml,views.xml>>, так как все описатели представлений разворачиваются в один общий репозиторий, и при рассредоточении описателей по разным файлам трудно обеспечить уникальность имен.

* `dsContext` − определяет <<datasources,источники данных>> данного экрана.

* `dialogMode` - определяет параметры геометрии и поведения экрана при открытии его в виде диалогового окна.
+
--
Атрибуты `dialogMode`:

** `closeable` - определяет наличие в диалоговом окне кнопки закрытия. Возможные значения: `true`, `false`.

** `closeOnClickOutside` - определяет возможность закрыть окно кликом по окружающей области, если диалог открыт в модальном режиме. Возможные значения: `true`, `false`.

** `forceDialog` - указывает, что экран должен всегда открываться в режиме диалога, независимо от того, какой `WindowManager.OpenType` был выбран в вызывающем коде. Возможные значения: `true`, `false`.

** `height` - устанавливает высоту диалогового окна.

** `maximized` - если выбрано значение `true`, диалог будет развёрнут во весь экран. Возможные значения: `true`, `false`.

** `modal` - устанавливает модальный режим диалогового окна. Возможные значения: `true`, `false`.

** `positionX` - задаёт положение левого верхнего угла диалога по оси `x`.

** `positionY` - задаёт положение левого верхнего угла диалога по оси `y`.

** `resizable` - определяет возможность пользователя изменять размеры диалога. Возможные значения: `true`, `false`.

** `width` - устанавливает ширину диалогового окна.

Пример использования `dialogMode`:

[source, xml]
----
include::{sourcesdir}/gui/dialogs_4.xml[]
----
--

* `actions` - определяет список <<gui_Action,действий>> данного экрана.

* `timers` - определяет список таймеров данного экрана.

* `companions` - определяет список классов-<<companions,компаньонов>> данного контроллера
+
Элементы `companions`:

** `web` - задает компаньон, реализованный в модуле *web*

** `desktop` - задает компаньон, реализованный в модуле *desktop*
+
Каждый из этих элементов содержит атрибут `class`, задающий класс компаньона.

[[screen_xml_layout]]
* `layout` − корневой элемент компоновки экрана. Является сам по себе контейнером с вертикальным расположением компонентов, аналогичным <<gui_BoxLayout,vbox>>.
+
Атрибуты `layout`:

** <<gui_attr_spacing,spacing>>

** <<gui_attr_margin,margin>>

** <<gui_attr_expand,expand>>

** <<gui_attr_stylename,stylename>>

** <<gui_attr_height,height>>

** <<gui_attr_width,width>>

** <<gui_attr_maxHeight,maxHeight>>

** <<gui_attr_minHeight,minHeight>>

** <<gui_attr_maxWidth,maxWidth>>

** <<gui_attr_minWidth,minWidth>>