:sourcesdir: ../../../source

[[remoting-spring.xml]]
=== remoting-spring.xml

Files of this type configure an additional *Spring Framework* container for the Middleware block, used for exporting services and other middleware components accessed by the client tier (hereafter _remote access container_). 

The `remoting-spring.xml` file of the project is specified in the <<cuba.remotingSpringContextConfig,cuba.remotingSpringContextConfig>> application property.

Remote access container is created with the main container (configured by <<spring.xml,spring.xml>> files) as its parent. Therefore, the beans of the remote access container can use the beans of the main container, while the beans of the main container cannot "see" the beans of the remote access container.

The primary goal of remote access is to make Middleware services accessible to the client level using the *Spring HttpInvoker* mechanism. The `cuba-remoting-spring.xml` file in the *cuba* application component defines the `servicesExporter` bean of `RemoteServicesBeanCreator` type, which receives all service classes from the main container and exports them. In addition to regular annotated services, remote access container exports a number of specific beans, such as `LoginService`.

Furthermore, the `cuba-remoting-spring.xml` file defines a base package that serves as a starting point for lookup of annotated *Spring MVC* controller classes used for file uploading and downloading.

The `remoting-spring.xml` file in the application project should only be created when specific *Spring MVC* controllers are used. Application project services will be imported by the standard `servicesExporter` bean defined in the *cuba* application component.

