:sourcesdir: ../../source

[appendix]
[[app_properties]]
== Свойства приложения

В данном разделе в алфавитном порядке описаны свойства приложения, имеющие отношение к генератору отчётов.

[[reporting.backgroundReportProcessingTimeoutMs]]
reporting.backgroundReportProcessingTimeoutMs::
+
--
Определяет таймаут для выполнения отчета в миллисекундах, если свойство <<reporting.useBackgroundReportProcessing,reporting.useBackgroundReportProcessing>> имеет значение `true`.

Значение по умолчанию: `10000`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--


[[reporting.displayDeviceAvailable]]
reporting.displayDeviceAvailable::
+
--
Значение `false` позволяет запускать OpenOffice / LibreOffice в серверной операционной системе без оконного интерфейса.

Значение по умолчанию: `false`

Используется в блоке *Middleware*.
--

[[reporting.enableTabSymbolInDataSetEditor]]
reporting.enableTabSymbolInDataSetEditor::
+
--
Указывает, должно ли нажатие клавиши TAB в полях Script редактора отчёта обрабатываться как символ табуляции вместо смены фокуса для навигации по экрану.

Значение по умолчанию: `false`

Используется в клиентских блоках.
--

[[reporting.executionHistory.cleanup.days]]
reporting.executionHistory.cleanup.days::
+
--
Назначенное задание удаляет все записи <<execution_history,истории выполнения отчётов>> старше указанного количества дней. Если значение свойства = 0, то назначенное задание не учитывает это свойство при удалении записей. Подробнее про настройку назначенного задания см. <<execution_history_cleanup, Удаление истории>>.

Значение по умолчанию: `730`.

Хранится в базе данных.

Используется в блоке *Middleware*.

--

[[reporting.executionHistory.cleanup.itemsPerReport]]
reporting.executionHistory.cleanup.itemsPerReport::
+
--
Назначенное задание оставляет то количество записей в <<execution_history,истории выполнения>> для каждого отчёта, которое указано в этом свойстве, остальные удаляет. Не рекомендуется использовать в качестве значения число, больше 1000. Если значение = 0, то назначенное задание не учитывает это свойство при удалении записей. Это полезно для часто запускаемых отчётов, таких как шаблоны писем, выставление счетов, шаблоны документов и т. д. Подробнее про настройку назначенного задания см. <<execution_history_cleanup, Удаление истории>>.

Значение по умолчанию: `1000`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--

[[reporting.executionHistory.enabled]]
reporting.executionHistory.enabled::
+
--
Включает механизм управления <<execution_history,историей выполнения отчётов>>.

Значение по умолчанию: `false`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--

[[reporting.executionHistory.saveOutputDocument]]
reporting.executionHistory.saveOutputDocument::
+
--
При установке в `true` файлы результатов отчётов сохраняются в {main_man_url}/file_storage.html[хранилище файлов], если свойство <<reporting.executionHistory.enabled,reporting.executionHistory.enabled>> включено. См. также <<history_output_documents,Выходные документы>>.

Значение по умолчанию: `false`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--

[[reporting.fontsDir]]
reporting.fontsDir::
+
--
Путь к каталогу со шрифтами для конвертации HTML в PDF.

Например: `reporting.fontsDir = C:/Windows/Fonts`

Используется в блоке *Middleware*.
--

[[reporting.docFormatterTimeout]]
reporting.docFormatterTimeout::
+
--
Задаёт время ожидания LibreOffice в секундах для преобразования DOCX/XLSX в HTML/PDF.

По истечении указанного таймаута пользователь получит сообщение об ошибке.

Значение по умолчанию: `20`

Используется в блоке *Middleware*.
--

[[reporting.office.docx.useOfficeForDocumentConversion]]
reporting.office.docx.useOfficeForDocumentConversion::
+
--
Включает использование OpenOffice для вывода отчёта с DOCX шаблоном в HTML/PDF, что значительно увеличивает точность конвертации.

Значение по умолчанию: `false`

Используется в блоке *Middleware*.
--

[[reporting.office.path]]
reporting.office.path::
+
--
Задает путь к установленному пакету OpenOffice.

Значение по умолчанию: `/`

Используется в блоке *Middleware*.
--

[[reporting.office.ports]]
reporting.office.ports::
+
--
Задает список портов для OpenOffice/LibreOffice, разделенный запятыми или вертикальной чертой.

Например: `reporting.office.ports = 8100|8101|8102|8103|8104|8105`.

Значение по умолчанию: `8100, 8101, 8102, 8103`.

Используется в блоке *Middleware*.
--

[[reporting.putEmptyRowIfNoDataSelected]]
reporting.putEmptyRowIfNoDataSelected::
+
--
Задает режим, в котором полосы, наборы данных которых не вернули ни одной записи, все равно выводятся один раз.

Значение по умолчанию: `true`

Используется в блоке *Middleware*.
--

[[reporting.useBackgroundReportProcessing]]
reporting.useBackgroundReportProcessing::
+
--

Позволяет задать выполнение отчёта в качестве фоновой задачи. Это свойство используется для добавления возможности <<run_cancel,отмены>> отчёта.

Значение по умолчанию: `false`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--
