[appendix]
[[app_properties]]
== Свойства приложения

В данном разделе в алфавитном порядке описаны свойства приложения, имеющие отношение к генератору отчетов.

[[cuba.reporting.displayDeviceUnavailable]]
cuba.reporting.displayDeviceUnavailable::
+
--
Позволяет запускать OpenOffice / LibreOffice в серверной операционной системе без оконного интерфейса.

Значение по умолчанию: `false`

Используется в блоке *Middleware*.
--

[[cuba.reporting.fontsDir]]
cuba.reporting.fontsDir::
+
--
Путь к каталогу со шрифтами для конвертации HTML в PDF.

Например: `cuba.reporting.fontsDir = C:/Windows/Fonts`

Используется в блоке *Middleware*.
--

[[cuba.reporting.openoffice.docx.useOfficeForPdfConversion]]
cuba.reporting.openoffice.docx.useOfficeForPdfConversion::
+
--
Включает использование OpenOffice для вывода отчета с DOCX шаблоном в PDF, что значительно увеличивает точность конвертации.

Значение по умолчанию: `false`

Используется в блоке *Middleware*.
--

[[cuba.reporting.openoffice.path]]
cuba.reporting.openoffice.path::
+
--
Задает путь к установленному пакету OpenOffice.

Значение по умолчанию: `/`

Используется в блоке *Middleware*.
--

[[cuba.reporting.putEmptyRowIfNoDataSelected]]
cuba.reporting.putEmptyRowIfNoDataSelected::
+
--
Задает режим, в котором полосы, наборы данных которых не вернули ни одной записи, все равно выводятся один раз.

Значение по умолчанию: `true`

Используется в блоке *Middleware*.
--

