:sourcesdir: ../../source

[appendix]
[[app_properties]]
== Свойства приложения

В данном разделе в алфавитном порядке описаны свойства приложения, имеющие отношение к генератору отчётов.

[[reporting.backgroundReportProcessingTimeoutMs]]
reporting.backgroundReportProcessingTimeoutMs::
+
--
Определяет таймаут для выполнения отчета в миллисекундах, если свойство <<reporting.useBackgroundReportProcessing,reporting.useBackgroundReportProcessing>> имеет значение `true`.

Значение по умолчанию: `10000`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--


[[reporting.displayDeviceUnavailable]]
reporting.displayDeviceUnavailable::
+
--
Позволяет запускать OpenOffice / LibreOffice в серверной операционной системе без оконного интерфейса.

Значение по умолчанию: `false`

Используется в блоке *Middleware*.
--

[[reporting.enableTabSymbolInDataSetEditor]]
reporting.enableTabSymbolInDataSetEditor::
+
--
Указывает, должно ли нажатие клавиши TAB в полях Script редактора отчёта обрабатываться как символ табуляции вместо смены фокуса для навигации по экрану.

Значение по умолчанию: `false`

Используется в клиентских блоках.
--

[[reporting.fontsDir]]
reporting.fontsDir::
+
--
Путь к каталогу со шрифтами для конвертации HTML в PDF.

Например: `reporting.fontsDir = C:/Windows/Fonts`

Используется в блоке *Middleware*.
--

[[reporting.docFormatterTimeout]]
reporting.docFormatterTimeout::
+
--
Задаёт время ожидания LibreOffice в секундах для преобразования DOCX/XLSX в HTML/PDF.

По истечении указанного таймаута пользователь получит сообщение об ошибке.

Значение по умолчанию: `20`

Используется в блоке *Middleware*.
--

[[reporting.openoffice.docx.useOfficeForDocumentConversion]]
reporting.openoffice.docx.useOfficeForDocumentConversion::
+
--
Включает использование OpenOffice для вывода отчёта с DOCX шаблоном в HTML/PDF, что значительно увеличивает точность конвертации.

Значение по умолчанию: `false`

Используется в блоке *Middleware*.
--

[[reporting.openoffice.path]]
reporting.openoffice.path::
+
--
Задает путь к установленному пакету OpenOffice.

Значение по умолчанию: `/`

Используется в блоке *Middleware*.
--

[[reporting.openoffice.ports]]
reporting.openoffice.ports::
+
--
Задает список портов для OpenOffice/LibreOffice, разделенный запятыми или вертикальной чертой.

Например: `reporting.openoffice.ports = 8100|8101|8102|8103|8104|8105`.

Значение по умолчанию: `8100, 8101, 8102, 8103`.

Используется в блоке *Middleware*.
--

[[reporting.putEmptyRowIfNoDataSelected]]
reporting.putEmptyRowIfNoDataSelected::
+
--
Задает режим, в котором полосы, наборы данных которых не вернули ни одной записи, все равно выводятся один раз.

Значение по умолчанию: `true`

Используется в блоке *Middleware*.
--

[[reporting.useBackgroundReportProcessing]]
reporting.useBackgroundReportProcessing::
+
--

Позволяет задать выполнение отчёта в качестве фоновой задачи. Это свойство используется для добавления возможности <<run_cancel,отмены>> отчёта.

Значение по умолчанию: `false`.

Хранится в базе данных.

Используется в блоке *Middleware*.
--
