[appendix]
[[open_office]]
== Установка и настройка OpenOffice

Генератор отчетов использует пакет *OpenOffice / LibreOffice* для вывода отчетов в <<template_to_output,форматах>> PDF и DOC. Ниже рассмотрена установка и настройка данного пакета на компьютере, содержащем сервер приложения.

*Установка и настройка OpenOffice для Microsoft Windows*

* Скачайте дистрибутив программы по адресу http://openoffice.org.

* Произведите установку программы.

* Укажите в свойстве приложения <<reporting.openoffice.path,reporting.openoffice.path>> путь к установленному *OpenOffice.org*, например:

[source, properties]
----
reporting.openoffice.path = C:/Program Files (x86)/OpenOffice.org 3/program
----

*Установка и настройка LibreOffice для Microsoft Windows*

* Скачайте дистрибутив программы по адресу http://www.libreoffice.org/download/download/.

* Произведите установку программы.

* Укажите в свойстве приложения <<reporting.openoffice.path,reporting.openoffice.path>> путь к установленному пакету *LibreOffice*, например:

[source, properties]
----
reporting.openoffice.path = C:/Program Files (x86)/LibreOffice 5/program
----

*Установка и настройка LibreOffice на сервере Ubuntu*

* Установить пакет libreoffice, например, командой 
+
`$ sudo apt-get install libreoffice`

* Указать в свойстве приложения <<reporting.openoffice.path,reporting.openoffice.path>> путь к установленному LibreOffice:

[source, properties]
----
reporting.openoffice.path = /usr/lib/libreoffice/program
----

* Если на сервере не установлен оконный интерфейс, то LibreOffice при старте будет выдавать ошибку вида `Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it`, или же просто завершаться без сообщений об ошибках. Для устранения проблемы установите свойство приложения <<reporting.displayDeviceUnavailable,reporting.displayDeviceUnavailable>>:

[source, properties]
----
reporting.displayDeviceUnavailable = true
----

* Для диагностики ошибок при старте *LibreOffice* можно выполнить следующую команду:
+
`$ strace -e trace=signal /usr/lib/libreoffice/program/soffice.bin --headless --accept="socket,host=localhost,port=8100;urp" --nologo --nolockcheck`

*Установка и настройка LibreOffice для macOS*

* Скачайте дистрибутив программы по адресу https://www.libreoffice.org/get-help/install-howto/os-x/.
* Произведите установку программы.
* Укажите в свойстве приложения <<app_properties.adoc#reporting.openoffice.path, reporting.openoffice.path>> путь к установленному *LibreOffice.app*, например:

[source, properties]
----
reporting.openoffice.path = /Applications/LibreOffice.app
----