:sourcesdir: ../../source

[appendix]
[[open_office]]
== Установка и настройка OpenOffice

Генератор отчетов использует пакет *OpenOffice / LibreOffice* для вывода отчетов в <<template_to_output,форматах>> PDF и DOC. Ниже рассмотрена установка и настройка данного пакета на компьютере, содержащем сервер приложения.

*Установка и настройка OpenOffice для Microsoft Windows*

* Скачайте дистрибутив программы по адресу http://openoffice.org.

* Произведите установку программы.

* Укажите в свойстве приложения <<reporting.openoffice.path,reporting.openoffice.path>> в файле `app.properties` модуля *core* путь к установленному *OpenOffice.org*, например:

[source, properties]
----
reporting.openoffice.path = C:/Program Files (x86)/OpenOffice.org 3/program
----

*Установка и настройка LibreOffice для Microsoft Windows*

* Скачайте дистрибутив программы по адресу http://www.libreoffice.org/download/download/.

* Произведите установку программы.

* Укажите в свойстве приложения <<reporting.openoffice.path,reporting.openoffice.path>> в файле `app.properties` модуля *core* путь к установленному пакету *LibreOffice*, например:

[source, properties]
----
reporting.openoffice.path = C:/Program Files (x86)/LibreOffice 5/program
----

*Установка и настройка LibreOffice на сервере Ubuntu*

* Установите пакет libreoffice, например, командой
+
[source, properties]
----
$ sudo apt-get install libreoffice
----

* Укажите в свойстве приложения <<reporting.openoffice.path,reporting.openoffice.path>> в файле `app.properties` модуля *core* путь к установленному LibreOffice:
+
[source, properties]
----
reporting.openoffice.path = /usr/lib/libreoffice/program
----

* Если на сервере не установлен оконный интерфейс, то LibreOffice при старте будет выдавать ошибку вида `Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it`, или же просто завершаться без сообщений об ошибках. Для устранения проблемы установите свойство приложения <<reporting.displayDeviceAvailable,reporting.displayDeviceAvailable>>:
+
[source, properties]
----
reporting.displayDeviceAvailable = false
----

* Для диагностики ошибок при старте *LibreOffice* выполните следующую команду:
+
[source, properties]
----
$ strace -e trace=signal /usr/lib/libreoffice/program/soffice.bin --headless --accept="socket,host=localhost,port=8100;urp" --nologo --nolockcheck
----

[TIP]
====
Если в Ubuntu вы установили tomcat с помощью пакетного менеджера `apt`, вам необходимо также скопировать каталог `~/.config/libreoffice` в `$CATALINA_HOME`. Для tomcat8, это `/usr/share/tomcat8`.

Затем измените пользователя этого каталога:

[source, properties]
----
sudo mkdir /usr/share/tomcat8/.config
sudo cp -pr ~/.config/libreoffice /usr/share/tomcat8/.config/
sudo chown -R tomcat8.tomcat8 /usr/share/tomcat8/.config/
----
====

*Установка и настройка LibreOffice для macOS*

* Скачайте дистрибутив программы по адресу https://www.libreoffice.org/get-help/install-howto/os-x/.
* Произведите установку программы.
* Укажите в свойстве приложения <<app_properties.adoc#reporting.openoffice.path, reporting.openoffice.path>> путь к установленному *LibreOffice.app*, например:

[source, properties]
----
reporting.openoffice.path = /Applications/LibreOffice.app
----

