= Платформа CUBA. Генератор отчетов
:toc: left
:toc-title: Содержание
:appendix-caption: Приложение
:toclevels: 6
:sectnumlevels: 6
:linkcss:
:stylesheet: cuba.css
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: ru
:revnumber: 6.9
:version-label: Версия
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)
:figure-caption: Рисунок

:!sectnums:

[[preface]]
[preface]
== Предисловие

Данный документ является руководством по созданию отчетов в системах, разработанных на платформе CUBA.

[[audience]]
=== Целевая аудитория

Руководство предназначено для разработчиков и администраторов CUBA-приложений. Для успешной работы с генератором отчетов требуется как минимум понимание принципов работы реляционных баз данных и умение писать запросы на языке SQL. В некоторых случаях данные для отчетов удобнее извлекать с помощью языков JPQL или Groovy, поэтому знакомство с ними является полезным.

[[additional_info]]
=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу https://www.cuba-platform.ru/manual.

Ядром генератора отчетов платформы является фреймворк *YARG*, распространяемый по свободной лицензии Apache 2.0. Документация по фреймворку доступна по адресу https://github.com/Haulmont/yarg/wiki.

[[feedback]]
=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, мы будем рады принять ваши pull request'ы и issues в исходниках документации на https://github.com/cuba-platform/documentation[GitHub]. Если вы увидели ошибку или несоответствие в документе - пожалуйста, форкните репозиторий и исправьте проблему. Заранее спасибо!

:sectnums:

include::creation.adoc[]

include::running.adoc[]

include::examples.adoc[]

include::wizard.adoc[]

include::open_office.adoc[]

include::app_properties.adoc[]