= Платформа CUBA. Генератор отчетов
:toc: left
:toc-title: Содержание
:appendix-caption: Приложение
:toclevels: 6
:sectnumlevels: 6
:linkcss:
:stylesheet: cuba.css
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: ru
:revnumber: 6.8
:version-label: Версия
:revremark: Copyright (c) 2018 Haulmont (www.haulmont.com)
:figure-caption: Рисунок

:!sectnums:

++++++++++++++
<span style="color: red;">Более новая версия доступна в <a style="color: inherit; text-decoration: underline;" href="https://www.cuba-platform.ru/documentation">разделе документации</a>.</span>
++++++++++++++

[[preface]]
[preface]
== Предисловие

Данный документ является руководством по созданию отчетов в системах, разработанных на платформе CUBA.

[[audience]]
=== Целевая аудитория

Руководство предназначено для разработчиков и администраторов CUBA-приложений. Для успешной работы с генератором отчетов требуется как минимум понимание принципов работы реляционных баз данных и умение писать запросы на языке SQL. В некоторых случаях данные для отчетов удобнее извлекать с помощью языков JPQL или Groovy, поэтому знакомство с ними является полезным.

[[additional_info]]
=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу https://www.cuba-platform.ru/manual.

Ядром генератора отчетов платформы является фреймворк *YARG*, распространяемый по свободной лицензии Apache 2.0. Документация по фреймворку доступна по адресу https://github.com/Haulmont/yarg/wiki.

[[feedback]]
=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, обратитесь пожалуйста в службу поддержки по адресу https://www.cuba-platform.ru/support/topics.

При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска. 

:sectnums:

include::creation.adoc[]

include::running.adoc[]

include::examples.adoc[]

include::wizard.adoc[]

include::open_office.adoc[]

include::app_properties.adoc[]