:sourcesdir: ../../../../../../source

[[gui_Embedded]]
====== Embedded (Deprecated)

[WARNING]
====
Starting from the version 6.8 of the Platform the `Embedded` component is deprecated. Use the <<gui_Image,Image>> component for displaying images or the <<gui_BrowserFrame,BrowserFrame>> component for embedded web pages.
====

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=image-embedded" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`Embedded` component is intended for displaying images and embedding arbitrary web pages into the application screens.

XML name of the component: `embedded`

The component is implemented for *Web Client* and *Desktop Client*. *Desktop Client* supports image display only.

Below is an example of using the component to display an image from a file located in <<file_storage,FileStorage>>. 

* Declare the component in an XML screen descriptor: 
+
[source, xml]
----
include::{sourcesdir}/gui_vcl/embedded_1.xml[]
---- 

* In a screen controller, inject the component itself and the `FileStorageService` interface. In `init()` method, get the `FileDescriptor` passed from the calling code, load the corresponding file in a byte array, create a `ByteArrayInputStream` for it, and pass the stream to the `setSource()` method of the component:
+
[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_2.java[]
----

[[gui_Embedded_type]]
The `Embedded` component supports several different content types, which are rendered differently in HTML. You can set the content type with the `setType()` method. Supported types:

* `OBJECT`  - allows embedding certain file types inside HTML <object> and <embed> elements.

* `IMAGE`  - embeds an image inside a HTML <img> element.

* `BROWSER`  - embeds a browser frame inside a HTML <iframe> element.

In Web Client, the component enables displaying of files located inside `VAADIN` folder. You can set the resource path relative to the application root, for example:

[[gui_Embedded_relativeSrc]]
[source, xml]
----
include::{sourcesdir}/gui_vcl/embedded_6.xml[]
----

or

[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_5.java[]
----

You can also define a resource files directory in the <<cuba.web.resourcesRoot,cuba.web.resourcesRoot>> application property and specify the name of a file inside this directory with the prefix for the value: `file://` , `url://` , or `theme://`:

[[gui_Embedded_src]]
[source, xml]
----
include::{sourcesdir}/gui_vcl/embedded_7.xml[]
----

or

[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_3.java[]
---- 

In order to display an external web page, pass its URL to the component:

[source, java]
----
include::{sourcesdir}/gui_vcl/embedded_4.java[]
---- 

'''

Attributes of embedded::
<<gui_attr_align,align>> -
<<gui_attr_height,height>> -
<<gui_attr_id,id>> -
<<gui_Embedded_relativeSrc,relativeSrc>> -
<<gui_Embedded_src,src>> -
<<gui_attr_stylename,stylename>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

'''

