:sourcesdir: ../../../../../../source

[[gui_Label]]
====== Label

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=simple-label" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Label.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`Label` is a text component that displays static text or value of an entity attribute.

XML name of the component: `label`

The `Label` component is implemented for *Web Client* and *Desktop Client*.

Below is an example of setting a label with text taken from the <<message_packs,localized message pack>>: 

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_1.xml[]
---- 

[[gui_Label_value]]
The `value` attribute sets text for a label.

In a web client, the text contained in `value` will be split into multiple lines if its length exceeds the <<gui_attr_width,width>> value. Therefore, to display a multiline label, it is sufficient to specify an absolute value of <<gui_attr_width,width>>. If the label text is too long and the value of <<gui_attr_width,width>> is not specified, the text will be truncated.

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_2.xml[]
----

You can set label parameters in the screen controller. To do this, you should specify a component identifier and get a reference to the component in the controller:

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_3.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_vcl/label_4.java[]
---- 

The `Label` component can display value of an entity attribute. For this purpose, <<gui_attr_datasource,datasource>> and <<gui_attr_property,property>> attributes are used. For example:

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_5.xml[]
---- 

In the example above, component displays the `name` attribute of the `Customer` entity located in the `customerDs` data source.

[[gui_Label_htmlEnabled]]
`htmlEnabled` attribute indicates the way the <<gui_Label_value,value>> attribute will be interpreted: if `htmlEnabled="true"`, the attribute will be treated as HTML code, otherwise as a plain string. Note that the desktop implementation of the screen does not support all HTML tags.

[[gui_Label_stylenames]]
Label styles::
+
--
In Web Client with a Halo-based theme, you can set predefined styles to the `Label` component using the `stylename` attribute either in the XML descriptor or in the screen controller:
[source, xml]
----
include::{sourcesdir}/gui_vcl/label_6.xml[]
----
When setting a style programmatically, select one of the `HaloTheme` class constants with the `LABEL_` prefix:
[source, java]
----
include::{sourcesdir}/gui_vcl/label_7.java[]
----

[[gui_label_bold]]
* `bold` - bolder font weight. Suitable for important/prominent UI text.

[[gui_label_colored]]
* `colored` - colored text.

[[gui_label_failure]]
* `failure` - failure badge style. Adds a border around the label and an icon next to the text. Suitable for UI notifications that need to be used in the direct context of some component.

[[gui_label_h1]]
* `h1` - header style for main application headings.

[[gui_label_h2]]
* `h2` - header style for different sections in the application.

[[gui_label_h3]]
* `h3` - header style for different sub-sections in the application.

[[gui_label_h4]]
* `h4` - header style for different sub-sections in the application.

[[gui_label_light]]
* `light` - lighter font weight. Suitable for additional/supplementary UI text.

[[gui_label_no-margin]]
* `no-margin` - removes default margins from the header.

[[gui_label_spinner]]
* `spinner` - spinner style. Add this style name to an empty `Label` to create a spinner.

[[gui_label_success]]
* `success` - success badge style. Adds a border around the label and an icon next to the text. Suitable for UI notifications that need to be used in the direct context of some component.

--

'''

Attributes of label::
<<gui_attr_align,align>> -
<<gui_attr_datasource,datasource>> -
<<gui_attr_enable,enable>> -
<<gui_attr_height,height>> -
<<gui_Label_htmlEnabled,htmlEnabled>> -
<<gui_attr_icon,icon>> -
<<gui_attr_id,id>> -
<<gui_attr_property,property>> -
<<gui_attr_stylename,stylename>> -
<<gui_Label_value,value>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

Elements of label::
<<gui_formatter,formatter>>

Predefined styles of label::
<<gui_label_bold,bold>> -
<<gui_label_colored,colored>> -
<<gui_label_failure,failure>> -
<<gui_label_h1,h1>> -
<<gui_label_h2,h2>> -
<<gui_label_h3,h3>> -
<<gui_label_h4,h4>> -
<<gui_attr_stylename_huge,huge>> -
<<gui_attr_stylename_large,large>> -
<<gui_label_light,light>> -
<<gui_label_no-margin,no-margin>> -
<<gui_attr_stylename_small,small>> -
<<gui_label_spinner,spinner>> -
<<gui_label_success,success>> -
<<gui_attr_stylename_tiny,tiny>>

API::
<<gui_api_addValueChangeListener,addValueChangeListener>>

'''

