:sourcesdir: ../../../../../../source

[[gui_Link]]
====== Link

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=simple-link" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Link.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`Link` is a hyperlink, which enables uniform opening of external web resources for the Web and Desktop client.

XML-name of the component: `link`

An example of XML-description for `link`: 

[source, xml]
----
include::{sourcesdir}/gui_vcl/link_1.xml[]
---- 

`link` attributes:

[[gui_Link_url]]
* `url` – the URL of the web resource.

[[gui_Link_target]]
* `target` – sets the web page opening mode for the Web Client, the same as the `target` attribute of the `<a>` HTML element.

[[gui_Link_rel]]
* `rel` - an optional attribute that specifies the relationship between the current document and the linked document. It corresponds to the `rel` HTML attribute which is placed within the `<a>` tag.
+
Default value is `"noopener noreferrer"`.
+
** `noopener` - indicates that any browsing context created by following the link will not have an opener browsing context, which means that its `window.opener` property will be `null`.
+
** `noreferrer` indicates that no HTTP referer header is to be sent when following the link.

'''

Attributes of link::
<<gui_attr_align,align>> -
<<gui_attr_caption,caption>> -
<<gui_attr_description,description>> -
<<gui_attr_enable,enable>> -
<<gui_attr_icon,icon>> -
<<gui_attr_id,id>> -
<<gui_Link_rel,rel>> -
<<gui_attr_stylename,stylename>> -
<<gui_Link_url,url>> -
<<gui_Link_target,target>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

'''

