:sourcesdir: ../../../../../source

[[aws_file_storage_impl]]
===== Amazon S3 File Storage Implementation

The standard file storage implementation can be replaced by a cloud storage service. We recommend to use separate cloud file storage services for cloud deployments which, commonly, don't guarantee the persistence of external files on their hard drives.

The platform provides support of Amazon S3 file storage service out-of-the-box. To support other services, you need to implement your custom logic.

To add Amazon S3 support, firstly, you need to register `AmazonS3FileStorage` class in the `spring.xml` file of the *core* module:

[source, xml]
----
<bean name="cuba_FileStorage"
          class="com.haulmont.cuba.core.app.filestorage.amazon.AmazonS3FileStorage"/>
----

Next, you should define your Amazon settings in the `app.properties` file in the *core* module:

[source, plain]
----
cuba.amazonS3.accessKey = <Access Key>
cuba.amazonS3.secretAccessKey = <Secret Access Key>
cuba.amazonS3.region = <Region>
cuba.amazonS3.bucket = <Bucket Name>
----

[TIP]
====
The `accessKey` and `secretAccessKey` should be those of your AWS IAM user account, not the AWS account itself. You can find the correct credentials on the *Users* tab of your AWS console.
====

The storage folder structure is organized similarly to the <<file_storage_impl,standard implementation>>.

