:sourcesdir: ../../../source

[[chart_data_binding]]
=== Connecting Data

There are two ways how you can pass data to a chart: through the `DataProvider` interface or using the <<chart_data_simplified,simplified data binding API>>, which allows adding the data directly using the `addData()` method and convenient `MapDataItem` constructors for those charts that are not bound to a data container. <<chart_example>> illustrates all approaches to providing chart data.

[[chart_data_provider]]
DataProvider: ::
+
--
The `DataProvider` interface has two standard implementations: `ListDataProvider` class and `ContainerDataProvider` class.

* `ListDataProvider` contains a list of `DataItem` instances from which the data for the chart will be taken. There are several standard implementations of `DataItem` interface:

** `EntityDataItem` takes an instance of any entity from which the data for the chart will be taken:
+
[source, java]
----
include::{sourcesdir}/chart/EntityDataItem_example.java[]
----
+

** `MapDataItem` is a set of key-value pairs from which the data for the chart will be taken:
+
[source, java]
----
include::{sourcesdir}/chart/MapDataItem_example.java[]
----
+

** `SimpleDataItem` takes an instance of any `public` class from which the data for the chart will be taken:
+
[source, java]
----
include::{sourcesdir}/chart/SimpleDataItem_example.java[]
----
+

* `ContainerDataProvider` is used to assign a {main_man_url}/gui_collection_container.html[CollectionContainer] to a `Chart` component.
+
[source, java]
----
include::{sourcesdir}/chart/ContainerDataProvider_example.java[]
----
+
This approach requires an entity that will represent chart data. It may be convenient when such entity already exists in the application data model and also when chart data should be displayed as a table.

An instance of `DataProvider` is passed to the `setDataProvider()` method of chart configuration. This approach to providing chart data is the most universal, but it requires creating instances of `DataProvider` or `DataItem` in a screen controller.

Entity properties or the values contained in an instance of `DataProvider` which are used for display purposes are defined in the chart attributes. The set of chart attributes may differ for different chart types. For example, for the `chart:pieChart` component, you should define the `valueField` and `titleField` attributes. The following types are allowed for attribute values: `Integer`, `Long`, `Double`, `String`, `Boolean`, `Date`.

Dynamic addition of data to an existing chart is supported for the data provider mechanisms.
--

[[chart_data]]
chart:data element: ::
+
--
This option is useful for quick prototyping of charts. The `chart:data` element and its nested `item` elements enable you to set key-value pairs of data directly in the XML descriptor of the chart, for example:

[source, xml]
----
include::{sourcesdir}/chart/chart_data.xml[]
----
--

