:sourcesdir: ../../../../source

[[qs_users_creation]]
==== Creating Users

In order to demonstrate the process, create three users in the *Administration > Users* screen:

* login: `norman`, First name: `Tommy`, Last name: `Norman`
* login: `roberts`, First name: `Casey`, Last name: `Roberts`
* login: `pierce`, First name: `Walter`, Last name: `Pierce`

Assign the *bpm-process-actor* role to the users in order to grant access to BPM entities.

Create the *quick-start* role and grant it the necessary permissions to work with the project:

. Go to *Administration -> Roles* screen and create a new role with the *quick-start* role.
. In the *Screens* tab allow *BPM -> Process Tasks* screen. It is not allowed in *bpm-process-actor* role because it may not be needed for some projects.
. Also, allow the screens:
+
* *Application ->Contracts*
* *bpm$ProcTask.edit*
* *bpmdemo_Contract.edit*
* *bpm$ProcInstance.edit*
+
. Allow *bpmdemo_Contract* in the *Entities* and *Attributes* tabs.
. Save the role.

Assign the *quick-start* role to the users .