:sourcesdir: ../../../../../source

[[soft_deletion]]
===== Мягкое удаление

Платформа CUBA поддерживает режим "мягкого удаления" данных - когда вместо удаления записей из базы данных они только помечаются определенным образом и становятся недоступными для обычного использования. В дальнейшем такие записи можно либо совсем удалить из БД с помощью отдельной регламентной процедуры, либо восстановить.

Механизм мягкого удаления является "прозрачным" для прикладного программиста - достаточно убедиться, что класс сущности реализует интерфейс `SoftDelete`, и платформа сама нужным образом будет модифицировать запросы и операции с данными.

Режим мягкого удаления имеет следующие преимущества:

* значительно снижается риск потери данных вследствие неверных действий пользователей

* позволяет быстро сделать некоторые записи недоступными, даже если на них имеются ссылки. 
+
Возьмем для примера модель данных `Заказы` - `Покупатели`. Допустим, на некоторого покупателя оформлено несколько заказов, однако нам нужно сделать его недоступным для дальнейшей работы пользователей. Традиционным "жестким" удалением сделать это невозможно, так как для удаления покупателя нам нужно либо удалить все его заказы, либо обнулить в этих заказах ссылки на него (т.е. потерять информацию). При мягком удалении покупателя он становится недоступным для поиска и изменения, однако при просмотре заказов пользователь видит на экране имя покупателя, так как при загрузке связей признак удаления намеренно игнорируется.
+
Описанное поведение является стандартным, но может быть модифицировано с помощью <<delete_policy,политики обработки связей>> при удалении.

Восстановить удалённые сущности можно через экран *Restore Deleted Entities*, по умолчанию доступный в стандартном меню *Administration* приложения. Эта функциональность предназначена для использования администраторами системы, имеющими <<permissions,разрешения>> на все сущности. Её следует использовать с осторожностью, также рекомендуется ограничить доступ к этому экрану для простых пользователей системы.

Отрицательной стороной мягкого удаления является увеличение объема базы данных и потенциальная необходимость дополнительных процедур ее очистки.

include::soft_deletion/soft_deletion_usage.adoc[]

include::soft_deletion/delete_policy.adoc[]

include::soft_deletion/soft_deletion_unique_constr.adoc[]

