:sourcesdir: ../../../../source

[[legacy_roles]]
==== Legacy Roles and Permissions

Before CUBA 7.2, the method of calculating effective permissions was different. A permission could be granted either explicitly by specifying "allow/deny" for a target, or by a role of a certain type, e.g. "Denying" role gave "deny" permissions to all targets except entity attributes. If a target took no explicit permission or permission by a role type, it was fully available to the user. As a result, a user without roles at all had all rights to the system.

It was recommended to give regular users first a "Denying" role, and then a set of roles with explicit allowing permissions. Now the denying role is not needed because users have no rights to a target, unless an appropriate permission is given to them by a role.

Also, in the previous versions, there were no <<security_scope,security scopes>>, so all roles affected both Generic UI and REST API clients.

If you are migrating to CUBA 7.2 from a previous version and want to keep your existing security configuration, follow the steps below to switch the security subsystem to the legacy behavior.

In `core` module, set properties for legacy permissions calculation method and using <<default-permission-values.xml>> configuration file:

.app.properties
[source,properties]
----
cuba.security.undefinedAccessPolicy = ALLOW
cuba.security.defaultPermissionValuesConfigEnabled = true
----

If your project uses the REST API add-on, add the following property in the `web` module to set REST security scope to the same value as used by the Generic UI:

.web-app.properties
[source,properties]
----
cuba.rest.securityScope = GENERIC_UI
----