:sourcesdir: ../../../../source

[[login_screen]]
==== Login Screen

The login screen provides the ability to register within the system with a login name and password. The login name is case-insensitive.

The Web Client's *Remember Me* checkbox can be configured by using the <<cuba.web.rememberMeEnabled,cuba.web.rememberMeEnabled>> application property. The drop-down list of supported languages on the standard login screen can be configured with the <<cuba.localeSelectVisible,cuba.localeSelectVisible>> and <<cuba.availableLocales,cuba.availableLocales>> application properties.

See also the <<cuba.web.loginDialogDefaultUser,cuba.web.loginDialogDefaultUser>>, <<cuba.web.loginDialogDefaultPassword,cuba.web.loginDialogDefaultPassword>> and <<cuba.web.loginDialogPoweredByLinkVisible,cuba.web.loginDialogPoweredByLinkVisible>> application properties.

In Web Client, the standard login window can be customized or completely replaced in the project using CUBA Studio. Select *Generic UI* in the project tree and click *New > Screen* in the context menu. Then select the *Login window* template on the *Legacy Screen Templates* tab. The new `ext-loginWindow.xml` file will be created in the Web module and automatically registered in the `web-screens.xml`. See also <<gui_web,>>.

The platform has a mechanism for the protection against password brute force cracking: see the <<cuba.bruteForceProtection.enabled,cuba.bruteForceProtection.enabled>> application property.

For deeper customization of the authentication procedure, see <<login>> and <<web_login>> sections.

The appearance of the `Login Screen` can be customized using SCSS variables with `$cuba-login-*` prefix. You can change these variables in the visual editor after creating a <<web_theme_extension,theme extension>> or a <<web_theme_creation,custom theme>>.

