:sourcesdir: ../../../../source

[[permissions]]
==== Permissions

_Permissions_ determine the user's right to application objects and functions, such as UI screens or entity operations. With regards to permissions, these objects are called _targets_.

Permissions are granted to users by assigning <<roles,roles>> to them.

[TIP]
====
Users have no rights to a target, unless an appropriate permission is given to them by a role. So users without roles have no any rights and cannot access the system through the Generic UI and REST API.
====

There are the following types of permissions differentiated by targets:

Screen permissions::
+
A screen can be either allowed or denied.
+
The screen permissions are checked by the framework when building the main menu and creating screens using the `create()` method of the `Screens` interface. To check screen permissions in the application code, use the `isScreenPermitted()` method of the <<security,Security>> interface.

Entity operation permissions::
+
For each entity, the following permissions can be allowed: Create, Read, Update, Delete.
+
See the <<data_access_checks>> section for how entity operation permissions are used by different mechanisms of the framework. To check entity operation permissions in the application code, use the `isEntityOpPermitted()` method of the <<security,Security>> interface.

Entity attribute permissions::
+
Each attribute of each entity can be allowed for viewing or for modification.
+
See the <<data_access_checks>> section for how entity attribute permissions are used by different mechanisms of the framework. To check entity attribute permissions in the application code, use the `isEntityAttrPermitted()` method of the <<security,Security>> interface.

Specific permissions::
+
These are permissions on arbitrary named functionality. Specific permissions for the project are set in the <<permissions.xml,permissions.xml>> configuration file.
+
An example of checking a specific permission :
+
[source, java]
----
@Inject
private Security security;

public void calculateBalance() {
    if (!security.isSpecificPermitted("myapp.calculateBalance"))
        return;
    // ...
}
----

Screen component permissions::
+
--
Screen component permissions allow you to hide or make read-only particular UI components of a screen, regardless of whether they are bound to entities or not. Screen component permissions are applied by the framework after sending <<screen_AfterInitEvent,AfterInitEvent>> and before <<screen_BeforeShowEvent,BeforeShowEvent>>.

[TIP]
====
The screen component permissions differ from other permission types in that they actually only restrict rights to their targets. Until you define a target component and a hidden/read-only permission for it, the component is fully available to the user.
====

The target component is specified by its path in the screen according to the following rules:

* If the component belongs to the screen, simply specify the component identifier.

* If the component belongs to the fragment that is embedded within the screen, specify the fragment identifier, and then the component identifier separated by period.

* If configuring permission for the <<gui_TabSheet>> tab or the <<gui_Form>> field, specify the component identifier, and then the tab or field identifier in square brackets.

* To configure permission for an <<gui_Action,action>>, specify the component, holding the action, and then the action identifier in angle brackets. For example: `customersTable<changeGrade>`.
--
