:sourcesdir: ../../../../source

[[db_update_in_prod_by_server]]
==== Использование механизма выполнения скриптов БД сервером

<<db_update_server,Механизм выполнения скриптов БД сервером>> можно использовать как для первичной инициализации базы данных, так и для ее последующего обновления в процессе развития приложения и изменения схемы данных.

Чтобы инициализировать новую базу данных, нужно выполнить следующее:

* Включите свойство приложения <<cuba.automaticDatabaseUpdate,cuba.automaticDatabaseUpdate>>, добавив следующую строку в файл <<app_properties_files,local.app.properties>> блока Middleware:
+
[source, properties]
----
cuba.automaticDatabaseUpdate = true
----
+
В случае <<fast_deployment,быстрого развертывания>> в Tomcat этот файл находится в каталоге `tomcat/conf/app-core`. Если файл не существует, создайте его.

* Создайте пустую базу данных, соответствующую URL, заданному в описании источника данных в <<context.xml,context.xml>>.

* Запустите сервер приложения, содержащий блок *Middleware*. На старте приложения БД будет проинициализирована и сразу же готова к работе.

В дальнейшем при каждом старте сервера приложения механизм выполнения скриптов будет сравнивать набор скриптов, находящийся в <<db_dir,каталоге скриптов базы данных>>, со списком выполненных скриптов, зарегистрированным в БД. При появлении в каталоге новых скриптов они будут выполнены и также зарегистрированы. Таким образом, достаточно в каждую новую версию приложения включать скрипты обновления, и при рестарте сервера приложения база данных будет приводиться в актуальное состояние.

При эксплуатации механизма выполнения скриптов на старте сервера следует иметь в виду следующее:

* При любой ошибке выполнения скрипта блок *Middleware* прерывает инициализацию и становится неработоспособным. Клиентские блоки выдают сообщения о невозможности подключения к *Middleware*.
+
Для выяснения причин сбоя необходимо открыть файл лога `app.log` в <<log_dir,каталоге журналов>> сервера и найти сообщения о выполнении SQL от логгера `com.haulmont.cuba.core.sys.DbUpdaterEngine`, и, возможно, последующие сообщения об ошибках.

* Скрипты обновления, а также отделенные символом "^" команды DDL и SQL внутри скриптов выполняются в отдельных транзакциях. Поэтому при возникновении ошибки при обновлении существует большая вероятность того, что часть скриптов, или даже отдельных команд последнего скрипта, выполнилась и зафиксирована в БД.
+
В связи с этим рекомендуется непосредственно перед запуском сервера с новой версией приложения делать резервное сохранение БД. Тогда после устранения причины ошибки достаточно восстановить БД и запустить автоматический процесс вновь.
+
Если бэкап БД отсутствует, то после устранения причины ошибки необходимо выяснить, какая часть вызвавшего ошибку скрипта выполнилась и закоммичена. Если скрипт не выполнился целиком, то можно сразу снова запускать автоматический процесс. Если же часть команд до ошибочной была отделена символом "^", выполнялась в отдельной транзакции и была закоммичена, то необходимо выполнить оставшуюся часть команд, а затем зарегистрировать данный скрипт в *SYS_DB_CHANGELOG* вручную. После этого можно стартовать сервер, механизм автоматического обновления продолжит работу со следующего невыполненного скрипта.
+
CUBA Studio генерирует скрипты обновления с символом ";" в качестве разделителями для всех типов БД, кроме Oracle. Если команды скрипта разделены точками с запятой, они выполняются в одной транзакции, и в случае ошибки скрипт откатывается целиком. Тем самым обеспечивается постоянное соответствие между структурой БД и списком выполненных скриптов обновления.

