:sourcesdir: ../../../../../source

[[screen_agent]]
===== Screen Agent

Screen agent enables choosing a screen template according to the current device and display parameters. For example, you can create two screens with different layouts (and possibly different functionality), and register them in <<screens.xml,screens.xml>> with the same identifier. Then at runtime, the platform will choose a screen that better conforms to the display from which the user accesses the application.

There are three predefined screen agents in the platform: `DESKTOP`, `TABLET`, `PHONE`. They are defined by the following classes respectively: `DesktopScreenAgent`, `TabletScreenAgent`, `PhoneScreenAgent`. You can define your own agents by creating <<managed_beans,managed beans>> implementing the `ScreenAgent` interface.

A screen agent is specified for a screen in the <<screens.xml,screens.xml>> file. The value of the `agent` attribute should be either one of the predefined constants listed above or a name of the custom bean implementing `ScreenAgent`.

In Studio, an agent is specified on the *Properties* tab of the screen designer page.


