:sourcesdir: ../../../source

[[gui_framework]]
=== Generic User Interface

The Generic User Interface (Generic UI, GUI) framework allows you to create UI screens using Java and XML. XML is optional but it provides a declarative approach to the screen layout and reduces the amount of code which is required for building the user interface.

.The Structure of Generic User Interface 
image::ClientStructure.svg[align="center"]

The application screens consist of the following parts:

* <<screen_descriptors,Descriptors>> – XML files for declarative definition of the screen layout and data components.
* <<screen_controllers,Controllers>> – Java classes for handling events generated by the screen and its UI controls and for programmatic manipulation with the screen components.

The code of application screens interacts with visual component interfaces (VCL Interfaces). These interfaces are implemented using the Vaadin framework components.

<<gui_vcl,Visual Components Library>> (VCL) contains a large set of ready-to-use components.

<<gui_data,Data components>> provide a unified interface for binding visual components to entities and for working with entities in screen controllers.

<<gui_web,Infrastructure>> includes the main application window and other common client mechanisms.

include::gui_framework/gui_screens.adoc[]

include::gui_framework/gui_vcl.adoc[]

include::gui_framework/gui_data.adoc[]

include::gui_framework/gui_Action.adoc[]

include::gui_framework/gui_dialogs.adoc[]

include::gui_framework/gui_notifications.adoc[]

include::gui_framework/background_tasks.adoc[]

include::gui_framework/gui_themes.adoc[]

include::gui_framework/gui_icons.adoc[]

include::gui_framework/html_attributes.adoc[]

include::gui_framework/shortcuts.adoc[]

include::gui_framework/url_history_navigation.adoc[]

include::gui_framework/pluggable_component_factories.adoc[]

include::gui_framework/webComponentsHelper.adoc[]

include::gui_framework/own_components.adoc[]

include::gui_framework/gui_web.adoc[]

include::gui_framework/main_window_layout.adoc[]

include::gui_framework/web_login.adoc[]

include::gui_framework/unsupported_browser_page.adoc[]
