:sourcesdir: ../../../source

[[polymer_ui]]
=== Polymer User Interface

The Polymer UI client <<app_tiers,block>> provides an ability to quickly create front-end portals with mobile-first responsive web UI. It is based on https://www.polymer-project.org[Google Polymer] framework and enables tight integration with mobile browsers for adding web applications to the device home screen and for offline work.

The CUBA platform Polymer UI has the following features:

* The Polymer build system is fully integrated into the project build system based on Gradle, so all building tools are downloaded and installed automatically. At the same time, once the Polymer module is created in the project, it can be developed further by front-end developers separately using the standard Polymer toolchain.

* The platform provides a set of web components for working with the middleware through the standard CUBA <<rest_api_v2,REST API>>. The components are described <<cuba_web_components,below>>.

* CUBA Studio enables easy creation of the Polymer client module and scaffolding of the application web components around the data model and middleware services of the project. Studio contains an extendable set of templates for creation of application level components.

Our current approach is to stick to Polymer’s https://www.polymer-project.org/2.0/start/install-2-0[techniques and tools] which are used for creating https://developers.google.com/web/progressive-web-apps/[Progressive Web Apps]. The aim is to follow Polymer's guidelines and best practices to provide similar learning curve and development experience. Polymer applications have component-based architecture and consist of https://www.webcomponents.org/[Web Components].

By default, the UI generated by Studio is based on https://www.webcomponents.org/collection/PolymerElements/paper-elements[paper-elements] - a set of elements by Polymer team which implement Google's
http://www.google.com/design/spec/material-design/introduction.html[material design] guidelines. It is possible to use other components by specifying custom templates in Studio.

In order to start developing effectively, you need to be familiar with basic Polymer concepts. Here is a very quick intro to the Polymer:
https://github.com/Polymer/polymer#polymer-in-1-minute. However, it’s better to learn it more in depth: https://www.polymer-project.org/2.0/start/. Since the Polymer is built around the standards by learning it in most cases you learn the web platform itself.

include::polymer_ui/polymer_requirements.adoc[]

include::polymer_ui/polymer_supported_browsers.adoc[]

include::polymer_ui/polymer_in_studio.adoc[]

include::polymer_ui/polymer_build_and_structure.adoc[]

include::polymer_ui/cuba_web_components.adoc[]

include::polymer_ui/polymer_styling.adoc[]

include::polymer_ui/polymer_offline.adoc[]

include::polymer_ui/polymer2_typescript.adoc[]

include::polymer_ui/polymer_troubleshooting.adoc[]

