:sourcesdir: ../../../../../../source

[[screen_controller_methods]]
====== Методы контроллеров

В данном разделе описаны некоторые методы базовых классов контроллеров экранов, которые можно вызывать или переопределять в коде приложения.

[[screen_methods]]
Общие для всех экранов методы::
+
--
* `show()` - отображает экран. Данный метод обычно вызывается после создания экрана, как описано в разделе <<opening_screens>>.

* `close()` - закрывает экран с переданным значением `StandardOutcome` или объектом `CloseAction`. Например:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_methods_1.java[]
----
+
Значение параметра доступно в <<screen_BeforeCloseEvent,BeforeCloseEvent>> и <<screen_AfterCloseEvent,AfterCloseEvent>>, поэтому информация о причине закрытия экрана может быть получена в слушателях этих событий. Подробная информация об использовании этих слушателей приведена в разделе <<screen_return_values,Выполнение кода после закрытия и возврат значений>>.

* `getScreenData()` - возвращает объект `ScreenData`, в котором зарегистрированы все <<gui_data,компоненты данных>>, объявленные в XML-дескрипторе экрана. Метод `loadAll()` этого объекта можно вызывать для срабатывания всех загрузчиков данных экрана:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_methods_2.java[]
----

* `getSettings()` - возвращает объект `Settings`, который может быть использован для чтения и записи специфичных настроек, ассоциированных с экраном для данного пользователя.

* `saveSettings()` - сохраняет настройки экрана, представляемые объектом `Settings`. Данный метод вызывается автоматически, если свойство приложения <<cuba.gui.manualScreenSettingsSaving,cuba.gui.manualScreenSettingsSaving>> установлено в false (что является значением по умолчанию).
--

[[standardEditor_methods]]
Методы StandardEditor::
+
--
* `getEditedEntity()` - когда экран открыт, возвращает экземпляр редактируемой сущности. Это экземпляр, установленный в контейнере данных, указанном аннотацией <<EditedEntityContainer_annotation,@EditedEntityContainer>>.
+
В слушателях <<screen_InitEvent,InitEvent>> и <<screen_AfterInitEvent,AfterInitEvent>> данный метод возвращает null. В слушателе <<screen_BeforeShowEvent,BeforeShowEvent>> данный метод возвращает экземпляр, переданный в экран для редактирования (позднее в процессе открытия экрана сущность перезагружается, и другой ее экземпляр устанавливается в контейнере данных).

Для закрытия экрана редактирования можно использовать следующие методы:

* `closeWithCommit()` - валидирует и сохраняет данные, затем закрывает экран с `StandardOutcome.COMMIT`.

* `closeWithDiscard()` - игнорирует несохраненные изменения и закрывает экран с `StandardOutcome.DISCARD`.

Если в экране есть несохраненные изменения в <<gui_DataContext,DataContext>>, при закрытии экрана отображается соответствующее сообщение. Вид данного сообщения можно настроить с помощью свойства приложения <<cuba.gui.useSaveConfirmation,cuba.gui.useSaveConfirmation>>. Если экран закрывается методом `closeWithDiscard()` или `close(StandardOutcome.DISCARD)` то несохраненные изменения игнорируются без каких-либо сообщений.

* `commitChanges()` - сохраняет изменения не закрывая экран. Данный метод можно вызвать из собственного слушателя события (например нажатия кнопки), или переопределить слушатель действия `windowCommit`, чтобы выполнить какие-либо операции после сохранения данных. Пример переопределения стандартного действия `windowCommit`:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_methods_3.java[]
----
+
Стандартная реализация метода `commit()` отображает сообщение об успешном сохранении. Ее можно отключить, вызвав метод `setShowSaveNotification(false)` при инициализации экрана.

* Метод `validateAdditionalRules()` можно переопределить для выполнения дополнительной валидации перед сохранением данных. Данный метод должен сохранить информацию об ошибках валидации в переданном ему объекте `ValidationErrors`. Впоследствии эта информация будет отображена вместе с ошибками стандартной процедуры валидации. Например:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_methods_4.java[]
----
--

[[masterDetailScreen_methods]]
Методы MasterDetailScreen::
+
--
* `getEditedEntity()` - когда когда находится в режиме редактирования, возвращает экземпляр редактируемой сущности. Это экземпляр, установленный в контейнере данных компонента `form`. Если экран не в режиме редактирования, данный метод выбрасывает `IllegalStateException`.

* Метод `validateAdditionalRules()` можно переопределить для выполнения дополнительной валидации перед сохранением данных, как описано выше для `StandardEditor`.
--