:sourcesdir: ../../../../../../source

[[screen_controller_methods]]
====== Методы контроллеров

Ниже описаны некоторые методы контроллеров экранов, которые вы можете вызывать из вашего кода.

[[screen_close]]
* `close()` - закрытие данного экрана, вызываемое переданным действием или, в случае экрана выбора или редактирования экземпляра сущности, с одним из стандартных значений перечисления `StandardOutcome`. Действие, переданное методу в качестве параметра, передаётся событиям <<screen_BeforeCloseEvent,BeforeCloseEvent>> и <<screen_AfterCloseEvent,AfterCloseEvent>>. Таким образом, заинтересованный код может получить информацию о причине закрытия экрана от кода, инициирующего закрытие.
+
--
В частности, в экранах редактирования сущностей при закрытии экрана после коммита изменений рекомендуется использовать константу `++Window.COMMIT_ACTION_ID++`, без коммита изменений - константу `++Window.CLOSE_ACTION_ID++`.

Если какой-либо из контейнеров данных содержит несохраненные изменения, перед закрытием экрана будет выдано диалоговое окно с соответствующим предупреждением. Тип предупреждения можно выбрать с помощью свойства приложения <<cuba.gui.useSaveConfirmation,cuba.gui.useSaveConfirmation>>.

Метод `close()` возвращает статус `Status.SUCCESS`, если экран был успешно закрыт, и статус `++Status.FAIL++`, если закрытие было прервано.

Примеры использования данного API см. в разделе <<screen_return_values,Выполнение кода после закрытия и возврат значений>>.
--

[[screen_closeWithDefaultAction]]
* `closeWithDefaultAction()` - закрытие экрана стандартным действием `++Window.CLOSE_ACTION_ID++`.

[[screen_closeWithCommit]]
* `closeWithCommit()` - попытка закрытия экрана с коммитом данных. Если данные сохранены успешно, экран будет закрыт действием `++Window.COMMIT_ACTION_ID++`. Перед закрытием экрана могут отобразиться ошибки валидации или дополнительное диалоговое окно.

[[screen_closeWithDiscard]]
* `closeWithDiscard()` - закрытие окна действием `++Window.CLOSE_ACTION_ID++`, несохраненные данные игнорируются.

[[screen_getEditedEntity]]
* `getEditedEntity()` -  возвращает экземпляр редактируемой сущности, установленный в главном контейнере данных экрана (т.е. в контейнере с типом `InstanceContainer`, указанном в аннотации <<EditedEntityContainer_annotation,@EditedEntityContainer>>).

[[screen_validateAdditionalRules]]
Валидация экрана::
+
--
Для дополнительной валидации экрана в контроллере можно реализовать шаблонный метод `validateAdditionalRules()`.
Получаемый методом объект `ValidationErrors` используется для добавления информации об ошибках валидации, которая будет отображена совместно с ошибками стандартной валидации:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_methods.java[]
----
--