:sourcesdir: ../../../../../../source

[[screen_controller_events]]
====== События Screen

Ниже описаны события жизненного цикла экрана, на которые можно подписаться в контроллере для реализации необходимой бизнес-логики.

[TIP]
====
Руководство https://www.cuba-platform.com/guides/decouple-business-logic-with-app-events#cuba_ui_events[Decouple Business Logic with Application Events] содержит примеры использования событий в UI.
====

'''

<<screen_InitEvent,InitEvent>>

<<screen_AfterInitEvent,AfterInitEvent>>

<<screen_InitEntityEvent,InitEntityEvent>>

<<screen_BeforeShowEvent,BeforeShowEvent>>

<<screen_AfterShowEvent,AfterShowEvent>>

<<screen_BeforeCommitChangesEvent,BeforeCommitChangesEvent>>

<<screen_AfterCommitChangesEvent,AfterCommitChangesEvent>>

<<screen_BeforeCloseEvent,BeforeCloseEvent>>

<<screen_AfterCloseEvent,AfterCloseEvent>>

<<screen_AfterDetachEvent,AfterDetachEvent>>

<<screen_UrlParamsChangedEvent,UrlParamsChangedEvent>>

'''

[[screen_InitEvent]]
InitEvent::
+
--
`InitEvent` посылается, когда контроллер экрана и все его компоненты, заданные декларативно, созданы, а инжекция зависимостей завершена. Вложенные фрагменты на этом этапе ещё не инициализированы. Некоторые визуальные компоненты инициализированы не полностью: например, кнопки ещё не связаны с действиями.

[source, java]
----
include::{sourcesdir}/gui/screens/screen_InitEvent.java[]
----
--

[[screen_AfterInitEvent]]
AfterInitEvent::
+
--
`AfterInitEvent` посылается, когда контроллер экрана и все его компоненты, заданные декларативно, созданы, инжекция зависимостей завершена, и все компоненты завершили свою внутреннюю процедуру инициализации. Вложенные фрагменты (при наличии) опубликовали свои события `InitEvent` и `AfterInitEvent`. В слушателе этого события можно создавать визуальные компоненты и компоненты данных, а также выполнить дополнительную инициализацию, если она зависит от инициализации вложенных фрагментов.
--

[[screen_InitEntityEvent]]
InitEntityEvent::
+
--
`InitEntityEvent` посылается в экранах, унаследованных от `StandardEditor` и `MasterDetailScreen`, перед тем, как новый экземпляр сущности будет установлен для контейнера редактируемой сущности.

[TIP]
====
Руководство https://www.cuba-platform.com/guides/initial-entity-values#internal_initialization_via_initentityevent[Initial Entity Values] содержит пример инициализации сущности с помощью `InitEntityEvent`.
====

Используйте слушатель этого события, чтобы инициализировать значения по умолчанию для новых экземпляров сущностей, например:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_InitEntityEvent.java[]
----
--

[[screen_BeforeShowEvent]]
BeforeShowEvent::
+
--
`BeforeShowEvent` посылается непосредственно перед тем, как экран будет отображён, иными словами, на этом этапе он ещё не добавлен к интерфейсу приложения. Ограничения безопасности уже применены к компонентам UI. Сохранённые настройки состояния компонентов UI ещё не применены. Данные ещё не загружены в экраны с аннотацией `@LoadDataBeforeShow`. В слушателе этого события можно загружать данные, проверять разрешения безопасности, а также изменять компоненты интерфейса. Например:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeShowEvent.java[]
----
--

[[screen_AfterShowEvent]]
AfterShowEvent::
+
--
* `AfterShowEvent` посылается сразу после отображения экрана, то есть тогда, когда экран уже добавлен к интерфейсу приложения. На этом этапе применены сохранённые настройки состояния компонентов UI. В слушателе этого события можно отображать уведомления, диалоговые окна или другие экраны. Например:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_AfterShowEvent.java[]
----
--

[[screen_BeforeCommitChangesEvent]]
BeforeCommitChangesEvent::
+
--
`BeforeCommitChangesEvent` посылается в экранах, унаследованных от `StandardEditor` и `MasterDetailScreen`, перед сохранением измененных данных методом `commitChanges()`. В слушателе этого события можно проверить какие-либо условия и прервать или продолжить операцию сохранения с помощью методов `preventCommit()` и `resume()` объекта события.

Рассмотрим некоторые варианты использования.

. Прервать операцию сохранения с выводом уведомления:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeCommitChangesEvent_1.java[]
----

. Прервать операцию сохранения, показать диалог и продолжить после подтверждения пользователем:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeCommitChangesEvent_2.java[]
----

. Прервать операцию сохранения, показать диалог и повторить `commitChanges()` после подтверждения пользователем:
+
[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeCommitChangesEvent_3.java[]
----
--

[[screen_AfterCommitChangesEvent]]
AfterCommitChangesEvent::
+
--
`AfterCommitChangesEvent` посылается в экранах, унаследованных от `StandardEditor` и `MasterDetailScreen`, после сохранения измененных данных методом `commitChanges()`. Пример использования:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_AfterCommitChangesEvent.java[]
----
--

[[screen_BeforeCloseEvent]]
BeforeCloseEvent::
+
--
`BeforeCloseEvent` посылается непосредственно перед закрытием экрана с помощью метода `close(CloseAction)`. На этом этапе экран ещё отображается и полностью функционален. Настройки состояния компонентов ещё не сохранялись. В слушателе этого события можно проверить некоторые условия и предотвратить закрытие экрана, используя метод события `preventWindowClose()`, например:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_BeforeCloseEvent.java[]
----

Одноимённый метод также определён в интерфейсе `Window`. Он вызывается перед тем, как экран будет закрыт неким внешним (относительно контроллера) действием, таким как нажатие кнопки во вкладке окна или клавиши Esc на клавиатуре. Способ, которым экран был закрыт, можно получить с помощью метода `getCloseOrigin()`, который возвращает значение в виде объекта, реализующего интерфейс `CloseOrigin`. Реализация этого интерфейса по умолчанию `CloseOriginType` включает в себя три значения:

** `BREADCRUMBS` - экран закрыт по клику на цепочке ссылок (breadcrumbs).
** `CLOSE_BUTTON` - экран закрыт по нажатию на кнопку закрытия в заголовке окна, на кнопку закрытия вкладки или через действия в контекстном меню: Close, Close All, Close Others.
** `SHORTCUT` - экран закрыт нажатием горячих клавиш, определённых в свойстве приложения <<shortcuts,cuba.gui.closeShortcut>>.

Вы можете подписаться на событие `Window.BeforeCloseEvent`, указав `Target.FRAME` в аннотации `@Subscribe`:

[source, java]
----
include::{sourcesdir}/gui/screens/window_BeforeCloseEvent.java[]
----
--

[[screen_AfterCloseEvent]]
AfterCloseEvent::
+
--
`AfterCloseEvent` посылается после того, как экран будет закрыт методом `close(CloseAction)`, и после события `Screen.AfterDetachEvent`. Настройки состояния компонентов сохранены. Слушатель этого события можно использовать для вывода уведомлений или диалоговых окон после закрытия экрана, например:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_AfterCloseEvent.java[]
----
--

[[screen_AfterDetachEvent]]
AfterDetachEvent::
+
--
`AfterDetachEvent` посылается после того, как экран удаляется из интерфейса приложения после закрытия экрана пользователем или выхода пользователя из системы. Слушатель этого события можно использовать для освобождения ресурсов, захваченных экраном. Обратите внимание, что при истечении HTTP-сессии это событие не публикуется.
--

[[screen_UrlParamsChangedEvent]]
UrlParamsChangedEvent::
+
--
[[screen_UrlParamsChangedEvent]]
`UrlParamsChangedEvent` посылается, когда изменяются параметры URL браузера, соответствующие данному экрану. Событие вызывается перед отображением экрана, что позволяет произвести некоторую подготовительную работу. В слушателе этого события можно загружать данные или изменять состояние элементов управления в экране в соответствии с новыми параметрами:

[source, java]
----
include::{sourcesdir}/gui/screens/screen_UrlParamsChangedEvent.java[]
----
--