:sourcesdir: ../../../../../../source

[[abstractFrame]]
====== AbstractFrame

[WARNING]
====
Это устаревший API. Новый API, доступный начиная с v.7.0, описан в разделе <<screen_controllers>>.
====

`AbstractFrame` является корнем иерархии классов контроллеров. Рассмотрим его основные методы:

[[abstractFrame_init]]
* `init()` - вызывается фреймворком после создания всего дерева компонентов, описанного XML-дескриптором, но до отображения экрана.
+
--
В метод `init()` из вызывающего кода передается мэп параметров, которые могут быть использованы внутри контроллера. Эти параметры могут быть переданы как из кода контроллера вызывающего экрана (в методе `openWindow()`, `openLookup()` или `openEditor()`), так и установлены в файле регистрации экранов <<screens.xml,screens.xml>>.

Метод `init()` следует имплементировать при необходимости инициализации компонентов экрана, например:

[source, java]
----
include::{sourcesdir}/gui/abstractframe_1.java[]
----
--

[[abstractFrame_getMessage]]
* `getMessage()`, `formatMessage()` - методы получения локализованных сообщений из <<message_packs,пакета>>, заданного для экрана в XML-дескрипторе. Представляют собой просто короткие варианты вызова одноименных методов интерфейса <<messages,Messages>>.

[[abstractFrame_openFrame]]
* `openFrame()` - загрузить фрейм по идентификатору, зарегистрированному в <<screens.xml,screens.xml>>, и, если в метод передан компонент-контейнер, отобразить его внутри контейнера. Возвращается контроллер фрейма. Например:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_3.java[]
----
+
Контейнер не обязательно сразу передавать в метод `openFrame()`, вместо этого можно загрузить фрейм, а затем добавить его в нужный контейнер:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_4.java[]
----

[[abstractFrame_openWindow]]
* `openWindow()`, `openLookup()`, `openEditor()` - открыть соответственно простой экран, экран выбора или редактирования. Методы возвращают контроллер созданного экрана.
+
При открытии экрана в режиме диалога метод `openWindow()` может быть вызван с параметрами, к примеру:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_7.java[]
----
Эти параметры будут учитываться, если они не конфликтуют с более приоритетными параметрами самого вызываемого экрана. Последние могут быть заданы в методе <<dialogOptions,getDialogOptions()>> контроллера экрана или в <<screen_xml,XML-дескрипторе>> этого экрана:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_8.xml[]
----
+
Для выполнения действий после закрытия вызываемого экрана необходимо добавить слушатель типа `CloseListener`, например:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_5.java[]
----
+
`CloseWithCommitListener` можно использовать в случае, если необходимо реагировать только при закрытии экрана действием с именем `Window.COMMIT_ACTION_ID` (то есть кнопкой *OK*), например:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_5_1.java[]
----

[[abstractFrame_showMessageDialog]]
* `showMessageDialog()` - отобразить диалоговое окно с сообщением.

[[abstractFrame_showOptionDialog]]
* `showOptionDialog()` - отобразить диалоговое окно с сообщением и возможностью выбора пользователем некоторых действий. Действия задаются массивом объектов типа <<gui_Action,Action>>, которые в диалоге отображаются посредством соответствующих кнопок.
+
Для отображения стандартных кнопок типа *OK*, *Cancel* и других рекомендуется использовать объекты типа `DialogAction`, например:
+
[source, java]
----
include::{sourcesdir}/gui/abstractframe_6.java[]
----

[[abstractFrame_showNotification]]
* `showNotification()` - отобразить всплывающее окно с сообщением.

[[abstractFrame_showWebPage]]
* `showWebPage()` - открыть указанную веб-страницу в браузере.

'''

API::
<<abstractFrame_getMessage,formatMessage()>> -
<<abstractFrame_getMessage,getMessage()>> -
<<abstractFrame_init,init()>> -
<<abstractFrame_openFrame,openFrame()>> -
<<abstractFrame_openWindow,openEditor()>> -
<<abstractFrame_openWindow,openLookup()>> -
<<abstractFrame_openWindow,openWindow()>> -
<<abstractFrame_showMessageDialog,showMessageDialog()>> -
<<abstractFrame_showNotification,showNotification()>> -
<<abstractFrame_showOptionDialog,showOptionDialog()>> -
<<abstractFrame_showWebPage,showWebPage()>>

'''

