:sourcesdir: ../../../../../../source

[[abstractLookup]]
====== AbstractLookup

[WARNING]
====
Это устаревший API. Новый API, доступный начиная с v.7.0, описан в разделе <<screen_controllers>>.
====

`AbstractLookup` базовый класс контроллеров <<screen_lookup,экранов выбора>>, является наследником <<abstractWindow,AbstractWindow>>, и определяет следующие собственные методы:

[[abstractLookup_setLookupComponent]]
* `setLookupComponent()` - установить компонент, из которого будет производиться выбор экземпляров сущности.
+
Как правило, компонент выбора устанавливается в XML-дескрипторе экрана, и вызывать данный метод в прикладном коде нет необходимости.

[[abstractLookup_setLookupValidator]]
* `setLookupValidator()` - установить для экрана объект типа `Window.Lookup.Validator`, метод `validate()` которого вызывается фреймворком перед тем как вернуть выбранные экземпляры сущностей. Если `validate()` возвращает `false`, процесс выбора и закрытия экрана прерывается.
+
По умолчанию валидатор не установлен.

'''

API::
<<abstractLookup_setLookupComponent,setLookupComponent()>> -
<<abstractLookup_setLookupValidator,setLookupValidator()>>

'''

