:sourcesdir: ../../../../../../source

[[companions]]
====== Компаньоны контроллеров

Базовые классы контроллеров расположены в <<app_modules,модуле>> *gui* <<app_components,базового проекта>> *cuba* и не содержат ссылок на классы реализации визуальных компонентов (*Swing* или *Vaadin*), что дает возможность использовать их в клиентах обоих типов.

В то же время конкретные классы контроллеров могут быть расположены как в модуле *gui*, так и в *web* или *desktop*, в зависимости от применяемых в проекте клиентских <<app_tiers,блоков>> и специфики экрана. Если контроллер является универсальным, но для разных типов клиента требуется дополнительная функциональность, ее можно определить в так называемых _классах-компаньонах_. 

Класс-компаньон располагается в модуле клиента соответствующего типа (*web* или *desktop*) и реализует интерфейс, задаваемый в использующем его контроллере. Класс компаньона задается в элементе `companions` XML-дескриптора экрана. Контроллер может получить ссылку на экземпляр компаньона с помощью инжекции или вызовом `getCompanion()`, и в нужный момент передать ему управление, например, для дополнительной инициализации визуальных компонентов специфичным для данного типа клиента способом. 

Например, необходимо раздельно для веб и десктоп клиентов проинициализировать таблицу некоторого экрана. Тогда в контроллере экрана, расположенном в модуле *gui*, определяем интерфейс компаньона и делегируем ему инициализацию таблицы:

[source, java]
----
include::{sourcesdir}/gui/companion_1.java[]
----

В модулях *web* и *desktop* создаем соответствующие классы реализации компаньона:

[source, java]
----
include::{sourcesdir}/gui/companion_2.java[]
----

[source, java]
----
include::{sourcesdir}/gui/companion_3.java[]
----

И регистрируем классы реализации компаньона в XML-дескрипторе экрана:

[source, xml]
----
include::{sourcesdir}/gui/companion_4.xml[]
----

Так как классы-компаньоны расположены в *web* и *desktop* модулях, в них можно использовать метод `unwrap()` классов <<webComponentsHelper,WebComponentsHelper>> и <<desktopComponentsHelper,DesktopComponentsHelper>> для извлечения из интерфейса <<gui_Table,Table>> ссылок на реализующие таблицу Vaadin и Swing компоненты, и работать с ними непосредственно.

