:sourcesdir: ../../../source

[[pivotTable_extension]]
=== Exporting PivotTable Data

`PivotTableExtension` is the extension of the `PivotTable` component that provides API for downloading the table with aggregated data in the XLS format.

An instance of the extension should be created in the screen controller using the class constructor (i.e., not the `UiComponents` bean), for example:

[source, java]
----
@Inject
private PivotTable pivotTable;

private PivotTableExtension extension;

@Override
public void init(Map<String, Object> params) {
    extension = new WebPivotTableExtension(pivotTable);
}
----

[TIP]
====
The extension works only for the following <<chart_PivotTable_renderers,renderers>> types: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP`, `ROW_HEATMAP`, and doesn't get the color of cells.
====

[[pivotTable_extension_xls]]
The `exportTableToXls()` method allows you to download the table data as an XLS file, for example, on a button click:

[source, java]
----
extension.exportTableToXls();
----

By default, the downloaded file name matches the localized caption of the entity in the `PivotTable` datasource. The file name can be defined using the `setFileName()` method:

[source, java]
----
extension.setFileName("Orders of " + new Date());
----

[TIP]
====
The XLS format implies the limitation for 65536 table rows. If `PivotTable` contains more than 65536 rows, its content will be cut by the last row, and you will see the corresponding warning message.
====

[[pivotTable_extension_data]]
Additionally, the `PivotTableExtension` provides two more ways to get the `PivotTable` data:

* the JSON representation:
+
[source, java]
----
extension.getPivotDataJSON();
----

* the serialized object of `PivotData` class:
+
[source, java]
----
extension.getPivotData();
----
