:sourcesdir: ../../../source

[[pivotTable_extension]]
=== Exporting PivotTable Data

`PivotTableExtension` is the extension of the `PivotTable` component that provides API for downloading the table with aggregated data in the XLS format.

An instance of the extension should be created in the screen controller using the class constructor (i.e., not the `ComponentsFactory` bean), for example:

[source, java]
----
@Inject
private PivotTable pivotTable;

private PivotTableExtension extension;

@Override
public void init(Map<String, Object> params) {
    extension = new WebPivotTableExtension(pivotTable);
}
----

[TIP]
====
The extension works only for the following <<chart_PivotTable_renderers,renderers>> types: `TABLE`, `TABLE_BAR_CHART`, `HEATMAP`, `COL_HEATMAP`, `ROW_HEATMAP`, and doesn't get the color of cells.
====

[[pivotTable_extension_xls]]
The `exportTableToXls()` method allows you to download the table data as an XLS file, for example, on a button click:

[source, java]
----
extension.exportTableToXls();
----

By default, the downloaded file name matches the localized caption of the entity in the `PivotTable` datasource. The file name can be defined using the `setFileName()` method:

[source, java]
----
extension.setFileName("Orders of " + new Date());
----

[TIP]
====
The XLS format implies the limitation for 65536 table rows. If `PivotTable` contains more than 65536 rows, its content will be cut by the last row, and you will see the corresponding warning message.
====

[[pivotTable_extension_data]]
Additionally, the `PivotTableExtension` provides two more ways to get the `PivotTable` data:

* the JSON representation:
+
[source, java]
----
extension.getPivotDataJSON();
----

* the serialized object of `PivotData` class:
+
[source, java]
----
extension.getPivotData();
----

[[chart_PivotTable_ShowPivotAction]]
==== Export with ShowPivotAction

`ShowPivotAction` is the special action that enables exporting data from the components that extend `ListComponent`, such as `Table`, `Tree`, and `DataGrid`, as a pivot table. It provides simple means of BI analysis without no additional application components required.

The action should be created programmatically in the screen controller and set as some button's action, for example:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction.java[]
----

`ShowPivotAction` has two modes for export: all rows and selected rows. If no rows are selected, all rows will be exported by default without confirmation.

The editable `PivotTable` component will be shown in a new tab. By default, all the attributes included in the component's datasource view will be displayed, except the following:

* attributes of Collection type,
* attributes of byte array type,
* UUID attributes,
* annotated with `@SystemLevel`.

If you want to exclude certain attributes or, otherwise, include only a part of them, it can be done with the following fluent API methods:

* `withIncludedProperties()`, for example:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_2.java[]
----

* `withExcludedProperties()`, for example:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_3.java[]
----

These methods take the list of properties names, all incorrect properties names will be ignored.

You can change the default configuration of the pivot table using the `withNativeJson()` method that receives a JSON String. Note that the localized properties names should be used:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_4.java[]
----

Below is the JSON structure for a non-editable pivot table:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_5.java[]
----

And here's the JSON structure for an editable pivot table:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_6.java[]
----

The displayed pivot data can be easily exported to Excel (if the current renderer is supported). The corresponding button will be displayed by default in the opened tab.
