:sourcesdir: ../../../source

[[pivotTable_ShowPivotAction]]
=== Using ShowPivotAction

`ShowPivotAction` is a special action that enables exporting data from the components that extend `ListComponent`, such as `Table`, `Tree`, and `DataGrid`, to a pivot table. It provides simple means of BI analysis without any additional application components.

The action should be created programmatically in the screen controller and used, for example, in a button:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction.java[]
----

`ShowPivotAction` has two modes for export: all rows and selected rows. If no rows are selected, all rows will be exported by default without confirmation.

The editable `PivotTable` component will be shown in a new tab. By default, all the attributes included in the component's datasource view will be displayed, except the following:

* attributes of Collection type,
* attributes of byte array type,
* UUID attributes,
* annotated with `@SystemLevel`.

If you want to exclude certain attributes or include only a part of them, it can be done with the following fluent API methods:

* `withIncludedProperties()`, for example:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_2.java[]
----

* `withExcludedProperties()`, for example:
+
[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_3.java[]
----

These methods take the list of properties names, all incorrect properties names will be ignored.

You can change the default configuration of the pivot table using the `withNativeJson()` method that receives a JSON String. Note that the localized property names should be used:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_4.java[]
----

Below is the JSON structure for a non-editable pivot table:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_5.java[]
----

And here's the JSON structure for an editable pivot table:

[source, java]
----
include::{sourcesdir}/pivot/ShowPivotAction_6.java[]
----

The displayed pivot data can be easily exported to Excel (if the current renderer is supported). The corresponding button will be displayed by default in the opened tab.
