:sourcesdir: ../../source

[[installation]]
== Установка

Перед установкой CUBA Studio убедитесь, что на вашей рабочей машине установлено и настроено необходимое программное обеспечение, описанное в разделе {main_man_url}/setup.html[Установка и настройка инструментария] основного Руководства по разработке.

// TODO update .com to .ru as soon as the site is ready
Ниже приведены инструкции по установке CUBA Studio как приложения для различных операционных систем и в качестве плагина для IntelliJ IDEA. Установочные файлы для Windows, macOS и Linux доступны по адресу https://www.cuba-platform.com/download.

[[install_windows]]
Установка на Windows::
+
--
. Скачайте программу установки `cuba-studio-XYZ.exe`.

. Запустите инсталлер и следуйте инструкциям в появившемся окне: выберите путь к каталогу установки, тип загрузчика, имя каталога, после чего дождитесь завершения установки.

. Запустите установленное приложение.
--

[[install_macos]]
Установка на macOS::
+
--
. Скачайте программу установки `cuba-studio-XYZ.dmg`.

. Дважды щёлкните на значке инсталлера, затем перетащите файл `CUBA Studio.app` в каталог `Applications`. Если на вашем компьютере установлена более старая версия Studio, которую вы хотели бы сохранить, выберите _Keep Both_ в появившемся диалоговом окне.

. Запустите приложение *CUBA Studio*.
--

[[install_linux]]
Установка на Linux::
+
--
. Установите необходимые зависимости:
+
----
$ sudo apt-get install libgconf-2-4
----

. Скачайте архив `cuba-studio-XYZ.tar.gz`.

. Перенесите архив в подходящий каталог, например, `~/lib`, и распакуйте его:
+
----
$ tar -xvf cuba-studio-XYZ.tar.gz
----

. Перейдите в подкаталог `bin` и запустите приложение:
+
----
$ cd ~/lib/cuba-studio-XYZ/bin
$ ./cuba-studio.sh
----
--

[[install_plugin]]
Установка IntelliJ IDEA Plugin::
+
--
TODO
--