:sourcesdir: ../../source

[[installation]]
== Установка

Перед установкой CUBA Studio убедитесь, что на вашей рабочей машине установлено и настроено необходимое программное обеспечение, описанное в разделе {main_man_url}/setup.html[Установка и настройка инструментария] основного Руководства по разработке.

CUBA Studio можно установить в двух различных формах: как самостоятельное приложение для вашей операционной системы, или как плагин для имеющейся IntelliJ IDEA. Самостоятельное приложение представляет собой специальную сборку IntelliJ IDEA Community Edition, включающую в себя плагин CUBA. Если вы ранее не использовали IntelliJ IDEA, мы рекомендуем установить Studio как самостоятельное приложение.

Приложение имеет версию, соответствующую используемой версии IntelliJ IDEA, например {idea-version}. Плагин CUBA имеет свою собственную версию, начинающуюся с {plugin-version}.

Установочные файлы приложения для Windows, macOS и Linux доступны по адресу https://www.cuba-platform.com/download. Плагин доступен в репозитории плагинов IntelliJ (см. <<install_plugin,ниже>>).

[[install_windows]]
Установка на Windows::
+
--
. Скачайте программу установки `cuba-studio-XYZ.exe`.

. Запустите программу установки и следуйте инструкциям в появившемся окне: выберите путь к каталогу установки, тип загрузчика, имя каталога, после чего дождитесь завершения установки.

. Запустите установленное приложение.
--

[[install_macos]]
Установка на macOS::
+
--
. Скачайте программу установки `cuba-studio-VERSION.dmg`.

. Дважды щёлкните на программы установки, затем перетащите файл `CUBA Studio.app` в каталог `Applications`. Если на вашем компьютере установлена более старая версия Studio, которую вы хотели бы сохранить, выберите _Keep Both_ в появившемся диалоговом окне.

. Запустите приложение *CUBA Studio*.
--

[[install_linux]]
Установка на Linux::
+
--
. Установите необходимые зависимости:
+
----
$ sudo apt-get install libgconf-2-4
----

. Скачайте архив `cuba-studio-VERSION.tar.gz`.

. Перенесите архив в подходящий каталог, например, `~/lib`, и распакуйте его:
+
----
$ tar -xvf cuba-studio-VERSION.tar.gz
----

. Перейдите в подкаталог `bin` и запустите приложение:
+
----
$ cd ~/lib/cuba-studio-VERSION/bin
$ ./cuba-studio.sh
----
--

[[install_plugin]]
Установка IntelliJ IDEA Plugin::
+
--
. Запустите IntelliJ IDEA {idea-version} или более новую версию.

. Откройте диалог *Plugins*.

. Щелкните на значок "шестеренка" и выберите *Manage Plugin Repositories*.

. Щелкните *Add* и введите в поле *Repository URL* следующее значение:
+
----
https://plugins.jetbrains.com/plugins/haulmont/list
----

. После добавления репозитория, переключитесь на вкладку *Marketplace*.

. Введите следующее значение в поле поиска:
+
----
repository:"https://plugins.jetbrains.com/plugins/haulmont/list"
----

. You will see the CUBA plugin in search results.

. Click *Install* and follow further instructions of the IDE.
--