:sourcesdir: ../../source

[[release_notes]]
== Release Notes

Версия 8::
+
--
. Первое открытие проекта теперь выполняется с помощью мастера импорта проектов. См. <<open_project>> для подробной информации.

. Модель проекта теперь сохраняется в файле внутри каталога `.idea` проекта, поэтому синхронизация Gradle не запускается каждый раз при открытии проекта.

. Редактор *Run/Debug Configuration* теперь позволяет выбрать JDK, который должен использоваться для запуска сервера приложения: см. поле *JVM* на вкладке *Configuration*. По умолчанию используется значение переменной окружения `JAVA_HOME`.

. Представления (views) можно переименовывать с помощью стандартного действия *Refactor > Rename*. Это действие можно вызвать в дереве проекта CUBA, на атрибуте `name` XML-элемента `view` в файле `views.xml`, а также на любой ссылке на представление в XML-дескрипторах экранов.

. Редактор представления можно вызвать из поля *view* контейнера данных в дизайнере экрана.

. Реализовано автодополнение и поиск ссылок для атрибута `screen` XML-элемента `<fragment>` в дескрипторах экранов.

. Реализован редактор локализованных сообщений для заголовков меню. Щелкните *Generic UI > Web Menu* в дереве проекта CUBA, переключитесь на вкладку *Structure*, выберите пункт меню и нажмите *edit* в поле *Caption*.

. Реализовано предупреждение для значений перечислений, не имеющих локализованных заголовков. Если вы увидели предупреждение, используйте quick fix *Create message in the message bundle* для создания заголовка по умолчанию.

. Реализовано автодополнение для имен свойств приложения, декларированных в конфигурационных интерфейсах. Нажмите Ctrl+Space при задании свойства в файлах `app.properties` или `web-app.properties`.

. Все завершенные задачи:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.0.*%20Fixed%20in%20builds:%208.1.*[Studio 8.0-8.1 Resolved Issues\]]
--

Версия 7::
+
--
. Если ваш проект базируется на CUBA 6.10 и использует премиум-дополнения BPM, Charts, Full-Text Search или Reports, необходимо установить имя и пароль доступа к репозиторию в файле `~/.gradle/gradle.properties`, как описано в {main_man_url}/access_to_repo.html#access_to_premium_repo[Руководстве по разработке приложений]. Studio не передает имя и пароль доступа к репозиторию в Gradle.

. Все завершенные задачи:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%207.3.*%20Fixed%20in%20builds:%207.4.*[Studio 7.3-7.4 Resolved Issues\]]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.2%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.2 Resolved Issues]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.0%20Fix%20versions:%207.1%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.0-7.1 Resolved Issues]
--

:sectnums:
