:sourcesdir: ../../../../../source

[[meta_annotations]]
===== Мета-аннотации

Мета-аннотации сущностей - набор пар ключ/значение, содержащих дополнительную информацию о сущностях.

Обращение к мета-аннотациям производится с помощью метода <<metaClass,мета-класса>> `getAnnotations()`.

Источниками мета-аннотаций сущности являются:

* <<entity_annotations,Аннотации>> `@OnDelete`, `@OnDeleteInverse`, `@Extends`. При этом в мета-аннотациях создаются служебные объекты связей между сущностями. 

* Расширяемые мета-аннотации, помеченные аннотацией `@MetaAnnotation`. Эти аннотации конвертируются в мета-аннотации с ключом, соответствующими полному имени класса Java аннотации и значением, являющимся map атрибутов аннотации. Например, аннотация `@TrackEditScreenHistory` будет иметь значение, являющееся map с единственным элементом: `value -> true`. Платформа предоставляет следующие аннотации такого вида: `@NamePattern`, `@SystemLevel`, `@EnableRestore`, `@TrackEditScreenHistory`. В вашем приложении или <<app_components,компоненте>> можно создать собственные аннотации и пометить их аннотацией `@MetaAnnotation`.

* Опционально: в файлах <<metadata.xml,metadata.xml>> также могут быть определены мета-аннотации сущностей. Если мета-аннотация в XML имеет то же имя, что и мета-аннотация, созданная по Java аннотации класса сущности, первая переопределит значение второй.
+
Пример переопределения мета-аннотаций в <<metadata.xml,metadata.xml>>:
+
[source, xml]
----
include::{sourcesdir}/common/metaannotations_1.xml[]
----

