:sourcesdir: ../../../../../source

[[metadata_building]]
===== Формирование метаданных

Основной источник формирования структуры метаданных - <<entity_annotations,аннотированные>> классы сущностей. 

Класс сущности отражается в метаданных в следующих случаях: 

* Класс персистентной сущности аннотирован `@Entity`, `@Embeddable`, `@MappedSuperclass` и расположен в пределах корневого пакета, указанного в <<metadata.xml,metadata.xml>>.

* Класс неперсистентной сущности аннотирован `@MetaClass` и расположен в пределах корневого пакета, указанного в <<metadata.xml,metadata.xml>>.

Все сущности внутри одного корневого пакета помещаются в один экземпляр `MetaModel`, которому присваивается имя этого пакета. Между сущностями внутри одной `MetaModel` можно устанавливать произвольные связи, между разными - в порядке объявления файлов `metadata.xml` в свойстве <<cuba.metadataConfig,cuba.metadataConfig>>.

Атрибут сущности отражается в метаданных, если: 

* поле класса аннотировано `@Column`, `@OneToOne`, `@OneToMany`, `@ManyToOne`, `@ManyToMany`, `@Embedded`

* поле класса или метод доступа на чтение (getter) аннотирован `@MetaProperty`

Параметры мета-класса и мета-свойств формируются на основе параметров перечисленных <<entity_annotations,аннотаций>>, а также типов полей и методов класса. Кроме того, если у атрибута отсутствует метод доступа на запись (setter), атрибут становится неизменяемым (read only). 

