:sourcesdir: ../../../../source

[[entity_extension]]
==== Расширение сущности

Создадим в проекте приложения класс сущности, унаследованный от `com.haulmont.cuba.security.entity.User` и добавим в него требуемый атрибут с соответствующими методами доступа: 

[source, java]
----
include::{sourcesdir}/extension/entity_extension_1.java[]
----

В аннотации <<entity_annotation,@Entity>> должно быть указано новое имя сущности. Так как базовая сущность не объявляет <<inheritance_annotation,стратегию наследования>>, то по умолчанию это `SINGLE_TABLE`. Это означает, что унаследованная сущность будет храниться в той же таблице, что и базовая, и аннотация <<table_annotation,@Table>> не требуется. Другие аннотации базовой сущности - <<namePattern_annotation,@NamePattern>>, <<listeners_annotation,@Listeners>> и прочие - автоматически применяются к расширяющей сущности, но могут быть переопределены в ее классе.

Важным элементом класса новой сущности является аннотация `@Extends` с базовым классом в качестве параметра. Она позволяет сформировать реестр расширяющих сущностей, и заставить механизмы платформы использовать их повсеместно вместо базовых. Реестр реализуется классом `ExtendedEntities`, который является бином *Spring* с именем `cuba_ExtendedEntities`, и доступен также через интерфейс <<metadata,Metadata>>.

Добавим локализованное название нового атрибута в <<message_packs,пакет>> `com.sample.sales.entity`:

`messages.properties`

[source, properties]
----
ExtUser.address=Address
----

`messages_ru.properties`

[source, properties]
----
ExtUser.address=Адрес
----

Зарегистрируем новую сущность в файле <<persistence.xml,persistence.xml>> проекта:

[source, xml]
----
<class>com.sample.sales.entity.ExtUser</class>
----

Добавим в <<db_scripts,скрипты создания и обновления базы данных>> команду модификации соответствующей таблицы:

[source, sql]
----
include::{sourcesdir}/extension/entity_extension_2.sql[]
----

Чтобы использовать новые атрибуты сущности в экранах, создадим <<views,представления>> для новой сущности с теми же именами, что у представлений базовой сущности. Новые представления должны расширять базовые и определять новые атрибуты. Например:

[source, xml]
----
include::{sourcesdir}/extension/entity_extension_3.xml[]
----

Расширяющее представление включает в себя все атрибуты базового представления. Расширяющее представление не требуется, если базовое расширяет `_local` и вы добавляете только локальные атрибуты. Поэтому в описываемом случае данный шаг может быть пропущен.

