:sourcesdir: ../../../../source

[[servlet_registration]]
==== Регистрация сервлетов и фильтров

Чтобы использовать сервлеты и фильтры Spring Security, настроенные в <<app_components,компоненте приложения>>, их нужно зарегистрировать из компонента так, чтобы регистрация динамически распространялась и на родительское приложение. По умолчанию, в рамках одного приложения сервлеты регистрируются в файле конфигурации <<web.xml,web.xml>>, но в случае с подключением компонентов такой подход не работает.

Для динамической регистрации сервлетов и фильтров используется бин `ServletRegistrationManager`: он гарантирует, что при загрузке каждого сервлета будет использован корректный ClassLoader, и позволяет обращаться к статическим классам, таким как <<appContext,AppContext>>. Этот бин необходимо использовать для корректной работы компонентов независимо от <<deployment_variants,варианта развёртывания>> приложения.

Бин `ServletRegistrationManager` имеет два метода:

. `createServlet()` - создаёт сервлет указанного класса. Он загружает класс сервлета с нужным экземпляром `ClassLoader`, который получает из контекста приложения. Таким образом, новый сервлет может использовать статические классы платформы, например, `AppContext` или бин <<messages,Messages>>.

. `createFilter()` - создаёт фильтр аналогично созданию сервлетов.

Для использования этого бина мы рекомендуем создать в компоненте приложения отдельный бин-инициализатор. Этот бин должен представлять собой обычный класс с аннотацией `@Component` и содержать слушатели событий создания и уничтожения контекста приложения: <<ServletContextInitializedEvent,ServletContextInitializedEvent>> и `ServletContextDestroyedEvent`.

Пример бина-инициализатора:

[source, java]
----
include::{sourcesdir}/extension/WebInitializer.java[]
----

Здесь класс `WebInitializer` содержит только один слушатель, который используется для регистрации HTTP-сервлета из компонента приложения в родительском приложении.

Метод `createServlet()` принимает контекст приложения, полученный из события `ServletContextInitializedEvent`, и полное имя класса HTTP-сервлета. Далее мы регистрируем сервлет по его имени (`my_servlet`) и указываем URL, по которому будет доступен сервлет (`/myservlet/`). Теперь при подключении этого компонента к другому приложению сервлет `MyHttpServlet` будет зарегистрирован сразу после инициализации `AppContext` и `ServletContext`.

Более сложный пример использования бина `ServletRegistrationManager` приведён в разделе <<servlet_registration_sample,Регистрация DispatcherServlet из компонента приложения>>.

[[servlet_registration_single_war]]
Регистрация сервлетов для развертывания в единый WAR-файл::
+
--
Для корректной загрузки сервлетов и фильтров при развертывании <<build.gradle_buildWar_single,в единый WAR-файл>> следуйте инструкции ниже:

. Создайте класс, расширяющий `javax.servlet.ServletContextListener`, который будет выполнять создание сервлетов/фильтров:
+
[source, java]
----
include::{sourcesdir}/extension/CustomWebListener.java[]
----

. Добавьте новый параметр `context-param` со ссылкой на созданный класс в файл `single-war-web.xml`:
+
[source, xml]
----
include::{sourcesdir}/extension/servlet_registration_single_war.xml[]
----
--

