:sourcesdir: ../../../source

[[recipes__navigation]]
=== Navigation

Certainly navigation is one of the most common features that we have to implement while creating a web application.
In this section, we'll consider one of the possible ways to do it.

The implementation is based on two components: `app-route` and `iron-lazy-pages`.

* `app-route` is used to analyze URL currently opened in the browser.

* `iron-lazy-pages` manages what page with which content should be opened.

Below is a simple example demonstrating how the result of using these elements might work. It's put in `<iframe/>` because
we have to change current location in order to show how navigation works.

*Navigation example*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/app-with-navigation.html">

    </iframe>
++++

*Code in iframe*

.app-with-navigation.html
[source, html]
----
include::{sourcesdir}/polymer-build/app-with-navigation.html[]
----

*Polymer element implementing navigation*

.src/recipes/navigation/thermodynamic-laws.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/navigation/thermodynamic-laws.html[]
----

Navigation can contain multiple levels. It can be achieved with the help of the same `app-route` and `iron-lazy-pages` components. In the example below, click on the "Paper Elements" link and you will be presented with the second level of navigation.

*2-level navigation*

[subs="none"]
++++
    <iframe
        height="300"
        class="polymer-iframe-container"
        src="html/app-with-2-level-navigation.html">

    </iframe>
++++

*Source code:*

.src/recipes/navigation/polymer-elements-registry.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/navigation/polymer-elements-registry.html[]
----

.src/recipes/navigation/paper-elements-registry.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/navigation/paper-elements-registry.html[]
----

The same method can be used to create any navigation tree.

