:sourcesdir: ../../../../../source

[[html_to_pdf]]
===== Converting HTML to PDF

Reports which have a template in HTML format and the PDF output format do not always properly display fonts. To resolve this, add `cuba/fonts` subdirectory with required `.ttf` fonts to the Middleware configuration directory (`tomcat/conf/app-core` in default deployment configuration). Additionally, you can use existing operating system fonts by specifying their path in the <<reporting.fontsDir,reporting.fontsDir>> application property.

In order to resolve the fonts issue on a Ubuntu server, you should do the following:

* Install the `ttf-mscorefonts-installer` package:
+
----
$ sudo apt-get install ttf-mscorefonts-installer
----

* Set the <<reporting.fontsDir,reporting.fontsDir>> application property:
+
----
reporting.fontsDir = /usr/share/fonts/truetype/msttcorefonts
----

* Explicitly specify fonts in HTML templates, for example:

[source, html]
----
<html>
<head>
    <style type="text/css">
        * {
            font-family: Times New Roman;
        }
    </style>
----

Another thing to mention is parsing of special characters. To avoid errors when converting HTML to PDF, it is recommended to wrap your fields in `<![CDATA[ ]]>` construction in your HTML template file:
[source, html]
----
<tr>
	<td> <![CDATA[${(row.fields('book_name'))!?string!}]]> </td>
	<td> <![CDATA[${(row.fields('author'))!?string!}]]> </td>
</tr>
----

