:sourcesdir: ../../../../../source

[[gui_NotificationFacet]]
===== NotificationFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/NotificationFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`NotificationFacet` is a non-visual component that provides an ability to pre-configure a <<gui_notifications,notification>>. Declarative definition of the replaces existing `Notifications.create()` method. `NotificationFacet` is defined in the `facets` element of the screen XML descriptor.

Component’s XML-name: `notification`.

Usage example:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_example.xml[]
----

The screen configured with `NotificationFacet` can be shown explicitly using the `show()` method:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_show.java[]
----

`notification` has the following attributes:

[[gui_NotificationFacet_onAction]]
* `onAction` attribute contains the <<gui_Action,action>> identifier. After this action is performed, the notification should be shown.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_onAction.xml[]
----

[[gui_NotificationFacet_onButton]]
* `onButton` attribute contains the <<gui_Button,button>> identifier. After this button is clicked, the notification should be shown.
+
[source, xml]
----
include::{sourcesdir}/gui_facets/gui_NotificationFacet_onButton.xml[]
----

'''

Attributes of notification::
<<gui_attr_caption,caption>> -
<<gui_notifications_contentMode,contentMode>> -
<<gui_notifications_delay,delay>> -
<<gui_notifications_description,description>> -
<<gui_attr_id,id>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_notifications_position,position>> -
<<gui_attr_stylename,stylename>> -
<<gui_notifications_type,type>>

