:sourcesdir: ../../../../../source

[[gui_EditorScreenFacet]]
===== EditorScreenFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/EditorScreenFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=screen-facet" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`EditorScreenFacet` is a non-visual component that provides an ability to pre-configure an <<opening_screens,editor screen>>. Declarative definition of the editor screen replaces existing `ScreenBuilders.editor()` method. `EditorScreenFacet` is defined in the `facets` element of the screen XML descriptor.

Component’s XML-name: `editorScreen`.

Usage example:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_EditorScreenFacet_example.xml[]
----

The screen configured with `EditorScreenFacet` can be shown explicitly using the `show()` method:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_EditorScreenFacet_show.java[]
----

Alternatively, the facet can be subscribed to any action (see <<gui_NotificationFacet_onAction,onAction>> attribute) or button (see <<gui_NotificationFacet_onButton,onButton>> attribute) by id.

`EditorScreenFacet` has the following attributes:

[[gui_EditorScreenFacet_addFirst]]
* `addFirst` – defines whether a new item will be added to the beginning or to the end of the collection. Affects only standalone containers; for nested containers new items are always added to the end.

[[gui_EditorScreenFacet_container]]
* `container` – sets a <<gui_collection_container,CollectionContainer>>. The container is updated after the screen is committed. If the container is <<gui_property_containers,nested>>, the framework automatically initializes the reference to the parent entity and sets up data context for editing compositions.

[[gui_EditorScreenFacet_editMode]]
* `editMode` – sets the screen edit mode, corresponds to the `EditMode` enum: `CREATE` (to create a new entity instance), or `EDIT` (to edit an existing one).

[[gui_EditorScreenFacet_entityClass]]
* `entityClass` – the full qualified name of an entity class.

[[gui_EditorScreenFacet_field]]
* `field` – sets the <<gui_PickerField,PickerField>> component id. If the field is set, the framework sets the committed entity to the field after a successful editor commit.

[[gui_EditorScreenFacet_listComponent]]
* `listComponent` – sets the list component id. The component is used to get the <<gui_EditorScreenFacet_container,container>> if it is not set. Usually, the list component is a <<gui_Table,Table>> or <<gui_DataGrid,DataGrid>> displaying the list of entities.

'''

Attributes of editorScreen ::
<<gui_EditorScreenFacet_addFirst,addFirst>> -
<<gui_EditorScreenFacet_container,container>> -
<<gui_EditorScreenFacet_editMode,editMode>> -
<<gui_EditorScreenFacet_entityClass,entityClass>> -
<<gui_EditorScreenFacet_field,field>> -
<<gui_attr_id,id>> -
<<gui_EditorScreenFacet_listComponent,listComponent>>
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_ScreenFacet_openMode,openMode>> -
<<gui_ScreenFacet_screenClass,screenClass>> -
<<gui_ScreenFacet_screenId,screenId>>

Element of editorScreen ::
<<gui_ScreenFacet_properties,properties>>
