:sourcesdir: ../../../../../source

[[gui_ScreenFacet]]
===== ScreenFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/ScreenFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=screen-facet" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

`ScreenFacet` is a non-visual component that provides an ability to pre-configure <<opening_screens,screen opening>> and <<screen_parameters,passing properties>>. Declarative definition of the screen replaces existing `ScreenBuilders.screen()` method. `ScreenFacet` is defined in the `facets` element of the screen XML descriptor.

Component’s XML-name: `screen`.

Usage example:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_ScreenFacet_example.xml[]
----

The screen configured with `ScreenFacet` can be shown explicitly using the `show()` method:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_ScreenFacet_show.java[]
----

Alternatively, the facet can be subscribed to any action (see <<gui_NotificationFacet_onAction,onAction>> attribute) or button (see <<gui_NotificationFacet_onButton,onButton>> attribute) by id.

`ScreenFacet` has the following attributes:

[[gui_ScreenFacet_screenId]]
* `screenId` – specifies the id of the screen to open.

[[gui_ScreenFacet_screenClass]]
* `screenClass` – Java class of the screen controller to open.

[[gui_ScreenFacet_openMode]]
* `openMode` – screen open mode, corresponds to the `OpenMode` enum: `NEW_TAB`, `DIALOG`, `NEW_WINDOW`, `ROOT`, `THIS_TAB`. The default value is `NEW_TAB`.

[[gui_ScreenFacet_properties]]
`ScreenFacet` has the `properties` element, which represents a list of properties, that will be injected into the opened screen via public setters. See <<screen_parameters,Passing parameters to screens>>.

'''

Attributes of screen ::
<<gui_attr_id,id>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_ScreenFacet_openMode,openMode>> -
<<gui_ScreenFacet_screenClass,screenClass>> -
<<gui_ScreenFacet_screenId,screenId>>

Element of screen ::
<<gui_ScreenFacet_properties,properties>>
