:sourcesdir: ../../../../../source

[[gui_Timer]]
===== Timer

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Timer.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=timer" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

Timer is a <<gui_facets,facet>> designed to run some screen controller code at specified time intervals. The timer works in a thread that handles user interface events, therefore it can update screen components. Timer stops working when a screen it was created for is closed.

The main approach for creating timers is by declaring them in the `facets` element of the screen XML descriptor.

Timers are described using the `timer` element.

* `delay` is a required attribute; it defines timer interval in milliseconds.

* `autostart` – an optional attribute; when it is set to `true`, timer starts immediately after the screen is opened. By default, the value is `false`, which means that the timer will start only when its `start()` method is invoked.

* `repeating` – an optional attribute, turns on repeated executions of the timer. If the attribute is set to `true`, the timer runs in cycles at equal intervals defined in the `delay` attribute. Otherwise, the timer runs only once – `delay` milliseconds after the timer start.

To execute some code on timer, subscribe to its `TimerActionEvent` in the screen controller.

An example of defining a timer and subscribing to it in the controller:

[source, xml]
----
include::{sourcesdir}/gui_facets/timer_1.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_facets/timer_2.java[]
----

A timer can be injected into a controller field, or acquired using the `getWindow().getFacet()` method. Timer execution can be controlled using the timer's `start()` and `stop()` methods. For an already active timer, `start()` invocation will be ignored. After stopping the timer using `stop()` method, it can be started again with `start()`.

Example of defining a timer in an XML descriptor and using timer listeners in a controller:

[source, xml]
----
include::{sourcesdir}/gui_facets/timer_3.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_facets/timer_4.java[]
----

<1> timer execution handler

<2> timer stop event

<3> start the timer

A timer can be created in a controller, in this case it should be added to the screen implicitly using the `addFacet()` method, for example:

[source, java]
----
include::{sourcesdir}/gui_facets/timer_5.java[]
----

<1> add timer to the screen

<2> set timer parameters

<3> add execution handler

<4> add stop listener

<5> start the timer