:sourcesdir: ../../../../../source

[[gui_InputDialogFacet]]
===== InputDialogFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/InputDialogFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`InputDialogFacet` is a non-visual component that provides an ability to pre-configure an <<gui_input_dialog,input dialog>>. Declarative definition of the input dialog replaces existing `Dialogs.createInputDialog()` method. `InputDialogFacet` is defined in the `facets` element of the screen XML descriptor.

Component’s XML-name: `inputDialog`.

Usage example:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_InputDialogFacet_example.xml[]
----

The screen configured with `InputDialogFacet` can be shown explicitly using the `show()` method:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_InputDialogFacet_show.java[]
----

Alternatively, the facet can be subscribed to any action (see <<gui_NotificationFacet_onAction,onAction>> attribute) or button (see <<gui_NotificationFacet_onButton,onButton>> attribute) by id.

[[gui_InputDialogFacet_defaultActions]]
In addition to attributes described for the <<gui_OptionDialogFacet,OptionDialogFacet>>, `inputDialog` has the `defaultActions` attribute that defines a set of predefined actions to use in a dialog. The standard values are:

* `OK`
* `OK_CANCEL`
* `YES_NO`
* `YES_NO_CANCEL`

The default value is `OK_CANCEL`.

*inputDialog elements:*

[[gui_InputDialogFacet_actions]]
* `actions` element represents a list of <<gui_option_dialog_actions,dialog actions>>.

[[gui_InputDialogFacet_parameters]]
* `parameters` element may contain the following parameters:
** `stringParameter`
** `booleanParameter`
** `intParameter`
** `doubleParameter`
** `longParameter`
** `bigDecimalParameter`
** `dateParameter`
** `timeParameter`
** `dateTimeParameter`
** `entityParameter`
** `enumParameter`

To implement custom logic for a dialog action, you should create an appropriate handler method in the controller.

To handle input dialog results, you can install the corresponding delegate:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_InputDialogFacet_handleResult.java[]
----

Attributes of inputDialog ::

<<gui_attr_caption,caption>> -
<<gui_message_dialog_contentMode,contentMode>> -
<<gui_InputDialogFacet_defaultActions,defaultActions>> -
<<gui_message_dialog_width_height,height>> -
<<gui_attr_id,id>> -
<<gui_message_dialog_withMaximized,maximized>> -
<<gui_message_dialog_message,message>> -
<<gui_message_dialog_modal,modal>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_attr_stylename,stylename>> -
<<gui_message_dialog_width_height,width>>

Element of inputDialog ::
<<gui_OptionDialogFacet_actions,actions>> -
<<gui_InputDialogFacet_parameters,parameters>>