:sourcesdir: ../../../../../source

[[gui_OptionDialogFacet]]
===== OptionDialogFacet

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.2/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.2</span>
    </a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="https://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/OptionDialogFacet.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

`OptionDialogFacet` is a non-visual component that provides an ability to pre-configure an <<gui_option_dialog,option dialog>>. Declarative definition of the option dialog replaces existing `Dialogs#createOptionDialog()` method. `OptionDialogFacet` is defined in the `facets` element of the screen XML descriptor.

Component’s XML-name: `optionDialog`.

Usage example:

[source, xml]
----
include::{sourcesdir}/gui_facets/gui_OptionDialogFacet_example.xml[]
----

Option dialog can be shown explicitly via the corresponding method:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_OptionDialogFacet_show.java[]
----

or subscribed to any action (see <<gui_NotificationFacet_onAction,onAction>> attribute) or button (see <<gui_NotificationFacet_onButton,onButton>> attribute) by id.

[[gui_OptionDialogFacet_actions]]
`optionDialog` has the `actions` element, which represents a list of <<gui_option_dialog_actions,dialog actions>>.

To implement custom logic for a dialog action, you should create an appropriate handler method in the controller:

[source, java]
----
include::{sourcesdir}/gui_facets/gui_OptionDialogFacet_installDelegate.java[]
----

<1> - a handler that is invoked when the user clicks the *OK* button in the option dialog.
<2> - a handler that is invoked when the user clicks the *Cancel* button in the option dialog.

'''

Attributes of optionDialog ::

<<gui_attr_caption,caption>> -
<<gui_message_dialog_contentMode,contentMode>> -
<<gui_message_dialog_width_height,height>> -
<<gui_attr_id,id>> -
<<gui_message_dialog_withMaximized,maximized>> -
<<gui_message_dialog_message,message>> -
<<gui_message_dialog_modal,modal>> -
<<gui_NotificationFacet_onAction,onAction>> -
<<gui_NotificationFacet_onButton,onButton>> -
<<gui_attr_stylename,stylename>> -
<<gui_message_dialog_width_height,width>>

Element of optionDialog ::
<<gui_OptionDialogFacet_actions,actions>>

