:sourcesdir: ../../../../source

[[legacy_roles]]
==== Предыдущая реализация ролей и разрешений

До CUBA 7.2 метод расчета действующих разрешений был другим. Разрешение могло быть дано либо явно путем указания "allow/deny" для целевого объекта, или ролью определенного типа, например роль "Denying" давала разрешение "deny" всем объектам кроме атрибутов сущностей. Если целевой объект не получал явных разрешений, либо разрешений от типа роли, он был полностью доступен пользователю. В результате, пользователь вообще без ролей имел полные права на систему.

При настройке ролей, рекомендовалось сначала давать обычным пользователям роль "Denying", а затем набор ролей с явными разрешениями. Теперь запрещающая роль не нужна, так как пользователи не имеют никаких прав на объекты, пока соответствующие разрешения не даны им какой-либо ролью.

Кроме того, в предыдущих версиях не было <<security_scope,областей действия>>, так что все роли действовали и на клиентов Generic UI и на клиентов REST API.

Если вы мигрировали проект на CUBA 7.2 с предыдущей версии и хотите сохранить текущую настройку прав доступа, используйте свойства приложения, приведенные ниже.

В модуле `core`, установите свойства для предыдущего метода расчета разрешений и использования конфигурационного файла <<default-permission-values.xml>>:

.app.properties
[source,properties]
----
cuba.security.undefinedAccessPolicy = ALLOW
cuba.security.defaultPermissionValuesConfigEnabled = true
----

Если в проекте используется аддон REST API, добавьте следующее свойство в модуле `web`, для того, чтобы установить область действия контроля доступа REST в то же значение, что используется в Generic UI:

.web-app.properties
[source,properties]
----
cuba.rest.securityScope = GENERIC_UI
----