:sourcesdir: ../../../../source

[[login_screen]]
==== Окно входа в систему

Окно входа в систему (Login screen) предназначено для регистрации пользователя путем ввода логина и пароля. Логин не чувствителен к регистру вводимых символов.

Управлять отображением флажка *Remember Me* в веб-клиенте можно с помощью свойства приложения <<cuba.web.rememberMeEnabled,cuba.web.rememberMeEnabled>>. Стандартное окно входа содержит также выпадающий список поддерживаемых системой языков. Отображение списка и его содержимое определяются комбинацией свойств приложения <<cuba.localeSelectVisible,cuba.localeSelectVisible>> и <<cuba.availableLocales,cuba.availableLocales>>.

Смотрите также свойства приложения <<cuba.web.loginDialogDefaultUser,cuba.web.loginDialogDefaultUser>>, <<cuba.web.loginDialogDefaultPassword,cuba.web.loginDialogDefaultPassword>> и <<cuba.web.loginDialogPoweredByLinkVisible,cuba.web.loginDialogPoweredByLinkVisible>>.

В веб-клиенте стандартное окно логина можно кастомизировать или полностью заменить в проекте, используя CUBA Studio. Выберите *New > Screen* в контекстном меню элемента *Generic UI* в дереве проекта. Затем на вкладке *Legacy Screen Templates* выберите шаблон *Login window*. Новый файл `ext-loginWindow.xml` будет создан в модуле Web и автоматически зарегистрирован в `web-screens.xml`. Смотрите также <<gui_web,>>.

В платформе имеется механизм защиты от взлома пароля методом перебора, смотрите свойство приложения <<cuba.bruteForceProtection.enabled,cuba.bruteForceProtection.enabled>>.

Для более глубокой кастомизации процесса аутентификации, смотрите разделы <<login>> и <<web_login>>.

