:sourcesdir: ../../../../source

[[roles]]
==== Роли

Роль объединяет набор <<permissions,разрешений>>, которые могут быть предоставлены пользователю.

Пользователь может иметь несколько ролей. При этом он получает логическую сумму (ИЛИ) прав на некоторый объект от всех ролей, которые у него есть. Например, если пользователю назначены роли A и B, роль A запрещает X, роль B разрешает X, то в итоге X будет разрешен.

Каждая роль предоставляет разрешения на все целевые объекты (кроме компонентов экранов) одним из следующих способов:

* Явно: путем указания разрешения для данного целевого объекта.
* По умолчанию: если на некоторый целевой объект разрешение не дано явно, то используется разрешение данного типа по умолчанию.

Например, в приложении с экранами X и Y, если роль задает разрешение "allow" на экран X и по умолчанию задает "deny" на все экраны, то результирующие разрешения будут "allow" для X и "deny" для Y.

Разрешения на компоненты экранов являются исключением из правил, описанных выше: у них нет значений по умолчанию и они могут быть указаны только явно. Кроме того, если ни одна роль не определяет разрешения на некоторый компонент экрана, то этот компонент полностью доступен пользователю.

Роль может иметь признак "по умолчанию", что означает, что такая роль будет автоматически назначаться вновь создаваемым пользователям. Это позволяет выдавать некоторый набор разрешений всем пользователям по умолчанию.

[[roles_design_time]]
Определение ролей во время разработки::
+
--
Рекомендуемый способ определения роли - создать класс, расширяющий `AnnotatedRoleDefinition`, переопределить методы, возвращающие разрешения различных типов, и добавить им аннотации, указывающие, какие разрешения дает данная роль. Класс должен находиться в модуле `core`. Например, роль дающая разрешения на сущность `Customer` и ее экраны списка и редактирования может выглядеть следующим образом:

[source,java]
----
include::{sourcesdir}/security/roles_1.java[]
----
--

[[roles_run_time]]
Определение ролей во время работы приложения::
+
--
Фреймворк содержит UI, который позволяет создавать роли в работающем приложении, см. *Administration > Roles*. Роли, созданные таким образом, можно изменить или удалить. Роли, заданные при разработке приложения, доступны только на чтение.

В верхней части экрана редактирования роли отображаются общие параметры роли и значения разрешений по умолчанию. В нижней части отображаюся вкладки управления явными разрешениями.

* Вкладка *Screens* - разрешения на экраны системы. Дерево в левой части вкладки отражает структуру главного меню системы. Последним элементом дерева является *Other screens*, внутри которого сосредоточены экраны, не включенные в главное меню (например, экраны редактирования сущностей).

* Вкладка *Entities* - разрешения на операции с сущностями. При переходе на данную вкладку изначально включен флажок *Assigned only*, поэтому в таблице отображаются только сущности, для которых в данной роли уже есть явные разрешения. Поэтому для новой роли таблица пуста. Для установки разрешений снимите флажок *Assigned only* и нажмите *Apply*. Список сущностей можно фильтровать, вводя в поле *Entity* любую часть имени сущности и нажимая *Apply*. Установив флажок *System level*, можно выбрать системную сущность, помеченную аннотацией `@SystemLevel`. По умолчанию такие сущности не показываются в таблице.

* Вкладка *Attributes* - разрешения на атрибуты сущностей. В таблице сущностей в колонке *Permissions* отображается список атрибутов, для которых явно указаны разрешения. Управление списком сущностей аналогично описанному для вкладки *Entities*.

* Вкладка *Specific* - разрешения на именованную функциональность. Имена объектов, на которые могут быть назначены специфические разрешения, определяются в конфигурационном файле <<permissions.xml,permissions.xml>> проекта.

* Вкладка *UI* - разрешения на UI-компоненты экранов. Для создания ограничения выберите нужный экран в выпадающем списке *Screen*, задайте путь к компоненту в поле *Component*, и нажмите *Add*. При формировании пути, следуйте правилам, описанным в разделе <<permissions>>. Для отображения структуры экрана нажмите кнопку *Components tree*, выберите компонент и выберите *Copy id to path* в контекстном меню.
--

[[security_scope]]
Области действия (security scopes)::
+
--
_Области действия_ позволяют назначать одному пользователю различные наборы ролей (и тем самым различные разрешения) в зависимости от клиентской технологии, которую он использует для доступа к приложению. Область действия указывается в атрибуте `securityScope` аннотации `@Role`, или в поле *Security scope* экрана редактирования роли, если роль создается во время работы приложения.

Ядро фреймворка содержит единственного клиента - <<gui_framework,Generic UI>>, поэтому все роли по умолчанию имеют область действия `GENERIC_UI`. Все пользователи, входящие в систему через UI приложения получат набор ролей с этим значением области действия.

[Аддон REST API] определяет свою собственную область действия - `REST`, поэтому если вы добавите аддон к проекту, вам необходимо сконфигурировать отдельный набор ролей для пользователей, входящих в систему через REST API. Если этого не сделать, пользователи не смогут входить через REST, так как у них не будет разрешения `cuba.restApi.enabled`.
--

[[system_roles]]
System roles::
+
--
Фреймворк определяет две предустановленные роли для области действия `GENERIC_UI`:

* `system-minimal` - содержит минимальный набор разрешений, необходимый пользователям для работы с Generic UI. Данная роль задается классом `MinimalRoleDefinition`. Она дает специфическое разрешени `cuba.gui.loginToClient`, а также разрешения на некоторый системные сущности и экраны. У роли `system-minimal` установлен атрибут "по умолчанию", поэтому она автоматически назначается новым пользователям.

* `system-full-access` - дает все разрешения на все объекты, тем самым может использоваться для создания администраторов, имеющих полные права на систему. Встроенный пользователь `admin` по умолчанию имеет эту роль.
--