:sourcesdir: ../../../../../source

[[scheduled_tasks_spring]]
===== Spring TaskScheduler

Данный механизм подробно описан в разделе *Task Execution and Scheduling* руководства *Spring Framework*.

`TaskScheduler` можно использовать для запуска методов произвольных бинов Spring в любом <<app_tiers,блоке>> приложения - как на *Middleware*, так и на клиентском уровне.

Пример конфигурации в файле <<spring.xml,spring.xml>>:

[source, xml]
----
include::{sourcesdir}/features/scheduled_tasks_1.xml[]
----

Здесь объявлены две задачи, запускающие на выполнение методы `someMethod()` и `someOtherMethod()` бина `++sales_Processor++`. При этом `someMethod()` запускается с момента старта приложения через фиксированные промежутки времени - 60 сек. Метод `someOtherMethod()` запускается в соответствии с расписанием, заданным выражением Cron (описание формата таких выражений см. https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html).

Собственно запуск задач выполняет бин, заданный в атрибуте `scheduler` элемента `scheduled-tasks`. Это бин класса `CubaThreadPoolTaskScheduler`, который сконфигурирован в модулях *core* и *web* компонента *cuba* (см. `cuba-spring.xml`, `cuba-web-spring.xml`). Данный класс содержит специфическую для CUBA функциональность.

Для того чтобы предоставить <<securityContext,SecurityContext>> коду, выполняемому задачами Spring на среднем слое, используйте <<system_authentication, системную аутентификацию>>.

