:sourcesdir: ../../../../../source

[[private_repo_install]]
===== Install the Repository Manager

For the purpose of this example, we will use Sonatype Nexus OSS repository manager.

On Microsoft Windows operating system::
+
--
- link:http://www.sonatype.org/downloads/nexus-latest-bundle.zip[Download] Sonatype Nexus OSS version 2.x (2.14.3 has been tested)
- Unpack zip file to the directory `c:\nexus-2.14.3-02`
- Modify settings located in file `c:\nexus-2.14.3-02\conf\nexus.properties`:
+
** You may configure server port; default is 8081
+
** Configure repository data folder:
+
replace
+
[source]
----
nexus-work=${bundleBasedir}/../sonatype-work/nexus
----
+
with any convenient path to cached data, for example
+
[source]
----
nexus-work=${bundleBasedir}/nexus/sonatype-work/content
----
- Navigate to the folder `c:\nexus-2.14.3-02\bin`
- To start and stop Nexus as a service, install the wrapper (run command as Administrator):
+
[source]
----
nexus.bat install
----

- Launch *nexus* service.
- Open `++http://localhost:8081/nexus++` in the web browser and log in with the default credentials: login `admin` and password `admin123`.
--

With Docker::
+
--
Alternatively, we can use Docker to simplify the setup for local use. Instructions are also available at the link:https://hub.docker.com/r/sonatype/nexus[Docker Hub].

- Run `docker pull sonatype/nexus:oss` to download the latest stable OSS image
- Then build the container with `docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss`
- The docker container will have nexus running in a few minutes. Test by either way:
+
** `curl ++http://localhost:8081/nexus/service/local/status++`
+
** Navigate to `++http://localhost:8081/nexus++` in the web browser.
- Credentials are the same: login `admin` and password `admin123`.
--