:sourcesdir: ../../../../../source

[[exceptionHandlers]]
===== Client-Level Exception Handlers

Unhandled exceptions thrown on the client tier or passed from Middleware, are passed to the special handlers mechanism of the Web Client block.

A handler is a <<managed_beans,Spring bean>> implementing the `UiExceptionHandler` interface. Its `handle()` method should process the exception and return `true`, or immediately return `false` if this handler is not able to handle the passed exception. This behavior enables creating a "chain of responsibility" for handlers.

It is recommended to inherit your handlers from the `AbstractUiExceptionHandler` base class, which is able to disassemble the exceptions chain (including ones packed inside `RemoteException`) and handle specific exception types. Exception types supported by this handler are defined by passing a string array to the base constructor from the handler constructor. Each string of the array should contain one full class name of the handled exception.

Suppose you have the following exception class:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_0.java[]
----

Then the handler for this exception must have the following constructor:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_1.java[]
----

If the exception class is not accessible on the client side, specify its name with the string literal:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_2.java[]
----

In the case of using `AbstractUiExceptionHandler` as a base class, the processing logic is located in `doHandle()` method and looks as follows:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_3.java[]
----

If the name of the exception class is insufficient to make a decision whether this handler can be applied to the exception, define the `canHandle()` method. This method accepts also the text of the exception. If the handler is applicable for this exception, the method must return `true`. For example:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_4.java[]
----

[[dialogs_showExceptionDialog]]
The `Dialogs` interface available via the `UiContext` parameter of the `doHandle()` method provides a special dialog for displaying exceptions containing a collapsable area with the complete exception stack trace. This dialog is used in the default handler, but you can use it for your exceptions too, for example:

[source, java]
----
include::{sourcesdir}/common/exceptionHandlers_5.java[]
----
