:sourcesdir: ../../../../../source

[[exception_classes]]
===== Exception Classes

The following rules should be followed when creating your own exception classes:

* If the exception is part of business logic and requires some non-trivial actions to handle it, the exception class should be made checked (inherited from `Exception`). Such exceptions are handled by the invoking code.

* If the exception indicates an error and assumes interruption of execution and a simple action like displaying the error information to the user, its class should be unchecked (inherited from `RuntimeException`). Such exceptions are processed by special <<exceptionHandlers,handler classes>> registered in the client blocks of the application.

* If the exception is thrown and processed in the same <<app_tiers,block>>, its class should be declared in corresponding <<app_modules,module>>. If the exception is thrown on Middleware and processed on the client tier, the exception class should be declared in the *global* module.

The platform contains a special unchecked exception class `SilentException`. It can be used to interrupt execution without showing any messages to the user or writing them to the log. `SilentException` is declared in the global module, and therefore is accessible both in Middleware and client blocks.

