:sourcesdir: ../../../../source

[[pie_chart]]
==== PieChart

The `PieChart` component allows you to create pie/donut charts.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=pie3d-chart" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

.PieChart
image::chart/pie-chart.svg[align="center", width="800"]

XML name of the component: `chart:pieChart`.

Data binding: ::
+
--
. Using a datasource.
+
You can assign a datasource of a `CollectionDatasource` type to the chart and then define the `titleField` and `valueField` attributes for the `pieChart` element:
+
[source, xml]
----
include::{sourcesdir}/chart/pie_chart.xml[]
----

. Using the <<chart_data,chart:data>> element.
--

`PieChart` event listeners: ::
+
--
* `ChartClickListener` - click on the canvas.
* `ChartRightClickListener` - right click on the canvas.
* `SliceClickListener` - click on a slice in a pie chart.
* `SlicePullInListener` - shift of a slice of a pie chart into the chart.
* `SlicePullOutListener` - shift of a slice of a pie chart out of the chart.
* `SliceRightClickListener` - right-click on a slice in a pie chart.
--

For more details, see http://docs.amcharts.com/3/javascriptcharts/AmPieChart[AmCharts documentation].

