:sourcesdir: ../../../../source

[[radar_chart]]
==== RadarChart

The `RadarChart` component allows you to create radar/polar charts.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=polar-chart" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

.RadarChart
image::chart/radar-chart.svg[align="center", width="800"]

XML name of the component: `chart:radarChart`.

Data binding: ::
+
--
You can assign a `CollectionContainer` to the chart and then define the `categoryField` attribute for the `radarChart` element and `valueField` attribute for the nested `graph` element:

[source, xml]
----
include::{sourcesdir}/chart/radar_chart.xml[]
----
--

`RadarChart` event listeners::
+
--
* `AxisZoomListener` – chart axis scaling.
* `ChartClickListener` – click on the canvas.
* `ChartRightClickListener` – right click on the canvas.
* `GraphClickListener` – click on a graph.
* `GraphItemClickListener` – click on a graph item.
* `GraphItemRightClickListener` – right click on a graph item.
* `RollOutGraphListener` – called when the user rolls-out of a graph.
* `RollOutGraphItemListener` – called when the user rolls-out of the data item.
* `RollOverGraphListener` – called when the user rolls-over a graph.
* `RollOverGraphItemListener` – called when the user rolls-over data item.
--

For more details, see http://docs.amcharts.com/3/javascriptcharts/AmRadarChart[AmCharts documentation].

