:sourcesdir: ../../../../source

[[oto_single_editor]]
==== One-to-One Composition with a Single Editor

++++
<div class="manual-live-demo-container">
    <a href="https://demo3.cuba-platform.com/generic-ui/open?screen=sample$Customer.browse" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

It is often convenient to edit the <<composition_oto_recipe,One-to-One composition>> in one single editor. Let's see how it can be implemented taking the https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/global/src/com/company/sample/entity/Customer.java[Customer] and the https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/global/src/com/company/sample/entity/CustomerDetails.java[CustomerDetails] relationship as an example.

* https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/web/src/com/company/sample/web/customer/customer-edit.xml[customer-edit.xml] descriptor contains the main `customerDs` and the nested `detailsDs` datasources:
+
--
[source, xml]
----
include::{sourcesdir}/cookbook/oto_single_editor.xml[]
----

Fields for editing both entities are grouped into one `fieldGroup`, where some fields are bound to the nested datasource:

[source, xml]
----
include::{sourcesdir}/cookbook/oto_single_editor_2.xml[]
----
--

* In the https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/web/src/com/company/sample/web/customer/CustomerEdit.java[CustomerEdit] controller we override the `initNewItem()` method. It will create a `CustomerDetails` instance and link it to the new `Customer` instance when the latter is just created:
+
--
[source, java]
----
include::{sourcesdir}/cookbook/oto_single_editor_3.java[]
----

Finally, let's handle the situation when a user clicks *Create* and then wants to close the editor without changing anything. This user will be asked for saving changes, as the `detailsDs` datasource already contains an empty instance and `isModified()` method of the `AbstractEditor` will always return `true`. To prevent the appearance of confirmation dialog, we should make `isModified()` consider changes only in the master datasource:

[source, java]
----
include::{sourcesdir}/cookbook/oto_single_editor_4.java[]
----
--

Now, both linked entities can be created and edited in one editor screen.

