:sourcesdir: ../../../../../../source

[[gui_formatter]]
====== Formatter

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/6.10/com/haulmont/cuba/gui/components/Formatter.html" class="api-docs-btn" target="_blank">API DOCS</a>
</div>
++++

[WARNING]
====
Formatter should be used with read-only components, such as <<gui_Label,Label>>, <<gui_Table,Table>> column and similar. Editable components values, for example, <<gui_TextField,TextField>>, should be formatted using the <<datatype,Datatype>> mechanism.
====

In an XML-descriptor of a screen, a component's formatter can be defined in a nested `formatter` element. The element has a single attribute:

* `class` − the name of a class implementing a `com.haulmont.cuba.gui.components.Formatter`

If formatter's constructor class has a `org.dom4j.Element`, parameter, then it will receive an XML element, describing this `formatter`. This can be used to parameterize a formatter instance. For example, using a formatted string. Particularly, `DateFormatter` and `NumberFormatter` classes in the platform can take the format string from the `format` attribute. Example of using the component: 

[source, xml]
----
include::{sourcesdir}/gui_vcl/formatter_1.xml[]
---- 

Additionally, `DateFormatter` class also recognizes a `type` attribute, which can have a `DATE` or `DATETIME` value. In this case, formatting is done using the <<datatype,Datatype>> mechanism using a `dateFormat` or a `dateTimeFormat` string respectively. For example:

[source, xml]
----
include::{sourcesdir}/gui_vcl/formatter_2.xml[]
----

By default, `DateFormatter` displays the date and time in the server timezone. To show the current user's timezone, set `true` for the `useUserTimezone` attribute of the formatter.

[TIP]
====
If a formatter is implemented as an internal class, it should be declared with a `static` modifier and its name should be separated by "$" for loading, for example:

`<formatter class="com.sample.sales.gui.OrderBrowse$CurrencyFormatter"/>`
====

Formatter can be assigned to a component not only using a screen XML-descriptor , but also programmatically – by submitting a formatter instance into a `setFormatter()` component.

An example of declaring a custom formatter and using it to format values in a table column: 

[source, java]
----
include::{sourcesdir}/gui_vcl/formatter_3.java[]
----

[source, java]
----
include::{sourcesdir}/gui_vcl/formatter_4.java[]
---- 

