:sourcesdir: ../../../../source

[[integration_tests_client]]
==== Интеграционные тесты веб-уровня

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.1/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

Интеграционные тесты веб-уровня выполняются в контейнере Spring блока Web Client. Тестовый контейнер работает независимо от среднего слоя, так как фреймворк автоматически создает заглушки (stubs) для всех сервисов. Тестовая инфраструктура состоит из следующих классов, расположенных в пакете `com.haulmont.cuba.web.testsupport` и его вложенных пакетах:

* `TestContainer` - обертка вокруг контейнера Spring для использования в качестве базового класса в проектах.
* `TestServiceProxy` - предоставляет заглушки по умолчанию для сервисов среднего слоя. Данный класс можно также использовать для регистрации моков сервисов, специфичных для теста: см. статический метод `mock()`.
* `DataServiceProxy` - заглушка по умолчанию для `DataManager`. Содержит реализацию метода `commit()`, которая имитирует поведение реального хранилища: делает новые экземпляры сущностей detached, инкрементирует версии, и т.д. Методы загрузки ничего не делают и возвращают null и пустые коллекции.
* `TestUiEnvironment` - предоставляет набор методов для конфигурирования и получения `TestContainer`. Экземпляр данного класса должен быть использован в тестах в качестве JUnit 5 extension.
* `TestEntityFactory` - фабрика для удобного создания тестовых экземпляров сущностей. Может быть получена из `TestContainer`.

Несмотря на то, что фреймворк предоставляет дефолтные заглушки для сервисов среднего слоя,  в тестах могут понадобится собственные моки сервисов. Для создания моков можно использовать любой мок-фреймворк, просто подключив его в зависимости проекта как описано в разделе <<testing,выше>>. Моки сервисов регистрируются с помощью метода `TestServiceProxy.mock()`.

[[integration_tests_client_container]]
Пример контейнера для интеграционных тестов веб-уровня::
+
--
Создайте каталог `test` в модуле `web`. Затем создайте в подходящем пакете данного каталога класс контейнера:

[source, java]
----
include::{sourcesdir}/development/web_testing_container.java[]
----
--

[[integration_tests_client_ex1]]
Пример теста экрана UI::
+
--
Ниже приведен пример теста, который проверяет состояние редактируемой в экране сущности после некоторого действия пользователя.

[source, java]
----
include::{sourcesdir}/development/web_testing_ex1.java[]
----
<1> - создание экземпляра `TestUiEnvironment` с разделяемым контейнером и пользователем `admin` в заглушке пользовательской сессии.
<2> - создание экземпляра сущности в состоянии `new`.
<3> - получение инфраструктурного объекта `Screens`.
<4> - открытие главного экрана, который необходим для открытия остальных экранов приложения.
<5> - создание, инициализация и открытие экрана редактирования сущности.
<6> - получение компонента `Button`.
<7> - создание объекта события нажатия кнопки и вызов метода контроллера, который реагирует на это событие.
--

[[integration_tests_client_ex2]]
Пример теста загрузки данных в экран::
+
--
Ниже приведен пример теста, который проверяет корректность загрузки данных в экране UI.

[source, java]
----
include::{sourcesdir}/development/web_testing_ex2.java[]
----
<1> - определение мока с помощью фреймворка JMockit.
<2> - задание поведения мока.
<3> - регистрация мока.
<4> - создание экземпляра сущности в состоянии `detached`.
<5> - удаление мока после завершения теста.
<6> - получение контейнера данных.
--
