:sourcesdir: ../../../../source

[[integration_tests_mw]]
==== Интеграционные тесты Middleware

Интеграционные тесты Middleware выполняются в полнофункциональном контейнере Spring с подключением к базе данных. В тестах такого типа можно выполнять код любого слоя внутри Middleware - от сервисов до ORM.

Сразу после создания нового проекта с помощью Studio, в базовом пакете модуля `core` находятся два класса: тестовый контейнер и пример теста. Класс тестового контейнера запускает контейнер Spring среднего слоя, настроенный для выполнения тестов. Пример теста использует этот контейнер и демонстрирует, как можно тестировать некоторые операции с сущностью.

Рассмотрим сгенерированный класс контейнера и пути его адаптации для нужд проекта.

Класс контейнера должен расширять класс `TestContainer`, предоставляемый CUBA. В конструкторе класса необходимо добавить в список `appComponents` все <<app_components_recipes,компоненты приложения>> (аддоны), используемые в проекте. Кроме того, в списке `appPropertiesFiles` можно указать дополнительные файлы свойств приложения.

Метод `initDbProperties()` выполняет инициализацию параметров подключения к базе данных. В сгенерированном классе, данный метод находит <<db_connection,параметры подключения>> независимо от того, объявлены ли они в свойствах приложения или в <<context.xml,context.xml>>. Если оставить реализацию метода в таком виде, то ваши тесты будут выполняться на основном хранилище данных, даже если вы поменяете его тип или то, как задается его JDBC DataSource.

В использовании одной базы данных и для тестов, и для приложения, есть недостаток: данные, введенные вручную в приложении, могут мешать выполнению тестов, и наоборот. Чтобы избежать этого, для тестов можно использовать отдельную БД. Рекомендуется использовать СУБД такого же типа, что и для основной БД, так как в этом случае можно использовать один набор <<db_scripts,скриптов миграции БД>>. Ниже приведен пример настройки тестовой базы данных на локальном PostgreSQL.

Во-первых, реализуйте `initDbProperties()` следующим образом:

[source, java]
----
public class DemoTestContainer extends TestContainer {
    // ...
    private void initDbProperties() {
        dbDriver = "org.postgresql.Driver";
        dbUrl = "jdbc:postgresql://localhost/demo_test";
        dbUser = "cuba";
        dbPassword = "cuba";
    }
----

Затем добавьте <<build.gradle_createDb,задачу создания тестовой БД>> в `build.gradle`:

[source, groovy]
----
include::{sourcesdir}/development/testing_4.groovy[]
----

Перед выполнением тестов создайте тестовую БД путем выполнения задачи:

[source]
----
./gradlew createTestDb
----

Тестовый контейнер используется в классах тестов в качестве JUnit 5 extension, указанного с помощью аннотации `@RegisterExtension`:

[source, java]
----
include::{sourcesdir}/development/testing_5.java[]
----

Полезные методы тестового контейнера::
+
--
Класс `TestContainer` содержит следующие методы, которые можно использовать в коде тестов (см. пример `CustomerTest` выше):

* `persistence()` - возвращает ссылку на интерфейс <<persistence,Persistence>>.

* `metadata()` - возвращает ссылку на интерфейс <<metadata,Metadata>>.

* `deleteRecord()` - этот набор перегруженных методов предназначен для использования в `@After` методах для удаления тестовых объектов из БД.
--

Логирование::
+
--
Класс `TestContainer` настраивает логирование в соответствие с файлом `test-logback.xml`, предоставляемым платформой. Данный файл содержится в артефакте `cuba-core-tests`.

Для того, чтобы настроить уровни логирования в своих тестах, необходимо выполнить следующее:

* Создайте файл `my-test-logback.xml` в каталоге `test` модуля `core` проекта. Вы можете взять за основу содержимое файла `test-logback.xml`, находящегося внутри артефакта `cuba-core-tests`.

* Добавьте блок статической инициализации в класс тестового контейнера проекта и укажите местоположение файла конфигурации Logback в системном свойстве `logback.configurationFile`:
+
[source, java]
----
include::{sourcesdir}/development/testing_9.java[]
----
--

[[integration_tests_mw_data_store]]
Дополнительные хранилища::
+
--
Если в вашем проекте используются <<data_store,дополнительные хранилища>>, необходимо создать соответствующие источники данных JDBC в тестовом контейнере. Например, если у вас есть хранилище `mydb`, являющееся базой данных PostgreSQL, добавьте следующий метод в класс тестового контейнера:

[source, java]
----
include::{sourcesdir}/development/testing_10.java[]
----

Кроме того, если тип дополнительной базы данных отличается от основной, необходимо добавить ее драйвер как `testRuntime` зависимость модуля `core` в `build.gradle`, например:

[source, java]
----
include::{sourcesdir}/development/testing_12.groovy[]
----
--
