:sourcesdir: ../../../../source

[[integration_tests_mw]]
==== Интеграционные тесты Middleware

На уровне Middleware можно создавать интеграционные тесты, которые выполняются в полнофункциональном контейнере Spring с подключением к базе данных. В тестах такого типа можно выполнять код любого слоя внутри Middleware - от сервисов до ORM.

Для того, чтобы выполнять тесты из IDE, создайте каталог `test` в модуле *core* рядом с `src`. После этого пересоздайте проектные файлы IDE.

Платформа содержит класс `TestContainer`, который может быть использован в качестве базового для тестовых контейнеров приложения. Создайте наследника этого класса в каталоге `test` модуля *core* и в его конструкторе переопределите параметры загрузки <<app_components, компонентов>> и <<app_properties_files, свойств приложения>>, а также параметры подключения к тестовой БД. Например:

[source, java]
----
include::{sourcesdir}/development/testing_3.java[]
----

Пример собственного файлв `test-app.properties`:

[source, java]
----
include::{sourcesdir}/development/testing_11.java[]
----

В качестве базы данных рекомендуется использовать отдельную тестовую БД, которую можно создавать, например, следующей <<build.gradle_createDb, задачей>> в `build.gradle`:

[source, groovy]
----
include::{sourcesdir}/development/testing_4.java[]
----

Тестовый контейнер используется в классах тестов в качестве JUnit rule, указанного с помощью аннотации `@ClassRule`:

[source, java]
----
include::{sourcesdir}/development/testing_5.java[]
----

В данном примере тестовый контейнер инициализируется один раз для всех тестовых методов класса, и уничтожается после того, как все они выполнены.

Так как запуск контейнера занимает некоторое время, имеет смысл инициализировать контейнер один раз для тестов из нескольких (или всех) классов. Для этого создайте общий синглтон-экземпляр тестового контейнера, например:

[source, java]
----
include::{sourcesdir}/development/testing_6.java[]
----

И используйте его в тестовых классах:

[source, java]
----
include::{sourcesdir}/development/testing_7.java[]
----

Полезные методы тестового контейнера::
+
--
Класс `TestContainer` содержит следующие методы, которые можно использовать в коде тестов (см. пример `CustomerLoadTest` выше):

* `persistence()` - возвращает ссылку на интерфейс <<persistence,Persistence>>.

* `metadata()` - возвращает ссылку на интерфейс <<metadata,Metadata>>.

* `deleteRecord()` - этот набор перегруженных методов предназначен для использования в `@After` методах для удаления тестовых объектов из БД.
--

Логирование::
+
--
Класс `TestContainer` настраивает логирование в соответствие с файлом `test-logback.xml`, предоставляемым платформой. Данный файл содержится в артефакте `cuba-core-tests`.

Для того, чтобы настроить уровни логирования в своих тестах, необходимо выполнить следующее:

* Скопируйте файл `test-logback.xml` из артефакта платформы в корень каталога `test` модуля `core` проекта, например как `my-test-logback.xml`.

* Сконфигурируйте параметры логирования в `my-test-logback.xml`.

* Добавьте блок статической инициализации в класс тестового контейнера проекта и укажите местоположение файла конфигурации Logback в системном свойстве `logback.configurationFile`:
+
[source, java]
----
include::{sourcesdir}/development/testing_9.java[]
----
--

Дополнительные хранилища::
+
--
Если в вашем проекте используются <<data_store,дополнительные хранилища>>, необходимо создать соответствующие источники данных JDBC в тестовом контейнере. Например, если у вас есть хранилище `mydb`, являющееся базой данных PostgreSQL, добавьте следующий метод в класс тестового контейнера:

[source, java]
----
include::{sourcesdir}/development/testing_10.java[]
----
--


