:sourcesdir: ../../../../source

[[integration_tests_mw]]
==== Интеграционные тесты Middleware

Интеграционные тесты Middleware выполняются в полнофункциональном контейнере Spring с подключением к базе данных. В тестах такого типа можно выполнять код любого слоя внутри Middleware - от сервисов до ORM.

Для конфигурирования и запуска контейнера Spring в тестах среднего слоя создайте в приложении наследника базовового класса `com.haulmont.cuba.testsupport.TestContainer` и используйте его экземпляр в тестах в качестве JUnit Rule.

Ниже приведен пример класса контейнера и интеграционного теста для проекта Sales, описанного в разделе <<quick_start>>. Все классы должны находится в каталоге `test` модуля `core`.

[source, java]
----
include::{sourcesdir}/development/testing_3.java[]
----

Пример собственного файлв `test-app.properties`:

[source, properties]
----
include::{sourcesdir}/development/testing_11.properties[]
----

В качестве базы данных рекомендуется использовать отдельную тестовую БД, которую можно создавать, например, следующей <<build.gradle_createDb, задачей>> в `build.gradle`:

[source, groovy]
----
include::{sourcesdir}/development/testing_4.groovy[]
----

Тестовый контейнер используется в классах тестов в качестве JUnit rule, указанного с помощью аннотации `@ClassRule`:

[source, java]
----
include::{sourcesdir}/development/testing_5.java[]
----

Полезные методы тестового контейнера::
+
--
Класс `TestContainer` содержит следующие методы, которые можно использовать в коде тестов (см. пример `CustomerLoadTest` выше):

* `persistence()` - возвращает ссылку на интерфейс <<persistence,Persistence>>.

* `metadata()` - возвращает ссылку на интерфейс <<metadata,Metadata>>.

* `deleteRecord()` - этот набор перегруженных методов предназначен для использования в `@After` методах для удаления тестовых объектов из БД.
--

Логирование::
+
--
Класс `TestContainer` настраивает логирование в соответствие с файлом `test-logback.xml`, предоставляемым платформой. Данный файл содержится в артефакте `cuba-core-tests`.

Для того, чтобы настроить уровни логирования в своих тестах, необходимо выполнить следующее:

* Скопируйте файл `test-logback.xml` из артефакта платформы в корень каталога `test` модуля `core` проекта, например как `my-test-logback.xml`.

* Сконфигурируйте параметры логирования в `my-test-logback.xml`.

* Добавьте блок статической инициализации в класс тестового контейнера проекта и укажите местоположение файла конфигурации Logback в системном свойстве `logback.configurationFile`:
+
[source, java]
----
include::{sourcesdir}/development/testing_9.java[]
----
--

[[integration_tests_mw_data_store]]
Дополнительные хранилища::
+
--
Если в вашем проекте используются <<data_store,дополнительные хранилища>>, необходимо создать соответствующие источники данных JDBC в тестовом контейнере. Например, если у вас есть хранилище `mydb`, являющееся базой данных PostgreSQL, добавьте следующий метод в класс тестового контейнера:

[source, java]
----
include::{sourcesdir}/development/testing_10.java[]
----

Кроме того, если тип дополнительной базы данных отличается от основной, необходимо добавить ее драйвер как `testRuntime` зависимость модуля `core` в `build.gradle`, например:

[source, java]
----
include::{sourcesdir}/development/testing_12.groovy[]
----
--
