:sourcesdir: ../../../../source

[[qs_contract_edit_controller]]
==== Contract Editor Controller

Open the `ContractEdit` screen controller and replace its content with the following code:

[source,java]
----
include::{sourcesdir}/quickstart/ContractEdit.java[]
----

Let's examine the controller code in details.

The `ProcessActionsFragment` is the fragment that displays process actions available to the user at the moment. On initialization, the fragment searches for a related `ProcInstance` object by two parameters: process code and entity instance. If the `ProcInstance` object is not found then a new instance is created, and the fragment displays the start process button. If the related process instance is found then the fragment searches for an uncompleted process task for the current user and displays buttons for process task actions. See <<proc_actions_fragment>> for details.

In the contract editor, the process actions fragment initialization is performed in the `onBeforeShow()` by the invocation of the `init(PROCESS_CODE, getEditedEntity())`. The `PROCESS_CODE` stores a process code (`contractApproval` – we saw this value during the model deployment, see <<qs_process_model_deployment>>). The second argument `getEditedEntity()` is the current edited contract.

The `standard()` initialization does the following:

* initializes standard process actions predicates that will be invoked before the process is started and before process tasks are completed. The predicates commit the entity editor.

* initializes standard listeners that will show notifications like "Process started" or "Task completed" and refresh the `procActionsFragment` after the process is started or process task is completed.
