:sourcesdir: ../../../../../../source

[[transactionalDataManager]]
====== TransactionalDataManager

`TransactionalDataManager` is a bean of the middle tier which mimics the `DataManager` interface but can join an existing transaction. It has the following features:

* If there is an active transaction, joins it, otherwise creates and commits a transaction same as `DataManager`.

* It accepts and returns entities in detached state. The developer should load entities with appropriate <<views,views>> and explicitly use the `save()` method to save modified instances to the database.

* It applies row-level security, works with dynamic attributes and cross-datastore references in the same way as `DataManager`.

Below is a simple example of using `TransactionalDataManager` in a service method:

[source,java]
----
include::{sourcesdir}/common/transactionalDataManager_1.java[]
----

You can find more complex example in the framework test: https://github.com/cuba-platform/cuba/blob/{git_branch}/modules/core/test/com/haulmont/cuba/core/DataManagerTransactionalUsageTest.java[DataManagerTransactionalUsageTest.java]

[TIP]
====
`TransactionalDataManager` is especially useful when handling <<entityChangedEvent,EntityChangedEvent>> in the current transaction. It allows you to get the current state of the changed entity from the database before the transaction is committed.
====