:sourcesdir: ../../../../../source

[[persistenceTools]]
===== PersistenceTools

<<managed_beans,ManagedBean>>, содержащий вспомогательные методы работы с хранилищем данных. Интерфейс `PersistenceTools` можно получить либо методом `Persistence.getTools()`, либо как любой другой бин - инжекцией или через класс `AppBeans`.

Методы `PersistenceTools`:

* `getDirtyFields()` - возвращает коллекцию имен атрибутов сущности, измененных со времени последней загрузки экземпляра из БД. Для новых экземпляров возвращает пустую коллекцию.

* `isLoaded()` - определяет, загружен ли из БД указанный атрибут экземпляра. Атрибут может быть _не_ загружен, если он не указан в примененном при загрузке <<views,представлении>>. 
+
Данный метод работает только для экземпляров в состоянии <<entity_states,Managed>>.

* `getReferenceId()` - возвращает идентификатор связанной сущности без загрузки ее из БД. 
+
Предположим, в <<persistence_context,персистентный контекст>> загружен экземпляр `Order`, и нужно получить значение идентификатора экземпляра `Customer`, связанного с данным Заказом. Стандартное решение `order.getCustomer().getId()` приведет к выполнению SQL запроса к БД для загрузки экземпляра `Customer`, что в данном случае избыточно, так как значение идентификатора Покупателя физически находится также и в таблице Заказов. Выполнение же
+
[source, java]
----
include::{sourcesdir}/middleware/persistencetools_1.java[]
----

не вызовет никаких дополнительных запросов к базе данных. 

Данный метод работает только для экземпляров в состоянии <<entity_states,Managed>>.

Для расширения набора вспомогательных методов в конкретном приложении бин `PersistenceTools` можно <<bean_extension,переопределить>>. Примеры работы с расширенным интерфейсом:

[source, java]
----
include::{sourcesdir}/middleware/persistencetools_2.java[]
----

[source, java]
----
include::{sourcesdir}/middleware/persistencetools_3.java[]
----

