:sourcesdir: ../../../../../source

[[baseAction]]
===== BaseAction

`BaseAction` - базовый класс реализации <<gui_Action,действий>>. От него рекомендуется наследовать собственные нестандартные действия, если возможностей <<declarative_actions,декларативного создания действий>> не хватает. 

При создании конкретного класса действия необходимо определить метод `actionPerform()` и передать в конструктор `BaseAction` идентификатор действия. Можно также переопределить любые методы получения свойств действия: `getCaption()`, `getDescription()`, `getIcon()`, `getShortcut()`, `isEnabled()`, `isVisible()`, `isPrimary()`. Стандартные реализации этих методов возвращают значения, установленные соответствующими set-методами. Исключение составляет метод `getCaption()`: если название действия явно не установлено методом `setCaption()`, то он обращается в <<message_packs,пакет локализованных сообщений>> с именем, соответствующим пакету класса действия, и возвращает сообщение с ключом, равным идентификатору действия. Если сообщения с таким ключом нет, то возвращается сам ключ, то есть идентификатор действия.

В качестве альтернативы переопределению методов можно использовать fluent interface для установки свойств и lambda expression для предоставления кода обработки действия: см. методы  `withXYZ()`.

`BaseAction` может изменять свои свойства `enabled` и `visible` в соответствии с <<permissions,разрешениями>> пользователя и текущим контекстом.

`BaseAction` видим (visible), если: 

* метод `setVisible(false)` не вызывался;

* для действия не установлено UI разрешение `hide`.

Действие разрешено (enabled), если: 

* метод `setEnabled(false)` не вызывался;

* для действия не установлено UI разрешений `hide` или `read-only`;

* метод `isPermitted()` возвращает true;

* метод `isApplicable()` возвращает true. 

Примеры использования:

* Действие кнопки: 
+
[source, java]
----
include::{sourcesdir}/gui/baseAction_1.java[]
----
+
В данном случае кнопка `helloBtn` получит в качестве заголовка строку, находящуюся в пакете сообщений с ключом `hello`. Для того, чтобы получить название кнопки каким-либо иным способом, можно переопределить метод `getCaption()` действия.

* Действие кнопки программно создаваемого <<gui_PickerField,PickerField>>:
+
[source, java]
----
include::{sourcesdir}/gui/baseAction_2.java[]
----
+
Здесь анонимный класс-наследник `BaseAction` используется для задания действия кнопки поля выбора. Заголовок кнопки не отображается, вместо него используется значок и описание, всплывающее при наведении курсора мыши.

* Действие таблицы:
+
[source, java]
----
include::{sourcesdir}/gui/baseAction_3.java[]
----
+
Здесь объявлен класс `HelloAction`, экземпляр которого добавляется в список действий таблицы. Действие разрешено пользователям, имеющим специфическое разрешение `*myapp.allow-greeting*`, и только когда выбрана одна строка таблицы. Последнее условие реализуется с помощью свойства `target` действия, которое автоматически устанавливается когда действие добавляется в `ListComponent` (`Table` или `Tree`).

* Если необходимо действие, которое доступно, когда выделены одна или более строк таблицы, удобно воспользоваться наследником `BaseAction` - классом `ItemTrackingAction`, который добавляет стандартную реализацию метода `isApplicable()`: 
+
[source, java]
----
include::{sourcesdir}/gui/baseAction_4.java[]
----

