:sourcesdir: ../../../../../source

[[custom_action_types]]
===== Собственные типы действий

В проекте можно создать собственнные типы действий или переопределить существующие стандартные типы.

Предположим, что вы хотите создать действие, которое бы показывало имя экземпляра текущей сущности, выбранной в таблице, и использовать это действие в различных экранах, указывая только его тип. Чтобы это сделать, необходимо выполнить следующие шаги:

. Создайте для действия отдельный класс с аннотацией `@ActionType`, в которой укажите желаемое имя типа:
+
[source, java]
----
include::{sourcesdir}/gui/std_actions/std_actions_2.java[]
----

. В файле `web-spring.xml` добавьте элемент `<gui:actions>`, и в его атрибуте `base-packages` укажите пакет, в котором нужно искать ваши аннотированные действия:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_2_1.xml[]
----

. Теперь вы можете использовать действие в дескрипторах экрана, просто указывая его тип:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_2_2.xml[]
----

[TIP]
====
Если вы хотите переопределить существующий тип действия, просто зарегистрируйте свое новое действие с таким же типом.
====