:sourcesdir: ../../../../../source

[[standard_actions]]
===== Стандартные действия

Стандартные <<gui_Action,действия>>, предлагаемые платформой, предназначены для решения типовых задач, таких как вызов экрана редактирования для сущности, выбранной в таблице. Стандартные действия можно объявлять в XML-дескрипторе экрана, просто указав их тип в атрибуте `type`, к примеру:

[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_1.xml[]
----

Конфигурация стандартного действия зависит от его типа и вызывающего компонента. В некоторых случаях стандартные действия могут требовать определения дополнительных параметров, в других случаях их можно использовать как есть.

Существует два вида стандартных действий:

* <<std_list_actions,Действия с коллекцией>> сущностей, отображаемой в таблице или дереве.

* <<std_picker_actions,Действия поля выбора>> экземпляра сущности.

В своих проектах вы можете создавать похожие действия или переопределять существующие стандартные типы.

Предположим, что вы хотите создать действие, которое бы показывало имя экземпляра текущей сущности, выбранной в таблице, и использовать это действие в различных экранах, указывая только его тип. Чтобы это сделать, необходимо выполнить следующие шаги:

. Создайте для действия отдельный класс с аннотацией `@ActionType`, в которой укажите желаемое имя типа:
+
[source, java]
----
include::{sourcesdir}/gui/std_actions/std_actions_2.java[]
----

. В файле `web-spring.xml` добавьте элемент `<gui:actions>`, и в его атрибуте `base-packages` укажите пакет, в котором нужно искать ваши аннотированные действия:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_2_1.xml[]
----

. Теперь вы можете использовать действие в дескрипторах экрана, просто указывая его тип:
+
[source, xml]
----
include::{sourcesdir}/gui/std_actions/std_actions_2_2.xml[]
----

include::standard_actions/std_list_actions.adoc[]

include::standard_actions/std_picker_actions.adoc[]

