:sourcesdir: ../../../../../source

[[meta_annotations]]
===== Meta-Annotations

Entity meta-annotations are a set of key/value pairs providing additional information about entities.

Meta-annotations are accessed using <<metaClass,meta-class>> `getAnnotations()` method.

The sources of meta-annotations are: 

* `@OnDelete`, `@OnDeleteInverse`, `@Extends` <<entity_annotations,annotations>>. These annotations cause creation of special meta-annotations for describing relations between entities.

* Extendable meta-annotations marked with `@MetaAnnotation`. These annotations are converted to meta-annotations with a key corresponding to the full name of Java class of the annotation and a value which is a map of annotation attributes. For example, `@TrackEditScreenHistory` annotation will have a value which is a map with a single entry: `value -> true`. The platform provides the following annotations of this kind: `@NamePattern`, `@SystemLevel`, `@EnableRestore`, `@TrackEditScreenHistory`. In your application or <<app_components,application components>>, you can create your own annotation classes and mark them with `@MetaAnnotation` annotation.

* Optional: entity meta-annotations can also be defined in <<metadata.xml,metadata.xml>> files. If a meta-annotation in XML has the same name as the meta-annotation created by Java entity class annotation, then it will override the latter.
+
The example below shows how to override meta-annotations in `metadata.xml`:
+
[source, xml]
----
include::{sourcesdir}/common/metaannotations_1.xml[]
----

