:sourcesdir: ../../../../../source

[[private_repo_install]]
===== Установка менеджера репозиториев

В данном руководстве будет рассмотрен пример установки менеджера репозитория Sonatype Nexus OSS.

В операционной системе Microsoft Windows::
+
--
- link:http://www.sonatype.org/downloads/nexus-latest-bundle.zip[Скачайте] на компьютер программу Sonatype Nexus OSS версии 2.x (протестирована версия 2.14.3)
- Распакуйте архив в папку `c:\nexus-2.14.3-02`
- Измените параметры в файле настроек `c:\nexus-2.14.3-02\conf\nexus.properties`
+
** Вы можете указать сетевой порт, по умолчанию установлен 8081
** Настройте путь к папке с данными кэша:
+
замените
+
[source]
----
nexus-work=${bundleBasedir}/../sonatype-work/nexus
----
+
на
+
[source]
----
nexus-work=${bundleBasedir}/nexus/sonatype-work/content
----

- Перейдите в папку `c:\nexus-2.14.3-02\bin`
-  Чтобы иметь возможность запускать *nexus* как службу, установите wrapper (запустите команду с правами Администратора):
+
[source]
----
nexus.bat install
----

- Запустите службу *nexus*.
- Откройте в браузере адрес `++http://localhost:8081/nexus++` и войдите, используя данные по умолчанию: логин `admin` и пароль `admin123`.
--

С помощью Docker::
+
--
Локальный репозиторий можно также легко установить с помощью Docker. См. инструкции на link:https://hub.docker.com/r/sonatype/nexus[Docker Hub].

- Запустите `docker pull sonatype/nexus:oss` чтобы загрузить свежий образ.
- Запустите контейнер: `docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss`
- Контейнер будет готов к использованию в течение нескольких минут. Его работоспобность можно проверить следующими способами:
+
** `curl ++http://localhost:8081/nexus/service/local/status++`
+
** Открыть `++http://localhost:8081/nexus++` в веб-браузере.
- Логин `admin`, пароль `admin123`.
--
