:sourcesdir: ../../../../../source

[[private_repo_configure]]
===== Настройка прокси-репозитория

Щелкните на ссылку *Repositories* в панели слева.

На открывшейся странице нажмите кнопку *Add*, затем выберите пункт *Proxy Repository*. Будет создан новый репозиторий. Заполните обязательные поля на вкладке *Configuration*:

- *Repository ID*: `cuba-work`
- *Repository Name*: `cuba-work`
- *Provider*: `Maven2`
- *Remote Storage Location*: `++https://repo.cuba-platform.com/content/groups/work++`
- Отключите опцию *Auto Blocking Enabled*: `false`
- Включите опцию *Authentication*, задайте имя пользователя *Username*: `cuba`, пароль *Password*: `cuba123`
- Нажмите кнопку *Save*.

Создайте группу репозиториев. В Nexus нажмите кнопку *Add*, затем выберите *Repository Group* и проделайте следующие шаги на вкладке *Configuration*:

- Введите *Group ID*: `cuba-group`
- Введите *Group Name*: `cuba-group`
- Выберите *Provider*: `Maven2`
- Перенесите репозиторий *cuba-work* из *Available Repositories* в *Ordered Group Repositories*
- Нажмите кнопку *Save*.

Если у вас есть подписка на Премиум-дополнения, то создайте еще один репозиторий со следующими настройками:

- *Repository ID*: `cuba-premium`
- *Repository Name*: `cuba-premium`
- *Provider*: `Maven2`
- *Remote Storage Location*: `++https://repo.cuba-platform.com/content/groups/premium++`
- Отключите опцию *Auto Blocking Enabled*: `false`
- Включите опцию *Authentication*, используйте первую часть лицензионного ключа (до дефиса) в поле *Username* и вторую часть ключа (после дефиса) в поле *Password*
- Нажмите кнопку *Save*
- Нажмите кнопку *Refresh*
- Щелкните по репозиторию *cuba-group*
- На вкладке *Configuration* добавьте репозиторий *cuba-premium* в группу *cuba-group* следом за репозиторием *cuba-work*
- Нажмите кнопку *Save*.

