:sourcesdir: ../../../source

[[app-component.xml]]
=== app-component.xml

Файл `app-component.xml` требуется для того, чтобы данное приложение можно было использовать в качестве <<app_components,компонента>> другого приложения. Файл определяет зависимости от других компонентов, описывает существующие <<app_modules,модули приложения>>, генерируемые <<artifact,артефакты>> и предоставляемые <<app_properties,свойства приложения>>.

Файл `app-component.xml` должен располагаться в пакете, указанном в элементе `App-Component-Id` манифеста JAR модуля *global*. Данный элемент манифеста позволяет системе сборки находить компоненты проекта, находящиеся в class path в момент сборки. В результате, для подключения некоторого компонента к проекту, достаточно добавить координаты артефакта модуля *global* компонента в элементе `dependencies/appComponent` файла <<build.gradle,build.gradle>> проекта.

По соглашению, файл `app-component.xml` располагается в корневом пакете проекта (заданном в <<metadata.xml,metadata.xml>>), который также равен группе артефактов проекта (заданной в <<build.gradle,build.gradle>>):

[source, plain]
----
App-Component-Id == root-package == cuba.artifact.group == e.g. 'com.company.sample'
----

Для генерации файла `app-component.xml` и элементов манифеста рекомендуется использовать CUBA Studio.

Подключение зависимостей как appJars: ::
+
--
Если компонент содержит сторонние библиотеки, которые вы хотите использовать как артефакты модулей другого приложения (например, `app-comp-core` или `app-comp-web`), так, чтобы они были развёрнуты в каталоге `tomcat/webapps/app[-core]/WEB-INF/lib/`, эти зависимости необходимо добавить как библиотеки *appJar*:

[source, xml]
----
include::{sourcesdir}/config_files/appJar.xml[]
----

[TIP]
====
В случае, если вы не планируете использовать проект в качестве компонента других приложений, сторонние зависимости нужно указывать как *appJars* в задаче <<build.gradle_deploy,deploy>> файла `build.gradle`:

[source, groovy]
----
include::{sourcesdir}/config_files/appJar.groovy[]
----
====
--

