:sourcesdir: ../../../source

[[context.xml]]
=== context.xml

Файл `context.xml` является дескриптором развертывания приложения на сервере *Apache Tomcat*. В развернутом приложении этот файл располагается в подкаталоге `META-INF` каталога веб-приложения или WAR-файла, например, `tomcat/webapps/app-core/META-INF/context.xml`. В проекте файлы данного типа находятся в каталогах `/web/META-INF` модулей *core*, *web*, *portal*.

Основное предназначение файла для блока Middleware - определить JDBC источник данных и поместить его в JNDI под именем, заданным свойством приложения <<cuba.dataSourceJndiName,cuba.dataSourceJndiName>>.

Пример определения источника данных для *PostgreSQL*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="org.postgresql.Driver"
  username="cuba"
  password="cuba"
  url="jdbc:postgresql://localhost/sales"/>
----

Пример определения источника данных для *Microsoft SQL Server 2005*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="net.sourceforge.jtds.jdbc.Driver"
  username="sa"
  password="saPass1"
  url="jdbc:jtds:sqlserver://localhost/sales"/>
----

Пример определения источника данных для *Microsoft SQL Server 2008+*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="net.sourceforge.jtds.jdbc.Driver"
  username="sa"
  password="saPass1"
  url="jdbc:jtds:sqlserver://localhost/sales"/>
----

Пример определения источника данных для *Oracle*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="oracle.jdbc.OracleDriver"
  username="sales"
  password="sales"
  url="jdbc:oracle:thin:@//localhost:1521/orcl"/>
----

Пример определения источника данных для *MySQL*:

[source, xml]
----
<Resource
  type="javax.sql.DataSource"
  name="jdbc/CubaDS"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="com.mysql.jdbc.Driver"
  password="cuba"
  username="cuba"
  url="jdbc:mysql://localhost/sales?useSSL=false&amp;allowMultiQueries=true"/>
----

Следующая строка отключает сериализацию HTTP-сессий:

[source, xml]
----
<Manager pathname=""/>
----

