:sourcesdir: ../../../source

[[metadata.xml]]
=== metadata.xml

Файлы данного типа используются для регистрации кастомных <<datatype,типов данных>> и неперсистентных сущностей, и для задания <<meta_annotations,мета-аннотаций>>.

Схема XML доступна по адресу {xsd_url}/metadata.xsd.

Расположение файла `metadata.xml` задается в свойстве приложения <<cuba.metadataConfig,cuba.metadataConfig>>.

Рассмотрим структуру файла.

`metadata` - корневой элемент.

Элементы `metadata`:

* `datatypes` - опциональный описатель кастомных типов данных.
+
Элементы `datatypes`:

** `datatype` - описатель типа данных. Имеет следующие атрибуты:
+
--
*** `id` - идентификатор, используемый для ссылки на данный тип из аннотации <<metaProperty_annotation,@MetaProperty>>.
*** `class` - задает класс имплементации.
*** `sqlType` - необязательный атрибут, задающий SQL-тип базы данных, подходящий для хранения значений данного типа. SQL-тип используется в Studio при генерации скриптов для БД. Подробнее см. <<datatype_custom_example,>>.

Элемент `datatype` может также содержать другие атрибуты, зависящие от конкретного класса реализации `Datatype`.
--

Должен иметь атрибут `class`, задающий класс реализации. Другие атрибуты опциональны и зависят от реализации. См. <<datatype_custom_example,>>.

* `metadata-model` - описатель метамодели проекта.
+
Атрибуты `metadata-model`:

** `root-package` - корневой пакет проекта.
+
Элементы `metadata-model`:

** `class` - класс неперсистентной сущности.

* `annotations` - корень элементов присвоения <<meta_annotations,мета-аннотаций>> сущностей.
+
Элемент `annotations` содержит список элементов `entity`, которые определяют сущности, для которых задаются мета-аннотации. Каждый элемент `entity` должен содержать атрибут `class`, который задает класс сущности, и список элементов `annotation`.
+
Элемент `annotation` определяет мета-аннотацию. Он имеет атрибут `name`, соответствующий имени мета-аннотации. Мэп атрибутов мета-аннотации задается списком вложенных элементов `attribute`.

Пример:

[source, xml]
----
include::{sourcesdir}/config_files/metadata_1.xml[]
----

