:sourcesdir: ../../../source

[[permissions.xml]]
=== permissions.xml

Файлы данного типа используются в блоке Web Client для регистрации специфических <<permissions,разрешений>> пользователей.

Расположение файла задается в свойстве приложения <<cuba.permissionConfig,cuba.permissionConfig>>. При создании нового проекта в Studio, она создает файл `web-permissions.xml` в корневом пакете модуля *web*, например `modules/web/src/com/company/sample/web-permissions.xml`.

Схема XML доступна по адресу {xsd_url}/permissions.xsd.

Рассмотрим структуру файла.

`permission-config` - корневой элемент.

Элементы `permission-config`:

* `specific` - описатель специфических разрешений.
+
Элементы `specific`:

** `category` - категория разрешений, используется для группировки в экране управления разрешениями <<roles,роли>>. Атрибут `id` используется как ключ для получения локализованного названия категории.

** `permission` - именованное разрешение. Атрибут `id` используется для получения значения разрешения методом `Security.isSpecificPermitted()`, а также как ключ для получения локализованного названия разрешения для отображения в экране управления разрешениями <<roles,роли>>.

Пример:

[source, xml]
----
include::{sourcesdir}/config_files/permissions.xml[]
----

Для того чтобы локализовать названия категорий и специфических разрешений, задайте ключи в <<main_message_pack,главном пакете сообщений>>:

[source, properties]
----
include::{sourcesdir}/config_files/messages.properties[]
----

