:sourcesdir: ../../../source

[[permissions.xml]]
=== permissions.xml

Файлы данного типа используются в блоках *Web Client* и *Desktop Client* для регистрации специфических <<permissions,разрешений>> пользователей. 

Расположение файла задается в свойстве приложения <<cuba.permissionConfig,cuba.permissionConfig>>. При создании нового проекта в Studio, она создает файл `web-permissions.xml` в корневом пакете модуля *web*, например `modules/web/src/com/company/sample/web-permissions.xml`.

Схема XML доступна по адресу {xsd_url}/permissions.xsd.

Рассмотрим структуру файла.

`permission-config` - корневой элемент.

Элементы `permission-config`:

* `specific` - описатель специфических разрешений.
+
Элементы `specific`:

** `category` - категория разрешений, используется для группировки в экране управления разрешениями <<roles,роли>>. Атрибут `id` используется как ключ для получения локализованного названия категории.

** `permission` - именованное разрешение. Атрибут `id` используется для получения значения разрешения методом `Security.isSpecificPermitted()`, а также как ключ для получения локализованного названия разрешения для отображения в экране управления разрешениями <<roles,роли>>.

Пример:

[source, xml]
----
<permission-config xmlns="http://schemas.haulmont.com/cuba/permissions.xsd">
  <specific>
      <category id="app">
          <permission id="app.doSomething"/>
          <permission id="app.doSomethingOther"/>
      </category>
  </specific>
</permission-config>
---- 

