:sourcesdir: ../../../source

[[web.xml]]
=== web.xml

Файл `web.xml` является стандартным дескриптором веб-приложения Java EE, и должен быть создан для блоков Middleware, Web Client и Web Portal.

В проекте приложения файлы `web.xml` располагаются в каталогах `web/WEB-INF` соответствующих <<app_modules,модулей>>.

* Рассмотрим содержимое `web.xml` блока Middleware (модуль *core* проекта):
+
--
[source, xml]
----
include::{sourcesdir}/config_files/web_1.xml[]
----

В элементах `context-param` задаются инициализирующие параметры объекта `ServletContext` данного веб-приложения. Список <<app_components,компонентов приложения>> задается в параметре `appComponents`, список <<app_properties_files,файлов свойств приложения>> задается в параметре `appPropertiesConfig`.

В элементе `listener` задается класс слушателя, реализующего интерфейс `ServletContextListener`. В блоке Middleware CUBA-приложения в качестве слушателя должен использоваться класс `AppContextLoader`, выполняющий инициализацию <<appContext,AppContext>>.

Далее следуют определения сервлетов, среди которых обязательным для Middleware является класс `RemotingServlet`, связанный с контейнером удаленного доступа (см. <<remoting-spring.xml,>>). Данный сервлет отображен на URL `++/remoting/*++`.
--

* Рассмотрим содержимое `web.xml` блока Web Client (модуль *web* проекта):
+
--
[source, xml]
----
include::{sourcesdir}/config_files/web_2.xml[]
----

В элементах `context-param` заданы списки <<app_components,компонентов приложения>> и <<app_properties_files,файлов свойств приложения>>.

В качестве `ServletContextListener` в блоке Web Client используется класс `WebAppContextLoader`.

`JSR356WebsocketInitializer` необходим для поддержки протокола WebSockets.

Сервлет `CubaApplicationServlet` обеспечивает функционирование <<gui_framework,универсального пользовательского интерфейса>>, основанного на фреймворке Vaadin.

Сервлет `CubaDispatcherServlet` инициализирует дополнительный контекст Spring для работы контроллеров Spring MVC. Этот контекст конфигурируется файлом <<dispatcher-spring.xml,>>.
--

