:sourcesdir: ../../../../../source

[[scheduled_tasks_spring]]
===== Spring TaskScheduler

This mechanism is described in details in the *Task Execution and Scheduling* section of the Spring Framework manual.

`TaskScheduler` can be used to run methods of arbitrary Spring beans in any application <<app_tiers,block>> both at the middleware and client tiers.

Example of configuration in <<spring.xml,spring.xml>>:

[source, xml]
----
include::{sourcesdir}/features/scheduled_tasks_1.xml[]
----

In the example above, two tasks are declared, which invoke `someMethod()` and `someOtherMethod()` of the `++sales_Processor++` bean. `someMethod()` will be invoked at fixed time intervals (60 seconds) from the moment of application startup. `someOtherMethod()` is invoked according to the schedule specified by Cron expression (for the description of the format of such expressions, see http://quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger).

The actual launch of tasks is performed by the bean specified in the `scheduler` attribute of the `scheduled-tasks` element. It is the bean of the `CubaThreadPoolTaskScheduler` class which is configured in the *core* and *web* modules of the *cuba* application component (see `cuba-spring.xml`, `cuba-web-spring.xml`). This class provides some CUBA-specific housekeeping functionality.

In order to provide <<securityContext,SecurityContext>> to the code executed by Spring scheduled tasks on the middle tier, use <<system_authentication>>.

