:sourcesdir: ../../../../../source

[[file_storage_impl]]
===== Стандартная реализация хранилища

Стандартная реализация хранит файлы в специальной структуре каталогов на одном или нескольких файловых ресурсах.

Корни структуры можно задать в свойстве приложения <<cuba.fileStorageDir,cuba.fileStorageDir>>. Формат - список путей через запятую. Например:

[source, properties]
----
cuba.fileStorageDir=/work/sales/filestorage,/mnt/backup/filestorage
----

Если данное свойство не задано, хранилище будет создано в подкаталоге `filestorage` <<work_dir,рабочего каталога>> *Middleware*. В стандартном варианте развертывания в Tomcat это каталог `tomcat/work/app-core/filestorage`.

В случае указания нескольких ресурсов хранилище ведет себя следующим образом:

* Первый каталог в списке является _основным_, остальные - _резервными_.

* Запись сохраняемых файлов производится в основной каталог, а затем файл копируется во все резервные каталоги.
+
Перед записью проверяется доступность каждого каталога. Если недоступен основной каталог, выбрасывается исключение и запись не производится. Если недоступен какой-то из резервных каталогов, запись все равно производится, в лог выводится сообщение об ошибке.

* Чтение производится из основного каталога.
+
При недоступности основного каталога чтение производится из первого резервного каталога, в котором имеется данный файл. В лог выводится сообщение об ошибке.

Файловая структура хранилища организована следующим образом:

* Имеется три уровня каталогов, соответствующих дате загрузки файла - год, месяц, день.

* Файл сохраняется в каталоге дня. Именем файла является идентификатор соответствующего объекта `FileDescriptor`. Расширение файла - исходное.

* В корне структуры хранилища ведется файл `storage.log`, содержащий информацию о том, какой файл, когда и каким пользователем был записан в хранилище. Этот журнал не несет никакой функциональности, но может быть полезен при поиске проблем.

JMX-бин `app-core.cuba:type=FileStorage` отображает текущий список корней хранилища, а также предоставляет следующие методы для поиска проблем:

* `findOrphanDescriptors()` - найти в базе данных все экземпляры `FileDescriptor`, для которых не имеется соответствующего файла в хранилище.

* `findOrphanFiles()` - найти файлы в хранилище, для которых не имеется соответствующего экземпляра `FileDescriptor` в БД.

