:sourcesdir: ../../../../../../source

[[gui_data_comp_decl]]
====== Declarative Creation of Data Components

TODO
////
The simplest way to create data components for a screen is to define them in the screen XML descriptor in the `<data>` element.

Let's consider the data model consisting of `Customer`, `Order` and `OrderLine` entities. The edit screen for the `Order` entity can have the following XML definition:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_1.xml[]
----

In this case, the following data components are created:

* `DataContext` instance.

* `InstanceContainer` with `orderDc` id and `InstanceLoader` for the `Order` entity.

* `CollectionPropertyContainer` with `linesDc` id for the `OrderLines` entity. It is bound to the `Order.lines` collection attribute.

* `CollectionContainer` with `customersDc` id for the `Customer` entity. It is loaded by `CollectionLoader` using the specified query.

The data containers can be used in visual components as follows:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_2.xml[]
----

<1> Standalone fields have `dataContainer` and `property` attributes.
<2> `form` propagates `dataContainer` to its fields so they need only `property` attribute.
<3> Lookup fields have `optionsContainer` attribute.
<4> Tables have only `dataContainer` attribute.
////