:sourcesdir: ../../../../../../source

[[gui_data_comp_param]]
====== Использование параметров экрана в загрузчиках

Часто бывает необходимо загружать данные в экране в зависимости от параметров, переданных в этот экран. В данном разделе приведен пример экрана, принимающего параметр и использующего его для фильтрации загружаемых данных.

Предположим, имеются две сущности: `Country` и `City`. У сущности `City` есть атрибут `country`, который является ссылкой на `Country`. Экран со списком городов принимает экземпляр страны и отображает города только этой страны.

Рассмотрим XML-дескриптор экрана со списком городов. Его загрузчик содержит параметр:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_param_1.xml[]
----

Контроллер экрана городов содержит публичный метод-setter для параметра и использует этот параметр в обработчике <<screen_BeforeShowEvent,BeforeShowEvent>>. Обратите внимание, что на классе экрана нет аннотации `@LoadDataBeforeShow`, так как загрузка вызывается явно:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_param_1.java[]
----

Экран городов можно вызвать из другого экрана, передавая параметр, как показано ниже:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_param_2.java[]
----
