:sourcesdir: ../../../../../../source

[[gui_data_comp_sort]]
====== Специализированная сортировка

++++
<div class="manual-since-container">
    <a href="http://files.cuba-platform.com/cuba/release-notes/7.1/" class="since-btn" target="_blank">
        <span class="since-btn-caption">Since</span><span class="since-btn-version">7.1</span>
    </a>
</div>
++++

Сортировка таблиц по атрибутам сущности в UI производится объектом типа `CollectionContainerSorter`, который устанавливается для <<gui_collection_container,CollectionContainer>>. Стандартная реализация сортирует данные в памяти, если загруженный список умещается на одну страницу, или посылает запрос с соответствующим "order by" в базу данных. Выражение "order by" формируется бином `JpqlSortExpressionProvider` среднего слоя.

Некоторые атрибуты могут потребовать специальной реализации сортировки. Ниже рассматривается простой пример: предположим, в сущности `Foo` есть атрибут `number` типа `String`, но на самом деле атрибут хранит только числовые значения. Поэтому необходимо иметь порядок сортировки для чисел: `1, 2, 3, 10, 11`. Стандартный механизм сортировки в данном случае выдаст порядок `1, 10, 11, 2, 3`.

Сначала создайте наследника класса `CollectionContainerSorter` в модуле `web` для сортировки в памяти:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_1.java[]
----

Если специализированная сортировка нужна только в некоторых экранах, `CustomCollectionContainerSorter` можно инстанциировать прямо в экране:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_2.java[]
----

Если же специализированная сортировка должна являться глобальной, то создайте собственную фабрику, которая будет инстанциировать сортировщик для всей системы:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_3.java[]
----

Зарегистрируйте фабрику в `web-spring.xml` для того, чтобы переопределить стандартную фабрику:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_4.xml[]
----

Теперь создайте собственную реализацию `JpqlSortExpressionProvider` в модуле `core` для сортировки на уровне БД:

[source, java]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_5.java[]
----

Зарегистрируйте класс в `spring.xml` для того, чтобы переопределить стандартную реализацию поставщика выражений:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_sort_6.xml[]
----
