:sourcesdir: ../../../../../../source

[[gui_data_comp_decl]]
====== Декларативное создание компонентов данных

Самый простой способ создать компоненты данных - это определить их в XML-дескрипторе экрана внутри элемента `<data>`.

Рассмотрим для примера модель данных, содержащую сущности `Customer`, `Order` и `OrderLine`. Дескриптор экрана редактирования сущности `Order` может иметь следующее определение:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_1.xml[]
----

В этом случае будут созданы следующие компоненты данных:

<1> - Экземпляр `DataContext`.
<2> - Контейнер `InstanceContainer` для сущности `Order`.
<3> - Встроенное описание <<views,представления>> экземпляра сущности, находящегося в контейнере. Встроенные представления могут расширять общие (заданные в `views.xml`).
<4> - `InstanceLoader` загружающий экземпляры сущности `Order`.
<5> - Контейнер `CollectionPropertyContainer` для сущности `OrderLines`. Этот контейнер привязан к атрибуту-коллекции `Order.lines`.
<6> - Контейнер `CollectionContainer` для сущности `Customer`. Атрибут `view` может указывать на общее представление.
<7> - `CollectionLoader`, загружающий экземпляры сущности `Customer` по определённому запросу.

Контейнеры данных используются в визуальных компонентах следующим образом:

[source, xml]
----
include::{sourcesdir}/gui/data_comp/data_comp_2.xml[]
----

<1> Отдельные поля имеют атрибуты `dataContainer` и `property`.
<2> Элемент `form` распространяет свой `dataContainer` на все вложенные поля, поэтому они требуют только указания атрибута `property`.
<3> Поля выбора имеют атрибут `optionsContainer`.
<4> У таблиц есть только атрибут `dataContainer`.
