= Платформа CUBA. Полнотекстовый поиск
:toc: left
:stylesheet: cuba.css
:toc-title: Содержание
:appendix-caption: Приложение
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:icons: font
:lang: ru
:!last-update-label:
:revnumber: 6.0
:version-label: Версия
:revremark: Copyright (c) 2015 Haulmont (www.haulmont.com)

:!sectnums:

[preface]
== Предисловие

Данный документ является руководством по применению подсистемы _полнотекстового поиска_ (_full text search_, _FTS_) платформы CUBA.

[[audience]]
=== Целевая аудитория

Данное руководство предназначено для разработчиков, создающих на платформе CUBA приложения с возможностью полнотекстового поиска. Предполагается, что читатель ознакомлен с *Руководством по разработке приложений*, доступным по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

[[additional_info]]
=== Дополнительные материалы

Настоящее Руководство, а также другая документация по платформе CUBA доступны по адресу link:$$https://www.cuba-platform.ru/manual$$[www.cuba-platform.ru/manual].

Подсистема полнотекстового поиска CUBA основана на фреймворке *Apache Lucene*, поэтому знакомство с его устройством будет полезным. См. link:$$http://lucene.apache.org/core$$[lucene.apache.org/core].

[[feedback]]
=== Обратная связь

Если у Вас имеются предложения по улучшению данного руководства, обратитесь пожалуйста в службу поддержки по адресу link:$$https://ru.cuba-platform.com/support/topics$$[ru.cuba-platform.com/support/topics]. 

При обнаружении ошибки в документации укажите, пожалуйста, номер главы и приведите небольшой участок окружающего текста для облегчения поиска. 

:sectnums:

include::chapter1.adoc[]

include::chapter2.adoc[]

[[fts_config]]
[appendix]
== Файл конфигурации FTS

Файл конфигурации полнотекстового поиска представляет собой XML-файл, как правило располагающийся в каталоге `src` модуля *core* и содержащий описание индексируемых сущностей и их атрибутов.

Набор конфигурационных файлов FTS, включая определенные в базовых проектах, задается в свойстве приложения <<cuba.ftsConfig,
        cuba.ftsConfig
      >>.

Рассмотрим структуру файла.

`fts-config` - корневой элемент.

Элементы `fts-config`: 

* `entities` - список сущностей, подлежащих индексированию и поиску.
+
Элементы `entities`: 

** `entity` - описание индексируемой сущности.
+
Атрибуты `entity`:

*** `class` - Java класс сущности. 

*** `show` - должна ли данная сущность показываться в результатах поиска самостоятельно. Значение `false` используется для сущностей-связей, которые не интересны пользователю сами по себе, но нужны, например, для связи загруженных файлов и сущностей предметной области. По умолчанию `true`. 
+
Элементы `entity`: 

*** `include` - включить атрибут или несколько атрибутов сущности в индекс.
+
Атрибуты `include`: 

**** `re` - регулярное выражение для отбора атрибутов по имени. Отбираются только атрибуты следующих типов: строка, число, дата, перечисление.

**** `name` - имя атрибута. Может быть путем (через точку) по ссылочным атрибутам. Тип не проверяется, однако если имя является путем, то конечный атрибут должен быть сущностью, а не простым типом (атрибут простого типа не имеет здесь смысла, он должен индексироваться в своей сущности). 

*** `exclude` - исключить ранее включенный атрибут. Возможные атрибуты такие же, как в элементе `include`.

*** `searchables` - Groovy-скрипт для добавления в очередь на индексирование произвольных сущностей, связанных с измененной.
+
Например, когда изменяется (добавляется, удаляется) экземпляр `CardAttachment`, мы должны также переиндексировать связанный с ним экземпляр `Card`, так как сам собой `Card` в очередь не встанет, ибо не менялся.
+
При запуске в скрипт передаются следующие переменные:

**** `searchables` - список сущностей, который нужно пополнять.

**** `entity` - текущий экземпляр сущности, помещаемый в очередь автоматически.
+
Пример скрипта: 
+
[source, xml]
----
include::{sourcesdir}/fts_config_1.xml[]
---- 

*** `searchableIf` - Groovy-скрипт для ограничения помещения в очередь некоторых экземпляров индексируемой сущности. 
+
Например, может быть не нужно индексировать старые версии документов. 
+
При запуске в скрипт передается переменная `entity` - текущий экземпляр сущности. Скрипт должен вернуть булевское значение - `true` для того чтобы индексировать текущий экземпляр, `false` чтобы игнорировать его.
+
Пример скрипта: 
+
[source, xml]
----
include::{sourcesdir}/fts_config_2.xml[]
---- 

Пример файла конфигурации FTS: 

[source, xml]
----
include::{sourcesdir}/fts_config_3.xml[]
---- 

[[fts_properties]]
[appendix]
== Свойства приложения

В данном разделе перечислены свойства приложения, имеющие отношение к подсистеме полнотекстового поиска.

[[cuba.ftsConfig]]
cuba.ftsConfig:: 
+
--
Конфигурационный параметр, задает набор файлов конфигурации FTS в проекте.

Значением свойства должен быть список имен файлов, разделенный пробелами. Файлы загружаются по правилам интерфейса `Resources`. 

Используется в блоке Middleware.

Пример:

[source, properties]
----
cuba.ftsConfig = cuba-fts.xml fts.xml
----
--

Все свойства, описанные ниже, являются параметрами времени выполнения, хранятся в базе данных и доступны в коде приложения через конфигурационный интерфейс `FtsConfig`.

[[cuba.fts.enabled]]
cuba.fts.enabled:: 
+
--
Флаг, разрешающий использование функциональности FTS в проекте. 

Значение данного флага может быть оперативно изменено с помощью атрибута *Enabled* JMX-бина `app-core.fts:type=FtsManager`. 

Значение по умолчанию: `false`
--

[[cuba.fts.indexDir]]
cuba.fts.indexDir:: 
+
--
Абсолютный путь к каталогу для хранения индексных файлов. Если не установлен, используется подкаталог `ftsindex` рабочего каталога приложения (задаваемого свойством `cuba.dataDir`), в стандартном варианте развертывания это `tomcat/work/app-core/ftsindex`. 

Значение по умолчанию: не установлено
--

[[cuba.fts.indexingBatchSize]]
cuba.fts.indexingBatchSize:: 
+
--
Количество записей, извлекаемое из очереди на индексирование за один вызов метода `processQueue()`. 

Данное ограничение актуально для ситуации, когда в очереди на индексацию оказывается сразу очень большое число записей, например после выполнения метода `reindexAll()` JMX-бина `app-core.fts:type=FtsManager`. В этом случае индексация выполняется порциями, что занимает больше времени, но создает ограниченную и предсказуемую нагрузку на сервер.

Значение по умолчанию: `300`
--

[[cuba.fts.maxSearchResults]]
cuba.fts.maxSearchResults:: 
+
--
Максимальное количество результатов поиска. 

Значение по умолчанию: `100`
--

[[cuba.fts.searchResultsBatchSize]]
cuba.fts.searchResultsBatchSize:: 
+
--
Количество элементов в одной порции результатов поиска. Для показа следующей порции пользователь должен нажать *More* на экране результатов. 

Значение по умолчанию: `5`
--
