:sourcesdir: ../../source

[[fts_properties]]
[appendix]
== Свойства приложения

В данном разделе перечислены свойства приложения, имеющие отношение к подсистеме полнотекстового поиска.

[[cuba.ftsConfig]]
cuba.ftsConfig:: 
+
--
Аддитивный конфигурационный параметр, задает файл конфигурации FTS проекта.

Файл загружается с помощью интерфейса `Resources`, поэтому может быть расположен в classpath или в `конфигурационном каталоге`.

Используется в блоке Middleware.

Пример:

[source, properties]
----
cuba.ftsConfig = +com/company/sample/fts.xml
----
--

Все свойства, описанные ниже, являются параметрами времени выполнения, хранятся в базе данных и доступны в коде приложения через конфигурационный интерфейс `FtsConfig`.

[[fts.enabled]]
fts.enabled::
+
--
Флаг, разрешающий использование функциональности FTS в проекте. 

Значение данного флага может быть оперативно изменено с помощью атрибута *Enabled* JMX-бина `app-core.fts:type=FtsManager`. 

Значение по умолчанию: `false`
--

[[fts.indexDir]]
fts.indexDir::
+
--
Абсолютный путь к каталогу для хранения индексных файлов. Если не установлен, используется подкаталог `ftsindex` рабочего каталога приложения (задаваемого свойством `cuba.dataDir`), в стандартном варианте развертывания это `tomcat/work/app-core/ftsindex`. 

Значение по умолчанию: не установлено
--

[[fts.indexingBatchSize]]
fts.indexingBatchSize::
+
--
Количество записей, извлекаемое из очереди на индексирование за один вызов метода `processQueue()`. 

Данное ограничение актуально для ситуации, когда в очереди на индексацию оказывается сразу очень большое число записей, например, после выполнения метода `reindexAll()` JMX-бина `app-core.fts:type=FtsManager`. В этом случае индексация выполняется порциями, что занимает больше времени, но создает ограниченную и предсказуемую нагрузку на сервер.

Значение по умолчанию: `300`
--

[[fts.reindexBatchSize]]
fts.reindexBatchSize::
+
--
Количество записей, помещаемое в очередь на индексацию за один вызов метода `reindexNextBatch()`.

Значение по умолчанию: `5000`
--

[[fts.maxSearchResults]]
fts.maxSearchResults::
+
--
Максимальное количество результатов поиска. 

Значение по умолчанию: `100`
--

[[fts.searchResultsBatchSize]]
fts.searchResultsBatchSize::
+
--
Количество элементов в одной порции результатов поиска. Для показа следующей порции пользователь должен нажать *More* на экране результатов. 

Значение по умолчанию: `5`
--
