:sourcesdir: ../../source

[[fts_config]]
[appendix]
== Файл конфигурации FTS

Файл конфигурации полнотекстового поиска представляет собой XML-файл, как правило располагающийся в каталоге `src` модуля *core* и содержащий описание индексируемых сущностей и их атрибутов.

Файл конфигурации FTS задается в свойстве приложения <<cuba.ftsConfig,cuba.ftsConfig>>.

Рассмотрим структуру файла.

`fts-config` - корневой элемент.

Элементы `fts-config`: 

* `entities` - список сущностей, подлежащих индексированию и поиску.
+
Элементы `entities`: 
+
** `entity` - описание индексируемой сущности.
+
--
Атрибуты `entity`:

* `class` - Java класс сущности.

* `show` - должна ли данная сущность показываться в результатах поиска самостоятельно. Значение `false` используется для сущностей-связей, которые не интересны пользователю сами по себе, но нужны, например, для связи загруженных файлов и сущностей предметной области. По умолчанию `true`.

Элементы `entity`: 

* `include` - включить атрибут или несколько атрибутов сущности в индекс.
+
Атрибуты `include`: 
+
** `re` - регулярное выражение для отбора атрибутов по имени.
+
** `name` - имя атрибута. Может быть путем (через точку) по ссылочным атрибутам. Тип не проверяется, однако если имя является путем, то возможны два случая:
+
. Конечный атрибут должен быть сущностью (не embeddable), а не простым типом (атрибут простого типа не имеет здесь смысла, он должен индексироваться в своей сущности).
+
. Конечный атрибут должен быть простым типом встраиваемой (embeddable) сущности. Например, если индексируемая сущность имеет поле "address" типа Address (embeddable сущность), то имя атрибута в конфиге fts должно быть "address.city" или "address.street", а не просто "address".
--

* `exclude` - исключить ранее включенный атрибут. Возможные атрибуты такие же, как в элементе `include`.

* `searchables` - Groovy-скрипт для добавления в очередь на индексирование произвольных сущностей, связанных с измененной.
+
--
Например, когда изменяется (добавляется, удаляется) экземпляр `CardAttachment`, мы должны также переиндексировать связанный с ним экземпляр `Card`, так как сам собой `Card` в очередь не встанет, ибо не менялся.

При запуске в скрипт передаются следующие переменные:

* `searchables` - список сущностей, который нужно пополнять.

* `entity` - текущий экземпляр сущности, помещаемый в очередь автоматически.

Пример скрипта: 

[source, xml]
----
include::{sourcesdir}/fts_config_1.xml[]
---- 
--

* `searchableIf` - Groovy-скрипт для ограничения помещения в очередь некоторых экземпляров индексируемой сущности.
+
--
Например, может быть не нужно индексировать старые версии документов. 

При запуске в скрипт передается переменная `entity` - текущий экземпляр сущности. Скрипт должен вернуть булевское значение - `true` для того чтобы индексировать текущий экземпляр, `false` чтобы игнорировать его.

Пример скрипта: 

[source, xml]
----
include::{sourcesdir}/fts_config_2.xml[]
---- 
--

Пример файла конфигурации FTS: 

[source, xml]
----
include::{sourcesdir}/fts_config_3.xml[]
---- 

