:sourcesdir: ../../../../source

[[own_component_samples]]
==== Creating Custom Visual Components

As explained in the <<own_components>> section, the standard set of visual components can be extended in your project. You have the following options:

. Integrate a Vaadin add-on. Many third-party Vaadin components are distributed as add-ons and available at `https://vaadin.com/directory`.

. Integrate a JavaScript component. You can create a Vaadin component using a JavaScript library.

. Create a new Vaadin component with the client part written on GWT.

Futher on, you can integrate the resulting Vaadin component into CUBA Generic UI to be able to use it declaratively in screen XML descriptors and bind to datasources.

And the final step of integration is the support of the new component in the Studio WYSIWYG layout editor.

This section gives you examples of creating new visual components with all the methods described above. Integration to the Generic UI and support in Studio are the same for all methods, so these topics are described only for a new component created on the basis of a Vaadin add-on.

include::own_component_samples/vaadin_addon_sample.adoc[]

include::own_component_samples/vaadin_addon_sample_gui.adoc[]

include::own_component_samples/js_library_sample.adoc[]

include::own_component_samples/gwt_component_sample.adoc[]

include::own_component_samples/own_component_in_studio.adoc[]

