:sourcesdir: ../../../../../source

[[categorized_entity]]
===== Категоризируемые сущности

Если сущность реализует интерфейс `com.haulmont.cuba.core.entity.Categorized`, то для работы с ее динамическими атрибутами можно использовать компонент `DynamicAttributesPanel`. Этот компонент позволяет пользователю выбрать для экземпляра сущности некоторую категорию и указать значения динамических атрибутов этой категории.

Для использования `DynamicAttributesPanel` в экране редактирования необходимо выполнить следующее:

* Включите атрибут `category` в <<views,представление>> вашей категоризируемой сущности:

+
[source, xml]
----
include::{sourcesdir}/features/entity_with_category.xml[]
----
+
* Объявите <<gui_instance_container,контейнер данных>> в разделе `data`:

+
[source, xml]
----
include::{sourcesdir}/features/instance_with_dynamicAttributes.xml[]
----
+

--
Чтобы загрузить динамические атрибуты сущности, установите для параметра `dynamicAttributes` <<gui_data_loaders,загрузчика данных>> значение `true`. По умолчанию динамические атрибуты не загружаются.
--
* После этого можно включить в XML-дескриптор экрана визуальный компонент `dynamicAttributesPanel`:
+
[source, xml]
----
include::{sourcesdir}/features/dynamicAttrPanel.xml[]
----
+
--
С помощью параметра `cols` можно указать количество столбцов для отображения динамических атрибутов. Или использовать параметр `rows` для указания количества строк (в этом случае количество столбцов будет вычисляться автоматически). По умолчанию все атрибуты будут отображаться в одном столбце.

[TIP]
====
На вкладке <<dynamic_attributes_mgmt_attr_location,Attributes Location>> редактора категорий вы можете более гибко настроить отображение динамических атрибутов. В таком случае значения параметров `cols` и `rows` будут игнорироваться.
====

--