:sourcesdir: ../../../../source

[[screen_params_return]]
==== Возврат значений из экрана

++++
<div class="manual-live-demo-container">
    <a href="https://demo3.cuba-platform.com/generic-ui/open?screen=sample$Order.browse2" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

<<abstractFrame_openWindow,Методы>>, используемые для открытия экранов (`openWindow()`, `openLookup()`, `openEditor()`), позволяют также и возвращать значения из этих экранов.

Возврат значения из экрана выбора::
+
--
Метод `openLookup()` позволяет задать обработчик для сущностей, выбранных в открываемом экране. В нашем примере, с помощью этого обработчика, реализованного лямбда-выражением, мы установим выбранного покупателя для редактируемого экземпляра сущности `Order`.

[source, java]
----
include::{sourcesdir}/cookbook/window_params_4.java[]
----
--

Возврат значения из произвольного экрана::
+
--
Идея состоит в том, чтобы вернуть ссылку на контроллер открываемого экрана, и к этой ссылке добавить слушатель `CloseListener`, который будет обрабатывать значения после закрытия экрана.

Экран https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/web/src/com/company/sample/web/order/OrderEdit.java[OrderEdit] демонстрирует два способа выбора сущности https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/global/src/com/company/sample/entity/Customer.java[Customer]: из экрана выбора (lookup) и из независимого экрана, и оба способа позволяют вернуть экземпляр `Customer`.

Метод `openWindow()` в следующем примере открывает список покупателей в простом диалоговом окне. Слушатель `CloseWithCommitListener` получает сообщение о <<abstractWindow_close,закрытии>> экрана действием с `Window.COMMIT_ACTION_ID` и устанавливает выбранного покупателя для редактируемого экземпляра сущности `Order`.

[source, java]
----
include::{sourcesdir}/cookbook/window_params_5.java[]
----
--

