:sourcesdir: ../../../source

[[context.xml]]
=== context.xml

`context.xml` file is the application deployment descriptor for the *Apache Tomcat* server. In a deployed application, this file is located in the `META-INF` folder of the web application directory or the WAR file, for example, `tomcat/webapps/app-core/META-INF/context.xml`. In an application project, this file can be found in the `/web/META-INF` folders of the *core*, *web* and *portal* modules.

The main purpose of this file in the Middleware block is to define a JDBC data source with the JNDI name, specified in the <<cuba.dataSourceJndiName,cuba.dataSourceJndiName>> application property.

An example of a data source declaration for *PostgreSQL*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="org.postgresql.Driver"
  username="cuba"
  password="cuba"
  url="jdbc:postgresql://localhost/sales"/>
----

An example of a data source declaration for *Microsoft SQL Server 2005*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="net.sourceforge.jtds.jdbc.Driver"
  username="sa"
  password="saPass1"
  url="jdbc:jtds:sqlserver://localhost/sales"/>
----

An example of a data source declaration for *Microsoft SQL Server 2008+*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="com.microsoft.sqlserver.jdbc.SQLServerDriver"
  username="sa"
  password="saPass1"
  url="jdbc:sqlserver://localhost;databaseName=sales"/>
----

An example of a data source declaration for *Oracle*:

[source, xml]
----
<Resource
  name="jdbc/CubaDS"
  type="javax.sql.DataSource"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="oracle.jdbc.OracleDriver"
  username="sales"
  password="sales"
  url="jdbc:oracle:thin:@//localhost:1521/orcl"/>
----

An example of a data source declaration for *MySQL*:

[source, xml]
----
<Resource
  type="javax.sql.DataSource"
  name="jdbc/CubaDS"
  maxIdle="2"
  maxTotal="20"
  maxWaitMillis="5000"
  driverClassName="com.mysql.jdbc.Driver"
  password="cuba"
  username="cuba"
  url="jdbc:mysql://localhost/sales?useSSL=false&amp;allowMultiQueries=true"/>
----

The following line disables the serialization of HTTP sessions:

[source, xml]
----
<Manager pathname=""/>
----

