:sourcesdir: ../../../source

[[metadata.xml]]
=== metadata.xml

Files of this type are used for registering custom <<datatype,datatypes>> and non-persistent entities and assigning <<meta_annotations,meta annotations>>.

XML schema is available at {xsd_url}/metadata.xsd.

The `metadata.xml` file of the project is specified in the <<cuba.metadataConfig,cuba.metadataConfig>> application property.

The file has the following structure:

`metadata` – root element.

`metadata` elements:

* `datatypes` - an optional descriptor of custom datatypes.
+
`datatypes` elements:

** `datatype` - the datatype descriptor. It has the following attributes:
+
--
*** `id` - identifier, which should be used to refer to this datatype from <<metaProperty_annotation,@MetaProperty>> annotation.
*** `class` - defines the implementation class.
*** `sqlType` - optional attribute which specifies an SQL type of your database suitable for storing values of this data type. The SQL type will be used by CUBA Studio when it generates database scripts. See <<datatype_custom_example,>> for details.

The `datatype` element can also contain other attributes that depend on the implementation of the datatype.
--

* `metadata-model` – the project's meta model descriptor.
+
`metadata-model` attribute:

** `root-package` – the project's root package.
+
`metadata-model` elements:

** `class` – a non-persistent entity class.

* `annotations` – contains assignments of entity <<meta_annotations,meta-annotations>>.
+
The `annotations` element contains `entity` elements which define entities to assign meta-annotation to. Each `entity` element must contain the `class` attribute which specifies an entity class, and a list of `annotation` elements.
+
The `annotation` element defines a meta-annotation. It has the `name` attribute which corresponds to the meta-annotation name. The map of meta-annotation attributes is defined using the list of nested `attribute` elements.

Example:

[source, xml]
----
include::{sourcesdir}/config_files/metadata_1.xml[]
----

