:sourcesdir: ../../../source

[[web.xml]]
=== web.xml

The `web.xml` file is a standard descriptor of a Java EE web application and should be created for the Middleware, Web Client and Web Portal blocks.

In an application project, `web.xml` files are located in the `web/WEB-INF` folders of the corresponding <<app_modules,modules>>.

* `web.xml` for the Middleware block (*core* project module) has the following content:
+
--
[source, xml]
----
include::{sourcesdir}/config_files/web_1.xml[]
----

The `context-param` elements define initializing parameters for the `ServletContext` object of the current web application. The list of <<app_components,application components>> is defined in the `appComponents` parameter, the list of <<app_properties_files,application property files>> is defined in the `appPropertiesConfig` parameter.

The `listener` element defines a listener class implementing the `ServletContextListener` interface. The Middleware block uses the `AppContextLoader` class as a listener. This class initializes the <<appContext,AppContext>>.

Servlet descriptions follow, including the `RemotingServlet` class, mandatory for the Middleware block. This servlet is accessible via the `++/remoting/*++` URL, and is related to the remote access container (see <<remoting-spring.xml,>>).
--

* `web.xml` for the Web Client block (*web* project module) has the following content:
+
--
[source, xml]
----
include::{sourcesdir}/config_files/web_2.xml[]
----

In the `context-param` elements, the lists of <<app_components,application components>> and <<app_properties_files,application property files>> are defined. The `webResourcesTs` parameter with the value substituted at build time ensures correct caching of static resources in web browser.

The Web Client block uses the `WebAppContextLoader` class as a `ServletContextListener`.

The `JSR356WebsocketInitializer` listener is required for WebSockets protocol support.

`CubaApplicationServlet` provides the <<gui_framework,generic user interface>> implementation based on the Vaadin framework.

`CubaDispatcherServlet` initializes an additional Spring context for Spring MVC controllers. This context is configured in the <<dispatcher-spring.xml,>> file.

`CubaRestApiServlet` provides the universal <<rest_api_v2,REST API>>.
--

