[[cookbook]]
== Cookbook

// for backward compatibility
[[dev_recipes]]

This collection of practical recipes for developing on CUBA platform contains examples of implementing typical use cases and solving common problems. The information in each section is organized from basic to advanced topics, so feel free to jump to another section or leave the documentation at any time and start coding.

Most of the sections are accompanied by the sample applications. You can see them online, view their source code on GitHub or download and run locally. You will also see the applications on the *Samples* tab in Studio.

[TIP]
====
The cookbook is a work in progress and will be gradually improved. If you have any ideas for new recipes which are worth demonstrating, feel free to create issues in the source repository on https://github.com/cuba-platform/documentation[GitHub].
====

include::cookbook/business_logic_recipes.adoc[]

include::cookbook/modeling_domain_recipes.adoc[]

include::cookbook/ui_recipes.adoc[]

include::cookbook/data_recipes.adoc[]

include::cookbook/rest_api_v2_usage_example.adoc[]

include::cookbook/app_components_recipes.adoc[]

include::cookbook/misc_recipes.adoc[]

