[[dbms]]
=== Database Components
This section provides information on all possible types of DBMS supported by CUBA platform. Furthermore, a script-based mechanism, which allows creating a new database and keeping it up-to-date throughout the entire cycle of the development and operation of the application, is described.

Database components belong to the Middleware <<app_tiers,block>>; other blocks of the application do not have direct access to the database. 

Some additional information on working with the database is provided in <<db_dev>> and <<db_update_in_prod>>.

[[dbms_types]]
==== DBMS Types

The type of the DBMS used is defined by the <<cuba.dbmsType,cuba.dbmsType>> and (optionally) <<cuba.dbmsVersion,cuba.dbmsVersion>> application properties and the configuration of `javax.sql.DataSource` datasource, which the database access is made through. The instance of the datasource is extracted from the JNDI by name specified in the <<cuba.dataSourceJndiName,cuba.dataSourceJndiName>> application property. The configuration file for Tomcat, which defines the datasource, is described in <<context.xml>>

The platform supports the following DBMS "out of the box":

[options="header", cols="3*"]
|===
| ^|cuba.dbmsType ^|cuba.dbmsVersion
|HSQLDB |hsql|
|PostgreSQL 8.4+ |postgres|
|Microsoft SQL Server 2005, 2008 |mssql|
|Microsoft SQL Server 2012+ |mssql |2012
|Oracle Database 11g |oracle|
|===

The table below describes the recommended mapping of data types between entity attributes in Java and table columns in different DBMS. These types are automatically chosen by *CUBA Studio* when generating scripts to create and update the database. The operation of all platform mechanisms is guaranteed when using these types.

[options="header"]
|===
^|Java ^|HSQL ^|PostgreSQL ^|MS SQL Server ^|Oracle
|UUID|varchar(36)|uuid|uniqueidentifier|varchar2(32)
|Date|timestamp|timestamp|datetime|timestamp
|java.sql.Date|timestamp|date|datetime|date
|java.sql.Time|timestamp|time|datetime|timestamp
|BigDecimal|decimal(p, s)|decimal(p, s)|decimal(p, s)|number(p, s)
|Double|double precision|double precision|double precision|float
|Long|bigint|bigint|bigint|number(19)
|Integer|integer|integer|integer|integer
|Boolean|boolean|boolean|tinyint|char(1)
|String (limited)|varchar(n)|varchar(n)|varchar(n)|varchar2(n)
|String (unlimited)|longvarchar|text|varchar(max)|clob
|byte[]|longvarbinary|bytea|image|blob
|===

As a rule, the whole work to convert the data between the database and the Java code is performed by the <<orm,ORM layer>> in conjunction with the appropriate JDBC driver. This means that no manual conversion is required when working with the data using the <<entityManager,EntityManager>> methods and <<query,JPQL queries>> you should simply use Java types listed in the left column of the table.

When using native SQL through <<nativeQuery,EntityManager.createNativeQuery()>> or through <<queryRunner,QueryRunner>> some types in the Java code will be different from those mentioned above, depending on DBMS used. In particular, this applies to attributes of the `UUID` - type – only the PostgreSQL driver returns values of corresponding columns using this type; other servers return `String`. To abstract application code from the DBMS used, it is recommended to convert parameter types and query results using the <<dbTypeConverter,DbTypeConverter>> interface.

[[arbitrary_dbms]]
===== Support for Other DBMSs

In the application project, you can use any DBMS supported by the <<orm,ORM>> framework (OpenJPA). Follow the steps below:

* Specify the type of database in the form of an arbitrary code in the <<cuba.dbmsType,cuba.dbmsType>> property. The code must be different from those used in the platform: `hsql`, `postgres`, `mssql`, `oracle`.

* Implement the `DbmsFeatures`, `SequenceSupport`, `DbTypeConverter` interfaces by classes with the following names: `TypeDbmsFeatures`, `TypeSequenceSupport`, and `TypeDbTypeConverter`, respectively, where `Type` is the DBMS type code. The package of the implementation class must be the same as of the interface.

* If the project includes the *workflow* base project, override the `CubaJbpmSpringHelper` bean and its `getHibernateDialectName()` method to select the Hibernate dialect that will be used in jBPM.

* Create database init and update scripts in the directories marked with the DBMS type code. Init scripts must create all database objects required by the platform entities (you can copy them from the existing `10-cuba`, etc. directories and modify for your database).

* To create and update the database by Gradle tasks, you need to specify the additional parameters for these tasks in `build.gradle`:
+
[source, java]
----
include::{sourcesdir}/dbms/dbtasks_1.gradle[]
----

[[dbms_version]]
===== DBMS Version

In addition to <<cuba.dbmsType,cuba.dbmsType>> application property, there is an optional <<cuba.dbmsVersion,cuba.dbmsVersion>> property. It affects the choice of interface implementations for `DbmsFeatures`, `SequenceSupport`, `DbTypeConverter`, and the search for database init and update scripts.

The name of the implementation class of the integration interface is constructed as follows: `TypeVersionName`. Here, `Type` is the value of the `cuba.dbmsType` property (capitalized), `Version` is the value of `cuba.dbmsVersion`, and `Name` is the interface name. The package of the class must correspond to that of the interface. If a class with the same name is not available, an attempt is made to find a class with the name without version: `TypeName`. If such class does not exist either, an exception is thrown.

For example, the `com.haulmont.cuba.core.sys.persistence.Mssql2012SequenceSupport` class is defined in the platform. This class will take effect if the following properties are specified in the project:

[source, properties]
----
cuba.dbmsType = mssql
cuba.dbmsVersion = 2012
----

The search for <<db_scripts,database init and update scripts>> prioritizes the `type-version` directory over the `type` directory. This means that the scripts in the `type-version` directory replace the scripts with the same name in the `type` directory. The `type-version` directory can also contain some scripts with unique names; they will be added to the common set of scripts for execution, too. Script sorting is performed by path, starting with the first subdirectory of the `type` or `type-version` directory, i.e. regardless of the directory where the script is located (versioned or not).

For example, the init script for Microsoft SQL Server versions below and above 2012 should look as follows:

[source, properties]
----
modules/core/db/init/
   mssql/
       10.create-db.sql
       20.create-db.sql
       30.create-db.sql
   mssql-2012/
       10.create-db.sql 
----

[[db_scripts]]
==== Scripts to Create and Update the Database

A CUBA-application project always contains two sets of scripts:

* Scripts to __create__ the database, intended for the creation of the database from scratch. They contain a set of the DDL and DML operators, which create an empty database schema that is fully consistent with the current state of the <<data_model,data model>> of the application. These scripts can also fill the database with the necessary initialization data.

* Scripts to __update__ the database, intended for bringing the database structure to the current state of the data model from any of the previous states.

When changing the data model, it is necessary to reproduce the corresponding change of the database schema in create and update scripts. For example, when adding the `address` attribute to the `Customer` entity, it is necessary to:

. Change the table creation script:
+
[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_1.sql[]
----
. Add an update script, which modifies the same table:
+
[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_2.sql[]
----

The create scripts are located in the `/db/init` directory of the *core* module. For each type of DBMS supported by the application, a separate set of scripts is created and located in the subdirectory specified in <<cuba.dbmsType,cuba.dbmsType>> application property, for example `/db/init/postgres`. Create scripts names should have the following format `++{optional_prefix}create-db.sql++`.

The update scripts are located in the `/db/update` directory of the *core* module. For each type of DBMS supported by the application, a separate set of scripts is created and located in the subdirectory specified in <<cuba.dbmsType,cuba.dbmsType>> application property, for example, `/db/update/postgres`. 

The update scripts can be of two types: with the `++*.sql++` or `++*.groovy++` extension. The primary way to update the database is with SQL scripts. Groovy scripts are only executed by <<db_update_server,the server mechanism to launch database scripts>>, Therefore they are mainly used at the production stage, in cases when migration or import of the data that cannot be implemented in pure SQL.

The update scripts should have names, which form the correct sequence of their execution when sorted in the alphabetical order (usually, it is a chronological sequence of their creation). Therefore, when creating such scripts manually, it is recommended to specify the name of the update scripts in the following format: `{yymmdd}-{description}.sql`, where `yy` is a year, `mm` is a month, `dd` is a day, and `description` is a short description of the script. For example, `121003-addCodeToCategoryAttribute.sql`. Studio also adheres to this format when generating scripts automatically.

It is possible to group update scripts into subdirectories, however the path to the script with the subdirectory should not break the chronological sequence. For example, subdirectories can be created by using year, or by year and month.

In a deployed application, the scripts to create and update the database are located in a special <<db_dir,database script directory>>, that is set by the <<cuba.dbDir,cuba.dbDir>> application property.

[[db_scripts_sql]]
===== The Structure of SQL Scripts

Create and update SQL scripts are text files with a set of DDL and DML commands separated by the "^" character. The "^" character is used, so that the ";" separator can be applied as part of complex commands; for example, when creating functions or triggers. The script execution mechanism splits the input file into separate commands using the "^" separator and executes each command in a separate transaction. This means that, if necessary, it is possible to group several single statements (e.g., `insert`), separated by semicolons and ensure that they execute in a single transaction.

An example of the update SQL script:

[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_3.sql[]
----

[[db_scripts_groovy]]
===== The Structure of Groovy scripts

Groovy update scripts have the following structure:

* The __main__ part, which contains the code executed before the start of the <<appContext,application context>>. In this section, you can use any Java, Groovy and the Middleware application block classes. However, it should be kept in mind that no beans, infrastructure interfaces and other application objects have yet been instantiated and it is impossible to use them.
+
The main part is primarily designed to update the database schema, as usually done with ordinary SQL scripts.

* The __PostUpdate__ part – a set of closures, which will be executed after the start of the application context and once the update process is finished. Inside these closures, it is possible to use any Middleware objects.
+
In this part of the script, it is convenient to perform data import as it is possible to use the <<persistence,Persistence>> interface and data model objects.

The execution mechanism passes the following variables to the Groovy scripts:

* `ds` – instance of `javax.sql.DataSource` for the application database;
* `log` – instance of `org.apache.commons.logging.Log` to output messages in the server log;
* `postUpdate` – object that contains the `add(Closure closure)` method to add PostUpdate closures described above.

[WARNING]
====
Groovy scripts are executed only by <<db_update_server,the server mechanism to launch database scripts>>.
====

An example of the Groovy update script:

[source, java]
----
include::{sourcesdir}/dbms/groovyupdate_1.groovy[]
----

[[db_update_gradle]]
==== The Execution of Database Scripts by Gradle Tasks

This mechanism is generally used by application developers for updating their own database instance. The execution of scripts essentially comes down to running a special Gradle task from <<build.gradle,build.gradle>> build script. This can be done from the command line or via the Studio interface.

To run scripts to __create__ the database, the `createDb` task is used. In Studio, it corresponds to the *Run* -> *Create database* command in main menu. When this task is started, the following occurs:

. Platform's <<base_projects,base projects>> scripts and `++db/**/*.sql++` scripts of the *core* module of the current project are built in the `modules/core/build/db` directory. Sets of scripts for base projects are located in subdirectories with numeric prefixes starting from 10. Scripts of the current project are located in a subdirectory with prefix 50. The numeric prefixes are used to provide the alphabetical order of the execution of scripts – first, *cuba* scripts are executed, then base projects scripts, then current project scripts.

. If the database exists, it is completely erased. A new empty database is created.

. All creation scripts from `++modules/core/build/db/init/**/*create-db.sql++` subdirectory are executed sequentially in the alphabetical order, and their names along with the path relative to the db directory are registered in the *SYS_DB_CHANGELOG* table.

. Similarly, in the *SYS_DB_CHANGELOG* table, all currently available `++modules/core/build/db/update/**/*.sql++` update scripts are registered. This is required for applying the future incremental updates to the database.

To run scripts to __update__ the database, the `updateDb` task is used. In Studio, it corresponds to the *Run* -> *Update database* command in main menu. When this task is started, the following occurs:

. The scripts are built in similar way to `createDb` command described above.

. The execution mechanism checks, whether all base projects have required tables in the database. If the database is not initialized for use of some base project, its creation scripts are executed.

. A search is performed in `++modules/core/build/db/update/**++` directories, for update scripts, which are not registered in the *SYS_DB_CHANGELOG* table, i.e., not previously executed.

. All scripts found in the previous step are executed sequentially in the alphabetical order, and their names along with the path relative to the `db` directory are registered in the *SYS_DB_CHANGELOG* table.

[[db_update_server]]
==== The Execution of Database Scripts by the Server

The mechanism to execute database scripts by the server is used for bringing the DB up to date at the start of the application server and is activated during the initialization of the Middleware block. Obviously, the application should have been built and deployed on the server – production or developer's Tomcat instance.

Depending on the conditions described below, this mechanism either executes create or update scripts, i.e., it can initialize the DB from scratch and update it. However, unlike the Gradle `createDb` task described in the previous section, the database must exist to be initialized – the server does not create the DB automatically but only executes scripts on it.

The mechanism to execute scripts by the server works as follows:

* The scripts are extracted from the <<db_dir,database scripts directory>>, defined by the <<cuba.dbDir,cuba.dbDir>> application property, which by default is set to `tomcat/webapps/app-core/WEB-INF/db`.

* If the DB does not have the *SEC_USER* table, the database is considered empty and the full initialization is run using the create scripts. After executing the initialization scripts, their names are stored in the *SYS_DB_CHANGELOG* table. The names of all available update scripts are stored in the same table, __without their execution__.

* If the DB has the *SEC_USER* table but does not have the *SYS_DB_CHANGELOG* table (this is the case when the described mechanism is launched for the first time on the existing production DB),__no scripts are executed__. Instead, the *SYS_DB_CHANGELOG* table is created and the names of all currently available create and update scripts are stored.

* If the DB has both the *SEC_USER* and *SYS_DB_CHANGELOG* tables, the update scripts whose names were not previously stored in the *SYS_DB_CHANGELOG* table are executed and their names are stored in the *SYS_DB_CHANGELOG* table. The sequence of scripts execution is determined by two factors: the priority of the base project (see <<db_dir,database scripts directory>>: `10-cuba`, `20-workflow`, ...) and the name of the script file (taking into account the subdirectories of the `update` directory) in the alphabetical order.
+
Before the execution of update scripts, the check is performed, whether all base projects have required tables in the database. If the database is not initialized for use of some base project, its creation scripts are executed.

The mechanism to execute the scripts on server startup is enabled by the <<cuba.automaticDatabaseUpdate,cuba.automaticDatabaseUpdate>> application property.

In already running application, the script execution mechanism can be launched using the `app-core.cuba:type=PersistenceManager` JMX bean by calling its `updateDatabase()` method with the *`update`* parameter. Obviously it is only possible to update already existing DB as it is impossible to log in to the system to run a method of the JMX bean with an empty DB. Please note, that an unrecoverable error will occur, if part of the data model no longer corresponding to the outdated DB schema is initialized during Middleware startup or user login. That is why the automatic update of the DB on the server startup before initializing the data model is only universal.

The JMX `app-core.cuba:type=PersistenceManager` bean has one more method related to the DB update mechanism: `findUpdateDatabaseScripts()`. It returns a list of new update scripts available in the directory and not registered in the DB (not yet executed).

Recommendations for usage of the server DB update mechanism can be found in <<db_update_in_prod>>.