[[extension]]
=== Functionality Extension

The platform enables extending and overriding the following aspects of its functionality in applications:

* Extending entity attributes set.

* Extending screens functionality. 

* Extending and overriding business logic contained in *Spring* beans.

Below is an example of the first two operations, illustrated by adding the "Address" field to the `User` entity of the platform <<users,security subsystem>>.

[[entity_extension]]
==== Extending an Entity

In the application project, derive an entity class from `com.haulmont.cuba.security.entity.User` and add the required attribute with the corresponding access methods:

[source, java]
----
include::{sourcesdir}/extension/entity_extension_1.java[]
----

The new name of the entity should be specified in the <<entity_annotation,@Entity>> annotation. Since the parent entity does not declare the <<inheritance_annotation,inheritance strategy>>, it is assumed to be `SINGLE_TABLE` by default. It means that the child entity will be stored in the same table as the parent one, and the <<table_annotation,@Table>> annotation is not required. Other parent entity annotations ( <<namePattern_annotation,@NamePattern>>, <<listeners_annotation,@Listeners>>, etc.) are automatically applied to the child entity, but can be overridden in its class.

An important element of the new entity class is the `@Extends` annotation, which takes the parent class as a parameter. It enables creating a registry of child entities and forces the platform mechanisms to use them everywhere instead of the parent ones. The registry is implemented by the `ExtendedEntities` class, which is a *Spring* bean named `cuba_ExtendedEntities`, and is also accessible via the <<metadata,Metadata>> interface.

Add a localized name of the new attribute to the `com.sample.sales.entity` <<message_packs,package>>: 

`messages.properties`

[source, properties]
----
ExtUser.address=Address
----

`messages_ru.properties`

[source, properties]
----
ExtUser.address=Адрес
----

Register the new entity in the <<persistence.xml,persistence.xml>> file of the project:

[source, xml]
----
<class>com.sample.sales.entity.ExtUser</class>
----

Add the update script for the corresponding table to the <<db_scripts,database create and update scripts>>:

[source, sql]
----
include::{sourcesdir}/extension/entity_extension_2.sql[]
----

In order to use new entity attributes in screens, create <<views,views>> for the new entity with the same names as the views of the base entity. A new view should extend the base view and define new attributes, for example:

[source, xml]
----
include::{sourcesdir}/extension/entity_extension_3.xml[]
----

The extended view will include all attributes from its parent view. An extended view is not required if the base one extends `_local` and you add only local attributes, so in the described case this step can be omitted.

[[screen_extension]]
==== Extending Screens

The platform supports creating new <<screen_xml,XML descriptors>> by inheriting them from the existing ones.

XML inheritance is implemented by specifying the parent descriptor path in the `extends` attribute of the root `window` element.

XML screen elements overriding rules:

* If the extending descriptor has a certain element, the corresponding element will be searched for in the parent descriptor using the following algorithm:

** If the overriding element is a `view`, the corresponding element will be searched by the `name`, `class` and `entity` attributes.

** If the overriding element is a `property`, the corresponding element will be searched by the `name` attribute.

** In other cases, if the overrinding element has the `id` attribute, the corresponding element with the same `id` will be searched for. 

** If the search is successful, the found element is *overridden*.

** Otherwise, the platform determines how many elements with the provided path and name are contained in the parent descriptor. If there is only one element, it is *overridden*.

** If search yields no result and there is either zero or more than one element with the given path and name in the parent descriptor, a new element is *added*.

* The text for the overridden or added element is copied from the extending element. 

* All attributes from the extending element are copied to the overridden or added element. If attribute names match, the value is taken from the extending element.

* By default, the new element is added to the end of the list of adjacent elements. In order to add a new element to the beginning or with an arbitrary index, you can do the following: 

** Define an additional namespace in the extending descriptor: `xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"`.

** Add the `ext:index` attribute with a desired index, for example: `ext:index="0"` to the extending element.

In order to debug the descriptor conversion, you can output the resulting XML to the server log by specifying the `TRACE` level for the `com.haulmont.cuba.gui.xml.XmlInheritanceProcessor` logger in the *Logback* configuration file.

Below is an example descriptor of the `ExtUser` entities browser screen:

[source, xml]
----
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
      xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"
      extends="/com/haulmont/cuba/gui/app/security/user/browse/user-browse.xml">
  <layout>
      <groupTable id="usersTable">
          <columns>
              <column id="address" ext:index="2"/>
          </columns>
      </groupTable>
  </layout>
</window>
----

In this example, the descriptor is inherited from the standard `User` entities browser of the platform. The `address` column is added to the table with index `2`, so it is displayed after `login` and `name`.

If you register a new screen in <<screens.xml,screens.xml>> with the same identifiers that were used for the parent screen, the new screen will be invoked everywhere instead of the old one.

[source, xml]
----
<screen id="sec$User.browse"
      template="com/sample/sales/gui/extuser/extuser-browse.xml"/>
<screen id="sec$User.lookup"
      template="com/sample/sales/gui/extuser/extuser-browse.xml"/>
----

Similarly, let us create an edit screen:

[source, xml]
----
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
      xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"
      extends="/com/haulmont/cuba/gui/app/security/user/edit/user-edit.xml">
  <layout>
      <fieldGroup id="fieldGroup">
          <column id="fieldGroupColumn2">
              <field property="address" ext:index="4"/>
          </column>
      </fieldGroup>
  </layout>
</window>
----

Register it in `screens.xml` with the identifier of the parent screen:

[source, xml]
----
<screen id="sec$User.edit"
      template="com/sample/sales/gui/extuser/extuser-edit.xml"/>
----

Once all the abovementioned actions are completed, the application will use `ExtUser` with the corresponding screens instead of the standard `User` entity of the platform.

Screen controller can be extended by creating a new class that is inherited from the base screen controller. Class name is specified in the `class` attribute of the root element of the extending XML descriptor; the usual rules of inheriting XML described above will apply.

[[bean_extension]]
==== Extending Business Logic

The main part of platform business logic is contained in *Spring* beans. This enables to easily extend or override it in the application.

To substitute a bean implementation, you should create your own class that implements the interface or extends the base platform class and register it in <<spring.xml,spring.xml>> of the application. You cannot apply the `@Component` annotation to the extending class; overriding beans is possible only in the XML configuration.

Below is an example of adding a method to the <<persistenceTools,PersistenceTools>> bean.

First, create a class with the necessary method:

[source, java]
----
public class ExtPersistenceTools extends PersistenceTools {

  public Entity reloadInSeparateTransaction(final Entity entity, final String... viewNames) {
      Entity result = persistence.createTransaction().execute(new Transaction.Callable<Entity>() {
          @Override
          public Entity call(EntityManager em) {
              return em.reload(entity, viewNames);
          }
      });
      return result;
  }
}
----

Register the class in `spring.xml` of the project *core* module with the same identifier as the platform bean:

[source, xml]
----
<bean id="cuba_PersistenceTools" class="com.sample.sales.core.ExtPersistenceTools"/>
----

After that, the *Spring* context will always return `ExtPersistenceTools` instead of the base `PersistenceTools` instance. A checking code example:

[source, java]
----
Persistence persistence;
PersistenceTools tools;

persistence = AppBeans.get(Persistence.class);
tools = persistence.getTools();
assertTrue(tools instanceof ExtPersistenceTools);

tools = AppBeans.get(PersistenceTools.class);
assertTrue(tools instanceof ExtPersistenceTools);

tools = AppBeans.get(PersistenceTools.NAME);
assertTrue(tools instanceof ExtPersistenceTools);
----

The same logic can be used for overriding services, for example, from <<app_components_sample,application components>>: to substitute a bean implementation, you should create a class that extends the base service functionality. In the example below the `NewOrderServiceBean` class is created to override the method from the base `OrderServiceBean`:

[source, java]
----
public class NewOrderServiceBean extends OrderServiceBean {
    @Override
    public BigDecimal calculateOrderAmount(Order order) {
        BigDecimal total = super.calculateOrderAmount(order);
        BigDecimal vatPercent = new BigDecimal(0.18);
        return total.multiply(BigDecimal.ONE.add(vatPercent));
    }
}
----

Then, if you register the new class in `spring.xml`, the new implementation will be used instead of the one from `OrderServiceBean`. Note that the base service `id` from the application component is used with the fully qualified name of the new class:

[source, xml]
----
<bean id="workshop_OrderService" class="com.company.retail.service.NewOrderServiceBean"/>
----

[[servlet_registration]]
==== Registration of Servlets and Filters

To use servlets and security filters, defined in the <<app_components,application component>>, in the owning application you need to register them in this component. The servlets are normally registered in the <<web.xml,web.xml>> configuration file, however, this configuration is not propagated in the application where this app component is used.

The `ServletRegistrationManager` bean enables to register servlets and filters dynamically with correct ClassLoader and enables using such static classes as <<appContext,AppContext>>. It also guarantees the correct work for all <<deployment_variants,deployment options>>.

`ServletRegistrationManager` has two methods:

. `createServlet()` - creates a servlet of the given servlet class. It loads the servlet class with the correct `ClassLoader` that is obtained from the application context object. It means that a new servlet will be able to use static classes, for example, `AppContext` or <<messages,Messages>> bean.

. `createFilter()` - create filters in the same way.

In order to use this bean, we recommend creating a managed initializer bean in the application component. This bean should be annotated with the `@Component` annotation and contain event listeners that are subscribed to the application context initialization and destroy: <<ServletContextInitializedEvent,ServletContextInitializedEvent>> and `ServletContextDestroyedEvent`.

An example of such bean:

[source, java]
----
include::{sourcesdir}/extension/WebInitializer.java[]
----

Here, the `WebInitializer` class has only one event listener which is used to register an HTTP servlet from an application component in the owning application.

The `createServlet()` method takes the application context obtained from `ServletContextInitializedEvent` and the HTTP servlet FQN. Then we register the servlet by its name (`my_servlet`) and define HTTP-mapping (`/myservlet/`). Now, if you add this app component to you application, `MyHttpServlet` will be registered right after the initialization of servlet and application contexts.

For more complex example, see the <<servlet_registration_sample,Registering DispatcherServlet from Application Component>> section.

