[[glossary]]
[glossary]
== Glossary

*Application Tiers*::
See <<app_tiers,>>.

[[app_properties_glossentry]]
*Application Properties*::
Application properties are named data values of various types that define different aspects of application configuration or functions. See <<app_properties,>>. 

*Application Blocks*::
See <<app_tiers,>>.

[[artifact]]
*Artifact*::
In the context of this manual, an artifact is a file (usually a JAR or ZIP file) that contains executable code or other code obtained as a result of building a project. An artifact has a name and a version number defined according to specific rules and can be stored in the artifact repository.

[[artifact_repository]]
*Artifact Repository*::
A server that stores  <<artifact,artifacts>>  in a specific structure. The artifacts that the project depends on are loaded from the repository when that project is built. 

[[base_projects]]
*Base Projects*::
The same as <<app_components,application components>>. This term was used in the previous versions of the platform and documentation.

[[container]]
*Container*::
Containers control lifecycle and configuration of application objects. This is a base component of the dependency injection mechanism also known as Inversion of Control.
+
CUBA platform uses the *Spring Framework* container.

*DB*::
A relational database.

*Datasource*::
See <<datasources,>>.

*Dependency Injection*::
Also known as Inversion of Control (IoC) principle. A mechanism for retrieving links to the objects being used, which assumes that an object should only declare which objects it depends on, while the container creates all the necessary objects and injects them in the dependent object.
+
See https://en.wikipedia.org/wiki/Dependency_injection.

[[eager_fetching]]
*Eager Fetching*::
Loading data from subclasses and related objects together with the requested entity.

[[entity]]
*Entity*::
Main element of the data model, see <<data_model,>>.

*Entity Browser*::
A screen containing a table with a list of <<entity,entities>> and buttons to create, edit and delete entities.

*EntityManager*::
A middle tier component for working with persistent  <<data_model,entities>>. 
+
See <<entityManager,>>.

[[interceptor]]
*Interceptor*::
An element of aspect-oriented programming that enables changing or extending object method invocations.
+
See https://en.wikipedia.org/wiki/Interceptor_pattern.

[[javaee_web_profile]]
*Java EE Web Profile*::
Simplified Java Enterprise Edition profile created for web applications that do not use technologies like EJB, JTA and others. 

[[jmx]]
*JMX*::
Java Management Extensions − a technology that provides tools to manage applications, system objects and devices. Defines the standard for <<jmx_beans,JMX-components>>. 
+
Additional details are available at: http://www.oracle.com/technetwork/java/javase/tech/javamanagement-140525.html.
+
See also <<jmx_tools,>>.

[[jpa]]
*JPA*::
Java Persistence API – a standard specification of the object-relational mapping technology (<<orm,ORM>>). CUBA platform uses  *EclipseLink* framework that implements this specification.

[[jpql]]
*JPQL*::
Platform independent object-oriented query language, defined as a part of the JPA specification. 
+
Additional details are available at https://en.wikibooks.org/wiki/Java_Persistence/JPQL.

*Lazy loading*::
See <<lazy_loading,>>.

[[local_attribute]]
*Local attribute*::
An entity attribute that is not a reference or a collection of references to other entities. Values of all local entity attributes are typically stored in one table (with the exception of certain entity inheritance strategies).

*Localized message pack*::
See <<message_packs,>>.

*Managed Beans*::
 Components that contain application business logic.
+
See <<managed_beans,>>.

*Main Message Pack*::
See <<main_message_pack,>>.

*MBeans*::
<<managed_beans,Managed Beans>> that have a JMX-interface. Typically, such beans have an internal state (e.g. cache, configuration data or statistics) that needs to be accessible through JMX. 

[[middleware_glossentry]]
*Middleware*::
Middle tier –  the application <<app_tiers,tier>>  that contains the business logic, works with the database and provides a common interface for higher client tier of an application.

[[optimistic_locking]]
*Optimistic locking*::
Optimistic locking – an approach to managing access to shared data by different users that assumes a very low probability of simultaneous access to the same entity instance. With this approach, locking itself is not applied, instead the system checks if a newer version of the data is available in the database at the moment when the changes are being saved. If so, an exception is thrown and the user must reload the entity instance.
+
See also https://en.wikipedia.org/wiki/Optimistic_concurrency_control.

*ORM*::
Object-Relational Mapping – a technology that links tables in a relational database to objects of a programming language. 
+
See <<orm,>>.

[[persistence_context]]
*Persistent context*::
A set of entity instances loaded from the database or just created. Persistent context serves as data cache within the current transaction. When transaction is committed, all persistent context entity changes are saved to a database.
+
See <<entityManager,>>.

[[screen_controller_glossentry]]
*Screen Controller*::
A Java class containing screen initialization and event handling logic. Works in conjunction with screen's <<screen_xml_glossentry,XML-descriptor>>.
+
See <<screen_controller,>>.

*Services*::
Middleware services provide the business interface for client calls and form the Middleware boundary. Services can encapsulate the business logic or delegate the execution to <<managed_beans,Managed Beans>>.
+
See <<services,>>.

*Soft deletion*::
See <<soft_deletion,>>.

*UI*::
User Interface.

*View*::
See <<views,>>

[[screen_xml_glossentry]]
*XML-descriptor*::
An XML file containing layout of visual components and <<datasources,datasources>> for a screen.
+
See <<screen_xml,>>.
