[[chapter_introduction]]
== Introduction

[[overview]]
=== Overview

*Basic Features*

* The platform is based on *Java* and thus supports almost all operating systems for servers and workstations

* Completely open source

* DBMS specifics independent

* Platform-based applications can be easily deployed in a fail-over configuration

* Efficient tools for <<gui_framework,user interface>> development using plain Java and XML

* Powerful <<chapter_security,access control>> means, which can be configured at runtime from the application UI

* A built-in Office and PDF reports generator (See *Report Generator* manual)

* The facility to create and execute business processes including an integrated visual process designer (See *Workflow* manual)

* Full-text search within entity attributes and file attachments (See *Full Text Search* manual)

* Charts and maps (See *Displaying Charts And Maps* manual)

* Built-in <<rest_api,REST API>> with support for data exchange in XML or JSON for rapid integration with third-party applications

* <<extension,Extensions support>> enabling off-the-shelf software customization for individual customers while retaining seamless product version upgrade

* <<cubaStudio_install,CUBA Studio>> – a tool for rapid development of platform-based applications. Studio provides visual tools for creating, designing and editing the project data model, screens and other elements. Using Studio does not restrict development using standard Java IDE, but rather helps to achieve maximum efficiency when working on a project using both tools:

** Studio is used for quick startup of the project, as well as visual design of the data model and UI screens layout

** Java IDE is used for the implementation of business logic and UI events handling
+
CUBA Studio is integrated with *IntelliJ IDEA* and *Eclipse* enabling quickly switching between Studio and the IDE.

*CUBA Platform Benefits* 

* Solutions built on the platform benefit from the efficient architecture, tried and tested on a number of applications created by *Haulmont* and other developers

* Declarative approach to user interface design provides the following advantages:

* abstracts the developer from the specifics of diverse technologies (HTML / JavaScript, Swing, etc.)

* clearly separates visual layout from initialization and event handling logic, making it easier to read and modify the code

* Application screens are equally functional in both *Web* and *Desktop* clients.

* The platform provides ready functionality on the following levels:

** System level

*** Infrastructure and means of implementing business logic on the <<middleware,middleware tier>>
*** <<gui_vcl,Visual components library>> and client tier infrastructure
*** Tools for managing configuration parameters and <<localization,localized messages>>
*** Support for running <<background_tasks,background tasks>> from the user interface
*** Support for running <<scheduled_tasks,scheduled tasks>> on the Middleware
*** Support for <<dynamic_attributes,dynamic attributes>> allowing adding new attributes to entities at runtime

** Application level

*** Security subsystem
*** Reports generator
*** Workflow subsystem
*** Full-text search
*** Reliable asynchronous <<email_sending,email sending>> facility
*** Full <<entity_log,audit>> of entity changes and tools for entity version <<entity_snapshots,snapshots>> storage

** Deployment level

*** Support for running applications in fail-over configuration
*** Tools for <<rest_api,integration with third-party applications>>
*** <<extension,Extensions>> support, enabling adapting off-the-shelf products to individual customer needs

* Platform functionality significantly reduces project development time and cost, as well as associated technological risks

* CUBA-based web applications development does not require knowledge of the traditional web technologies, such as HTML, CSS, or JavaScript.

=== Technical Requirements

*Minimum requirements*for development using CUBA platform: 

* Memory – 4 GB
* Hard drive space – 5 GB
* Operating system: *Microsoft Windows*,*Linux* or *Mac OS X*

[[releaseNotes]]
=== Release Notes

CUBA platform changelog is available at http://files.cuba-platform.com/cuba/platform/platform-5.5-changelog.html.

