= CUBA Platform. Developer's Manual
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.2
:version-label: Version
:revremark: Copyright (c) 2016 Haulmont (www.haulmont.com)
:gradleVersion: 2.13
:xsd_url: http://schemas.haulmont.com/cuba/{revnumber}
:fts_man_url: http://docs.haulmont.com/cuba/{revnumber}/fts/en/html-single/fts.html

:!sectnums:

[[preface]]
== Preface

This manual provides the reference information for the CUBA platform and covers the most important topics of developing business applications with it.

[[audience]]
=== Intended Audience

This manual is intended for application developers using the CUBA platform. The following technologies knowledge is required to use the platform:

* Java Standard Edition

* Relational databases (SQL, DDL)

[[additional_info]]
=== Further Reading

This manual and other documentation related to the CUBA platform can be found at link:https://www.cuba-platform.com/manual[www.cuba-platform.com/manual].

Video materials and presentations that can help you to understand the platform are available at link:https://www.cuba-platform.com/tutorials[www.cuba-platform.com/tutorials].

You can also check out online demo applications at link:https://www.cuba-platform.com/online-demo[www.cuba-platform.com/online-demo].

Knowledge of the following technologies and frameworks will be helpful to get a deeper understanding of the platform:

* link:https://docs.gradle.org/{gradleVersion}/userguide/userguide.html[Gradle] build system

* link:$$http://projects.spring.io/spring-framework$$[Spring Framework]

* link:$$http://en.wikipedia.org/wiki/Java_Persistence_API$$[Java Persistence API]

* link:$$https://www.eclipse.org/eclipselink/documentation$$[EclipseLink] framework

* link:$$https://vaadin.com/book$$[Vaadin] web applications framework

* HTML / CSS / JavaScript

* Java Servlets

* Java Swing

[[feedback]]
=== Feedback

If you have any suggestions for improvement of this Manual, please contact support at link:$$https://www.cuba-platform.com/support/topics$$[www.cuba-platform.com/support/topics].

If you find a mistake in the documentation, please specify the number of the chapter and attach a small portion of the surrounding text to facilitate the search.

:sectnums:

include::introduction.adoc[]

include::setup.adoc[]

include::quick_start.adoc[]

[[framework]]
== The Framework

This chapter contains detailed description of the platform architecture, components and mechanisms.

include::architecture.adoc[]

include::common.adoc[]

include::dbms.adoc[]

include::middleware.adoc[]

include::gui.adoc[]

include::portal.adoc[]

include::features.adoc[]

include::extension.adoc[]

include::development.adoc[]

include::deployment.adoc[]

include::database.adoc[]

include::security.adoc[]

include::config_files.adoc[]

include::app_properties.adoc[]

include::system_properties.adoc[]

include::glossary.adoc[]