= CUBA Platform. Developer's Manual
:toc: left
:toc-title: Table of contents
:toclevels: 6
:sectnumlevels: 6
:stylesheet: cuba.css
:linkcss:
:source-highlighter: coderay
:imagesdir: ./img
:stylesdir: ./styles
:sourcesdir: ../../source
:doctype: book
:sectlinks:
:sectanchors:
:lang: en
:revnumber: 6.0
:version-label: Version
:revremark: Copyright (c) 2015 Haulmont (www.haulmont.com)
:gradleVersion: 2.6
:xsd_url: http://schemas.haulmont.com/cuba/6.0
:fts_man_url: http://docs.haulmont.com/cuba/6.0/fts/en/html-single/fts.html

:!sectnums:

[[preface]]
[preface]
== Preface

This Manual provides the information required for the development of CUBA-based _business applications_. Business applications are understood here as a wide range of information systems intended for the support of enterprise operations, management and decision-making.

=== Intended Audience

This Manual is intended for business applications developers using the *CUBA* platform. The following technologies knowledge is required to use the platform:

* Java Standard Edition

* Relational databases (SQL, DDL)

=== Further Reading

This Manual and other documentation related to the CUBA platform can be found at link:$$https://www.cuba-platform.com/manual$$[www.cuba-platform.com/manual].

Knowledge of the following technologies and frameworks will be helpful to get a deeper understanding of the core principles of the platform:

* link:https://docs.gradle.org/{gradleVersion}/userguide/userguide.html[Gradle] build system

* link:$$http://projects.spring.io/spring-framework$$[Spring Framework]

* link:$$http://en.wikipedia.org/wiki/Java_Persistence_API$$[Java Persistence API]

* link:$$https://www.eclipse.org/eclipselink/documentation$$[EclipseLink] framework

* link:$$https://vaadin.com/book$$[Vaadin] web applications framework

* HTML / CSS / JavaScript

* Java Servlets

* Java Swing

=== Feedback

If you have any suggestions for improvement of this Manual, please contact support at link:$$https://www.cuba-platform.com/support/topics$$[www.cuba-platform.com/support/topics].

If you find a mistake in the documentation, please specify the number of the chapter and attach a small portion of the surrounding text to facilitate the search.

:sectnums:

include::introduction.adoc[]

include::setup.adoc[]

include::quick_start.adoc[]

[[chapter_framework]]
== The Framework

This chapter contains detailed description of the platform architecture, components and mechanisms.

include::architecture.adoc[]

include::common.adoc[]

include::dbms.adoc[]

include::middleware.adoc[]

include::gui.adoc[]

include::portal.adoc[]

include::features.adoc[]

include::extension.adoc[]

include::development.adoc[]

include::deployment.adoc[]

include::database.adoc[]

include::security.adoc[]

include::config_files.adoc[]

include::app_properties.adoc[]

include::system_properties.adoc[]

include::glossary.adoc[]