[[polymer_ui]]
=== Polymer User Interface

The Polymer UI client <<app_tiers,block>> provides an ability to quickly create front-end portals with mobile-first responsive web UI. It is based on https://www.polymer-project.org[Google Polymer] framework and enables tight integration with mobile browsers for adding web applications to the device home screen and for offline work.

The CUBA platform Polymer UI has the following features:

* The Polymer build system is fully integrated into the project build system based on Gradle, so all building tools are downloaded and installed automatically. At the same time, once the Polymer module is created in the project, it can be developed further by front-end developers separately using the standard Polymer toolchain.

* The platform provides a set of web components for working with the middleware through the standard CUBA <<rest_api_v2,REST API>>. The components are described <<cuba_web_components,below>>.

* CUBA Studio enables easy creation of the Polymer client module and scaffolding of the application web components around the data model and middleware services of the project. Studio contains an extendable set of templates for creation of application level components.

Our current approach is to stick to Polymer’s https://www.polymer-project.org/2.0/start/install-2-0[techniques and tools] which are used for creating https://developers.google.com/web/progressive-web-apps/[Progressive Web Apps]. The aim is to follow Polymer's guidelines and best practices to provide similar learning curve and development experience. Polymer applications have component-based architecture and consist of https://www.webcomponents.org/[Web Components].

By default, the UI generated by Studio is based on https://www.webcomponents.org/collection/PolymerElements/paper-elements[paper-elements] - a set of elements by Polymer team which implement Google's
http://www.google.com/design/spec/material-design/introduction.html[material design] guidelines. It is possible to use other components by specifying custom templates in Studio.

In order to start developing effectively, you need to be familiar with basic Polymer concepts. Here is a very quick intro to the Polymer:
https://github.com/Polymer/polymer#polymer-in-1-minute. However, it’s better to learn it more in depth: https://www.polymer-project.org/2.0/start/. Since the Polymer is built around the standards by learning it in most cases you learn the web platform itself.

[[polymer_requirements]]
==== Requirements
http://git-scm.com/downloads[Git] should be installed and available from the command line.
It’s required for https://bower.io/[bower] - the package manager for front-end applications.

[[polymer_supported_browsers]]
==== Supported Browsers
See the list of supported browsers on the Polymer’s https://www.polymer-project.org/2.0/docs/browsers[website]

[WARNING]
====
Please do not to use Polymer client if you are targeting legacy browsers.
====

[[polymer_in_studio]]
==== Polymer UI in Studio

In order to add the Polymer client module to your project, open it in CUBA Studio and click *Create module > Create polymer client module* on the *Project Properties* navigator tab.
Studio will create the *polymer-client* module in the project and configure it in `build.gradle`. The module will contain an application stub that is able to connect to the REST API and login/logout user to the middleware.

After creating the module, start the application server and open `++http://localhost:8080/app-front++` in a web browser. You will be presented with a login form. After logging in, the main window with a vertical menu and responsive layout will be shown.

In order to create a UI screen working with an entity, select an entity in Studio navigator and click *New > Polymer UI component*. Select a template (e.g. *Entity cards list with editor*), fill in required properties and click *Create*. The web component will be created and added to the menu. Studio provides hot-deploy of Polymer components, so you just need to refresh the page in the browser and you will see the newly created screen in the menu.

[[polymer_build_and_structure]]
==== Build System and Project Structure
The following tools are used in Polymer client build chain:

* https://nodejs.org/en/[Node.js]
* https://bower.io/[bower]
* https://github.com/Polymer/polymer-cli[polymer-cli]

By default Gradle handles installation and invocation of these tools. It's possible to use them directly, see <<polymer_tools,Using Native Polymer Tools>>.

Polymer 2.x and its native elements are written using ES6, thus it requires additional build step (ES6 → ES5 https://www.polymer-project.org/2.0/docs/es6[compilation]) in order to support old browsers.

[WARNING]
====
The default preset used in Polymer client is `es6-unbundled`. It means that if you are targeting old browsers and production deployment you should change it to `es5-bundled`.
====

In order to change build preset open `polymer.json` and change `builds` property accordingly e.g.:

[source,json]
----
  "builds": [
    {
      "preset": "es5-bundled",
      "basePath": "/app-front/",
      "addServiceWorker": false
    }
  ]
----

You can specify several presets or customize build process in `polymer.json`. More info about presets and options is available on https://www.polymer-project.org/2.0/toolbox/build-for-production[Polymer website].

In order the results of specific preset build being deployed to Tomcat you need to change `deploy` task in `build.gradle`:

[source,groovy]
----
    task deploy(type: Copy, dependsOn: [assemble, deployUnbundled]) {
        from file('build/es5-unbundled')
        into "$cuba.tomcat.dir/webapps/$frontAppDir"
    }
----

Notice `es6-bundled` → `es5-unbundled` change in `polymer.json` and `build.gradle`.

[[polymer_directory_structure]]
===== Directory Structure

----
polymer-client/
|-- src/
|   |-- app-shell.html
|   |-- shared-styles.html
|-- images
|   |-- app-icon/
|   |-- favicon.ico
|-- .gitignore
|-- bower.json
|-- index.html
|-- manifest.json
|-- package.json
|-- polymer.json
|-- service-worker.js
|-- sw-precache-config.js
----

src:: Folder where components are placed.

package.json:: Lists dependencies on Node.js modules which will be used in a build purposes.

bower.json:: Lists dependencies on web libraries (primarily web components) which will be used at runtime.

polymer.json:: Polymer https://www.polymer-project.org/2.0/docs/tools/polymer-cli#build[build configuration].

index.html:: An application entry point. Contains logic on loading polyfills and <appname>-shell.html import.

manifest.json:: Web app manifest. Contains information which used when the application is being added to a device’s home screen.
More info: https://developer.mozilla.org/en-US/docs/Web/Manifest

service-worker.js:: Service worker stub.

sw-precache-config.js:: Config used by https://github.com/GoogleChrome/sw-precache[sw-precache] library in order to generate service worker at build time (disabled by default). See <<polymer_offline>>.

[[polymer_hot_deploy]]
===== Hot Deploy

When you run and deploy your application using CUBA Studio or Gradle the build system will bundle your components according to the configuration in `polymer.json` file. By default, it will bundle the whole application into a single `app-shell.html` file. When you change some of your app components Studio will hot deploy it to the tomcat.  Also, it will replace bundled `app-shell.html` with an unbundled version in order changes to be picked. Keep it in mind if you deploy your application on production directly from `tomcat/webapps`.

[WARNING]
====
If you use `es5-bundled` build preset, hot deploy will not work as expected since Studio does not perform any JavaScript transpilation on the fly.
====

[WARNING]
====
If you use TypeScript based client you have to run `npm run watch` command manually to hot-deploy changes in components classes.
====

[[polymer_tools]]
===== Using Native Polymer Tools

You can use native Polymer framework toolchain when developing Polymer UI components. It can be convenient if a separate team of front-end developers works on the project. In this case, `Node.js` should be installed on the system.

Install `bower` and `polymer-cli` globally:

[source]
----
npm install bower polymer-cli -g
----

Then you can build and run the web application without Gradle:

[source]
----
cd modules/polymer-client
npm install
bower install
polymer serve
----

You need to specify the absolute path to REST API in `modules/polymer-client/index.html` if you want to serve the app by polymer server (instead of Tomcat), e.g.:

[source,html]
----
<myapp-shell api-url="http://localhost:8080/app/rest/"></myapp-shell>
----

After that, the web application will be available at `++http://localhost:8081++` (see the particular port in command line output) and it will work with the REST API running at `++http://localhost:8080/app/rest/++`.

[[cuba_web_components]]
==== CUBA Web Components

The detailed API reference of CUBA elements can be found https://cuba-elements.github.io/cuba-elements/[here].

[[polymer_inintialization]]
===== Initialization

In order to use any `cuba-` element you need to initialize common library and connection to the REST API using `cuba-app` element :

[source,html]
----
<cuba-app api-url="/app/rest/"></cuba-app>
----

It should be placed once in your app as early as possible. Do not change properties dynamically or detach/attach the element after initialization.

[[polymer_working_with_data]]
===== Working With Data

In order to load data just place some of https://cuba-elements.github.io/cuba-elements/components/cuba-data/[cuba-data]
elements in HTML and specify required attributes.

*Entities Loading*

Use https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entities[cuba-entities] to load entities. Once `entity-name` and `view` attributes are specified the element loads list of entities and exposes it to the Polymer data binding via `data` property:

[source,html]
----
<cuba-entities entity-name="sec$User" view="_local" data="{{users}}"></cuba-entities>
----

Then you can display the data as simple as:

[source,html]
----
<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----


*Entities Querying*

Define a query as described <<rest_api_v2_queries_config,here>>.

Use https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-query[cuba-query] element to retrieve query results. You can optionally pass parameters using `params` property:

[source,html]
----
<cuba-query id="query"
            auto="[[auto]]"
            entity-name="sec$User"
            query-name="usersByName"
            data="{{users}}">
</cuba-query>

<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----

*Service Invocation*

Expose a service and it's method as described <<rest_api_v2_services_config,here>>. Use https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-service[cuba-service] element
to invoke the method:

[source,html]
----
<cuba-service service-name="cuba_ServerInfoService"
              method="getReleaseNumber"
              data="{{releaseNumber}}"
              handle-as="text"></cuba-service>

Release number: [[releaseNumber]]
----

*Entity Creation*

`cuba-entity-form` and `cuba-service-form` elements facilitate sending data to the backend.

In the example below, we bind `user` object which should be persisted to the `entity` property.

[source,html]
----
<cuba-entity-form id="entityForm"
                  entity-name="sec$User"
                  entity="[[user]]"
                  on-cuba-form-response="_handleFormResponse"
                  on-cuba-form-error="_handleFormError">

  <label>Login: <input type="text" name="login" value="{{user.login::input}}"></label>
  <label>Name: <input type="text" name="login" value="{{user.name::input}}"></label>

  <button on-tap="_submit">Submit</button>

</cuba-entity-form>

<paper-toast id="successToast">Entity created</paper-toast>
<paper-toast id="errorToast">Entity creation error</paper-toast>
----

[source,javascript]
----
_submit: function() {
  this.$.entityForm.submit();
},
_handleFormResponse: function() {
  this.user = getUserStub();
  this.$.successToast.open();
},
_handleFormError: function() {
  this.$.errorToast.open();
}
----

[TIP]
====
You should enable <<rest_api_v2_anonymous, anonymous access>> in the REST API if you want to use the examples above without forcing users to log in.
====

[[polymer_styling]]
==== Styling

See the Polymer's https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom[styling guide]. The most noticeable difference between traditional approach is how global styles are specified.
Since Polymer elements use Shadow DOM global styles do not leak inside the components. You need to use https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-modules[style-modules] instead. There is a `shares-styles.html` file in Polymer client which is automatically being imported to any new component created in Studio.

[[polymer_offline]]
==== Offline Capabilities

[WARNING]
====
Experimental!

The technologies listed below are not supported by all browsers yet (e.g. service workers are https://jakearchibald.github.io/isserviceworkerready[not yet implemented] in Safari).
====

Currently, together with the Polymer we offer to use https://developers.google.com/web/progressive-web-apps/[Progressive Web Applications] techniques such as https://developer.mozilla.org/en-US/docs/Web/Manifest[web app manifest] https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/[2] to have *native-like* presence on the user's home screen. See the `manifest.json` file in Polymer client module.

There are two main approaches:

* Service Workers which primarily used to cache the app itself.
Take a look at `sw-precache-config.js` file generated with Polymer client.
In order to enable service worker generation set `"addServiceWorker": true` in `polymer.json`.

More info on how to setup and use service workers can be found
https://www.polymer-project.org/2.0/toolbox/service-worker[here].

* https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage[Local storage] and https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API[Indexed DB] which used to store data locally.
This functionality exposed in the corresponding Polymer elements:
https://www.webcomponents.org/element/PolymerElements/app-storage?active=app-localstorage-document[app-localstorage-document]
https://www.webcomponents.org/element/PolymerElements/app-storage?active=app-indexeddb-mirror[app-indexeddb-mirror].

[[polymer2_typescript]]
==== TypeScript Support

Since Release 6.9 you can scaffold TypeScript based Polymer client in Studio. When creating Polymer client module you will be able to select `polymer2-typesript` preset of the client. Main differences with basic JavaScript version:

Component classes are placed in separate `*.ts` files::

[source,typescript]
.myapp-component.ts
----
namespace myapp {

  const {customElement} = Polymer.decorators;

  @customElement('myapp-component')
  class MyappComponent extends Polymer.Element {
  }
}
----

[source,html]
.myapp-component.html
----
<link rel="import" href="../bower_components/polymer/polymer.html">

<link rel="import" href="./shared-styles.html">

<dom-module id="myapp-component">
  <template>
     <!-- some html markup -->
  </template>
  <script src="myapp-component.js"></script>
</dom-module>
----

There is an additional phase of build process - TypeScript compilation::

See `scripts` section of `package.json`

[source,json]
----
{
  "scripts": {
    "build": "npm run compile && polymer build",
    "compile": "tsc",
    "watch": "tsc -w"
  }
}
----

Now before `polymer build` there is `npm run compile` command which effectively runs TypeScript compilation (`tsc`).

[WARNING]
====
If you change the source code of component classes and expect your changes to be picked by Studio's hot deploy you should manually run `npm run watch` command in `modules/polymer-client` directory.
====


[[polymer2_typescript_components]]
===== Create Polymer Components with TypeScript

TypeScript decorators by Polymer team provide more convenient and less verbose way to create component classes. Let's look at the following example:

[source,typescript]
----
/// <reference path="../bower_components/cuba-app/cuba-app.d.ts" />
/// <reference path="../bower_components/app-layout/app-drawer/app-drawer.d.ts" />
/// <reference path="../bower_components/app-layout/app-drawer-layout/app-drawer-layout.d.ts" />

namespace myapp {

  // Create shortcuts to decorators
  const {customElement, property, observe, query} = Polymer.decorators;

  @customElement('myapp-component')
  class MyappComponent extends (Polymer.mixinBehaviors([CubaAppAwareBehavior, CubaLocalizeBehavior], Polymer.Element) as
    new () => Polymer.Element & CubaAppAwareBehavior & CubaLocalizeBehavior) {

    @property({type: Boolean})
    enabled: boolean;

    @property({type: String})
    caption: string;

    @query('#drawer')
    drawer: AppDrawerElement;

    @observe('app')
    _init(app: cuba.CubaApp) {
      ...
    }

    @computed('enabled', 'caption')
    get enabledCaption() {
      ...
    }
  }
}
----

* `/// <reference path="..."/>` - allows you to import TypeScript declarations of other elements or libraries.

* `@customElements('element-name')` decorator eliminates necessity to define `static get is()` method and manual invocation of `customElements.define()`.

* `@property()` decorator allows you to specify component's properties.

* `@query('.css-selector')` decorator allows you to select DOM elements of your component.

* `@observe('propertyName')` decorator allows you to define property observers.

* `@computed()` decorator allows you to define computed methods.

See https://github.com/Polymer/polymer-decorators[polymer-decorators] github repository for more examples.

[[polymer_troubleshooting]]
==== Troubleshooting
Proxy::
If you work behind a proxy you may need to configure bower and npm accordingly. In order to allow bower and npm to work behind a proxy create the following files in the `modules/polymer-client/`
directory:

 .bowerrc
[source,json]
----
{
    "proxy":"http://<user>:<password>@<host>:<port>",
    "https-proxy":"http://<user>:<password>@<host>:<port>"
}
----

 .npmrc
[source]
----
proxy=http://<user>:<password>@<host>:<port>
https-proxy=http://<user>:<password>@<host>:<port>
----

NPM install failed::
There is a https://github.com/npm/npm/issues/19934[known issue] with `npm install` command on Windows.

You may experience the following error in the build process:
----
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted,
----

As a workaround, you can try to disable Windows Defender/any other antivirus software, make sure you do not open project in any IDE and run build again.

Track the following https://youtrack.cuba-platform.com/issue/STUDIO-4504[issue] for upcoming possible solution.