[[polymer_ui]]
=== Polymer User Interface

The Polymer UI client <<app_tiers,block>> provides an ability to quickly create front-end portals with mobile-first
responsive web UI. It is based on https://www.polymer-project.org[Google Polymer] framework and enables tight
integration with mobile browsers for adding web applications to the device home screen and for offline work.

The CUBA platform Polymer UI has the following features:

* The Polymer build system is fully integrated into the project build system based on Gradle, so all building tools
are downloaded and installed automatically. At the same time, once the Polymer module is created in the project,
it can be developed further by front-end developers separately using the standard Polymer toolchain.

* The platform provides a set of web components for working with the middleware through the standard CUBA
<<rest_api_v2,REST API>>. The components are described <<cuba_web_components,below>>.

* CUBA Studio enables easy creation of the Polymer client module and scaffolding of the application web components
around the data model and middleware services of the project. Studio contains an extendable set of templates for
creation of application level components.

Our current approach is to stick to Polymer’s https://www.polymer-project.org/1.0/start/toolbox/set-up[techniques and tools]
which are used for creating https://developers.google.com/web/progressive-web-apps/[Progressive Web Apps].
The aim is to follow Polymer's guidelines and best practices to provide similar learning curve and development experience.
Polymer applications have component-based architecture and consist of https://www.webcomponents.org/[Web Components].

By default the UI generated by Studio is based on https://www.webcomponents.org/collection/PolymerElements/paper-elements[paper-elements]
- a set of elements by Polymer team which implement Google's
http://www.google.com/design/spec/material-design/introduction.html[material design] guidelines. It is possible to use
another components by specifying custom templates in Studio.

In order to start developing effectively you need to be familiar with basic Polymer concepts.
Here is a very quick intro to the Polymer:
https://github.com/Polymer/polymer/tree/1.x#polymer-in-1-minute. However it’s better to learn it more in depth:
https://www.polymer-project.org/1.0/start. Since the Polymer is built around the standards by learning it in most cases you
learn the web platform itself.


[[polymer_requirements]]
==== Requirements
http://git-scm.com/downloads[Git] should be installed and available from the command line.
It’s required for https://bower.io/[bower] - package manager for front-end applications.


[[polymer_supported_browsers]]
==== Supported Browsers
See the list of supported browsers on the Polymer’s https://www.polymer-project.org/1.0/docs/browsers[website]

[WARNING]
====
Please do not to use Polymer client if you are targeting legacy browsers.
====

[[polymer_in_studio]]
==== Polymer UI in Studio

In order to add the Polymer client module to your project, open it in CUBA Studio and click *Create module >
Create polymer client module* on the *Project Properties* navigator tab.
Studio will create the *polymer-client* module in the project and configure it in `build.gradle`.
The module will contain an application stub that is able to connect to the REST API and login/logout user to the middleware.

After creating the module, start the application server and open `++http://localhost:8080/app-front++` in a web browser.
You will be presented with a login form. After logging in, the main window with a vertical menu and responsive layout will be shown.

In order to create a UI screen working with an entity, select an entity in Studio navigator and click *New >
Polymer UI component*. Select a template (e.g. *Entity cards list with editor*), fill in required properties and click *Create*.
The web component will be created and added to the menu. Studio provides hot-deploy of Polymer components,
so you just need to refresh the page in the browser and you will see the newly created screen in the menu.

[[polymer_build_and_structure]]
==== Build System and Project Structure
The following tools are used in Polymer client build chain:

* https://nodejs.org/en/[Node.js]
* https://bower.io/[bower]
* http://gulpjs.com/[gulp]
* https://github.com/Polymer/polymer-build[polymer-build]

By default Gradle handles installation and invocation of these tools. It's possible to use them directly,
see <<polymer_tools,Using Native Polymer Tools>>.


[[polymer_directory_structure]]
===== Directory Structure

----
polymer-client/
|-- src/
|   |-- app-shell.html
|   |-- shared-styles.html
|-- images
|   |-- app-icon/
|   |-- favicon.ico
|-- .gitignore
|-- bower.json
|-- gulpfile.js
|-- index.html
|-- manifest.json
|-- package.json
|-- polymer.json
|-- service-worker.js
|-- sw-precache-config.js
----

src:: Folder where components are placed.

package.json:: Lists dependencies on Node.js modules which will be used in a build purposes.

bower.json:: Lists dependencies on web libraries (primarily web components) which will be used in runtime.

polymer.json:: Polymer https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build[build configuration].

gulpfile.js:: http://gulpjs.com/[Gulp] build file. It’s a right place to add some processing like
 minification/preprocessors etc. More info: https://github.com/Polymer/polymer-build#polymerproject.

index.html:: An application entry point. Contains logic on loading polyfills and <appname>-shell.html import.

manifest.json:: Web app manifest. Contains information which used when application is being added to a device’s homescreen.
More info: https://developer.mozilla.org/en-US/docs/Web/Manifest

service-worker.js:: Service worker stub.

sw-precache-config.js:: Config used by https://github.com/GoogleChrome/sw-precache[sw-precache] library
in order to generate service worker at build time (disabled by default). See <<polymer_offline>>.

[[polymer_hot_deploy]]
===== Hot Deploy
When you run and deploy your application using CUBA Studio or gradle the build system will bundle your components
according to the configuration in `polymer.json` file. By default it will bundle the whole application into a single
`app-shell.html` file. When you change some of your app components Studio will hot deploy it to the tomcat.
 Also it will replace bundled `app-shell.html` with unbundled version in order changes to be picked.
Keep it in mind if you deploy your application on production directly from `tomcat/webapps`.

[[polymer_tools]]
===== Using Native Polymer Tools

You can use native Polymer framework toolchain when developing Polymer UI components.
It can be convenient if a separate team of front-end developers works on the project.
In this case `Node.js` should be installed on the system.

Install `bower` and `gulp` globally:

[source]
----
npm install bower gulp-cli -g
----

Then you can build and run the web application without Gradle:

[source]
----
cd modules/polymer-client
npm install
bower install
gulp serve
----

You need to apply the following changes in the source code if you want to serve app by polymer server
(instead of Tomcat):

* Open `modules/polymer-client/index.html` and edit `base` element as follows:
+
[source,html]
----
<base href="/">
----

* Open `modules/polymer-client/src/<appname>-shell.html` and edit `cuba-app` element as follows:
+
[source,html]
----
<cuba-app api-url="http://localhost:8080/app/rest/" on-cuba-token-expired="_handleTokenExpired"></cuba-app>
----

After that, the web application will be available at `++http://localhost:8081++` and it will work with the REST API
 running at `++http://localhost:8080/app/rest/++`.


[[cuba_web_components]]
==== CUBA Web Components

The detailed API reference of CUBA elements can be found https://cuba-elements.github.io/cuba-elements/[here].

[[polymer_inintialization]]
===== Initialization
In order to use any `cuba-` element you need to initialize common library and connection to the REST API using
`cuba-app` element :

[source,html]
----
<cuba-app api-url="/app/rest/"></cuba-app>
----

It should be placed once in your app as early as possible.
Do not change properties dynamically or detach/attach the element after initialization.


[[polymer_working_with_data]]
===== Working With Data

In order to load data just place some of https://cuba-elements.github.io/cuba-elements/components/cuba-data/[cuba-data]
elements in HTML and specify required attributes.

*Entities Loading*

Use https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-entities[cuba-entities] to load entities.
Once `entity-name` and `view` attributes are specified the element loads list of entities and exposes it to the Polymer
data binding via `data` property:

[source,html]
----
<cuba-entities entity-name="sec$User" view="_local" data="{{users}}"></cuba-entities>
----

Then you can display the data as simple as:

[source,html]
----
<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----


*Entities Querying*

Define a query as described <<rest_api_v2_queries_config,here>>.

Use https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-query[cuba-query] element to retrieve
query results. You can optionally pass parameters using `params` property:

[source,html]
----
<cuba-query id="query"
            auto="[[auto]]"
            entity-name="sec$User"
            query-name="usersByName"
            data="{{users}}">
</cuba-query>

<template is="dom-repeat" items="[[users]]" as="user">
  <div>[[user.login]]</div>
</template>
----

*Service Invocation*

Expose a service and it's method as described <<rest_api_v2_services_config,here>>.
Use https://cuba-elements.github.io/cuba-elements/components/cuba-data/#cuba-service[cuba-service] element
to invoke the method:

[source,html]
----
<cuba-service service-name="cuba_ServerInfoService"
              method="getReleaseNumber"
              data="{{releaseNumber}}"
              handle-as="text"></cuba-service>

Release number: [[releaseNumber]]
----

*Entity Creation*

`cuba-entity-form` and `cuba-service-form` elements facilitate sending data to the backend.

In the example below we bind `user` object which should be persisted to the `entity` property.


[source,html]
----
<cuba-entity-form id="entityForm"
                  entity-name="sec$User"
                  entity="[[user]]"
                  on-cuba-form-response="_handleFormResponse"
                  on-cuba-form-error="_handleFormError">

  <label>Login: <input type="text" name="login" value="{{user.login::input}}"></label>
  <label>Name: <input type="text" name="login" value="{{user.name::input}}"></label>

  <button on-tap="_submit">Submit</button>

</cuba-entity-form>

<paper-toast id="successToast">Entity created</paper-toast>
<paper-toast id="errorToast">Entity creation error</paper-toast>
----

[source,javascript]
----
_submit: function() {
  this.$.entityForm.submit();
},
_handleFormResponse: function() {
  this.user = getUserStub();
  this.$.successToast.open();
},
_handleFormError: function() {
  this.$.errorToast.open();
}
----


[TIP]
====
You should enable <<rest_api_v2_anonymous, anonymous access>> in the REST API if you want to use the examples above without
forcing users to log in.
====

[[polymer_styling]]
==== Styling
See the Polymer's https://www.polymer-project.org/1.0/docs/devguide/styling[styling guide].
The most noticeable difference between traditional approach is how global styles are specified.
Since Polymer elements use Shadow DOM global styles do not leak inside the components.
You need to use https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules[style-modules] instead.
There is a `shares-styles.html` file in Polymer client which is automatically being imported to any new component created in Studio.

[[polymer_offline]]
==== Offline Capabilities

[WARNING]
====
Experimental!

The technologies listed below are not supported by all browsers yet (e.g. service workers are
[not implemented](https://jakearchibald.github.io/isserviceworkerready) in Safari).
====

Currently, together with the Polymer we offer to use
https://developers.google.com/web/progressive-web-apps/[Progressive Web Applications] techniques such
as https://developer.mozilla.org/en-US/docs/Web/Manifest[web app manifest]
https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/[2] to have *native-like* presence
on the user's homescreen. See the `manifest.json` file in Polymer client module.

There are two main approaches:

* Service Workers which primarily used to cache the app itself.
Take a look at `sw-precache-config.js` file generated with Polymer client.
In order to enable service worker generation change `assemble` task of  Polymer module in the following way:
```
    ...
    task assemble(type: NodeTask, dependsOn: installBowerPackages) {
        script = file("node_modules/gulp/bin/gulp.js")
        args = ['build-sw']
    ...
```
More info on how to setup and use service workers can be found
https://www.polymer-project.org/1.0/toolbox/service-worker[here].

* https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage[Local storage] and
https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API[Indexed DB] which used to store data locally.
This functionality exposed in the corresponding Polymer elements:
https://elements.polymer-project.org/elements/app-storage?active=app-localstorage-document[app-localstorage-document]
https://elements.polymer-project.org/elements/app-storage?active=app-indexeddb-mirror[app-indexeddb-mirror].


[[polymer_troubleshooting]]
==== Troubleshooting
Proxy::
If you work behind a proxy you may need to configure bower and npm accordingly.
In order to allow bower and npm to work behind a proxy create the following files in the `modules/polymer-client/`
directory:

 .bowerrc
[source,json]
----
{
    "proxy":"http://<user>:<password>@<host>:<port>",
    "https-proxy":"http://<user>:<password>@<host>:<port>"
}
----

 .npmrc
[source]
----
proxy=http://<user>:<password>@<host>:<port>
https-proxy=http://<user>:<password>@<host>:<port>
----