[[rest_api_v2]]
=== REST API

The universal REST API provides the following functionality:

* CRUD operations on entities.
* Execution of predefined JPQL queries.
* Execution of service methods.
* Getting metadata (entities, views, enumerations, datatypes).
* Getting current user permissions (access to entities, attributes, specific permissions).
* Getting current user information (name, language, time zone, etc.).
* Uploading and downloading files.

REST API uses the OAuth2 protocol for authentication and supports anonymous access.

[TIP]
====
The detailed documentation for the API is written according to http://swagger.io/specification[Swagger specification] and is available at the following URL: {rest_swagger_url}.

Any running CUBA application also exports the swagger documentation at `\http://HOST:PORT/APP_NAME/rest/v2/docs/swagger.yaml` and  `\http://HOST:PORT/APP_NAME/rest/v2/docs/swagger.json`.
====

The <<rest_api_v2_usage_example>> cookbook section contains a lot of examples demonstrating REST API features in action.

Below we provide a formal description of some features and configuration options.

[[rest_api_v2_queries_config]]
==== Predefined JPQL Queries Configuration

In the CUBA application, predefined JPQL queries must be specified in files registered in the <<cuba.rest.queriesConfig, cuba.rest.queriesConfig>> application property of the *web* or *portal* module (e.g in the `web-app.properties file`):

[source,properties]
----
cuba.rest.queriesConfig = +com/company/myapp/rest-queries.xml
----

The `rest-queries.xml` file must be placed in the root package of the *web* or *portal* module (e.g. `com.company.myapp`). Its content is defined by the http://schemas.haulmont.com/cuba/{revnumber}/rest-queries.xsd[rest-queries.xsd] schema, for example:

[source, xml]
----
include::{sourcesdir}/rest/rest-queries-config.xml[]
----

An example of how to configure and execute a query can be found in the <<rest_api_v2_ex_query_get>> and <<rest_api_v2_ex_query_post>> chapter.

The platform also provides the predefined `all` query for getting all instances of a specified entity type. It can be used with `/count` to receive the total number of entity instances, for example:

  http://localhost:8080/app/rest/v2/queries/sales$Order/all/count

[[rest_api_v2_services_config]]
==== Services Configuration

The list of service methods that are available via the REST API must be configured in the CUBA application in files registered in the <<cuba.rest.servicesConfig, cuba.rest.servicesConfig>> application property of the *web* or *portal* module (e.g in the `web-app.properties file`):

[source,properties]
----
cuba.rest.servicesConfig = +com/company/myapp/rest-services.xml
----

The content of the `rest-services.xml` must be placed in the root package of the *web* or *portal* module (e.g. `com.company.myapp`). Its content is defined by the http://schemas.haulmont.com/cuba/{revnumber}/rest-services-v2.xsd[rest-services-v2.xsd] schema, for example:

[source, xml]
----
include::{sourcesdir}/rest/rest-services-config.xml[]
----

Method parameter types can be omitted if the service doesn't contain an overloaded method with the same number of parameters. Otherwise, types must be defined.

An example of how to configure and invoke a service can be found in the <<rest_api_v2_ex_service_get>> chapter.

[[rest_api_v2_data_model_versioning]]
==== Data Model Versioning

REST API can handle data model changes. It is useful when, for example, some entity attribute was renamed, but REST API client doesn't know about this modification and expects the attribute to have an old name.

For such cases REST API allows you to define transformation rules for entities JSON. If the client application sends the data model version in the request query parameter then the JSON in REST API method response or request body will be transformed according to transformation rules defined for that particular domain model version.

JSON transformation rules must be specified in files registered in <<cuba.rest.jsonTransformationConfig, cuba.rest.jsonTransformationConfig>> application property of the *web* or *portal* module (e.g in the `web-app.properties` file):

[source,properties]
----
cuba.rest.jsonTransformationConfig = +com/company/myapp/rest-json-transformations.xml
----

The `rest-json-transformations.xml` file must be placed in the *web* or *portal* module (e.g. in package `com.company.myapp`). Its content is defined by the {xsd_url}/rest-json-transformations.xsd[rest-json-transformations.xsd] schema. File example:

[source, xml]
----
include::{sourcesdir}/rest/rest-json-transformations.xml[]
----

Standard transformers configured in the config file can perform the following transformations of entity JSON:

* rename entity

* rename entity attribute

* remove entity attribute

JSON transformation works for the following REST API endpoints:

* */entities* - getting entities list, getting a single entity, entity create, entity update, entity delete

* */queries* - entities JSON returned by the query will be transformed

* */services* - JSON transformations will be applied both to entities returned by the service method and to entities passed as a service method argument

JSON transformations are applied if the request to the REST API contains the `modelVersion` URL parameter with the data model version number.

See the <<rest_api_v2_ex_json_transformations>> to understand how to configure data model versioning and use it from the client application.

[[rest_api_v2_cors]]
==== CORS Settings

By default, all CORS requests to the REST API are allowed. To restrict the origins list you can define the <<cuba.rest.allowedOrigins, cuba.rest.allowedOrigins>> application property.

[[rest_api_v2_anonymous]]
==== Anonymous Access

By default, anonymous access is disabled. To enable it, use the <<cuba.rest.anonymousEnabled, cuba.rest.anonymousEnabled>> application property. A request is considered to be anonymous if it doesn't contain an `Authentication` header. In this case, the <<securityContext, SecurityContext>> will contain an anonymous user session.

To set up permissions for anonymous user you must define <<roles, roles>> for the user specified by the <<cuba.anonymousLogin, cuba.anonymousLogin>> application property.

[[rest_api_v2_settings]]
==== Other REST API Settings

<<cuba.rest.client.id, cuba.rest.client.id>> - defines a default REST API client id.

<<cuba.rest.client.secret, cuba.rest.client.secret>> - defines a default REST API client secret.

<<cuba.rest.client.tokenExpirationTimeSec, cuba.rest.client.tokenExpirationTimeSec>> - defines a token expiration time for the default client in seconds.

<<cuba.rest.maxUploadSize, cuba.rest.maxUploadSize>> - defines a maximum file size that can be uploaded with the REST API.

[[rest_api_v2_custom_controllers]]
==== Creating Custom OAuth2 Protected Controllers

If you need to create a custom REST controller protected with the OAuth2 authentication then you have to do the following:

. Suppose you have the following REST controller:
+
[source, java]
----
include::{sourcesdir}/features/MyController.java[]
----

. Create a new Spring configuration file with name `rest-dispatcher-spring.xml` under the root package (`com.company.test`) of *web* or *portal* module. The content of the file must be as follows:
+
[source, xml]
----
include::{sourcesdir}/rest/rest-dispatcher-spring.xml[]
----

. Define an <<additive_app_properties,additive>> application property `cuba.restSpringContextConfig` in the properties file of the module,.e.g. `portal-app.properties`:
+
[source, properties]
----
cuba.restSpringContextConfig = +com/company/test/rest-dispatcher-spring.xml
----

. The new controller runs in the context of the `CubaRestApiServlet`. So the URL for controller methods will start with the `/rest`, i.e. the doSmth() method will be accesed by the URL: `http://localhost:8080/app-portal/rest/myapi/dosmth`.
+
[WARNING]
====
URL of the custom controller MUST NOT start with the `/rest/v2`.
====

[[rest_api_v2_security_constraints]]
==== Security Constraints for Collection Attributes

If an entity that is returned by the REST API has a collection attribute and entities in the collection are restricted by any <<constraints,constraint>> then a system attribute `+__securityToken+` may be returned in the result JSON. When you send such entity to REST API methods for update you have to specify the `+__securityToken+` property (the one you got on entity read) in the JSON object. Otherwise, the collection property may be saved incorrectly.

Example:

[source, json]
----
include::{sourcesdir}/features/securityToken.json[]
----

[[rest_api_v2_persistent_token_store]]
==== Persistent Token Store

By default, OAuth tokens are stored in memory only. If you want to persist them in the database as well, you should set the <<cuba.rest.storeTokensInDb,cuba.rest.storeTokensInDb>> application property to `true`. The property value is stored in the database, so you can change its value in the *Administration > Application Properties* screen.

Expired tokens in the database store must be periodically deleted. The cron expression for scheduled removing of expired tokens is specified in the <<cuba.rest.deleteExpiredTokensCron,cuba.rest.deleteExpiredTokensCron>> application property.
