[[system_properties]]
[appendix]
== System Properties

System properties can be specified at JVM startup, using the command line argument `-D`. Additionally, system properties can be read or set using the `getProperty()` and `setProperty()` methods of the `System` class.

You can use system properties to set or override values of <<app_properties,application properties>>. For example, the following command line argument will override the value of the
<<cuba.connectionUrlList,cuba.connectionUrlList>> property which is normally set in the `web-app.properties` file:

[source,plain]
----
-Dcuba.connectionUrlList=http://somehost:8080/app-core
----

[WARNING]
====
Keep in mind, that system properties affect the whole JVM, i.e all application blocks running on the JVM will get the same value of a property.
====

Below are the system properties that are used by the platform but are not application properties.

[[logback.configurationFile]]
logback.configurationFile::
+
--
Defines the location of the *Logback* framework configuration file.

For application <<app_tiers,blocks>> running on the Tomcat web server, this system property is configured in the `tomcat/bin/setenv.bat` and `tomcat/bin/setenv.sh` files. By default, it points to the `tomcat/conf/logback.xml` configuration file.

For the Desktop Client block, the application code configures this property if it is not defined at JVM startup. By default it points to the `cuba-logback.xml` file in the CLASSPATH root. See <<logging_setup_desktop>>.
--

[[cuba.desktop.home]]
cuba.desktop.home:: 
+
--
For the Desktop Client <<app_tiers,block>>, this property defines the root for the folders defined in the <<cuba.confDir,cuba.confDir>>, <<cuba.logDir,cuba.logDir>>, <<cuba.tempDir,cuba.tempDir>>, and <<cuba.dataDir,cuba.dataDir>> application properties.

If this property is not defined at JVM startup, the default value of ${user.home}/.haulmont/cuba will be used. A different location can be specified by overriding the `getDefaultHomeDir()` method of the `com.haulmont.cuba.desktop.App` class.
--

[[cuba.unitTestMode]]
cuba.unitTestMode:: 
+
--
This system property is set to `true` when the `CubaTestCase` base class is running integration tests.

Example:

[source, java]
----
if (!Boolean.valueOf(System.getProperty("cuba.unitTestMode")))
  return "Not in test mode";
----
--

