[[system_properties]]
[appendix]
== System Properties

System properties can be specified at JVM startup, using the command line argument `-D`. Additionally, system properties can be read or set using the `getProperty()` and `setProperty()` methods of the `System` class.

You can use system properties to set or override values of <<app_properties,application properties>>. For example, the following command line argument will override the value of the
<<cuba.connectionUrlList,cuba.connectionUrlList>> property which is normally set in the `web-app.properties` file:

[source,plain]
----
-Dcuba.connectionUrlList=http://somehost:8080/app-core
----

[WARNING]
====
Keep in mind, that system properties affect the whole JVM, i.e all application blocks running on the JVM will get the same value of a property.
====

[WARNING]
====
System properties are cached by the framework at server startup, so your application should not rely on ability to override an application property by changing a system property at runtime. If you absolutely need it, reset the cache after changing a system property using the `clearSystemPropertiesCache()` methods of the <<cachingFacadeMBean,CachingFacadeMBean>> JMX bean.
====

Below are the system properties that are used by the platform but are not application properties.

[[logback.configurationFile]]
logback.configurationFile::
+
--
Defines the location of the *Logback* framework configuration file.

For application <<app_tiers,blocks>> running on the Tomcat web server, this system property is configured in the `tomcat/bin/setenv.bat` and `tomcat/bin/setenv.sh` files. By default, it points to the `tomcat/conf/logback.xml` configuration file.
--

[[cuba.unitTestMode]]
cuba.unitTestMode:: 
+
--
This system property is set to `true` when the `CubaTestCase` base class is running integration tests.

Example:

[source, java]
----
if (!Boolean.valueOf(System.getProperty("cuba.unitTestMode")))
  return "Not in test mode";
----
--

