:sourcesdir: ../../../../../source

[[app_properties_db]]
===== Storing Properties in the Database

Application properties that represent runtime parameters are stored in the `SYS_CONFIG` database table.

Such properties have the following distinctive features:

* As the property value is stored in the database, it is defined in a single location, regardless of what application blocks use it.

* The value can be changed and saved at runtime in the following ways:
** Using the *Administration > Application Properties* screen.
** Using the <<configStorageMBean,ConfigStorageMBean>> JMX bean.
** If the configuration interface has a setter method, you can set the property value in the application code.

* Property value can be overridden for a particular application block in its `*app.properties` file or via Java system property with the same name.

It is important to mention, that access to properties stored in the database on the client side leads to Middleware requests. This is less efficient than retrieving properties from local `*app.properties` files. To reduce the number of requests, the client caches properties for the lifetime of configuration interface implementation instance. Thus, if you need to access the properties of a configuration interface from some UI screen for several times, it is recommended to get the reference to this interface upon screen initialization and save it to a screen controller field for further access.

