:sourcesdir: ../../../../source

[[gantt_chart]]
==== GanttChart

Компонент `GanttChart` позволяет вам создать диаграмму Ганта.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=gantt-chart" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

.GanttChart
image::chart/gantt-chart.svg[align="center", width="800"]

XML-имя компонента: `chart:ganttChart`.

Элементы `chart:ganttChart`: ::
+
--
* `categoryAxis` - элемент, описывающий ось категорий.

* `graph` - элемент, содержащий коллекцию вложенных элементов `chart:graph`, описывающих графы диаграммы.
+
** атрибут `type` определяет тип графа и может быть: линией, столбцом, пунктиром, кривой, OHLC и японской свечой.
+
** атрибут `valueField` указывает ключ из коллекции пар ключ-значение, полученной из источника данных или data provider.

* `valueAxis` - элемент, описывающий ось значений. Если данные диаграммы основаны на значениях дат или времени, для оси значений можно указать тип  `date`.
--

Атрибуты `chart:ganttChart`: ::
+
--
* `segmentsField` - поле сегментов диаграммы.

* `additionalSegmentFields` - список дополнительных полей для сегментов, соответствующих некоторым атрибутам сущности, которые необходимо дополнительно загрузить из источника данных диаграммы. Этот атрибут используется аналогично атрибуту <<chart_additionalFields,additionalFields>>.

* `endField`/`endDateField` - конечное значение или конечная дата диаграммы.

* `startField`/`startDateField` - начальное значение или начальная дата диаграммы.

* `startDate` - начальная дата диаграммы, если выбран тип оси `date`.

* `categoryField` - поле категорий диаграммы.
--

Связь с данными: ::
+
--
Вы можете указать для диаграммы источник данных с типом `CollectionDatasource`. В примере ниже атрибуты `start` и `end` сущности указаны в качестве значений атрибутов `startDateField` и `endDateField` диаграммы:

[source, xml]
----
include::{sourcesdir}/chart/gantt_chart.xml[]
----
--

Слушатели событий `GanttChart`: ::
+
--
* `AxisZoomListener` - масштабирование оси графика.
* `CategoryItemClickListener` - щелчок по категории на оси категорий.
* `ChartClickListener` - щелчок по холсту.
* `ChartRightClickListener` - щелчок по холсту правой клавишей мыши.
* `CursorPeriodSelectListener` - выбор периода отображения курсором.
* `CursorZoomListener` - масштабирование области графика курсором.
* `GraphClickListener` - щелчок по графику.
* `GraphItemClickListener` - щелчок по элементу графика.
* `GraphItemRightClickListener` - щелчок по элементу графика правой клавишей мыши.
* `ZoomListener` - масштабирование холста.
--

Для более подробной информации об этом типе диаграмм см. http://docs.amcharts.com/3/javascriptcharts/AmGanttChart[документацию AmCharts].

