:sourcesdir: ../../../../source

[[gauge_chart]]
==== AngularGaugeChart

Компонент `AngularGaugeChart` позволяет вам создать диаграмму-спидометр.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=gauge-chart" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

.GaugeChart
image::chart/gauge-chart.svg[align="center", width="800"]

XML-имя компонента: `chart:gaugeChart`.

Элементы `chart:gaugeChart`: ::
+
--
* `arrows` - содержит вложенные элементы `arrow` со стрелками осей.
+
[source, xml]
----
<chart:arrows>
    <chart:arrow value="60"/>
</chart:arrows>
----

* `axes` - содержит вложенные элементы `axis` для осей диаграммы.
+
[source, xml]
----
include::{sourcesdir}/chart/chart_axes.xml[]
----
+
Элемент `band` позволяет разделить ось на несколько полос, как на изображении выше:
+
[source, xml]
----
include::{sourcesdir}/chart/chart_axes_band.xml[]
----
+
Атрибуты `endValue` и `startValue` определяют диапазон значений на шкале диаграммы, атрибут `valueInterval` задаёт шаг деления шкалы.
--

Слушатели событий `AngularGaugeChart`: ::
+
--
* `ChartClickListener` - щелчок по холсту.
* `ChartRightClickListener` - щелчок по холсту правой клавишей мыши.
--

Для более подробной информации об этом типе диаграмм см. http://docs.amcharts.com/3/javascriptcharts/AmAngularGauge[документацию AmCharts].

