:sourcesdir: ../../../../source

[[pie_chart]]
==== PieChart

Компонент `PieChart` позволяет вам создать круговые диаграммы.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=pie3d-chart" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

.PieChart
image::chart/pie-chart.svg[align="center", width="800"]

XML-имя компонента: `chart:pieChart`.

Связь с данными: ::
+
--
. Через контейнер данных.
+
Вы можете указать для диаграммы контейнер данных с типом `CollectionContainer`, а затем указать нужные поля в атрибутах `titleField` и `valueField` элемента `pieChart`:
+
[source, xml]
----
include::{sourcesdir}/chart/pie_chart.xml[]
----

. С помощью элемента <<chart_data,chart:data>>.
--

Слушатели событий `PieChart`: ::
+
--
* `ChartClickListener` – щелчок по холсту.
* `ChartRightClickListener` – щелчок по холсту правой клавишей мыши.
* `SliceClickListener` – щелчок по элементу круговой диаграммы.
* `SlicePullInListener` – элемент круговой диаграммы соединён с диаграммой.
* `SlicePullOutListener` – элемент круговой диаграммы отсоединён от диаграммы.
* `SliceRightClickListener` – щелчок по элементу круговой диаграммы правой клавишей мыши.
--

Для более подробной информации об этом типе диаграмм смотрите http://docs.amcharts.com/3/javascriptcharts/AmPieChart[документацию AmCharts].

