:sourcesdir: ../../../../source

[[radar_chart]]
==== RadarChart

Компонент `RadarChart` позволяет вам создать радиальные/сетчатые диаграммы.

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.com/sampler/open?screen=polar-chart" class="live-demo-btn" target="_blank">ДЕМОНСТРАЦИЯ</a>
</div>
++++

.RadarChart
image::chart/radar-chart.svg[align="center", width="800"]

XML-имя компонента: `chart:radarChart`.

Связь с данными: ::
+
--
Вы можете указать для диаграммы контейнер данных с типом `CollectionContainer`, а затем указать нужные поля в качестве значений атрибутов `categoryField` элемента `radarChart` и `valueField` вложенного элемента `graph`:

[source, xml]
----
include::{sourcesdir}/chart/radar_chart.xml[]
----
--

Слушатели событий `RadarChart`: ::
+
--
* `AxisZoomListener` – масштабирование оси графика.
* `ChartClickListener` – щелчок по холсту.
* `ChartRightClickListener` – щелчок по холсту правой клавишей мыши.
* `GraphClickListener` – щелчок по графику.
* `GraphItemClickListener` – щелчок по элементу графика.
* `GraphItemRightClickListener` – щелчок по элементу графика правой клавишей мыши.
--

Для более подробной информации об этом типе диаграмм смотрите http://docs.amcharts.com/3/javascriptcharts/AmRadarChart[AmCharts documentation].

