:sourcesdir: ../../../../../source

[[entity_listeners]]
===== Entity Listeners

_Entity Listeners_ предназначены для реакции на события жизненного цикла экземпляров сущностей на уровне Middleware. См. пример использования в <<using_entity_listeners_recipe, сборнике рецептов>>.

Слушатель представляет собой класс, реализующий один или несколько интерфейсов пакета `com.haulmont.cuba.core.listener`. Слушатель будет реагировать на события типов, соответствующих реализуемым интерфейсам.

BeforeDetachEntityListener::
+
--
Метод `onBeforeDetach()` вызывается перед отделением объекта от <<entityManager,EntityManager>> при коммите транзакции.

Данный слушатель можно использовать, например, для заполнения неперсистентных атрибутов сущности перед отправкой ее на клиентский уровень.
--

BeforeAttachEntityListener::
+
--
Метод `onBeforeAttach()` вызывается перед введением объекта в персистентный контекст при выполнении операции `EntityManager.merge()`.

Данный слушатель можно использовать, например, для заполнения персистентных атрибутов сущности перед сохранением ее в базе данных.
--

BeforeInsertEntityListener::
Метод `onBeforeInsert()` вызывается перед выполнением вставки записи в БД. В данном методе возможны любые операции с текущим `EntityManager`.

AfterInsertEntityListener::
Метод `onAfterInsert()` вызывается после выполнения вставки записи в БД, но до коммита транзакции. В данном методе нельзя модифицировать текущий персистентный контекст, однако можно производить изменения в БД с помощью <<queryRunner,QueryRunner>>.

BeforeUpdateEntityListener::
Метод `onBeforeUpdate()` вызывается перед изменением записи в БД. В данном методе возможны любые операции с текущим `EntityManager`.

AfterUpdateEntityListener::
Метод `onAfterUpdate()` вызывается после изменения записи в БД, но до коммита транзакции. В данном методе нельзя модифицировать текущий персистентный контекст, однако можно производить изменения в БД с помощью `QueryRunner`.

BeforeDeleteEntityListener::
Метод `onBeforeDelete()` вызывается перед удалением записи из БД (или в случае <<soft_deletion,мягкого удаления>> - перед изменением записи). В данном методе возможны любые операции с текущим `EntityManager`.

AfterDeleteEntityListener::
Метод `onAfterDelete()` вызывается после удаления записи из БД (или в случае мягкого удаления - после изменения записи), но до коммита транзакции. В данном методе нельзя модифицировать текущий персистентный контекст, однако можно производить изменения в БД с помощью `QueryRunner`.

Entity Listener должен являться управляемым бином, поэтому в нем можно использовать инжекцию:

[source, java]
----
include::{sourcesdir}/middleware/entitylisteners_1.java[]
----

Все слушатели кроме `BeforeAttachEntityListener` выполняются внутри транзакции. Это значит, что если внутри слушателя выбрасывается исключение, текущая транзакция откатывается и все изменения в базе данных теряются.

Если вам необходимо выполнить некоторые действия после успешного завершения транзакции, используйте callback-интерфейс `TransactionSynchronization` фреймворка Spring для того чтобы отложить выполнение до нужной фазы транзакции. Например:

[source, java]
----
include::{sourcesdir}/middleware/entitylisteners_3.java[]
----

Регистрация entity listeners::
+
--
Entity Listener может быть задан двумя способами:

* Статически - имена бинов слушателей указываются в аннотации <<listeners_annotation,@Listeners>> на классе сущности:
+
[source, java]
----
include::{sourcesdir}/middleware/entitylisteners_2.java[]
----

* Динамически - имя бина слушателя передается в метод `addListener()` бина `EntityListenerManager`. Пример динамического добавления слушателя рассматривается в разделе рецептов разработки: <<app_start_recipe,Выполнение кода на старте приложения>>.

Для всех экземпляров некоторого класса сущности создается _один_ экземпляр слушателя определенного типа, поэтому слушатель _не должен иметь состояния_.

Если для сущности объявлены несколько слушателей одного типа (например, аннотациями класса сущности и его предков, плюс динамически), то их вызов будет выполняться в следующем порядке:

. Для каждого предка, начиная с самого дальнего, вызываются его динамически добавленные слушатели, затем статически назначенные.

. После всех предков вызываются динамически добавленные слушатели данного класса, затем статически назначенные.
--
