:sourcesdir: ../../../../../source

[[entity_states]]
===== Состояния сущности

New:: 
+
--
Только что созданный в памяти экземпляр, например: `Car car = new Car()`.
Новый экземпляр может быть передан в `EntityManager.persist()` для сохранения в БД, при этом он переходит в состояние Managed.
--

Managed:: 
+
--
Загруженный из БД или новый, переданный в EntityManager.persist(), экземпляр. Принадлежит некоторому экземпляру `EntityManager`, другими словами, находится в его персистентном контексте.

Любые изменения экземпляра в состоянии Managed будут сохранены в БД в случае коммита транзакции, к которой принадлежит данный `EntityManager`.

--

Detached:: 
+
--
Экземпляр, загруженный из БД и отсоединенный от своего персистентного контекста (вследствие завершения транзакции или сериализации).

Изменения, вносимые в Detached экземпляр, запоминаются в самом этом экземпляре (в полях, добавленных с помощью bytecode enhancement). Эти изменения будут сохранены в БД, только если данный экземпляр будет снова переведен в состояние Managed путем передачи в метод `EntityManager.merge()`.
--

