:sourcesdir: ../../../../../source

[[nativeQuery]]
===== Выполнение SQL запросов

ORM позволяет выполнять SQL запросы к базе данных, возвращая как списки отдельных полей, так и экземпляры сущностей. Для этого необходимо создать объект `Query` или `TypedQuery` вызовом одного из методов `EntityManager.createNativeQuery()`. 

Если выполняется выборка отдельных колонок таблицы, то результирующий список будет содержать строки в виде `Object[]`. Например:

[source, java]
----
include::{sourcesdir}/middleware/sqlquery_1.java[]
----

Если выполняется выборка единственной колонки или агрегатной функции, то результирующий список будет содержать эти значения непосредственно:

[source, java]
----
include::{sourcesdir}/middleware/sqlquery_3.java[]
----

Если вместе с текстом запроса передан класс результирующей сущности, то возвращается `TypedQuery` и после выполнения производится попытка отображения результатов запроса на атрибуты сущности. Например:

[source, java]
----
include::{sourcesdir}/middleware/sqlquery_2.java[]
----

Следует иметь в виду, что при использовании SQL колонки, соответствующие атрибутам сущностей типа `UUID`, возвращаются в виде `UUID` или в виде `String`, в зависимости от используемой СУБД:

* *HSQLDB* - `String`
* *PostgreSQL* - `UUID`
* *Microsoft SQL Server* - `String`
* *Oracle* - `String`
* *MySQL* – `String`

Параметры этого типа также должны задаваться либо как `UUID`, либо своим строковым представлением, в зависимости от используемой СУБД. Для обеспечения независимости кода от используемой СУБД рекомендуется использовать <<dbTypeConverter,DbTypeConverter>>, который обеспечивает конвертацию данных между объектами Java и параметрами и результатами JDBC.

В SQL запросах можно использовать позиционные или именованные параметры. Позиционные параметры обозначаются ? с последующим номером параметра начиная с 1. Именованные параметры обозначаются знаком #. См. примеры выше.

Поведение SQL запросов, возвращающих сущности, и модифицирующих запросов (`update`, `delete`), по отношению к текущему персистентному контексту аналогично описанному для <<query,JPQL запросов>>.

См. также <<queryRunner,>>.

