:sourcesdir: ../../../source

[[qs_project_creation]]
=== Creating the Project
. Create a new project in CUBA Studio as described in the {studio_man_url}/create_project.html[Creating a New Project] section of the {studio_man_url}/index.html[CUBA Studio User Guide]:

* Project name: `bpm-demo`
* Project namespace: `demo`
* Root package: `com.company.bpmdemo`

[start=2]
. Open the *Project Properties* editor in CUBA Studio: click *CUBA > Project Properties* main menu item. Add the *bpm* application component in the *App components* list. Confirm when Studio suggests recreating Gradle scripts.

. Assemble the project: select option *CUBA* > *Build Tasks* > *Assemble* in the Studio main menu. At this stage, all required libraries will be downloaded and project {main_man_url}/glossary.html#artifact[artifacts] will be assembled in `build` subdirectories of the project {main_man_url}/app_modules.html[modules].

. Create the database on the local *HyperSQL* server: select option *CUBA* > *Create database* in the main menu. The database name is the same as project namespace by default.

. Select *CUBA* > *Build Tasks* > *Deploy* menu option. The *Tomcat* server with the deployed application will be installed in the project `deploy` subdirectory.

. Select *CUBA* > *Start application server* option. The link in the *Runs at...* section of the CUBA project tree will help to open the application in a web browser directly from Studio.
+
The username and password are `admin` / `admin`.
+
The running application contains two main menu items (*Administration* and *Help*), as well as {main_man_url}/security_subsystem.html[security] and administration subsystems functionality.


