:sourcesdir: ../../../../source

[[structure_json]]
==== Набор данных JSON

*JSON* – набор данных формируется из данных в формате JSON, которые могут быть получены из следующих источников:

. *Groovy script*
+
--
Скрипт задается пользователем и должен возвращать JSON как строку, например:

[source, json]
----
include::{sourcesdir}/json.groovy[]
----
--

. *URL*
+
--
Генератор отчётов запрашивает данные через URL с помощью GET HTTP-запроса, например:

[source, plain]
----
https://jsonplaceholder.typicode.com/users
----
--

. *Parameter*
+
--
Внешний параметр отчёта с типом String, содержащий данные JSON, можно создать на вкладке *Parameters and Formats* редактора отчётов.
--

Извлечь необходимые данные из полученного дерева JSON можно запросом JsonPath. К примеру, выражение `$.store.book[*]` вернет все книги из дерева JSON в следующем примере:

[source, json]
----
include::{sourcesdir}/json.json[]
----

Более подробно о выражениях JsonPath можно посмотреть на http://goessner.net/articles/JsonPath/.

[WARNING]
====
Поля, выводимые отчётом, имеющие типы данных `Date`, `DateTime`, `Time`, не поддерживают формат, определённый по правилам `java.text.SimpleDateFormat`. Для задания корректного формата вам следует написать скрипт на Groovy.

Для этого перейдите на вкладку **Parameters and Formats** редактора отчёта и откройте форму добавления <<formatters,формата>>.
Например, для поля отчёта `bookPublication.dateTime` Groovy-скрипт будет иметь следующий вид:

[source, groovy]
----
include::{sourcesdir}/formatter_for_dates.groovy[]
----
====
