:sourcesdir: ../../../../source

[[structure_jpql]]
==== Набор данных JPQL

*JPQL* – набор данных формируется выполнением JPQL-запроса к базе данных. Поля результирующего набора запроса необходимо снабдить алиасами с помощью оператора `as`. В JPQL-запросе можно использовать входные параметры отчёта и поля родительских полос аналогично описанному для SQL-запроса.

Пример JPQL-запроса с параметром `groupId`, полученным из родительской полосы `group`, и внешним параметром `active`:

[source, groovy]
----
select u.name as userName, u.login as userLogin
from sec$User u
where u.group.id = ${group.groupId}
    and u.active = ${active}
----

Запросы на JPQL автоматически поддерживают мягкое удаление и возвращают только неудаленные записи.

Также вы можете использовать <<query_preprocessing,препроцессор запросов>>, установив флажок *Preprocess query as Groovy template* под редактором полосы.

По умолчанию JPQL-запросы выполняются по сущностям основной базы данных. Если необходимо выполнить запрос к сущностям {main_man_url}/data_store.html[дополнительного хранилища], укажите его имя в поле *Data store*.

