:sourcesdir: ../../../../../../source

[[rest_api_v2_social_login]]
====== Social Login в REST API

Механизм авторизации через социальные сети, или social login, также можно использовать в REST API. Исходный код приложения, описанного в этом примере, доступен на https://github.com/cuba-platform/sample-social-login/[GitHub], а сам пример описан в разделе <<social_login>>. Ниже приведены ключевые моменты этого примера, позволяющие получить OAuth-токен через аккаунт Facebook.

. Создайте пакет `restapi` в корневом каталоге модуля *web* и поместите в него собственный контроллер Spring MVC. Контроллер должен содержать два основных метода: `get()`, возвращающий `ResponseEntity`, и `login()`, в котором мы будем получать OAuth-токен.
+
--
[source,java]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/src/com/company/demo/restapi/FacebookAuthenticationController.java[FacebookAuthenticationController.java]
----
include::{sourcesdir}/rest/social_login_rest_1.java[]
----

Здесь мы проверяем переданный код Facebook, получаем код доступа и издаём токен с помощью `OAuthTokenIssuer`:

[source,java]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/src/com/company/demo/restapi/FacebookAuthenticationController.java[FacebookAuthenticationController.java]
----
include::{sourcesdir}/rest/social_login_rest_2.java[]
----
--

. Исключите пакет `restapi` из сканирования в модулях *web/core*: это необходимо, так как бин `OAuthTokenIssuer` доступен только внутри контекста REST API, и сканирование его в контексте приложения будет вызывать ошибку.
+
[source, xml]
----
include::{sourcesdir}/rest/social_login_rest_5.xml[]
----

. Создайте файл `facebook-login-demo.html` в каталоге проекта `modules/web/web/VAADIN`. Он будет содержать JavaScript-код, выполняющийся на HTML-странице:
+
--
[source, html]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/web/VAADIN/facebook-login-demo.html[facebook-login-demo.html]
----
include::{sourcesdir}/rest/social_login_rest_3.html[]
----

В этом скрипте мы попробуем залогиниться через Facebook. Сначала удаляем лишний код из URL, затем передаём код в REST API для получения OAuth-токена, и в случае успешной аутентификации мы сможем загружать и сохранять данные как обычно:

[source, js]
.https://github.com/cuba-platform/sample-social-login/blob/master/modules/web/web/VAADIN/facebook-login-demo.html[facebook-login-demo.html]
----
include::{sourcesdir}/rest/social_login_rest_4.js[]
----

Другой пример использования JavaScript-кода в приложениях CUBA вы можете найти в разделе <<rest_api_v2_ex_javascript_usage>>.
--

