:sourcesdir: ../../../../../source

[[tomcat_in_prod]]
===== Использование Tomcat при эксплуатации приложения

Процедура <<fast_deployment,быстрого развертывания>> по умолчанию создает веб приложения `app` и `app-core`, работающие на локальном инстансе Tomcat на порту 8080. Это означает, что веб-клиент доступен по адресу `++http://localhost:8080/app++`.

Вы можете использовать этот экземпляр Tomcat для эксплуатации приложения, просто скопировав его на сервер. После этого необходимо установить имя хоста сервера в файлах `conf/app/local.app.properties` и `conf/app-core/local.app.properties` (создайте файлы если они не существуют):

[source, plain]
----
  cuba.webHostName = myserver
  cuba.webAppUrl = http://myserver:8080/app
---- 

Кроме того, необходимо настроить подключение к production базе данных. Это можно сделать в файле <<context.xml>> веб-приложения (`webapps/app-core/META-INF/context.xml`), или скопировать этот файл в `conf/Catalina/localhost/app-core.xml` как описано в предыдущем разделе, чтобы разделить настройки соединения с БД для разработки и эксплуатации.

Базу данных для production можно создать из бэкапа той базы, которая использовалась при разработке, либо настроить автоматическое создание и обновление БД. См. <<db_update_in_prod>>.

Опциональная конфигурация::
+
--
. Если вы хотите изменить порт Tomcat или веб-контекст (последнюю часть URL после `/`), используйте *Studio*:

* Откройте проект в Studio.

* Перейдите в *Project Properties*.

* Чтобы изменить веб-контекст, отредактируйте поле *Modules prefix*.

* Чтобы изменить порт Tomcat, отредактируйте поле *Tomcat ports* > *HTTP port*.

. Если вы хотите использовать корневой контекст (`++http://myserver:8080/++`), переименуйте каталоги `app` (или то что вы задали на предыдущем этапе) в `ROOT`
+
[source, plain]
----
tomcat/
  conf/
      ROOT/
          local.app.properties
      app-core/
          local.app.properties
  webapps/
      ROOT/
      app-core/
----
+
и используйте `/` в качестве веб контекста в файле `conf/ROOT/local.app.properties`:
+
[source, plain]
----
cuba.webContextName = /
---- 
--

