:sourcesdir: ../../../../../source

[[tomcat_in_prod]]
===== Использование Tomcat при эксплуатации приложения

Процедура <<fast_deployment,быстрого развертывания>> по умолчанию создает веб приложения `app` и `app-core`, работающие на локальном инстансе Tomcat на порту 8080. Это означает, что веб-клиент доступен по адресу `++http://localhost:8080/app++`.

Вы можете использовать этот экземпляр Tomcat для эксплуатации приложения, просто скопировав каталоги `tomcat` и `app_home` на сервер. Пользователь, запускающий Tomcat, должен иметь права на чтение и запись в этих каталогах.

После этого необходимо установить имя хоста сервера в `app_home/local.app.properties`:

[source, plain]
----
  cuba.webHostName = myserver
  cuba.webAppUrl = http://myserver:8080/app
---- 

Кроме того, необходимо настроить подключение к production базе данных. Это можно сделать в файле <<context.xml>> веб-приложения (`tomcat/webapps/app-core/META-INF/context.xml`), или скопировать этот файл в `tomcat/conf/Catalina/localhost/app-core.xml` как описано в предыдущем разделе, чтобы разделить настройки соединения с БД для разработки и эксплуатации.

Базу данных для production можно создать из бэкапа той базы, которая использовалась при разработке, либо настроить автоматическое создание и обновление БД. См. <<db_update_in_prod>>.
