:sourcesdir: ../../../../../source

[[polymer_in_studio]]
===== Polymer UI в Studio

// TODO update Studio flow
Для добавления в проект клиентского модуля Polymer откройте его в CUBA Studio и нажмите *Create module > Create polymer client module* на вкладке *Project Properties* навигатора. Studio создаст модуль *front* и сконфигурирует соответствующим образом `build.gradle`. Модуль будет содержать заглушку приложения, которая позволяет подключаться к REST API и выполнять login и logout пользователя в middleware.

После создания модуля, запустите сервер приложения и откройте `++http://localhost:8080/app-front++` в веб-браузере. Вы увидите форму логина. После успешного входа будет отображено главное окно с вертикальным меню и responsive дизайном.

Для создания экрана UI, работающего с сущностью, выберите сущность в секции *Data Model* Studio и нажмите *New > Polymer UI component*. Выберите шаблон (например, *Entity cards list with editor*), заполните свойства шаблона и нажмите *Create*. Веб-компонент будет сгенерирован и добавлен в меню приложения. Studio обеспечивает hot-deploy компонентов Polymer, так что вам необходимо лишь обновить страницу в браузере и вы увидите в меню элемент, вызывающий только что созданный экран.

