:sourcesdir: ../../../../source

[[access_to_repo]]
==== Configuring Access to Repository

Main Repository::
+
--
When you create a new project, you have to select a main repository containing CUBA artifacts. By default, there are two options (and you can have more if you set up a <<private_repo,private repository>>):

* `++https://repo.cuba-platform.com/content/groups/work++` - a repository located at Haulmont's server. It requires common credentials which are specified right in the build script (`cuba` / `cuba123`).

* `++https://dl.bintray.com/cuba-platform/main++` - a repository hosted at https://bintray.com[JFrog Bintray]. It has anonymous access.

Both repositories have identical contents for the latest platform versions, but Bintray does not contain snapshots. We assume that Bintray is more reliable for worldwide access.

In case of Bintray, the build script of the new project is also configured to use Maven Central, JCenter and Vaadin Add-ons repositories separately.
--

[[access_to_premium_repo]]
Access to CUBA Premium Add-ons::
+
--
If your project uses CUBA Premium Add-ons, Studio adds one more repository:

* In case of `repo.cuba-platform.com` it is `++https://repo.cuba-platform.com/content/groups/premium++`

* In case of Bintray it is `++https://cuba-platform.bintray.com/premium++`

If you use a <<private_repo,private repository>>, nothing is added automatically, because it is assumed that it proxies all CUBA repositories including premium ones.

Both Premium Add-ons repositories require a user name and a password which are provided by per-developer subscription. The first part of your license key before dash is the repository user name, the part after dash is the password. For example, if your key is `111111222222-abcdefabcdef`, then the user name is `111111222222` and the password is `abcdefabcdef`.

When you build the project from Studio, it passes repository credentials to Gradle automatically. If you want to build the project outside Studio, you can pass `premiumRepoUser` and `premiumRepoPass` in the command line arguments with `-P` prefix. In case of Bintray, the user name must be followed by `@cuba-platform`.

Example of building with `repo.cuba-platform.com`:

[source]
----
gradlew assemble -PpremiumRepoUser=111111222222 -PpremiumRepoPass=abcdefabcdef
----

Example of building with Bintray:

[source]
----
gradlew assemble -PpremiumRepoUser=111111222222@cuba-platform -PpremiumRepoPass=abcdefabcdef
----

Instead of passing credentials each time you build the project from the command line, you can set them once in one of the following ways.

* Either create a `~/.gradle/gradle.properties` file and set properties in it:

[source]
----
premiumRepoUser=111111222222
premiumRepoPass=abcdefabcdef
----

* Or set the following environment variables for your operating system:

** `CUBA_PREMIUM_USER` - will be used if `premiumRepoUser` is not passed.

** `CUBA_PREMIUM_PASSWORD` - will be used if `premiumRepoPass` is not passed.
--

[[custom_repositories]]
Custom Repositories::
+
--
Your project can use any number of custom repositories containing <<app_components,application components>>. They should be specified in `build.gradle` manually *after* the main repository, for example:

[source,groovy]
----
include::{sourcesdir}/development/access_to_repo_1.groovy[]
----
--

