:sourcesdir: ../../../../../source

[[entity_log_view]]
===== Отображение журнала

Для просмотра журнала изменений некоторого экземпляра сущности достаточно обычным способом загрузить в контейнеры данных экрана коллекцию экземпляров `EntityLogItem` и ассоциированных с ними `EntityLogAttr`, и создать визуальные компоненты, связанные с этими контейнерами.

В приведенном ниже примере показан фрагмент XML-дескриптора экрана сущности `Customer`, который содержит вкладку с содержимым журнала сущности.

.Фрагмент XML-дескриптора customer-edit.xml
[source, xml]
----
include::{sourcesdir}/features/entity_log.xml[]
----

Теперь рассмотрим контроллер экрана редактирования сущности `Customer`:

.Фрагмент контроллера экрана редактирования
[source, java]
----
include::{sourcesdir}/features/entity_log_controller.java[]
----

Обратите внимание, что на классе экрана нет аннотации `@LoadDataBeforeShow`, так как загрузка вызывается явно.

<1> − в методе `onBeforeShow` загружаются данные перед отображением экрана.
<2> − в обработчике `ItemChangeEvent` родительского контейнера `customerDc` передаётся параметр в зависимый загрузчик, и затем загружаются данные.
