:sourcesdir: ../../../../source

[[polymer_build_and_structure]]
==== Структура проекта и система сборки
В системе сборки Polymer-клиента используются следующие инструменты:

* https://nodejs.org/en/[Node.js]
* https://bower.io/[bower]
* https://github.com/Polymer/polymer-cli[polymer-cli]

По умолчанию, установкой и запуском этих инструментов занимается Gradle, однако можно использовать их и напрямую, см. <<polymer_tools,Использование нативных инструментов Polymer>>.

Polymer 2.0 и нативные компоненты написаны с использованием синтаксиса ES6, поэтому для поддержки старых браузеров требуется https://www.polymer-project.org/2.0/docs/es6[дополнительная компиляция] ES6 → ES5 при сборке.

[WARNING]
====
По умолчанию в Polymer клиенте используется пресет сбоки `es6-unbundled`, который не подразумевает компиляцию в ES5. Поэтому для поддержки старых проектов и развёртывания на живые сервера необходимо изменить его на `es5-bundled`.
====

Для изменения пресета отредактируйте свойство `builds` в файле `polymer.json`:

[source,json]
----
  "builds": [
    {
      "preset": "es5-bundled",
      "basePath": "/app-front/",
      "addServiceWorker": false
    }
  ]
----

Более подробную информацию о пресетах и опциях сборки вы можете найти на https://www.polymer-project.org/2.0/toolbox/build-for-production[сайте Polymer].

В `polymer.json` можно указать несколько вариантов сборки, для разворачивания конкретного варианта в Tomcat необходимо изменить задачу `deploy` в `build.gradle`:

[source,groovy]
----
    task deploy(type: Copy, dependsOn: [assemble, deployUnbundled]) {
        from file('build/es5-unbundled')
        into "$cuba.tomcat.dir/webapps/$frontAppDir"
    }
----

Обратите внимание на изменение `es6-bundled` → `es5-unbundled` в `polymer.json` и `build.gradle`.

include::polymer_build_and_structure/polymer_directory_structure.adoc[]

include::polymer_build_and_structure/polymer_hot_deploy.adoc[]

include::polymer_build_and_structure/polymer_tools.adoc[]

