:sourcesdir: ../../../../source

[[polymer_offline]]
==== Использование offline

[WARNING]
====
Экспериментальная технология!

Ещё не все браузеры поддерживают технологии из списка ниже (к примеру, service workers https://jakearchibald.github.io/isserviceworkerready[пока не поддерживаются] в Safari).
====

В настоящее время мы рекомендуем вместе с Polymer использовать технологии https://developers.google.com/web/progressive-web-apps/[Progressive Web Applications], такие как https://developer.mozilla.org/en-US/docs/Web/Manifest[web app manifest] https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/[2], чтобы добиться *native-like* присутствия на домашнем экране пользователя. См. файл `manifest.json` в модуле клиента Polymer.

Существуют два основных подхода:

* Service Workers используется преимущественно для кэширования самого приложения. См. файл `sw-precache-config.js`, сгенерированный при создании Polymer клиента. Чтобы разрешить генерацию service worker, измените команду `assemble` модуля Polymer следующим образом:

Больше информации о том, как настроить и использовать service workers, вы можете найти https://www.polymer-project.org/2.0/toolbox/service-worker[здесь].

* https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage[Local storage] и
https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API[Indexed DB], используемые для локального хранения данных. Примеры использования этой функциональности в соответствующих элементах Polymer:
https://www.webcomponents.org/element/PolymerElements/app-storage?active=app-localstorage-document[app-localstorage-document]
https://www.webcomponents.org/element/PolymerElements/app-storage?active=app-indexeddb-mirror[app-indexeddb-mirror].

