:sourcesdir: ../../../../source

[[qs_users_creation]]
==== Создание пользователей

Для демонстрации работы процесса создайте несколько тестовых пользователей. Откройте экран *Administration > Users* и создайте трех пользователей:

* login: `norman`, First name: `Tommy`, Last name: `Norman`, Full name: `Tommy Norman`
* login: `roberts`, First name: `Casey`, Last name: `Roberts`, Full name: `Casey Roberts`
* login: `pierce`, First name: `Walter`, Last name: `Pierce`, Full name: `Walter Pierce`

Назначьте роль *bpm-process-actor*, чтобы предоставить доступ к сущностям BPM.

Создайте роль *quick-start* и предоставьте ей необходимые для работы с проектом разрешения:

. Перейдите на экран *Administration -> Roles* и создайте новую роль с именем *quick-start*.
. На вкладке *Screens* разрешите доступ к экрану *BPM -> Process Tasks*. Этот экран не доступен в роли *bpm-process-actor*, так как может понадобиться не всем проектам.
. Разрешите доступ к экранам:
+
* *Application ->Contracts*
* *bpm$ProcTask.edit*
* *bpmdemo_Contract.edit*
* *bpm$ProcInstance.edit*
+
. Разрешите *bpmdemo_Contract* во вкладках *Entities* и *Attributes*.
. Сохраните роль.

Назначьте роль *quick-start* созданным ранее пользователям.

