:sourcesdir: ../../../../source

[[screen_params_return]]
==== Returning Values from an Invoked Screen

++++
<div class="manual-live-demo-container">
    <a href="https://demo3.cuba-platform.com/generic-ui/open?screen=sample$Order.browse2" class="live-demo-btn" target="_blank">LIVE DEMO</a>
</div>
++++

The <<abstractFrame_openWindow,methods>> used for opening screens (`openWindow()`, `openLookup()`, `openEditor()`) also allow you to get values back from these screens.

Returning a value from lookup screen::
+
--
The `openLookup()` method accepts a handler for the items selected in the opened lookup screen. In our example, the handler implemented by the lambda expression sets the selected customer for the edited `Order` instance.

[source, java]
----
include::{sourcesdir}/cookbook/window_params_4.java[]
----
--

Returning a value from an arbitrary screen::
+
--
The idea is that you return a reference to the controller of the opened screen, and then add a `CloseListener` to this reference. In the listener, you handle the values after the screen is closed.

https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/web/src/com/company/sample/web/order/OrderEdit.java[OrderEdit] screen controller demonstrates two ways of looking up a https://github.com/cuba-platform/sample-generic-ui/blob/master/modules/global/src/com/company/sample/entity/Customer.java[Customer]: from a lookup screen and from an arbitrary screen, both returning a `Customer` instance.

The `openWindow()` method in the following example will open the customers list screen as a dialog window. `CloseWithCommitListener` will be notified when the screen is <<abstractWindow_close,closed>> by action with `Window.COMMIT_ACTION_ID`. This listener will be used to set the selected customer for the edited `Order` instance.

[source, java]
----
include::{sourcesdir}/cookbook/window_params_5.java[]
----
--

