:sourcesdir: ../../../source

[[gui_framework]]
=== Универсальный пользовательский интерфейс

Подсистема универсального пользовательского интерфейса (Generic UI, GUI) позволяет разрабатывать экраны UI, используя Java и XML. Использование XML не обязательно, но позволяет описывать компоновку экрана декларативно и снижает объем кода, требуемого для создания пользовательского интерфейса.

.Структура универсального пользовательского интерфейса 
image::ClientStructure.svg[align="center"]

Экраны приложения состоят из следующих частей:

* <<screen_descriptors,Дескрипторы>> - XML-файлы, содержащие информацию о компоновке экрана и компонентах данных.

* <<screen_controllers,Контроллеры>> - классы Java, содержащие логику инициализации и обработки событий от экрана и его компонентов.

Код экранов приложения взаимодействует с интерфейсами визуальных компонентов (VCL Interfaces). Эти интерфейсы реализованы с использованием компонентов фреймворка Vaadin.

<<gui_vcl,Библиотека визуальных компонентов>> (Visual Components Library, VCL) содержит большой набор готовых компонентов.

<<gui_data,Компоненты данных>> (Data components) предоставляют унифицированный интерфейс для связывания визуальных компонентов с сущностями модели данных и для работы с сущностями в контроллерах экранов.

<<gui_web,Инфраструктура>> (Infrastructure) включает в себя главное окно приложения и другие общие клиентские механизмы.

include::gui_framework/gui_screens.adoc[]

include::gui_framework/gui_vcl.adoc[]

include::gui_framework/gui_data.adoc[]

include::gui_framework/gui_facets.adoc[]

include::gui_framework/gui_Action.adoc[]

include::gui_framework/gui_dialogs.adoc[]

include::gui_framework/gui_notifications.adoc[]

include::gui_framework/background_tasks.adoc[]

include::gui_framework/gui_themes.adoc[]

include::gui_framework/gui_icons.adoc[]

include::gui_framework/html_attributes.adoc[]

include::gui_framework/shortcuts.adoc[]

include::gui_framework/url_history_navigation.adoc[]

include::gui_framework/composite_components.adoc[]

include::gui_framework/pluggable_component_factories.adoc[]

include::gui_framework/webComponentsHelper.adoc[]

include::gui_framework/own_components.adoc[]

include::gui_framework/gui_web.adoc[]

include::gui_framework/web_login.adoc[]

include::gui_framework/gui_anonymous_access.adoc[]

include::gui_framework/unsupported_browser_page.adoc[]

include::gui_framework/webBrowserTools.adoc[]

include::gui_framework/static_resources.adoc[]