:sourcesdir: ../../../source

[[portal]]
=== Компоненты портала

В данном руководстве _порталом_ называется клиентский <<app_tiers,блок>>, способный решать следующие задачи:

* предоставлять альтернативный веб-интерфейс, как правило, предназначенный для пользователей за пределами организации;

* предоставлять интерфейс для интеграции с мобильными приложениями и со сторонними системами.

Конкретное приложение может содержать несколько портальных модулей, предназначенных для различных целей, например, в случае приложения, автоматизирующего бизнес такси, это может быть публичный веб-сайт для клиентов, интеграционный модуль мобильного приложения заказа такси, интеграционный модуль мобильного приложения водителей, и т.д. 

<<app_components,Базовый проект>> *cuba* платформы содержит в своем составе модуль *portal*, который является заготовкой для создания порталов в проектах. Он предоставляет базовую функциональность клиентского блока для работы с Middleware. Кроме того, универсальный <<rest_api_v2,REST API>>, включенный в модуль *portal* в качестве зависимости, запускается по умолчанию.

Рассмотрим основные компоненты, предоставляемые платформой для построения портала.

* `PortalAppContextLoader` - загрузчик <<appContext,AppContext>>, должен быть зарегистрирован в элементе `listener` файла `web.xml`.

* `PortalDispatcherServlet` - центральный сервлет, распределяющий запросы по контроллерам Spring MVC, как для веб-интерфейса, так и для REST API. Набор файлов конфигурации контекста Spring определяется свойством приложения <<cuba.dispatcherSpringContextConfig,cuba.dispatcherSpringContextConfig>>. Данный сервлет должен быть зарегистрирован в `web.xml` и отображен на корневой URL веб-приложения.

* `App` - объект, содержащий информацию о текущем HTTP запросе и ссылку на объект `Connection`. Экземпляр `App` может быть получен в прикладном коде вызовом статического метода `App.getInstance()`.

* `Connection` - позволяет выполнять логин и логаут пользователя на Middleware.

* `PortalSession` - специфический для портала объект <<userSession,пользовательской сессии>>. Возвращается интерфейсом инфраструктуры <<userSessionSource,UserSessionSource>>, а также статическим методом `PortalSessionProvider.getUserSession()`.
+
Имеет дополнительный метод `isAuthenticated()`, возвращающий `true`, если данная сессия принадлежит неанонимному, т.е. явно зарегистрировавшемуся с логином и паролем, пользователю.
+
При первом обращении некоторого пользователя к порталу `SecurityContextHandlerInterceptor` создает для него (или привязывает уже имеющуюся) анонимную сессию, регистрируясь на Middleware с именем пользователя, указанным в свойстве приложения <<cuba.portal.anonymousUserLogin,cuba.portal.anonymousUserLogin>>. Регистрация производится методом <<login,loginTrusted()>>, поэтому в блоке портала необходимо установить также свойство <<cuba.trustedClientPassword,cuba.trustedClientPassword>>. Таким образом, любой анонимный пользователь портала может работать с сервисами Middleware с правами пользователя `cuba.portal.anonymousUserLogin`.
+
Если портал содержит страницу регистрации пользователя с именем и паролем, то после выполнения `Connection.login()` при обработке запросов `SecurityContextHandlerInterceptor` устанавливает в потоке выполнения пользовательскую сессию явно зарегистрированного пользователя, и работа с Middleware происходит от его имени.

* `PortalLogoutHandler` - обрабатывает навигацию на страницу логаута. Должен быть зарегистрирован в файле `portal-security-spring.xml` проекта.

