:sourcesdir: ../../../source

[[rest_api_v2]]
=== REST API

Универсальный REST API предоставляет следующую функциональность:

* CRUD операции над сущностями.
* Выполнение предопределенных JPQL запросов.
* Вызов методов сервисов.
* Получение метаданных (сущности, представления, перечисления, типы данных).
* Получение разрешений для текущего пользователя (доступ к сущностям, атрибутам, специфические разрешения).
* Получение информации о текущем пользователе (имя, язык, временная зона и т.д.).
* Загрузка и скачивание файлов.

REST API использует протокол OAuth2 для аутентификации и поддерживает анонимный доступ.

[TIP]
====
Подробная документация по REST API написана согласно спецификации http://swagger.io/specification[Swagger] и доступна по следующему адресу: {rest_swagger_url}.

Кроме того, любое запущенное приложение на CUBA экспортирует специфичную для проекта документацию, см. <<rest_swagger,>>.
====

Раздел <<rest_api_v2_usage_example>> сборника рецептов содержит большое количество примеров, демонстрирующих возможности REST API в действии.

В разделах ниже приведено формальное описание некоторых особенностей и конфигурационных параметров.

include::rest_api_v2/rest_api_v2_queries_config.adoc[]

include::rest_api_v2/rest_api_v2_services_config.adoc[]

include::rest_api_v2/rest_api_v2_data_model_versioning.adoc[]

include::rest_api_v2/rest_api_v2_cors.adoc[]

include::rest_api_v2/rest_api_v2_anonymous.adoc[]

include::rest_api_v2/rest_api_v2_settings.adoc[]

include::rest_api_v2/rest_api_v2_custom_controllers.adoc[]

include::rest_api_v2/rest_api_v2_security_constraints.adoc[]

include::rest_api_v2/rest_api_v2_persistent_token_store.adoc[]

include::rest_api_v2/rest_swagger.adoc[]

