:sourcesdir: ../../../../source

[[polymer_manual__advanced__mixins]]
==== Mixins

Inheritance in Polymer is implemented with so called *mixins*. A mixin is a set of methods, properties, observers and lifecycle callback methods that can be inherited by any Polymer component.

Each web component can use any number of mixins. Web components can use mixins' methods and properties as if they were
their own. And mixins can use web components' methods and properties.

Below is an example demonstrating how to write and use mixins. It's a spelling improvement program that offers
a user to type a word. If the user fails to spell it correctly then the input will be highlighted with red. On any typing
the highlighting will be removed. Logic for setting/removing error state in the component is implemented by a mixin called
`ValidatedElementMixin`.

*Spelling checker*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/mixins/spelling-checker.html">

<div class="polymer-demo-container">
    <spelling-checker word="Elephant"></spelling-checker>
</div>

++++

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/mixins/spelling-checker.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <spelling-checker word="Elephant"></spelling-checker>
</body>
</html>
----

.src/polymer-advanced/mixins/spelling-checker.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/mixins/spelling-checker.html[]
----

.src/polymer-advanced/mixins/input-with-validation.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/mixins/input-with-validation.html[]
----

.src/polymer-advanced/mixins/validated-element-mixin.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/mixins/validated-element-mixin.html[]
----

`input-with-validation` represents a common UI component that supports validation.
`ValidatedElementMixin` can be used with other types of elements: comboboxes, text areas, radio-buttons, etc.

[TIP]
====
Please note what we marked the `value` property in `input-with-validation.html` with the `notify` attribute.
It's a necessary detail if want to allow clients of this element to use this property with 2-way binding.
====

In this example, we used just one mixin, but it's possible to use any number of mixins by including them one into another.
For example, we could create something like that:

[source, javascript]
----
class PowerfulInput extends ElementWithDebounceMixin(SelfPersistedElementMixin(ValidatedElementMixin(Polymer.Element)))
----

[TIP]
====
Please note that prior to version 2.0, Polymer used so called *behaviors* instead of mixins. They are elements
similar to mixins with the same purpose and possibilities but using another syntax for creation and usage.
You don't need to create or use behaviors in your code but you might encounter them in third-party components.
See more details in https://www.polymer-project.org/1.0/docs/devguide/behaviors.
====

What we have learned so far::
+
--
* We can use mixins to implement some common logic and share it between components.

* Mixins can contain methods, properties, lifecycle callback methods and observers.

* After extending a mixin, a Polymer component doesn't know which properties/methods are inherited and which are not.
So, the component treats them the same.

* In order to allow some property to be used by clients in two-way binding, we have to mark it with the `notify` parameter.
--

