:sourcesdir: ../../../../source

[[polymer_manual__advanced__computed]]
==== Computed Properties

Sometimes you may need properties that depend on other properties. For example, you have properties `firstName`, `lastName`
and also need property `fullName` that concatenates first and last names.
Or you have a boolean property that defines if a button is enabled or disabled, and this property depends on a number of other properties.

Obviously, you shouldn't manually change a value for such synthetic properties, it should be calculated automatically. Luckily, Polymer provides so called computed properties, and below is an example of using them.

*Source code*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/polymer-advanced/computed-properties/service-agreement.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <service-agreement></service-agreement>
</body>
</html>
----

.src/polymer-advanced/computed-properties/service-agreement.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/polymer-advanced/computed-properties/service-agreement.html[]
----

*Result*
[subs="none"]
++++

<link rel="import" href="html/src/polymer-advanced/computed-properties/service-agreement.html">

<div class="polymer-demo-container">
    <service-agreement></service-agreement>
</div>

++++

In this example, users cannot submit a form until they type in their name and accept an agreement.

It's essential to specify what properties we depend on. You cannot just type `computed: "isContinueEnabled()"` and then use `this.name` and `this.agreementConfirmed` in the `isContinueEnabled` method, because then Polymer won't know what properties we depend on and it won't re-calculate a computed property when required.

What we have learned so far::
+
--
* We can use computed properties when we need some information that can be calculated based on other properties.
--

