:sourcesdir: ../../../../../source

[[polymer_offline]]
===== Offline Capabilities

[WARNING]
====
Experimental!

The technologies listed below are not supported by all browsers yet (e.g. service workers are https://jakearchibald.github.io/isserviceworkerready[not yet implemented] in Safari).
====

Currently, together with the Polymer we offer to use https://developers.google.com/web/progressive-web-apps/[Progressive Web Applications] techniques such as https://developer.mozilla.org/en-US/docs/Web/Manifest[web app manifest] https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/[2] to have *native-like* presence on the user's home screen. See the `manifest.json` file in Polymer client module.

There are two main approaches:

* Service Workers which primarily used to cache the app itself.
Take a look at `sw-precache-config.js` file generated with Polymer client.
In order to enable service worker generation set `"addServiceWorker": true` in `polymer.json`.

More info on how to setup and use service workers can be found
https://polymer-library.polymer-project.org/2.0/toolbox/service-worker[here].

* https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage[Local storage] and https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API[Indexed DB] which used to store data locally.
This functionality exposed in the corresponding Polymer elements:
https://www.webcomponents.org/element/PolymerElements/app-storage?active=app-localstorage-document[app-localstorage-document]
https://www.webcomponents.org/element/PolymerElements/app-storage?active=app-indexeddb-mirror[app-indexeddb-mirror].

